### ISSUE TITLE
服务删除后，ServiceRegistryClient还一直从注册中心周期获取服务信息，导致大量异常信息

### ISSUE THREAD

**Issue by Fangfeikun** [apache/servicecomb-java-chassis#1003]
![image](https://user-images.githubusercontent.com/12439957/48930213-01a42680-ef2a-11e8-8728-6aab99329556.png)
注册中心的服务被删除后，或者服务多久没有被访问，sdk应该移除该服务的注册信息，不再周期获取该服务的信息，下一次再次被访问时，再重新获取该服务的注册信息

**Comment by Fangfeikun** [comment]
`2018-11-23 00:36:11.179 ERROR 1 --- [erListUpdater-1] o.a.s.s.r.AbstractServiceRegistry        : Can not find any instances from service center due to previous errors. service=default/e0c4472f-9598-42cf-948b-069f35030c1a/0.0.0+
2018-11-23 00:36:11.179  INFO 1 --- [erListUpdater-1] o.a.s.s.c.MicroserviceVersions           : create MicroserviceVersionRule, appId=default, microserviceName=e0c4472f-9598-42cf-948b-069f35030c1a, versionRule=0.0.0+.
2018-11-23 00:36:11.179  INFO 1 --- [erListUpdater-1] o.a.s.s.c.MicroserviceVersions           : create MicroserviceVersions, appId=default, microserviceName=0e736c27-c6ce-4690-b78b-4bb663a3aabb.
2018-11-23 00:36:11.180  WARN 1 --- [ntloop-thread-0] o.a.s.s.c.h.ServiceRegistryClientImpl    : {"errorCode":"400012","errorMessage":"Micro-service does not exist","detail":"provider does not exist, consumer 6848338eedfc11e89c1f0255ac109680 find service /default/d4f3f776-3b6b-4603-ab93-720e7fd7f67f/0.0.0+"}`

**Comment by Fangfeikun** [comment]
应该要有移除机制，一是，减少性能损坏，再者，不会出现大量的异常信息

**Comment by Fangfeikun** [comment]
![image](https://user-images.githubusercontent.com/12439957/48931104-88a7cd80-ef2f-11e8-8b18-45a8105fd0cf.png)
服务被删除之后，静态信息是不存在的，如果排除是注册中心的异常，那么只有一种情况，就是用户手动删除了该服务，因此，这种情况下，不应该再刷新该服务的注册信息。

**Comment by jeho0815** [comment]
@Fangfeikun  服务删除了，后面不会重新注册调用了？

**Comment by liubao68** [comment]
你使用的是哪个版本？记得服务被删除后，还会查询实例信息是很早之前的一个问题，最新版本已经修复过了的。 

另外，对于长期没有访问的服务，是否需要保留缓存，这个问题目前看没性能影响，修改的意义不是很大。 以为“保留的信息是被检查过的信息”，这些信息内容一般都很少，也不存在恶意使用的可能。

**Comment by sxcooler** [comment]
我也遇到这个问题，我在sc frontend把服务删除了，但是gateway（zuul）还一直在找他们，大量报错
<img width="1169" alt="serviceregistryclientimpl" src="https://user-images.githubusercontent.com/3192045/53932051-bc6bc500-40d2-11e9-91ba-b4969fc229ca.png">
我用的sc版本是docker image latest，java-chassis版本是1.1.0

**Comment by wujimin** [comment]
看起来资源在不断创建和删除，是不是不断有关于这个被删除的微服务的请求进来？

**Comment by sxcooler** [comment]
@wujimin 应该没有，我是开发机localhost起的sc，启动的就gateway和user两个服务，其他服务也不该有请求。

**Comment by wujimin** [comment]
build a test case to verity this problem, but can not reproduced
do you mind provide a reproduce project? thanks.

![image](https://user-images.githubusercontent.com/16874843/54098809-1630ff80-43f1-11e9-8c7b-f635001a74da.png)

**Comment by sxcooler** [comment]
@wujimin 我大概知道是什么原因了，这个问题只出现在gateway（基于zuul）里，因为我使用了ribbon的eager-load（为了解决第一次请求加载很慢的问题），所以它会一直寻找我设置了路由的所有服务。
这个大概解决不了，因为这不是一个bug。

**Comment by liubao68** [comment]
Clear long time not updated issue. Please feel free to submit a new one if problem happended again.
