### ISSUE TITLE
spring-boot-starter命名建议

### ISSUE THREAD

**Issue by zxcstc1256** [apache/servicecomb-java-chassis#1034]
根据Spring官方文档[docs.spring.io](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-auto-configuration.html#boot-features-custom-starter-naming)关于自定义starter命名部分，非官方的starter命名建议为{name}-spring-boot-starter，建议命名为servicecomb-spring-boot-starter
友商命名参考：
> https://github.com/Microsoft/azure-spring-boot
> https://github.com/mybatis/spring-boot-starter
> https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter

**Comment by liubao68** [comment]
谢谢指出， 我们考虑下如何改进。

**Comment by liubao68** [comment]
I add a [PR](https://github.com/apache/servicecomb-java-chassis/pull/1439) for this issue

**Comment by liubao68** [comment]
fixed in master(2.0.0-SNAPSHOT)
