### ISSUE TITLE
use servicecomb to realize multicast

### ISSUE THREAD

**Issue by ctlove0523** [apache/servicecomb-java-chassis#1044]
I want use servicecomb to realize multicast(client one call,all server instances receive the call).But,i find the calss `Invocation`‘s method `    public void next(AsyncResponse asyncResp) throws Exception {
        int runIndex = this.handlerIndex++;
        ((Handler)this.handlerList.get(runIndex)).handle(this, asyncResp);
    }`
check the index,so it invoke a `IndexOutOfBoundsException`.

Help me,thanks~

**Comment by wujimin** [comment]
multicast by RPC is not a good idea
think about there are 100 server instances:
  - the latency of this invocation ?
  - some of sub invocation failed by net problem/server instance offline or restart and so on

can you describe your business requirement, not technical requirements？

**Comment by liubao68** [comment]
Implement multicast in RPC is not a good idea, because it's very hard to make this application work as strong enough as you expected. Maybe you can find some publish/subscribe models to do this.

**Comment by liubao68** [comment]
Clear long time not updated issue. Please feel free to submit a new one if problem happended again.
