### ISSUE TITLE
Upgrading Zipkin 2.4.2 to Zipkin 2.11.12, should we remain the earlier version suporting?

### ISSUE THREAD

**Issue by bettermanzzy** [apache/servicecomb-java-chassis#1057]
Now, I am going to upgrade the version of zipkin supporting in java-chassis.

Version of the zipkin kit supported in Java-Chassis now,
Brave 4.13.1, zipkin 2.4.2, zipkin-reporter 2.2.2. 
Version of the zipkin kit that I am going to upgrade to,
Brave 5.6.0, zipkin 2.11.12, zipkin.java 2.10.1, zipkin-reporter 2.7.13.  

In the new zipkin kit , there are some APIs have been deprecated, such as, MDCCurrentTraceContext, StrictCurrentTraceContext, etc. Therefore, if I upgrade it, the Java-Chassis could not support the earlier one. Should I remain the related code of earlier zipkin in Java-Chassis?

To my opinion, I just have to upgrade it through replace the earlier zipkin kit with new one. In that way, the Java-Chassis can only support the zipkin 2.11.12 but not zipkin 2.4.2.

What about other's opinion?please feel free to let me know.

**Comment by jasononion** [comment]
I prefer to upgrade the zipkin kit because the new version supports Open Tracing which is widely adopted in other develop frameworks, thus servicecomb can easily match the tracing protocal of other applicaitions.

**Comment by liubao68** [comment]
It looks fine to upgrade the component. Zipkin support is quite a independent module in java chassis, better default to use some latest protocol and users can use ths old one with little modification bases on the default implementation.

**Comment by zenlinTechnofreak** [comment]
@liubao68 
What I concern about it is that we should keep ServiceComb compatible with the latest version of the surrounding ecosystem. Software in the ecosystem will often release new versions,  if we remain the elder code each time, we will grow strange, In that way,Java-Chassis will have code with Zipkin 2.11.12, Zipkin 2.4.2, and Zipkin 3.x.x in the near future.

Therefore, what about just keep it compatible with the latest version of the software in the surrounding ecosystem?

**Comment by liubao68** [comment]
@zenlinTechnofreak 
Most of time we only keep compatible with the latest version. However there are exceptions, e.g. we will keep work with spring 4/spring 5 for a quite a long time. 
Compatibility is sometimes a hard decision to make, we receive many complaints from users when imcompatible changes are made. However, we will keep going forward to make it a better environment.

**Comment by bettermanzzy** [comment]
@liubao68 @zenlinTechnofreak 
Do you mean as following,
handlers
├── handler-bizkeeper
├── handler-fault-injection
├── handler-flowcontrol-qps
├── handler-loadbalance
├── handler-publickey-auth
├── handler-tracing-zipkin 
├── handler-tracing-zipkin-2.11.12
└── pom.xml
Treat handler-tracing-zipkin  as default version(2.4.2), and handler-tracing-zipkin-2.11.12 ad as the newest.

I am not sure weather I have got correctly what you mean.
Thanks for help.

**Comment by liubao68** [comment]
@bettermanzzy For zipkin integration, servicecomb will keep only one version, I'd prefered to upgrade to 2.11.12. However, I checked some constraints for using this version, we can only upgrade to 2.9.3. I am afraid we can not modify this issue sooner as you expect.

**Comment by liubao68** [comment]
@bettermanzzy We have a lot of evalutions need to be done when introduce new softwares, and all versions is managed by third party system. Evalutions include licenses, bugs, vulnerablities and users preference. It'll take a quite a time to finish all these stuffs.

**Comment by bettermanzzy** [comment]
@liubao68 Ok, are we sure to upgrade to 2.9.3 version of zipkin? I have checked the dependencies with brave. if we use zipkin 2.9.3 , we can upgrade brave to 5.1.0 and  zipkin-reporter to 2.7.13.  Can we upgrade this in java chassis?

**Comment by liubao68** [comment]
fixed in https://github.com/apache/servicecomb-java-chassis/pull/1064
