### ISSUE TITLE
edge service转发请求给后端服务，后端服务契约注册有误，枚举参数有误，导致edge service报错

### ISSUE THREAD

**Issue by 13602470081** [apache/servicecomb-java-chassis#1068]
edge报错
![1](https://user-images.githubusercontent.com/46912794/51510228-36076680-1e37-11e9-9b45-64ae2e052071.png)

原因是后端服务注册的契约对于枚举处理有误：
![image](https://user-images.githubusercontent.com/46912794/51510242-4b7c9080-1e37-11e9-8ea0-6e5bec7586f8.png)
实际上应该注册的是H.264

**Comment by yhs0092** [comment]
你好，这个issue已经在 [https://github.com/apache/servicecomb-java-chassis/pull/1073]() 里修复了。也许你可以看看它是否符合你的预期。
