### ISSUE TITLE
business-service-pojo-archetype生成项目问题

### ISSUE THREAD

**Issue by sxcooler** [apache/servicecomb-java-chassis#1071]
business-service-pojo-archetype 版本1.1.0，生成的项目不能直接运行，有两个问题，一是需要配置log4j，这个应该还好。
但另一个问题是provider.bean.xml里的xsi:schemaLocation少配了http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd 这个定义，导致报错cvc-elt.1: 找不到元素 'beans' 的声明

BTW.
http://servicecomb.apache.org/cn/users/develop-with-transparent-rpc/ 这篇文档我只从archetype生成的项目的readme里找到，网站上似乎没有入口，看上去比https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/transparent-rpc.html 这篇更详尽。

**Comment by wujimin** [comment]
多谢指出问题，有一个PR在解决这个问题了：https://github.com/apache/servicecomb-java-chassis/pull/1070

1.provider.bean.xml可以直接删除，只有之前的版本才必须要这个文件，当前版本Main class所在package会自动加到扫描路径去，不通过bean文件声明了
2.log4jUtils.init可以删除，这是扩展的支持配置增量生效的log4j，但是不是必须使用它
  按标准方式使用logback，或是log4j2，或是log4是，都是ok的
3.文档我们将持续优化

**Comment by sxcooler** [comment]
抱歉我在issue里搜了没搜到才发的，没想到还是发重了，多谢释疑。
