### ISSUE TITLE
【求助】Edge Service如何转发非微服务的请求

### ISSUE THREAD

**Issue by willard-kali** [apache/servicecomb-java-chassis#1079]
现在有个应用场景，需要通过Edge Service，将浏览器发过来的请求，按照普通的tomcat的REST接口进行转发（类似nginx反向代理的功能），而不是转发给其他的微服务。
我看过相关的demo程序了，在dispatcher或者handler以及httpserverfilter里边加都有困难（传入参数是invocation或者context这种），和原生的httpservletrequest和httpservletresponse差异较大。
请问当前是否有可行方案满足这个场景？

**Comment by liubao68** [comment]
https://github.com/huaweicse/cse-java-chassis-samples/blob/master/porter/gateway-service/src/main/java/com/huawei/cse/porter/gateway/UiDispatcher.java  或许这个例子可以参考下。

**Comment by willard-kali** [comment]
这个确实有帮助，问题解决了。感谢！
