### ISSUE TITLE
how can i run local registy

### ISSUE THREAD

**Issue by liangyuanpeng** [apache/servicecomb-java-chassis#1089]
i try to run ``SpringmvcProviderMain#main``  

but i got some error of   
```
2019-02-05 13:47:39,846 [INFO] Change service center address from 127.0.0.1:30100 to 127.0.0.1:30100 org.apache.servicecomb.serviceregistry.client.IpPortManager.getNextAvailableAddress(IpPortManager.java:100)

```  

how can i run this registry about ``127.0.0.1:30100``

**Comment by liangyuanpeng** [comment]
I just want to get started quickly  

maybe modules of ``demo`` can be solve my problem

**Comment by willard-kali** [comment]
servicecomb need to start service center first.
see https://servicecomb.apache.org/cn/users/setup-environment/

**Comment by liubao68** [comment]
Clear long time not updated issue. Please feel free to submit a new one if problem happended again.
