### ISSUE TITLE
请教LocalDateTime的输出形式能否自定义

### ISSUE THREAD

**Issue by sxcooler** [apache/servicecomb-java-chassis#1095]
例如我有一个字段createTime在数据库里是timestamp，在实体里定义的是LocalDateTime，@RestSchema直接return的话，在浏览器看到是这样的：
![image](https://user-images.githubusercontent.com/3192045/52781545-cd06bd80-3087-11e9-96ae-7f85ef8ebd8a.png)
但是我用fastjson序列化输出到console是这样的：`"createTime":"2019-02-11T15:15:32"`
请教这个能否自定义？我希望输出像fastjson那样，或者我可以用DateTimeFormatter自定义更好。
btw，如果这个字段在实体里定义为String，则输出是这样的：`2019-02-11  15:15:32.0`

**Comment by liubao68** [comment]
使用ServiceComb的最佳实践里面，不推荐业务定制序列化方式，以保障所有通过代码声明生成的契约的语义都是一致的。 
提这类问题一般都发生在遗留代码，需要保持老系统接口兼容的场景。 
你提的问题实际上就提供了一种解决思路： 
首先定义一个需要输出的json格式，比如 class Time{String createTime}
或者返回String， 自己序列化。 当然还可以参考RestObjectMapperFactory.setDefaultRestObjectMapper自定义RestObjectMapper，不过这个过程稍微复杂一些，也可能会有其他一些涉及到语义的兼容性问题。

**Comment by sxcooler** [comment]
@liubao68 大概明白了，多谢。
