### ISSUE TITLE
It seems that there is a conflict between handler-bizkeeper  and spring cloud hystrix  

### ISSUE THREAD

**Issue by kakulisen** [apache/servicecomb-java-chassis#1097]
Hi, I have tried to use spring-cloud-hystrix in my web project with ServiceComb-java-chassis.
When I use HystrixCommand like below, it does not work
```
    @HystrixCommand(
            fallbackMethod = "errorHandler",
            commandProperties = {
                    @HystrixProperty(name = "execution.isolation.thread.timeoutInMilliseconds", value = "1000")
            }
    )
```

Here is my pom.xml
```xml
       <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-hystrix</artifactId>
            <version>1.4.4.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.apache.servicecomb</groupId>
            <artifactId>spring-boot-starter-provider</artifactId>
            <version>1.1.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.servicecomb</groupId>
            <artifactId>spring-boot-starter-discovery</artifactId>
            <version>1.1.0</version>
        </dependency>
```

I found that spring-boot-starter-provider have a transitive dependencies handler-bizkeeper.
I exclude it in my pom, then anything is right
```xml
        <dependency>
            <groupId>org.apache.servicecomb</groupId>
            <artifactId>spring-boot-starter-provider</artifactId>
            <version>1.1.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.servicecomb</groupId>
                    <artifactId>handler-bizkeeper</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

It seems that there is a conflict between handler-bizkeeper  and spring-cloud-hystrix . Is there any other way to solve this problem?

**Comment by liubao68** [comment]
There are differences between the runtime logic of ServiceComb (REST transport )& Spring Cloud(Spring MVC Rest framework) . Here have a document to refer to :　https://bbs.huaweicloud.com/blogs/02de5f11cb6e11e8bd5a7ca23e93a891

You can use hystrix by include handler-biazkeeper without any code, this doc shows the concepts and configuration items: https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/configuration/downgrade-strategy.html

**Comment by liubao68** [comment]
Clear long time not updated issue. Please feel free to submit a new one if problem happended again.
