### ISSUE TITLE
【求助】使用Edge Service在zipkin无法显示依赖关系。  

### ISSUE THREAD

**Issue by myVictor** [apache/servicecomb-java-chassis#1103]
按照用户使用手册“使用Edge Service做边缘服务”做了一个边缘服务器，方式为URLMappedEdgeDispatcher，路由功能是正常的，但是在Zipkin监控页面无法显示依赖关系。
![image](https://user-images.githubusercontent.com/7285684/53221933-9859be00-36a6-11e9-89ee-c71841bbb591.png)
服务是正常显示的。
![image](https://user-images.githubusercontent.com/7285684/53221944-a576ad00-36a6-11e9-8ca1-02963438dbe0.png)
依赖关系无法显示，这是什么原因？

**Comment by myVictor** [comment]
![image](https://user-images.githubusercontent.com/7285684/53224985-84678980-36b1-11e9-817f-4e94b0530704.png)
用zuul做就能显示。

**Comment by liubao68** [comment]
你是使用了handler-tracing对接zipkin吗？ 这个是在handler执行的。 edge service只执行consumer handler chain，没有provider chain，可能存在你说的情况。如果是这种场景的话， 我们需要验证下，看是否能够优化。

**Comment by myVictor** [comment]
不好意思，我也是刚刚接触这个框架。我开始按照快速入门通过跑了demo程序（体质指数），然后通过zipkin监控页面查看依赖能显示一个依赖关系图。然后按照用户操作自己做了个Edge Service边缘服务，测试调用功能是没问题的。再看依赖关系没有关系图，但是通过查找可以发现有两个服务。

另外所有的操作都是按照用户手册做的，我应该用的是handler-tracing对接zipkin的。下图是的边缘服务器配置。
![image](https://user-images.githubusercontent.com/7285684/53241566-f903ed80-36dc-11e9-9104-b7c841b87ac1.png)

**Comment by WillemJiang** [comment]
不知道是不是EdgeService 把需要传递调用关系的header给过滤掉了。

**Comment by wujimin** [comment]
i try this right now, there is no problem.
![image](https://user-images.githubusercontent.com/16874843/53244635-7122e100-36e6-11e9-9ddf-397d826e5621.png)


maybe you missed declare zipkin in microservice.yaml?
```
  handler: 
    chain: 
      Consumer: 
        default: tracing-consumer,loadbalance
      Provider: 
        default: tracing-provider
```

**Comment by wujimin** [comment]
you declare tracing-provider for Consumer, but it should be "tracing-consumer"

**Comment by myVictor** [comment]
> you declare tracing-provider for Consumer, but it should be "tracing-consumer"
谢了哈，是这个原因。
