### ISSUE TITLE
生成契约时没有考虑继承泛型接口时生成的桥方法

### ISSUE THREAD

**Issue by demonbug** [apache/servicecomb-java-chassis#1104]
https://github.com/apache/servicecomb-java-chassis/blob/f3ec3889cedbb3c55be2d1dd60bf646da26ff3a5/swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/SwaggerGenerator.java#L263

`public interface A extends B<C>`
会生成
A.xxx(C)和A.xxx(Object)两个方法，导致契约注册冲突

**Comment by wujimin** [comment]
yes, should filter such methods

**Comment by wujimin** [comment]
do you mind submit a PR for this?

**Comment by wujimin** [comment]
https://issues.apache.org/jira/browse/SCB-1165

**Comment by wujimin** [comment]
do you have a jira account?
i will set "Assignee" to you, and close the task.

https://issues.apache.org/jira/browse/SCB-1165
