### ISSUE TITLE
JDK升级8U191之后，容器内线程数变少了，是否可以开放参数设置

### ISSUE THREAD

**Issue by zhangfeng751** [apache/servicecomb-java-chassis#1112]
JDK 8U191支持容器特性
![image](https://user-images.githubusercontent.com/17715446/53573673-f0158f00-3ba8-11e9-8070-de2f4cda50c8.png)
，服务比较多，不想每个服务都加上这个启动参数，想在包装的时候默认修改这个配置。类似如下的可以参数设置线程池大小，
![image](https://user-images.githubusercontent.com/17715446/53573780-310da380-3ba9-11e9-8949-c4ccf7af54d4.png)

但是也有vert.x类似这种获取CPU使用，是否可以开放API设置java-chassis底层使用的VertxOptions 参数
![image](https://user-images.githubusercontent.com/17715446/53574181-0243fd00-3baa-11e9-8253-ccb1c338c691.png)

**Comment by zhangfeng751** [comment]
java-chassis有多处使用VertxOptions的地方
![image](https://user-images.githubusercontent.com/17715446/53705475-c0dc7780-3e5f-11e9-975c-3b4d79082e0e.png)

**Comment by wujimin** [comment]
一般来说，eventloop逻辑，不需要去调整这个参数，cpu资源就那么多，再调整也没什么用
除非像样在eventloop中执行了不允许的：大循环/阻塞等待等等动作

**Comment by liubao68** [comment]
Check https://docs.servicecomb.io/java-chassis/zh_CN/transports/rest-over-vertx.html


Clear long time not updated issue. Please feel free to submit a new one if problem happended again.
