### ISSUE TITLE
与Skywalking 6 GA整合发生错误！

### ISSUE THREAD

**Issue by vanlin** [apache/servicecomb-java-chassis#1114]
与skywalking6整合时 启用 apm-spring-annotation-plugin-6.0.0-GA.jar 插件

AbstractSchemaFactory 类 使用 @Inject 方法注入失败 schemaLoader 为 null 不能工作
```java
  @Inject
  public void setSchemaLoader(SchemaLoader schemaLoader) {
    this.schemaLoader = schemaLoader;
  }
```

如果 @Inject 放到  protected SchemaLoader schemaLoader;  Field 会不会影响逻辑？

**Comment by vanlin** [comment]
已经在 Skywalking 提交 issue  https://github.com/apache/incubator-skywalking/issues/2308

**Comment by WillemJiang** [comment]
I just checked the status of the issue in skywalking,  it has been fixed, so I close this issue.
