### ISSUE TITLE
Java-chassis用户手册中配置项映射定义文件应该是mapping.yaml

### ISSUE THREAD

**Issue by xiaojunl** [apache/servicecomb-java-chassis#1117]
进行配置项映射链接：https://docs.servicecomb.io/java-chassis/zh_CN/general-development/config.html
描述语句：“可以通过classpath下的config.yaml进行映射定义” 应改为“可以通过classpath下的mapping.yaml进行映射定义”

**Comment by wujimin** [comment]
do you mind raise a PR for this? thanks.
https://github.com/apache/servicecomb-docs

**Comment by xiaojunl** [comment]
I didn't find the Issues.
![Uploading 20190311114402.jpg…]()

**Comment by wujimin** [comment]
oh
moved to:
https://github.com/apache/servicecomb-docs/blob/master/java-chassis-reference/zh_CN/config/general-config.md
https://github.com/apache/servicecomb-docs/blob/master/java-chassis-reference/en_US/config/general-config.md

**Comment by wujimin** [comment]
thanks for your PR, already merged.
