### ISSUE TITLE
近期遇到的坑一览

### ISSUE THREAD

**Issue by sxcooler** [apache/servicecomb-java-chassis#1121]
总体而言还是文档不够完善，对新人不够友好，以下是我近期遇到的一些问题：

- 首先是gateway项目，用zuul做边缘服务的话，官方文档是这一篇https://docs.servicecomb.io/java-chassis/zh_CN/edge/zuul.html ，但是没提到依赖org.apache.servicecomb.spring-boot-starter-servicecomb 这个starter（比如我用官方的archetype建的项目，是没有这个依赖的，只有spring-boot-starter-provider），启动直接就会application fail to start错误，大概是这样：
![image](https://user-images.githubusercontent.com/3192045/53932235-9db9fe00-40d3-11e9-8506-3df90186910a.png)
于是我添加了spring-boot-starter-servicecomb，去掉了spring-boot-starter-provider，埋下了一个伏笔。

- 然后配置好路由以后大部分转发都好使了，偏偏有一个服务不行（服务都是一个模板搞起来的差别不是太大），遇到了https://www.twblogs.net/a/5c3a011ebd9eee35b21db163 这里面的“三”这个问题，就是如果不小心写了一个空的restSchema的话会导致Swagger Invocation报错，但是这个这么重要的问题却未见于任何官方文档或Q&A，要是没有这篇台湾同胞的blog我还在抓瞎。

- 接下来是配置认证服务，参考官方的Company例子，加好token鉴权filter以后发现，不过filter的请求比如login没问题，但是过filter的请求全部报错，一开始在被调用的微服务（user服务）里step by step调试，发现最终报错在某highway的文件里，于是想到之前遇到的transport使用混乱的问题（按官方文档两种transport都可用的时候将会轮流使用），将user服务里的highway协议禁用（microservice.yaml里注释掉），结果神奇的事情发生了，gateway报找不到可用的地址！类似这个问题https://jira.apache.org/jira/browse/SCB-407 ，折腾得我死去活来以后突然想起之前被我干掉的spring-boot-starter-provider（里面依赖了transport-rest-vertx），果断加上，问题解决（只是这个问题解决）。
分析原因：zuul直接转发的请求不依赖其他库，但我的pre-filter（上文所述认证鉴权），使用了restTemplate，却又没有transport-rest-vertx可用，它便去使用highway通路，而被调用服务实际没实现highway协议，导致了上述问题。

- 接着遇到了NoSuchMethodError: Status.Family.familyOf的问题，org.apache.servicecomb.foundation.common.http.HttpStatus 依赖了javax.ws.rs.core.Response.Status.Family，查依赖树如下：
![image](https://user-images.githubusercontent.com/3192045/53932287-d9ed5e80-40d3-11e9-99aa-09a473c74e7d.png)
本来是应该用上面这个的，但是由于不知道什么原因，它选择了用下面这个，导致familyOf方法找不到，而且由于这俩包名不一样，一般的检测冲突还检测不出来。
还记得我最开始说的那篇文档吗？https://docs.servicecomb.io/java-chassis/zh_CN/edge/zuul.html spring-boot-starter-discovery和spring-cloud-starter-ribbon我可是按文档引入的，有这么大个坑官方好歹提醒一下吧？

**Comment by liubao68** [comment]
谢谢你的反馈。 
问题2：这个问题已经修复和完善。参考案例https://bbs.huaweicloud.com/forum/thread-13817-1-1.html
问题3：spring boot/cloud相关组件集成方面支持的场景很多， servicecomb提供的starter也比较多，这块文档确实不太完善，对于不了解spring cloud DiscoveryTree工作原理的新开发者，确实非常难理解各个starter的作用。加上servicecomb支持了spring boot1和spring boot2，他们的starter设计方式差异也比较大。 这里有个文档说明：https://huaweicse.github.io/cse-java-chassis-doc/using-cse-in-spring-boot/using-cse-in-spring-boot.html  。 当然你提到的使用了highway转发，这个应该属于spring starter的bug，下来分析改进下。 记得spring boot1适配的时候，考虑过这个问题，不知道是不是代码遗漏了。 
问题5： 三方件依赖问题比较多，在ServiceComb社区微信号也问的最多。 这块目前没有直接的解决方法。 https://bbs.huaweicloud.com/forum/thread-14705-1-1.html 的备注里面有个理解maven dependency management的案例，理解maven管理依赖关系的机制后，解决这类问题会变得简单，可以了解下。

**Comment by sxcooler** [comment]
@liubao68 感谢回复，求加微信群……

**Comment by liubao68** [comment]
2.3.62对应的是华为发布的ServiceComb的商业版本。这个版本比ServiceComb发布版本的速度快一些， 先关RN说明参考： https://huaweicse.github.io/cse-java-chassis-doc/ 。 对于的ServiceComb某个commit版本，使用上一样。 

微信人数较多需要邀请才能够加入。 你可以给微信名称发我邮箱， 我邀请你。

**Comment by WillemJiang** [comment]
也可以在gitter 这打招呼 ，主要的开发人员都在上面。 https://gitter.im/ServiceCombUsers/Lobby

**Comment by sxcooler** [comment]
感谢两位

**Comment by spean90** [comment]
问题三，切换回spring-boot-starter-provider启动不会报问题一点那个错了吗？
