### ISSUE TITLE
edge如何转发请求给非servicecomb服务？如何扩展接入其他服务注册中心？

### ISSUE THREAD

**Issue by chenzj** [apache/servicecomb-java-chassis#1126]
请教几个问题：
1. 我现在有很多现有的服务，是直接使用的springmvc，我想在前面通过servicecomb-edge做为网关转发，能否类似nginx一样直接做url的rewrite?还是说一定需要将服务注册到SC？
2.  若一定需要将现有服务注册到SC，是否一定需要将Schema也注册到SC。使用edge，是否可以不需要知道后端服务的Schema?因为请求参数可以直接透传就ok了。
3. 如果需要接现有的其他服务注册中心，应该是需要扩展ServiceRegistry接口，但是这个接口貌似没有做出SPI的方式？我是只能通过修改service-registry模块的方式吗？

**Comment by liubao68** [comment]
你的问题涉及到edge-service的路由规则定制。 参考文档：https://docs.servicecomb.io/java-chassis/zh_CN/edge/by-servicecomb-sdk.html ，也可以参考servicecomb提供的默认Dispatcher怎么实现的，实现自己的。 下面几个DEMO中的实现可能有用：
无需schema的转发：https://github.com/huaweicse/cse-java-chassis-samples/blob/master/HouseAppWithSpringBoot2/edge-service/src/main/java/com/huawei/cse/houseapp/edge/WebPageDispatcher.java
重定向： https://github.com/huaweicse/cse-java-chassis-samples/blob/master/HouseAppWithSpringBoot2/edge-service/src/main/java/com/huawei/cse/houseapp/edge/RedirectToLoginDispatcher.java

**Comment by willard-kali** [comment]
如果需要在UI转发（httpClientRequest）之前，需要增加鉴权认证逻辑，请问如何能够实现？
我自己尝试了CseAsyncRestTemplate调用微服务并创建异步监听，监听成功的处理流程中进行http请求转发，然而却卡在了

**Comment by liubao68** [comment]
使用HttpServerFilter应该可以. servicecomb-fence有类似代码。 


Clear long time not updated issue. Please feel free to submit a new one if problem happended again.
