### ISSUE TITLE
Version dependency alarms when compiling with microservices (integrated springboot) generated by archetype

### ISSUE THREAD

**Issue by kakulisen** [apache/servicecomb-java-chassis#1145]
**Version**
ServiceComb javachassis version is 1.2.0-SNAPSHOT

**Environment**
windows10

**Describe the bug**
Version dependency alarms when compiling with microservices (integrated springboot) generated by archetype

**Expected result**
no warn

**Steps to reproduce the bug**
1. generate project
```
mvn org.apache.maven.plugins:maven-archetype-plugin:2.4:generate -DarchetypeGroupId=org.apache.servicecomb.archetypes -DarchetypeArtifactId=business-service-spring-boot-starter-archetype -DarchetypeVersion=1.2.0-SNAPSHOT -DarchetypeRepository=https://repository.apache.org/content/groups/snapshots-group
```
project artifactId: demo-jaxrs

2. 
```
cd demo-jaxrs
mvn spring-boot:run
```

**Comment by liubao68** [comment]
Is this issue related to https://github.com/apache/servicecomb-java-chassis/pull/1147?

**Comment by kakulisen** [comment]
Yes
