### ISSUE TITLE
车库咖啡，请问这个和springcloud家族有什么区别呢

### ISSUE THREAD

**Issue by lilyhuli** [apache/servicecomb-java-chassis#1146]
感觉没啥区别啊

**Comment by liubao68** [comment]
我有几个选型文章， 可以参考下. 后面两个可以帮助理解他们的差异。 

基于CSE的微服务架构实践-基础架构: https://bbs.huaweicloud.com/blogs/8bb2c3b8366c11e9bd5a7ca23e93a891
基于CSE的微服务架构实践-轻量级架构技术选型: https://bbs.huaweicloud.com/blogs/1be7166e371511e9bd5a7ca23e93a891
基于CSE的微服务架构实践-Spring Boot技术栈选型: https://bbs.huaweicloud.com/blogs/eca98a6f399a11e9bd5a7ca23e93a891
基于CSE的微服务架构实践-Spring Cloud技术栈选型: https://bbs.huaweicloud.com/blogs/e8e3deb63f1311e9bd5a7ca23e93a891

**Comment by liubao68** [comment]
Clear long time not updated issue. Please feel free to submit a new one if problem happended again.
