### ISSUE TITLE
关于rpc方式调用服务提供者的问题

### ISSUE THREAD

**Issue by Lvjingbo** [apache/servicecomb-java-chassis#1156]
demo和文档中，说可以通过
@RpcReference(microserviceName="techsuperVision", schemaId="StandardManagerService")
	private StandardManagerService service;
这样调用服务提供者；但在服务消费者中，并没有StandardManagerService 的定义和声明；根本无法引用；请问，我该如何在消费者中调用？

**Comment by heyile** [comment]
你说的根本无法引用什么意思? 你需要在consumer 提供一个类似的 interface
```

public interface Hello {

  String sayHi(String name);

  String sayHello(Person person);
}
```
然后才可以调用

```
  @RpcReference(microserviceName = "springmvc", schemaId = "springmvcHello")
  private static Hello hello;
public static void main(String[] args) throws Exception {
    BeanUtils.init();
    Person person = new Person();
    person.setName("ServiceComb/Java Chassis");

    // POJO Consumer
    System.out.println("POJO consumer sayhi services: " + hello.sayHi("Java Chassis"));
    System.out.println("POJO consumer sayhello services: " + hello.sayHello(person));
  }
```

详情可参考: https://github.com/apache/servicecomb-java-chassis/tree/master/samples/springmvc-sample

**Comment by Lvjingbo** [comment]
参照文档定义了接口
public interface TestService {

    @ApiOperation(nickname = "testService", value = "reactive method for testService")
    CompletableFuture<String> testService();
}

消费端调用
@RestSchema(schemaId = "hello")
@RequestMapping(path = "/")
public class HelloImpl {

    @RpcReference(microserviceName="techsuperVision", schemaId="StandardManagerService")
    private TestService service;
    @GetMapping(path = "/hello")
    public String hello() {
        return "Hello World!";
    }

    @GetMapping(path = "/test")
    public String test() {
        System.out.println(service.testService());
        return service.testService().toString();
    }
}
测试/test契约，报错找不到服务提供者

**Comment by heyile** [comment]
@Lvjingbo  provider启动并成功注册到服务中心了吗 ?

**Comment by Lvjingbo** [comment]
就是在注册中心测试的契约；提供者的接口正常，消费者这边不行

**Comment by heyile** [comment]
@Lvjingbo  啥意思, 正常的运行逻辑是 provider 启动,把自己注册到 服务中心. 然后consumer 通过服务中心发现 provider, 再远程调用.  整个流程有什么出入吗? 或者你可以给一个demo 吗 ? 我用你的provider和 consumer 试一下看是啥问题

**Comment by Lvjingbo** [comment]
稍等

**Comment by Lvjingbo** [comment]
搞定了，provider 配置文件microservice.yaml中 environment: development；consumer的配置文件microservice.yaml中，必须也得加上environment: development才可以；这是什么原理？

**Comment by Lvjingbo** [comment]
https://docs.servicecomb.io/java-chassis/zh_CN/build-consumer/develop-consumer-using-rpc.html还有这里，讲到  只需要使用jdk的CompletableFuture对返回值进行包装即可； 这是干什么的？文档说的太简单了；说透明rpc的方式和spring cloud的feign类似；对于我这种没接触spring cloud的人说，完全不知道文档在讲什么；能麻烦解释一下吗？或者哪里有比较详细的解释说明

**Comment by heyile** [comment]
@Lvjingbo  多环境是隔离的.
https://docs.servicecomb.io/java-chassis/zh_CN/general-development/multienvironment.html

**Comment by heyile** [comment]
@Lvjingbo  一般开发也不会使用 CompletableFuture 对返回值进行包装, 这个只有在异步调用的时候才需要.  如果你现阶段没有异步调用的概念, 就直接 **String sayHi(String name);**. 和这个示例一样
https://github.com/apache/servicecomb-java-chassis/tree/master/samples/pojo-sample

```
interface Hello {
  String sayHi(String name);

  @ApiOperation(nickname = "sayHi", value = "reactive method for sayHi")
  CompletableFuture<String> asyncSayHi(String name);
}
```
feign 的话. 其实和你现在的demo 类似. 就是自定义一个 interface. 然后consumer可以通过 interface 远程访问 provider. 其实你没必要纠结 feign 咋样(实在想知道.可以网上搜下feign), 只要知道按照我们这个规则来,可以远程调用 provider, 能跑通就好了

**Comment by liubao68** [comment]
Clear long time not updated issue. Please feel free to submit a new one if problem happended again.
