### ISSUE TITLE
filter功能完善，dubbo在发布的时候支持不同的接口定义不同的filter

### ISSUE THREAD

**Issue by HoyerIsAlexander** [apache/servicecomb-java-chassis#1174]
filter功能完善，dubbo在发布的时候支持不同的接口定义不同的filter，但是servicecomb目前配置的filter是针对全局的，如果想区分得代码中逻辑区分或者使用edge或者zuul，开发起来比较麻烦，不知道时候有相关的计划

**Comment by liubao68** [comment]
ServiceComb的handler链支持不同的微服务设置不一样的处理链，在handler链里面能够获取到接口信息，可以对接口做治理，非常灵活的。你的具体应用场景能够简单描述下吗？看看是否有替换的或者更好的方案。

**Comment by liubao68** [comment]
场景对应的解决方案： https://bbs.huaweicloud.com/blogs/ee3811655ffb11e9bd5a7ca23e93a891
