### ISSUE TITLE
通过什么方法可以获取一个schema的type，rpc或者rest？

### ISSUE THREAD

**Issue by HoyerIsAlexander** [apache/servicecomb-java-chassis#1175]
通过什么方法可以获取一个schema的type，rpc或者rest？看了下相关的方法或者变量，好像无法保存这个信息，当前只能根据实现类的注解来判断？

**Comment by liubao68** [comment]
不管rpc或者rest， servicecomb的契约都是swagger，即都是rest。 你的应用场景是什么？区分这个的目的是啥？

**Comment by HoyerIsAlexander** [comment]
当前的场景是一个服务即提供rpc又提供rest，但是配置的filter是针对全局实现的，除非通过edge或者zuul来实现，这样就比较复杂，所以想获取调用的schema的type来区分

**Comment by liubao68** [comment]
"当前的场景是一个服务即提供rpc又提供rest" 这个具体是什么意思？是指有些接口用了@RpcSchema，有些用了@RestSchema？ 这个并没有本质的区别。是否为REST，取决于通信是否为HTTP。 
很多框架或者开发者对于rpc和rest的理解和ServiceComb的概念是不一样的。 通常我们说的REST指json编码+http通信， rpc则是所有远程通信的总称（但是有些框架将他定义为自定义编码（比如gRPC）+自定义通信协议）。 

总体上还是不理解你的场景。不知道方不方便从业务应用的角度讲讲需求。 这里有个关于ServiceComb的架构设计介绍，可以参考： https://bbs.huaweicloud.com/blogs/1fc9427c088611e89fc57ca23e93a89f

**Comment by liubao68** [comment]
该场景的解决方案: https://bbs.huaweicloud.com/blogs/ee3811655ffb11e9bd5a7ca23e93a891
