### ISSUE TITLE
关于service comb文档上的一些疑问和实际运用中的不符点

### ISSUE THREAD

**Issue by wpcchengxuyuan** [apache/servicecomb-java-chassis#1181]
因为最近在做一些网关性能对比，所以对1.1版本的service comb做了一个详细的测评，以下是个人的疑惑，望您解答。
1.负载均衡部分关于服务端配置tag的疑问。
文档是![image](https://user-images.githubusercontent.com/18682598/56103780-15970600-5f67-11e9-996c-70a3651f7666.png)
而实际代码中写死为
![image](https://user-images.githubusercontent.com/18682598/56105497-17fd5e00-5f6f-11e9-9a4e-2d8daf23ecbf.png)
2.关于transport-rest连接数问题，文档中给出为client.thread-count*client.maxPoolsize的乘积。
![image](https://user-images.githubusercontent.com/18682598/56105464-f603db80-5f6e-11e9-85f7-703827548f74.png)
我在实际操作过程中发现，如果server.thread-count>client.thread-count的乘积，则连接数为前者和maxPoolSize的乘积。因为是用ab压测工具采用1000并发直接压测网关服务，后端部署4个服务，所以应该能达到文档说的极限连接，然而后端服务连接数如图
![image](https://user-images.githubusercontent.com/18682598/56104964-a3c1bb00-5f6c-11e9-9bbf-5bf54b4cdfdf.png)。有一条是本身服务的监听连接，则有45条和网关的连接。
网关配置如图
![image](https://user-images.githubusercontent.com/18682598/56105004-dbc8fe00-5f6c-11e9-8551-b1885e40ab7d.png)。client.thread-count*maxPoolSize=24,server.thread-count*maxPoolSize=45。显然和文档不符，我猜测是由于服务本身又作为客户端又作为服务端，而通讯采用长连，连接需要复用，因此选用最大的。这只是猜测，望您指点疑惑。
3.关于transport-rest网络线程数问题，文档指出为
![image](https://user-images.githubusercontent.com/18682598/56105276-ff407880-5f6d-11e9-8c81-5373846a092c.png)，应该就是核数*2，机器核数为40
![image](https://user-images.githubusercontent.com/18682598/56105318-33b43480-5f6e-11e9-8514-9eb7e51a09a6.png)，然而jstack将eventloop统计之后发现不为这个数字
![image](https://user-images.githubusercontent.com/18682598/56105371-7118c200-5f6e-11e9-9135-cf8be382f3e7.png)。然后也仔细的查看了jstack，除了eventloop没有其他的网络线程名称例如nio之类的。查看源码只发现服务作为server端时有一个accept线程，workEventLoop是通过addWork操作动态添加的。文档对于这部分貌似也不是正确的描述，希望您大致的指导解释一下。

**Comment by wujimin** [comment]
赞，看文档很仔细

1. 写死的是读取tags的key，不是value
2. edge默认工作于reactive模式，此时的http client对象实际创建于server vertile中，所以，这个场景与client vertile数据完全无关
  如果将edge改为线程池模式，则http client对象会创建于client verticle中
  其实，所有场景下，都是这个规则，如果是reactive流程，则需要创建http client时，不会再特地切线程的

  另外，看连接数，需要区分是客户端连接数，还是服务端连接数，这一块metrics中会有详细的统计
![image](https://user-images.githubusercontent.com/16874843/56105723-46c80400-5f70-11e9-8faf-f26267e41111.png)

3. 当前因为一些历史原因，进程中不止创建了一个vertx实例，实际至少有registry和transport两个vertx实例，如果引入了ConfigCenter，还有一个config vertx实例，有一些浪费资源，后期会对此实现做修改

**Comment by wpcchengxuyuan** [comment]
原来如此，谢谢您的解答
