### ISSUE TITLE
文件下载经过Edge网关后，报错提示content-type not supported

### ISSUE THREAD

**Issue by HsbGitHub** [apache/servicecomb-java-chassis#1184]
文件下载经过Edge网关后，报错提示content-type not supported，不走网关是可以的。
错误提示：
{
    "message": "method GET, path /netdisk/file_download/, statusCode 200, reasonPhrase OK, response content-type application/octet-stream is not supported"
}

接口代码：
@ApiResponses({
            @ApiResponse(code = 200, response = File.class, message = "")
    })
    @GetMapping(value = "/file_download")
    public ResponseEntity<InputStream> fileDownload(InvocationContext ic , FileDownloadReq req) {
        String fileName = req.getFileName();
        String fileStr = super.doFileDownload(OutApiServerEnum.TY_HUI_JIAO_YUN.getValue(), ic, fileName);

        return ResponseEntity
                .ok().header(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_OCTET_STREAM_VALUE)
                .header(HttpHeaders.CONTENT_DISPOSITION, "attachment;filename="+fileName)
                .body(new ByteArrayInputStream(fileStr.getBytes()));
    }

**Comment by liubao68** [comment]
应该是接口声明有误。 你可以参考这个帖子的说明： https://bbs.huaweicloud.com/forum/thread-14557-1-1.html

ResponseEntity<bytes[]>, ResponseEntity<Part>等，需要指定类型。 可以先看下DownloadSchema.java（在java-chassis项目的intergration tests目录）

**Comment by HsbGitHub** [comment]
谢谢！
