### ISSUE TITLE
java.net.URL类型做参数时启动失败

### ISSUE THREAD

**Issue by zhangzc0419** [apache/servicecomb-java-chassis#1192]
```
Caused by: java.lang.NullPointerException: null
5cbedd1414926425e587e6aa 	at org.apache.servicecomb.common.javassist.CtType.<init>(CtType.java:52)

```
参数什么类型情况下会导致javassist.CtType初始化失败？有没有文档说明？

还有使用内部类作为参数时也会启动失败：
```
@ResponseBody
    @RequestMapping(value = "test", method = POST)
    public String test(@RequestBody TestRequest data) throws Exception {
        return "";
    }
 
   @Data
    public static class TestRequest {
        private String data;
    }

```

**Comment by yhs0092** [comment]
ServiceComb-Java-Chassis对于微服务接口的定义不是完全没有要求的，简单地说，开发者定义的微服务接口需要能够被swagger服务契约明确地描述出来。参考资料：  https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/interface-constraints.html  建议对照文档和你的代码排查一下 : )

**Comment by liubao68** [comment]
And diffrence of Spring MVC: https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/springmvc.html

**Comment by liubao68** [comment]
Close old issues. Please feel free to create a new one when meet the problem again.
