### ISSUE TITLE
rpc接口返回类型为ResponseEntity<FilePart>，消费者端收到之后解析失败

### ISSUE THREAD

**Issue by HoyerIsAlexander** [apache/servicecomb-java-chassis#1200]
Version：1.1.0.B036

rpc接口返回类型为ResponseEntity(FilePart)，消费者端收到之后解析失败，debug发现，返回类型变成了ReadStreamPart，而实际的接口定义的类型为FilePart，导致Jackson报错，这个需要自定义converter解决吗？

**Comment by wujimin** [comment]
https://docs.servicecomb.io/java-chassis/zh_CN/general-development/file-download.html
"二、Consumer"

download consumer response type always to be ReadStreamPart
