### ISSUE TITLE
如何调用go-chassis的服务？

### ISSUE THREAD

**Issue by modernstar** [apache/servicecomb-java-chassis#1203]
通过RestTemplate方式调用Go-chassis编写的微服务时出现NullPointerException 错误！有相关Demo吗?

**Comment by johnyannj** [comment]
@modernstar  建议读一下
https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md

**Comment by liubao68** [comment]
go-chassis的问题不在这个项目的讨论访问。 我理解你问题发生的原因，是因为go-chassis在服务注册的时候，没有契约，所以无法支持相互调用。 我了解的情况是go-chassis是可以注册契约的，只是过程不清楚， 建议可以在go-chassis的网站寻找帮助。

**Comment by modernstar** [comment]
@liubao68 非常感谢您的耐心解答！
