### ISSUE TITLE
客户端调用服务端异常场景无法ExceptionToProducerResponseConverters

### ISSUE THREAD

**Issue by solomoni0999** [apache/servicecomb-java-chassis#1211]
客户端异常信息
CommonExceptionData [message=method POST, path /v1/hdfs/createDir/, statusCode 500, reasonPhrase , response content-type text/html;charset=UTF-8 is not supported]
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: org.apache.servicecomb.foundation.vertx.stream.BufferInputStream@699bb304; line: 1, column: 2]
使用csejavasdk是1.1.0版本

**Comment by yhs0092** [comment]
检查一下自己的异常转换扩展类，是不是没有配置SPI文件？
https://docs.servicecomb.io/java-chassis/zh_CN/general-development/error-handling.html

**Comment by yhs0092** [comment]
https://github.com/yhs0092/ExceptionConverterDemo_Java-Chassis
这里有个demo可以参考一下

**Comment by yhs0092** [comment]
你可以通过看日志来判断框架是否有利用SPI机制加载了你的自定义异常转换类，Java-Chassis在第一次碰到异常要转换的时候会打印相关的SPI加载日志（这是懒加载的，启动的时候不会打）：
```
Found SPI service org.apache.servicecomb.swagger.invocation.exception.ExceptionToProducerResponseConverter, count=4.
  0. org.apache.servicecomb.swagger.invocation.validator.ConstraintViolationExceptionToProducerResponseConverter.
  1. servicecomb.demo.provider.exception.DemoExceptionConverter.
  2. org.apache.servicecomb.swagger.invocation.exception.InvocationExceptionToProducerResponseConverter.
  3. org.apache.servicecomb.swagger.invocation.exception.DefaultExceptionToProducerResponseConverter.
```
可以看到这里加载了自定义的 `DemoExceptionConverter`

**Comment by liubao68** [comment]
Close old issues. Please feel free to create a new one when meet the problem again.
