### ISSUE TITLE
controller接口返回异常类，前台无法解析返回code和message信息

### ISSUE THREAD

**Issue by solomoni0999** [apache/servicecomb-java-chassis#1212]
controller层统一抛出InvocationException这个异常后，前台无法捕获后台抛出的error code和error msg

**Comment by yhs0092** [comment]
#1211 这两个问题可能是相关的
建议结合 https://github.com/yhs0092/ExceptionConverterDemo_Java-Chassis 这里的demo一起看一下，里面有一个consume和一个provider，展示了异常返回的整个流程

**Comment by liubao68** [comment]
Close old issues. Please feel free to create a new one when meet the problem again.
