### ISSUE TITLE
rpc提供方方法重名，消费方调用时，会报方法名找不到的错误

### ISSUE THREAD

**Issue by HoyerIsAlexander** [apache/servicecomb-java-chassis#1213]
Version：1.1.0.B036

消费方Api定义rpcApi，两个方法，sayHi()、sayHi(Request request)，分别用ApiOperation注解nickName="sayHi",nickName="sayHiHasRequest"，消费方调用rpcApi.sayHi()时，报Consumer method sayHi not exist。

想问下是使用方法不对，还是本身的问题，跟踪源码发现，方法重名的时候，Map<String, SwaggerConsumerOperation> opMap = new HashMap<>()；中没有保存重名方法的数据。

**Comment by liubao68** [comment]
你能分别贴一下提供方的接口定义和消费方的接口定义吗？

**Comment by HoyerIsAlexander** [comment]
提供方Api定义如下
Interface RpcApi
{
  @ApiOperation(nickname="sayHiNoParam")
  void sayHi();
 @ApiOperation(nickname="sayHiWithParam")
  void sayHi(String content);
}
提供方实现类型如下
RpcApi implements RpcApi
{
 void sayHi(){//do something}；
 void sayHi(String content){//do something};
}

消费方调用如下
CustomerRpcServie
{
  @RpcReference(XXXX)
  RpcApi rpcApi；
  rpcApi.sayHi();
}

提供方RpcApi定义如上时，调用时会报找不到sayHi method，因为加了nickname之后RPCAPI Path变了

**Comment by HoyerIsAlexander** [comment]
将提供方RpcApi修改为如下方式，增加@ApiOperation注解
Interface RpcApi
{
  @ApiOperation(nickname="sayHiNoParam")
  void sayHi();
 @ApiOperation(nickname="sayHiWithParam")
  void sayHi(String content);
}

提供方RpcApi定义如上时，消费方调用时会报找不到sayHi()这个无参的接口，debug发现在寻址时Map<String, SwaggerConsumerOperation> opMap = new HashMap<>()；该数据中只有sayHi(String content)接口数据，因为这个opMap将method.getName()作为key

**Comment by HoyerIsAlexander** [comment]
请确认是Bug还是我的使用方式的问题，谢谢！

**Comment by yhs0092** [comment]
按照你的描述，我尝试复现了一下问题
服务端REST 接口类定义：
```java
@RestSchema(schemaId = "RpcApi")
public class RpcApi {

  private static final Logger LOGGER = LoggerFactory.getLogger(RpcApi.class);

  @ApiOperation(value = "", nickname = "sayHi")
  public void sayHi() {//do something
    LOGGER.info("sayHi!!!");
  }

  @ApiOperation(value = "", nickname = "sayHiWithParam")
  public void sayHi(String content) {//do something
    LOGGER.info("sayHi[{}]", content);
  }
}
```
客户端定义服务端接口代码：
```java
public interface RpcApi {

  void sayHi();

  void sayHiWithParam(String content);
}
```
客户端调用代码：
```java
  @RpcReference(microserviceName = "provider", schemaId = "RpcApi")
  RpcApi rpcApi;

  @Path("test")
  @GET
  public String test() {
    String result = "";
    rpcApi.sayHi();
    result += "OK";
    rpcApi.sayHiWithParam("test");
    result += "OK";
    return result;
  }
```
如果按照以上代码运行的话，调用客户端的test方法能够得到"OKOK"的响应，服务端的日志也说明请求能够正常地接收到。

但是如果客户端使用的`RpcApi`接口定义改为下面这样的话，会碰到问题：
```java
public interface RpcApi {
  @ApiOperation(value = "", nickname = "sayHi")
  void sayHi();

  @ApiOperation(value = "", nickname = "sayHiWithParam")
  void sayHi(String content);  // 这里两个方法是同名的，只依靠@ApiOperation注解来区分的话会有问题
}
```

总的来说我们**建议用户在定义REST接口的时候保持每个接口方法的方法名在当前接口类中是唯一的**，如果您真的有无法规避的要求，必须将服务端接口定义为同名的话，可以考虑我上面给出的例子 : )

**Comment by liubao68** [comment]
I tested the scenario, it seems a bug. You can try this in client:

```
Interface RpcApi
{
void sayHiNoParam();

void sayHiWithParam(String content);
}
```

**Comment by liubao68** [comment]
My testing code:

provider:
```
@RestSchema(schemaId = "RpcSchemaService")
@RequestMapping(path = "/")
public class RpcSchemaService {
    @ApiOperation(value = "", nickname = "sayHiAge")
    @PostMapping(path = "sayHiAge")
    public String sayHi(@RequestParam(name = "age") Integer age) {
        return "Hello " + age;
    }

    @ApiOperation(value = "", nickname = "sayHiNameAge")
    @PostMapping(path = "sayHiNameAge")
    public String sayHi(@RequestParam(name = "name") String name, @RequestParam(name = "age") Integer age) {
        return "Hello " + name + " with " + age;
    }
}
```

consumer:
```
public interface IRpcSchemaServiceClient {
//    @ApiOperation(value = "", nickname = "sayHiAge")
    public String sayHiAge(Integer age);

//    @ApiOperation(value = "", nickname = "sayHiNameAge")
    public String sayHiNameAge(String name, Integer age);
}


@Component
public class RpcSchemaServiceClient {
    @RpcReference(microserviceName = "customer-service", schemaId = "RpcSchemaService")
    private static IRpcSchemaServiceClient service;

    public static void run() {
        testOverride();
    }

    private static void testOverride() {
        TestMgr.check("Hello world with 2", service.sayHiNameAge("world", 2));
        TestMgr.check("Hello 2", service.sayHiAge(2));
    }

}
```

**Comment by HoyerIsAlexander** [comment]
> I tested the scenario, it seems a bug. You can try this in client:
> 
> ```
> Interface RpcApi
> {
> void sayHiNoParam();
> 
> void sayHiWithParam(String content);
> }
> ```

Thanks.  We will change our code and use the unique method name, but i think  servicecomb need to support this feature.

**Comment by yhs0092** [comment]
A new issue is create to track it [SCB-1291](https://issues.apache.org/jira/browse/SCB-1291)

**Comment by xiaojunl** [comment]
servicecomb版本:1.2.0，rpc方式下方法重载的两个bug
1  提供方重载方法，在按参数对象生成契约时，生成的swagger中ref值，取方法名+ body会冲突
2 不支持使用提供方接口调用

**Comment by yhs0092** [comment]
@xiaojunl  Hello, could you provide a demo project?

**Comment by xiaojunl** [comment]
provider:
`public interface MethodOverloadService {
 
    String singleParamMethod(String name);
 
    String singleParamMethod(List<String> names);
 
    String multipleParamMethod(String type, String name);
 
    String multipleParamMethod(String type, List<String> names);
 
}

@RpcSchema("methodOverload")
public class MethodOverloadServiceImpl implements MethodOverloadService {
 
    @Override
    public String singleParamMethod(String name) {
        return "hi " + name;
    }
 
    @Override
    @ApiOperation(value = "", nickname = "singleParamMethods")
    public String singleParamMethod(List<String> names) {
        return "hi " + names.stream().collect(Collectors.joining(","));
    }
 
    @Override
    public String multipleParamMethod(String type, String name) {
        return "hi " + name + ", with type " + type;
    }
 
    @Override
    @ApiOperation(value = "", nickname = "multipleParamMethods")
    public String multipleParamMethod(String type, List<String> names) {
        return "hi " + names.stream().collect(Collectors.joining(",")) + ", with type " + type;
    }
}
`

consumer:
`@RestSchema
@RequestMapping("/overload")
public class MethodOverloadController {
    @RongReference(appId = "service-demo-services", serviceId = "methodOverload")
    private MethodOverloadService methodOverloadService;
 
    @GetMapping("/singleParamMethod")
    public String singleParamMethod(String name) {
      return methodOverloadService.singleParamMethod(name);
    }
 
    @GetMapping("/singleParamMethods")
    @ApiOperation(value = "", nickname = "singleParamMethods")
    public String singleParamMethod(List<String> names) {
      return methodOverloadService.singleParamMethods(names);
    }
}`

**Comment by liubao68** [comment]
fixed in 1.3.0.
