### ISSUE TITLE
servicecomb.foundation-protobuf not compatible with protobuf class

### ISSUE THREAD

**Issue by yellowbigbird** [apache/servicecomb-java-chassis#1217]
Hi:
我现在又需求用POJO 做protobuf的validation. 
考虑用javax.validation.
测试servicecomb.foundation-protobuf, 发现转换protbuf 生成class, 序列化的binary, 解析上还是有问题.
我写了个test 项目.
https://github.com/yellowbigbird/test-protobuf
https://github.com/yellowbigbird/test-protobuf/blob/master/src/test/java/util/ServiceCombTest.java 有几个test跑不过, 请查看.
Thx

**Comment by liubao68** [comment]
I think  this requirement is out of the topic of java-chassis, and do not suggest you depend on servicecomb apis this way.

**Comment by wujimin** [comment]
servicecomb's protobuf codec should compatible to standard protobuf
i think need to check if it is compatible.

**Comment by yellowbigbird** [comment]
> I think this requirement is out of the topic of java-chassis, and do not suggest you depend on servicecomb apis this way.

So would u mind suggest the correct way please?

**Comment by wujimin** [comment]
i tried to run your test case: util.ServiceCombTest#testEqual_basicinfo
defaultly can not pass.

and then i changed your idl, make field names equals to java model field name(ServiceComb not read Tag annotation)
and then passed.
![image](https://user-images.githubusercontent.com/16874843/59870468-35640380-93c8-11e9-800d-15602dff2c8c.png)

**Comment by liubao68** [comment]
Close old issues. Please feel free to create a new one when meet the problem again.
