### ISSUE TITLE
 rest请求参数有继承时无法获取父类参数内容

### ISSUE THREAD

**Issue by dongzegithub** [apache/servicecomb-java-chassis#1218]
##### 请求参数类TestAReq 继承TestBReq
```java
@Data
@EqualsAndHashCode(callSuper = false)
public class TestAReq extends TestBReq
{
    @QueryParam("tempC")
    private String tempC; 
    
    @QueryParam("tempD")
    private String tempD; 
}
```
```java
@Data
public class TestBReq
{
    @QueryParam("tempA")
    private String tempA; 
    
    @QueryParam("tempB")
    private String tempB; 
}
```

##### 在rest请求queryTest中使用TestAReq作为请求参数，在传参之后，TestAReq中的tempA、tempB的值为null
```java
    @GET
    @Path("")
    @Consumes({MediaType.APPLICATION_JSON, MediaType.TEXT_XML})
    @Produces({"application/json; charset=UTF-8", "text/xml; charset=UTF-8"})
    public TestRsp queryTest(
            @BeanParam TestAReq request)
    {
        return XXXX;
    }

```

**Comment by liubao68** [comment]
Do you missed @Data for TestBReq?

**Comment by dongzegithub** [comment]
> Do you missed `@Data` for TestBReq?

TestBReq  has  @Data.

**Comment by yhs0092** [comment]
I've tested the similar case. If the getter and setter methods are generated manually, there seems no problem.
Can you check the schema of the provider service whether the param fields are all listed in the schema?

**Comment by yhs0092** [comment]
> I've tested the similar case. If the getter and setter methods are generated manually, there seems no problem.
> Can you check the schema of the provider service whether the param fields are all listed in the schema?

The case that getter/setter methods generated by Lombok is also tested and no problem is find in my dev environment. Can you check the schema of the provider service and tell us which version of ServiceComb-Java-Chassis is used?  @dongzegithub

**Comment by liubao68** [comment]
Close old issues. Please feel free to create a new one when meet the problem again.
