### ISSUE TITLE
debug模式下启动时间过长

### ISSUE THREAD

**Issue by msnetc** [apache/servicecomb-java-chassis#1220]
我的基于java-chassis1.2.0的项目，在debug模式下 花了接近20分钟，还没启动成功。
但是在非debug模式下，一分钟不到就启动了，在注册中心注册成功。
1-2019-05-28 12:38:17 [main] DEBUG org.hibernate.validator.internal.xml.ValidationXmlParser - No META-INF/validation.xml found. Using annotation based configuration only.
1-2019-05-28 12:51:15 [main] INFO org.apache.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-auto-1"]

例如只这个步骤就暂停了13分钟。

**Comment by yhs0092** [comment]
Hello, could you dump the JVM thread stack while it's getting stuck?

**Comment by liubao68** [comment]
Close old issues. Please feel free to create a new one when meet the problem again.
