### ISSUE TITLE
关于servicecomb对SPI扩展的使用问题

### ISSUE THREAD

**Issue by johnyannj** [apache/servicecomb-java-chassis#1221]
servicecomb有好多处使用了SPI扩展。

使用SPI的方式全部都是
ServiceLoader.load(className)；

它默认使用线程上下文里的classloader去寻找SPI文件和加载类。

ServiceLoader有另外一个方法是
public static \<S\> ServiceLoader\<S\> load(Class\<S\> service,
                                            ClassLoader loader)
可以指定classloader

我觉得servicecomb应该使用第二个方法可能习惯更好一点。 把加载servicecomb类的classloader传给他。

这样可以允许业务考虑使用独立的classloader加载servicecomb。

**Comment by liubao68** [comment]
你可以具体描述下使用场景吗？ 比如Osgi ？ 这类需求是 do it on demand.

**Comment by liubao68** [comment]
Close old issues. Please feel free to create a new one when meet the problem again.
