### ISSUE TITLE
About RuleNameExtentionsFactory spell error

### ISSUE THREAD

**Issue by johnyannj** [apache/servicecomb-java-chassis#1223]
Different spells:

org.apache.servicecomb.loadbalance.ExtensionsFactory
org.apache.servicecomb.loadbalance.RuleNameExtentionsFactory
org.apache.servicecomb.loadbalance.DefaultRetryExtensionsFactory

wrong:
public class RuleNameExtentionsFactory implements ExtensionsFactory

I think “Extensions” is better than “Extentions”

RuleNameExtentionsFactory =\> RuleNameExtensionsFactory

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
