### ISSUE TITLE
不确定zuul的依赖和使用https协议报This combination of host and port requires TLS.

### ISSUE THREAD

**Issue by solomoni0999** [apache/servicecomb-java-chassis#1239]
使用zuul边缘服务访问其他微服务应用，不确定zuul工程具体添加什么依赖和使用demo依赖后报TLS异常错误

**Comment by yhs0092** [comment]
部署服务是基于什么HTTP服务器的呢？Vertx还是SpringBoot内嵌的Tomcat，或者独立Tomcat？

**Comment by yhs0092** [comment]
ServiceComb-Java-Chassis提供的 [TLS配置](https://docs.servicecomb.io/java-chassis/zh_CN/security/tls.html) 是用于原生开发方式的，也就是底层HTTP服务器是Vertx的场景。
如果你是使用SpringBoot内嵌Tomcat运行，或打war包在独立Tomcat里运行，就需要去网上搜一下它们配置TLS证书的方法。使用我们提供的[配置](https://docs.servicecomb.io/java-chassis/zh_CN/security/tls.html)是无法让你的服务启用HTTPS的。

**Comment by solomoni0999** [comment]
使用外置tomcat，并且tomcat已经配置证书了
<Connector port="29644" protocol="com.huawei.dlf.security.Http11Protocol"
               maxThreads="200"
               maxHeaderCount="100"
               maxParameterCount="10000"
               maxPostSize="10240"
               maxHttpHeaderSize="32768"
               maxKeepAliveRequests="100"
               connectionTimeout="20000"
               xpoweredBy="false"
               URIEncoding="UTF-8"
               SSLEnabled="true" scheme="https" secure="true" clientAuth="false"
               sslProtocol="TLS"
               sslEnabledProtocols="TLSv1.2"
               keystoreFile="/opt/huawei/Bigdata/adapters/FusionInsight_DLF_V100R002C80SPC200/DLFCommon/conf/keystore.jks"
               keystorePass="d2NjX2NyeXB0ATQxNDU1MzVGNDM0MjQzOzM3MzUzOTM5MzA0NjMwMzczNDMyNDY0NjM3MzkzODM4MzQzNTQzMzczODMyMzk0MjMwNDE0NDQ1NDQzNzMxNDQ7OzMxMzAzMDMwMzA7MUQxRERDQTkyQTg1M0MxQkQwMDU4MTE5MjBDNjZDRkY7QzI4RkU3QjExRUJBMjYwMDs2NjM1MzgzMzMyNjU2MzMxMkQ2NTYzNjEzODJEMzQzOTM0MzEyRDYxMzkzNzYzMkQzNjM3MzAzOTMzMzczMTYyMzMzMTYyNjI7"
     />

**Comment by liubao68** [comment]
This issue has very little imformance about what it is done. Maybe this is the correct behavior when you access zuul using some client like postman. See https://www.cnblogs.com/silentdoer/p/9102119.html

**Comment by liubao68** [comment]
Clean up old questions. Please feel free to create a new one if you met the problem again.
