### ISSUE TITLE
Api use inner static class will throw javassist.NotFoundException

### ISSUE THREAD

**Issue by johnyannj** [apache/servicecomb-java-chassis#1242]
demo:
```
@RestSchema(schemaId="demo")
class Service
{
    public static class Model
    {

    }

    @RequestMapping(path = "/get", method = RequestMethod.GET)
    public Model foo()
    {
        return null;
    }
}
```

it will take error at

org.apache.servicecomb.common.javassist.CtType.<init>(CtType.java:55)

```
  public CtType(JavaType javaType) {
    if (CtTypeJavaType.class.isInstance(javaType)) {
      CtType ctType = ((CtTypeJavaType) javaType).getType();
      init(ctType.ctClass, ctType.hasGenericTypes, ctType.genericSignature);
      return;
    }

    ClassLoader classLoader = javaType.getRawClass().getClassLoader();
    try {
      ClassPool classPool = JavassistUtils.getOrCreateClassPool(classLoader);
      **init(classPool.get(javaType.getRawClass().getCanonicalName()), javaType.hasGenericTypes(),
          javaType.getGenericSignature()**
      );
    } catch (NotFoundException e) {
      throw new IllegalStateException(
          String.format("Failed to get CtClass for %s in classloader %s.",
              javaType.getRawClass().getName(),
              classLoader),
          e);
    }
}

```

javaType.getRawClass().getCanonicalName() is "com.zhaoyanblog.Service.Model"
the classPool.get will throw javassist.NotFoundException
the right name is "com.zhaoyanblog.Service$Model"

**Comment by yhs0092** [comment]
Hello, we had a [discussion](http://mail-archives.apache.org/mod_mbox/servicecomb-dev/201901.mbox/%3CCAFN%2B3hp_p_F9d%2BAETqFLLRKh3PhqNB3PgnZLd-rf3DRBaSCGTQ%40mail.gmail.com%3E) before about this situation. And you can search all the related mails [here](http://mail-archives.apache.org/mod_mbox/servicecomb-dev/201901.mbox/browser).
It's not recommended to define the param type as a inner class. Is there any necessary in your situation to do so?

**Comment by johnyannj** [comment]
hi @yhs0092:

"[Discuss] Should we support inner class param type defined in REST service class?"  is your discussion. it is only refer  " type defined in REST service class", 

All inner class in other classs as service “param ”or “return“” will also throw exception.

I think it is a simple mistake.  It should be corrected. which is natural。

no a "support " or "not support" question.

ext:
Inner class is used by me  When I do a simple test。

**Comment by yhs0092** [comment]
Hello @johnyannj , sorry for not replying to you in time.
I agree that there is a mistake in the code preventing users from defining inner class as the REST operation param type. Originally it seems a mistake. But as this mistake just prevents a use case which is not a good practice, so after the discussion, we decide not to fix it.
As you think this feature is necessary, you can raise a discussion in the dev mailing list and point out the necessity. And we'll appreciate if you can create a pull request to fix this issue : )

**Comment by liubao68** [comment]
Clean up old questions. Please feel free to create a new one if you met the problem again.
