### ISSUE TITLE
MicroService Communication With SSL Certificate Question

### ISSUE THREAD

**Issue by willard-kali** [apache/servicecomb-java-chassis#1245]
I used this to call for some api:
`restTemplate.getForObject(“cse://micro-name/mine/to/path”, responseType, uriVariables);`
when I prepare to open ssl switch,I don't know how to configure the client certificate location？
I just find these config:
```
ssl.protocols: TLSv1.2
ssl.authPeer: false
ssl.checkCN.host: false
ssl.ciphers: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_128_GCM_SHA256

#Certificates Config
ssl.trustStore: trust.jks
ssl.trustStoreType: JKS
ssl.trustStoreValue: trustStorePass
ssl.keyStore: server.p12
ssl.keyStoreType: PKCS12
ssl.keyStoreValue: keyStorePass
ssl.crl: revoke.crl
ssl.sslCustomClass: mine.to.path.SomeSSLCustom
```

Look forward to your reply.

**Comment by liubao68** [comment]
Please check https://docs.servicecomb.io/java-chassis/zh_CN/security/tls.html for rest client configuration.
