### ISSUE TITLE
参数校验不生效

### ISSUE THREAD

**Issue by clairedidi** [apache/servicecomb-java-chassis#1246]
按照文档配置ExceptionToProducerResponseConverter，但是没有生效，报错信息可以看出先抛出的异常然后再加载SPI服务，其中CustomExceptionToProducerResponseConverter是自定义的ExceptionToProducerResponseConverter（在另一个工程里面同样的写法却是正常的，正常的逻辑应该是走到swagger-invocation-validator.jar中的ParameterValidator类中抛出ConstraintViolationException后被自定义的ExceptionToProducerResponseConverter实现类捕获）
报错信息如下：
`org.apache.servicecomb.swagger.invocation.exception.InvocationException: InvocationException: code=400;msg=CommonExceptionData [message=Parameter is not valid for operation [data-service.overview.addVod]. Parameter is [req]. Processor is [body].]
	at org.apache.servicecomb.common.rest.codec.RestCodec.restToArgs(RestCodec.java:66)
	at org.apache.servicecomb.common.rest.filter.inner.ServerRestArgsFilter.afterReceiveRequest(ServerRestArgsFilter.java:60)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.prepareInvoke(AbstractRestInvocation.java:226)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.invoke(AbstractRestInvocation.java:206)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.runOnExecutor(AbstractRestInvocation.java:196)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.lambda$scheduleInvocation$0(AbstractRestInvocation.java:159)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
16:38:28.009 [pool-2-thread-1] INFO  [] o.a.s.f.common.utils.SPIServiceUtils - Found SPI service org.apache.servicecomb.swagger.invocation.exception.ExceptionToProducerResponseConverter, count=5.
16:38:28.009 [pool-2-thread-1] INFO  [] o.a.s.f.common.utils.SPIServiceUtils -   0. com.huawei.wukong.dataservice.exception.CustomExceptionToProducerResponseConverter.
16:38:28.010 [pool-2-thread-1] INFO  [] o.a.s.f.common.utils.SPIServiceUtils -   1. org.apache.servicecomb.swagger.invocation.validator.ConstraintViolationExceptionToProducerResponseConverter.
16:38:28.010 [pool-2-thread-1] INFO  [] o.a.s.f.common.utils.SPIServiceUtils -   2. org.apache.servicecomb.swagger.invocation.exception.InvocationExceptionToProducerResponseConverter.
16:38:28.010 [pool-2-thread-1] INFO  [] o.a.s.f.common.utils.SPIServiceUtils -   3. org.apache.servicecomb.swagger.invocation.exception.DefaultExceptionToProducerResponseConverter.
16:38:28.010 [pool-2-thread-1] INFO  [] o.a.s.f.common.utils.SPIServiceUtils -   4. com.huawei.wukong.dataservice.exception.MyExceptionToProducerResponseConverter.`

CustomExceptionToProducerResponseConverter类如下
`import javax.validation.ConstraintViolationException;
import org.apache.servicecomb.swagger.invocation.Response;
import org.apache.servicecomb.swagger.invocation.SwaggerInvocation;
import org.apache.servicecomb.swagger.invocation.exception.ExceptionToProducerResponseConverter;
import org.apache.servicecomb.swagger.invocation.exception.InvocationException;
import com.huawei.wukong.dataservice.bean.ErrorResp;
import com.huawei.wukong.dataservice.constant.ErrorCode;

public class CustomExceptionToProducerResponseConverter
		implements ExceptionToProducerResponseConverter<ConstraintViolationException> {

	@Override
	public Class<ConstraintViolationException> getExceptionClass() {
		return ConstraintViolationException.class;
	}

	@Override
	public Response convert(SwaggerInvocation swaggerInvocation, ConstraintViolationException e) {
		ErrorResp response = new ErrorResp();	
		response.setCode(ErrorCode.ERROR_VALIDATION.getCode());
		response.setMsg(e.getConstraintViolations().toString());
		InvocationException state = new InvocationException(ErrorCode.ERROR_VALIDATION.getStatus(), response);
	    return Response.failResp(state);
	}
	
	@Override
	public int getOrder() {
		    return -100;
	}

}
`

**Comment by liubao68** [comment]
信息比较少，看不出问题在哪儿。 建议可以调试一下。先下载servicecomb-java-chassis代码，看看ExceptionToProducerResponseConverter 的 convert 方法在哪儿被调用，然后在对应的地方打一个端点，看看SPI是否被加载执行。

**Comment by liubao68** [comment]
Clean up old questions. Please feel free to create a new one if you met the problem again.
