### ISSUE TITLE
参数校验GET方式请求不生效，POST方式请求正常

### ISSUE THREAD

**Issue by guanhaobi** [apache/servicecomb-java-chassis#1249]
按照文档，配置了ExceptionToProducerResponseConverter，发现下POST请求下可以正常处理自定义的参数校逻辑，GET方式请求下，无法进入自定义参数校验逻辑，debug调试发现这两种请求方式下，框架的方法调用栈不一样：
public class ConstraintViolationExceptionToProducerResponseConverter
    implements ExceptionToProducerResponseConverter<ConstraintViolationException> {
  @Override
  public Class<ConstraintViolationException> getExceptionClass() {
      return ConstraintViolationException.class;
  }

  @Override
  public Response convert(SwaggerInvocation swaggerInvocation, ConstraintViolationException e) {
      Map<String,Object> errorInfo = new HashMap<>(2);
      errorInfo.put("rtnCode",1);
      errorInfo.put("rtnDesc":"Parameter valid faild.")
     return Response.createFail(new InvocationException(Status.BAD_REQUEST, errorInfo ));
  }

  @Override
  public int getOrder() {
      return -200;
  }
}

跟踪代码调试了下，发现在RestCodec这个类的restToArgs方法中，根据参数校验的必填字段获取请求参数值，GET请求如果没传参，获取到null值，会直接抛出异常，这个异常导致不会走到自定义参数校验的逻辑。
相似的场景：
     POST请求，如果传的json数据格式错误，也会导致restToArgs方法报错而抛出异常，也不会进到自定义参数校验逻辑。如错误的json内容： {
    "name":"test1234" , //这里写个逗号，破坏json数据格式
}

**Comment by clairedidi** [comment]
我这边有两个工程，其中一个工程POST请求是可以处理参数校验抛出的异常，另一个工程复制过来之后POST请求就不能处理

**Comment by guanhaobi** [comment]
> 我这边有两个工程，其中一个工程POST请求是可以处理参数校验抛出的异常，另一个工程复制过来之后POST请求就不能处理

这种情况应该不存在，你仔细检查检查，1.SPI加载的那个配置文件 2.配置文件中类名是否正确，是否存在复杂工程后，包路径变化了的情况 3.断点调试下

**Comment by liubao68** [comment]
Clean up old questions. Please feel free to create a new one if you met the problem again.
