### ISSUE TITLE
怎么定义Annotation才能在Hanlder中获取到

### ISSUE THREAD

**Issue by HoyerIsAlexander** [apache/servicecomb-java-chassis#1252]
版本号：1.1.0.B036

背景：想通过Schema上使用自定义注解定义接口可以访问的角色以及权限等信息进行纵向越权检查，然后再handler中统一获取统一校验，但是尝试之后，handler中获取不到定义的Annotation

请问是有什么方法或者案例吗？

**Comment by liubao68** [comment]
你需要提供更多具体的信息（具体问题）帮助大家回答。这个是寻找解决方案，大家可能并没有像你这样尝试过，所以可能无法帮你提供解决方案。 

annotation鉴权其实可以参考spring security \@PreAuthorize 的实现，这个是比较优雅的。 类似的项目可以参考： https://github.com/apache/servicecomb-fence  这个专为servicecomb认证鉴权设计，很多技巧是可以参考的。

**Comment by HoyerIsAlexander** [comment]
我们服务结构是edge-apigateway-rpc，希望在edge上统一完成越权的校验，servicecomb对于edge的定义也包括统一的认证鉴权，而不需要在每个apigateway或者rpc上

我们的Rest接口在ApiGateWay上定义

比如一个RestSchema

HelloApi
{
    @RequireRole（“admin”）//只有admin角色可以访问
    @Get
    @Path（“/hello”） 
    sayHello（）；
}

通过edge访问/hello，在edge的handler中通过invocation.getOperationMeta().getMethod()获取到Method信息，但是method中annotation数据为空；

spring security也有考虑，但是也需要在edge上获取到注解的信息才能完成在edge的统一鉴权；

**Comment by liubao68** [comment]
是不是将annotation信息放到接口定义里面，而不是实现类里面？ 需要理解JDK annotation的使用限制，JDK是不支持annotation继承的。你需要用非常特殊的方法获取到接口定义里面的annotation。 详细信息可以搜索下JDK对于annotation继承的支持。

**Comment by HoyerIsAlexander** [comment]
多谢，接口定义和实现类都试了下，我看看JDK对于annotation继承的支持
