### ISSUE TITLE
Springboot集成的问题

### ISSUE THREAD

**Issue by xz794273799** [apache/servicecomb-java-chassis#1253]
1、不兼容Springboot2，发现ServiceComb引入的Springboot1的包，jar包冲突，服务不能启动
2、尝试Springboot1的版本
ServiceComb Java-Chassis 1.2.0
ServiceComb Java-Chassis 1.1.0
ServiceComb Java-Chassis 1.0.0
ServiceComb Java-Chassis 1.0.0-m2
ServiceComb Java-Chassis 1.0.0-m1
以上版本都试过一遍，除了1.0.0-m1，其他版本都无法启动，报错如下：
2019-07-01 18:34:39.333  WARN 6276 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.apache.servicecomb.springboot.starter.provider.ServiceCombSpringConfiguration': Unsatisfied dependency expressed through method 'setCseApplicationListener' parameter 0; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'org.apache.servicecomb.core.CseApplicationListener' available: expected single matching bean but found 2: org.apache.servicecomb.core.CseApplicationListener#0,org.apache.servicecomb.core.CseApplicationListener#1

**Comment by xz794273799** [comment]
Springboot web模式启动后，调用RestTemaplte进行消费，报错：

java.lang.IllegalStateException: System is not ready for remote calls. When beans are making remote calls in initialization, it's better to implement org.apache.servicecomb.core.BootListener and do it after EventType.AFTER_REGISTRY.

**Comment by myVictor** [comment]
> 1、不兼容Springboot2，发现ServiceComb引入的Springboot1的包，jar包冲突，服务不能启动
> 2、尝试Springboot1的版本
> ServiceComb Java-Chassis 1.2.0
> ServiceComb Java-Chassis 1.1.0
> ServiceComb Java-Chassis 1.0.0
> ServiceComb Java-Chassis 1.0.0-m2
> ServiceComb Java-Chassis 1.0.0-m1
> 以上版本都试过一遍，除了1.0.0-m1，其他版本都无法启动，报错如下：
> 2019-07-01 18:34:39.333 WARN 6276 --- [ main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.apache.servicecomb.springboot.starter.provider.ServiceCombSpringConfiguration': Unsatisfied dependency expressed through method 'setCseApplicationListener' parameter 0; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'org.apache.servicecomb.core.CseApplicationListener' available: expected single matching bean but found 2: org.apache.servicecomb.core.CseApplicationListener#0,org.apache.servicecomb.core.CseApplicationListener#1

怎么解决的？

**Comment by liubao68** [comment]
建议参考下： https://github.com/apache/servicecomb-samples/tree/master/dependency_management  里面关于spring boot 2集成的例子。

**Comment by ltp217** [comment]
同遇到了，把这个org.apache.servicecomb.spring-boot2-starter删掉就好了，不知道具体啥原因。

**Comment by liubao68** [comment]
Clean up old questions. Please feel free to create a new one if you met the problem again.

**Comment by sofkyle** [comment]
> 建议参考下： https://github.com/apache/servicecomb-samples/tree/master/dependency_management 里面关于spring boot 2集成的例子。

链接失效了

**Comment by liubao68** [comment]
文档： https://servicecomb.apache.org/references/java-chassis/zh_CN/using-java-chassis-in-spring-boot/using-java-chassis-in-spring-boot.html

例子： https://github.com/apache/servicecomb-samples/tree/master/porter_springboot
