### ISSUE TITLE
trust-sample在指定场景出现java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by brankLY** [apache/servicecomb-java-chassis#1261]
我在尝试运行trust-sample成功后，关停sc（本地），短时间内进行consumer端调用store成功，但是在经过12小时后进行调用会报错，java.lang.NullPointerException: null，message会报Internal Server Error

**Comment by brankLY** [comment]
问题定位在AccessController.java:99，怀疑是在进行isAllowed判断时没有验证microservice是否为空产生的报错，但问题关键在于此类场景怎么保证服务可以正常调用。

**Comment by liubao68** [comment]
samples changed.
