### ISSUE TITLE
一键式脚手架 现在打不开了?

### ISSUE THREAD

**Issue by new-lcc** [apache/servicecomb-java-chassis#1262]
一键式脚手架 现在打不开了? http://start.servicecomb.io/

**Comment by new-lcc** [comment]
1

**Comment by Walker-Don** [comment]
1

**Comment by henryzp** [comment]
@new-lcc ，你能打开了？？我的还是打不开啊

**Comment by javens0601** [comment]
现在还是打不开这个网页，有人知道为什么吗？ 可以留言回复一下

**Comment by liubao68** [comment]
网站没维护了。 可以直接下载[例子](https://github.com/apache/servicecomb-samples)，比脚手架灵活。
