### ISSUE TITLE
怎样在程序里通过注解的方式获取配置参数

### ISSUE THREAD

**Issue by walker-dead-cave** [apache/servicecomb-java-chassis#1264]

**Comment by yhs0092** [comment]
通过注解的方式获取配置值的话，可以用`org.springframework.beans.factory.annotation.Value`，但是这种注解只能初始化一次配置值，无法在后面进行动态配置刷新。
另外还有两种获取配置值的方式可以考虑一下：
1. 使用Archaius的API获取配置值，参考[这里](https://docs.servicecomb.io/java-chassis/zh_CN/config/general-config.html)的“在程序中读取配置信息”部分
2. 使用ServiceComb-Java-Chassis提供的配置注入对象功能，参考[这篇文档](https://docs.servicecomb.io/java-chassis/zh_CN/config/inject-config.html)。需要注意的是，通过这种功能创建的配置注入对象，如果不再使用的话，需要进行显式的注销操作（文末有说明），否则会造成内存泄漏。

**Comment by wujimin** [comment]
一次性的创建，也没什么问题
主要是不要同一个对象重复创建不释放

**Comment by walker-dead-cave** [comment]
IefConfigEntityaa config = SCBEngine.getInstance().getPriorityPropertyManager().createConfigObject(IefConfigEntityaa.class);
这个创建了，一直不释放，配置中心更新了也不会更新这个对象吧

**Comment by liubao68** [comment]
Close old issues. Please feel free to create a new one when meet the problem again.
