### ISSUE TITLE
不支持zip流下载吗？

### ISSUE THREAD

**Issue by Gold-Z** [apache/servicecomb-java-chassis#1265]
存在边下载变压缩的使用场景

**Comment by liubao68** [comment]
目前支持这里的下载功能: https://docs.servicecomb.io/java-chassis/zh_CN/general-development/file-download.html  我理解你的场景可以使用InputStream类型，业务自己构造zip流

**Comment by liubao68** [comment]
Close old issues. Please feel free to create a new one when meet the problem again.
