### ISSUE TITLE
highway协议在处理空集合时引发空指针

### ISSUE THREAD

**Issue by xiaojunl** [apache/servicecomb-java-chassis#1267]
在两种情况发现空指针：
1 服务提供方返回空集合（return Collections.emptyList())，服务消费方接收到null值，对比REST下会返回空集合
2 服务提供方有List型参数，服务消费方在调用时无论传null值还是空集合都会引发空指针

**Comment by wujimin** [comment]
highway=tcp+protobuf
而protobuf没有空的概念，无法传递

甚至：List<String> lists = Arrays.asList(null, null, "abc")，序列化，再反序列化，也只能得到一个list中只有一个元素"abc"
这是protobuf本身的约束

**Comment by xiaojunl** [comment]
EmptyList，有好的处理建议吗？

**Comment by wujimin** [comment]
在使用protobuf的前提下，只能在业务代码中，将null与empty list同等对待才行了

**Comment by xiaojunl** [comment]
好的
