### ISSUE TITLE
RestTemplateBuilder.create使用问题

### ISSUE THREAD

**Issue by zhuhongqi** [apache/servicecomb-java-chassis#1268]
RestTemplateBuilder.create里面是单例模式（RestTemplateWrapper的单例），这样导致如果我某个微服务接口调用设置了指定的超时时间会影响其他接口的调用，是否有其他的方法可以new一个RestTemplateWrapper出来呢？

**Comment by wujimin** [comment]
Timeout is not controlled by the RestTemplate instance
it's depend on configuration: 
```
  global:             servicecomb.request.timeout
  microservice:       servicecomb.request.${service}.timeout
  schema:             servicecomb.request.${service}.${schema}.timeout
  operation:          servicecomb.request.${service}.${schema}.${operation}.timeout
```
operation has the highest priority

**Comment by liubao68** [comment]
> > Timeout is not controlled by the RestTemplate instance
> > it's depend on configuration:
> > ```
> >   global:             servicecomb.request.timeout
> >   microservice:       servicecomb.request.${service}.timeout
> >   schema:             servicecomb.request.${service}.${schema}.timeout
> >   operation:          servicecomb.request.${service}.${schema}.${operation}.timeout
> > ```
> > 
> > 
> > operation has the highest priority
> 
> 我使用的是CSE，在microservice.yaml里面如何配置operation级别的超时

上面的回答应该已经包含了你要的答案

**Comment by liubao68** [comment]
Close old issues. Please feel free to create a new one when meet the problem again.
