### ISSUE TITLE
程序运行失败都没有看到一个error日志

### ISSUE THREAD

**Issue by walker-dead-cave** [apache/servicecomb-java-chassis#1270]
全部是debug和info日志，然后程序运行失败，定位不到问题

**Comment by liubao68** [comment]
你给的信息太少了。 没法帮组到你。 正常情况下，所有的logger机制都是会输出高级别的日志的，如果有的话。

**Comment by WillemJiang** [comment]
@walker-dead-cave 有什么更多的信息需要补充吗？

**Comment by liubao68** [comment]
Close old issues. Please feel free to create a new one when meet the problem again.
