### ISSUE TITLE
LoggingFailureAnalysisReporter

### ISSUE THREAD

**Issue by walker-dead-cave** [apache/servicecomb-java-chassis#1272]
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-07-12 18:25:20 ERROR (LoggingFailureAnalysisReporter.java:42)- 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class

Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).

**Comment by yhs0092** [comment]
Hello, it seems there should be a database URL config item? Maybe you need to find the answer in the database references.

**Comment by liubao68** [comment]
Close old issues. Please feel free to create a new one when meet the problem again.
