### ISSUE TITLE
servicecomb怎么能直接访问HTML页面？

### ISSUE THREAD

**Issue by zhangaijing** [apache/servicecomb-java-chassis#1274]
现在在resource目录下创建view.html页面，直接访问时提示：.OperationLocator >> locate path failed, status:Not Found, http method:GET, path:/view.html/

**Comment by liubao68** [comment]
servicecomb缺省不是一个web服务器，只是http服务，提供REST。servicecomb的web模式下，可以使用web容器的功能，比如spring boot的embeded tomcat。 这里有个例子可以参考: https://github.com/huaweicse/HouseApp/tree/master/customer-website 这里使用了spring boot自身的web容器，页面按照spring boot的要求放到了static目录。 详细可以参考spring boot文档说明。

可以通过https://bbs.huaweicloud.com/blogs/eca98a6f399a11e9bd5a7ca23e93a891了解下与spring boot的差异。

**Comment by zhangaijing** [comment]
> servicecomb缺省不是一个web服务器，只是http服务，提供REST。servicecomb的web模式下，可以使用web容器的功能，比如spring boot的embeded tomcat。 这里有个例子可以参考: https://github.com/huaweicse/HouseApp/tree/master/customer-website 这里使用了spring boot自身的web容器，页面按照spring boot的要求放到了static目录。 详细可以参考spring boot文档说明。
> 
> 可以通过[https://bbs.huaweicloud.com/blogs/eca98a6f399a11e9bd5a7ca23e93a891了解下与spring](https://bbs.huaweicloud.com/blogs/eca98a6f399a11e9bd5a7ca23e93a891%E4%BA%86%E8%A7%A3%E4%B8%8B%E4%B8%8Espring) boot的差异。

感谢你的回复，参考的例子还没细看。请问下：想做一个类似swagger这样的功能，能嵌入到serviceComb项目中（只要在serviceComb项目中MAVEN进来（swagger jar包）就可以直接访问swagger里的页面），该如何实现？？
![image](https://user-images.githubusercontent.com/16713552/61627037-65e1da80-acb1-11e9-8a0d-6a612c777b65.png)

**Comment by liubao68** [comment]
可以查看开发指南inspector功能，servicecomb已经实现了查看swagger的功能

**Comment by zhangaijing** [comment]
> 可以查看开发指南inspector功能，servicecomb已经实现了查看swagger的功能

您好！未找到开发指南inspector功能，能提供下链接地址吗？

**Comment by yhs0092** [comment]
@zhangaijing  看看这篇 [Javachaiss1.2.0新特性解读 |使用inspector功能查看和管理契约](https://mp.weixin.qq.com/s?__biz=MzUxNTEwNTg5Mg==&mid=2247487265&idx=1&sn=0d605687b416a01d2c5d476bc2c5e95b&chksm=f9bafa2acecd733c6ef112f1a2c485ba08a637f400dcab14ae9ee4cd3c56533dc43974ce2882&token=418283571&lang=zh_CN#rd)

**Comment by zhangaijing** [comment]
> 可以查看开发指南inspector功能，servicecomb已经实现了查看swagger的功能

不好意思，问题描述的有问题。是这样的我们公司用的是servicecomb，我已经写好一个辅助工具带UI(HTML)页面，打成JAR包，在springboot项目中依赖这个JAR包能可以访问包里的HTML页面，但把这个JAR加入到公司的servicecomb项目中，该JAR包中的HTML页面无法访问。所以请问下在servicecomb项目中如何解决静态页面访问问题？访问下出现如下报错信息：.OperationLocator >> locate path failed, status:Not Found, http method:GET, path:/view.html/

**Comment by yhs0092** [comment]
你说的辅助工具是运行于Web容器环境的吗？SpringBoot打成可执行jar包运行的话，默认是跑在一个内嵌的Tomcat里的。如果你的辅助工具需要依赖这么一个Web容器，那么它就无法在完全不修改代码及配置的情况下直接运行于ServiceComb-Java-Chassis默认开发模式了，因为java-chassis默认的传输方式是REST over Vertx的，也就是说它底层依赖的HTTP服务器不是Tomcat之类的Web服务器，而是Vertx。
建议参考一下ServiceComb-Java-Chassis的文档，[REST over Vertx传输方式](https://docs.servicecomb.io/java-chassis/zh_CN/transports/rest-over-vertx.html) 和 [REST over Servlet传输方式](https://docs.servicecomb.io/java-chassis/zh_CN/transports/rest-over-servlet.html)。

对于你的场景，比较简单的方法可能是把你的服务的传输方式改为 REST over Servlet 的，不过这需要你打war包放在独立的Tomcat里运行，或者考虑 [SpringBoot+ServiceComb-Java-Chassis 的web开发方式](https://docs.servicecomb.io/java-chassis/zh_CN/using-java-chassis-in-spring-boot/web-application.html)，依赖SpringBoot的功能，你仍然可以打出一个可执行jar包来运行你的服务，底层的服务端传输部分仍然沿用了SpringBoot的配置。
或者如果你想彻底使用java-chassis框架来做，不想用SpringBoot了的话，那么可以参考我们的inspector功能，看看我们框架里`org.apache.servicecomb.inspector.internal.InspectorImpl`类的`getStaticResource`方法是怎么做的，这里实际上是把静态页面请求当成了[文件下载](https://docs.servicecomb.io/java-chassis/zh_CN/general-development/file-download.html)来处理的。

**Comment by liubao68** [comment]
Close old issues. Please feel free to create a new one when meet the problem again.
