### ISSUE TITLE
云服务器上 microservice rest配置不支持公网IP

### ISSUE THREAD

**Issue by brankLY** [apache/servicecomb-java-chassis#1276]
在使用云服务器进行微服务部署时，在microservice.yaml中配置rest项去sc注册，目前不支持配置公网IP，服务启动验证时会检查rest配置项是否为本地配置，但云服务器的公网IP配置项不可以本地检查，该场景无法实现，若配置本地ip，在跨微服务调用时，通过sc拿到的endpoint为内网ip，无法进行跨服务器调用

**Comment by yhs0092** [comment]
建议参考一下这篇资料   [服务监听地址和发布地址](https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/listen-address-and-publish-address.html)。
一般大家配置的`servicecomb.rest.address`是监听地址，而实际注册到sc的endpoint是由发布地址决定的。平常大家没有配置发布地址，发布地址是由Java-Chassis框架从监听地址推断出来的。如果不满足你的场景的话，也可以试试直接配置`servicecomb.service.publishAddress`来显式定义发布地址。

**Comment by brankLY** [comment]
感谢，已解决
