### ISSUE TITLE
cse 下载的sdk demo怎么用responseEntity返回自定义的headers和httpstatus

### ISSUE THREAD

**Issue by twotwodeng** [apache/servicecomb-java-chassis#1278]
1. 代码

@RequestMapping(value = "/helloworld",
            produces = { "application/json" },method = RequestMethod.POST)
    public  ResponseEntity<String> helloworldFail2(HttpServletRequest request,String body) {
        HttpHeaders headers = new HttpHeaders();
        headers.add("test","test");
        return new ResponseEntity<>("test",headers,HttpStatus.BAD_REQUEST);
    }

2. 结果 

status code是 590
{
"message": "Cse Internal Server Error"
}

**Comment by liubao68** [comment]
可以的
```
  @ResponseHeaders({@ResponseHeader(name = "h1", response = String.class),
      @ResponseHeader(name = "h2", response = String.class)})
  @RequestMapping(path = "/responseEntity", method = RequestMethod.POST)
  public ResponseEntity<Date> responseEntity(InvocationContext c1, @RequestAttribute("date") Date date) {
    HttpHeaders headers = new HttpHeaders();
    headers.add("h1", "h1v " + c1.getContext().get(Const.SRC_MICROSERVICE));

    InvocationContext c2 = ContextUtils.getInvocationContext();
    headers.add("h2", "h2v " + c2.getContext().get(Const.SRC_MICROSERVICE));

    return new ResponseEntity<>(date, headers, HttpStatus.ACCEPTED);
  }
```

需要注意ServiceComb是“编译时语义”, 即接口声明的时候，需要明确其语义。 和Spring MVC是有些差异的。

相关例子：
https://docs.servicecomb.io/java-chassis/zh_CN/general-development/error-handling.html
https://github.com/apache/servicecomb-java-chassis/blob/master/integration-tests/

与Spring MVC的差异说明：
https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/springmvc.html

编译时语义的一些背景：
https://zhuanlan.zhihu.com/p/75348817

**Comment by liubao68** [comment]
Close old issues. Please feel free to create a new one when meet the problem again.
