### ISSUE TITLE
watcher connect to service center server failed  

### ISSUE THREAD

**Issue by Fang57** [apache/servicecomb-java-chassis#1279]
"message": "watcher connect to service center server failed, microservice 7719c975dd58e354fdd9c0902308f01079cb1e0f, Websocket connection attempt returned HTTP status code 401",
    "loggerFqcn": "org.apache.logging.slf4j.Log4jLogger",
    "level": "ERROR",
    "@timestamp": "2019-07-26T09:00:37.762Z",
    "thread": "registry-vert.x-eventloop-thread-2",
    "loggerName": "org.apache.servicecomb.serviceregistry.client.http.ServiceRegistryClientImpl",

在项目启动后，会出现此类日志，请问这个有谁知道原因吗

**Comment by liubao68** [comment]
可以试试配置watch=false

参考：https://huaweicse.github.io/cse-java-chassis-doc/servicecomb-using-cse/connect-service-center.html . 

通常是网络设置问题，经过网关的情况下，一般不支持watch，只有服务中心和微服务在局域网内直达的时候开启watch。

**Comment by liubao68** [comment]
Close old issue. Please feel free to create a new one.
