### ISSUE TITLE
网关中参数丢失

### ISSUE THREAD

**Issue by HsbGitHub** [apache/servicecomb-java-chassis#1280]
普通的get请求，比如:
http://xx:port/gateway/h-mdata/data_main_op_log/list?pageNo=1&pageSize=10&appKey=7ab928574cf24c0fa6cf55c8cfec26c1&modelTbName=&opType=
在微服务网关HttpServerFilter的自定义过滤其中，appKey参数丢失。
![image](https://user-images.githubusercontent.com/9192706/61945938-d8192e80-afd3-11e9-9dbc-23f7a1351cf9.png)

其中还有一个问题是，queryParams中的entries 从0，1，2  直接到11了。
大佬帮忙分析下，谢谢~

**Comment by liubao68** [comment]
ServiceComb的gateway是根据契约转发的，接口里面未定义的请求会丢弃。 
如果需要传递额外参数，可以通过InvocationContext，参考认证鉴权的例子. 先把额外参数从HttpServerFilter获取出来，放到InvocationContext里面，然后使用的地方从InvocationContext获取。 

参考：
https://github.com/apache/servicecomb-fence/blob/master/api/edge-service/endpoint/src/main/java/org/apache/servicecomb/authentication/edge/AuthenticationFilter.java
https://docs.servicecomb.io/java-chassis/zh_CN/general-development/context.html

第二个问题，java数据结构存储的问题（Hash)

**Comment by HsbGitHub** [comment]
非常感谢~  确实是契约中没定义，导致。
