### ISSUE TITLE
mvn clean install -Psamples -DskipTests	报错

### ISSUE THREAD

**Issue by yangquanli** [apache/servicecomb-java-chassis#1285]
按照 Spring MVC 的配置指导第二步“Start provider service by maven” ，执行mvn clean install -Psamples -DskipTests 报错，
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.931 s
[INFO] Finished at: 2019-07-31T11:19:20+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project codefirst-provider: Could not resolve dependencies for project org.apache.servicecomb.samples:codefirst-provider:jar:1.3.0-SNAPSHOT: The following artifacts could not be resolved: org.apache.servicecomb:provider-pojo:jar:1.3.0-SNAPSHOT, org.apache.servicecomb:provider-springmvc:jar:1.3.0-SNAPSHOT, org.apache.servicecomb:transport-highway:jar:1.3.0-SNAPSHOT, org.apache.servicecomb:transport-rest-vertx:jar:1.3.0-SNAPSHOT: Could not find artifact org.apache.servicecomb:provider-pojo:jar:1.3.0-SNAPSHOT in RepoMirror (https://repo.huaweicloud.com/repository/maven/) -> [Help 1]

去远程华为镜像库中搜索，发现  java-chassis-dependencies 最高只有1.2.1版本，而samples中要求的是1.3.0-SNAPSHOT。而 maven仓库的地址设置是按照 serviceCom 开发者指南文档配置的。

**Comment by liubao68** [comment]
你执行命令的目录是哪个？如果下载servicecomb-java-chassis源码，可以在根目录执行maven clean install。

**Comment by liubao68** [comment]
我们将samples移动到[servicecomb-samples](https://github.com/apache/servicecomb-samples/tree/master/java-chassis-samples)项目了。 直接使用release版本。可以试试。
