### ISSUE TITLE
下载接口在返回请求头中设置Content-Length，但是通过edge调用该接口，返回请求头中没有Content-Length

### ISSUE THREAD

**Issue by HoyerIsAlexander** [apache/servicecomb-java-chassis#1286]
当前使用的版本：1.1.0.B036

问题现象：服务中有一些播放音频的功能，后台下载音频内容的接口在返回请求头中设置Content-Length，但是通过edge调用该下载接口，返回请求头中没有Content-Length，导致使用部分播放插件出现功能问题

查询社区发现edge中会去掉Content-Length的请求头，请问这个是出于什么考虑，如果服务中需要这个请求头如何规避？

**Comment by yhs0092** [comment]
ServiceComb-Java-Chassis并不会去掉`Content-Length`头，而是根据用户返回的消息自动进行了设置，我们不建议用户自行设置Content-Length。下载文件接口返回的结果通常会被设置为分块传输的，可以看看你抓到的响应里是不是有`Transfer-Encoding: chunked`这样的header

**Comment by liubao68** [comment]
对于文件等类型，或者返回内容较大，使用chunked编码是非常常见的。使用者应该需要能够处理这种常见的HTTP格式。

**Comment by liubao68** [comment]
Close old issue. Please feel free to create a new one.

**Comment by GalileoFinchDudi** [comment]
问题现象：服务中下载文件资源，会自动追加`Transfer-Encoding: chunked`这样的header，但是他会增加两次，从哪可以控制只增加一次呢？因为我们的网关对header要求比较严格，两个这个key会引发报错。
![image](https://user-images.githubusercontent.com/17262882/89998931-bbc06080-dcc0-11ea-9954-a1db4408ae53.png)
