### ISSUE TITLE
客户端用服务端接口，返回体的PO类必须与服务端完全保持一致问题

### ISSUE THREAD

**Issue by jinyule** [apache/servicecomb-java-chassis#1287]
目前发现客户端用服务端接口，返回体的PO必须与服务端完全保持，尽管按json定义好了PO类，但仍会报强转失败

**Comment by liubao68** [comment]
当前版本是这样的，正在优化这个能力。

**Comment by liubao68** [comment]
参考 ： https://github.com/apache/servicecomb-java-chassis/issues/1413
