### ISSUE TITLE
哪位大佬帮忙看看，Servicecomb无法集成CAS实现单点登录吗？急，在线等！！！

### ISSUE THREAD

**Issue by zttAsoiaf** [apache/servicecomb-java-chassis#1303]

**Comment by wangqj** [comment]
可以参考一个demo，jwt实现的，
https://github.com/servicestage-demo/distributed-login-authz
cas实现的话同理，只要在APIGateway里拦截请求，验证token即可

**Comment by willard-kali** [comment]
可以参考pac4j-cas的实现，
https://github.com/pac4j/pac4j/tree/master/pac4j-cas

**Comment by liubao68** [comment]
Close old issue. Please feel free to create a new one.
