### ISSUE TITLE
如何搭建一个属于自己项目的edge网管，必要配置有哪些？路由规则在哪里定义？希望大神能给一个最简单的网关例子最好有详细步骤和注释！

### ISSUE THREAD

**Issue by luhuaitong** [apache/servicecomb-java-chassis#1308]
社区的demo-edge 项目下载下来，服务都可以运行，注册中心也有服务，但是consumer启动的时候报404错误，而且找不到服务的入口！！很苦恼，看了差不多一个月了，但是总是感觉还没入门，项目代码里面很多实现类不知道思路，阅读不同，而且很多注释也没有见过，也不知道起什么作用！！
望哪位大神给一个最简单的edge网关程序，包含最基础的功能就可以啦

**Comment by yhs0092** [comment]
EdgeService网关的开发方式与普通微服务基本一致，不同点主要是：
- pom文件中需要引入edge-core依赖包
- microservice.yaml配置文件里增加请求转发规则的配置，具体配置内容取决于你使用的是`DefaultEdgeDispatcher`还是`URLMappedEdgeDispatcher`做转发

可以参考这里的[微服务培训课程](https://education.huaweicloud.com:8443/courses/course-v1:HuaweiX+CBUCNXP012+Self-paced/courseware/da725ede26794694a621b8088a858743/f840404cbae3467baf17b3ab8452ca53/)看看，demo工程压缩包可以在页面上下载到。你也可以从[这里](https://gitee.com/yhs0092/demo-training21days-publish/commits/day6_homework) clone 到全部demo工程源码。

**Comment by luhuaitong** [comment]
请问  AK  SK   我应该怎么设置，你这个服务注册中心怎么用啊

**Comment by DongJigong** [comment]
servicecenter is written by go language, please download source code and find the service-center-start.sh.If your os is windows, just click it.

**Comment by liubao68** [comment]
Close old issue. Please feel free to create a new one.
