### ISSUE TITLE
ServiceComb服务中心如何搭建集群？？有哪位大神做过可以分享一下集群实现服务中心具体该怎么操作，怎么配置？

### ISSUE THREAD

**Issue by luhuaitong** [apache/servicecomb-java-chassis#1309]

**Comment by msnetc** [comment]
请参考文档：在集群模式下部署服务中心（Service-Center）
https://docs.servicecomb.io/service-center/zh_CN/sc-cluster.html

**Comment by liubao68** [comment]
Close old issue. Please feel free to create a new one.
