### ISSUE TITLE
servciecomb 微服务提供者和消费者应当如何实现多个实例！用springcloud 那样的方式同样的项目，同一个服务名的项目配置多份然后启动多个容器可以吗

### ISSUE THREAD

**Issue by luhuaitong** [apache/servicecomb-java-chassis#1310]
spring cloud 服务提供者 可以通过启动两个容器，但是微服务名称相同的方式可以提供多个实例！
而且还可以通过多个main方法，配置多配置文件，修改下端口号也可以启动多个实例！
servicecomb 可以这样做嘛？怎么做服务中心的集群以及服务的集群实现，哪位大神做过啊
可以给实现的具体步骤和代码嘛，谢谢啦！！

**Comment by liubao68** [comment]
启动多个实例是简单的，保证端口号不冲突即可。

**Comment by liubao68** [comment]
如果期望使用spring boot多profile的功能，也可以将java-chassis运行于spring boot 2之上， 参考： https://github.com/apache/servicecomb-samples/tree/master/dependency_management/springboot2/src/main/resources

**Comment by yhs0092** [comment]
微服务开发框架都是支持多实例启动的，主要是要防止端口冲突。你可以通过环境变量、system property之类的方式修改各个微服务实例监听的端口号，就可以做到本地多实例启动了
配置的使用方法可以参考[这里](https://education.huaweicloud.com:8443/courses/course-v1:HuaweiX+CBUCNXP012+Self-paced/courseware/da725ede26794694a621b8088a858743/b5b553d0380a4e91a813bedfbbfcd091/)

**Comment by liubao68** [comment]
Close old issue, please feel free to create new one if you meet the problem again.
