### ISSUE TITLE
Servciecomb - pack 项目如何引入到自己项目中，分布式事务如何管理，哪位大神做过啊，望分享经验

### ISSUE THREAD

**Issue by luhuaitong** [apache/servicecomb-java-chassis#1311]

**Comment by WillemJiang** [comment]
这是ServiceComb-Pack的相关的问题，你可以参考我们的[使用文档](https://github.com/apache/servicecomb-pack/blob/master/docs/user_guide_zh.md)。
以及 [demo](https://github.com/apache/servicecomb-pack/tree/master/demo)实例来集成到你的项目中。


如果有其他问题欢迎到[ServiceComb-Pack](https://github.com/apache/servicecomb-pack) 提问题。

**Comment by liubao68** [comment]
Close old issue. Please feel free to create a new one.
