### ISSUE TITLE
 cse如何定义Springboot的HandlerInterceptor拦截器。

### ISSUE THREAD

**Issue by ZhuhuiHe** [apache/servicecomb-java-chassis#1314]
maven：
 <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency> 
<dependency>
            <groupId>org.apache.servicecomb</groupId>
            <artifactId>spring-boot-starter-provider</artifactId>
        </dependency>

定义拦截器后 工程无法启动。
这个应该怎么解决。

**Comment by yhs0092** [comment]
SpringBoot+Java-Chassis开发方式有两种，分别是[Java应用开发方式](https://docs.servicecomb.io/java-chassis/zh_CN/using-java-chassis-in-spring-boot/java-application.html)和[Web开发方式](https://docs.servicecomb.io/java-chassis/zh_CN/using-java-chassis-in-spring-boot/web-application.html)。
根据你的描述，由于引用了`spring-boot-starter-provider`依赖包，你的服务应该是使用的Java应用开发方式，这种方式下你的服务运行在Vertx上，不是SpringBoot提供的内嵌Tomcat上，所以自定义的用于Tomcat的拦截器也是没办法生效的。
至于工程无法启动的问题，建议你先按照java-chassis文档资料做一下调整，再看看问题还存不存在。

**Comment by wangqj** [comment]
怀疑你没配置好，给你个参考https://github.com/servicestage-demo/distributed-login-authz/blob/master/example/src/main/java/com/yyy/service1/config/InterceptorConfiguration.java

**Comment by liubao68** [comment]
Close old issue, please feel free to create new one if you meet the problem again.
