### ISSUE TITLE
ServiceComb Java-Chassis的tracing组件兼容问题

### ISSUE THREAD

**Issue by WillemJiang** [apache/servicecomb-java-chassis#1317]
基于ServiceComb的微服务能否兼容pinpoint？ 自有的tracing组件能否停用？

**Comment by liubao68** [comment]
ServiceComb通过集成handler-tracing模块的方式使用zipkin， 此外没集成其他的tracing机制。不存在停用的说法。

**Comment by liubao68** [comment]
Close old issue, please feel free to create new one if you meet the problem again.
