### ISSUE TITLE
Edge 注册在service-center 地址是 127.0.0.1：30100上报错，服务启动不成功

### ISSUE THREAD

**Issue by luhuaitong** [apache/servicecomb-java-chassis#1321]
错误日志：
"C:\Program Files\Java\jdk1.8.0_101\bin\java" -javaagent:D:\interIDEA\lib\idea_rt.jar=60732:D:\interIDEA\bin -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_101\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\rt.jar;D:\ServiceCombCode\TDGL\tdgl-edge\target\classes;D:\tool\apache-maven-3.3.9\repository\org\apache\servicecomb\edge-core\1.0.0-m2\edge-core-1.0.0-m2.jar;D:\tool\apache-maven-3.3.9\repository\org\apache\servicecomb\transport-rest-vertx\1.0.0-m2\transport-rest-vertx-1.0.0-m2.jar;D:\tool\apache-maven-3.3.9\repository\org\apache\servicecomb\transport-rest-client\1.0.0-m2\transport-rest-client-1.0.0-m2.jar;D:\tool\apache-maven-3.3.9\repository\org\apache\servicecomb\foundation-vertx\1.0.0-m2\foundation-vertx-1.0.0-m2.jar;D:\tool\apache-maven-3.3.9\repository\io\vertx\vertx-core\3.5.0\vertx-core-3.5.0.jar;D:\tool\apache-maven-3.3.9\repository\io\netty\netty-resolver-dns\4.1.24.Final\netty-resolver-dns-4.1.24.Final.jar;D:\tool\apache-maven-3.3.9\repository\io\netty\netty-codec-dns\4.1.24.Final\netty-codec-dns-4.1.24.Final.jar;D:\tool\apache-maven-3.3.9\repository\io\vertx\vertx-web\3.5.0\vertx-web-3.5.0.jar;D:\tool\apache-maven-3.3.9\repository\io\vertx\vertx-auth-common\3.5.0\vertx-auth-common-3.5.0.jar;D:\tool\apache-maven-3.3.9\repository\io\vertx\vertx-bridge-common\3.5.0\vertx-bridge-common-3.5.0.jar;D:\tool\apache-maven-3.3.9\repository\org\apache\servicecomb\foundation-ssl\1.0.0-m2\foundation-ssl-1.0.0-m2.jar;D:\tool\apache-maven-3.3.9\repository\io\netty\netty-tcnative-boringssl-static\2.0.7.Final\netty-tcnative-boringssl-static-2.0.7.Final.jar;D:\tool\apache-maven-3.3.9\repository\org\apache\servicecomb\common-rest\1.0.0-m2\common-rest-1.0.0-m2.jar;D:\tool\apache-maven-3.3.9\repository\javax\servlet\javax.servlet-api\3.1.0\javax.servlet-api-3.1.0.jar;D:\tool\apache-maven-3.3.9\repository\javax\inject\javax.inject\1\javax.inject-1.jar;D:\tool\apache-maven-3.3.9\repository\org\springframework\spring-aspects\4.3.16.RELEASE\spring-aspects-4.3.16.RELEASE.jar;D:\tool\apache-maven-3.3.9\repository\org\aspectj\aspectjweaver\1.8.8\aspectjweaver-1.8.8.jar;D:\tool\apache-maven-3.3.9\repository\org\apache\servicecomb\handler-loadbalance\1.0.0-m2\handler-loadbalance-1.0.0-m2.jar;D:\tool\apache-maven-3.3.9\repository\org\apache\servicecomb\java-chassis-core\1.0.0-m2\java-chassis-core-1.0.0-m2.jar;D:\tool\apache-maven-3.3.9\repository\org\apache\servicecomb\service-registry\1.0.0-m2\service-registry-1.0.0-m2.jar;D:\tool\apache-maven-3.3.9\repository\org\apache\servicecomb\foundation-config\1.0.0-m2\foundation-config-1.0.0-m2.jar;D:\tool\apache-maven-3.3.9\repository\org\springframework\spring-beans\4.3.16.RELEASE\spring-beans-4.3.16.RELEASE.jar;D:\tool\apache-maven-3.3.9\repository\org\springframework\spring-core\4.3.16.RELEASE\spring-core-4.3.16.RELEASE.jar;D:\tool\apache-maven-3.3.9\repository\org\yaml\snakeyaml\1.16\snakeyaml-1.16.jar;D:\tool\apache-maven-3.3.9\repository\net\sf\json-lib\json-lib\2.4\json-lib-2.4-jdk15.jar;D:\tool\apache-maven-3.3.9\repository\commons-beanutils\commons-beanutils\1.9.2\commons-beanutils-1.9.2.jar;D:\tool\apache-maven-3.3.9\repository\commons-collections\commons-collections\3.2.2\commons-collections-3.2.2.jar;D:\tool\apache-maven-3.3.9\repository\net\sf\ezmorph\ezmorph\1.0.6\ezmorph-1.0.6.jar;D:\tool\apache-maven-3.3.9\repository\org\apache\httpcomponents\httpclient\4.5.2\httpclient-4.5.2.jar;D:\tool\apache-maven-3.3.9\repository\org\apache\httpcomponents\httpcore\4.4.9\httpcore-4.4.9.jar;D:\tool\apache-maven-3.3.9\repository\commons-codec\commons-codec\1.10\commons-codec-1.10.jar;D:\tool\apache-maven-3.3.9\repository\io\netty\netty-codec\4.1.24.Final\netty-codec-4.1.24.Final.jar;D:\tool\apache-maven-3.3.9\repository\io\netty\netty-codec-http\4.1.24.Final\netty-codec-http-4.1.24.Final.jar;D:\tool\apache-maven-3.3.9\repository\io\netty\netty-codec-http2\4.1.24.Final\netty-codec-http2-4.1.24.Final.jar;D:\tool\apache-maven-3.3.9\repository\io\netty\netty-common\4.1.24.Final\netty-common-4.1.24.Final.jar;D:\tool\apache-maven-3.3.9\repository\io\netty\netty-handler\4.1.24.Final\netty-handler-4.1.24.Final.jar;D:\tool\apache-maven-3.3.9\repository\io\netty\netty-buffer\4.1.24.Final\netty-buffer-4.1.24.Final.jar;D:\tool\apache-maven-3.3.9\repository\io\netty\netty-codec-socks\4.1.24.Final\netty-codec-socks-4.1.24.Final.jar;D:\tool\apache-maven-3.3.9\repository\io\netty\netty-handler-proxy\4.1.24.Final\netty-handler-proxy-4.1.24.Final.jar;D:\tool\apache-maven-3.3.9\repository\io\netty\netty-resolver\4.1.24.Final\netty-resolver-4.1.24.Final.jar;D:\tool\apache-maven-3.3.9\repository\io\netty\netty-transport\4.1.24.Final\netty-transport-4.1.24.Final.jar;D:\tool\apache-maven-3.3.9\repository\org\apache\servicecomb\foundation-common\1.0.0-m2\foundation-common-1.0.0-m2.jar;D:\tool\apache-maven-3.3.9\repository\com\fasterxml\jackson\dataformat\jackson-dataformat-xml\2.9.5\jackson-dataformat-xml-2.9.5.jar;D:\tool\apache-maven-3.3.9\repository\com\fasterxml\jackson\module\jackson-module-jaxb-annotations\2.8.11\jackson-module-jaxb-annotations-2.8.11.jar;D:\tool\apache-maven-3.3.9\repository\org\codehaus\woodstox\stax2-api\3.1.4\stax2-api-3.1.4.jar;D:\tool\apache-maven-3.3.9\repository\com\fasterxml\woodstox\woodstox-core\5.0.3\woodstox-core-5.0.3.jar;D:\tool\apache-maven-3.3.9\repository\org\springframework\spring-context\4.3.16.RELEASE\spring-context-4.3.16.RELEASE.jar;D:\tool\apache-maven-3.3.9\repository\org\springframework\spring-aop\4.3.16.RELEASE\spring-aop-4.3.16.RELEASE.jar;D:\tool\apache-maven-3.3.9\repository\org\springframework\spring-expression\4.3.16.RELEASE\spring-expression-4.3.16.RELEASE.jar;D:\tool\apache-maven-3.3.9\repository\log4j\log4j\1.2.17\log4j-1.2.17.jar;D:\tool\apache-maven-3.3.9\repository\javax\ws\rs\javax.ws.rs-api\2.0.1\javax.ws.rs-api-2.0.1.jar;D:\tool\apache-maven-3.3.9\repository\commons-io\commons-io\2.4\commons-io-2.4.jar;D:\tool\apache-maven-3.3.9\repository\org\apache\servicecomb\swagger-invocation-core\1.0.0-m2\swagger-invocation-core-1.0.0-m2.jar;D:\tool\apache-maven-3.3.9\repository\org\apache\servicecomb\swagger-generator-core\1.0.0-m2\swagger-generator-core-1.0.0-m2.jar;D:\tool\apache-maven-3.3.9\repository\io\swagger\swagger-core\1.5.12\swagger-core-1.5.12.jar;D:\tool\apache-maven-3.3.9\repository\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar;D:\tool\apache-maven-3.3.9\repository\com\fasterxml\jackson\dataformat\jackson-dataformat-yaml\2.9.5\jackson-dataformat-yaml-2.9.5.jar;D:\tool\apache-maven-3.3.9\repository\io\swagger\swagger-models\1.5.12\swagger-models-1.5.12.jar;D:\tool\apache-maven-3.3.9\repository\io\swagger\swagger-annotations\1.5.12\swagger-annotations-1.5.12.jar;D:\tool\apache-maven-3.3.9\repository\org\apache\servicecomb\common-javassist\1.0.0-m2\common-javassist-1.0.0-m2.jar;D:\tool\apache-maven-3.3.9\repository\org\javassist\javassist\3.18.1-GA\javassist-3.18.1-GA.jar;D:\tool\apache-maven-3.3.9\repository\io\zipkin\brave\brave\4.13.1\brave-4.13.1.jar;D:\tool\apache-maven-3.3.9\repository\io\zipkin\zipkin2\zipkin\2.4.2\zipkin-2.4.2.jar;D:\tool\apache-maven-3.3.9\repository\io\zipkin\reporter2\zipkin-reporter\2.5.0\zipkin-reporter-2.5.0.jar;D:\tool\apache-maven-3.3.9\repository\com\netflix\ribbon\ribbon\2.2.2\ribbon-2.2.2.jar;D:\tool\apache-maven-3.3.9\repository\com\netflix\ribbon\ribbon-transport\2.2.2\ribbon-transport-2.2.2.jar;D:\tool\apache-maven-3.3.9\repository\io\reactivex\rxnetty-contexts\0.4.9\rxnetty-contexts-0.4.9.jar;D:\tool\apache-maven-3.3.9\repository\io\reactivex\rxnetty-servo\0.4.9\rxnetty-servo-0.4.9.jar;D:\tool\apache-maven-3.3.9\repository\com\netflix\hystrix\hystrix-core\1.5.10\hystrix-core-1.5.10.jar;D:\tool\apache-maven-3.3.9\repository\org\hdrhistogram\HdrHistogram\2.1.9\HdrHistogram-2.1.9.jar;D:\tool\apache-maven-3.3.9\repository\io\reactivex\rxnetty\0.4.9\rxnetty-0.4.9.jar;D:\tool\apache-maven-3.3.9\repository\commons-configuration\commons-configuration\1.10\commons-configuration-1.10.jar;D:\tool\apache-maven-3.3.9\repository\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;D:\tool\apache-maven-3.3.9\repository\com\google\guava\guava\19.0\guava-19.0.jar;D:\tool\apache-maven-3.3.9\repository\com\netflix\ribbon\ribbon-loadbalancer\2.2.2\ribbon-loadbalancer-2.2.2.jar;D:\tool\apache-maven-3.3.9\repository\com\netflix\netflix-commons\netflix-statistics\0.1.1\netflix-statistics-0.1.1.jar;D:\tool\apache-maven-3.3.9\repository\org\slf4j\slf4j-api\1.7.7\slf4j-api-1.7.7.jar;D:\tool\apache-maven-3.3.9\repository\com\netflix\servo\servo-core\0.10.1\servo-core-0.10.1.jar;D:\tool\apache-maven-3.3.9\repository\com\netflix\servo\servo-internal\0.10.1\servo-internal-0.10.1.jar;D:\tool\apache-maven-3.3.9\repository\com\netflix\netflix-commons\netflix-commons-util\0.1.1\netflix-commons-util-0.1.1.jar;D:\tool\apache-maven-3.3.9\repository\com\netflix\ribbon\ribbon-core\2.2.2\ribbon-core-2.2.2.jar;D:\tool\apache-maven-3.3.9\repository\com\netflix\archaius\archaius-core\0.7.3\archaius-core-0.7.3.jar;D:\tool\apache-maven-3.3.9\repository\com\google\code\findbugs\jsr305\3.0.1\jsr305-3.0.1.jar;D:\tool\apache-maven-3.3.9\repository\com\fasterxml\jackson\core\jackson-annotations\2.9.5\jackson-annotations-2.9.5.jar;D:\tool\apache-maven-3.3.9\repository\com\fasterxml\jackson\core\jackson-core\2.9.5\jackson-core-2.9.5.jar;D:\tool\apache-maven-3.3.9\repository\com\fasterxml\jackson\core\jackson-databind\2.9.5\jackson-databind-2.9.5.jar;D:\tool\apache-maven-3.3.9\repository\io\reactivex\rxjava\1.1.6\rxjava-1.1.6.jar;D:\tool\apache-maven-3.3.9\repository\commons-lang\commons-lang\2.6\commons-lang-2.6.jar;D:\tool\apache-maven-3.3.9\repository\org\hibernate\validator\hibernate-validator\6.0.2.Final\hibernate-validator-6.0.2.Final.jar;D:\tool\apache-maven-3.3.9\repository\org\jboss\logging\jboss-logging\3.3.2.Final\jboss-logging-3.3.2.Final.jar;D:\tool\apache-maven-3.3.9\repository\com\fasterxml\classmate\1.3.4\classmate-1.3.4.jar;D:\tool\apache-maven-3.3.9\repository\javax\validation\validation-api\2.0.0.Final\validation-api-2.0.0.Final.jar" com.csk.edgeMain
log4j:WARN No appenders could be found for logger (org.springframework.core.io.support.PathMatchingResourcePatternResolver).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2019-09-05 14:42:08,747 [INFO] Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@58ceff1: startup date [Thu Sep 05 14:42:08 CST 2019]; root of context hierarchy org.springframework.context.support.AbstractApplicationContext.prepareRefresh(AbstractApplicationContext.java:583)
2019-09-05 14:42:09,040 [INFO] Loading XML bean definitions from URL [jar:file:/D:/tool/apache-maven-3.3.9/repository/org/apache/servicecomb/transport-rest-client/1.0.0-m2/transport-rest-client-1.0.0-m2.jar!/META-INF/spring/cse.transport.rest.bean.xml] org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:317)
2019-09-05 14:42:09,759 [INFO] Loading XML bean definitions from URL [jar:file:/D:/tool/apache-maven-3.3.9/repository/org/apache/servicecomb/foundation-vertx/1.0.0-m2/foundation-vertx-1.0.0-m2.jar!/META-INF/spring/cse.bean.xml] org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:317)
2019-09-05 14:42:09,871 [INFO] Loading XML bean definitions from URL [jar:file:/D:/tool/apache-maven-3.3.9/repository/org/apache/servicecomb/handler-loadbalance/1.0.0-m2/handler-loadbalance-1.0.0-m2.jar!/META-INF/spring/cse.bean.xml] org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:317)
2019-09-05 14:42:09,912 [INFO] Loading XML bean definitions from URL [jar:file:/D:/tool/apache-maven-3.3.9/repository/org/apache/servicecomb/java-chassis-core/1.0.0-m2/java-chassis-core-1.0.0-m2.jar!/META-INF/spring/cse.bean.xml] org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:317)
2019-09-05 14:42:11,494 [INFO] Loading XML bean definitions from URL [jar:file:/D:/tool/apache-maven-3.3.9/repository/org/apache/servicecomb/foundation-config/1.0.0-m2/foundation-config-1.0.0-m2.jar!/META-INF/spring/cse.bean.xml] org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:317)
2019-09-05 14:42:11,533 [INFO] Loading XML bean definitions from URL [jar:file:/D:/tool/apache-maven-3.3.9/repository/org/apache/servicecomb/foundation-common/1.0.0-m2/foundation-common-1.0.0-m2.jar!/META-INF/spring/common.bean.xml] org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:317)
2019-09-05 14:42:13,270 [INFO] JSR-330 'javax.inject.Inject' annotation found and supported for autowiring org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.<init>(AutowiredAnnotationBeanPostProcessor.java:155)

Process finished with exit code 1

**Comment by luhuaitong** [comment]
我一直是按照官方步骤来的，其他几个项目都没有问题，用的cloud zuul网关通过测试了
按照官网步骤，加edge 的依赖，写启动类，加配置文件，然后就报错

但是在CSE 上， edge 就可以正常使用

**Comment by luhuaitong** [comment]
我一直是按照官方步骤来的，其他几个项目都没有问题，用的cloud zuul网关通过测试了
按照官网步骤，加edge 的依赖，写启动类，加配置文件，然后就报错

但是在CSE 上， edge 就可以正常使用

**Comment by liubao68** [comment]
Close old issue, please feel free to create new one if you meet the problem again.
