### ISSUE TITLE
controller 层无法使用@Validated注解，而只能使用@Valid注解，导致无法进行group分类，请问怎么解决？

### ISSUE THREAD

**Issue by zttAsoiaf** [apache/servicecomb-java-chassis#1322]
public ApplicationResp update(@NotBlank @PathVariable("project_id") String projectId, @PathVariable long id,**@Validated** @RequestBody ApplicationReq appReq)

**Comment by liubao68** [comment]
java-chassis 使用的是 hibernate validation, 上述机制是 spring validation 提供的功能。 需要分析下是否在 java-chassis 中替换.

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
