### ISSUE TITLE
edge 网关  如何做鉴权服务？ 求相关文档或者demo

### ISSUE THREAD

**Issue by luhuaitong** [apache/servicecomb-java-chassis#1323]
servicecomb 微服务体系有没有对于网管鉴权的支持，有没有相关文档或者demo参考一下啊，哪位大佬望告知谢谢啦！！！

**Comment by liubao68** [comment]
可以参考下： https://github.com/apache/servicecomb-fence

**Comment by liubao68** [comment]
Close old issue, please feel free to create new one if you meet the problem again.
