### ISSUE TITLE
请问service fence 项目源码down下来启动报错！ 网关地址访问静态页面也是404，找不到原因

### ISSUE THREAD

**Issue by luhuaitong** [apache/servicecomb-java-chassis#1325]
请问关于这个项目的细节文档有吗，fence项目社区好像一个人都没有啊

**Comment by yhs0092** [comment]
ServiceComb-Fence的问题建议提到fence的[issue列表](https://github.com/apache/servicecomb-fence/issues)里 : )

**Comment by liubao68** [comment]
Close old issue, please feel free to create new one if you meet the problem again.
