### ISSUE TITLE
servicecomb 限流策略，到达限流条件后 是如何处理。

### ISSUE THREAD

**Issue by ZhuhuiHe** [apache/servicecomb-java-chassis#1333]
https://liubao68.github.io/ReadTheDocDemo/build-provider/configuration/ratelimite-strategy.html。
只提及了如何配置限流策略，可是限流策略 超过最大QPS 后，是直接丢弃请求，还是缓存请求呢。

**Comment by liubao68** [comment]
默认情况下是直接丢弃请求，返回429。详细情况可以查看ConsumerQpsFlowControlHandler或者ProviderQpsFlowControlHandler的代码。

**Comment by liubao68** [comment]
Close old issue, please feel free to create new one if you meet the problem again.
