### ISSUE TITLE
SVC开发模式支持Request，Response，吗？ 做上传和下载功能

### ISSUE THREAD

**Issue by luhuaitong** [apache/servicecomb-java-chassis#1336]
请问servicecomb 支持 request， response，吗？IO流应该怎么用，demo提供的 BIgFile 和 download方法 ，方法有点看不太明白？哪位大神给具体讲讲？ IO 流 在 servicecomb 中的具体应用？

**Comment by beneshadyhw** [comment]
https://docs.servicecomb.io/java-chassis/zh_CN/general-development/file-upload.html

可能是你需要的

**Comment by whuxiari** [comment]
参考了下面的方式写了下载的接口，通过地址栏直接访问URL，可以下载到文件；但是在F12查看却提示“Failed to load response data”
https://docs.servicecomb.io/java-chassis/zh_CN/general-development/file-download.html

![image](https://user-images.githubusercontent.com/9291379/71092323-f6c9cd00-21e1-11ea-9cb1-a980cdc33c0f.png)

`   @RequestMapping(value = "/export", method = RequestMethod.GET)
    @ApiResponses({@ApiResponse(code = 200, response = File.class, message = "Test")})
    public ResponseEntity<FileSystemResource> export() {
        String path = System.getProperty("user.dir");
        String fileName = "userId" + System.currentTimeMillis() + EXCEL_EXT_XLSX;
        String filePath = path + fileName;
        logger.info("Filepath: {}", filePath);
        try {
            FileSystemResource inputStreamSource = getInputStreamSource(filePath, fileName);
            return ResponseEntity.ok()
                .header(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_OCTET_STREAM_VALUE)
                .header(HttpHeaders.CONTENT_DISPOSITION, "attachment;filename=" + fileName)
                .body(inputStreamSource);
        } finally {
            FileUtils.deleteQuietly(FileUtils.getFile(filePath));
        }
    }`

**Comment by liubao68** [comment]
Close old issue, please feel free to create new one if you meet the problem again.
