### ISSUE TITLE
哪位大佬帮忙看看，文件上传报错，servicecomb.uploads.directory已配置，急，在线等！！！

### ISSUE THREAD

**Issue by beneshadyhw** [apache/servicecomb-java-chassis#1337]
报错如下：
exception: "org.springframework.web.multipart.MultipartException"
message: "Could not parse multipart servlet request; nested exception is java.io.IOException: The temporary upload location [/tmp/tomcat.7810722732755196876.38889/work/Tomcat/localhost/ROOT] is not valid"

根据[https://docs.servicecomb.io/java-chassis/zh_CN/general-development/file-upload.html](url)配置，昨天还行的不知道动了哪里。
application.properties相关配置如下：
  uploads:
    directory : Uploads/

**Comment by WillemJiang** [comment]
@beneshadyhw 你的问题怎么解决的？
方便的话写一下回复，这样能够帮助到更多跟你遇到同样问题的朋友。

**Comment by beneshadyhw** [comment]
> @beneshadyhw 你的问题怎么解决的？
> 方便的话写一下回复，这样能够帮助到更多跟你遇到同样问题的朋友。

说起来比较蠢：我微服务的配置文件加了uploads，但是网关的配置没加。调用API的时候经过网关就报错了。
