### ISSUE TITLE
Can not close file when upload file body without the end delimiter

### ISSUE THREAD

**Issue by willard-kali** [apache/servicecomb-java-chassis#1347]
**Step:**
1. use edge service to route REST url request, use class org.apache.servicecomb.transport.rest.vertx.RestBodyHandler to parse request body,including files.
2. server has a REST interface, like Content-Type: multipart/form-data, accept file(s).
3. send a post request to the file upload REST, and use proxy tool to modify the request raw.
use the latest version.

**For example:**
[Normal]
> POST /url/ HTTP/1.x
xxxxxx
Content-Type: multipart/form-data; boundary=--------1122334455
xxxxxx
--------1122334455
...file...
--------1122334455
...file...
--------1122334455--

[Abnormal]
> POST /url/ HTTP/1.x
xxxxxx
Content-Type: multipart/form-data; boundary=--------1122334455
xxxxxx
--------1122334455
...file...
--------1122334455
...file...

Use abnormal body to request, it will be wating to timeout.
I find the NettyFileUpload#addContent param-last is false, it will not into if branch to execute end() method, so the file will not close in endHandler after open by HttpServerFileUploadImpl#streamToFileSystem.
Is there an elegant way to solve this problem?

**Comment by liubao68** [comment]
Why do you need to solve this problem?

**Comment by willard-kali** [comment]
If client always request this abnormal message, it will cause the edge service to die.

**Comment by liubao68** [comment]
We have update netty(4.1.43.RELEASE) and vert.x(3.8.3) to the lasted version. But I am not sure if they solved this problem. Would you mind make your test with the lastest version?

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
