### ISSUE TITLE
对接 Nacos  配置中心

### ISSUE THREAD

**Issue by msnetc** [apache/servicecomb-java-chassis#1354]
nacos的动态配置服务让您能够以中心化、外部化和动态化的方式管理所有环境的配置。动态配置消除了配置变更时重新部署应用和服务的需要。配置中心化管理让实现无状态服务更简单，也让按需弹性扩展服务更容易。
能否提供java-chassis对接Nacos的配置中心的demo?

**Comment by liubao68** [comment]
we do not have this yet. Do you mind contribute the client code ? ServiceComb use archorius API to add dynamic support and examles are https://github.com/apache/servicecomb-java-chassis/tree/master/dynamic-config which already impements support for config-center, servicecomb-kie and Appollo.

**Comment by 160731liupf** [comment]
Hello,I am trying to add this client model,this is pr:https://github.com/apache/servicecomb-java-chassis/pull/1404

**Comment by liubao68** [comment]
> Hello,I am trying to add this client model,this is pr:#1404

Looks great. I see you closed the PR, why?

**Comment by 160731liupf** [comment]
Sorry，I add some new file in config-nacos model，the new pr is :https://github.com/apache/servicecomb-java-chassis/pull/1405

**Comment by liubao68** [comment]
> Sorry，I add some new file in config-nacos model，the new pr is :#1405

Thanks. You can add more commits to the PR if you find something wrong and github will help to integrate new commits to the some PR :-)

**Comment by liubao68** [comment]
Nacos supported， see: https://docs.servicecomb.io/java-chassis/zh_CN/config/general-config/

Close old issues, please feel free to open a new one.
