### ISSUE TITLE
AsyncRestTemplate has deprecated in springframework

### ISSUE THREAD

**Issue by willard-kali** [apache/servicecomb-java-chassis#1361]
`
CseAsyncRestTemplate extends AsyncRestTemplate
`
AsyncRestTemplate Deprecated, as of Spring 5.0, in favor of WebClient.
[https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/client/AsyncRestTemplate.html](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/client/AsyncRestTemplate.html)
when CseAsyncRestTemplate update?

**Comment by liubao68** [comment]
This need further discussion. However you can still use AsyncRestTemplate in servicecomb, the implementation is not dependends on spring and not effected by spring upgrading.

**Comment by liubao68** [comment]
This problem is traced in this [issue](https://issues.apache.org/jira/browse/SCB-1624)

**Comment by liubao68** [comment]
Start from 2.0.0. java-chassis only support spring 5, it's not recommended to use `AsyncRestTemplate`.   Use `CompletableFuture` instead

```
interface GetSessionOperation {
  CompletableFuture<SessionInfo> getSession(String sessionId);
}
```

see a example [here](https://github.com/apache/servicecomb-samples/pull/41/files)
