### ISSUE TITLE
demo版本号不对，编译不通过

### ISSUE THREAD

**Issue by stupidbai** [apache/servicecomb-java-chassis#1362]
![微信图片_20191025213318](https://user-images.githubusercontent.com/18230061/67575420-21158600-f76f-11e9-8844-16f016d28592.png)
![微信图片_20191025213327](https://user-images.githubusercontent.com/18230061/67575432-270b6700-f76f-11e9-924b-115381316792.png)

中心仓缺少1.3版本的jar包，导致本地编译不通过

**Comment by WillemJiang** [comment]
1.3.0 还没有发布（月底应该会发布），建议你改一下版本号。

**Comment by liubao68** [comment]
Close old issue, please feel free to create new one if you meet the problem again.
