### ISSUE TITLE
求助，EventListener 类在新版本里没有了？没有替代的类吗？

### ISSUE THREAD

**Issue by zwwtj2014** [apache/servicecomb-java-chassis#1367]
请问有升级文档吗？

**Comment by liubao68** [comment]
Can you provide the full class name and version ?  I can not find any history info about this change.

**Comment by yhs0092** [comment]
Hello, do you mean [org.apache.servicecomb.core.BootListener](https://github.com/apache/servicecomb-java-chassis/blob/master/core/src/main/java/org/apache/servicecomb/core/BootListener.java)?

**Comment by zwwtj2014** [comment]
`https://github.com/apache/servicecomb-java-chassis/blob/1.0.0/foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/event/EventListener.java` 

Maybe this is inner class, and I should not use it?

**Comment by liubao68** [comment]
This class is intended for internal use only. You may use it with careful.

**Comment by zwwtj2014** [comment]
@liubao68 ok. But  class `EventListener` can not be found in version 1.2.0 . And Is there an alternative class?

**Comment by liubao68** [comment]
@zwwtj2014 I checked the old code, and find no where to use this API, maybe it is deleted for used code. If you still want to use this code, you can use guava api, or you can clone 1.2.0 source code and copy this class to your project.

**Comment by liubao68** [comment]
Close old issue, please feel free to create new one if you meet the problem again.
