### ISSUE TITLE
@Override is not allowed when implementing interfalse method

### ISSUE THREAD

**Issue by lov3r** [apache/servicecomb-java-chassis#1368]
![image](https://user-images.githubusercontent.com/33676682/67839988-d52c5d80-fb2f-11e9-98fe-f4ce6493d9c2.png)

**Comment by liubao68** [comment]
Maybe the IDE is telling you how to fix it.

**Comment by liubao68** [comment]
Close old issue, please feel free to create new one if you meet the problem again.
