### ISSUE TITLE
CseAsyncRestTemplate设置HTTP header未生效

### ISSUE THREAD

**Issue by wangguowei2018** [apache/servicecomb-java-chassis#1403]
ListenableFuture<ResponseEntity<Void>> entity = cseAsyncRestTemplate.postForEntity(url,
new CseHttpEntity<>(msgBody, headers), Void.class);

headers被CSE丢弃，发出去的消息中，不会携带headers中定义的私有头域；标准头域设置也不生效。

我们服务基于SpringBoot开发，现在集成CSE出现这个问题，还请定位解决。谢谢！

**Comment by liubao68** [comment]
ServiceComb的设计不同于Spring MVC，Spring MVC技术建立在servlet基础之上，所以可以直接操作HTTP。 而ServiceComb本质上是基于Open API 的 RPC 框架，而独立于servlet，可以使用非HTTP协议进行通信。传递的参数可能会忽略掉没有在接口中声明的信息。
这个场景需要进一步考虑如何支持。 
传递自定义header，可以考虑实现HttpServerFilter，即在http层处理。 当然如果存在a -> b -> c 这样的调用链中传递，可以考虑使用ServiceComb的[Context](https://docs.servicecomb.io/java-chassis/zh_CN/general-development/context.html)，而不是使用HTTP。

**Comment by zhangchi02** [comment]
fixed in [#1229](https://github.com/apache/servicecomb-java-chassis/pull/1229)

**Comment by liubao68** [comment]
> fixed in [#1229](https://github.com/apache/servicecomb-java-chassis/pull/1229)

Thanks for sharing this.

**Comment by liubao68** [comment]
Fixed in 1.3.0.
