### ISSUE TITLE
java项目怎么与go项目注册到cse上的自定义rest规则相建链

### ISSUE THREAD

**Issue by Fang57** [apache/servicecomb-java-chassis#1407]

**Comment by Fang57** [comment]
在cse上通过注册到schema的方式开放了多个端口，但是其他服务通过cse访问无法访问到自定义schema对应的端口上

**Comment by liubao68** [comment]
你能提供更多细节信息吗，java-chassis是独立设计的RPC框架，如果和其他语言通信，需要其他语言满足很多设计要求。 最简单的要求包括同时在一个服务中心注册服务，注册服务的信息里面包含接口契约信息等。

**Comment by liubao68** [comment]
我找到一个材料介绍go-chassis和java-chassis[互通的例子](https://docs.go-chassis.com/user-guides/java-call-go.html)，可以参考
