### ISSUE TITLE
demo中不存在所说项目

### ISSUE THREAD

**Issue by xhanthow** [apache/servicecomb-java-chassis#1409]
http://servicecomb.apache.org/cn/docs/quick-start/
![image](https://user-images.githubusercontent.com/7291995/69507753-8d51f800-0f6e-11ea-95e4-84d2e2a14cc4.png)
看到commit message才知道。。
![image](https://user-images.githubusercontent.com/7291995/69507767-9a6ee700-0f6e-11ea-9abb-6c86fe476752.png)

**Comment by liubao68** [comment]
I submit a PR for this : https://github.com/apache/servicecomb-website/pull/224

**Comment by liubao68** [comment]
This has been fixed.
