### ISSUE TITLE
资料文档不具备指导作用

### ISSUE THREAD

**Issue by swp10101106** [apache/servicecomb-java-chassis#1411]
https://docs.servicecomb.io/java-chassis/zh_CN/config/general-config.html  根据文档的内容，无法明确指导开发人员进行相关配置，例如配置的文件名称，文件格式，文件路径等。。。。建议细化文档或者发布指到的配置demo，谢谢

**Comment by liubao68** [comment]
Close old issue, please feel free to create new one if you meet the problem again.

**Comment by liubao68** [comment]
2.0.0 文档进行了刷新， [参考](https://docs.servicecomb.io/java-chassis/zh_CN/config/general-config/) 。 有问题欢迎提新问题反馈。
