### ISSUE TITLE
使用Edge Service做边缘服务，如何精细化限流

### ISSUE THREAD

**Issue by tonghualin** [apache/servicecomb-java-chassis#1416]
servicecomb.flowcontrol.Provider.qps.limit.[ServiceName].[Schema].[operation]
限流文档中Schema和operation分别指的什么？是否有示例？方法支持正则吗？

使用Edge Service做边缘服务时候如何对浏览器或者接口调用的请求做根据URL的限流？

**Comment by liubao68** [comment]
[ServiceName].[Schema].[operation]这个其实就是URL，可以先试用一下java-chassis开发一个DEMO试下。每个接口都有对应的schema和operationid

**Comment by liubao68** [comment]
Close old issue, please feel free to create new one if you meet the problem again.
