### ISSUE TITLE
expected: .TooLongFrameException but was :io.vertx.core.VertxException

### ISSUE THREAD

**Issue by surechen** [apache/servicecomb-java-chassis#1417]
![image](https://user-images.githubusercontent.com/7249331/69805579-eabea100-121b-11ea-9c8a-44ba76293a56.png)

![image](https://user-images.githubusercontent.com/7249331/69805608-f5793600-121b-11ea-96a1-ddcb081a6564.png)

![image](https://user-images.githubusercontent.com/7249331/69805616-fb6f1700-121b-11ea-8dd3-8a135a2460e7.png)

![image](https://user-images.githubusercontent.com/7249331/69805649-0a55c980-121c-11ea-9d50-aa5df3f53b8d.png)

这里我跑it-consumer过不了，我发现在类  /transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/http/RestClientInvocation.java处理后
本来是class io.netty.handler.codec.TooLongFrameException错误，经过处理后连接断开，变成了class io.vertx.core.VertxException错误，最后断言判断错误不匹配，不知道我的理解对不对？

**Comment by liubao68** [comment]
你是如何跑测试用例的？下载最新的java-chassis，然后
```
mvn clean install -Pit
```
这样吗？
项目的自动化测试每天都在跑，应该不会出现这种情况。

**Comment by surechen** [comment]
我在arm64上构建，有什么需要特别注意的设置吗？ 执行命令 ：
mvn clean install -B -Pdocker -Pjacoco -Pit

**Comment by liubao68** [comment]
This has been fixed in latest version, you can clone the latest code and try. Please feel free to create a new one if you still got some problem.
