### ISSUE TITLE
本地部署edge能成功转发请求，部署到CCE后，报locate path failed, status:Not Found,

### ISSUE THREAD

**Issue by lastshot-E** [apache/servicecomb-java-chassis#1418]
CCE 容器日志显示SPI已经成功加载dispatcher,但实际转发无法路由，本地windows起是可以转发的
2019-11-29 03:26:27.156 | [vert.x-eventloop-thread-3] | INFO  |
                o.a.s.foundation.common.utils.SPIServiceUtils |   0. com.huawei.ivcs.hdmc.ooc.oocsedge.dispatcher.ApiDispatcherForOthers.
2019-11-29 03:26:27.156 | [vert.x-eventloop-thread-3] | INFO  |
                o.a.s.foundation.common.utils.SPIServiceUtils |   1. com.huawei.ivcs.hdmc.ooc.oocsedge.dispatcher.ApiDispatcher.
2019-11-29 03:26:27.156 | [vert.x-eventloop-thread-3] | INFO  |
                o.a.s.foundation.common.utils.SPIServiceUtils |   2. com.huawei.ivcs.hdmc.ooc.oocsedge.dispatcher.LoginDispatcher.

public class ApiDispatcherForOthers extends BaseApiDispatcher {
    private static final String KEY_ENABLED = "servicecomb.http.dispatcher.edge.api.enabled";

    private static final String ROUTE_URI = "(/api/(user|oss)/oocs-iam/(auth|tenants)/(.*))";

o.a.s.common.rest.locator.OperationLocator | locate path failed, status:Not Found, http method:POST, pat
h:/api/user/oocs-iam/auth/v1/verify-code/, microserviceName:oocs-edge

**Comment by liubao68** [comment]
这个需要更多的信息确认问题，比如是否进入ApiDispatcherForOthers它的onRequest方法。

**Comment by lastshot-E** [comment]
已经修复，是两边配置不一致的问题，microservice.yaml里的CCE上没配，因为路由规则是直接配在dispatcher里的，microservice.yaml里的  http:
    dispatcher:实际是没有使用，而且我看到日志SPI加载到了dispatcher并且没有报错，就没注意，这个问题比较隐蔽，不会进入ApiDispatcher中的Onrequest，后续版本可否增加日志信息。

**Comment by tianxiaoliang** [comment]
@lastshot-E 是否愿意帮我们贡献这部分日志信息？
