### ISSUE TITLE
demo edge:edge service 的pom有些问题，导致build成功后无法运行

### ISSUE THREAD

**Issue by cindy-she** [apache/servicecomb-java-chassis#1420]
maven配置少了一个依赖项：
 <dependency>
      <groupId>org.apache.servicecomb</groupId>
      <artifactId>java-chassis-dependencies</artifactId>
      <type>pom</type>
      <scope>import</scope>
      <version>1.3.0</version>
     </dependency>
 maven配置少了个build配置：
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.1</version>
        <configuration>
          <compilerArgument>-parameters</compilerArgument>
          <encoding>UTF-8</encoding>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>2.10</version>
        <executions>
          <execution>
            <id>copy-dependencies</id>
            <phase>package</phase>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <configuration>
              <outputDirectory>target/lib</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>2.6</version>
        <configuration>
          <archive>
            <manifest>
              <addClasspath>true</addClasspath>
              <classpathPrefix>./lib/</classpathPrefix>
              <mainClass>${main.class}</mainClass>
              <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
              <addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
            </manifest>
            <manifestEntries>
              <Class-Path>.</Class-Path>
            </manifestEntries>
          </archive>
        </configuration>
      </plugin>
    </plugins>
  </build>

我加了这两个配置后eclipse构建成功后，并能成功启动服务。

**Comment by liubao68** [comment]
谢谢反馈。 DEMO目录下面的内容目前的主要用途是集成测试，不是用于打包部署的，保证
```
mvn clean install -Pit
```
能够运行即可。 

如果需要寻找下载可以执行的例子，可以参考 [servicecomb-samples](https://github.com/apache/servicecomb-samples/tree/master/porter_lightweight)

**Comment by liubao68** [comment]
Close old issue, please feel free to create new one if you meet the problem again.
