### ISSUE TITLE
servicecomb开发的微服务，升级时候，接口偶现断服

### ISSUE THREAD

**Issue by minshiwu** [apache/servicecomb-java-chassis#1421]
servicecomb consumer实现的WeightedResponseTimeRuleExt选择Server时候，没有判断server可用性和可达性。会导致升级时候，偶现接口断服。这一块sevicecomb设计时候，怎么考虑的。我看原生ribbon的WeightedResponseTimeRule有判断server可用和可达性的。这样保证每次选到的server是alive的。

**Comment by liubao68** [comment]
检查可用性和可达性需要去ping服务实例，不能够在每次调用的过程中去操作，不然就会影响性能。 这个过程servicecomb是在后台进行的。 如果请求某个实例的时候，刚好实例故障了， 并且后台还没有检测到实例故障，那么就可能请求故障实例导致错误。 这块可以通过必要的重试、隔离等机制进行补偿。 [参考案例](https://bbs.huaweicloud.com/blogs/107630)

**Comment by liubao68** [comment]
Close old issue, please feel free to create new one if you meet the problem again.
