### ISSUE TITLE
The special param types in Java-Chassis

### ISSUE THREAD

**Issue by yhs0092** [apache/servicecomb-java-chassis#1422]
When we defined a REST interface class, there are two kinds of params can be added into the method param list without changing the schema content, they are `javax.servlet.http.HttpServletRequest` and `org.apache.servicecomb.swagger.invocation.context.InvocationContext`.

----------------------------------------------------

The `javax.servlet.http.HttpServletRequest` seems like the common servlet request in a web container. But the underlying implementation may be different, which is determined by the transport way you services choose.
e.g., if your service is running on the [REST over Vertx](https://docs.servicecomb.io/java-chassis/zh_CN/transports/rest-over-vertx.html) transport mode, the vertx request data type is wrapped into `org.apache.servicecomb.foundation.vertx.http.VertxServerRequestToHttpServletRequest`. And you can treat this as a "mock" servlet request.
Therefore, not all the operation you can perform in a web container(like Tomcat) can be done to the `HttpServletRequest` in Java-Chassis. To avoid some confusing problem, it's suggested that you should only "read" data from the servlet request, and DO NOT write into it.
A common usage for `HttpServletRequest` param is like below, you can get all request headers from it:
```java
  @Path("/greetingRT")
  @POST
  public GreetingResponse greetingRT(Person person, HttpServletRequest request) {
    final Enumeration<String> headerNames = request.getHeaderNames();
    while (headerNames.hasMoreElements()) {
      LOGGER.info("header: " + request.getHeader(headerNames.nextElement()));
    }
    return new GreetingResponse();
  }
```

----------------------------------------------------

As for `org.apache.servicecomb.swagger.invocation.context.InvocationContext`, this is a data type defined originally in Java-Chassis. And it's also suggested that you only read from this param type in such situation. Some other key information can be got from it, like [InvocationContext](https://docs.servicecomb.io/java-chassis/zh_CN/general-development/context.html)

**Comment by liubao68** [comment]
这个问题对于早期的Spring MVC（老版本，基于Servlet，新的spring 5.0提供了WebClient支持异步）用户问的很多，ServiceComb本质是一个既可以运行于Servlet，也可以运行于非Servlet(vert.x TCP, vert.x HTTP1, vert.x HTTP2等）的RPC框架（支持REST风格和传统RPC编程风格）

**Comment by liubao68** [comment]
Close old issue, please feel free to create new one if you meet the problem again.
