### ISSUE TITLE
Java-chassis does not support @JsonView.

### ISSUE THREAD

**Issue by alec-z** [apache/servicecomb-java-chassis#1424]

**Comment by liubao68** [comment]
Java-Chassis supports some of Spring MVN annotations, but they are different. [This](https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/springmvc.html) guide and [this](https://bbs.huaweicloud.com/blogs/115961) article may help to understand it.

**Comment by liubao68** [comment]
Close old issue, please feel free to create new one if you meet the problem again.
