### ISSUE TITLE
以前ResultResponse<?>这样的返回类型，契约支持，新升级版本CSE 2.3.75.RC1后不支持了

### ISSUE THREAD

**Issue by 3254365436** [apache/servicecomb-java-chassis#1426]
契约的返回值 

```
   public ResultResponse<?> exportCloudSpaceBannerList(ExportRequest request) {
        return cloudSpaceBannerConfigService.exportCloudSpaceBannerList(request);
    }
```

以前 ```ResultResponse<?>``` 这样的返回类型，契约支持，新升级版本后不支持了
CSE 2.3.75.RC1
以前支持的版本是2.3.70，正常无问题。

请问如何解决？基于以前的版本开发如果不支持的话，如需修改，风险很大。谢谢

**Comment by liubao68** [comment]
根据设计，这种使用方式是不支持的，老版本应该也不支持。 因为 ```？``` 无法通过契约描述。 可以将 ```? ``` 修改为具体类型。 参考[泛型支持](https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/interface-constraints.html)

```
当用户使用隐式契约功能自动生成微服务契约时，需要在provider接口方法的返回消息中明确指定泛型类型，以保证 ServiceComb-Java-Chassis 生成的契约中包含足够的接口信息
```

**Comment by 3254365436** [comment]
> 根据设计，这种使用方式是不支持的，老版本应该也不支持。 因为 `？` 无法通过契约描述。 可以将 `? ` 修改为具体类型。 参考[泛型支持](https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/interface-constraints.html)
> 
> ```
> 当用户使用隐式契约功能自动生成微服务契约时，需要在provider接口方法的返回消息中明确指定泛型类型，以保证 ServiceComb-Java-Chassis 生成的契约中包含足够的接口信息
> ```

我们用了很久老版本了，一直是支持的呀。可以私下联系我，谢谢：huyanqiang3@huawei.com

**Comment by liubao68** [comment]
Close old issue, please feel free to create new one if you meet the problem again.
