### ISSUE TITLE
servicecomb的consumer是否支持按需缓存依赖服务的schema，而不是全量缓存

### ISSUE THREAD

**Issue by minshiwu** [apache/servicecomb-java-chassis#1428]
在开发中发现，consumer调用cse://microserviceName/business-url时候，会尝试从sc加载依赖服务的Schema信息到自己的缓存。跟踪源码发现会全量加载依赖服务所有schema信息，代码如下ConsumerSchemaFactory.java 中：
```java
    for (String schemaId : microservice.getSchemas()) {
      ConsumerSchemaContext context = new ConsumerSchemaContext();
      context.setMicroserviceMeta(microserviceMeta);
      context.setMicroservice(microservice);
      context.setSchemaId(schemaId);
      context.setProviderClass(null);
      getOrCreateSchema(context);
    }
```
由于在getOrCreateSchema中会通过反射创建schema的request，response等java对象。导致在cpu等外部资源低的机器上运行，耗时很慢。在我们一个k8s node里面。缓存所有依赖服务的schema这个过程耗时了25s。

考虑如下一种典型场景：我只需要调用依赖服务(包含100+接口)的一个接口，但是在实际第一次调用时候，确需要将对端100+接口的shema全部拉取下来进行反射后缓存。这样是否合理？ 我的想法是，我只需要缓存包含我需要调用的business-url的schema，其他schema我没有使用到，不用缓存。

**Comment by liubao68** [comment]
这个确实是一个优化点。 目前的建议是可以实现一个BootEventListener, 在启动的时候，预加载一下契约，避免第一次访问缓慢。 2.0.0目前会做契约管理优化， 我将这个issue标记为improvement。

**Comment by liubao68** [comment]
2.0.0版本不再进行swagger编译，可以尝试一下。有问题可以新建issue反馈，本问题关闭。
