### ISSUE TITLE
升级版本之后，所使用得netty版本还是4.1.36.Final，该版本存在CVE漏洞

### ISSUE THREAD

**Issue by liuyifeng1992** [apache/servicecomb-java-chassis#1429]
我手动把netty版本指定为符合规定的4.1.43.Final，netty-tcnative 版本指定为符合规定的2.0.26.Final，可以正常使用，请问我指定的版本对于cse这个版本来说，可以用吗？
这两个版本指定为上述版本之后，日志会定时报错如下
2019-12-02 14:55:29[ERROR][REQ-][registry-vert.x-worker-thread-1][ServiceRegistryClientImpl.java-699]-watcher handle microservice 325e22e6e7f7580f94f09e89055c4469781729dc response failed, 
但是似乎不影响使用

**Comment by liubao68** [comment]
we fixed it in this [PR](https://github.com/apache/servicecomb-java-chassis/pull/1394) in 2.0.0 release.

**Comment by tianxiaoliang** [comment]
安全漏洞建议及时修复到1.x版本

**Comment by jeho0815** [comment]
netty已经升级到了4.1.43了，你自己排查下吧依赖树

**Comment by liuyifeng1992** [comment]
经过检查，应该确实已经升级至4.1.43了，但是这个报错能帮忙看下嘛？
[ServiceRegistryClientImpl.java-699]-watcher handle microservice 325e22e6e7f7580f94f09e89055c4469781729dc response failed,

我看源码，不清楚它这个watch的什么response，虽然这个报错目前我看不影响功能，但是每30秒就打印一次日志

**Comment by liubao68** [comment]
这个错误是watch变更失败，具体代码：
```
            try {
              response = JsonUtils.readValue(bodyBuffer.getBytes(),
                  MicroserviceInstanceChangedEvent.class);
            } catch (Exception e) {
              LOGGER.error("watcher handle microservice {} response failed, {}",
                  selfMicroserviceId,
                  bodyBuffer.toString());
              return;
            }
```
看日志是会打印响应内容的，也可以调试看下e是什么。是否有影响需要结合你的环境看下，是否依赖于watch功能， ServcieCenter使用pull模式也是可以保持实例一致的，没有watch不会影响功能，但可能影响到实例变更检查的时效性 。

**Comment by liuyifeng1992** [comment]
> 这个错误是watch变更失败，具体代码：
> 
> ```
>             try {
>               response = JsonUtils.readValue(bodyBuffer.getBytes(),
>                   MicroserviceInstanceChangedEvent.class);
>             } catch (Exception e) {
>               LOGGER.error("watcher handle microservice {} response failed, {}",
>                   selfMicroserviceId,
>                   bodyBuffer.toString());
>               return;
>             }
> ```
> 
> 看日志是会打印响应内容的，也可以调试看下e是什么。是否有影响需要结合你的环境看下，是否依赖于watch功能， ServcieCenter使用pull模式也是可以保持实例一致的，没有watch不会影响功能，但可能影响到实例变更检查的时效性 。

debug调试后，bodyBuffer的内容如下
UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 0, cap: 0)
然后异常e的堆栈如下
com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (byte[])""; line: 1, column: 0]

**Comment by liubao68** [comment]
This error seems wobsocket do not handle PONG message properly. I add this as a ***bug*** for this.

**Comment by liubao68** [comment]
updrading netty in 1.3.0 is tracked in [ISSUE](https://issues.apache.org/jira/browse/SCB-1592)
PONG message handling si tracked in [ISSUE](https://issues.apache.org/jira/browse/SCB-1638)
