### ISSUE TITLE
微服务之间调用的时候，提示Probably invoke a service before it is registered, or no instance found for it

### ISSUE THREAD

**Issue by pengyaobin** [apache/servicecomb-java-chassis#1431]
两个微服务的之间接口调用，在服务中心已经查看两个微服务都已注册，并且测试契约也没有问题

**Comment by yhs0092** [comment]
Probably invoke a service before it is registered, or no instance found for it
打印这行日志的直接原因是consumer端无法加载provider端的信息，可能的问题场景比较多：
- provider端服务注册失败
- sc上注册的provider服务实例数为零
- provider的契约有问题，导致consumer加载provider契约失败
……

通常需要结合实际运行情况以及上下文日志来判断

**Comment by jeho0815** [comment]
调用是在注册之前？

**Comment by pengyaobin** [comment]
> 调用是在注册之前？

是已经注册之后才调用的，在服务中心的页面上可以看到注册状态是up状态

**Comment by pengyaobin** [comment]
> Probably invoke a service before it is registered, or no instance found for it
> 打印这行日志的直接原因是consumer端无法加载provider端的信息，可能的问题场景比较多：
> 
> * provider端服务注册失败
> * sc上注册的provider服务实例数为零
> * provider的契约有问题，导致consumer加载provider契约失败
>   ……
> 
> 通常需要结合实际运行情况以及上下文日志来判断

**Comment by yhs0092** [comment]
在打印`Probably invoke a service before it is registered, or no instance found for it`日志之前，有没有什么error或者warning日志呢？
举个例子，如果consumer无法从sc查到provider的服务，会打印这样的日志
```
[2019-12-03 15:06:05,705/CST][registry-vert.x-eventloop-thread-0][WARN]failed to findInstances: {"errorCode":"400012","errorMessage":"Micro-service does not exist","detail":"Consumer[0a575d066669cf0ed8117101d47921e240c8564c][/Weak-Contract-Type-Exam/consumer/0.0.1] find provider[/Weak-Contract-Type-Exam/provider/0.0.0+] failed, provider does not exist."}
 org.apache.servicecomb.serviceregistry.client.http.ServiceRegistryClientImpl.lambda$null$7(ServiceRegistryClientImpl.java:242)
```

建议去检查一下日志上下文，看看有没有相关的error或者warn信息

**Comment by pengyaobin** [comment]
> 在打印`Probably invoke a service before it is registered, or no instance found for it`日志之前，有没有什么error或者warning日志呢？
> 举个例子，如果consumer无法从sc查到provider的服务，会打印这样的日志
> 
> ```
> [2019-12-03 15:06:05,705/CST][registry-vert.x-eventloop-thread-0][WARN]failed to findInstances: {"errorCode":"400012","errorMessage":"Micro-service does not exist","detail":"Consumer[0a575d066669cf0ed8117101d47921e240c8564c][/Weak-Contract-Type-Exam/consumer/0.0.1] find provider[/Weak-Contract-Type-Exam/provider/0.0.0+] failed, provider does not exist."}
>  org.apache.servicecomb.serviceregistry.client.http.ServiceRegistryClientImpl.lambda$null$7(ServiceRegistryClientImpl.java:242)
> ```
> 
> 建议去检查一下日志上下文，看看有没有相关的error或者warn信息

2019-12-03 15:28:48,120 [http-nio-12581-exec-2] ERROR o.a.s.s.consumer.MicroserviceVersions:166 - Failed to setInstances, appId=CloudTest, microserviceName=userAuth.
报了这个异常

**Comment by yhs0092** [comment]
`Failed to setInstances` consumer端能打印这一行日志的话，那么它至少已经从服务中心查询到provider服务的信息了。
也许是契约加载碰到问题了，如果是那样的话可以从日志里面推测出来是加载到哪个契约时报错的。你可以去服务中心的服务契约详情页面把yaml格式的契约内容复制出来，粘贴到[Swagger Editor](https://editor.swagger.io/) 里面，让 Swagger Editor 来帮你判断一下是否契约内容有问题。

或者你贴出来的那行日志的前后应该有打印异常信息吧？也可以把完整的错误日志，包含异常堆栈信息都贴出来，我们一起看一下

**Comment by pengyaobin** [comment]
> `Failed to setInstances` consumer端能打印这一行日志的话，那么它至少已经从服务中心查询到provider服务的信息了。
> 也许是契约加载碰到问题了，如果是那样的话可以从日志里面推测出来是加载到哪个契约时报错的。你可以去服务中心的服务契约详情页面把yaml格式的契约内容复制出来，粘贴到[Swagger Editor](https://editor.swagger.io/) 里面，让 Swagger Editor 来帮你判断一下是否契约内容有问题。
> 
> 或者你贴出来的那行日志的前后应该有打印异常信息吧？也可以把完整的错误日志，包含异常堆栈信息都贴出来，我们一起看一下

谢谢解答，我的问题和https://github.com/apache/servicecomb-java-chassis/issues/1436一样，已经解决了
