### ISSUE TITLE
springboot2改造cse项目，application.properties文件和microservice.yaml文件配置

### ISSUE THREAD

**Issue by 296230551** [apache/servicecomb-java-chassis#1432]
springboot2改造cse项目，application.properties文件和microservice.yaml文件配置问题：
1、是否可以将microservice.yaml相关的注册中心、配置中心、ak/sk等信息配置到application.properties文件中，整合为一个配置文件？
2、这两个配置文件中的哪个端口配置是有效的？
3、在@SpringBootApplication注解加上(exclude = DispatcherServletAutoConfiguration.class)，配置文件同步加入spring.main.web-application-type=none之后发现spring支持的过滤器均会失效，不加则可以使用。还有ssl证书相关配置也会失效。加与不加对服务注册，服务之间的调用会有影响吗？

**Comment by liubao68** [comment]
1. 可以按照spring boot的使用习惯都配置到application.yml中。 参考[示例](https://github.com/apache/servicecomb-samples/tree/master/dependency_management)
2. 参考问题1的处理。
3. 可以参考[原理](https://bbs.huaweicloud.com/blogs/115961)和[差异](https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/springmvc.html)了解下差异.
