### ISSUE TITLE
在arm64上执行集成测试出错 -Dservicecomb.rest.address=0.0.0.0:0?sslEnabled=true&protocol=http2

### ISSUE THREAD

**Issue by surechen** [apache/servicecomb-java-chassis#1437]
在integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/deploy.java文件中
有设置服务的访问地址-Dservicecomb.rest.address=0.0.0.0:0?sslEnabled=true&protocol=http2
执行集成测试时报错--找不到服务，这个带参数的地址没有成功注册到服务中心，让客户端可以获取到，去掉参数部分‘?sslEnabled=true&protocol=http2’后再执行测试用例可以通过。
1、请问这个问题跟服务中心的docker镜像有关系吗？是否服务中心需要什么特殊配置？
2、是否这里对ssl支持有问题？
3、这里删除url地址中的参数规避问题会有什么影响吗？

**Comment by liubao68** [comment]
这个参数指定的是本微服务监听的地址信息，和服务发现没关系。 即监听随机端口，协议是HTTP2， 并启用了TLS（即H2）.
