### ISSUE TITLE
在arm64上执行multiple-client 单元测试时服务挂起，一直等待，却没有任何处理？

### ISSUE THREAD

**Issue by surechen** [apache/servicecomb-java-chassis#1438]
这里我在arm64环境中升级了docker-maven-plugin插件版本到0.28.0，之后执行中发现一个非必现问题：执行multiple-client的UT测试时服务挂起，构建流程一直挂起，cpu占用下降，在demo/demo-multiple/multiple-client/src/添加了测试用例后执行通过，我想这里可能跟插件版本相关，
请问这里添加测试用例应该不会给服务造成什么影响吧？
请问是否有计划升级下比较陈旧的插件和库以支持较新的系统和处理器？

**Comment by liubao68** [comment]
按照你的描述“添加测试用例”不应该规避前面的构建挂起问题， 看不出具体问题所在。
