### ISSUE TITLE
cse中如何获取request、response

### ISSUE THREAD

**Issue by DannyKiler** [apache/servicecomb-java-chassis#1440]
cse应该是有线程隔离，请问怎样获取request、response对象，
试了下  
@Autowired
private HttpServletRequest request;

HttpServletRequest request = ((ServletRequestAttributes)RequestContextHolder.getRequestAttributes()).getRequest();

两种方式均拿不到，而作为参数在控制层传入发现拿不到请求头信息，并cse不支持response作为参数传入

**Comment by liubao68** [comment]
你可以看看[原理](https://bbs.huaweicloud.com/forum/thread-27592-1-1.html)了解下与Spring MVC（基于servlet）的差异。 servicecomb本质上是一个RPC框架，可以基于servlet，也可以基于非servlet，是不可以注入HttpServletRequest 和 HttpServletResponse的。 另外， ServiceComb整体运行流程是异步的，也不能像spring mvc那样通过ThreadLocal做一些变量保存，做一些特殊的基于ThreadLoacle的拦截和注入。

**Comment by afan321** [comment]
那有一些变量保存可以用什么去做呢?

**Comment by yhs0092** [comment]
> 那有一些变量保存可以用什么去做呢?

需要跨实例调用里传输可以使用 local context `org.apache.servicecomb.swagger.invocation.context.InvocationContext#context`，只在本实例内使用的话可以考虑 InvocationContext `org.apache.servicecomb.swagger.invocation.context.InvocationContext#localContext`

-> [关于InvocationContext的参考资料](https://docs.servicecomb.io/java-chassis/zh_CN/general-development/context.html)

**Comment by yhs0092** [comment]
@DannyKiler  在Java-Chassis内部我们更推荐使用InvocationContext来传输额外的信息，而非HTTP header。如果有些场景一定要拿到请求header的话，可以看看这篇 [The special param types in Java-Chassis](https://github.com/apache/servicecomb-java-chassis/issues/1422)
