### ISSUE TITLE
cse如何对response操作

### ISSUE THREAD

**Issue by DannyKiler** [apache/servicecomb-java-chassis#1441]
进行整改的时候发现原有的代码有对response的请求头，ContentType、CharacterEncoding、OutputStream等进行操作，由于cse拿不到response 请问该如何实现 

原有的接口返回值类型有的是void，只在失败的时候操作response,能否有不改变返回值类型即改造最小的代价的实现方案

**Comment by willard-kali** [comment]
参考https://docs.servicecomb.io/java-chassis/zh_CN/general-development/http-filter.html
通过HttpServerFilter中的beforeSendResponse应该可以实现。

**Comment by DannyKiler** [comment]
> 参考https://docs.servicecomb.io/java-chassis/zh_CN/general-development/http-filter.html
> 通过HttpServerFilter中的beforeSendResponse应该可以实现。

之前是按照业务逻辑的不同在请求头里面塞一些不同的东西，或者对流的不同操作，如果用过滤器的话那应该怎么实现

**Comment by DannyKiler** [comment]
比如说没有查到某数据，然后要给头里面填一个或者改一个东西，而过滤器不知道此处流程的结果，怎样去修改相应的头信息。
还有就是resp流的操作，这个操作本来是放在业务层的，现在怎么实现，
接口对resp的操作都是不同的，主要是针对流程的不同，所以我的的问题是如何根据不同接口、不同流程的处理结果来修改相应的resp

**Comment by willard-kali** [comment]
那你这个问题应该是业务接口定义了，和ServiceComb框架没关系吧。
用ResponseEntity应该可以解决吧。
参考：https://my.oschina.net/spinachgit/blog/1583068

**Comment by yhs0092** [comment]
根据你描述的，你的服务是以Servlet方式开发的吗？在Tomcat之类的web容器里部署，controller的方法定义的参数是 `HttpServletRequest` 和 `HttpServletResponse` ，HTTP请求的参数从 `HttpServletRequest` 里面取，HTTP响应往 `HttpServletResponse` 里面写？
然而ServiceComb-Java-Chassis 框架是一个REST的微服务框架，设计之初就与OpenAPI契约规范有原生支持，并不是让用户随意收发数据格式的。如果你使用的是 `HttpServletResponse` 来返回HTTP响应，那么框架是无法得知你的返回值的数据类型的，甚至很多这样Servlet方式开发的服务其实接口收发的数据结构也不一定是固定的，这样的接口没法用符合REST规范的契约描述。建议你看一下 [接口定义和数据类型](https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/interface-constraints.html) 这篇文档来了解一下Java-Chassis对于接口定义的约束。所以你看到的Java-Chassis的资料里推荐的接口定义方式都使用的是明确的参数和返回值类型，因为只有这样才能让框架生成明确的服务契约。

至于 ContentType、CharacterEncoding、OutputStream 这些东西，属于传输模块，如果按照Java-Chassis设想的开发方式，传输实现与业务接口定义应该是解耦合的，也不太建议你再手工修改返回值body的码流了，除非你对Java-Chassis、对底层的传输框架都很熟悉，否则太容易碰到问题，这样也很容易跟框架实现耦合起来，加重开发者的负担。

最后，如果你想接收HTTP请求的header，可以参考[这里](https://github.com/apache/servicecomb-java-chassis/issues/1422)，从`HttpServerFilter`里面取也行，而自定义不同状态码下的返回值类型的方法、设置特定的response header的方法可以参考Java-Chassis自带的demo，像 `org.apache.servicecomb.demo.jaxrs.server.multiErrorCode.MultiErrorCodeService#errorCodeWithHeader` 和 `org.apache.servicecomb.demo.springmvc.server.CodeFirstSpringmvc#responseEntity` 这样的方式都行。

**Comment by DannyKiler** [comment]
> 那你这个问题应该是业务接口定义了，和ServiceComb框架没关系吧。
> 用ResponseEntity应该可以解决吧。
> 参考：https://my.oschina.net/spinachgit/blog/1583068

老项目改造，设计之初没有想到这个问题。所以来问问有没有好的解决方案

**Comment by DannyKiler** [comment]
> 根据你描述的，你的服务是以Servlet方式开发的吗？在Tomcat之类的web容器里部署，controller的方法定义的参数是 `HttpServletRequest` 和 `HttpServletResponse` ，HTTP请求的参数从 `HttpServletRequest` 里面取，HTTP响应往 `HttpServletResponse` 里面写？
> 然而ServiceComb-Java-Chassis 框架是一个REST的微服务框架，设计之初就与OpenAPI契约规范有原生支持，并不是让用户随意收发数据格式的。如果你使用的是 `HttpServletResponse` 来返回HTTP响应，那么框架是无法得知你的返回值的数据类型的，甚至很多这样Servlet方式开发的服务其实接口收发的数据结构也不一定是固定的，这样的接口没法用符合REST规范的契约描述。建议你看一下 [接口定义和数据类型](https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/interface-constraints.html) 这篇文档来了解一下Java-Chassis对于接口定义的约束。所以你看到的Java-Chassis的资料里推荐的接口定义方式都使用的是明确的参数和返回值类型，因为只有这样才能让框架生成明确的服务契约。
> 
> 至于 ContentType、CharacterEncoding、OutputStream 这些东西，属于传输模块，如果按照Java-Chassis设想的开发方式，传输实现与业务接口定义应该是解耦合的，也不太建议你再手工修改返回值body的码流了，除非你对Java-Chassis、对底层的传输框架都很熟悉，否则太容易碰到问题，这样也很容易跟框架实现耦合起来，加重开发者的负担。
> 
> 最后，如果你想接收HTTP请求的header，可以参考[这里](https://github.com/apache/servicecomb-java-chassis/issues/1422)，从`HttpServerFilter`里面取也行，而自定义不同状态码下的返回值类型的方法、设置特定的response header的方法可以参考Java-Chassis自带的demo，像 `org.apache.servicecomb.demo.jaxrs.server.multiErrorCode.MultiErrorCodeService#errorCodeWithHeader` 和 `org.apache.servicecomb.demo.springmvc.server.CodeFirstSpringmvc#responseEntity` 这样的方式都行。

老项目改造，设计之初没有想到这个问题。所以来问问有没有好的解决方案
