### ISSUE TITLE
前台数据是一个非json的字符串，后台如何获取

### ISSUE THREAD

**Issue by pengyaobin** [apache/servicecomb-java-chassis#1442]
前台数据是一个非json的字符串，springBoot的controller层使用post接收，请问后台如何接收数据
我的后台是这样子写的：
@RequestBody String caseids
前台传的数据是这样的：
Request Payload:
cd0107d2-7b84-4519-8d56-3e25989408b8,902c4348-3afb-49bf-9202-c3fcda323c3e,01840783-ce20-48bb-9aea-1c5894d5f31b,d0fad9e2-ee06-44dc-ad0e-6a3d32ebfc2a,75f219c6-ca7f-40e2-8895-b5e8d725f6b9,5fd526d0-1195-46f4-b654-6641d187a18b,78340e37-c0bb-4341-854b-9ac8ba5639d0,b8161064-6d46-4ccb-b31b-ee00eb8b373b,7f497dd9-47dc-4128-8e72-e9f88198b8fd,8b59bab4-6710-4f2d-8f65-450b538da8d6,51f7c917-54a8-4304-825d-c552f652b068,c6cf11f5-01be-4ceb-bca2-7e7cde5b28b2,1602fa30-0acd-41b9-bf0b-24383c9a1097,27432206-002b-46dd-b7cb-7f1b309278f7,5d555655-6553-4876-acc1-4990934925fc,6cceae30-193e-4953-9aa0-1b30541eac29,10ad9447-efcb-4462-bdba-17137e8de4e9,3fe4d78b-4e09-4ea3-93d1-ad7ef94bbeef,8390ba6c-74c1-479b-b594-6c7dc37365fd,3d86d30d-50b2-49d6-bfd7-9de72f92a354,62dca3f7-6372-4b94-bc0f-3a43dd833ffa,4e595d2e-4a78-4984-9371-5184211e8f55,39cb2344-0874-4091-b459-5ef7df03c7e4,c144c1b2-56ba-4a26-9524-79a57c4661cc,9be397f5-ec13-4ffd-ac53-23367be714ed,101aa4a2-3512-4d65-b66b-9d529323e834,7892304e-9c01-4cbb-a994-1a0a43d6476d,0649178d-faf0-4cd4-b712-c248a19f2fcb,161ba47b-41f5-4f75-bf47-c40fcf5ac9ec,97492898-ea30-4ee0-9f5e-2471f34d0c5f,1d0272db-dfec-4a60-a825-22c2daefab9b,eefd625b-292c-46c1-b736-e2851f956bef,f16e4f94-40d3-4d0b-b9b5-68e8ba6d2ed3,267ead08-92e1-4306-9e93-bf16f2a1df8e,e23cac9f-8cec-44e3-a9d3-51a0aa253f9e,ab5db3df-e3a6-4af0-b30a-2093ca18e459,2a313465-1e5e-4191-b511-917034b50589,292a2582-f5cc-4fce-92f3-f02cbfd6d7f6,6d3059af-80da-446c-a5cf-21d2a93571ab,8e84a166-5172-4e84-b662-4ccb418e06c2,318a2f74-47bc-4489-9e9a-06b4bfef6ac4,1feeb1e8-28d5-437e-a25b-29bea29d4a8d,f47ef8c7-d410-4847-87ce-1c06bda2aac3,ac8fcef4-22de-4e3e-bfaf-142a4cdd80cd,7b4c81e8-4acb-49fd-862c-3598cc0aac53,91560429-ef63-40cf-a775-d4f86b1eee4f,39fd7b55-2542-4f24-b1e0-aaa8731c5173,13aed467-72ac-4c94-8ea0-58fc09ba9197,d4975fb2-b442-4d19-9d1e-d81a1481516e,081fe4ce-1a6d-41e2-a20f-f7b4687a4aa5,91b8f287-bdfc-443f-95f4-7c808618c7fc,4db1ec9c-8c71-4fb2-bd12-218485625296,3afbf69a-b500-4b47-904f-e561b9756f79,8c0dde0f-c2d5-4669-bc90-d500e25942f0,5fd34e39-122e-4a1d-a375-be0b93665ee8,eb94f3f2-6e64-4e7d-8427-c1fd9cc0c621,074d55c9-7f28-4335-9797-2a4be7aae0d5,be2c938f-3e05-4a57-87fb-5d21ceea1bfa,d53010b6-4477-4570-a350-a0eeaa82be6d,8179dd41-296a-426f-a678-ee548ebb5ccf,a6042074-5bbd-42c1-9637-a488d68c6e9c,b9b08ec1-9b60-45eb-8079-df13fcce7d22,36303d07-1890-48d0-8c05-782d9a789b9e,474567bb-7344-486e-b4ce-b1bce2996ac8,0cac8861-bcf1-44c0-be8e-d850f1c6dc3b,eb5defe7-29c3-4f8f-9843-5b6ca35ea0a2,89f56d9b-ab9d-41c5-bd1a-ea07dca5e27d,8abcd6b7-fcb4-4c41-a5f0-09c2e0211819,8c8f3c70-a2a3-447c-96d4-9945ca87ef9d,939977fd-d681-42a6-89db-5e8f8356bec8,ffa1732e-9ed5-48ec-8a5f-326d13f326bf,5d38c6f2-ae3a-41aa-9719-ae083b54b4b3,765f58d4-a3b8-478c-982c-87c4e5478800,aefa48ae-6f85-4aba-8c72-738942f7693d,9e681215-a445-413f-a5a6-6f2ff3a2870c,7fefaaab-e172-42d1-8cb1-b43489cd3ca6,a4f40f09-f7bf-45bf-852a-ec2726b0c631,181423fa-9ace-454e-9007-588c95f1007e,b365d9bf-8819-4bba-b0c4-988fd8e788ed,0499a6d3-7adc-4fe8-835c-a523df8acbce,56464ce8-ae7e-4ee9-b347-a175113f2299
报的异常:
org.apache.servicecomb.swagger.invocation.exception.InvocationException: InvocationException: code=400;msg=CommonExceptionData [message=Parameter is not valid for operation [commom.TraceTestCaseController.getTestEvnsAndAssociateEvnsByCaseIds]. Parameter is [caseids]. Processor is [body].]
	at org.apache.servicecomb.common.rest.codec.RestCodec.restToArgs(RestCodec.java:66)
	at org.apache.servicecomb.common.rest.filter.inner.ServerRestArgsFilter.afterReceiveRequest(ServerRestArgsFilter.java:61)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.prepareInvoke(AbstractRestInvocation.java:226)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.invoke(AbstractRestInvocation.java:206)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.runOnExecutor(AbstractRestInvocation.java:196)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.lambda$scheduleInvocation$0(AbstractRestInvocation.java:159)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
我知道这个是类型不对。目前发现必须是那种带key值能转成对象的才能接收，像这种没有key值的，如何接收呢

**Comment by yhs0092** [comment]
前台传的数据格式是不是不对啊？json的字符串要求用双引号包起来，比如你传`abc`，直接这么传是会报错的，得传`"abc"`才行。
建议拿 postman 或者 curl 试一下

**Comment by pengyaobin** [comment]
> 前台传的数据格式是不是不对啊？json的字符串要求用双引号包起来，比如你传`abc`，直接这么传是会报错的，得传`"abc"`才行。
> 建议拿 postman 或者 curl 试一下

谢谢，问题已经解决了，因为我们前台的请求头中设置的数据类型是json，前台将数据类型改为text/plain后就接收到了
