### ISSUE TITLE
ServiceCenter中微服务instance信息丢失

### ISSUE THREAD

**Issue by willard-kali** [apache/servicecomb-java-chassis#1443]
### 环境：
有1个Linux节点，部署了1个ServiceCenter，以及多个微服务（A、B）。
### 场景：
刚部署完成时，微服务功能都正常。
一段时间后，微服务B的instance信息突然就查不到了，但是进程一直在。
此时，微服务A还能通过cse://B/xxx的方式调用接口成功。
但是，微服务A重启过后，此调用方式调用失败，提示找不到B的instance地址。
看了ServiceCenter的log日志，没有发现有微服务的remove、add变更记录。
### 问题：
现在如何确认，微服务B的instance信息为什么会丢失？

**Comment by yhs0092** [comment]
sc里面没有服务B的实例信息，但是服务A的实例仍能调用B成功，应该是A缓存了B的实例列表在本地内存里。一旦A重启了，就得先去sc查询B的实例列表才能做调用。
建议去看看B的日志有没有什么报错呢？一般每个微服务实例都应该要定时向sc发送心跳以维持自己的实例记录在线，也许是有什么原因导致B心跳失败了。

**Comment by willard-kali** [comment]
B的微服务日志中，因为log4j滚动压缩，只找到2处如下的日志，但是不能确定该instanceId是否是当前微服务的。另外，servicecomb打印的日志，没有其他内容了。

> org.apache.servicecomb.loadbalance.ServiceCombLoadBalancerStats --> [LoadBalancerStatsTimer] stats of instance xd098423fxx911e9adxx04885ffa1a9x removed.

**Comment by yhs0092** [comment]
你贴出来的这行日志是 [ServiceCombLoadBalancerStats](https://github.com/apache/servicecomb-java-chassis/blob/master/handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/ServiceCombLoadBalancerStats.java) 去除实例状态统计信息的，跟B服务实例下线没有关系。
建议找个测试环境看看能否复现出来。需要关注一下整个流程中B服务的实例的日志，B的实例是在注册成功多久之后掉线的，jstack 看看B的进程里面有没有线程阻塞。
如果你能给出一个最小问题复现demo的话，也可以贴出来，大家一起看看 : )

**Comment by willard-kali** [comment]
> 你贴出来的这行日志是 [ServiceCombLoadBalancerStats](https://github.com/apache/servicecomb-java-chassis/blob/master/handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/ServiceCombLoadBalancerStats.java) 去除实例状态统计信息的，跟B服务实例下线没有关系。
> 建议找个测试环境看看能否复现出来。需要关注一下整个流程中B服务的实例的日志，B的实例是在注册成功多久之后掉线的，jstack 看看B的进程里面有没有线程阻塞。
> 如果你能给出一个最小问题复现demo的话，也可以贴出来，大家一起看看 : )
1. 这是真实环境出现的问题，概率极小，暂时无法复现。
2. 启动时间在10月份，最早的servicecenter日志只到11月底，从现有的servicecenter日志没有找到微服务B的CREATE或者DELETE记录（其他微服务的倒是有一些，应该是微服务重启造成的，DELETE和CREATE会成对出现）。
3. 无法确定B的实例是在注册多久后掉线的。

请问下按照servicecomb1.2.1版本的servicecenter逻辑，instance DELETE和CREATE一般会有哪些场景会出现？如：微服务重启。

附：搜到的servicecenter中的其他微服务日志类似如下：

> INFO    event/instance_event_handler.go:79      caught [DELETE] service[xxxx56b78c4fa5978ff4424d914183f3ecb00xxx][/appid/servicename/version] instance[xxxx6feaf66911e9ad6604885ffa1a9b] event, endpoints []
INFO    event/instance_event_handler.go:79      caught [CREATE] service[xxxx56b78c4fa5978ff4424d914183f3ecb00xxx][/appid/servicename/version] instance[yyyy697915b211eaad6604885ffa1a9b] event, endpoints []

**Comment by yhs0092** [comment]
CREATE 事件一般是有微服务实例注册上线。
DELETE 是微服务实例下线，一般有两种情况，一种是微服务实例主动调sc接口注销自己；另一种是微服务实例连续心跳失败达到阈值，被sc自动注销下线。可以看看 [这里](https://docs.servicecomb.io/java-chassis/zh_CN/general-development/visit-sc.html) 关于`servicecomb.service.registry.instance.healthCheck.times`配置项的描述

**Comment by liubao68** [comment]
根据问题描述， 看起来是B实例已经在服务中心下线，但是A缓存里面还有B信息。 这里有个疑问, 
```
一段时间后，微服务B的instance信息突然就查不到了，但是进程一直在。
此时，微服务A还能通过cse://B/xxx的方式调用接口成功。
但是，微服务A重启过后，此调用方式调用失败，提示找不到B的instance地址。
```
这里说的A能够调用成功大概持续了多久？如果超过上一条回复的心跳时间（一般是2分多钟）， 问题有可能是A服务本身无法连接服务中心发现相关服务实例了（如果发现，A会移除缓存，错误应该是没有实例可用）。 

看起来总体上各个现象有矛盾的地方。有可能某些地方有错漏。

**Comment by willard-kali** [comment]
> 根据问题描述， 看起来是B实例已经在服务中心下线，但是A缓存里面还有B信息。 这里有个疑问,
> 
> ```
> 一段时间后，微服务B的instance信息突然就查不到了，但是进程一直在。
> 此时，微服务A还能通过cse://B/xxx的方式调用接口成功。
> 但是，微服务A重启过后，此调用方式调用失败，提示找不到B的instance地址。
> ```
> 
> 这里说的A能够调用成功大概持续了多久？如果超过上一条回复的心跳时间（一般是2分多钟）， 问题有可能是A服务本身无法连接服务中心发现相关服务实例了（如果发现，A会移除缓存，错误应该是没有实例可用）。
> 
> 看起来总体上各个现象有矛盾的地方。有可能某些地方有错漏。

现象确实非常奇怪，我们使用了很久ServiceComb也是第一次出现该情况。
1. A能够调用成功B，持续时间大于N天（N应该大于1周），具体时间因无法看到更早日志无法确定。
2. A应该是能连到SC的，SC中执行命令查询，其他微服务的实例是存在的，并且其他大部分功能都正常（有很多功能都是微服务间互相调用的）。

因无更多日志可以分析，所以已经恢复了环境，计划再观察1周，如无更新关闭该issue。
