### ISSUE TITLE
在src/main/resources 路径下的配置文件在CSE配置文件中的路径配置问题

### ISSUE THREAD

**Issue by afan321** [apache/servicecomb-java-chassis#1444]
CSE的配置文件和证书都放在  src/main/resources  路径下   在springboot 的配置文件 我会这样写 keyStore: classpath:key.keystore  但对于CSE 配置 写成keyStore: classpath:key.keystore  或 keyStore: key.keystore 都会报文件找不到.   对于这种配置我应该怎么去写

**Comment by liubao68** [comment]
没使用过你说的场景，不知道你是具体使用哪个组件碰到的问题？可能需要调试下具体模块的代码，看看它是如何读取和使用配置项的。

**Comment by liubao68** [comment]
BTW: 如果采用spring boot方式集成java-chassis，最佳的实践是使用application.yml替换microservice.yaml，这样开发体验会更加spring boot的开发体验。
