### ISSUE TITLE
springboot切cse中不替换DispatcherServlet的影响

### ISSUE THREAD

**Issue by DannyKiler** [apache/servicecomb-java-chassis#1448]
如题，不替换DispatcherServlet对于项目改造切GDE会有什么影响吗，发现替换之后文件的上传下载功能改动较大。
https://docs.servicecomb.io/java-chassis/zh_CN/general-development/file-upload.html此处的基于SpringMvc上传操作是否对DispatcherServlet进行了替换

**Comment by liubao68** [comment]
开发指南的说明部分都是java-chassis提供的功能，不是Spring MVC DispatcherServlet提供的功能。 如果不涉及“网关”、“服务发现”等场景，可以考虑[两个Servlet并存](https://docs.servicecomb.io/java-chassis/zh_CN/using-java-chassis-in-spring-boot/web-application.html)以保持历史代码功能的兼容
