### ISSUE TITLE
EdgeService熔断配置不生效

### ISSUE THREAD

**Issue by willard-kali** [apache/servicecomb-java-chassis#1451]
EdgeService，
pom引用了bizkeeper：

> \<dependency>
            \<groupId>org.apache.servicecomb\</groupId>
            \<artifactId>handler-bizkeeper\</artifactId>
            \<version>1.2.1\</version>
        \</dependency>

微服务yaml配置如下：
> servicecomb:
  handler:
    chain:
      Consumer:
        default: bizkeeper-consumer
      Provider:
        default: bizkeeper-provider
  isolation:
    Consumer:
      timeout:
        enabled: true
      timeoutInMilliseconds: 10
    Provider:
      timeout:
        enabled: true
      timeoutInMilliseconds: 10
  circuitBreaker:
    Consumer:
      enabled: true
      **forceOpen: true**
      sleepWindowInMilliseconds: 15000
      requestVolumeThreshold: 1
    Provider:
      enabled: true
      **forceOpen: true**
      sleepWindowInMilliseconds: 15000
      requestVolumeThreshold: 1
  fallback:
    Consumer:
      enabled: true
    Provider:
      enabled: true
  fallbackpolicy:
    Consumer:
      policy: throwexception
    Provider:
      policy: throwexception

上述配置，consumer和provider分开配置进行测试。
运行后，EdgeService调用微服务的接口逻辑，直接就报490，表示bizkeeper-consumer生效了，符合预期。
但是浏览器直接访问EdgeService时，bizkeeper-provider未生效，没有报490。
**请问在EdgeService这种网关服务上，bizkeeper-provider的熔断策略是否不会生效？**

看了下org.apache.servicecomb.bizkeeper.ProviderBizkeeperHanlder的源码，没看懂它的处理逻辑是什么样子的。

**Comment by liubao68** [comment]
edge service不会走provider处理链，只有consumer处理链,  [参考](https://docs.servicecomb.io/java-chassis/zh_CN/edge/by-servicecomb-sdk.html)
