### ISSUE TITLE
consulting about the cse context injection

### ISSUE THREAD

**Issue by leland17** [apache/servicecomb-java-chassis#1456]
I want to know how could I set context elements by tools such as postman?  When I work with alpha tests that is important, because many context is set after the edge authentication, and after the request invocation, other microservice could get the context. 

but in the alpha tests, context is empty, so could any method to achieve this.

**Comment by yhs0092** [comment]
If you mean the [InvocationContext](https://docs.servicecomb.io/java-chassis/zh_CN/general-development/context.html), actually Java-Chassis keep the InvocationContext in a map. And on the REST transport mode, it's serialized as json and passed in HTTP header, the header name is `x-cse-context`.

**Comment by leland17** [comment]
@yhs0092 thanks a lot

**Comment by yhs0092** [comment]
My pleasure : )
