### ISSUE TITLE
建议提供更灵活的线程池扩展

### ISSUE THREAD

**Issue by johnyannj** [apache/servicecomb-java-chassis#1459]
servicecomb支持为每个接口提供执行线程池，前提是需要在spring里定义对应的线程池bean，同时在microservice.yaml里进行对应的配置。

一些业务场景，需要临时动态的调整线程池的安排，通过spring+microservice.yaml的调整加重启的方式显得笨拙了一些。

期待提供一种更灵活的线程池扩展形式，
1、可以仅通过修改配置文件就可以定义出一个线程池
2、可以在代码级别扩展线程池自定义线程池选择策略
3、支持在请求处理前一刻选择线程池。

**Comment by liubao68** [comment]
Thread pools [reference ](https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/thread-pool.html), 

It seems like you want to support creating THREAD POOLS according to the configuration. This is not a good idea and seams too complicated.

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
