### ISSUE TITLE
org.apache.servicecomb.swagger.invocation.converter.ConverterMgr#findConverter时能否通过注解表明当前类和目标类结构相似无需转换

### ISSUE THREAD

**Issue by Nick-The-Uncharted** [apache/servicecomb-java-chassis#1460]
比如微服务A 有`PersonA{name, age}` 微服务B有`PersonB{name, age, gender}`，微服务A调用微服务B时完全可以使用PeronA实例作为参数编码然后微服务B使用PersonB为参数解码。目前的Json和protobuf编码方式都不会将类名编码，所以应该完全没问题。 

注解类似于 `@SameStructureWith({"packgeB.personB", "packageC.personC"})`

**Comment by yhs0092** [comment]
Java-Chassis 1.x 版本由于强类型内核机制的限定，要求框架内传递的参数类型和契约里面声明的参数类型一致（可以调试看看`org.apache.servicecomb.swagger.invocation.SwaggerInvocation#swaggerArguments`数组里面的东西），甚至在classpath里面找不着契约中声明的类型时，还会根据契约内容动态生成对应的Java参数类型。
Java-Chassis 2.0 版本将这一“强类型内核”机制改为了“弱类型内核”。如果classpath里面没有契约中`x-java-class`属性声明的参数类型时，在REST传输方式下，框架会依赖Jackson的能力对参数做反序列化，`Invocation#swaggerArguments`里面传输的不一定是对应的Java参数类型了，也有可能是`LinkedHashMap`、`String`之类的数据类型，这取决于你传递的数据码流以及Jackson的处理行为。
如果你对这多的一次参数类型转换比较介意的话，建议关注一下Java-Chassis 2.0版本（当前在master分支上开发中），也许它能满足你的预期  : )

**Comment by Nick-The-Uncharted** [comment]
期待2.0版本~

**Comment by yhs0092** [comment]
可以把代码clone到本地`mvn clean install` 一下看看，REST传输方式已经能跑了 ^_^
