### ISSUE TITLE
how to generate a pic verify code for the web portal ?

### ISSUE THREAD

**Issue by leland17** [apache/servicecomb-java-chassis#1462]
I want to know how servicecomb support to produce a picture of verify code, and how to set its response in this case. In my controller, how do i write image bytes to the response?

**Comment by yhs0092** [comment]
If you can get the picture file somehow, maybe you can send the file by the [file-downloading function](https://docs.servicecomb.io/java-chassis/zh_CN/general-development/file-download.html).
Anyway, as far as I know, Java-Chassis does not provide the end-to-end verify code picture function. So you need to consider how to get the verify pictures : )

**Comment by liubao68** [comment]
Maybe you can use following:
1. byte[] as the return value;
2. File or Inputstream, this API is something like file downloading.

see [download](https://docs.servicecomb.io/java-chassis/zh_CN/general-development/file-download.html) and [examples](https://github.com/apache/servicecomb-java-chassis/blob/master/integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/DownloadSchema.java)

**Comment by leland17** [comment]
thanks. solutions as below，

public ResponseEntity<InputStream> getVerifyCodePic() {
        SpecCaptcha specCaptcha = VerifyCodeUtil.getSpecCaptcha();
        if (!authFreeService.setPicVerifyCode(specCaptcha.text())) {
            ExceptionUtil.newInvocationException(ExceptionEnum.SYS_RUNTIME_EXCEPTION);
        }
        CodexUtil.infoLogWithArguments(log, "current pic verify code is:{}", specCaptcha.text());
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        specCaptcha.out(outputStream);
        return ResponseEntity.ok()
            .header(HttpHeaders.CONTENT_TYPE, "image/png")
            .header("Cache-Control", "no-cache, no-store, must-revalidate")
            .header("Pragma", "no-cache")
            .header("X-Download-Options", "noopen")
            .header("X-Content-Type-Options", "nosniff")
            .body(new ByteArrayInputStream(outputStream.toByteArray()));
    }

**Comment by liubao68** [comment]
Thanks for sharing. It's better to specify the template type when using ResponseEntity , e.g. 
```
public ResponseEntity<InputStream> getVerifyCodePic()
```
