### ISSUE TITLE
cse启动过程中报端口冲突

### ISSUE THREAD

**Issue by tianyaohua-hw** [apache/servicecomb-java-chassis#1463]
报错日志：
2019-12-17 01:08:32,126  WARN [main] o.a.s.t.r.v.VertxRestTransport | Can not start VertxRestTransport, the port:28080 may have been occupied. You can ignore this message if you are using a web container like tomcat. | org.apache.servicecomb.transport.rest.vertx.VertxRestTransport.canInit(VertxRestTransport.java:62)

但是，在业务启动脚本中，启动之前会检查端口是否被监听，启动检查时端口未被占用

**Comment by liubao68** [comment]
This is a warning message and tells you about the reason. And I can not get what's your problem.

**Comment by yhs0092** [comment]
Java-Chassis 支持的默认的REST传输方式有两种，[Rest over Vertx](https://docs.servicecomb.io/java-chassis/zh_CN/transports/rest-over-vertx.html) 和 [Rest over Servlet](https://docs.servicecomb.io/java-chassis/zh_CN/transports/rest-over-servlet.html)。前者是由一个WEB容器（如Tomcat）监听端口，Java-Chassis通过这个WEB容器接收请求；后者是Java-Chassis使用自带的Vert.x监听端口接收请求。
如果你配置了REST传输方式所要监听的IP端口，在启动流程中Java-Chassis会去选择一种传输方式作为实际工作的REST传输方式。实际运行时先由REST over Vertx模块（也就是你贴出来的日志中的`VertxRestTransport`）检查能否工作，如果端口被占用了，Java-Chassis就认为你的服务运行在一个WEB容器里，`VertxRestTransport`会被跳过去，由 Rest over Servlet 模块处理请求。
所以你打的这行日志不一定是真实的错误，也有可能你的服务确实运行在一个WEB容器中，启动流程里Java-Chassis打了这行告警，但是依然能正常工作。

**Comment by tianyaohua-hw** [comment]
我们是使用nuwa作为容器，启动前已经检查过28080端口没有被监听。启动过程中，会检查28080端口是否正常监听，如果监听了，会调用health接口检查业务是否启动正常。从启动日志看，启动报错是端口被占用，但启动前的确检查了端口未被占用。
还有什么可能的原因会占到这个报错吗？

**Comment by liubao68** [comment]
> 我们是使用nuwa作为容器，启动前已经检查过28080端口没有被监听。启动过程中，会检查28080端口是否正常监听，如果监听了，会调用health接口检查业务是否启动正常。从启动日志看，启动报错是端口被占用，但启动前的确检查了端口未被占用。
> 还有什么可能的原因会占到这个报错吗？

I think the previous replies have answered your question, and you can ignore this warning.
