### ISSUE TITLE
cse熔断判断590问题

### ISSUE THREAD

**Issue by hongfeihuangseu** [apache/servicecomb-java-chassis#1465]
业务直接抛出错误码400，没有去捕获这个异常，然后被CSE认为是590，然后就开始熔断计数了，但是400在业务逻辑被认为是不需要熔断的，请问如何规避这个问题呢

**Comment by liubao68** [comment]
查看[这里](https://bbs.huaweicloud.com/forum/thread-12790-1-1.html)的说明

**Comment by yhs0092** [comment]
> 业务直接抛出错误码400，没有去捕获这个异常，然后被CSE认为是590，然后就开始熔断计数了，但是400在业务逻辑被认为是不需要熔断的，请问如何规避这个问题呢

业务抛出400，具体是怎么抛的呢？如果是 throw new InvocationException，那么Java-Chassis能认出来这是一个400返回。但如果你们抛400是把响应包装在一个自定义的异常类型里面抛出来的，Java-Chassis默认是不认识的，此时Java-Chassis会把你们从业务代码抛出的异常包装成InvocationException返回，状态码是590。所以很有可能从Java-Chassis的熔断模块看来，是碰到590状态码触发熔断了。
关于返回错误状态码，可以看看[这里](https://docs.servicecomb.io/java-chassis/zh_CN/general-development/error-handling.html)，如果你要沿用自己业务定义的异常类型的话，就需要扩展`ExceptionToProducerResponseConverter`来自定义捕获你们的业务异常类型，将它转换成Java-Chassis能识别的400错误返回形式，[资料](https://docs.servicecomb.io/java-chassis/zh_CN/general-development/error-handling.html)里面都有说明。
