### ISSUE TITLE
【Feature Request】支持入参为MultiValueMap，从而与spring保持一致

### ISSUE THREAD

**Issue by Nick-The-Uncharted** [apache/servicecomb-java-chassis#1466]
Spring相关代码见 org.springframework.web.method.annotation.RequestParamMapMethodArgumentResolver#resolveArgument

**Comment by liubao68** [comment]
This is equals to ```Map<K, List<V>>```, you can use this directly. 

java-chassis implements Open API specification, do not bind to spring datatypes. [see](https://swagger.io/docs/specification/data-models/dictionaries/)

**Comment by Nick-The-Uncharted** [comment]
@liubao68 Thank you and I just find out that LinkedMultiValueMap worked as well.
