### ISSUE TITLE
RuleExt （RandomRuleExt、WeightedResponseTimeRuleExt）中应该使用ThreadLocalRandom代替Random

### ISSUE THREAD

**Issue by johnyannj** [apache/servicecomb-java-chassis#1467]
Random虽然是线程安全的，但是在多线程情况下会因为竞争导致性能下降。

javadoc：

Instances of java.util.Random are threadsafe. However, the concurrent use of the same java.util.Random instance across threads may encounter contention and consequent poor performance. Consider instead using java.util.concurrent.ThreadLocalRandom in multithreaded designs

**Comment by liubao68** [comment]
Thanks for your suggestion. Can you help to submit a PR for this?

**Comment by johnyannj** [comment]
@liubao68 ok

**Comment by liubao68** [comment]
fixed in https://github.com/apache/servicecomb-java-chassis/pull/1552
