### ISSUE TITLE
RestTemplateBuilder 缺少setConnectionTimeout和setReadTimeout方法

### ISSUE THREAD

**Issue by Nick-The-Uncharted** [apache/servicecomb-java-chassis#1468]
但是org.springframework.boot.web.client.RestTemplateBuilder#setConnectTimeout 支持

**Comment by liubao68** [comment]
```
org.apache.servicecomb.provider.springmvc.reference.RestTemplateBuilder 
```

Do not have any relationship with 

```
org.springframework.boot.web.client.RestTemplateBuilder
```

read [this](https://www.jianshu.com/p/490b48a0223a)  or [this](https://bbs.huaweicloud.com/forum/thread-21895-1-1.html) for timeout settings.

**Comment by Nick-The-Uncharted** [comment]
@liubao68 But I want to configure each request differently. A unified timeout value seems not to be enough.

**Comment by liubao68** [comment]
```
servicecomb.request.${service}.${schema}.${operation}.timeout
```
request timeout can be set to each operation.

**Comment by liubao68** [comment]
Close old issues, please feel free to open a new one.
