### ISSUE TITLE
文件下载接口，客户端Response body为空，导致客户端JS收不到文件流

### ISSUE THREAD

**Issue by whuxiari** [apache/servicecomb-java-chassis#1469]
参考如下文档写了一个文件下载接口，但是客户端收到的Response body为空，导致前端JS处理时获取不到文件流。

代码截图：
![image](https://user-images.githubusercontent.com/9291379/71141526-5ad6aa80-224f-11ea-846e-4cdcc6bfdb49.png)

客户端问题：
![image](https://user-images.githubusercontent.com/9291379/71141553-75a91f00-224f-11ea-8187-68ff945262b6.png)

服务端有过滤器，过滤器解析body的时候，body也是null，导致报了空指针异常：
![image](https://user-images.githubusercontent.com/9291379/71141578-8fe2fd00-224f-11ea-831e-84106273aec0.png)

参考文档：https://docs.servicecomb.io/java-chassis/zh_CN/general-development/file-download.html

https://github.com/apache/servicecomb-java-chassis/blob/master/integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/DownloadSchema.java

**Comment by whuxiari** [comment]
补充说明一下：在浏览器地址栏直接请求URL，是可以下载的文件的，如下图：

![image](https://user-images.githubusercontent.com/9291379/71141921-a2aa0180-2250-11ea-9fae-e3c5aa1256ce.png)

**Comment by yhs0092** [comment]
浏览器地址栏直接访问URL，如果能把文件正常下载下来的话，那服务端应该是没有问题的了。那样的话得看看前端的js脚本是不是有什么问题。

**Comment by whuxiari** [comment]
按上面的代码实例在Chrome浏览器上可以下载到文本文件。但将文件改成Excel之后，前端下载下来的文件是损坏的。

代码如下：
return ResponseEntity.ok()
                .header(HttpHeaders.CONTENT_TYPE, "application/msexcel;charset=UTF-8")
                .header(HttpHeaders.CONTENT_DISPOSITION, "attachment;filename=" + fileName)
                .body(new FileInputStream(FileUtils.getFile(filePath)));

前端响应如下图：
![image](https://user-images.githubusercontent.com/9291379/71150502-92a01b00-226c-11ea-89ac-5a2f00b2ee7e.png)


![image](https://user-images.githubusercontent.com/9291379/71150480-85832c00-226c-11ea-9808-7f8aaf8aa8b5.png)

**Comment by yhs0092** [comment]
代码和返回的消息头看上去都挺正常的，不过貌似你不是在本地做开发调试的对吧？建议先在本地跑一下看看，排查一下中间的代理或者网关造成问题的可能性。

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
