### ISSUE TITLE
开发环境微服务多次发布后网关服务发生GC, MircroserviceMeta占用内存过大

### ISSUE THREAD

**Issue by Gold-Z** [apache/servicecomb-java-chassis#1472]
每次服务升级版本，MircroserviceMeta 实例都保留旧的版本，不知道什么原因实例占用内存越来越大

![dump](https://user-images.githubusercontent.com/7219324/71154877-83729a80-2277-11ea-8071-e182d2d63f7a.png)

**Comment by liubao68** [comment]
This is a major problem working on 2.0.0(not released, but for REST transports the version is ready, and we still have a lot of work to do with HIGHWAY transports). Using versions before 2.0.0 should avoid change versions frequently or restart edge service is needed or the the memory will grow when a new version comes.

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
