### ISSUE TITLE
在Controller类的方法中如何获得request header中的信息

### ISSUE THREAD

**Issue by sunjinghan7331** [apache/servicecomb-java-chassis#1479]
请问在如下代码中，我如何在getUserAll()方法体中获得request header中Authorization字段所对应的值？

    @Path("/")
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @ApiOperation(value = "get all user informations", response = TenantResponse.class, responseContainer = "List")
    @ApiImplicitParams({@ApiImplicitParam(paramType = "header", value = "Authorization token", name = "Authorization",
        example = "Basic 18zgoYu4sSAP/RZ1lVrTVA==", dataType = "string", required = true)})
    public Response getUserAll() {
        
        return Response.ok().build();
    }

**Comment by liubao68** [comment]
```

@Path("/")
@GET
@Produces(MediaType.APPLICATION_JSON)
@ApiOperation(value = "get all user informations", response = TenantResponse.class, responseContainer = "List")
@ApiImplicitParams({@ApiImplicitParam(paramType = "header", value = "Authorization token", name = "Authorization",
    example = "Basic 18zgoYu4sSAP/RZ1lVrTVA==", dataType = "string", required = true)})
public Response getUserAll() {
    request.getHeader("Authorization");
    return Response.ok().build();
}

```


Or you can using InvocationContext, first put header to context in HttpServerFilter and then get it using InvocationContext.  [java-chassis-fence](https://github.com/apache/servicecomb-fence) can be a project example.

**Comment by sunjinghan7331** [comment]
好的
