### ISSUE TITLE
本地微服务能够注册到远端Service Center？

### ISSUE THREAD

**Issue by sunjinghan7331** [apache/servicecomb-java-chassis#1481]
在本地开发调试微服务，能够在microservice.yaml中指定远端service center 的地址，从而注册到远端service center？

**Comment by WillemJiang** [comment]
建议参考下面文档进行设置 https://docs.servicecomb.io/java-chassis/zh_CN/general-development/visit-sc.html

**Comment by sunjinghan7331** [comment]
设置过了，我在香港的一套环境上启动了service center，在本地开发的微服务注册不上去

**Comment by yhs0092** [comment]
网络是通的吗？

**Comment by sunjinghan7331** [comment]
网络是通的

**Comment by sunjinghan7331** [comment]
修改service center 的启动配置文件，修改启动ip为0.0.0.0即可远程访问

**Comment by yhs0092** [comment]
:+1:
