### ISSUE TITLE
Service Center Front前端界面的访问权限如何设置？

### ISSUE THREAD

**Issue by sunjinghan7331** [apache/servicecomb-java-chassis#1482]
Service Center Front前端界面的访问权限如何设置？

**Comment by yhs0092** [comment]
service center 相关的问题推荐去sc的issue列表里面提问~ https://github.com/apache/servicecomb-service-center/issues
BTW，据我所知，sc自带的[前端](https://github.com/apache/servicecomb-service-center/tree/master/frontend)当前是没有访问权限控制功能的

**Comment by sunjinghan7331** [comment]
好的
