### ISSUE TITLE
edge契约更新不动

### ISSUE THREAD

**Issue by leland17** [apache/servicecomb-java-chassis#1492]
感觉上了环境有些问题的。edge感知不到后面微服务最新接口字段的变化，重启和升级版本都试过了，edge还是感知不到新增的字段。

直接请求微服务节点是能够获取最新的接口数据，通过edge转发请求的话，就更新的接口字段展示不出来。

**Comment by yhs0092** [comment]
edge从sc拉取到了到新版本的微服务实例的话，会打印日志的，可以搜一下日志关键字`find instances`，看看打印了几条日志，像这样
```
2019-12-25 17:24:35,003 [INFO] find instances[1] from service center success. service=default/CseMonitoring/latest, old revision=null, new revision=3a995f3e509dd4b5ea14c852b983df92fce4431c org.apache.servicecomb.serviceregistry.registry.AbstractServiceRegistry.findServiceInstances(AbstractServiceRegistry.java:253)
2019-12-25 17:24:35,004 [INFO] service id=8b09a7085f4011e89f130255ac10470c, instance id=8b160d485f4011e89f130255ac10470c, endpoints=[rest://100.125.0.198:30109?sslEnabled=true] org.apache.servicecomb.serviceregistry.registry.AbstractServiceRegistry.findServiceInstances(AbstractServiceRegistry.java:261)
```

----------------

> edge感知不到后面微服务最新接口字段的变化

后端微服务的接口具体发生了什么变化呢？

----------------

> 重启和升级版本都试过了，edge还是感知不到新增的字段

是edge不动，后端服务升级或重启吗？

**Comment by leland17** [comment]
![image](https://user-images.githubusercontent.com/9267662/71441871-612cc100-273e-11ea-96ca-804660f07c62.png)

![image](https://user-images.githubusercontent.com/9267662/71441886-70137380-273e-11ea-984d-252832535749.png)
上述是接口数据的不同之处

是edge和后面微服务都升级了版本且重启了，都不生效。

**Comment by yhs0092** [comment]
EdgeService实际能感知到的是后端服务的契约，所以还是得看EdgeService加载的契约的内容是不是新版本的。可以去服务中心看一下新版本的服务的契约，或者把EdgeService的日志级别调成`DEBUG`级，`org.apache.servicecomb.core.definition.schema.ConsumerSchemaFactory#loadSwagger`方法中会打印从sc加载的契约内容。

如果契约内容是新的，但是EdgeService转发给后端的请求body仍然少了这两个字段，那可以在EdgeService里面打断点调试一下，先确定一下参数字段是哪个阶段丢的。
1. EdgeService接收外来请求并反序列化为后端服务契约声明的参数类型：

    这个操作是在`org.apache.servicecomb.common.rest.filter.inner.ServerRestArgsFilter#afterReceiveRequest` 方法中做的。从这里走到`org.apache.servicecomb.common.rest.codec.RestCodec#restToArgs`方法里面去看一下反序列化操作，`restToArgs`方法返回的args数组就是依照契约声明反序列化出来的参数数据。

2. EdgeService将参数做序列化再发送给后端服务：

    这个操作是在`org.apache.servicecomb.common.rest.filter.inner.ClientRestArgsFilter#beforeSendRequest`方法中做的。这里调用的`org.apache.servicecomb.common.rest.codec.RestCodec#argsToRest`方法将`org.apache.servicecomb.swagger.invocation.SwaggerInvocation#swaggerArguments`中对应的body参数序列化为发送给后端的body。

3. 接收后端服务返回的响应并做反序列化：

    操作流程在`org.apache.servicecomb.transport.rest.client.http.DefaultHttpClientFilter#extractResponse`中，你需要关注这个方法里对`org.apache.servicecomb.common.rest.codec.produce.ProduceProcessor#decodeResponse(io.vertx.core.buffer.Buffer, com.fasterxml.jackson.databind.JavaType)`方法的调用。

4. 将返回值body做序列化并返回给外部调用者：

    `org.apache.servicecomb.common.rest.filter.inner.ServerRestArgsFilter#beforeSendResponseAsync`方法中执行序列化body

如果出问题的是request body，那么需要关注1/2，response body出问题则需要关注3/4

**Comment by leland17** [comment]
感谢你的答复。问题解决了，是由于我们edgeService同样依赖了旧的api包，旧的api包中的model类和edge从注册中心拉取的schema之间不一致，导致edgeService序列化时候应该是加载的旧的api中model类，而不是从保持和注册中心拉取的schema一致。感谢

**Comment by yhs0092** [comment]
不客气 : )
对于强类型内核的Java-Chassis版本（1.x版本），框架会把契约中的`x-java-class`属性所记录的Java类型作为参数的实际类型。consumer端加载provider契约后会根据`x-java-class`字段去classpath中搜索是否存在这个类，如果存在就直接拿来用。如果不存在会根据契约动态生成这个Java类型。
一般edge不引入后端服务的jar包的话，每次加载新版本服务契约都会动态生成Java参数类型的（一个微服务版本对应一个ClassLoader），所以碰不到你这种问题。
不过你们这种场景下就会一直沿用依赖jar包里面的旧的参数类型了。

**Comment by liubao68** [comment]
Close old issues, please feel free to open a new one.
