### ISSUE TITLE
没有microservices文件夹 和 没有微服务的yaml时在服务重启后，在CSE上午无法注册成功

### ISSUE THREAD

**Issue by xuzhiweiand** [apache/servicecomb-java-chassis#1493]
没有microservices文件夹 和 没有微服务的yaml时在服务重启后，在CSE上午无法注册成功

SCBEngine | ServiceComb had closed
SCBEngine | The request is rejected. Cannot process the request due to STATUS = FAILED
SCBEngine | The request is rejected. Cannot process the request due to STATUS = FAILED
SCBEngine | The request is rejected. Cannot process the request due to STATUS = FAILED
SCBEngine | The request is rejected. Cannot process the request due to STATUS = FAILED

**Comment by yhs0092** [comment]
检查一下看看这段日志的前面是否有其他报错日志呢？一般是启动流程中抛出异常打断了Java-Chassis的启动流程。

**Comment by xuzhiweiand** [comment]
日志显示这个错误： 
      LOGGER.warn(
          "service center schema and local schema both are different:\n service center schema:\n[{}\n local schema:\n[{}]",
          scSchemaContent,
          localSchemaContent);

通过打印出来的比较，可以看到有个字段生成的顺序不一致。。如果打印这个错误是否会导致服务注册到CSE失败？？

**Comment by yhs0092** [comment]
会。
如果你同一个版本的服务启动两遍，生成的契约不一样的话，可能是因为你定义的参数类不是标准的Java Bean。建议排查一下字段顺序有变化的参数类型。
参考[Java-Chassis对于接口定义的约束](https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/interface-constraints.html)，在里面搜一下关键字`JAVA Bean`能找到和你这个问题相关的内容。

**Comment by xuzhiweiand** [comment]
好的，根据这个约束，我们再排查一下。
