### ISSUE TITLE
应答消息Content-Type charset=ANSI_X3.4-1968，不是utf8

### ISSUE THREAD

**Issue by bi-kai** [apache/servicecomb-java-chassis#1494]
response中Content-Type: application/json; charset=ANSI_X3.4-1968，字符集不是utf-8，ANSI是CSE带上的么？

**Comment by liubao68** [comment]
Maybe you need to debug your application and find where this header is setting. java-chassis is not likely to add this header

**Comment by bi-kai** [comment]
找到原因了，补充一下结果:
