### ISSUE TITLE
对于JDK8以上的支持问题

### ISSUE THREAD

**Issue by Shoothzj** [apache/servicecomb-java-chassis#1495]
使用RpcSchema注解，在jdk11及以上跑samples会出现failed to create lamda的问题，请问这个会是啥原因?在网上搜索了一下，大概是jdk8以上lamda机制变更导致的。使用jdk11以上使用servicecomb的计划是怎么样的?

**Comment by liubao68** [comment]
JDK9以上有很多不兼容特性。java-chassis暂时还没有针对以上版本进行适配和测试。

**Comment by liubao68** [comment]
可以使用 2.0.0 版本， 已经可以支持 JDK 11运行。
