### ISSUE TITLE
本地微服务注册到远端service center后，SC是否能提供路由功能？

### ISSUE THREAD

**Issue by sunjinghan7331** [apache/servicecomb-java-chassis#1496]
本地微服务注册到远端service center后，能否访问SC的ip从而调用到本地微服务？SC是否提供此能力？还是只能通过本地的ip调用微服务

**Comment by liubao68** [comment]
SC不是代理服务，是“注册发现服务”。服务可以自己往SC注册自己的信息，其他服务可以通过SC发现这些信息。

**Comment by sunjinghan7331** [comment]
好的
