### ISSUE TITLE
ServiceComb框架下如何进行api接口测试

### ISSUE THREAD

**Issue by sunjinghan7331** [apache/servicecomb-java-chassis#1498]
ServiceComb框架下如何进行api接口测试

**Comment by liubao68** [comment]
This is a generic question. 

java-chassis integration tests can be a reference for you

* demo : using docker to run all providers/consumers
* integration-tests: there is a customized engine to start/stop providers/consumers to run all tests.

**Comment by sunjinghan7331** [comment]
谢谢，可能我没有表述清楚，我想问的是ServiceComb支持使用什么工具类进行api接口测试代码的编写，像Junit一样的测试代码

**Comment by liubao68** [comment]
你可以使用类似@SpringBootTest等把Bean的执行环境初始化起来，然后调用接口进行测试。 不过java-chassis项目的大部分集成测试不是采用这种方式测试的，都是依赖于启动consumer/provider来测试。开发自己的执行引擎或者使用docker，对于微服务的集成测试能够带来非常大的便利。涉及到网络通信的测试，建议采用集成测试的方式（当然集成测试也是在执行mvn test的过程中运行的，用JUnit API检测运行结果， java-chassis的DEMO都是这样被执行的）

**Comment by sunjinghan7331** [comment]
好的，谢谢
