### ISSUE TITLE
JDK12demo启动报错：NullPointerException，换回JDK8没问题。

### ISSUE THREAD

**Issue by mf1632015** [apache/servicecomb-java-chassis#1502]
JDK12 启动java-chassis-demo里面的所有的例子，无论是provider还是consumer都会报空指针异常，经过排查发现，下面的代码处，常量MODIFIERS_FIELD是null。我怀疑，JDK12的Field类已经不能获得它的成员变量了。我也试了下，Field.getDeclaredFields()返回的是一个空数组。
![image](https://user-images.githubusercontent.com/29472151/71555447-686a0c80-2a67-11ea-9551-ed8a323ae741.png)
错误异常截图如下：
![image](https://user-images.githubusercontent.com/29472151/71555470-a9622100-2a67-11ea-8f58-b13b4d96fa34.png)

**Comment by mf1632015** [comment]
图片上传失败了，报空指针异常的位置位于org.apache.servicecomb.foundation.common.utils.ReflectUtils#MODIFIERS_FIELD
static {
    MODIFIERS_FIELD.setAccessible(true);
  }

异常信息没有保存，就是上图的MODIFIERS_FIELD是空指针，如果从源代码看的话，就是JDK12的Field这个反射类没办法继续反射了。Field.class.getDeclaredFields()是个空数组

**Comment by mf1632015** [comment]
沟通了组内的大牛，他怀疑是java的默认安全级别提升了。不过jdk12已经被我卸载了，我有机会复现下看看。

**Comment by liubao68** [comment]
JDK9以上有很多不兼容特性。java-chassis暂时还没有针对以上版本进行适配和测试。

**Comment by WillemJiang** [comment]
@liubao68  我觉得是时候考虑一下支持jdk11了。

**Comment by zhfeng** [comment]
https://stackoverflow.com/questions/56039341/get-declared-fields-of-java-lang-reflect-fields-in-jdk12

**Comment by zhfeng** [comment]
@WillemJiang jdk11 有LTS的版本吗？

**Comment by WillemJiang** [comment]
JDK11 是一个长期支持版本。 https://www.oracle.com/technetwork/java/java-se-support-roadmap.html

**Comment by liubao68** [comment]
JDK 12 为了安全性， 所有破坏对象封装性的的操作都是不允许的了。 目前 java-chassis 还有部分特性以及一些三方件还使用这些特性，无法运行于 JDK 12。 发布的 2.0.0 版本已经可以在 JDK 11运行， 目前  JDK 11 是 JAVA 的 TLS 版本，建议优先采用这个版本。 

这个问题先关闭， 相关JDK 封装特性的修改已经创建  apache 任务， java-chassis 需要在后续版本支持 JDK 12及其以上版本。
