### ISSUE TITLE
怎么自定义Jackson的ObjectMapper？

### ISSUE THREAD

**Issue by zhufeizzz** [apache/servicecomb-java-chassis#1505]
我想做两件事：
1、支持org.json的转换
2、把所有Rest接口默认使用下划线方式

没找到相关文档，扒代码找到如下方式设置：
```
JsonUtils.OBJ_MAPPER.registerModule(new JsonOrgModule());
JsonUtils.OBJ_MAPPER.setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE);
        
RestObjectMapperFactory.getRestObjectMapper().registerModule(new JsonOrgModule()); 
RestObjectMapperFactory.getRestObjectMapper().setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE);
```

我试了下org.json支持没问题，但是SNAKE_CASE会导致ServiceComb无法启动，提示微服务命名格式不对。

我这是标准的扩展ObjectMapper的方式吗？扩展的时候到底有什么限制？

**Comment by liubao68** [comment]
你需要使用RestObjectMapperFactory setConsumerWriterMapper 和 setDefaultRestObjectMapper覆盖AbstractRestObjectMapper，需要先自定义一个实现。 

通常，不推荐自定义，这个会导致不同的系统之间相互协作出现问题，或者在a -> b -> c等场景下，容易出现错误。 仅仅在需要兼容的情况下，做适当的处理，否则建议改善接口设计，遵循标准行为是推荐的方式。

**Comment by zhufeizzz** [comment]
1、有没有文档定义哪些行为能改，判断原则有吗？比如我现在改了，目测能运行，但是不知道有没有什么坑。
2、setConsumerWriterMapper是什么场景用的，调试时没看到有地方使用。

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.

**Comment by JasonBeiJing** [comment]
不推荐自定义？这个不应该吧，比如A服务用java开发，默认行为json串就是驼峰命名法；B服务可能是另一种语言，其发布的api响应可能是snake case，所以对于json格式，应该不具有某种语言特性吧

**Comment by liubao68** [comment]
你说的这种场景我理解和是否支持定制ObjectMapper没关系，比如可以使用 `@JsonProperty` 来处理java 对象和json文本的映射。 
ObjectMapper不允许定制更多的强调是标准行为， 比如对于`Date`类型，按照Open API的标准，一定是按照 ISO 标准格式编码， 定制 `Date`的序列化方式会使得同样的 swagger， 不同的开发者返回的 json 文本有差异。
