### ISSUE TITLE
能否允许业务对流式数据进行处理，比如上行流可以让业务自己来读取

### ISSUE THREAD

**Issue by zhangrongfei** [apache/servicecomb-java-chassis#1506]
现在业务需要流式读取数据，但是貌似框架会把数据从socket里面读取完毕，然后一把给到下面业务处理，这块有没有比较好的方法来完成，多谢！

**Comment by liubao68** [comment]
可以参考这个[示例](https://github.com/apache/servicecomb-java-chassis/blob/master/demo/demo-signature/src/main/java/org/apache/servicecomb/demo/signature/ClientSignature.java)

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
