### ISSUE TITLE
通过RestClient/PostMan等工具发送的HTTP 请求中的Cookie缺失了部分信息

### ISSUE THREAD

**Issue by whuxiari** [apache/servicecomb-java-chassis#1507]
以下是在工具中配置的Cookie内容，为何在服务端从request中取出来的cookie少了authInfo？

X-HD-SESSION=12456c12-2*****************37ee545d5; authInfo="{\"expiretime\":\"20200102T102330Z\",\"rtCiphertext\":\"7qfADfdUA*******************************************SQ2/XhB6wV6siN6P9UyFvLzivo/cLOYTrom8JV0vOAEy/SCYXCts7iutg+Nv5+FhvovWBsCPS/fPnxBaCjWiLJWzlI2nw\",\"createtime\":\"20200102T092330Z\",\"accesstoken\":\"CV4NxKKd/E*******************cIpjY9uoZs8uGD/Hv6rw01AD*****************LDelXxDg==\",\"siteID\":\"11\",\"x-uid\":\"900086*****001817\"}"; csrfToken=24B4805793964D1D7D558649451764E1CD0D602E18E9542C97; x-hd-grey=1; x-country=CN; x-userType=2; ID_CAS_ISCASLOGIN=true; CASLOGINSITE=1; LOGINACCSITE=1; x-uid=90008*****000375; x-teamId=90008*****000375; x-country=CN; x-userType=2; x-uid=90008*****000375; developer_userinfo=%7B%22siteid%22%3A***********************************amid%22%3A%22900086000000000375%22%7D

**Comment by whuxiari** [comment]
工具设置如下图

![image](https://user-images.githubusercontent.com/9291379/71669327-447c3300-2da7-11ea-9664-6f443786a3b2.png)

**Comment by liubao68** [comment]
你可以试试更加简单的cookie，或者将内容编码一下再发送（HTTP的HEADER只支持[特定字符集](https://stackoverflow.com/questions/4400678/what-character-encoding-should-i-use-for-a-http-header)）

**Comment by whuxiari** [comment]
试过将Cookie内容进行URL编码，编码之后可以获取到了。

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
