### ISSUE TITLE
为什么在过滤器中，无法向HTTP请求头添加参数？

### ISSUE THREAD

**Issue by whuxiari** [apache/servicecomb-java-chassis#1509]
如下图，自定义了一个过滤器，在过滤器中向请求头添加参数，在Controller中无法拿到该参数；
但是添加的Parameter参数，在Controller中可以获取到。这是为什么？

![image](https://user-images.githubusercontent.com/9291379/71711033-f82e0300-2e39-11ea-9d80-db27c97eec50.png)

**Comment by yhs0092** [comment]
你说的过滤器是什么过滤器，能否给一个简单的问题复现demo呢？

**Comment by whuxiari** [comment]
接口HttpServerFilter的实现类，业务逻辑已省略，重点看：

![image](https://user-images.githubusercontent.com/9291379/71713572-354bc280-2e45-11ea-9235-89a5d9216136.png)

参考文档：
https://docs.servicecomb.io/java-chassis/zh_CN/general-development/http-filter.html

**Comment by yhs0092** [comment]
因为 HttpServletRequestEx 在服务端的实现类确实没有实现 `setHeader` 和 `addHeader` 的逻辑啊。
你可以打断点debug进去看看，`org.apache.servicecomb.common.rest.filter.HttpServerFilter`接口给出了这两个方法的默认实现，是空的

**Comment by whuxiari** [comment]
为啥不实现呢？

那这里要在Filter层设置参数到header中，在Controller层获取，应该怎么实现呢？

**Comment by sunjinghan7331** [comment]
可以使用invocation这个参数进行传递.
在过滤器的afterReceiveRequest()方法中,将你要传递的header参数使用
invocation.addContext(Constants.DEVELOPER_UID, “123456”);
的方式进行包装，然后在Controller中使用
public Response logout(InvocationContext context) {
        String value = context.getContext(Constants.DEVELOPER_UID);
        return null;
    }
即可获取到值。

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.

**Comment by xuzhihao975** [comment]
我也想拦截请求下来，做校验后，设置一个header，然后再调用接口。
invocation.getRequestEx().addHeader("x-user-id", userId);
但是不行，没有设置成功。因为调用的接口需要这个请求头。
