### ISSUE TITLE
如何获取项目的整体接口文档，而不是按照schemaId进行分类后的分散的接口文档

### ISSUE THREAD

**Issue by sunjinghan7331** [apache/servicecomb-java-chassis#1511]
在我的项目中共有两个Controller类，每个类各有一个schemaId，这两个schemaId是不同的，在服务启动时会生成两套接口文档，分别以这两个schemaId命名，并在ServiceCenter的Schema这一栏中列出来。那么我现在需要将这两个接口文档合并为一个，而同时我又不想将这两个Controller类合并到一起，请问有什么办法？还有就是我如何获取生成的接口文档？是否有相应的支持方法？

**Comment by liubao68** [comment]
可以了解下 java-chassis 提供的 [inspector](https://blog.csdn.net/devcloud/article/details/90755031)

**Comment by sunjinghan7331** [comment]
@liubao68 详细的看了一下inspector的能力，发现并不能满足我的需求。如果一个工程下有两个schema，那么会生成两套契约文件，如何将这两套契约合为一个？框架是否有这个能力？还有就是生成的契约文件如何获取？Java-chassis中是否有相应的方法获取到契约文件？

**Comment by liubao68** [comment]
提供的参考里面有部分生成文档的功能。 你提的“合并契约”是不支持的。需要下载到所有契约文件，根据业务需求，再加工下。

**Comment by sunjinghan7331** [comment]
好的，知道了
