### ISSUE TITLE
CSE的服务端会话缓存是否开启和缓存周期这个是在哪块配置的？

### ISSUE THREAD

**Issue by kqiao** [apache/servicecomb-java-chassis#1512]
### session ID 由服务器端支持，协议中的标准字段，因此基本所有服务器都支持，服务器端保存会话ID以及协商的通信信息，Nginx 中1M 内存约可以保存4000个 session ID 机器相关信息，占用服务器资源较多;
=====================
### 就是这个TLS协议下的sessionID缓存机制

**Comment by kqiao** [comment]
![image](https://user-images.githubusercontent.com/1992470/71944150-d5b33580-31fd-11ea-8ee6-9566d0f87f31.png)

**Comment by liubao68** [comment]
JDK 13之前的版本不支持session ticket. 你可以采用OpenSSL替换JDK的实现。这个特性在TLS1.3协议里面已经废弃，采用了其他机制替换。详细信息可以检索下其他网络资料。

**Comment by kqiao** [comment]
嗯，没有用session ticket。只是用了session ID缓存，这个是TLS标准协议支持的。在CSE上通过sslEnabled开启后已经验证过了，想确认下这个sessionID缓存在CSE上怎么配置 是否开启 和 缓存时间。

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
