### ISSUE TITLE
探针埋点问题

### ISSUE THREAD

**Issue by JangNum** [apache/servicecomb-java-chassis#1513]
需要埋点获取CSE发起调用时的endpoint和微服务接口名，请问要在哪个底层类的哪个方法埋点？

**Comment by liubao68** [comment]
你可以看下一个RPC调用的[运行图](http://servicecomb.apache.org/cn/docs/open-design/) 。 

客户端选择endpoint是在LoadBalanceHandler里面做的，然后地址信息会存到Context里面，其他Handler也会获取到。 

handler接口如下：invocation里面能够取到接口和endpoint信息
```
public void handle(Invocation invocation, AsyncResponse asyncResp)
```

**Comment by JangNum** [comment]
> 你可以看下一个RPC调用的[运行图](http://servicecomb.apache.org/cn/docs/open-design/) 。
> 
> 客户端选择endpoint是在LoadBalanceHandler里面做的，然后地址信息会存到Context里面，其他Handler也会获取到。
> 
> handler接口如下：invocation里面能够取到接口和endpoint信息
> 
> ```
> public void handle(Invocation invocation, AsyncResponse asyncResp)
> ```

非常感谢 ，已经解决。
