### ISSUE TITLE
使用servlet将工程打成war包，无法生成契约

### ISSUE THREAD

**Issue by sunjinghan7331** [apache/servicecomb-java-chassis#1514]
![image](https://user-images.githubusercontent.com/40970933/72032630-e54c8000-32ca-11ea-90e9-8ee3129e0e6f.png)

使用上述方法将项目打成war包放在tomcat下启动，成功注册到service center了，但是没有生成契约文件，不知道是什么原因，Controller类上面添加了@RestSchema的注解，本地启动是没有问题的，但是打包后就出了问题

**Comment by liubao68** [comment]
May be you can add this to your web.xml

```
  <context-param>
    <param-name>contextConfigLocation</param-name>
    <param-value>
      classpath*:META-INF/spring/*.bean.xml
    </param-value>
  </context-param>
```

see this [demo](https://github.com/apache/servicecomb-java-chassis/blob/master/demo/demo-server-servlet/src/main/webapp/WEB-INF/web.xml)

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
