### ISSUE TITLE
【求助】CSE框架edge直接返回如何记录traceId到cse接口日志

### ISSUE THREAD

**Issue by gaoming28** [apache/servicecomb-java-chassis#1515]
![image](https://user-images.githubusercontent.com/52325473/72044486-d4ae0100-32ee-11ea-8946-c5052956978e.png)

打印方式为yaml中如下方式：

pattern: "%SCB-traceId|%{yyyy-MM-dd HH:mm:ss.SSS}t|%h|%r|%s|%D"

traceId加入上下文方式（非edge直接返回场景可以正常打印）：

ContextUtils.getInvocationContext().addContext(Const.TRACE_ID_NAME, traceId)

使用 routingContext.response() 返回的

**Comment by liubao68** [comment]
I do not quite understand your question. Maybe you can investigate [RestServerVerticle](https://github.com/apache/servicecomb-java-chassis/blob/master/transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestServerVerticle.java) , the access log module is bounded as a Handler to mainRoot.

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
