### ISSUE TITLE
用spring boot拉起service-comb微服务(vert.x）方式，能不能注解代替xml

### ISSUE THREAD

**Issue by loringao** [apache/servicecomb-java-chassis#1520]
1. edgeservice.xxxxx.resource.config.cse.handler.xml
2.edgesservice.xxxxx.resource.services.org.apache.servicecomb.common.rest.filter.HttpServerFilter

**Comment by liubao68** [comment]
Handlers and HttpServerFilters are not loaded by SPRING framework, you can not using annotations like \@Component

**Comment by loringao** [comment]
Ok, please close this issue
