### ISSUE TITLE
接口返回值定义的是ResponseEntity，为什么返回值的Body为空？

### ISSUE THREAD

**Issue by whuxiari** [apache/servicecomb-java-chassis#1522]
返回代码参考：return ResponseEntity.status(status).body(message)；

**Comment by liubao68** [comment]
能将完整的接口原型定义和客户端调用方式的代码贴一下吗？

**Comment by whuxiari** [comment]
通过这样返回，在前端查看Body为空。不是null，是啥都没有。    
public static ResponseEntity<String> getResponseEntity(XXXXException e) {
        return ResponseEntity.status(HttpStatus.valueOf(e.getCode())).body(e.getMsg());
    }

改成这样抛出异常，前端是可以获取到Body的：
throw new InvocationException(e.getCode(), e.getMessage(), e.getMsg());

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
