### ISSUE TITLE
故障注入功能配置生效问题

### ISSUE THREAD

**Issue by JangNum** [apache/servicecomb-java-chassis#1523]
请问，通过修改配置对微服务进行故障注入时，故障注入配置生效的耗时是多少？ 需要重启应用吗？

**Comment by liubao68** [comment]
java-chassis的故障注入都是通过[Hanlders](https://github.com/apache/servicecomb-java-chassis/tree/master/handlers/handler-fault-injection)实现的， 内部配置生效依赖于动态配置下发生效。 这个取决于连接[配置中心的机制](https://docs.servicecomb.io/java-chassis/zh_CN/config/general-config.html)，如果是pull模式（默认），时效性一般在1~2个pull周期，默认是30s一个周期。 如果是push模式，时效性更好。 但是pull模式的可靠性会好很多。

**Comment by JangNum** [comment]
> java-chassis的故障注入都是通过[Hanlders](https://github.com/apache/servicecomb-java-chassis/tree/master/handlers/handler-fault-injection)实现的， 内部配置生效依赖于动态配置下发生效。 这个取决于连接[配置中心的机制](https://docs.servicecomb.io/java-chassis/zh_CN/config/general-config.html)，如果是pull模式（默认），时效性一般在1~2个pull周期，默认是30s一个周期。 如果是push模式，时效性更好。 但是pull模式的可靠性会好很多。

理解了，非常感谢。

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
