### ISSUE TITLE
除了在controller参数里声明 Invocation 外，能否提供便捷方法获取Invocation

### ISSUE THREAD

**Issue by Nick-The-Uncharted** [apache/servicecomb-java-chassis#1529]
类似于 org.apache.servicecomb.swagger.invocation.context.ContextUtils#getInvocationContext

**Comment by yhs0092** [comment]
能否详细描述一下场景呢？Java-Chassis的[Handler](https://github.com/apache/servicecomb-java-chassis/blob/master/core/src/main/java/org/apache/servicecomb/core/Handler.java)/[HttpServerFilter](https://github.com/apache/servicecomb-java-chassis/blob/master/common/common-rest/src/main/java/org/apache/servicecomb/common/rest/filter/HttpServerFilter.java)/[HttpClientFilter](https://github.com/apache/servicecomb-java-chassis/blob/master/common/common-rest/src/main/java/org/apache/servicecomb/common/rest/filter/HttpClientFilter.java)接口方法的参数表里都是有Invocation的。除了这些地方和你写的REST 接口类（或者叫它controller），不知道你还要在什么地方拿Invocation，以及做什么事情。

**Comment by Nick-The-Uncharted** [comment]
比如我提供一个工具类给其他人在service层用，serviceImplA不需要使用invocation，serviceImplB需要，关键这个service的接口已经给出去了，这时候如果能直接获取Invocation会方便很多。

**Comment by liubao68** [comment]
1. Invocation is subclass of InvocationContext, so that you can try .ContextUtils#getInvocationContext
2. You can add a new method:

```
service(args)
service(args, invocation)
```

This is a better solution, or you assume users call service in an determined context, e.g. no thread switch and in a controller context.

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
