### ISSUE TITLE
接口参数声明使用了子类，服务启动后接口契约识别的参数只有子类的，无父类中定义的属性参数

### ISSUE THREAD

**Issue by ywx307266** [apache/servicecomb-java-chassis#1530]

**Comment by liubao68** [comment]
Can you debug the class AbstractOperationGenerator method extractAggregatedParameterGenerators to find out what's going on?

**Comment by ywx307266** [comment]
@BeanParam 这个注解修饰的参数 框架包中解析类BeanParamAnnotationProcessor 只解析当前类定义的字段，不包含父类的；这是官方源码
![20200114-093151(eSpace)](https://user-images.githubusercontent.com/38533501/72306044-c4ac6d80-36b0-11ea-8c7f-c685fc190d8b.png)

**Comment by liubao68** [comment]
我们分析下这种场景是否支持。不过建议替换一种方式，不要在BeanParam使用复杂的数据结构。即使对于简单类型的BeanParam，也建议越少越好，因为太多的query参数不是一个好主意， 此外还有一些内部RPC逻辑处理上存在的一些潜在问题。

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
