### ISSUE TITLE
rest方式通过edge网关调用微服务的时候使用@Requestbody接受json字符串映射成java对象中文变问号如何解决？

### ISSUE THREAD

**Issue by luhuaitong** [apache/servicecomb-java-chassis#1537]
我都web项目，页面发ajax请求发送json字符串到web项目的后台使用@Requestbody接受并映射成java实体类对象数据接受没有问题，但是在web项目（相当于消费者项目）去通过rest方式调用提供者服务，因为servicecomb不支持复杂类型的参数传递，所以把java对象通过fastjson转换成了json字符串，传递给提供者，提供者使用@Requestbody接受json映射java实体类的时候，参数中的中文全变成了问号，数字没有问题正常显示，请问怎么可以解决这个中文显示问号的问题

**Comment by liubao68** [comment]
这个问题可能需要你先调试下代码，看看问题在哪儿。有几个关键环节： 1. fastjson编码前后；2. java-chassis RestCodec类编码前后。

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
