### ISSUE TITLE
急急急！cse的微服务配置flowcontrol中operation，配置的这个值是单实例的值，还是汇总的值？

### ISSUE THREAD

**Issue by kindasusenne** [apache/servicecomb-java-chassis#1538]
flowcontrol中存在microservice/schema/operation三个级别的配置 如果配置operation，配置的这个值是单实例的值，还是几台实例的汇总的值？

**Comment by liubao68** [comment]
本实例的。如果是provider，表示别人请求本实例本方法的流量；如果是consumer，表示本实例请求被请求服务的所有实例的方法的流量。

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
