### ISSUE TITLE
在edge的Dispatcher的onRequest方法中去调用redis会不会用线程上的问题

### ISSUE THREAD

**Issue by NoComments** [apache/servicecomb-java-chassis#1539]
在edge的Dispatcher的onRequest方法中去调用redis会不会用线程上的问题。

现在想在edge中通过访问redis来判断http header的token的合法性，请问应该放到request中去做，

还是放到handler里去实现。

**Comment by liubao68** [comment]
都是可以的。 但是需要注意edge里面是处理默认是reactive的，因此写的代码不能阻塞。 认证鉴权可以参考[servicecomb-fence](https://github.com/apache/servicecomb-fence)，很多相关的开发技巧这里面都会用到。

**Comment by NoComments** [comment]
多谢。
