### ISSUE TITLE
开启Https双向认证后如何对接nginx

### ISSUE THREAD

**Issue by edsuperyang** [apache/servicecomb-java-chassis#1543]
开启https双向认证
![image](https://user-images.githubusercontent.com/12776176/72579596-88794700-3914-11ea-9f24-4b81adadae34.png)

此时nginx接入的请求报错
2020/01/17 09:35:50 [error] 14558#0: *5546524 SSL_do_handshake() failed (SSL: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:SSL alert number 42) while SSL handshaking to upstream, client: 58.240.77.242, server: lfsmurfsecuritytest.hwcloudtest.cn, request: "POST /smurf/v1/device/user/its/schedule HTTP/1.1", upstream: "https://10.31.53.67:18080/smurf/v1/device/user/its/schedule", host: "lfsmurfsecuritytest.hwcloudtest.cn:21443"

请问开启https后 ，nginx如何配置对应的证书？没找到相关资料

**Comment by yhs0092** [comment]
如果你的NGINX是做反向代理的，Java-Chassis这边的微服务开启了双向认证的话，就需要NGINX配置客户端证书，证书能被Java-Chassis微服务信任。
可以在Java微服务启动命令里加上`-Djavax.net.debug=ssl`看看SSL握手具体在哪一步报错。
Nginx证书的配置方式需要查阅Nginx的资料才行。

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
