### ISSUE TITLE
edge部署在docker中报以下错误

### ISSUE THREAD

**Issue by NoComments** [apache/servicecomb-java-chassis#1546]

**Comment by NoComments** [comment]
Unexpected error in server.cause:IOException.message:Connection reset by peer 
会重复滚动这条错误

**Comment by liubao68** [comment]
有可能是开启了监控检查。某些基于TCP的监控检查机制，会定期给微服务发送一个TCP报文，然后立即关闭连接，导致微服务打印上述错误（这个TCP报文不是完整的TCP握手，早期一些C的程序，为了减少TCP握手次数，会在发送SYN报文后，立即RST）。 这个不影响业务功能，但是会有很多错误日志。 可以通过设置logger关闭这个日志显示， 也可以尝试将监控检查调整为其他策略，比如HTTP。

**Comment by NoComments** [comment]
收到，非常感谢。
