### ISSUE TITLE
swagger method wait not exist in producer

### ISSUE THREAD

**Issue by Java-debuger** [apache/servicecomb-java-chassis#1547]
切换到2.3.77版本的CSE后，服务启动报错：swagger method wait not exist in producer。我的代码中没有名为wait的method

**Comment by liubao68** [comment]
可以看下swagger内容，是否有wait这样一个operation-id。 然后再看看这个怎么来的。比如看看服务端启动日志最新的swagger是否有。

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
