### ISSUE TITLE
edge网关边缘服务采用web容器tomcat部署是如何配置的

### ISSUE THREAD

**Issue by zouwenxmu** [apache/servicecomb-java-chassis#1554]
使用springboot方式部署功能都正常，参考普通微服务的war部署方式，路由转发功能不正常，报404
 `  <servlet>
        <servlet-name>SpringMVCServlet</servlet-name>
        <servlet-class>org.apache.servicecomb.transport.rest.servlet.CseDispatcherServlet</servlet-class>
        <load-on-startup>1</load-on-startup>
    </servlet>
    <servlet-mapping>
        <servlet-name>SpringMVCServlet</servlet-name>
        <url-pattern>/*</url-pattern>
    </servlet-mapping>`

**Comment by liubao68** [comment]
edge网关只能运行于vert.x reactive模式。 不支持运行于servlet之上。
