### ISSUE TITLE
query about servicecomb rsa  authentication between microservices

### ISSUE THREAD

**Issue by leland17** [apache/servicecomb-java-chassis#1566]
I want to konw how should i do with my alpha tests if my microservice is configed RSA authentication, how can i  genarate the rsa public key the register center make signature with the private key?

will it be okay with the edge service ?

**Comment by leland17** [comment]
and i have test, when i configed the auth-consumer and auth-provider in the edge service, it seems not take effect.

**Comment by liubao68** [comment]
Public Key and Private Key are auto generated when servicecomb is started up and every instance has different key pairs. Please check AuthHandlerBoot for details.

**Comment by leland17** [comment]
@liubao68 I found the config auth-provider takes no effect on the edge service, is it right?

**Comment by liubao68** [comment]
Yes. Edge service do not enter "provider handler chain" bacause it is handling HTTP requests and acting as raw HTTP server. When edge forwarding requests to internal services, "consumer handler chain" is executed. For requests from browsers, you need enable HTTPS to authenticate the client.

**Comment by leland17** [comment]
okay，get it，thanks a lot

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
