### ISSUE TITLE
默认线程池没有指定线程名称

### ISSUE THREAD

**Issue by johnyannj** [apache/servicecomb-java-chassis#1573]
servicecomb默认使用的线程池
org.apache.servicecomb.core.executor.ThreadPoolExecutorEx#ThreadPoolExecutorEx

在初始化的时候没有指定有意义的线程名称，难以在堆栈中区分线程，不利于问题的调查。

**Comment by liubao68** [comment]
I looked ThreadPoolExecutorEx, and find that the thread name is given to 'group{num}-{num}-thread-{num}', and this is a special pattern.
