### ISSUE TITLE
服务报错InvocationException，信息是message=not support file upload.

### ISSUE THREAD

**Issue by Nongkahei1231** [apache/servicecomb-java-chassis#1574]
服务报错InvocationException，这个是什么原因导致
http server failed.org.apache.servicecomb.swagger.invocation.exception.InvocationException: InvocationException: code=590;msg=CommonExceptionData [message=not support file upload.]	at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.doCreate(ExceptionFactory.java:74)	at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.create(ExceptionFactory.java:61)	at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.createProducerException(ExceptionFactory.java:69)

**Comment by yhs0092** [comment]
这个通常是没有设置上传文件缓存目录导致的

**Comment by yhs0092** [comment]
资料在这里   http://liubao68.gitee.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/general-development/file-upload/
参考 `servicecomb.uploads.directory` 配置项的说明

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
