### ISSUE TITLE
CSE目前的熔断是服务级的还是方法级的？

### ISSUE THREAD

**Issue by hongfeihuangseu** [apache/servicecomb-java-chassis#1577]

**Comment by liubao68** [comment]
Please take a look at [1](http://liubao68.gitee.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/build-provider/configuration/downgrade-strategy/) & [2](http://liubao68.gitee.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/references-handlers/loadbalance/)

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
