### ISSUE TITLE
serviceComb框架如何设置支持跨域？

### ISSUE THREAD

**Issue by whuxiari** [apache/servicecomb-java-chassis#1578]
业务需要支持跨域访问，而浏览器会在跨域发生前先发起试探的OPTIONS请求，服务端却响应“Method not Allowed”失败，最终导致请求失败。

OPTIONS前端请求：
![image](https://user-images.githubusercontent.com/9291379/74639080-36903f00-51a8-11ea-82a2-1908fb0ca81c.png)
响应体：
![image](https://user-images.githubusercontent.com/9291379/74639095-3db74d00-51a8-11ea-83ba-fea2494218ec.png)

服务端已通过过滤器设置支持跨域如下：

        responseEx.setHeader(HttpHeaders.ACCESS_CONTROL_ALLOW_ORIGIN, ALLIANCE_DOMAIN);

        responseEx.setHeader(HttpHeaders.ACCESS_CONTROL_ALLOW_CREDENTIALS, "true");

        responseEx.setHeader(HttpHeaders.ACCESS_CONTROL_ALLOW_HEADERS,
            "Content-Type,X-Requested-With,Access-Control,Referer,Sec-Fetch-Dest,User-Agent,Accept-Encoding,Cache-Control,Content-Length,Host,Origin");
        responseEx.setHeader(HttpHeaders.ACCESS_CONTROL_ALLOW_METHODS, "POST,GET,OPTIONS,DELETE,PUT");
        responseEx.setHeader(HttpHeaders.ACCESS_CONTROL_MAX_AGE, "86400");

**Comment by liubao68** [comment]
ServiceComb的[跨域配置](https://docs.servicecomb.io/java-chassis/zh_CN/general-development/CORS/)

你的跨域设置代码是在什么地方进行的？ ServiceComb 接口定义是不存在 response 对象的。

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
