### ISSUE TITLE
使用zuul网关进行http代理对接servicecomb,在http请求中添加header报错

### ISSUE THREAD

**Issue by SheldonDemo** [apache/servicecomb-java-chassis#1581]
使用Zuul网关进行代理，把前台编译出的静态文件放入resources/static目录下，发现带有Authorization header的http请求报错：
`CommonExceptionData [message=Parameter is not valid for operation [user-mgmt-be.user-mgmt-be.getUser]. Parameter is [Authorization]. Processor is [header].]`
不带header的请求调用正常。

zuul网关代码：
`@SpringBootApplication`
`@EnableZuulProxy`
`@EnableServiceComb`
`public class GatewayApplication {`
`public static void main(String[] args) {`
`    SpringApplication.run(GatewayApplication.class, args);`
`  }`
`}`
前台axios调用代码：
`url = '/user-mgmt-be/v1/users/' + res.data.userId`
`            axios({`
`              method: 'GET',`
`              url: url,`
`              headers: {`
`                'Authorization': 'Basic ' + res.data.token,`
`                'Content-Type': 'application/json'`
`              }`
`            })`

**Comment by liubao68** [comment]
You can first debug `RestCodec` to find the actual resons for the codec error.  For security reasons, the exception is not printed by default.

**Comment by SheldonDemo** [comment]
> You can first debug `RestCodec` to find the actual resons for the codec error. For security reasons, the exception is not printed by default

**Comment by SheldonDemo** [comment]
> You can first debug `RestCodec` to find the actual resons for the codec error. For security reasons, the exception is not printed by default.
I can't debug  common-rest-1.3.0.jar...

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
