### ISSUE TITLE
SpringBoot集成ServiceComb后测试用例运行时端口冲突

### ISSUE THREAD

**Issue by sunjinghan7331** [apache/servicecomb-java-chassis#1583]
在原本的Springboot项目上加入了ServiceComb框架，项目可以正常注册到service center，但是测试用例中使用了@SpringBootTest(classes = MainServer.class)注解。MainServer如下：
public class MainServer {
    public static void main(String[] args) {
        SpringApplication.run(MainServer.class, args);
    }
}
由于项目main和test使用的是一个microservice.yaml，所以在项目正常启动时，测试用例会由于端口冲突无法启动。在test-resources文件夹中新建了测试专用的microservice.yaml，但是测试用例依然使用main项目中的配置文件，不识别test-resources中的配置文件，请问该如何解决。

**Comment by liubao68** [comment]
你可以在日志里面搜索一下， java-chassis 加载的配置文件会打印出来:

```
2020-02-19 10:40:33.450  INFO 5844 --- [           main] o.apache.servicecomb.config.ConfigUtil   :  jar:file:/C:/Users/Administrator/.m2/repository/org/apache/servicecomb/java-chassis-core/2.0.0/java-chassis-core-2.0.0.jar!/microservice.yaml.
```

还可以看下 target 目录， 是否在 classes 目录有正确的 `microservice.yaml`

**Comment by sunjinghan7331** [comment]
@liubao68 可能我没有描述清我的述求，我的正常项目依靠位于src/main/resources中的microservice.yaml文件正常运行，我想让我的测试用例依靠位于src/test/resources中的microservice.yaml文件启动运行，应该如何做。
目前的情况是我位于src/test/resources中的microservice.yaml文件在测试用例启动时没有被读取，测试用例启动时默认读取了位于src/main/resources中的microservice.yaml文件

**Comment by liubao68** [comment]
我理解的就是你的意思。 按照你的项目结果，编译器应该会在 target/classes里面存着一个microservice.yaml文件， 并且是 test 目录下的， 如果是 main 下面的， 而且没有  test 目录下面的， 那么可能是 IDE的问题， 因为它没给你拷贝到测试进程的 classpath 里面。 这个估计是错误的原因。 如果不是这个，参考我前面的回复排查下日志。

**Comment by sunjinghan7331** [comment]
@liubao68 
我的target/classes目录下和target/test-classes目录下都有microservice.yaml，我排查了我的日志，先加载了磁盘里的microservice.yaml，后加载了test-classes中的microservice.yaml，最后加载了classes中的microservice.yaml，而最终生效的是classes中的microservice.yaml。这个要怎么解决？

**Comment by liubao68** [comment]
配置文件第一行加上 `servicecomb-config-order` 试试， 存在相同配置项时， 值大的会覆盖值小的配置文件。 详细参考前面发的文档链接。

**Comment by sunjinghan7331** [comment]
@liubao68 
在microservice.yaml配置文件第一行加上servicecomb-config-order后，成功达到了我的目的，感谢。
