### ISSUE TITLE
@RestControllerAdvice配置失效问题

### ISSUE THREAD

**Issue by Caixinyang** [apache/servicecomb-java-chassis#1587]
配置了如下全局异常捕捉：
	// 处理请求参数格式错误 @RequestParam上validate失败后抛出的异常是javax.validation.ConstraintViolationException
	@ExceptionHandler(ConstraintViolationException.class)
	@ResponseBody
	@ResponseStatus(HttpStatus.BAD_REQUEST)
	public ResponseEntity<String> ConstraintViolationExceptionHandler(ConstraintViolationException exception) {
		return ResponseEntity.status(HttpStatus.BAD_REQUEST)
				.body("error, class A");
	}
实际调接口返回：
{
    "message": "[ConstraintViolationImpl{interpolatedMessage='page should not less 1', propertyPath=getResponse1.page, rootBeanClass=class com.huaweicloud.app.manage.controller.AController$$EnhancerBySpringCGLIB$$38ac2b26, messageTemplate='page should not less 1'}]"
}

**Comment by liubao68** [comment]
看起来是和 spring boot 的功能混淆了。 可以先参考一下介绍
* [ java chassis SpringMVC的差异](https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/springmvc/#servicecombspring-mvc)
* [运行时差异](https://docs.servicecomb.io/java-chassis/zh_CN/using-java-chassis-in-spring-boot/introduction/)

**Comment by Caixinyang** [comment]
OK

**Comment by Caixinyang** [comment]
您好，我参考你提供的文档配置了ExceptionToProducerResponseConverter<ConstraintViolationException>捕捉到了@RequestParam异常。但是@RequestHeader异常不住不到，我尝试增加了ExceptionToProducerResponseConverter<InvocationException>，
ExceptionToProducerResponseConverter<Exception>
ExceptionToProducerResponseConverter<ServletRequestBindingException>
ExceptionToProducerResponseConverter<UnsatisfiedServletRequestParameterException>等
但是结果抓不到@RequestHeader的异常：
org.apache.servicecomb.swagger.invocation.exception.InvocationException: InvocationException: code=400;msg=CommonExceptionData [message=Parameter is not valid for operation [application-manage.IefAppTemplateController.getAppTemplateList]. Parameter is [X-Auth-Token]. Processor is [header].]

**Comment by Caixinyang** [comment]
您好，我参考你提供的文档配置了ExceptionToProducerResponseConverter捕捉到了@RequestParam异常。但是@RequestHeader异常不住不到，我尝试增加了对ServletRequestBindingException、UnsatisfiedServletRequestParameterException、Exception等异常的捕捉。
但是结果都抓不到@RequestHeader的异常：
org.apache.servicecomb.swagger.invocation.exception.InvocationException: InvocationException: code=400;msg=CommonExceptionData [message=Parameter is not valid for operation [application-manage.IefAppTemplateController.getAppTemplateList]. Parameter is [X-Auth-Token]. Processor is [header].]

**Comment by liubao68** [comment]
是否能捕获到，要看异常抛出的位置。 这个异常ExceptionToProducerResponseConverter是捕获不到的。 
目前java-chassis不能很好的由业务处理这类异常。
