### ISSUE TITLE
动态配置获取不到

### ISSUE THREAD

**Issue by jinsheng12** [apache/servicecomb-java-chassis#1589]
@value和ConfigUtil.getProperty()都获取不到动态配置，refreshMode: 1时没有错误提示，refreshMode: 2时：提示连不上30104端口。
18:40:54.830 [config-center-vert.x-eventloop-thread-0] ERROR org.apache.servicecomb.config.client.ConfigCenterClient: - watcher connect to config center https://192.168.0.26:30103 refresh port 30104 failed. Error message is [Connection refused: no further information: /192.168.0.26:30104]

**Comment by liubao68** [comment]
Please check your network configurations and make sure `192.168.0.26:30104` is reachable

**Comment by jinsheng12** [comment]
refreshMode设置为1和0都不能还获取到配置中心的配置

**Comment by jinsheng12** [comment]
environment: development 本地这个配置导致的
