### ISSUE TITLE
请教一下，当前CSE是否支持双通道？

### ISSUE THREAD

**Issue by w00285519** [apache/servicecomb-java-chassis#1591]
当前CSE是否支持双通道；比方说Server-Sent Events；

如果不支持，是否有CSE+双通道解决方案；希望各位大虾帮忙答疑一下

**Comment by liubao68** [comment]
java chassis 目前支持的是 `RPC`， 没有支持事件机制。 可以选择其他消息中间件及其对应的SDK。

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
