### ISSUE TITLE
微服务RPC调用时在HttpClientFilter 中如何处理请求中产生的异常？

### ISSUE THREAD

**Issue by Bluselye** [apache/servicecomb-java-chassis#1596]
在微服务RPC请求时，增加一个HttpClientFilter 做过滤器记录外部请求情况。
如果请求中发生异常，比如超时异常时，在过滤器中会进beforeSendRequest方法但是不会进afterReceiveResponse方法。此时应该如何处理才能满足需求？

**Comment by liubao68** [comment]
比较通用的做法可以实现一个[Handler](https://docs.servicecomb.io/java-chassis/zh_CN/references-handlers/intruduction/)，比如 error-handler, 然后配置在其他Handler的前面。 Handler里面可以从Invocation取到很多信息，如果没有的信息，比如HTTP协议里面的某些header，可以在HttpClientFilter里面setContext。

**Comment by Bluselye** [comment]
请问下这个Handler有没有对应的开发资料，提供一下,这个也是一个方法，或者有没有对应接口和配置，去重写Invocation实现？

**Comment by liubao68** [comment]
我的回复有链接

**Comment by Bluselye** [comment]
实践了一下，这样做不能在Invocation的LocalContext中传递消息，并且handler会在filter之前调用前执行，处理起来比较麻烦，有专门的设置ExceptionHandler处理么？

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
