### ISSUE TITLE
Is there a plan to support swagger 3.0?

### ISSUE THREAD

**Issue by HoyerIsAlexander** [apache/servicecomb-java-chassis#1597]
Is there a plan to support swagger 3.0，our service want to use the swagger file as the API document，but some definitions are not support，like the length of String etc.

**Comment by liubao68** [comment]
Do you use "contrast first" development mode? First write API's , and then use some tool to generate code.

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
