### ISSUE TITLE
使用HttpServerFilter拦截请求时无法获取body体内容

### ISSUE THREAD

**Issue by leonhart** [apache/servicecomb-java-chassis#1598]
sdk版本2.5.0。本地使用postman调用服务api，拦截到的httpServletRequestEX中bodyBuffer内容为空。如果放行到正常的代码逻辑里是正常的。其他人使用相同版本和写法就能正常获取
![local](https://user-images.githubusercontent.com/14150277/75406315-1fd9ad00-594b-11ea-88e1-bd512cfd1cf0.jpg)

**Comment by liubao68** [comment]
可以先看下 httpServletRequestEX 的具体实现类是哪一个， 不同的运行环境这个类的示例不一样， 行为也不一样。 getBodyBuffer 可能为空 。 如果运行于 Servlet 环境， 在实现 HttpServerFilter的时候，注意 'needCacheRequest' 需要返回 true。

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
