### ISSUE TITLE
上下文传递信息

### ISSUE THREAD

**Issue by xhanthow** [apache/servicecomb-java-chassis#1599]
调用链路：前端请求->边缘服务->A微服务，A服务收到请求后往context里写了一些信息，用的是`ContextUtils`，然后边缘服务接收到response，获取刚才A微服务中设置的值，确获取不到。正确的姿势是什么了？

**Comment by liubao68** [comment]
边缘服务从 Invocation 里面应该是可以取到的。 从边缘服务读取的代码是怎么样的，在哪个环节？

**Comment by xhanthow** [comment]
是在`onExecuteHttpServerFiltersFinish()`这个方法中读取的

**Comment by xhanthow** [comment]
读取和设置的方法如下：
```
InvocationContext context = ContextUtils.getInvocationContext();
Map<String, String> mapContext = context.getContext();
mapContext.get(key);
```
```
InvocationContext context = ContextUtils.getInvocationContext();
context.addContext(key, value);
```

**Comment by xhanthow** [comment]
正向的话是可以的，比如我在边缘服务上下文中写值，然后A微服务上下文中读取值，是正常的。但是反向的话就有问题了

**Comment by yhs0092** [comment]
`InvocationContext` 就是正向传递的，不会从服务端返回客户端

**Comment by xhanthow** [comment]
> `InvocationContext` 就是正向传递的，不会从服务端返回客户端

好的，明白了
