### ISSUE TITLE
ETCD升级到2.2.3时，使用旧的CA签发证书，server.cer和server.p12文件大小为0

### ISSUE THREAD

**Issue by mayf94** [apache/servicecomb-java-chassis#1601]
ETCD升级到2.2.3时，使用旧的CA签发证书，server.cer和server.p12文件大小为0，但新使用生成的CA就可以成功签发正常文件，keytool版本没有问题，不想更换CA的原因是：业务代码里使用的server.p12和trust.jks，若重新用新的CA签发需要更换掉，会影响现网升级部署，麻烦帮忙看下怎么解决，谢谢！
![image](https://user-images.githubusercontent.com/32881735/75534972-04a49580-5a50-11ea-9a3e-656424ac3b79.png)

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
