### ISSUE TITLE
cse本地schema加载

### ISSUE THREAD

**Issue by leland17** [apache/servicecomb-java-chassis#1605]

**Comment by leland17** [comment]
想问问，怎么加载我们本地定义的schema文件来定义第三方接口呢？

**Comment by yhs0092** [comment]
你说的“定义第三方接口”是指的[第三方调用](http://1v96us.coding-pages.com/docs/java-chassis/zh_CN/build-consumer/3rd-party-service-invoke/) 的功能吗？第三方调用的接口的契约是根据设置的接口类型自动生成的，不能加载本地手写的契约文件呢

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
