### ISSUE TITLE
ServiceComb在RPC调用时如果业务请求报错了怎么样才能拿到请求报错的InvocationContext ？

### ISSUE THREAD

**Issue by Bluselye** [apache/servicecomb-java-chassis#1610]
在RPC调用时发生了请求异常，此时异常在try-catch中捕获，
如果在当前想要拿到此次RPC请求的异常的InvocationContext ，该怎么取？有办法取吗？

**Comment by heyile** [comment]
可以.

```java
  public String sayHi(String name) {
    InvocationContext context = ContextUtils.getInvocationContext();
    context.setStatus(402);
    return "Hello " + name;
  }
```

**Comment by Bluselye** [comment]
这个试了下，获取到的是Service的不是作为Client的InvocationContext 
try{
       rpc.method
}catch(Exception e){
      InvocationContext context = ContextUtils.getInvocationContext();  // 这个获取的是作为Service的，而此时我想要获取的是这个RPC调用时（作为Client）时的InvocationContext 
}

**Comment by heyile** [comment]
能介绍一下你的业务场景吗? 为啥要 Client 的 InvocationContext

**Comment by Bluselye** [comment]
当RPC请求产生异常报错的时候，该报错信息会抛到业务层面上来，如果能在catch位置拿到作为Client时的InvocationContext，就能从里面拿到我设置的变量进行下一步的业务处理。或者这样实现不是很合理。我当前需要做一个记录服务外部调用的功能，想通过ServiceComb框架做一个通用点的实现。不知道有没有更简单的实现？

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
