### ISSUE TITLE
bmi/webapp 这里sample如何启动，webroot是不是需要配置static的绝对路径？

### ISSUE THREAD

**Issue by zhangbeiyuan-hw** [apache/servicecomb-java-chassis#1612]
配置如下，这里是否要配置绝对路径，能否按照相对路径配置到resuource/static下？windows系统下怎么配置？
# This is web root for windows server, change this path according to where you put your source code
gateway:
  webroot: /code/servicecomb-samples/java-chassis-samples/bmi/webapp/src/main/resources/static

2020-03-03 17:08:41.143 ERROR 9760 --- [ntloop-thread-5] o.a.s.c.rest.locator.OperationLocator    : locate path failed, status:Not Found, http method:GET, path:/index.html/, microserviceName:gateway

**Comment by liubao68** [comment]
[BMI 例子](https://github.com/apache/servicecomb-samples/tree/master/java-chassis-samples/bmi) 里面有配置。 就是你发的：

```
gateway:
    webroot: /code/servicecomb-samples/java-chassis-samples/bmi/webapp/src/main/resources/static
```

这个是windows配置， linux配置的话，只能用相对路径

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
