### ISSUE TITLE
ServiceComb 进行RPC调用时RestClientInvocation可以支持自已实现么？

### ISSUE THREAD

**Issue by Bluselye** [apache/servicecomb-java-chassis#1616]
ServiceComb 进行RPC调用时会通过RestClientInvocation进行转发，这个类支持自定义扩展么？如果可以该如何配置？

**Comment by heyile** [comment]
暂时没有把这个开放出来.

**Comment by heyile** [comment]
你的使用场景是啥?

**Comment by Bluselye** [comment]
做个记录outcall.log的功能，想从框架里面做实现，目前来看不好实现
https://github.com/apache/servicecomb-java-chassis/issues/1611

**Comment by heyile** [comment]
海石已经回了, 可以在 #1611 中讨论

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
