### ISSUE TITLE
cse是否支持schemaId或mappath粒度的契约注册控制

### ISSUE THREAD

**Issue by FoxCATT** [apache/servicecomb-java-chassis#1619]
## 问题场景
同一个微服务区分功能部署在两个集群，契约相同且注册到同一注册中心。但由于两个集群中环境不同，部分接口只能在其中一个集群中提供正确的服务，但注册中心有两个集群全部实例的信息，导致其他微服务在调用这个微服务的接口时会得不到正确的结果。
## 问题
一个具有众多接口的微服务在不拆分微服务的方式下能否通过一些配置使一个集群中的微服务只能将部分契约注册到注册中心中。即**是否可以通过配置契约来完成微服务功能的拆分**。

**Comment by heyile** [comment]
@liubao68 .

**Comment by yhs0092** [comment]
对于ServiceComb体系下的微服务而言，一个微服务的版本确定时，它的接口也是确定的。所以同一个微服务同一个版本的实例分两拨，一拨注册这些接口契约，另一拨注册那些接口契约，这种事情在ServiceComb的概念下是说不通的。

最终要怎么解决问题取决于你是怎么看待这两个集群中的服务的。如果因为环境不同，它们就是提供不同的功能的，那么可能改一下微服务名字，保证两个集群里的实例分属于不同名的两个微服务可能更好一些。让客户端分别调用。

如果这种不一致只是暂时的，你也可以考虑使用Java-Chassis的负载均衡模块自带的[根据实例属性进行路由转发](https://docs.servicecomb.io/java-chassis/zh_CN/references-handlers/loadbalance/)功能。
