### ISSUE TITLE
通过edge访问返回response content-type application/json; charset=utf-8 is not supported

### ISSUE THREAD

**Issue by xhanthow** [apache/servicecomb-java-chassis#1624]
通过edge访问一个接口，返回`{
    "message": "method POST, path xxx statusCode 200, reasonPhrase OK, response content-type application/json; charset=utf-8 is not supported"
}`，返回码为400，如果直接访问返回`{
    "result": {
        "code": 200,
        "message": "xxx"
    }
}`

**Comment by xhanthow** [comment]
经过观察发现，契约定义的返回为void。。这种情况有什么好的方法避免么
![image](https://user-images.githubusercontent.com/7291995/76079181-1ac9cd00-5fdf-11ea-9e10-6d3ab7329ecd.png)

**Comment by heyile** [comment]
给一个demo吧. 看的不是很明白.

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.

**Comment by thenumb** [comment]
这个问题应该怎么解决
