### ISSUE TITLE
servicecomb的yaml配置文件，配置项无法通过集成Jasypt方式进行加解密

### ISSUE THREAD

**Issue by zouwenxmu** [apache/servicecomb-java-chassis#1631]
项目中jasypt-spring-boot-starter可以对spring的配置项进行加解密处理，有没有办法使用jasypt处理microservices.yaml的配置项，求助

**Comment by liubao68** [comment]
jasypt应该可以用。 如果使用Spring Boot的话。 但是spring boot不会处理microservice.yaml. 使用Spring Boot的场景， 可以将所有配置项放到application.yml。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
