### ISSUE TITLE
CSE如何在microservice.yaml里面配置ipv6地址

### ISSUE THREAD

**Issue by zmystc** [apache/servicecomb-java-chassis#1634]
当前在microservice.yaml里面配置ipv6地址会启动报错
版本号如下
![image](https://user-images.githubusercontent.com/62241237/76747152-a992d280-67b3-11ea-8a91-129b35ec352e.png)

配置格式1：
![image](https://user-images.githubusercontent.com/62241237/76746492-8d426600-67b2-11ea-9ad1-d5c2b68f233c.png)
![image](https://user-images.githubusercontent.com/62241237/76746505-95020a80-67b2-11ea-8419-206d0745db34.png)

配置格式2：
![image](https://user-images.githubusercontent.com/62241237/76746541-a3e8bd00-67b2-11ea-9c8b-78ae2935d48b.png)
![image](https://user-images.githubusercontent.com/62241237/76746640-ced31100-67b2-11ea-9506-f6dffc101746.png)

**Comment by heyile** [comment]
用单引号包起来试下.

**Comment by heyile** [comment]
这样试下
```yaml

cse:
  rest:
     address: '[xxx]:11000'
```

**Comment by zmystc** [comment]
已解决
