### ISSUE TITLE
rest.addres:0.0.0.0，有改为自动获取虚机ip的方法

### ISSUE THREAD

**Issue by walker-bichen** [apache/servicecomb-java-chassis#1637]
由于公司信息安全要求，绑定地址不能为0.0.0.0；
有方法改为listen：
cse:
   listen:eth0:8989

但是我的程序可以启动注册，但是访问不了，不知道这个rest改为listen有没有什么现在，或者其他方法
多谢！

**Comment by liubao68** [comment]
可以看看[这里的说明](https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/listen-address-and-publish-address/)， 目前只能支持配置实际IP地址。 监听地址不支持使用网卡名称。

**Comment by heyile** [comment]
版本号 和  你的 microservice.yaml 给下

**Comment by walker-dead-cave** [comment]
多谢，知道结论了，建议后续可以考虑加上：发布地址都可以，监听地址也支持，达到统一性

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
