### ISSUE TITLE
SpringCloud项目改造为Springboot项目时，generate operation swagger failed

### ISSUE THREAD

**Issue by Fang57** [apache/servicecomb-java-chassis#1639]
在文档上看到接口参数不支持HttpServletResponse ，请问异常类Errors也不支持吗

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.springframework.validation.Errors;

@RequestMapping(value = "/demo/v1/hello", produces = "application/json;charset=UTF-8", method = RequestMethod.POST)
    public String queryConfig(@PathVariable(value = "id") Integer id,
                                @Valid @RequestBody NodeInfo nodeInfo,
                                Errors errors,
                                HttpServletRequest request,
                                HttpServletResponse response) {
        return HttpStatus.OK.toString();
    }

**Comment by liubao68** [comment]
能否打开Errors类详细看下， [类型约束参考](https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/interface-constraints/)

**Comment by heyile** [comment]
把问题场景和背景说下吧. 为啥要用Errors. 然后给一个可用的 demo

**Comment by Fang57** [comment]
接口改造时发现有有接口用到了Errors类进行异常处理，所以想确认下
