### ISSUE TITLE
【Feature Request】Support @JsonView

### ISSUE THREAD

**Issue by Nick-The-Uncharted** [apache/servicecomb-java-chassis#1644]
In our project we have many dataObjects, they came from kafka (with multiple different format), saved into redis and db and returned  in rest api in more than one flavors. To properly handle them we have a bunch of classes like `PersonEntity/Person/PersonDTO/PersonDTOWithName`, all of them are terribly similiar which smells really bad. We need a more efficent and cleaner way to express the intention to  (de)serialize same json with different property or alias.

Some modification in `org.apache.servicecomb.common.rest.codec.param.BodyProcessorCreator.BodyProcessor#getValue` and `org.apache.servicecomb.common.rest.codec.produce.ProduceJsonProcessor#doEncodeResponse` shall be enough.

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
