### ISSUE TITLE
HttpServerFilter过滤器怎么使用@Resource注入对象

### ISSUE THREAD

**Issue by Fang57** [apache/servicecomb-java-chassis#1646]
public class CustomizedFilter implements HttpServerFilter {
    @Resource
    private EncryptkeyInfo enKeyInfo;
    @Resource
    private AuthUtil authUtil;
    @Override
    public Response afterReceiveRequest(Invocation invocation, HttpServletRequestEx requestEx) {
        return null;
    }
    @Override
    public void beforeSendResponse(Invocation invocation, HttpServletResponseEx responseEx) {
    }
}

**Comment by heyile** [comment]
暂时不支持

**Comment by liubao68** [comment]
HttpServerFilter 不是 bean， 因此不能注入 spring bean 对象。需要注入 spring bean 对象， 得采用 spring 的一些常用技巧， 在非 bean里面获取bean。 

比如可以自定义一个 bean:

```
@Component("holder")
public class Holder｛
@resource
private EncryptkeyInfo enKeyInfo;
@resource
private AuthUtil authUtil;
｝
```

然后在 Filter里面通过 BeanUtils 获取 :

```
Holder bean = BeanUtils.getBean("holder");
```

**Comment by zhoudamin** [comment]
> HttpServerFilter 不是 bean， 因此不能注入 spring bean 对象。需要注入 spring bean 对象， 得采用 spring 的一些常用技巧， 在非 bean里面获取bean。
> 
> 比如可以自定义一个 bean:
> 
> ```
> @Component("holder")
> public class Holder｛
> @resource
> private EncryptkeyInfo enKeyInfo;
> @resource
> private AuthUtil authUtil;
> ｝
> ```
> 
> 然后在 Filter里面通过 BeanUtils 获取 :
> 
> ```
> Holder bean = BeanUtils.getBean("holder");
> ```
-----------------------------------------
1、Holder 加个 Data 的lombok注解
2、Holder bean = BeanUtils.getBean("holder");
bean.getEncryptkeyInfo.getxxx
