### ISSUE TITLE
TLS传输明文配置私钥口令

### ISSUE THREAD

**Issue by chenhongjin** [apache/servicecomb-java-chassis#1650]
microservice.yaml文件中启用TLS通信的配置
ssl.protocols: TLSv1.2
ssl.authPeer: true
ssl.checkCN.host: true

#########certificates config
ssl.trustStore: trust.jks
ssl.trustStoreType: JKS
ssl.trustStoreValue: Changeme_123
ssl.keyStore: server.p12
ssl.keyStoreType: PKCS12
ssl.keyStoreValue: Changeme_123
ssl.crl: revoke.crl
ssl.sslCustomClass: org.apache.servicecomb.demo.DemoSSLCustom

明文配置的私钥口令是Changeme_123,导致私钥泄露风险极大

**Comment by liubao68** [comment]
你可以自定义 `ssl.sslCustomClass` ， 然后提供加密解密措施。

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
