### ISSUE TITLE
RPC风格，微服务消费端抛异常，麻烦帮忙看看，多谢！

### ISSUE THREAD

**Issue by liukuancn** [apache/servicecomb-java-chassis#1654]
消费端抛异常，没有走到服务端，异常如下。
Method threw 'java.lang.IllegalStateException' exception. Cannot evaluate com.sun.proxy.$Proxy55.toString()

之前调通过，接口没有修改过，只是更新了一些消息类定义。
用的本地服务中心，看服务中心里2个服务都正常注册了。

客户端版本号：java-chassis-core-1.2.0.B007r7

**Comment by SD-WG** [comment]
这个问题是怎么解决的呢？最近用反射的时候也遇到了这个问题。

**Comment by liubao68** [comment]
这个只在调试的时候出现， 因为观察的对象是一个远程对象，没有 toString 方法。 对于业务是没影响的。
