### ISSUE TITLE
在A服务中引入了inspector，在B服务中能够通过cse调用获取到A服务的接口文档

### ISSUE THREAD

**Issue by sunjinghan7331** [apache/servicecomb-java-chassis#1655]
如题，在A服务中引入了inspector，在B服务中能够通过cse调用获取到A服务的swagger形式的接口文档？

**Comment by liubao68** [comment]
理论上可以的， 参考[inspector说明](https://docs.servicecomb.io/java-chassis/zh_CN/featured-topics/using-inspector/)， 注意 inspector 功能不建议暴露给用户直接使用， 不能够将业务功能建立在依赖这个功能之上，只作为不重要的维护功能。

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
