### ISSUE TITLE
CSEJavaSDK集成shiro 报错，

### ISSUE THREAD

**Issue by zhangming2019** [apache/servicecomb-java-chassis#1666]
![image](https://user-images.githubusercontent.com/19624999/77648464-25a2cc80-6fa3-11ea-846b-1f846749f0d9.png)
rg.apache.shiro.UnavailableSecurityManagerException: No SecurityManager accessible to the calling code, either bound to the org.apache.shiro.util.ThreadContext or as a vm static singleton.  This is an invalid application configuration.
但是相同的代码只用springboot是可以的

**Comment by zhangming2019** [comment]
看了你们给的demo 绕过了ShiroFilterFactoryBean，直接写的HttpServerFilter  有什么方案可以使用ShiroFilterFactoryBean

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
