### ISSUE TITLE
Load balancer does not have available server for client

### ISSUE THREAD

**Issue by xhanthow** [apache/servicecomb-java-chassis#1671]
![image](https://user-images.githubusercontent.com/7291995/77737339-bd0e2b00-7048-11ea-869b-c4bc4688a963.png)
请问下这是什么原因导致的了

**Comment by heyile** [comment]
没有可用的Server 端了

**Comment by ArlenShawChina** [comment]
![server no found](https://user-images.githubusercontent.com/27500866/77884088-fd62e880-7296-11ea-9343-1e6af6ddecb9.png)
服务实际注册上了，在Dash面板上也有，浏览器也可以访问。

**Comment by heyile** [comment]
给一个复现问题的demo吧。 带上SDK版本号啥的

**Comment by liubao68** [comment]
可以简单看下日志排查下： 1. 搜索下 find instance 关键字， 看看 consumer 是否查询到 provider 的实例列表； 2. 如果没有就检查下是不是应用 ID ，微服务名称， environment等写错误了。 如果有，可以调试下代码， 看看实例是否被某一个 filter 过滤掉了，不使用。

**Comment by heyile** [comment]
> 可以简单看下日志排查下： 1. 搜索下 find instance 关键字， 看看 consumer 是否查询到 provider 的实例列表； 2. 如果没有就检查下是不是应用 ID ，微服务名称， environment等写错误了。 如果有，可以调试下代码， 看看实例是否被某一个 filter 过滤掉了，不使用。

确定了，它使用不是咱们的版本，consumer 去查注册的provider的时候， 字段endpoints 丢失了

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.

**Comment by sofkyle** [comment]
> 

能进一步解释下吗，“它使用不是咱们的版本”，指的是啥版本？我遇到了同样的问题，invocation里面的endpoint也是空

**Comment by sofkyle** [comment]
> > 可以简单看下日志排查下： 1. 搜索下 find instance 关键字， 看看 consumer 是否查询到 provider 的实例列表； 2. 如果没有就检查下是不是应用 ID ，微服务名称， environment等写错误了。 如果有，可以调试下代码， 看看实例是否被某一个 filter 过滤掉了，不使用。
> 
> 确定了，它使用不是咱们的版本，consumer 去查注册的provider的时候， 字段endpoints 丢失了

能进一步解释下吗，“它使用不是咱们的版本”，指的是啥版本？我遇到了同样的问题，invocation里面的endpoint也是空

**Comment by liubao68** [comment]
@sofkyle 可以日志里面查询下 find instance 关键字， 看看是否正确的从服务端查询到实例列表。 也可以在注册中心先看下服务端的实例信息，包括地址信息是否正确。
