### ISSUE TITLE
ServiceComb熔断配置求助

### ISSUE THREAD

**Issue by willard-kali** [apache/servicecomb-java-chassis#1681]
针对servicecomb的熔断配置：
![image](https://user-images.githubusercontent.com/10024569/77916657-fa361f80-72cb-11ea-90ef-b7c8def7ff3f.png)

帮忙指正如下理解是否有误：
1.Provider方处理接口超过60s或者同1s内的请求数超过10个，会触发熔断。
2.然后限制30s内，再过来的所有请求都会直接返回异常。
3.配置没有指定具体微服务，是针对所有的微服务生效，只要有1个接口出现问题，其他所有的接口也都不能用了。
4.circuitBreaker.requestVolumeThreshold参数和isolation.maxConcurrentRequests参数两者如何理解？看官方说明不太清楚。

已参考官方文档：https://www.bookstack.cn/read/ApacheServiceCombJavaChassis/20.md

**Comment by liubao68** [comment]
1. 当前并发处理请求数超过10个。没有1s内的限制。
2. sleepWindowInMilliseconds 是指熔断的时间窗。 是你理解的意思
3. 是的
4. 在发生熔断前的请求个数必须超过requestVolumeThreshold，否则不会熔断。 maxConcurrentRequests 参考问题1. 

[官网文档链接](https://docs.servicecomb.io/java-chassis/zh_CN/references-handlers/bizkeeper/) 你发的文档比较旧，估计是第三方爬虫生成的， 并没有发布过这个文档。

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
