### ISSUE TITLE
边缘服务偶发性Connection closed，影响现网运行。

### ISSUE THREAD

**Issue by mf1632015** [apache/servicecomb-java-chassis#1685]
偶发性的问题，一个请求发送到边缘服务返回490，边缘服务抛出这个异常。已经发生两次了，上一次发生是几天前。
这个问题的原因是什么，是不是网络问题导致的？如果是，有没有解决方案，比如重试等。
异常信息：
![image](https://user-images.githubusercontent.com/29472151/78130552-182a8e00-744c-11ea-9bc5-76e8d6ea83ea.png)

**Comment by liubao68** [comment]
有可能是网络原因，也有可能是其他原因，比如性能原因。建议做一些性能和压力测试，看看情况。观察下出现异常时候的网络发送情况，连接断开情况等信息。 

参考材料：[打开性能监控分析](https://docs.servicecomb.io/java-chassis/zh_CN/general-development/metrics/), [重试和隔离](https://docs.servicecomb.io/java-chassis/zh_CN/references-handlers/loadbalance/)

**Comment by mf1632015** [comment]
当时并发并不高，也就只有二三十的并发量。而且就失败了这一次，后续就没有失败了

**Comment by mf1632015** [comment]
> 有可能是网络原因，也有可能是其他原因，比如性能原因。建议做一些性能和压力测试，看看情况。观察下出现异常时候的网络发送情况，连接断开情况等信息。
> 
> 参考材料：[打开性能监控分析](https://docs.servicecomb.io/java-chassis/zh_CN/general-development/metrics/), [重试和隔离](https://docs.servicecomb.io/java-chassis/zh_CN/references-handlers/loadbalance/)

当时并发并不高，也就只有二三十的并发量。而且就失败了这一次，后续就没有失败了

**Comment by 907474646** [comment]
Hi, did you hava  resolved  this question?

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
