### ISSUE TITLE
Rest的TLS协商，消费者不配置证书也能通过

### ISSUE THREAD

**Issue by fu-hui** [apache/servicecomb-java-chassis#1694]
生产者A，，开启Rest 的TLS端口，单向认证，POST Man等测试，tls已经确保开启
消费者B  请求生产者A ：

1. 消费者B未添加对应的根证书，能够TLS请求通生产者A （是不是默认放通对服务器证书的校验 ?）
2. 消费者B按要求配置证书，只要配置了 ssl.checkCN.host:false，即使证书配置错误，也能通（是不是只有将ssl.checkCN.host配置成true，才会进行证书验证 ?）

**Comment by liubao68** [comment]
ssl.authPeer 需要设置为 true

**Comment by fu-hui** [comment]
authPeer作用应该是： 是否开启双向认证吧

作为服务器：如果将ssl.authPeer 需要设置为 true，意思是说，服务器也需要认证客户端证书
作为消费者：将 ssl.authPeer 需要设置为 true，只认证服务器证书就好了么

**Comment by liubao68** [comment]
> authPeer作用应该是： 是否开启双向认证吧
> 
> 作为服务器：如果将ssl.authPeer 需要设置为 true，意思是说，服务器也需要认证客户端证书
> 作为消费者：将 ssl.authPeer 需要设置为 true，只认证服务器证书就好了么

是的。 双向认证的情况下， consumer & provider 都需要将 authPeer 设置为 true。

**Comment by fu-hui** [comment]
我这是需要单向认证呀，服务器认证客户端

目前发现，服务器单向认证客户端的时候, 没有配置根证书，也通过了

**Comment by fu-hui** [comment]
我这是需要单向认证呀，客户端认证服务器

目前发现，客户端单向认证服务器的时候, 没有配置根证书，也通过了

**Comment by liubao68** [comment]
ssl.rest.consumer.authPeer=false, check [docs](http://liubao68.gitee.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/security/tls/)

**Comment by fu-hui** [comment]
好像明白了

单向认证时，服务器 authPeer=false，客户端 authPeer=true 
双向认证时，服务器 authPeer=true ，客户端 authPeer=true

**Comment by fu-hui** [comment]
好像明白了

单向认证时，服务器 authPeer=false，客户端 authPeer=true
双向认证时，服务器 authPeer=true ，客户端 authPeer=true

对否？

**Comment by liubao68** [comment]
是的

**Comment by fu-hui** [comment]
好滴，谢谢
