### ISSUE TITLE
在microservice.yaml里定义了0.0.0.0:8088?sslEnabled=false&protocol=http2，访问还是HTTP1.1

### ISSUE THREAD

**Issue by xioyaozi** [apache/servicecomb-java-chassis#1696]
在microservice.yaml里定义了0.0.0.0:8088?sslEnabled=false&protocol=http2，访问还是HTTP1.1，而且每次请求都会重新建立连接，没有复用原来的连接

**Comment by heyile** [comment]
给一个可复现问题的demo吧. 本地测试没复现

**Comment by xioyaozi** [comment]
microservice.yaml定义如下：
servicecomb:
  service:
    registry:
      address: http://127.0.0.1:****
  rest:
    address: 0.0.0.0:8088?sslEnabled=false&protocol=http2
    parameter:
      query:
        ignoreRequiredCheck: true
    server:
      thread-count: 4
      http2:
        concurrentStreams: 6000
        useAlpnEnabled: true
      verticle-count: 4
1、使用浏览器访问http://127.0.0.1:8088/***，通过抓包看的话，是http1.1，每次请求端口号都会改变。
2、如果把sslEnabled=true的话，通过浏览器访问https://127.0.0.1:8088/***的话，这个时候端口不会改变。
3、但是我在微服务内部用restTemplate.发送https请求https://127.0.0.1:8088/***，通过抓包看，端口号又一直在变

**Comment by heyile** [comment]
通过浏览器 会是 http1.1. 只有用consumer 端走cse 去调用, cse 会根据远端 endpoint 做适配.

详情可参考 RestTransportClient#send

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
