### ISSUE TITLE
微服务开启了公钥认证，但是希望对前端访问免认证，一般建议用什么方案？谢谢！

### ISSUE THREAD

**Issue by liukuancn** [apache/servicecomb-java-chassis#1698]
如果用白名单的话，propertyName、rule应该怎么配？谢谢！
white:
        list02:
          category: property
          propertyName: serviceName
          rule: cust*

**Comment by liubao68** [comment]
可以参考文档 [公钥认证](http://liubao68.gitee.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/references-handlers/publickey/) 。 可以查看 ProviderAuthHandler 的代码了解详细情况。
