### ISSUE TITLE
[WIP]VersionCompareUtil可以优化掉，复用serviceregistry模块里的Version类

### ISSUE THREAD

**Issue by Matrix0xCC** [apache/servicecomb-java-chassis#1707]
https://github.com/apache/servicecomb-java-chassis/blob/10d45c6f88de8b13b066d4db32be1eb9483803f0/handlers/handler-router/src/main/java/org/apache/servicecomb/router/util/VersionCompareUtil.java#L31

**Comment by liubao68** [comment]
Thanks for your suggestion, fixed in this [PR](https://github.com/apache/servicecomb-java-chassis/pull/1728)
