### ISSUE TITLE
客户端采用InvokeUtil调用服务接口时，是否能通过目标服务的schemeId获取到microserviceName?

### ISSUE THREAD

**Issue by jerome2018** [apache/servicecomb-java-chassis#1716]
在RPC开发模式下，微服务之间相互调用时，客户端采用InvokeUtil调用服务接口时，是否能通过目标服务的schemeId获取到microserviceName?

**Comment by liubao68** [comment]
不可以的。 不同的微服务允许一样的 schemaID。 在不知道微服务名称的情况下， 可以考虑使用 RestTemplate 访问。

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
