### ISSUE TITLE
使用zuul做边缘服务，与后端服务通信是否支持RSA认证方式？

### ISSUE THREAD

**Issue by zouwenxmu** [apache/servicecomb-java-chassis#1717]
在zuul上面配置
`handler:
    chain:
      Consumer:
        default: loadbalance,auth-consumer`
后端服务配置
`handler:
    chain:
      Provider:
        default: auth-provider`
从zuul路由到后端服务的请求响应为401

**Comment by liubao68** [comment]
zuul的请求转发不会走 java-chassiss 的处理链，完全是由zuul自己实现的逻辑。 配置项 `handler: chain: Consumer: default: loadbalance,auth-consumer` 不会有任何效果。 可以考虑 edge service， 新版本提供了很丰富的路由功能，包括 [第三方非 java-chassis 的转发](https://docs.servicecomb.io/java-chassis/zh_CN/featured-topics/features/http-dispatcher/)。

**Comment by zouwenxmu** [comment]
> zuul的请求转发不会走 java-chassiss 的处理链，完全是由zuul自己实现的逻辑。 配置项 `handler: chain: Consumer: default: loadbalance,auth-consumer` 不会有任何效果。 可以考虑 edge service， 新版本提供了很丰富的路由功能，包括 [第三方非 java-chassis 的转发](https://docs.servicecomb.io/java-chassis/zh_CN/featured-topics/features/http-dispatcher/)。

edge service上次问过不支持外置tomcat部署，不支持servlet filter，存量系统切换不了。T-T

**Comment by zouwenxmu** [comment]
写一个PreFilter，在CSE_CONTEXT注入token就能实现与后端服务的RSA认证，O(∩_∩)O
