### ISSUE TITLE
CSE适配批处理

### ISSUE THREAD

**Issue by hongfeihuangseu** [apache/servicecomb-java-chassis#1719]
存在A服务和B服务，B服务有一个Batch批处理接口，Batch接口收到A服务的请求，请求body里包含了多个子请求，这些子请求是用来请求B服务其他的方法的，Batch接口把这些子请求一个个解析出来，请问怎么才能将这些子请求一一调用到这些B服务对应的方法，获取正确的响应呢
（注：子请求内容有有url：/databases/1091096/types/Files/records，header，body）

**Comment by liubao68** [comment]
这个场景要求 B 不知道任何 A 的接口信息， 只知道 HTTP 的 header, body 等信息， 类似只能通过 HttpClient 请求 B 服务。 目前 java-chassis 的里面没提供直接面向 HTTP 的 client 接口。 不过也有其他解决方法的，比如查询到目标服务的地址， 然后使用第三方的 httpclient 调用对方接口。 这里[有个例子演示了如何查询地址](https://docs.servicecomb.io/java-chassis/zh_CN/general-development/context/)

**Comment by hongfeihuangseu** [comment]
A服务的请求可以正常到达B服务，并且能够调用到B服务的Batch接口。不需要httpclient

**Comment by liubao68** [comment]
按照这么说，就不太明白问题点在哪儿了。可能需要描述下需要 java-chassis 具体解决问题。

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
