### ISSUE TITLE
CSE支持本地调用模式吗

### ISSUE THREAD

**Issue by hongfeihuangseu** [apache/servicecomb-java-chassis#1720]
当一个应用既是一个服务的提供者，同时也是这个服务的消费者的时候，可以直接对本机提供的服务发起本地调用，这个CSE支持吗

**Comment by liubao68** [comment]
为什么不考虑： getBean("controller").invokeSomeMethod()? , controller 实现一个接口即可。

**Comment by zhufeizzz** [comment]
@liubao68 我们也有类似问题，本地直接调用会错过CSE的Handler，导致逻辑不一致

**Comment by liubao68** [comment]
> @liubao68 我们也有类似问题，本地直接调用会错过CSE的Handler，导致逻辑不一致

那你们是期望本地调用经过网络处理，还是不经过网络处理？不经过网络只需要执行 Handler ？

**Comment by zhufeizzz** [comment]
@liubao68 想本地调用不走网络（直接反射），但是要执行Handler
我们是做一个在线编排开发平台，类似SalesForce和Mendix，服务分为两种：
1、静态服务，通过标准CSE的方式开发出来的。
2、动态服务，在线编排开发出的服务，底层用统一的CSE服务接口封装。动态调用其他静态和动态服务，所以经常会出现微服务内部的CSE调用。

**Comment by liubao68** [comment]
或许可以实现一个简单的负载均衡策略，将调用本服务的接口的 endpoint 设置为 localhost

**Comment by liubao68** [comment]
参考: https://docs.servicecomb.io/java-chassis/zh_CN/general-development/context/

调用的时候，指定 Endpoint 为 localhost 即可。 

```
InvocationContext invocationContext = new InvocationContext();
    invocationContext.addLocalContext(LoadbalanceHandler.SERVICECOMB_SERVER_ENDPOINT, parseEndpoint(endpoint));
    Date date = new Date();
    TestMgr.check(date.getTime(), dateTimeSchemaWithContextInf.getDate(invocationContext, date).getTime());
```
