### ISSUE TITLE
微服务业务代码怎么获取SwaggerProducerOperation 的信息

### ISSUE THREAD

**Issue by hongfeihuangseu** [apache/servicecomb-java-chassis#1724]
public class SwaggerProducerOperation {
  private static final Logger LOGGER = LoggerFactory.getLogger(SwaggerProducerOperation.class);

  private String name;

  // 因为存在aop场景，所以，producerClass不一定等于producerInstance.getClass()
  private Class<?> producerClass;

  private Object producerInstance;

  private Method producerMethod;

  private Method swaggerMethod;

  private ProducerArgumentsMapper argumentsMapper;

  private ProducerResponseMapper responseMapper;

  private List<ProducerInvokeExtension> producerInvokeExtenstionList =
      SPIServiceUtils.getSortedService(ProducerInvokeExtension.class);

请问在微服务里面怎么获取SwaggerProducerOperation 的信息，以便得到producerMethod和producerInstance的信息

**Comment by liubao68** [comment]
Invocation.getOperationMeta.getSwaggerProducerOperation

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
