### ISSUE TITLE
参数类型错误不能走自定义的ExceptionToProducerResponseConverter

### ISSUE THREAD

**Issue by Nick-The-Uncharted** [apache/servicecomb-java-chassis#1731]
本地暂时规避方案：
 覆盖了 org.apache.servicecomb.common.rest.filter.inner.ServerRestArgsFilter
catch了 `org.apache.servicecomb.common.rest.codec.RestCodec#restToArgs` 抛出的异常 然后`return processException(invocation, e);`
```
    protected Response processException(SwaggerInvocation invocation, Throwable e) {
        if (e instanceof InvocationTargetException) {
            e = ((InvocationTargetException) e).getTargetException();
        }

        return ExceptionFactory.convertExceptionToResponse(invocation, e);
    }
```

**Comment by liubao68** [comment]
这个被设计为捕获业务的异常，最新代码做了少量的优化。 ServerFilter和Handler的异常目前没处理， 这个值得讨论下。

**Comment by Nick-The-Uncharted** [comment]
@liubao68 主要是如果是参数范围不合理可以正常转换，类型错误不可以，需要统一~或者这类异常也提供一个converter

**Comment by liubao68** [comment]
能简单描述下你的测试用例吗？比如服务端定义，测试的数据。

**Comment by Nick-The-Uncharted** [comment]
```
    @GetMapping("/test")
    public long test(@RequestParam long id) {
        return id;
    }
```
curl host:port/test?id=sss 就会报错了~

**Comment by liubao68** [comment]
目前ServerFilter抛出的异常还没有统一拦截的机制，后续版本会归一化 ServerFilter和Handler， 这样异常处理就简单很多。 

针对这个问题，当前可以自定义一个 HttpServerFilter， 实现
`default void beforeSendResponse(Invocation invocation, HttpServletResponseEx responseEx)`
方法, 将 response 里面的异常做一个处理也是可以的。

**Comment by zjlin1984** [comment]
HttpServerFilter抛出的异常，要如何捕获？

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
