### ISSUE TITLE
怎么从nethod.invoke结果里获取status，headers，body

### ISSUE THREAD

**Issue by hongfeihuangseu** [apache/servicecomb-java-chassis#1732]
Object result = method.invoke(producerInstance, args);

怎么从result 里获取status，headers，body

**Comment by liubao68** [comment]
或许可以参考下这个 PR 的例子： https://github.com/apache/servicecomb-java-chassis/pull/1667/files

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
