### ISSUE TITLE
microservice.yaml配置项集中到一个conf类中

### ISSUE THREAD

**Issue by shijinkui** [apache/servicecomb-java-chassis#1738]
microsservice.yaml的配置项散落在各处，需要集中到一起，加上注释和文档

**Comment by liubao68** [comment]
可以参考 : https://docs.servicecomb.io/java-chassis/zh_CN/config/general-config/
microservice.yaml也是支持公共配置的，其他微服务只配置差异部分。 使用 `servicecomb-config-order` 控制配置项的优先级。 扩展使用集中的配置中心管理所有配置。

**Comment by shijinkui** [comment]
@liubao68 两个问题：1）ful-conf文档需要的，每个kv的用途；2）ful-conf在工程里集中维护

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
