### ISSUE TITLE
新出CommonHttpEdgeDispatcher是否还支持filter和handler

### ISSUE THREAD

**Issue by NoComments** [apache/servicecomb-java-chassis#1755]
如果不支持的话，后端服务如果使用非servicecomb开发，也想使用edge，有没有好的解决办法，求大神指教

**Comment by liubao68** [comment]
可以参考： https://docs.servicecomb.io/java-chassis/zh_CN/featured-topics/features/http-dispatcher/  这里的描述。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
