### ISSUE TITLE
服务无法注册。

### ISSUE THREAD

**Issue by myVictor** [apache/servicecomb-java-chassis#1756]
注册中心在1.2.0没问题，换成1.3.0就注册不了了。

服务日志：
2020-05-18  11:03:27.945 [Service Center Task [java.util.concurrent.ThreadPoolExecutor$Worker@5869f15f[State = -1, empty queue][58]]] ERROR org.apache.servicecomb.serviceregistry.task.MicroserviceRegisterTask - Registry microservice failed. appId=[cxisoft], name=[tkcust], version=[1.0.0], env=[development]

抓包数据：

HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=UTF-8
Server: SERVICECENTER/1.3.0
Vary: Accept-Encoding
Vary: Origin
X-Response-Status: 400
X-Schema-Summary: 
Date: Mon, 18 May 2020 02:29:44 GMT
Content-Length: 129

{"errorCode":"400012","errorMessage":"Micro-service does not exist","detail":"development/cxisoft/tkcust/1.0.0 does not exist."}
HTTP/1.1 400 Bad Request
Connection: close
Content-Type: application/json; charset=UTF-8
Server: SERVICECENTER/1.3.0
Vary: Accept-Encoding
Vary: Origin
X-Response-Status: 400
Date: Mon, 18 May 2020 02:29:44 GMT
Content-Length: 101

{"errorCode":"400001","errorMessage":"Invalid parameter(s)","detail":"http: request body too large"}

{
	"service": {
		"serviceId": null,
		"framework": {
			"name": "servicecomb-java-chassis",
			"version": "ServiceComb:1.3.0"
		},
		"registerBy": "SDK",
		"environment": "development",
		"appId": "cxisoft",
		"serviceName": "tkcust",
		"alias": null,
		"version": "1.0.0",
		"description": null,
		"level": "FRONT",
		"schemas": ["com.cz073586.tuokebusiness.controller.admin.JzxGxInfoController", "com.cz073586.tuokebusinesshis.controller.index.OrderHistoryChangeIndexController", "com.cz073586.tuokebusiness.controller.index.OfficeWorkrToGcIndexController", "com.cz073586.tuokebusiness.controller.admin.SijiWorkInfoController", "com.cz073586.tuokebusiness.controller.admin.MatouInfoController", "com.cz073586.tuokebusiness.controller.index.CustAreaInfoIndexController", "com.cz073586.tuokebusiness.controller.index.OrderRuntimeIndexController", "com.cz073586.tuokebusiness.controller.index.SijiWorkInfoIndexController", "com.cz073586.tuokebusiness.controller.index.OrderRuntimeChangeIndexController", "com.cz073586.tuokebusiness.controller.index.SijiPaymentTypeIndexController", "com.cz073586.tuokebusiness.controller.index.SijiTixianIndexController", "com.cz073586.tuokebusinesshis.controller.admin.OrderHistoryController", "com.cz073586.tuokebusiness.controller.index.OfficeWorkerIndexController", "com.cz073586.tuokebusiness.controller.admin.SijiXyValueController", "com.cz073586.tuokebusinesshis.controller.admin.OrderHistoryStatusItemsController", "com.cz073586.tuokebusiness.controller.index.StatisticsWithKhInfoIndexController", "com.cz073586.tkcustex.controller.admin.CoustomerInfoTuokeController", "com.cz073586.tuokebusiness.controller.admin.StatisticsWithYyInfoController", "com.cz073586.tkcustex.controller.admin.OrderCostItemBusiExController", "com.cz073586.tuokebusiness.controller.admin.OrderCostItemController", "com.cz073586.tuokeandroid.controller.index.SijiWorkInfoApiController", "com.cz073586.tuokebusiness.controller.index.SmsCodeIndexController", "com.cz073586.tuokebusiness.controller.admin.StatisticsWithKhInfoController", "com.cz073586.tuokebusiness.controller.index.PlaceCfgInfoIndexController", "com.cz073586.tuokebusiness.controller.index.WharfInfoIndexController", "com.cz073586.tkcustex.controller.index.CoustomerInfoTuokeIndexController", "com.cz073586.tuokebusiness.controller.index.MatouInfoIndexController", "com.cz073586.tkcustex.controller.admin.OrderHisBusiExController", "com.cz073586.tuokebusiness.controller.index.HelpInfoIndexController", "com.cz073586.tuokebusiness.controller.admin.SijiPaymentTypeController", "com.cz073586.tuokebusiness.controller.api.SijiPaymentTypeApiController", "com.cz073586.tuokebusiness.controller.admin.SijiInfoController", "com.cz073586.tuokebusinesshis.controller.admin.OrderHistoryChangeController", "com.cz073586.tuokebusiness.controller.admin.PlaceCfgInfoController", "com.cz073586.tuokebusiness.controller.admin.SmsCodeController", "com.cz073586.tuokebusiness.controller.admin.CustGcInfoController", "com.cz073586.tuokebusiness.controller.admin.OrderRuntimeChangeController", "com.cz073586.tuokebusiness.controller.index.CustGcInfoIndexController", "com.cz073586.tuokebusiness.controller.index.YyExportHeaderInfoIndexController", "com.cz073586.tuokebusiness.controller.admin.HelpInfoController", "com.cz073586.tuokebusiness.controller.admin.OrderRuntimeController", "com.cz073586.tuokebusiness.controller.admin.SijiChargeController", "com.cz073586.tuokebusiness.controller.admin.WharfInfoController", "com.cz073586.tuokebusiness.controller.admin.YyExportHeaderInfoController", "com.cz073586.tuokebusiness.controller.index.StatisticsWithYyIndexController", "com.cz073586.tuokebusiness.controller.index.OrderRuntimeStatusItemsIndexController", "com.cz073586.tuokebusiness.controller.index.JzxGxInfoIndexController", "com.cz073586.tuokebusiness.controller.admin.OfficeWorkrToGcController", "com.cz073586.tuokebusiness.controller.index.YunfeiInfoIndexController", "com.cz073586.tuokebusiness.controller.admin.OrderRuntimeStatusItemsController", "com.cz073586.tuokebusiness.controller.index.OrderCostItemIndexController", "com.cz073586.tuokebusinesshis.controller.index.OrderHistoryIndexController", "com.cz073586.tuokebusiness.controller.admin.YunfeiInfoController", "com.cz073586.tuokebusinesshis.controller.index.OrderHistoryStatusItemsIndexController", "com.cz073586.tuokebusiness.controller.admin.SijiMapCustController", "com.cz073586.tkcustex.controller.admin.StationBusiController", "com.cz073586.tuokebusiness.controller.admin.JzxWeightInfoController", "com.cz073586.tuokebusiness.controller.admin.CustAreaInfoController", "com.cz073586.tuokeandroid.controller.index.TestPushController", "com.cz073586.tuokebusiness.controller.admin.OfficeWorkerController", "com.cz073586.tuokebusiness.controller.index.SijiMapCustIndexController", "com.cz073586.tuokebusiness.controller.index.SijiChargeIndexController", "com.cz073586.tuokebusiness.controller.admin.SijiTixianController", "com.cz073586.tuokebusiness.controller.index.SijiInfoIndexController", "com.cz073586.tuokebusiness.controller.index.JzxWeightInfoIndexController", "com.cz073586.tuokebusiness.controller.index.SijiXyValueIndexController", "com.cz073586.tuokeandroid.controller.index.SijiInfoAndroidController"],
		"paths": [],
		"status": "UP",
		"properties": {},
		"thirdPartyService": false,
		"intance": {
			"instanceId": null,
			"serviceId": null,
			"endpoints": ["rest://127.0.0.1:80?protocol=http"],
			"hostName": null,
			"status": "UP",
			"properties": {},
			"healthCheck": {
				"mode": "push",
				"port": 0,
				"interval": 0,
				"times": 0,
				"ttl": 0
			},
			"environment": "production",
			"stage": "prod",
			"dataCenterInfo": null,
			"timestamp": null
		}
	}
}

**Comment by myVictor** [comment]
服务器中心日志：ERROR	v4/microservice_controller.go:53	read body failed	{"error": "http: request body too large"}

**Comment by liubao68** [comment]
看 schemas 的内容，可能超长了。 

看起来你是用了 @RestController定义接口，这个一般是老的 spring boot应用接口， 建议使用 @RestSchema 指定 schema id, 这样  schemas 长度会减少很多。

**Comment by myVictor** [comment]
那为什么1.2.0版本的注册中心没问题？如果是请求体过大业务多了还是会出现这个问题吧。
