### ISSUE TITLE
Q: o.ap.se.sw.invocation.Response 如何设置响应 cookie?

### ISSUE THREAD

**Issue by anqurvanillapy** [apache/servicecomb-java-chassis#1759]
https://github.com/apache/servicecomb-java-chassis/blob/master/swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/Response.java 这一个 `Response` 类与 `jaxrs` 的类似, 但是当前需要设置 cookie,

* 只能手写 `Set-Cookie` 请求头了么?  有没有其他的手段?
* 以及设计上对于 cookie 这块有什么相关的考虑?

**Comment by liubao68** [comment]
和早期的一些 REST 框架基于 web 不同(jsp/servlet)， java-chassis的REST可能不基于web， 应用开发没有暴露过多的 HTTP 协议相关的操作。 设计到 HTTP 协议相关的操作， 少量的可以通过返回特定的状态码和http header实现， 其他的一些场景，可以通过扩展 HttpServerFilter 实现。 如果应用系统是运行于 web (jsp/servlet)，也可以采用 Filter 来拦截请求。
