### ISSUE TITLE
获取yaml中类属性的信息

### ISSUE THREAD

**Issue by xhanthow** [apache/servicecomb-java-chassis#1762]
如要获取parameterList的类型的信息
![image](https://user-images.githubusercontent.com/7291995/82284973-e4d89a00-99cc-11ea-826b-a9e4fd95b834.png)

**Comment by liubao68** [comment]
Invocation.SchemaMeta.Swagger

这样或许可以。得到的是 swagger 类型。 如果存在一个类与之对应，比如 provider 或者 consumer采用了RPC方式调用， Invocation.getInvocationArguments 得到的实际的类型， 采用 BeanDescriptor 可以获取到 java class 的字段信息。

**Comment by xhanthow** [comment]
![image](https://user-images.githubusercontent.com/7291995/82302601-67248680-99ec-11ea-8696-f65df01b9078.png)
有直接方法获取这个targetType么~除了反射
