### ISSUE TITLE
微服务实例是否可以分组？一个微服务是否可以同时注册到多套servicecenter？

### ISSUE THREAD

**Issue by liukuancn** [apache/servicecomb-java-chassis#1763]
场景：
不同业务A、B希望物理隔离环境，不互相影响，但是又希望能共用X微服务

问题：
如下思路1/2是否可行？

思路1：
一套微服务实例分为A、B两组，A组只处理A业务，B组只处理B业务，都能走微服务接口访问X。

思路2：
A、B两套微服务，独立的servicecenter，但是X能同时注册到两个servicecenter上，A、B都能访问。

思路3：
拆分X微服务为服务，A、B和X走服务接口

**Comment by liubao68** [comment]
java-chassis 提供了简单的逻辑隔离支持这种场景： A 属于 appA, B 属于 appB， X属于appX， X设置为允许夸app访问， X的服务名称为 appX:X ， 显示的指定 app id.  参考： https://github.com/apache/servicecomb-java-chassis/tree/master/demo/demo-crossapp

**Comment by liukuancn** [comment]
> java-chassis 提供了简单的逻辑隔离支持这种场景： A 属于 appA, B 属于 appB， X属于appX， X设置为允许夸app访问， X的服务名称为 appX:X ， 显示的指定 app id. 参考： https://github.com/apache/servicecomb-java-chassis/tree/master/demo/demo-crossapp
确实可以，多谢！
另外发现本地调试用的“local-service-center-2.3.34-windows-amd64”不支持跨app访问，最好能优化下：）
