### ISSUE TITLE
ARM上不支持netty-tcnative,etcd鉴权失败，服务ARM平台core dump

### ISSUE THREAD

**Issue by hongfeihuangseu** [apache/servicecomb-java-chassis#1765]
微服务执行定时任务连接etcd需要鉴权，用到了netty-tcnative，在x86机器上可以，ARM上直接core dump，初步定位是ARM上不支持netty-tcnative，请问下怎么解决

**Comment by liubao68** [comment]
netty tcnative 里面包含一些 so 文件， boringssl 的， 没有 ARM 版本， 需要自行编译 ARM 版本

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
