### ISSUE TITLE
RestSchema生成yaml错误

### ISSUE THREAD

**Issue by 364844763** [apache/servicecomb-java-chassis#1772]
public enum AttributeDataType {
    INT("int"),
    LONG("long"),
    DECIMAL("decimal"),
    STRING("string"),
    DATE_TIME("DateTime"),
    JSON_OBJECT("jsonObject");

    private String value;

    private AttributeDataType(String value) {
        this.value = value;
    }

    public String toString() {
        return this.value;
    }

    public static AttributeDataType fromValue(String text) {
        if (StringUtils.isEmpty(text)) {
            return null;
        } else {
            AttributeDataType[] var1 = values();
            int var2 = var1.length;

            for(int var3 = 0; var3 < var2; ++var3) {
                AttributeDataType b = var1[var3];
                if (StringUtils.equals(b.value, text)) {
                    return b;
                }
            }

            return null;
        }
    }
}

Cannot deserialize value of type `cse.gen.EDGE_WL_2_2.IoEdgeManager.DataCleanConsoleController.Enum_4d0959a16fa8639c84dc1faa05048f8ef176038864985daccffa767696c70b6b` from String "decimal": not one of the values accepted for Enum class: [DECIMAL, JSON_OBJECT, LONG, DATE_TIME, INT, STRING

RestSchema的没有实现序列化的方法，导致接口解析失败

**Comment by liubao68** [comment]
Maybe you can try `@JsonProperty`, see https://www.baeldung.com/jackson-serialize-enums for an example

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
