### ISSUE TITLE
jedis-2.9.0 scope被指定为provided，导致业务lib没这个包，影响功能

### ISSUE THREAD

**Issue by Neverstop** [apache/servicecomb-java-chassis#1776]
java-chassis-dependencies-2.0.1.pom ： 
      <dependency>
        <groupId>redis.clients</groupId>
        <artifactId>jedis</artifactId>
        <version>${jedis.version}</version>
        <scope>provided</scope>
        <optional>true</optional>
      </dependency>

**Comment by liubao68** [comment]
java chassis do not use redis, maybe can be removed in next version. you can specify the scope in your dependency or add you own dependency-management to include it.

**Comment by liubao68** [comment]
Fixed in https://github.com/apache/servicecomb-java-chassis/pull/1846  and will be available in 2.1.0
