### ISSUE TITLE
现在ServiceComb是否能支持动态路由注册，以支持服务的重构？

### ISSUE THREAD

**Issue by zhufeizzz** [apache/servicecomb-java-chassis#1785]
比如原来有两个服务，分别提供两个接口：
cse://service-a/rest/do-something-a/
cse://service-b/rest/do-something-b/

因为架构整改需要合并service-a和service-b，有办法通过注册路由的方式无缝兼容吗？

**Comment by liubao68** [comment]
兼容的具体含义是什么？ 没看明白。 合并后微服务名字是 xxx, 客户端仍然用 service-a, service-b调用？

**Comment by zhufeizzz** [comment]
@liubao68 
是的，代码的重构会涉及微服务的拆分和合并，想做到对Client无感知
在文档里面搜了下没发现哪个特性能支持

**Comment by liubao68** [comment]
这种情况客户端必须修改服务名称，或者需要在客户端做一些其他额外的处理，将老名称映射到新名称，这两种处理策略按照上面的要求都是不兼容的。 

唯一的办法就是服务发现能够继续发现 service-a, service-b， 并把地址指向合并的服务xxx。 这个方案是复杂的，而且容易出错。

java-chassis/demo/demo-multiple有个很好的例子尽可能减少合并后客户端的修改， 但仍然做不到兼容。

**Comment by zhufeizzz** [comment]
@liubao68 
如果我可以定制Client端代码，我需要用哪种扩展来实现自定义路由呢？我看例子里只是用SpringBoot变量来动态设置，这种对Client会有侵入。

**Comment by liubao68** [comment]
如果可以改客户端代码（重新编译，但是对使用者透明，也算修改客户端代码）， 我觉得最好的办法就是让客户端排查下，把服务名字改下。 

这种场景核心要解决的是独立升级的问题，即要求服务端升级不影响客户端功能。这个目前看就只有先老的两个服务不下线， 新服务上线， 然后通知使用者变更，给使用者修改周期，当使用者都修改完成后，将老服务下线即可。

**Comment by zhufeizzz** [comment]
@liubao68 
我的意思是说能否通过ServiceComb扩展的方式实现，而不是直接修改ServiceComb源码。

**Comment by liubao68** [comment]
没有标准化的方式进行这样的扩展，但是应该可以做到的， 方案会显得非常难看和难于维护， 所以就不能给你推荐方案了。 正如我前一个回复的说明，`如果可以改客户端代码（零代码修改，对使用者透明，但是需要重新编译，也算修改客户端代码）， 我觉得最好的办法就是让客户端排查下，把服务名字改下。`
