### ISSUE TITLE
servicecomb.rest.servlet.urlPattern 支持多个path吗？

### ISSUE THREAD

**Issue by zouwenxmu** [apache/servicecomb-java-chassis#1801]
因存量项目需要注册多个路径下的rest接口，跟踪了一下初始化sevlet代码
`ServletUtils.filterUrlPatterns(urlPattern)`，从源码看上去像是要支持多个路径的
使用数组参数传入urlPattern
`urlPattern: ['/cse/*','/adapter/*']` 或者
`urlPattern:` 
` - /cse/*`
` -/adapter/*`
尝试后，并没有解析成多个路径，注册不成功

**Comment by liubao68** [comment]
目前是不支持的。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
