### ISSUE TITLE
servicecomb集群场景，新服务上线瞬间，集群处理能力显著下降

### ISSUE THREAD

**Issue by jiangqiushi** [apache/servicecomb-java-chassis#1808]
我们有个测试场景，一个客户端，一个nginx，两个网关（servicecomb 客户端），两个业务后台服务（servicecomb server），如下图所示：
![捕获](https://user-images.githubusercontent.com/19721172/83474887-adcfb180-a4bf-11ea-873d-ded2762b3df9.PNG)

当ServiceComb Server1下线，集群处理能力降低了50%，和预期一致。
但是当ServiceComb Server1重新上线后，在上线瞬间500ms内，tps又下降了40%。
![捕获1](https://user-images.githubusercontent.com/19721172/83475144-52ea8a00-a4c0-11ea-8310-21fd9a9660af.PNG)

我的疑问：

1. 服务上下线servicecomb客户端需要更新路由缓存吧？更新缓存会阻塞客户端请求吧？
2. 服务上线后为什么在500ms内，处理能力下降了很多？

**Comment by liubao68** [comment]
你使用的是哪个版本？客户端和服务端是否存在大量的接口？ 
还有可以单独测试下当server启动成功后，第一次调用这个接口的时延，有可能业务第一次调用需要初始化，比较耗时， 这样可能拖慢整体吞吐量，因为当新实例启动后， 请求会在两个实例之间均匀分配，第一次调用比较慢或者存在锁等情况，会拖慢这50%的请求。

**Comment by jiangqiushi** [comment]
> 你使用的是哪个版本？客户端和服务端是否存在大量的接口？
> 还有可以单独测试下当server启动成功后，第一次调用这个接口的时延，有可能业务第一次调用需要初始化，比较耗时， 这样可能拖慢整体吞吐量，因为当新实例启动后， 请求会在两个实例之间均匀分配，第一次调用比较慢或者存在锁等情况，会拖慢这50%的请求。

我们使用的版本是1.3.0，就一个rest接口，逻辑也非常简单。
你的分析我觉得有点不通，就算我新上线的server第一次处理请求比较慢，但是server2不论是资源还是连接都是已经ready的，处理能力是不变的，不应该再下降40%。

**Comment by liubao68** [comment]
> > 你使用的是哪个版本？客户端和服务端是否存在大量的接口？
> > 还有可以单独测试下当server启动成功后，第一次调用这个接口的时延，有可能业务第一次调用需要初始化，比较耗时， 这样可能拖慢整体吞吐量，因为当新实例启动后， 请求会在两个实例之间均匀分配，第一次调用比较慢或者存在锁等情况，会拖慢这50%的请求。
> 
> 我们使用的版本是1.3.0，就一个rest接口，逻辑也非常简单。
> 你的分析我觉得有点不通，就算我新上线的server第一次处理请求比较慢，但是server2不论是资源还是连接都是已经ready的，处理能力是不变的，不应该再下降40%。

第一次调用 server2， 会存在很多资源的初始化，包括：建立连接（如果采用 https， 并发建立连接通常非常慢，并不是连接是ready了，而是请求来的时候，才开始）；还要看具体rest接口本身的逻辑，比如有时候需要初始化一些单例，这个时候存在锁，其他请求虽然来了，但是需要等待锁，整体性能也会下降。
