### ISSUE TITLE
Please upgrade netty-tcnative-boringssl-static version to 2.0.31

### ISSUE THREAD

**Issue by johnyannj** [apache/servicecomb-java-chassis#1831]
netty-tcnative 2.0.31.Final  was released.  it already supports aarch64.

so  please upgrade it to 2.0.31  and remove the  “ .so”  file in fondation-ssl 

Thanks

**Comment by liubao68** [comment]
fixed in https://github.com/apache/servicecomb-java-chassis/pull/1851 and will be available at 2.1.0
