### ISSUE TITLE
ServiceComb有性能测试报告可以参考吗？

### ISSUE THREAD

**Issue by zhufeizzz** [apache/servicecomb-java-chassis#1833]
比如不同协议，不同对象大小的QPS这些，有官方的测试报告参考吗？

@liubao68 
我对比了一下Highway和Http，空请求情况下Highway性能略高20%，大数据量场景下性能还低30%左右，不知道是我测试场景不对还是什么。

测试环境：Windows10 i7-8700 32G
ServiceComb版本：2.0.2
HTTP服务端：Tomcat 50线程
HighWay服务端：默认配置
客户端：10线程

报文说明：
数据使用org.json的JSONObject对象存储，放到1000条的List中，每个字段长度为10字符，测试结果如下
![image](https://user-images.githubusercontent.com/4591255/84979789-e7144c80-b162-11ea-85c5-c974ae8d4479.png)

**Comment by liubao68** [comment]
Highway不支持JSONObject编解码，为了保持和REST的一致性，后台进行了特殊处理JSONObject还是使用的JSON编解码的。 Highway 基于 protobuffer 编码， 当使用跨语言的数据结构的时候，才能够获得最高性能。比如：

```
class Request {
   int a;
  String b;
   long c;
   Map<String, Strnig> d;
}
```

这些类型 protobuffer 都支持的很好。 

另外，看你的测试client和server都在一个windows机器上，需要观察下机器本身的CPU和内存占用情况。 很可能已经到机器的处理上限了，性能不会往上增长。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
