### ISSUE TITLE
CSE集成Springfox 报找不到ServletContext这个bean 请问怎么解决

### ISSUE THREAD

**Issue by guanhang89** [apache/servicecomb-java-chassis#1834]

**Comment by liubao68** [comment]
Springfox 依赖于 spring boot mvc 运行时， 无法直接在 servicecomb 直接使用。 servicecomb 会将swagger注册到服务中心的。另外， 通过集成 [inspector](https://docs.servicecomb.io/java-chassis/zh_CN/featured-topics/using-inspector/)， 也能够从微服务进入契约管理控制台，不需要 springfox。

**Comment by Shoothzj** [comment]
the springfox project is now unmaintained, It is recommended to use springdoc to replace
