### ISSUE TITLE
1.2.0.B007r7版本CSE对pathParam参数值为url时，疑似存在编解码的bug

### ISSUE THREAD

**Issue by Wangren725** [apache/servicecomb-java-chassis#1847]
1.2.0.B007r7版本CSE对pathParam参数值为url时，疑似存在编解码的bug
场景再现：
客户端->边缘服务->微服务
客户端发起请求：GET /aaa/bbb/https%3A%2F%2Fdomain.cn%2Fv726
经过边缘服务转发变为了（注意https后面的那个冒号）：GET /aaa/bbb/https:%2F%2Fdomain.cn%2Fv726
微服务接到请求后解码，获得的参数值为null

初步定位：
边缘服务发起请求对pathParam的编码调用方法：org.apache.servicecomb.foundation.common.http.HttpUtils#encodePathParam，该方法并不会对冒号进行编码
微服务收到请求是对pathParam进行解码调用方法：org.apache.servicecomb.foundation.common.http.HttpUtils#uriDecodePath，该方法解码https:%2F%2Fdomain.cn%2Fv726后得到的结果为null

**Comment by liubao68** [comment]
你可以试试最新版本是否还有这个问题吗？记得早期修复过类似问题。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
