### ISSUE TITLE
求助：Service Center 是否支持监听SC上所有服务的注册/反注册，服务信息变更（增、删、改）事件的订阅？

### ISSUE THREAD

**Issue by HarryMMM** [apache/servicecomb-java-chassis#1857]
背景： 需要实现一个功能，步骤如下：
       1.  获取所有微服务的信息，并存储在DB中。。  
       2.  当SC上的微服务信息有变化时，更新DB中的信息。（期望通过SC的时间，而非轮询）
期望得知：
       SC已有能力是否支持相关事件的订阅（即背景中的步骤二功能）？如有，该怎么使用？

**Comment by liubao68** [comment]
SC支持websocket连接获取事件。详细的技术细节可以参考 servicecomb-service-center 项目， java 代码可以参考本项目的 registry-service-center 模块。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
