### ISSUE TITLE
loadbalance请求重试机制没有生效

### ISSUE THREAD

**Issue by liyupeisleep** [apache/servicecomb-java-chassis#1858]
起了一个消费端，两个服务端。一个服务端超时，一个ok。请求重试机制的配置没有问题

![image](https://user-images.githubusercontent.com/67566979/85965850-a9c87e00-b9f0-11ea-9b7b-f2ffa7b8e5bf.png)

结果还是报490，另一台机器上也没有access日志

**Comment by liyupeisleep** [comment]
备注一下，是本地起的两个服务端，用的不同的端口

**Comment by liubao68** [comment]
超时不会重试。可以参考： https://bbs.huaweicloud.com/forum/thread-12790-1-1.html

**Comment by liyupeisleep** [comment]
> 超时不会重试。可以参考： https://bbs.huaweicloud.com/forum/thread-12790-1-1.html

你看下截图，已经走到isFaiedResponse=true的分支里了，源码里也是显示490


  protected boolean isFailedResponse(Response resp) {
    if (resp.isFailed()) {
      if (InvocationException.class.isInstance(resp.getResult())) {
        InvocationException e = (InvocationException) resp.getResult();
        return e.getStatusCode() == ExceptionFactory.CONSUMER_INNER_STATUS_CODE
            || e.getStatusCode() == 503;
      } else {
        return true;
      }
    } else {
      return false;
    }
  }

  public static final int CONSUMER_INNER_STATUS_CODE = 490;

**Comment by liubao68** [comment]
这个地方不是重试逻辑， 你可以看下上面的逻辑， 构造 RetryHandler 的过程。

**Comment by liyupeisleep** [comment]
感谢宝哥，问题解决
