### ISSUE TITLE
无法正确使用nacos，在nacos中配置路由不生效

### ISSUE THREAD

**Issue by cmkcmk181** [apache/servicecomb-java-chassis#1859]
java-chassis版本：2.0.2
nacos-server版本：1.1.4
问题：
nacos配置如下：
![360截图17120526525657](https://user-images.githubusercontent.com/8915324/86016925-fb572400-ba55-11ea-9064-06d74f0fae42.png)

在启动应用的过程中无法解析yaml格式，报错如下：
![360截图170405178212974](https://user-images.githubusercontent.com/8915324/86016944-001bd800-ba56-11ea-8122-982344b43be6.png)

如果将配置中心的格式改为json后不会报错，但路由并未生效。

**Comment by liubao68** [comment]
路由不生效的问题，可以通过调试 `CommonHttpEdgeDispatcher` 分析下。 报错看起来应该是你的配置错误了， 多了一个 TAB 缩进。

**Comment by cmkcmk181** [comment]
应该不缩进的问题改了也是报错，在NacosClient.java中解析yaml格式的字符串时报错了，如下：
![image](https://user-images.githubusercontent.com/8915324/86084222-da7ee500-bace-11ea-86a4-211ac30081a5.png)

**Comment by liubao68** [comment]
那应该是早期模块的贡献者没有考虑支持 `yaml` 格式了。 你有没有兴趣结合你的场景修改代码，提交个 PR？

**Comment by liubao68** [comment]
检查了下代码的 readme, 早期代码确实只实现了 `json` 的支持， 参考： https://github.com/apache/servicecomb-java-chassis/tree/master/dynamic-config/config-nacos

**Comment by cmkcmk181** [comment]
json比较麻烦

**Comment by cmkcmk181** [comment]
在microservice.yaml中的配置也比较奇怪，要在两个地方写配置中心的地址，少写一个就会报错：
![image](https://user-images.githubusercontent.com/8915324/86100070-f09a9e80-baea-11ea-9475-2174a7069248.png)

**Comment by liubao68** [comment]
我看了下代码， 你又帮忙发现一个 bug， 有两个地方读取的配置项值不一样。 应该是最开始用的 nacos.config.servierAddr， 后面提了个检视意见，改成了 servicecomb.nacos.serverAddr， 有个地方忘记改了。

**Comment by cmkcmk181** [comment]
我改为json的格式配置也不生效，我跟踪了代码发现以下if条件不满足，是不是和这个有关系？
![image](https://user-images.githubusercontent.com/8915324/86337381-9aad2e80-bc83-11ea-8dbb-7376da0fe2c1.png)
怎么会有cse.开头的？

**Comment by liubao68** [comment]
应该不是这个原因。 你调试的时候 'added' 包含下发的配置吗？ 这个代码是为了兼容做的特殊处理， 即将 'cse.xxx' 拷贝一份 'servicecomb.xxx'。

**Comment by cmkcmk181** [comment]
content和body都有值，但是路由还是不生效。直接配置在microservice.yaml中是生效的

![image](https://user-images.githubusercontent.com/8915324/87123990-673d5600-c2ba-11ea-8c48-972898722239.png)

json格式如下：
{
    "servicecomb": {
      "edge": {
        "filter": { 
          "addHeader": {
            "enabled": true,
            "allowedHeaders": "Authorization"
          }
        }
      },
      "http": {
        "dispatcher": {
          "edge": {
            "url": {
              "enabled": true,
              "pattern": "/(.*)",
              "mappings": {
                "authV1": {
                  "prefixSegmentCount": 1,
                  "path": "/api/auth/v1/.*",
                  "microserviceName": "fw-auth",
                  "versionRule": "1.0.0-2.0.0"
                }
              }
            }
          }
        }
      }
    }
}

**Comment by liubao68** [comment]
我看你的截图，貌似json配置的配置项是 `servicecomb.servicecomb.*`

**Comment by cmkcmk181** [comment]
不是，只有一个servicecomb.

**Comment by cmkcmk181** [comment]
nacos的配置如下：
![image](https://user-images.githubusercontent.com/8915324/87126741-55aa7d00-c2bf-11ea-8f30-cb5cfcc0baa3.png)

**Comment by liubao68** [comment]
你可以试试在 URLMappedEdgeDispatcher 下面的代码打个断点看看，更新配置的时候， 这个 listener 是否被执行到。 

```
  private void loadConfigurations() {
    ConcurrentCompositeConfiguration config = (ConcurrentCompositeConfiguration) DynamicPropertyFactory
        .getBackingConfigurationSource();
    configurations = URLMappedConfigurationLoader.loadConfigurations(config, KEY_MAPPING_PREFIX);
    config.addConfigurationListener(event -> {
      if (event.getPropertyName().startsWith(KEY_MAPPING_PREFIX)) {
        LOG.info("Map rule have been changed. Reload configurations. Event=" + event.getType());
        configurations = URLMappedConfigurationLoader.loadConfigurations(config, KEY_MAPPING_PREFIX);
      }
    });
  }
```

**Comment by liubao68** [comment]
我突然想到可能什么原因了， 配置项被转换为 Map of Map ， 而不是 Map of key String and value String.  这个地方也是 bug .. 这部分贡献的代码测试不充分... 。  你如果继续使用，可以考虑将这个类本地拷贝一份， 和业务代码一起编译，把发现的bug改下。 如果你方便的话，可以将修改代码提交一个 PR。 项目维护人数比较少， 最近我也抽不出时间来帮忙修复。 短期内看你需要大家帮忙修复了， 或者等我把手头事情弄完后修复。

**Comment by cmkcmk181** [comment]
好的，是JSON转map的问题，框架内有现成的转换方法吗？

**Comment by cmkcmk181** [comment]
已提交PR

**Comment by liubao68** [comment]
@cmkcmk181 This PR have some improvements need fix. Do you have time to finish it? Or need others help?

**Comment by liubao68** [comment]
fixed in 2.1.1

**Comment by liubao68** [comment]
文档配置进行类刷新，参考： https://docs.servicecomb.io/java-chassis/zh_CN/config/general-config/
