### ISSUE TITLE
在Apollo中配置关于日志的配置不生效，还有就是我想自己监听Apollo的配置变化做一些事情，不知道该怎么做

### ISSUE THREAD

**Issue by ze380639914** [apache/servicecomb-java-chassis#1862]

**Comment by liubao68** [comment]
可以参考[开发指南](https://docs.servicecomb.io/java-chassis/zh_CN/config/general-config/) 的中 `在程序中读取配置信息` 配置注入机制`章节。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
