### ISSUE TITLE
请问TransportManager这里有线程不安全的问题吗

### ISSUE THREAD

**Issue by Shoothzj** [apache/servicecomb-java-chassis#1872]
![image](https://user-images.githubusercontent.com/12933197/86776397-c2890180-c08a-11ea-8dee-954bd68aaa89.png)

![image](https://user-images.githubusercontent.com/12933197/86776445-ccab0000-c08a-11ea-8e42-d7db93921955.png)
这里提示了还是空指针，客户端版本1.3.0的话，我分析了一下，看好像是transportManager没注入进去?

**Comment by yhs0092** [comment]
看代码最有可能的原因确实是`TransportManager`没注入到`CseContext`，如果真是这样的话，你需要先检查一下是不是加载了不止一个 Spring ApplicationContext 导致 bean 注入有问题。
不行的话就提供一个能复现问题的demo给我们看看吧，只看这两张截图很难确定根因的
