### ISSUE TITLE
servicecomb-2.0.2高并发性能测试报错

### ISSUE THREAD

**Issue by neverstop** [apache/servicecomb-java-chassis#1873]
[RestServerVerticle:117]|Unexpected error in server.cause:SSLException,message:Received close_notify during handshake
run.log:2020-07-08 09:32:45.309|ERROR|[vert.x-eventloop-thread-3]|5f052237e3a23cad|[RestServerVerticle:117]|Unexpected error in server.cause:SSLException,message:Received close_notify during handshake
run.log:2020-07-08 09:32:45.347|ERROR|[vert.x-eventloop-thread-3]|5f052237e3a23cad|[RestServerVerticle:117]|Unexpected error in server.cause:SSLException,message:Received close_notify during handshake
run.log:2020-07-08 09:32:45.374|ERROR|[vert.x-eventloop-thread-3]|5f052237e3a23cad|[RestServerVerticle:117]|Unexpected error in server.cause:SSLException,message:Received close_notify during handshak

大量报错，大家有遇到过吗

**Comment by liubao68** [comment]
这种情况可能发生在大量连接断连，然后重连的情况，由于 SSL 握手比较慢，大量并发连接会超过服务端的处理负荷，就会出现连接异常。测试的时候，可以缓缓加压，当稳定后，再增大并发测试。 另外，如果测试过程中，大量请求超时，也可能导致大量并发连接重建的情况。可以通过打开 java-chassis 的 metrics 功能， 观察下连接建立和断开的情况。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
