### ISSUE TITLE
请问CSE的文件上传有Demo吗，按照开发指南使用获取到的MultiPart为null

### ISSUE THREAD

**Issue by guanhang89** [apache/servicecomb-java-chassis#1878]
部分代码：
![1](https://user-images.githubusercontent.com/10530898/87016256-0c93f380-c201-11ea-8dc1-7cf96a23594f.png)
postman测试：
![2](https://user-images.githubusercontent.com/10530898/87016263-0ef64d80-c201-11ea-87a6-da0d743de892.png)

**Comment by liubao68** [comment]
You can read docs here https://docs.servicecomb.io/java-chassis/zh_CN/general-development/upload-download/

**Comment by szcg1981** [comment]
要把除path外的全去掉
