### ISSUE TITLE
Spring Validation验证抛出的异常无法捕获吗

### ISSUE THREAD

**Issue by macosong** [apache/servicecomb-java-chassis#1879]
我测试用的controller接口定义如下：
`String getVerifyCode(@NotNull(message = "phone cannot be empty!") Long phone) throws Exception;`
Long型变量为空时访问rest接口会抛出javax.validation.ConstraintViolationException
但是我自定义的ExceptionToProducerResponseConverter类却无法捕捉到这个异常，convert方法中的异常处理逻辑并没有执行。
请问这个问题怎么解决呢？谢谢

**Comment by liubao68** [comment]
java-chassis包含了`ConstraintViolationExceptionToProducerResponseConverter`，看下是否被这个处理了。 或者是不是没有配置SPI的service文件，导致新加的配置不生效。

**Comment by macosong** [comment]
> java-chassis包含了`ConstraintViolationExceptionToProducerResponseConverter`，看下是否被这个处理了。 或者是不是没有配置SPI的service文件，导致新加的配置不生效。

有配置service文件，应该是被`ConstraintViolationExceptionToProducerResponseConverte`处理了，所以我自定义的converter类没有生效。
因为要修改它默认返回的Response，所以可能让自定义的Converter需要覆盖掉这个类，请问有什么办法解决吗?谢谢

**Comment by liubao68** [comment]
如果过这样的话， 覆盖下 getOrder 方法。

**Comment by macosong** [comment]
已解决，谢谢。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
