### ISSUE TITLE
Zipkin的Tracing不能自己定制吗？比如采样率

### ISSUE THREAD

**Issue by zhufeizzz** [apache/servicecomb-java-chassis#1880]
TracingConfiguration没看到有开放扩展地方。我想定制几个地方
1、Tags，区分CSE和普通的SpringMVC
2、采样率
3、SpanName，添加URL，而不只是HTTP方法名

**Comment by liubao68** [comment]
这个功能不是特别熟悉，这里有两个文档，可以参考下：
https://docs.servicecomb.io/java-chassis/zh_CN/general-development/customized-tracing/
https://docs.servicecomb.io/java-chassis/zh_CN/general-development/customized-tracing/

**Comment by zhufeizzz** [comment]
> 这个功能不是特别熟悉，这里有两个文档，可以参考下：
@liubao68 我建议是这样
1、现在CSE的TracingConfiguration的Bean自动扫描初始化，不支持用户覆盖，希望增加类似@ConditionOnMissingBean注解，支持用户自己覆盖。
2、建议升级一下zipkin的版本，现在的5.6版本是18年的，有些特性不支持。

**Comment by xingx2** [comment]
调用RpcSchema定义的api时追踪信息不全，http.path只显示方法名，不显示SchemaId或实际的path（/类名/方法名）。
有什么方法可以获得实际path或者schemaId吗？

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
