### ISSUE TITLE
微服务开启了公钥认证后，服务自身的健康检查接口就无法被外部请求调用了

### ISSUE THREAD

**Issue by zhangchi02** [apache/servicecomb-java-chassis#1884]
服务开启了公钥认证，然后CCE配置了调用服务接口的健康检查，这样的话CCE的请求会因为没有使用服务公钥签名而失败，进而导致进程直接被kill掉

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
