### ISSUE TITLE
microservice.yaml  可以配置多个环境吗? 类似 spring.profiles.active

### ISSUE THREAD

**Issue by huanghezhen** [apache/servicecomb-java-chassis#1889]

**Comment by liubao68** [comment]
不支持的，但是可以通过在classpath存放一个文件或者通过动态配置、环境变量覆盖。 参考： https://docs.servicecomb.io/java-chassis/zh_CN/config/general-config/

**Comment by huanghezhen** [comment]
好的好的 谢谢 谢谢

**Comment by liubao68** [comment]
补充说明下， 如果你使用 spring boot 运行 java-chassis， java-chassis 也支持读取 spring 的配置，这种情况下， 你仍然可以使用 spring.profiles.active 机制创建多个 application*.yml 文件。

**Comment by huanghezhen** [comment]
servicecomb 与 spring 解析yml数组不统一,导致使用application配置多个注册中心(集群模式)的时候报错

**Comment by liubao68** [comment]
@huanghezhen 可以研究下 spring 如何配置。 BTW： 不要在已经 closed 的 issue 里面回复， 可以另外开启新的 issue。
