### ISSUE TITLE
未配置重试机制，但是却触发了重试机制

### ISSUE THREAD

**Issue by solitudeycq** [apache/servicecomb-java-chassis#1890]
两个微服务，A和B，A配置了负载均衡但是未配置重试机制，A调用B的服务，B抛出RuntimeException，A中日志打印InvocationException，code=590，但是随后A又自动调用B，并且丢掉了所有的请求信息，请问这是什么原因？

**Comment by liubao68** [comment]
需要提供更多的信息帮助识别问题。
