### ISSUE TITLE
cse降级熔断，出错后的处理策略问题

### ISSUE THREAD

**Issue by gankerrrr** [apache/servicecomb-java-chassis#1891]
cse降级熔断基本实现了，有个遗留问题，现在调用接口如果出现异常，直接就返回cse 的fallback了，后面的代码逻辑都不执行了，这样不太合适吧？

**Comment by liubao68** [comment]
你能提供下代码示例和期望的执行过程吗？https://docs.servicecomb.io/java-chassis/zh_CN/references-handlers/bizkeeper/ 这里有关于出错和熔断过程的描述。 流程是设计后是固定的， 要看看业务场景和预期结果，可以帮助改善设计

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
