### ISSUE TITLE
CSE的sdk中getServletContext以及获取session的方法固定抛出异常

### ISSUE THREAD

**Issue by liuyifeng1992** [apache/servicecomb-java-chassis#1892]
请问如果需要获取这两个对象，有没有什么方法呢？

**Comment by liubao68** [comment]
你的运行环境是怎么样的？ rest over vert.x HTTP server还是rest over Servlet?

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
