### ISSUE TITLE
Can not run it on OSX

### ISSUE THREAD

**Issue by Shoothzj** [apache/servicecomb-java-chassis#1895]
I have a very strange problem here. The mac system runs start-service-center.sh, servicecomb creates a data folder by itself, and then accesses it unconditionally.

![image](https://user-images.githubusercontent.com/12933197/88608828-3da36d80-d0b5-11ea-98e7-4c7ed61caa1c.png)

![image](https://user-images.githubusercontent.com/12933197/88608845-48f69900-d0b5-11ea-81e3-ba84800e4399.png)

**Comment by liubao68** [comment]
You can ask service center questions here :  https://github.com/apache/servicecomb-service-center/issues
