### ISSUE TITLE
OSX local start, NPE org.apache.servicecomb.registry.RegistrationManager.getMicroservice(RegistrationManager.java:88)

### ISSUE THREAD

**Issue by Shoothzj** [apache/servicecomb-java-chassis#1896]
Demo地址: https://github.com/Shoothzj/maven-demo

I have no idea, what's primary?

**Comment by Shoothzj** [comment]
![image](https://user-images.githubusercontent.com/12933197/88610548-89f0ac80-d0b9-11ea-8e9c-500c1feefc34.png)

![image](https://user-images.githubusercontent.com/12933197/88610566-94ab4180-d0b9-11ea-95ed-0e24390d6c8d.png)

**Comment by yhs0092** [comment]
Hello, as the registration mechanism changed in the new version, Java-Chassis provides multiple choices about how your microservice instances register themselves and discover the providers. As for the registration of connecting to the Apache Service Center, which is the default plan in Java-Chassis 1.x, is just one of the choices in Java-Chassis new version. To enable it, there are two more step you need to do before you start the demo:

- introduce a new dependency org.apache.servicecomb:registry-service-center

  This dependency contains the service center client to enable your microservice to get access to Service Center

- add a new config item in your microservice.yaml file:

  `servicecomb.service.registry.enabled`=`true`, this item enable the `ServiceRegistry` implementation connecting to Service Center to work.

For more information about the registration mechanism of Java-Chassis, you can refer to the [registration docs](https://docs.servicecomb.io/java-chassis/zh_CN/registry/introduction/)

**Comment by liubao68** [comment]
mentioned in upgrade guide https://docs.servicecomb.io/java-chassis/zh_CN/featured-topics/upgrading/2_0_1T2_1_0/
