### ISSUE TITLE
实例隔离没有生效

### ISSUE THREAD

**Issue by liyupeisleep** [apache/servicecomb-java-chassis#1910]
1、注册了三个服务端A、B、C，一个消费端。将消费端的实例隔离配置修改如下
![image](https://user-images.githubusercontent.com/67566979/89303170-67085e80-d69e-11ea-937c-005677b62551.png)
2、服务端B方法内设置sleep，使其超时报490
3、一分钟内触发多次，还是会有1/10左右的概率请求到B服务，报490
2020/08/04 21:54:15 +0800||5f2968872646c812||GET /eculs/v1/4130049000000004802/learnt-count||10.52.219.152||10.52.219.152||500||-||-||0||-||getUserLearntCount
2020/08/04 21:54:21 +0800||5f29688d952ad804||GET /eculs/v1/4130049000000004802/learnt-count||10.52.219.152||10.52.219.152||500||-||-||0||-||getUserLearntCount
2020/08/04 21:54:27 +0800||5f296893d2969513||GET /eculs/v1/4130049000000004802/learnt-count||10.52.219.152||10.52.219.152||500||-||-||0||-||getUserLearntCount
2020/08/04 21:54:33 +0800||5f2968993fe63b1d||GET /eculs/v1/4130049000000004802/learnt-count||10.52.219.152||10.52.219.152||500||-||-||0||-||getUserLearntCount
2020/08/04 21:54:39 +0800||5f29689f61bcfc86||GET /eculs/v1/4130049000000004802/learnt-count||10.52.219.152||10.52.219.152||501||-||-||0||-||getUserLearntCount
2020/08/04 21:54:45 +0800||5f2968a50dc53b72||GET /eculs/v1/4130049000000004802/learnt-count||10.52.219.152||10.52.219.152||501||-||-||0||-||getUserLearntCount
2020/08/04 21:54:52 +0800||5f2968acb71274d0||GET /eculs/v1/4130049000000004802/learnt-count||10.52.219.152||10.52.219.152||499||-||-||0||-||getUserLearntCount
2020/08/04 21:54:58 +0800||5f2968b25657f0ac||GET /eculs/v1/4130049000000004802/learnt-count||10.52.219.152||10.52.219.152||501||-||-||0||-||getUserLearntCount
2020/08/04 21:55:06 +0800||5f2968bab56e7ed4||GET /eculs/v1/4130049000000004802/learnt-count||10.52.219.152||10.52.219.152||499||-||-||0||-||getUserLearntCount
2020/08/04 21:55:13 +0800||5f2968c1fdd6fc65||GET /eculs/v1/4130049000000004802/learnt-count||10.52.219.152||10.52.219.152||500||-||-||0||-||getUserLearntCount
2020/08/04 21:55:21 +0800||5f2968c9ffb5a219||GET /eculs/v1/4130049000000004802/learnt-count||10.52.219.152||10.52.219.152||501||-||-||0||-||getUserLearntCount
2020/08/04 21:55:27 +0800||5f2968cfab3cc39a||GET /eculs/v1/4130049000000004802/learnt-count||10.52.219.152||10.52.219.152||500||-||-||0||-||getUserLearntCount
2020/08/04 21:55:33 +0800||5f2968d5820c6573||GET /eculs/v1/4130049000000004802/learnt-count||10.52.219.152||10.52.219.152||501||-||-||0||-||getUserLearntCount
2020/08/04 21:55:39 +0800||5f2968db5c7f02b1||GET /eculs/v1/4130049000000004802/learnt-count||10.52.219.152||10.52.219.152||498||-||-||0||-||getUserLearntCount
2020/08/04 21:55:45 +0800||5f2968e1fb5bb32c||GET /eculs/v1/4130049000000004802/learnt-count||10.52.219.152||10.52.219.152||500||-||-||0||-||getUserLearntCount
2020/08/04 21:55:51 +0800||5f2968e7f2e80ddf||GET /eculs/v1/4130049000000004802/learnt-count||10.52.219.152||10.52.219.152||499||-||-||0||-||getUserLearntCount
2020/08/04 21:56:03 +0800||5f2968f37ea82fda||GET /eculs/v1/4130049000000004802/learnt-count||10.52.219.152||10.52.219.152||501||-||-||0||-||getUserLearntCount
2020/08/04 21:56:10 +0800||5f2968fa13d62ef8||GET /eculs/v1/4130049000000004802/learnt-count||10.52.219.152||10.52.219.152||498||-||-||0||-||getUserLearntCount
2020/08/04 21:56:17 +0800||5f29690162f6c189||GET /eculs/v1/4130049000000004802/learnt-count||10.52.219.152||10.52.219.152||501||-||-||0||-||getUserLearntCount

**Comment by liyupeisleep** [comment]
负载均衡设置的权重策略。所以看着像负载均衡的策略，B实例怎么才能判断被隔离？

**Comment by liubao68** [comment]
实例被隔离会打印日志和[发送隔离事件](https://docs.servicecomb.io/java-chassis/zh_CN/general-development/AlarmEvent/)

有一定的请求到 B ， 我估计是因为 singleTestTime 的原因， 这个隔离时间较短， 5秒中可能尝试访问这个被隔离的实例一次。

**Comment by liyupeisleep** [comment]
> 实例被隔离会打印日志和[发送隔离事件](https://docs.servicecomb.io/java-chassis/zh_CN/general-development/AlarmEvent/)
> 
> 有一定的请求到 B ， 我估计是因为 singleTestTime 的原因， 这个隔离时间较短， 5秒中可能尝试访问这个被隔离的实例一次。

请问日志关键字是啥，我在消费端日志搜 isolation没结果

**Comment by liubao68** [comment]
```
        serverStats.markIsolated(true);
        eventBus.post(
            new IsolationServerEvent(invocation, instance, serverStats,
                settings, Type.OPEN, server.getEndpoint())); 
        LOGGER.warn("Isolate service {}'s instance {}.", invocation.getMicroserviceName(),
            instance.getInstanceId());
```

可以查看 IsolationDiscoveryFilter 的细节。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
