### ISSUE TITLE
RegistryUtils修改后不兼容旧版本

### ISSUE THREAD

**Issue by Matrix0xCC** [apache/servicecomb-java-chassis#1915]
这个是不兼容的修改？
修改之后`versionRule`被忽略了，为何不直接去掉这个参数？
这个类目前被业务使用，升级之后没有发现这个接口的功能变更，导致了一个问题。

_Originally posted by @Matrix0xCC in https://github.com/apache/servicecomb-java-chassis/pull/1600_

**Comment by liubao68** [comment]
你是从哪个版本升级到哪个版本？

**Comment by Matrix0xCC** [comment]
从1.3.0升级到2.0.1

> 你是从哪个版本升级到哪个版本？


旧版本逻辑如下

https://github.com/apache/servicecomb-java-chassis/blob/d59f2a6739de8a21d0db7f83bcd692389db2fcdf/service-registry/src/main/java/org/apache/servicecomb/serviceregistry/registry/AbstractServiceRegistry.java#L226-L250

新版本
https://github.com/apache/servicecomb-java-chassis/blob/ed0fe890e8e59dd97d96e9cbea76addc747d4e60/service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/RegistryUtils.java#L153-L163

**Comment by liubao68** [comment]
Fixed in 2.1.1
