### ISSUE TITLE
优雅停机能力

### ISSUE THREAD

**Issue by liukuancn** [apache/servicecomb-java-chassis#1918]
请问servicecomb有提供优雅停机的能力吗，即停机前不会接入新的微服务调用，但是要等业务处理完当前正在处理的业务再停机，多谢！

**Comment by yhs0092** [comment]
建议查看一下`SCBEngine#doDestroy`方法的代码，Java-Chassis 向 JVM 注册了 shutdown hook 来进行进程退出前的终止操作，称为 优雅停机。它基本符合你的描述。
如果你想要感知服务进程退出的并做一些自定义的操作的话，可以监听`BootListener`中定义的`BEFORE_CLOSE`事件。

PS：`SCBEngine#blockShutDownOperationForConsumerRefresh`方法可以在微服务进程退出时阻塞住退出线程一段时间，给 consumer 端实例留出从 sc 感知 provider 实例下线的时间。可以试用一下这个功能，看看是否适合你的部署场景。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
