### ISSUE TITLE
使用RestTemplate开发服务消费者，content-type如何设置成multipart/mixed; boundary=END_OF_PART

### ISSUE THREAD

**Issue by hongfeihuangseu** [apache/servicecomb-java-chassis#1926]
问题：使用RestTemplate开发服务消费者，content-type设置为multipart/mixed; boundary=END_OF_PART，最终传过来的值变为application/json，不符合预期。
现状：CSE的服务端的content-type目前只有 json/text/form几种，和契约保持一致。
诉求：使用RestTemplate开发服务消费者，content-type需要设置成multipart/mixed; boundary=END_OF_PART，有没有啥方法可以适配一下。

**Comment by liubao68** [comment]
能否具体描述下为什么这么使用？ 比如服务端的 service 接口是怎么定义的？ 采用这个 content-type 表达的 HTTP 映射语义是什么？

java-chassis 目前设计的主要是 json 语义，将 JAVA 对象 通过 jacskon 编码， 放到  body 参数 中。 不知道你这样使用是表达一个什么语义。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
