### ISSUE TITLE
请问熔断这里错误率统计是按照微服务还是单实例来统计的?

### ISSUE THREAD

**Issue by zhoudamin** [apache/servicecomb-java-chassis#1927]
超时等错误发生时，会抛出异常到cse拦截器，cse进行统计的时候：
1、是统计微服务该接口的总体请求错误率，达标后，对微服务该接口进行熔断？
2、还是按照每个实例单独统计，某个实例错误率达标后，该实例里面的接口熔断，但是其他实例的接口还能正常访问？这种情况可能是某个虚机网络问题，造成该虚机上的实例运行异常引发的。

**Comment by liubao68** [comment]
有针对方法的，有针对实例的机制。 具体情况不一样。 参考：

 https://docs.servicecomb.io/java-chassis/zh_CN/references-handlers/bizkeeper/

https://docs.servicecomb.io/java-chassis/zh_CN/references-handlers/loadbalance/

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
