### ISSUE TITLE
can registry-zero-config module use java NIO realize UDP server and client?

### ISSUE THREAD

**Issue by ctlove0523** [apache/servicecomb-java-chassis#1932]
current registry-zero-config module use java.net.MulticastSocket realize UDP server and client,can use java NIO to do that work.
This project accept PR？

**Comment by liubao68** [comment]
@jungan21

**Comment by jungan21** [comment]
Thx @ctlove0523 ! could you elaborate more ? especially, the benefits of NIO can bring.

**Comment by liubao68** [comment]
PR is welcome. I notice that you want to introduce new implementations, while registry-zero-config is used for small applications and the performance is not very important. So before you start, you need provide some improvements and details this PR will bring to this module. More implements could intruduce more code and complications.

**Comment by ctlove0523** [comment]
ok, understand
