### ISSUE TITLE
springboot外置tomcat，edge不能加载自定义dispatcher

### ISSUE THREAD

**Issue by lvvgang** [apache/servicecomb-java-chassis#1937]
![image](https://user-images.githubusercontent.com/50510955/92124888-e8cfe100-ee30-11ea-83ad-7060440068a6.png)
![image](https://user-images.githubusercontent.com/50510955/92124915-f4bba300-ee30-11ea-8294-1e6e077629b0.png)
![image](https://user-images.githubusercontent.com/50510955/92125007-0f8e1780-ee31-11ea-9909-d15ddcb28b21.png)

![image](https://user-images.githubusercontent.com/50510955/92125055-1d439d00-ee31-11ea-9ca1-6251c2840a01.png)

**Comment by yhs0092** [comment]
edge dispatcher扩展自`VertxHttpDispatcher`，这个是在 Rest over Vertx 传输模式下才会启用的。
把底层的HTTP服务器改为Tomcat的话自然就不能用上了。

**Comment by lvvgang** [comment]
如果底层的HTTP服务器为Tomcat，`Edge Service`就不能用了？

**Comment by lvvgang** [comment]
![image](https://user-images.githubusercontent.com/50510955/92345267-531ba680-f0fb-11ea-8530-ce65d3f9af02.png)

通过引入`standalone`依赖，可以使用`VertxHttpDispatcher`
