### ISSUE TITLE
resttemplate 跨应用调用，部分微服务实例请求不成功，返回500，提示服务不存在

### ISSUE THREAD

**Issue by lengshanwudi** [apache/servicecomb-java-chassis#1938]
app_id A 下的a服务，跨应用调用app_id B下的b服务和c服务，调用方式：
cse://B:b/**
cse://B:c/**
b和c均已注册服务成功，且可以正常接收和处理app_id B下的其它服务请求。

问题：cse://B:b/** 可以请求成功，cse://B:c/**请求不成功返回500,：
request process failed, response code:500, message:Probably invoke a service before it is registered, or no instance found for it, appId=SpeakerCloudzc, name=SpeakerCloudzc:alert-servcie, versionRule=0.0.0.0+.

**Comment by liubao68** [comment]
可以通过关键字 find instances 检查下查找实例是否成功

**Comment by lengshanwudi** [comment]
已解决，可以考虑排查一下三点：
1）服务是否开启微服务跨应用调用（allowCrossApp开关）：
service_description:
  properties:
    allowCrossApp: true
2）客户端配置修改后，需要同步升级服务端微服务版本号
3）确认应用名和微服务是否书写错误，很多笔误肉眼难以发现
