### ISSUE TITLE
chassis由2.0.1升级到2.1.0报错

### ISSUE THREAD

**Issue by lvvgang** [apache/servicecomb-java-chassis#1939]
#### 报错信息：
![Snipaste_2020-09-07_11-02-56](https://user-images.githubusercontent.com/50510955/92344940-4a76a080-f0fa-11ea-947b-48a966800d70.png)

#### 配置文件：
![image](https://user-images.githubusercontent.com/50510955/92345127-d983b880-f0fa-11ea-8de9-62c7e6fdc403.png)

**Comment by liubao68** [comment]
参考下升级指南。 需要引入 registry-service-center这个包。 2.1.1会打印根据确切的日志提示。

**Comment by lvvgang** [comment]
@liubao68 谢谢，已解决
