### ISSUE TITLE
SchemaTest调用失败，但是Postman可以

### ISSUE THREAD

**Issue by lvvgang** [apache/servicecomb-java-chassis#1941]
#### SchemaTest测试结果：
![image](https://user-images.githubusercontent.com/50510955/92424734-b703a500-f1b7-11ea-8364-72bd1cb24789.png)

#### Postman测试结果：
![image](https://user-images.githubusercontent.com/50510955/92424749-bf5be000-f1b7-11ea-87a2-18a6a1536c5f.png)

#### 代码
![image](https://user-images.githubusercontent.com/50510955/92424815-ec0ff780-f1b7-11ea-9070-19c447426849.png)

**Comment by liubao68** [comment]
响应里面有错误信息： no route to xxxx
服务中心的测试，会通过服务中心间接给微服务发送信息， 是否你的服务中心部署在不同网络环境下？ 建议你可以在 servicecomb-service-center咨询。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
