### ISSUE TITLE
消费者方，发生异常，提示 No available address found

### ISSUE THREAD

**Issue by yunhaijian** [apache/servicecomb-java-chassis#1942]
你好，我们现在存在两个微服务 A 和 B，它们互为消费者和提供者，现在 B 调用 A 的接口，可以调用成功。但是 A 调用 B 的接口时，发生异常，日志如下：

2020-09-07 21:49:39.205 [Timer-2] ERROR - [ExceptionUtils.java:createCseException:58] - [] - 
Exception: org.apache.servicecomb.core.exception.CseException; No available address found. microserviceName=***:******, version=0.0.0.0+, discoveryGroupName=0.0.0.0+/upInstances/0.0.7.0+/instancesAll/
ServiceDefinitionException Code:servicecomb.lb.no.available.address, Message:No available address found. microserviceName=***:******, version=0.0.0.0+, discoveryGroupName=0.0.0.0+/upInstances/0.0.7.0+/instancesAll/
	...

**Comment by liubao68** [comment]
可以通过 find instance 关键字看下 A 查询 B 的示例列表的时候，是否查询到实例信息。

**Comment by yunhaijian** [comment]
已解决，谢谢

**Comment by lqllyf** [comment]
请问你这个怎么解决的？我遇到了同样的问题
