### ISSUE TITLE
edge中的handler调用微服务失败

### ISSUE THREAD

**Issue by lvvgang** [apache/servicecomb-java-chassis#1943]
#### 代码
![image](https://user-images.githubusercontent.com/50510955/92443268-dd3f3a00-f1e3-11ea-9801-7d9e6f220c7b.png)

#### 报错信息
![image](https://user-images.githubusercontent.com/50510955/92443361-fd6ef900-f1e3-11ea-91cf-e239607093ba.png)

这个报错，与我用RestTemplate请求有关系吗？

**Comment by liubao68** [comment]
错误日志没有包含详细的错误原因， 不知道具体情况。 但是你的用法是错误的。 edge service默认是工作在 reacitve 模式， 即 Handler 的执行都是在 event-loop 线程。 这意味着不能执行任何阻塞操作。包括你写的 restTemplate.getForObject 就属于阻塞操作。 在 reactive 模式，使用阻塞操作容易导致超时、死锁等情况。 

Hanlder调用其他服务， 需要使用异步非阻塞的方式处理。 参考示例代码：

https://github.com/apache/servicecomb-fence/blob/master/api/edge-service/endpoint/src/main/java/org/apache/servicecomb/authentication/edge/AuthHandler.java

**Comment by lvvgang** [comment]
改成了异步方式，还是调不通，另提了一个isuue
