### ISSUE TITLE
edge的hander中调用微服务失败

### ISSUE THREAD

**Issue by lvvgang** [apache/servicecomb-java-chassis#1944]
#### 报错信息
![image](https://user-images.githubusercontent.com/50510955/92546749-df59d500-f285-11ea-8e5b-bb58d6f77d49.png)

![image](https://user-images.githubusercontent.com/50510955/92549501-fb607500-f28b-11ea-8e5e-6f02fa0bb2ec.png)

#### consumer代码
![image](https://user-images.githubusercontent.com/50510955/92546816-0ca68300-f286-11ea-9570-c9e1a0b42a37.png)

#### provider代码
![image](https://user-images.githubusercontent.com/50510955/92547162-e0d7cd00-f286-11ea-96df-791d2cef1b9e.png)

**Comment by liubao68** [comment]
ClassNotFound, NoSuchMethod 等异常， 意味着你的项目依赖可能有误。 比如servicecomb不同的模块的包的版本号不一样。 通常发生在修改依赖、升级等过程。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
