### ISSUE TITLE
servicecomb现在支持websocket接口吗？可以响应multipart格式吗？

### ISSUE THREAD

**Issue by kissLife** [apache/servicecomb-java-chassis#1954]
1. servicecomb现在支持开发websocket接口吗？
2. 有个项目从spring迁移到CSE，之前返回的响应格式为multipart格式，如下：
```
--boundary
Content-Disposition: form-data; name="first result"
Content-Type: application/json; charset=UTF-8
{ "hello": "first" }
--boundary
Content-Disposition: form-data; name="second result"
Content-Type: application/json; charset=UTF-8
{ "hello": "second" }
--boundary--
```
我修改了CSE接口定义，produces = MediaType.MULTIPART_FORM_DATA_VALUE，但是返回的时候还是 application/json，如下：
![image](https://user-images.githubusercontent.com/4749407/93161296-dca72600-f744-11ea-8f31-461184027913.png)
请求CSE现在支持这种multipart响应格式吗?

**Comment by liubao68** [comment]
对于 body 参数， java-chassis 只支持 json <-> java class 之间的映射和序列化和反序列化。 （对于 String 类型， 为了兼容，支持使用 text plain 的方式序列化和反序列化）。 java-chassis 不建议改变序列化方案， 因为 open API 没有针对接口单独说明序列化信息，不支持序列化定制，可以保留swagger接口语义的一致性。 

针对你的场景，可以考虑使用[上传、下载功能](https://docs.servicecomb.io/java-chassis/zh_CN/general-development/upload-download/)。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
