### ISSUE TITLE
cse接口调用请求参数中的int64位参数接收后变成了字符串

### ISSUE THREAD

**Issue by x00384074** [apache/servicecomb-java-chassis#1956]
cse接口调用请求参数中的int64位参数接收后变成了字符串：
请求参数是int64位整型，后端接口定义的是int64，接收到后变成了字符串

**Comment by liubao68** [comment]
你是如何使用的了？有示例代码吗？

手写 swagger， 然后通过 swagger 自动生成服务代码？
