### ISSUE TITLE
流下载超大文件速度很慢

### ISSUE THREAD

**Issue by TotoroChen** [apache/servicecomb-java-chassis#1958]
参考/slowInputStream，使用pipeInputStream实现zip包边压缩边下载的方式，但是下载太慢，有没加快下载的案例分享？
3G大小花了12分钟。

参考：
https://github.com/apache/servicecomb-java-chassis/blob/c4accb23c8246a842bce7d1a619b7f90135abfb0/integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/DownloadSchema.java

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
