### ISSUE TITLE
ExceptionToProducerResponseConverter为什么返回的是InvocationException的RuntimeException，有没有办法能继承Exception的自定义异常？

### ISSUE THREAD

**Issue by wang727955603** [apache/servicecomb-java-chassis#1965]

**Comment by liubao68** [comment]
不可以的。 java-chassis 的 RPC 层是语言无关的，没有类型信息。 出现错误的时候， 错误消息都通过 InvocationException 来表示。 参考错误处理： https://docs.servicecomb.io/java-chassis/zh_CN/general-development/error-handling/

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
