### ISSUE TITLE
2.1 中新特性 CommonHttpEdgeDispatcher 在CSE环境中报空指针异常

### ISSUE THREAD

**Issue by NoComments** [apache/servicecomb-java-chassis#1966]
CSE集成DarklaunchServerListFilter。且无法disable，工作时会因为找不到schema报空指针异常。
![image](https://user-images.githubusercontent.com/6245237/93956202-2e266500-fd84-11ea-8d55-f187209c492e.png)

**Comment by liubao68** [comment]
可以考虑在 pom 中排除 `cse-handler-cloud-extension` 的依赖来规避。

**Comment by liubao68** [comment]
fixed in 2.1.2
