### ISSUE TITLE
TooLongFrameException,message:HTTP header is larger than 32768 bytes 请教如何解决???

### ISSUE THREAD

**Issue by zhangaijing** [apache/servicecomb-java-chassis#1968]
org.apache.servicecomb.transport.rest.vertx.RestServerVerticle >> Unexpected error in server.cause:TooLongFrameException,message:HTTP header is larger than 32768 bytes.

**Comment by liubao68** [comment]
错误消息已经很明确了。 另外可以参考： https://docs.servicecomb.io/java-chassis/zh_CN/transports/rest-over-vertx/
查询配置信息。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
