### ISSUE TITLE
ServiceComb和CSE关系是什么，应该如何选择？

### ISSUE THREAD

**Issue by zhufeizzz** [apache/servicecomb-java-chassis#1970]
有没有文档介绍ServiceComb和CSE的关系？
1、功能差异。
2、代码同步策略，两边代码是完全独立维护还是有计划会定期同步，同步方向是什么？
3、兼容性如何，文档上都宣传ServiceComb可以接入CSE，但我看即使CSE最新的8.0版本也是基于ServiceComb 1.x的，在大版本差异的情况也保证兼容吗？
4、选择建议，是不是只要对接CSE就不推荐使用ServiceComb客户端？

**Comment by liubao68** [comment]
可以参考： https://support.huaweicloud.com/productdesc-servicestage/cse_productdesc_0008.html  的说明。
