### ISSUE TITLE
微服务CSE调用490报错，偶现原因确认。

### ISSUE THREAD

**Issue by myname00707** [apache/servicecomb-java-chassis#1971]
1，客户端调用服务端接口超时时间4.5s，客户端连接超时时间默认，30s，服务端连接超时时间默认，60s，微服务调用低概率报如下错误：
2020-09-23 10:11:04.493|[vert.x-eventloop-thread-4]|[ERROR]|[RestClientInvocation:]|Failed to send request, local:10.33.8.68:34698, remote:/10.31.15.138:8083.
io.vertx.core.VertxException: Connection was closed

客户端的metric日志，服务端没有收到请求：

```
2020-09-23 10:11:22.812|[spectator-poller-0]|[INFO ]|[DefaultLogPublisher:]|
os:
  cpu:
    all usage: 4.47%    all idle: 95.53%    process: 0.90%
  net:
    send(Bps)    recv(Bps)    send(pps)    recv(pps)    interface
    5.254K       5.229K       22           19           eth0
vertx:
  instances:
    name       eventLoopContext-created
    registry   0
    registry-watch 0
    transport  0
  transport:
    client.endpoints:
      connectCount disconnectCount queue         connections send(Bps) receive(Bps) remote
      3            2               0             3           6         100          10.31.15.199:7474
      3            1               0             4           208       82           10.33.8.228:8083
      3            1               0             3           197       68           10.33.8.139:8083
      2            1               0             3           135       50           10.33.168.151:8082
      2            0               0             4           202       57           10.31.19.112:8083
      0            0               0             0           0         0            10.33.168.40:8085
      3            2               0             3           201       55           10.31.15.138:8083
      1            0               0             3           135       40           10.33.8.216:8082
      2            3               0             2           102       32           10.31.19.202:8082
      3            1               0             4           6         100          10.33.8.10:7474
      3            3               0             3           135       57           10.31.15.110:8082
      2            1               0             3           5         75           10.33.8.222:7474
      4            2               0             4           6         100          10.31.15.211:7474
      31           17              0             39          1.313K    820          (summary)
    server.endpoints:
      connectCount disconnectCount rejectByLimit connections send(Bps) receive(Bps) listen
      12           9               0             15          182       529          10.33.8.68:8099
      12           9               0             15          182       529          (summary)
threadPool:
  coreSize maxThreads poolSize currentBusy rejected queueSize taskCount taskFinished name
  25       200        25       0           NaN      0         0.1       0.1          cse.executor.groupThreadPool-group1
  25       200        25       0           NaN      0         0.1       0.1          cse.executor.groupThreadPool-group0
consumer:
 simple:
  status      tps      latency            [0,1000) [1000,2000) [2000,3000) [3000,4000) [4000,)  operation
  rest.200    0.3      13.916/36.387      15       0           0           0           0        doNlu
              0.3      8.898/17.948       15       0           0           0           0        findDeviceInfoByKeys
              0.3      40.143/64.296      15       0           0           0           0        handleDialog
              0.8      20.986/64.296      45       0           0           0           0        (summary)
  rest.490    0.0      0.788/0.788        1        0           0           0           0        handleDialog
              0.0      0.788/0.788        1        0           0           0           0        (summary)
              0.0      0.000/0.000        0        0           0           0           0        (summary)
 details:
    rest.200:
      doNlu:
        prepare     : 0.004/0.008        handlersReq : 0.098/0.117        cFiltersReq: 0.035/0.048        sendReq     : 3.642/12.410
        getConnect  : 3.528/12.304       writeBuf    : 0.114/0.124        waitResp   : 10.091/34.637      wakeConsumer: 0.016/0.019
        cFiltersResp: 0.022/0.026        handlersResp: 0.006/0.013
      findDeviceInfoByKeys:
        prepare     : 0.003/0.007        handlersReq : 0.082/0.096        cFiltersReq: 0.014/0.019        sendReq     : 4.984/11.360
        getConnect  : 4.920/11.297       writeBuf    : 0.064/0.071        waitResp   : 3.771/6.465        wakeConsumer: 0.017/0.025
        cFiltersResp: 0.022/0.026        handlersResp: 0.005/0.013
      handleDialog:
        prepare     : 0.004/0.014        handlersReq : 0.080/0.096        cFiltersReq: 0.042/0.049        sendReq     : 3.889/9.272
        getConnect  : 3.773/9.154        writeBuf    : 0.116/0.146        waitResp   : 36.049/61.935      wakeConsumer: 0.017/0.021
        cFiltersResp: 0.055/0.066        handlersResp: 0.008/0.023
    rest.490:
      handleDialog:
        prepare     : 0.003/0.003        handlersReq : 0.099/0.099        cFiltersReq: 0.043/0.043        sendReq     : 0.254/0.254
        getConnect  : 0.040/0.040        writeBuf    : 0.214/0.214        waitResp   : 0.223/0.223        wakeConsumer: 0.001/0.001
        cFiltersResp: 0.001/0.001        handlersResp: 0.164/0.164
    rest.408:
producer:
 simple:
  status      tps      latency            [0,1000) [1000,2000) [2000,3000) [3000,4000) [4000,)  operation
  rest.200    0.3      71.894/99.427      15       0           0           0           0        event
              0.3      71.894/99.427      15       0           0           0           0        (summary)
              0.0      0.000/0.000        0        0           0           0           0        (summary)
 details:
    rest.200:
      event:
        prepare: 0.017/0.028        queue       : 0.040/0.053        filtersReq : 0.557/0.600        handlersReq: 0.041/0.044
        execute: 71.201/98.716      handlersResp: 0.008/0.010        filtersResp: 0.019/0.021        sendResp   : 0.010/0.013
    rest.400:

```

**Comment by liubao68** [comment]
通过这个日志没法直接定位原因。 从 handleDialog  的执行情况看， 有成功也有失败， 成功的时候， waitResp 时延比较高， 有可能和这个服务的负载比较高有关系， 可以观察下这个服务的负载情况。

**Comment by myname00707** [comment]
服务侧的metric日志，服务端的负载也不大：
2020-09-23 10:11:40.952|[spectator-poller-0]|[INFO ]|[DefaultLogPublisher:]|
os:
  cpu:
    all usage: 2.46%    all idle: 97.54%    process: 3.22%
  net:
    send(Bps)    recv(Bps)    send(pps)    recv(pps)    interface
    9.485K       7.808K       53           65           eth0
vertx:
  instances:
    name       eventLoopContext-created
    registry   0
    registry-watch 0
    transport  0
  transport:
    client.endpoints:
      connectCount disconnectCount queue         connections send(Bps) receive(Bps) remote
      2            2               0             3           6         100          10.31.15.199:7474
      0            0               0             0           0         0            10.31.17.15:8086
      0            0               0             0           0         0            10.33.8.163:8085
      0            1               0             0           0         0            10.33.8.37:8086
      0            0               0             0           0         0            10.33.168.40:8085
      0            0               0             0           0         0            10.31.15.103:8086
      0            0               0             0           0         0            10.31.15.58:8085
      7            0               0             7           0         17           10.31.15.195:8086
      4            3               0             4           6         100          10.33.8.10:7474
      0            0               0             0           0         0            10.31.19.153:8085
      1            3               0             2           5         75           10.33.8.222:7474
      0            0               0             0           0         0            10.31.17.77:8086
      0            0               0             0           0         0            10.33.8.17:8086
      2            1               0             4           6         100          10.31.15.211:7474
      16           10              0             20          25        393          (summary)
    server.endpoints:
      connectCount disconnectCount rejectByLimit connections send(Bps) receive(Bps) listen
      10           8               0             13          313       778          10.31.15.138:8083
      10           8               0             13          313       778          (summary)
threadPool:
  coreSize maxThreads poolSize currentBusy rejected queueSize taskCount taskFinished name
  25       200        25       0           NaN      0         0.1       0.1          cse.executor.groupThreadPool-group1
  25       200        25       0           NaN      0         0.1       0.1          cse.executor.groupThreadPool-group0
consumer:
 simple:
  status      tps      latency            [0,1000) [1000,2000) [2000,3000) [3000,4000) [4000,)  operation
  rest.200    0.3      3.196/5.785        15       0           0           0           0        getmatchname
              0.3      11.148/41.397      15       0           0           0           0        app-service.app-server.findDeviceInfoByKeys
              0.5      7.172/41.397       30       0           0           0           0        (summary)
 details:
    rest.200:
      getmatchname:
        prepare     : 0.008/0.018        handlersReq : 0.367/0.467        cFiltersReq: 0.019/0.028        sendReq     : 1.406/2.466
        getConnect  : 1.338/2.404        writeBuf    : 0.068/0.086        waitResp   : 1.290/3.010        wakeConsumer: 0.028/0.038
        cFiltersResp: 0.058/0.075        handlersResp: 0.021/0.035
      findDeviceInfoByKeys:
        prepare     : 0.008/0.010        handlersReq : 0.191/0.249        cFiltersReq: 0.045/0.055        sendReq     : 7.445/37.424
        getConnect  : 7.361/37.355       writeBuf    : 0.085/0.114        waitResp   : 3.324/6.885        wakeConsumer: 0.033/0.041
        cFiltersResp: 0.073/0.091        handlersResp: 0.029/0.044
producer:
 simple:
  status      tps      latency            [0,1000) [1000,2000) [2000,3000) [3000,4000) [4000,)  operation
  rest.200    0.3      19.607/50.135      15       0           0           0           0        internal-dialogmgr-service.dialogMgr.handleDialog
              0.3      19.607/50.135      15       0           0           0           0        (summary)
 details:
    rest.200:
      handleDialog:
        prepare: 0.053/0.068        queue       : 0.104/0.141        filtersReq : 0.383/0.487        handlersReq: 0.161/0.200
        execute: 18.307/48.857      handlersResp: 0.023/0.026        filtersResp: 0.533/1.570        sendResp   : 0.019/0.022

**Comment by myname00707** [comment]
> 通过这个日志没法直接定位原因。 从 handleDialog 的执行情况看， 有成功也有失败， 成功的时候， waitResp 时延比较高， 有可能和这个服务的负载比较高有关系， 可以观察下这个服务的负载情况。

**Comment by liubao68** [comment]
如果服务端负载不高， 则可能是网络问题了。 这类问题需要长期观察下。 单纯从日志无法识别问题原因。

**Comment by myname00707** [comment]
> 1，客户端调用服务端接口超时时间4.5s，客户端连接超时时间默认，30s，服务端连接超时时间默认，60s，微服务调用低概率报如下错误：
> 2020-09-23 10:11:04.493|[vert.x-eventloop-thread-4]|[ERROR]|[RestClientInvocation:]|Failed to send request, local:10.33.8.68:34698, remote:/10.31.15.138:8083.
> io.vertx.core.VertxException: Connection was closed
> 
> 客户端的metric日志，服务端没有收到请求：
> 
> ```
> 2020-09-23 10:11:22.812|[spectator-poller-0]|[INFO ]|[DefaultLogPublisher:]|
> os:
>   cpu:
>     all usage: 4.47%    all idle: 95.53%    process: 0.90%
>   net:
>     send(Bps)    recv(Bps)    send(pps)    recv(pps)    interface
>     5.254K       5.229K       22           19           eth0
> vertx:
>   instances:
>     name       eventLoopContext-created
>     registry   0
>     registry-watch 0
>     transport  0
>   transport:
>     client.endpoints:
>       connectCount disconnectCount queue         connections send(Bps) receive(Bps) remote
>       3            2               0             3           6         100          10.31.15.199:7474
>       3            1               0             4           208       82           10.33.8.228:8083
>       3            1               0             3           197       68           10.33.8.139:8083
>       2            1               0             3           135       50           10.33.168.151:8082
>       2            0               0             4           202       57           10.31.19.112:8083
>       0            0               0             0           0         0            10.33.168.40:8085
>       3            2               0             3           201       55           10.31.15.138:8083
>       1            0               0             3           135       40           10.33.8.216:8082
>       2            3               0             2           102       32           10.31.19.202:8082
>       3            1               0             4           6         100          10.33.8.10:7474
>       3            3               0             3           135       57           10.31.15.110:8082
>       2            1               0             3           5         75           10.33.8.222:7474
>       4            2               0             4           6         100          10.31.15.211:7474
>       31           17              0             39          1.313K    820          (summary)
>     server.endpoints:
>       connectCount disconnectCount rejectByLimit connections send(Bps) receive(Bps) listen
>       12           9               0             15          182       529          10.33.8.68:8099
>       12           9               0             15          182       529          (summary)
> threadPool:
>   coreSize maxThreads poolSize currentBusy rejected queueSize taskCount taskFinished name
>   25       200        25       0           NaN      0         0.1       0.1          cse.executor.groupThreadPool-group1
>   25       200        25       0           NaN      0         0.1       0.1          cse.executor.groupThreadPool-group0
> consumer:
>  simple:
>   status      tps      latency            [0,1000) [1000,2000) [2000,3000) [3000,4000) [4000,)  operation
>   rest.200    0.3      13.916/36.387      15       0           0           0           0        doNlu
>               0.3      8.898/17.948       15       0           0           0           0        findDeviceInfoByKeys
>               0.3      40.143/64.296      15       0           0           0           0        handleDialog
>               0.8      20.986/64.296      45       0           0           0           0        (summary)
>   rest.490    0.0      0.788/0.788        1        0           0           0           0        handleDialog
>               0.0      0.788/0.788        1        0           0           0           0        (summary)
>               0.0      0.000/0.000        0        0           0           0           0        (summary)
>  details:
>     rest.200:
>       doNlu:
>         prepare     : 0.004/0.008        handlersReq : 0.098/0.117        cFiltersReq: 0.035/0.048        sendReq     : 3.642/12.410
>         getConnect  : 3.528/12.304       writeBuf    : 0.114/0.124        waitResp   : 10.091/34.637      wakeConsumer: 0.016/0.019
>         cFiltersResp: 0.022/0.026        handlersResp: 0.006/0.013
>       findDeviceInfoByKeys:
>         prepare     : 0.003/0.007        handlersReq : 0.082/0.096        cFiltersReq: 0.014/0.019        sendReq     : 4.984/11.360
>         getConnect  : 4.920/11.297       writeBuf    : 0.064/0.071        waitResp   : 3.771/6.465        wakeConsumer: 0.017/0.025
>         cFiltersResp: 0.022/0.026        handlersResp: 0.005/0.013
>       handleDialog:
>         prepare     : 0.004/0.014        handlersReq : 0.080/0.096        cFiltersReq: 0.042/0.049        sendReq     : 3.889/9.272
>         getConnect  : 3.773/9.154        writeBuf    : 0.116/0.146        waitResp   : 36.049/61.935      wakeConsumer: 0.017/0.021
>         cFiltersResp: 0.055/0.066        handlersResp: 0.008/0.023
>     rest.490:
>       handleDialog:
>         prepare     : 0.003/0.003        handlersReq : 0.099/0.099        cFiltersReq: 0.043/0.043        sendReq     : 0.254/0.254
>         getConnect  : 0.040/0.040        writeBuf    : 0.214/0.214        waitResp   : 0.223/0.223        wakeConsumer: 0.001/0.001
>         cFiltersResp: 0.001/0.001        handlersResp: 0.164/0.164
>     rest.408:
> producer:
>  simple:
>   status      tps      latency            [0,1000) [1000,2000) [2000,3000) [3000,4000) [4000,)  operation
>   rest.200    0.3      71.894/99.427      15       0           0           0           0        event
>               0.3      71.894/99.427      15       0           0           0           0        (summary)
>               0.0      0.000/0.000        0        0           0           0           0        (summary)
>  details:
>     rest.200:
>       event:
>         prepare: 0.017/0.028        queue       : 0.040/0.053        filtersReq : 0.557/0.600        handlersReq: 0.041/0.044
>         execute: 71.201/98.716      handlersResp: 0.008/0.010        filtersResp: 0.019/0.021        sendResp   : 0.010/0.013
>     rest.400:
> ```

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
