### ISSUE TITLE
CSE跨域注册调用找不到新增接口，报404错误 （locate path failed, status:"NOT_FOUND"）

### ISSUE THREAD

**Issue by xiaoyuer11** [apache/servicecomb-java-chassis#1974]
Region R1服务S1版本1.1.X，Region R2服务S1版本1.2.X。R1 Region中S1的是新版本服务，有新增接口API1，当R1 Region服务S2去调用R1 Region的S1新增接口API1，会报404。

**Comment by liubao68** [comment]
按照接口兼容规则， 1.2.x 在 1.1.x 基础上可以新增接口。 你的操作不太符合这个规则， 怎么会 1.1.x 在 1.2.x 上面新增接口了？ 是删除了接口？
