### ISSUE TITLE
rpc调用如何指定一个服务的访问地址

### ISSUE THREAD

**Issue by huanghezhen** [apache/servicecomb-java-chassis#1976]
背景: 开发环境下 一个服务需要访问另外两个服务,这两个服务不想在本地启动,想直接连接测试环境

请问如何实现?

**Comment by liubao68** [comment]
可以考虑使用 Endpoint ： https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/context-param/
或者本地注册： https://docs.servicecomb.io/java-chassis/zh_CN/registry/local-registry/
