### ISSUE TITLE
2.1.0版本 文件下载服务提供者 FilePart.setDeleteAfterFinished(true)未生效

### ISSUE THREAD

**Issue by SenixCoder** [apache/servicecomb-java-chassis#1979]
- 文件下载Provider，代码参照demo示例写的：
`return new FilePart(null, zipFile).setDeleteAfterFinished(true).setSubmittedFileName(zipFile.getName());`

- Debug到org.apache.servicecomb.foundation.vertx.http.StandardHttpServletResponseEx#sendPart，发现方法中Context context = Vertx.currentContext(); 获取到的context为空

- context为空后，在PumpFromPart.toOutputStream中走了toOutputStreamSync逻辑，导致Provider端文件没有被删除

- 想知道为什么context为null，以及怎么能够使setDeleteAfterFinished正确的触发

**Comment by liubao68** [comment]
我写了一个测试， https://github.com/apache/servicecomb-java-chassis/pull/1993

没有复现你的问题。 你可以写一个复现的 DEMO 吗？

**Comment by SenixCoder** [comment]
项目使用的是tomcat，在tomcat容器下，setDeleteAfterFinished(true)不生效，我稍后提交一份merge。

**Comment by liubao68** [comment]
Fixed in this PR https://github.com/apache/servicecomb-java-chassis/pull/2241
