### ISSUE TITLE
CSE管理节点存在访问外部域名的情况

### ISSUE THREAD

**Issue by demonbug** [apache/servicecomb-java-chassis#1981]
从DNS解析日志中发现，部署configcenter/consolewebsite/dashboardservice/governanceservice/servicecenter的主机，存在持续解析cfe-apiserver.cfe、cluster-manager.cfe两个域名的情况，近一个月解析了20次，请问访问这两个域名的目的是什么？

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
