### ISSUE TITLE
提个需求：通过spring xml方式<cse:rpc-schema schema-id ...>发布服务时，支持只发布interface的方法为服务接口

### ISSUE THREAD

**Issue by zhoutianli518** [apache/servicecomb-java-chassis#1982]
通过@RestSchema注解方法发布服务时，2.1.1版本开始支持只发布interface的方法为服务接口。通过ServiceComb的官方指导可以知道有这个特性。
https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/use-interface/

但通过spring xml方式<cse:rpc-schema schema-id ...>发布时，目前是不支持的。从org.apache.servicecomb.provider.pojo.schema.SchemaDefParser类的doParse方法实现可以看出来。

  @Override
  protected void doParse(Element element, ParserContext parserContext,
      BeanDefinitionBuilder builder) {
    builder.addPropertyValue(PojoConst.FIELD_SCHEMA_ID, element.getAttribute(PojoConst.SCHEMA_ID));
    builder.addPropertyValue(PojoConst.IMPL, element.getAttribute(PojoConst.IMPL));
  }

能否为cse:rpc-schema配置增加一个schemaInterface 的属性，让其和@RestSchema注解一样，也可以指定只发布interface的方法为服务接口呢？

**Comment by liubao68** [comment]
很好的建议，下个版本安排计划

**Comment by liubao68** [comment]
https://github.com/apache/servicecomb-java-chassis/pull/1995

**Comment by liubao68** [comment]
fixed in 2.1.2
