### ISSUE TITLE
No Schema Found

### ISSUE THREAD

**Issue by twilight0620** [apache/servicecomb-java-chassis#1983]
项目之前有过schema，后来改了url，service center中的schema是空了，已经配置了@RestSchema(schemaId = "testTask")，为什么schema出不来？？

**Comment by sxcooler** [comment]
遇到同样的问题，而且meta-data里能看到schema列表，但是schema这一栏就是No Schema Found

**Comment by liubao68** [comment]
1. 确定下 service-center 用的版本， 或者下载地址。
2. 看下微服务启动日志，是否注册schema有失败。 
3. 试试删除注册中心的微服务信息，重启下微服务试试。

**Comment by sxcooler** [comment]
> 1. 确定下 service-center 用的版本， 或者下载地址。
> 2. 看下微服务启动日志，是否注册schema有失败。
> 3. 试试删除注册中心的微服务信息，重启下微服务试试。

1. 下载地址是
https://servicecomb.apache.org/release/service-center-downloads/

2. 应该没有
![image](https://user-images.githubusercontent.com/3192045/134447494-4db66939-c832-4284-9107-0db07843a801.png)
![image](https://user-images.githubusercontent.com/3192045/134447509-d5f66267-cb30-4a29-ba7f-f988d0f15074.png)
![image](https://user-images.githubusercontent.com/3192045/134447553-c21223dd-9d00-492b-b296-945006e3faa7.png)

3. 我甚至把sc目录下的data目录都删了都不行

**Comment by liubao68** [comment]
@sxcooler  你的问题应该是 service-center 2.0.0 的bug， 可以在 https://github.com/apache/servicecomb-service-center/issues  提交一个 issue。 

原始问题和你这应该没有关系。 我先把问题关闭了。 如果有新问题，可以新建一个 issue。
