### ISSUE TITLE
缺少直接注册服务的API，是必须使用swagger对象么？

### ISSUE THREAD

**Issue by cherohey** [apache/servicecomb-java-chassis#1984]
.

**Comment by hityc2019** [comment]
Service Center提供了注册服务的API，可参考https://github.com/apache/servicecomb-service-center/blob/master/server/core/swagger/v4.yaml

**Comment by liubao68** [comment]
可以参考：
https://github.com/apache/servicecomb-java-chassis/blob/master/inspector/src/main/java/org/apache/servicecomb/inspector/internal/InspectorBootListener.java

https://github.com/apache/servicecomb-java-chassis/blob/master/providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/schema/PojoProducers.java

**Comment by cherohey** [comment]
thanks
