### ISSUE TITLE
求助：Jackson @JsonProperty注解未生效

### ISSUE THREAD

**Issue by rianepeny** [apache/servicecomb-java-chassis#1988]
代码：
`
@Setter
@Getter
public class GetUserInfoResult {
    private String resultCode = "0";

    @JsonProperty("GetUserInfoRsp")
    private GetUserInfoRsp getUserInfoRsp;
}
`

返回的Json还是小写
` 
{
        "resultCode": "0",
        "**getUserInfoRsp**": {
            "version": "50000",
            "traceFlag": "0"
        }
}
`

**Comment by liubao68** [comment]
看下 import 的类属于哪个 package? 是不是package不对?

**Comment by rianepeny** [comment]
> 看下 import 的类属于哪个 package? 是不是package不对?

我引用的包名是：com.fasterxml.jackson.annotation.JsonProperty

**Comment by liubao68** [comment]
那么需要你提供一个简单的重现 DEMO 了， 我查询了 java-chassis 的自动化测试用例， 有涵盖这方面的测试。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
