### ISSUE TITLE
1.3版本怎么升级到2.11以上？另外如果以前是老系统改造的很多springmvc注解都用不了了。如：@RequestBody

### ISSUE THREAD

**Issue by myVictor** [apache/servicecomb-java-chassis#1989]
我是老系统改造上来的，目前底座版本是1.3。

maven配置：
<dependency>
			<groupId>org.apache.servicecomb</groupId>
			<artifactId>spring-boot-starter-provider</artifactId>
			<version>1.3.0</version>
		</dependency>

		<dependency>
			<groupId>org.apache.servicecomb</groupId>
			<artifactId>handler-bizkeeper</artifactId>
			<version>1.3.0</version>
			<exclusions>
				<exclusion>
					<groupId>org.apache.servicecomb</groupId>
					<artifactId>common-javassist</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.apache.servicecomb</groupId>
			<artifactId>handler-tracing-zipkin</artifactId>
			<version>1.3.0</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.servicecomb</groupId>
			<artifactId>handler-loadbalance</artifactId>
			<version>1.3.0</version>
		</dependency>

		<dependency>
			<groupId>org.apache.servicecomb</groupId>
			<artifactId>handler-flowcontrol-qps</artifactId>
			<version>1.3.0</version>
		</dependency>

升级2.1.1后报错，报错：

17:47:17,691 |-INFO in ch.qos.logback.classic.joran.action.ContextNameAction - Setting logger context name as [logs]
17:47:17,789 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
17:47:17,803 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
17:47:17,977 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
17:47:17,992 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
17:47:18,021 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1923598304 - No compression will be used
17:47:18,027 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1923598304 - Will use the pattern /opt/logs/tuokeCustmLogs/output.%d{yyyy-MM-dd}.log for the active file
17:47:18,046 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern '/opt/logs/tuokeCustmLogs/output.%d{yyyy-MM-dd}.log'.
17:47:18,048 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
17:47:18,065 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Sun Oct 11 17:47:18 CST 2020
17:47:18,072 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: /opt/logs/tuokeCustmLogs/output.2020-10-11.log
17:47:18,073 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [null]
17:47:18,078 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
17:47:18,079 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ERROR_FILE]
17:47:18,082 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1668016508 - No compression will be used
17:47:18,083 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1668016508 - Will use the pattern /opt/logs/tuokeCustmLogs/error.%d{yyyy-MM-dd}.log for the active file
17:47:18,087 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern '/opt/logs/tuokeCustmLogs/error.%d{yyyy-MM-dd}.log'.
17:47:18,087 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
17:47:18,089 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Sun Oct 11 17:47:18 CST 2020
17:47:18,105 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ERROR_FILE] - Active log file name: /opt/logs/tuokeCustmLogs/error.2020-10-11.log
17:47:18,105 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ERROR_FILE] - File property is set to [null]
17:47:18,106 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
17:47:18,107 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [SYNC_FILE]
17:47:18,110 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1254344205 - No compression will be used
17:47:18,111 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1254344205 - Will use the pattern /opt/logs/tuokeCustmLogs/sync.%d{yyyy-MM-dd}.log for the active file
17:47:18,114 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern '/opt/logs/tuokeCustmLogs/sync.%d{yyyy-MM-dd}.log'.
17:47:18,114 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
17:47:18,116 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Sun Oct 11 17:47:18 CST 2020
17:47:18,121 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[SYNC_FILE] - Active log file name: /opt/logs/tuokeCustmLogs/sync.2020-10-11.log
17:47:18,121 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[SYNC_FILE] - File property is set to [null]
17:47:18,125 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [log.sync] to DEBUG
17:47:18,126 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [SYNC_FILE] to Logger[log.sync]
17:47:18,130 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.apache.ibatis] to TRACE
17:47:18,131 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [java.sql.Connection] to DEBUG
17:47:18,131 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [java.sql.Statement] to DEBUG
17:47:18,132 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [java.sql.PreparedStatement] to DEBUG
17:47:18,132 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.springframework] to ERROR
17:47:18,133 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.mybatis] to ERROR
17:47:18,133 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.atomikos] to ERROR
17:47:18,133 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.camel] to ERROR
17:47:18,134 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [net.sf] to ERROR
17:47:18,134 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache] to ERROR
17:47:18,134 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.hibernate] to ERROR
17:47:18,135 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.quartz] to ERROR
17:47:18,135 |-INFO in ch.qos.logback.classic.joran.action.LevelAction - ROOT level set to ERROR
17:47:18,136 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
17:47:18,136 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ERROR_FILE] to Logger[ROOT]
17:47:18,136 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
17:47:18,139 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@72f926e6 - Registering current configuration as safe fallback point
17:47:20,860 |-INFO in ch.qos.logback.classic.joran.action.ContextNameAction - Setting logger context name as [logs]
17:47:20,860 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
17:47:20,860 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
17:47:20,865 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
17:47:20,865 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
17:47:20,869 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@53940034 - No compression will be used
17:47:20,870 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@53940034 - Will use the pattern /opt/logs/tuokeCustmLogs/output.%d{yyyy-MM-dd}.log for the active file
17:47:20,873 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern '/opt/logs/tuokeCustmLogs/output.%d{yyyy-MM-dd}.log'.
17:47:20,873 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
17:47:20,875 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Sun Oct 11 17:47:20 CST 2020
17:47:20,879 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: /opt/logs/tuokeCustmLogs/output.2020-10-11.log
17:47:20,879 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [null]
17:47:20,880 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
17:47:20,880 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ERROR_FILE]
17:47:20,883 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1616359099 - No compression will be used
17:47:20,884 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1616359099 - Will use the pattern /opt/logs/tuokeCustmLogs/error.%d{yyyy-MM-dd}.log for the active file
17:47:20,932 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern '/opt/logs/tuokeCustmLogs/error.%d{yyyy-MM-dd}.log'.
17:47:20,933 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
17:47:20,936 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Sun Oct 11 17:47:20 CST 2020
17:47:20,947 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ERROR_FILE] - Active log file name: /opt/logs/tuokeCustmLogs/error.2020-10-11.log
17:47:20,948 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ERROR_FILE] - File property is set to [null]
17:47:20,948 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
17:47:20,949 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [SYNC_FILE]
17:47:20,952 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1676605578 - No compression will be used
17:47:20,953 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1676605578 - Will use the pattern /opt/logs/tuokeCustmLogs/sync.%d{yyyy-MM-dd}.log for the active file
17:47:20,955 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern '/opt/logs/tuokeCustmLogs/sync.%d{yyyy-MM-dd}.log'.
17:47:20,955 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
17:47:20,956 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Sun Oct 11 17:47:20 CST 2020
17:47:20,960 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[SYNC_FILE] - Active log file name: /opt/logs/tuokeCustmLogs/sync.2020-10-11.log
17:47:20,960 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[SYNC_FILE] - File property is set to [null]
17:47:20,961 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [log.sync] to DEBUG
17:47:20,961 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@53251a66 - Propagating DEBUG level on Logger[log.sync] onto the JUL framework
17:47:20,964 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [SYNC_FILE] to Logger[log.sync]
17:47:20,964 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.apache.ibatis] to TRACE
17:47:20,964 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@53251a66 - Propagating TRACE level on Logger[com.apache.ibatis] onto the JUL framework
17:47:20,965 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [java.sql.Connection] to DEBUG
17:47:20,965 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@53251a66 - Propagating DEBUG level on Logger[java.sql.Connection] onto the JUL framework
17:47:20,966 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [java.sql.Statement] to DEBUG
17:47:20,966 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@53251a66 - Propagating DEBUG level on Logger[java.sql.Statement] onto the JUL framework
17:47:20,966 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [java.sql.PreparedStatement] to DEBUG
17:47:20,966 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@53251a66 - Propagating DEBUG level on Logger[java.sql.PreparedStatement] onto the JUL framework
17:47:20,967 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.springframework] to ERROR
17:47:20,967 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@53251a66 - Propagating ERROR level on Logger[org.springframework] onto the JUL framework
17:47:20,968 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.mybatis] to ERROR
17:47:20,968 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@53251a66 - Propagating ERROR level on Logger[org.mybatis] onto the JUL framework
17:47:20,968 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.atomikos] to ERROR
17:47:20,968 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@53251a66 - Propagating ERROR level on Logger[com.atomikos] onto the JUL framework
17:47:20,969 |-WARN in Logger[org.hibernate.validator.internal.engine.resolver.TraversableResolvers] - No appenders present in context [logs] for logger [org.hibernate.validator.internal.engine.resolver.TraversableResolvers].
17:47:20,969 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.camel] to ERROR
17:47:20,969 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@53251a66 - Propagating ERROR level on Logger[org.apache.camel] onto the JUL framework
17:47:20,969 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [net.sf] to ERROR
17:47:20,970 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@53251a66 - Propagating ERROR level on Logger[net.sf] onto the JUL framework
17:47:20,970 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache] to ERROR
17:47:20,970 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@53251a66 - Propagating ERROR level on Logger[org.apache] onto the JUL framework
17:47:20,971 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.hibernate] to ERROR
17:47:20,972 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@53251a66 - Propagating ERROR level on Logger[org.hibernate] onto the JUL framework
17:47:20,972 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.quartz] to ERROR
17:47:20,973 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@53251a66 - Propagating ERROR level on Logger[org.quartz] onto the JUL framework
17:47:20,973 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@53251a66 - Propagating ERROR level on Logger[ROOT] onto the JUL framework
17:47:20,973 |-INFO in ch.qos.logback.classic.joran.action.LevelAction - ROOT level set to ERROR
17:47:20,974 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
17:47:20,974 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ERROR_FILE] to Logger[ROOT]
17:47:20,974 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
17:47:20,975 |-INFO in org.springframework.boot.logging.logback.SpringBootJoranConfigurator@71e693fa - Registering current configuration as safe fallback point

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.2.RELEASE)

2020-10-11  17:47:28.958 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from URL [jar:file:/D:/mysolution/maven/apache-maven-3.2.1/repo1/org/apache/servicecomb/java-chassis-core/2.1.1/java-chassis-core-2.1.1.jar!/META-INF/spring/cse.bean.xml]; nested exception is org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'serviceCombSpringConfiguration' for bean class [org.apache.servicecomb.springboot.starter.provider.ServiceCombSpringConfiguration] conflicts with existing, non-compatible bean definition of same name and class [org.apache.servicecomb.springboot2.starter.ServiceCombSpringConfiguration]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:420)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:337)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:305)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:188)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:224)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:195)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.lambda$loadBeanDefinitionsFromImportedResources$0(ConfigurationClassBeanDefinitionReader.java:358)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsFromImportedResources(ConfigurationClassBeanDefinitionReader.java:325)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:144)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:117)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:327)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:232)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:705)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at com.cz073586.tuokeandroid.TuoKeCustApplication.main(TuoKeCustApplication.java:23)
Caused by: org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'serviceCombSpringConfiguration' for bean class [org.apache.servicecomb.springboot.starter.provider.ServiceCombSpringConfiguration] conflicts with existing, non-compatible bean definition of same name and class [org.apache.servicecomb.springboot2.starter.ServiceCombSpringConfiguration]
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.checkCandidate(ClassPathBeanDefinitionScanner.java:348)
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:286)
	at org.springframework.context.annotation.ComponentScanBeanDefinitionParser.parse(ComponentScanBeanDefinitionParser.java:90)
	at org.springframework.beans.factory.xml.NamespaceHandlerSupport.parse(NamespaceHandlerSupport.java:74)
	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1391)
	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1371)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:179)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.doRegisterBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:149)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:96)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(XmlBeanDefinitionReader.java:514)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:394)
	... 23 common frames omitted

**Comment by liubao68** [comment]
可以参考： https://docs.servicecomb.io/java-chassis/zh_CN/using-java-chassis-in-spring-boot/components-for-spring-boot/

了解 sprint boot starter 的变化， 这里也提供了例子： https://github.com/apache/servicecomb-samples/tree/master/porter_springboot
