### ISSUE TITLE
AbstractTransport AbstractVerticle继承使用指南

### ISSUE THREAD

**Issue by neverstop** [apache/servicecomb-java-chassis#1992]
请问 AbstractTransport AbstractVerticle继承使用指南 在哪里找到

**Comment by liubao68** [comment]
这块没有使用指南。涉及这块的扩展比较复杂， 需要了解 servicecomb 的实现细节， 建议深入理解 servicecomb 后操作。

**Comment by xhanthow** [comment]
最近也在看相关的知识，以下是我的理解：
`AbstractVerticle`这个就是`vertx`中提供给我们来继承实现`Verticle`的，这个直接看`vertx`的官方文档就行了，有很多例子。这个`AbstractTransport`就需要打断点更下`servicecomb`的代码了，主要用来实例化`transport`类型的`Verticle`，具体来说包括`http1.1`（客户端）、`http2`（客户端）和服务端这3个`Verticle`，这3类`Verticle`对应的`vertx`实例都是同一个。

**Comment by liubao68** [comment]
> 最近也在看相关的知识，以下是我的理解：
> `AbstractVerticle`这个就是`vertx`中提供给我们来继承实现`Verticle`的，这个直接看`vertx`的官方文档就行了，有很多例子。这个`AbstractTransport`就需要打断点更下`servicecomb`的代码了，主要用来实例化`transport`类型的`Verticle`，具体来说包括`http1.1`（客户端）、`http2`（客户端）和服务端这3个`Verticle`，这3类`Verticle`对应的`vertx`实例都是同一个。

不错的建议，熟悉 servicecomb 的使用， 需要从学习 vert.x 开始，这样理解就简单了。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
