### ISSUE TITLE
sdk包从2.3.35替换到2.5.0后出现Connection reset by peer

### ISSUE THREAD

**Issue by kzhuangfeilong** [apache/servicecomb-java-chassis#1998]
现在知道是ELB健康检查引起的，现在除了屏蔽健康检查，还有其他方式能解决吗，这个报的是error错误，影响后续查询业务日志的错误

**Comment by liubao68** [comment]
你也可以看下打印日志的 logger, 不输出该 logger 的日志。 不过这样的话，其他错误也打印不出来了。
