### ISSUE TITLE
期望使用调用第三方REST服务的能力，能够对302响应做处理？

### ISSUE THREAD

**Issue by Wangren725** [apache/servicecomb-java-chassis#1999]
尝试使用如下方式将第三方REST服务注册为一个服务然后使用rpc调用：
```java
    @POST
    @Path("/rest.php")
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = String.class),
            @ApiResponse(code = 302, message = "location", responseHeaders = {@ResponseHeader(name = "location", response = String.class)})
    })
    CompletableFuture<ResponseEntity<String>> verify(xxx);
```
但是调用结果是一个异常，且响应体为null（可能是因为响应体本身为空）。
是否有方法能够让rpc调用获取到location头的优雅方法？

**Comment by liubao68** [comment]
你这里定义的是 consumer  interface 吗？ 一个 RPC interface， 只能有一个返回值类型。 java-chassis 使用 InvocationException 表示其他类型的返回值类型。 参考：http://localhost:8000/general-development/error-handling/

**Comment by liubao68** [comment]
不过目前 InvocationException 只支持从 body 获取 errorData， 无法获取到 302 错误码里面的 header location。 暂时无法满足你的场景需求。

**Comment by liubao68** [comment]
另外， 302 是一个特殊的错误码， 表示重定向。 有两个处理策略：
1. follow redirect， 业务不需要再接口定义中声明 302 错误码， http 层会进行重定向， 并获取最终结果。 
2. 直接处理。 目前 java-chassis 的方式。 接口声明 302 错误码， 业务获取到 errorcode 和 location， 自己做后续处理。 
你们期望的是那种方式了？

**Comment by Wangren725** [comment]
我们的当前的场景是方式2：业务获取到httpcode和location自己处理

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
