### ISSUE TITLE
servicecomb微服务验证客户端证书是否被吊销，如果吊销有没有钩子或者回调可以捕获到这个错误，有没有相应的可以自定义处理的扩展类

### ISSUE THREAD

**Issue by liuguangrong** [apache/servicecomb-java-chassis#2002]

**Comment by liubao68** [comment]
没有了。 证书被吊销会抛出 `throw new CertificateException("certificate revoked");` 异常。 但是这个异常也是 JDK 底层处理的， 并不会将异常直接返回给业务（可能 cause 里面有，需要测试。）

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
