### ISSUE TITLE
配置中心读取失败

### ISSUE THREAD

**Issue by holdyou01** [apache/servicecomb-java-chassis#2003]
微服务使用的servicecomb从1.2.0.B017升级到2.0.1后.无法在公有云上注册，后分析发现：微服务在本地CSE也无法读取配置中心内容。是不是servicecomb升级后需要更改哪里的配置才能读取配置中心内容？

**Comment by liubao68** [comment]
没碰到类似问题。 需要提供下具体错误和更加详细的错误描述。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
