### ISSUE TITLE
cse整合springboot1.5版本，启动报错，ServiceCombSpringConfiguration 出现bean重复

### ISSUE THREAD

**Issue by xuleixie** [apache/servicecomb-java-chassis#2004]
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method setCseApplicationListener in org.apache.servicecomb.springboot.starter.provider.ServiceCombSpringConfiguration required a single bean, but 2 were found:
	- org.apache.servicecomb.core.CseApplicationListener#0: defined in URL [jar:file:/D:/local-repository/org/apache/servicecomb/java-chassis-core/1.1.0.B028/java-chassis-core-1.1.0.B028.jar!/META-INF/spring/cse.bean.xml]
	- org.apache.servicecomb.core.CseApplicationListener#1: defined in URL [jar:file:/D:/local-repository/org/apache/servicecomb/java-chassis-core/1.1.0.B028/java-chassis-core-1.1.0.B028.jar!/META-INF/spring/cse.bean.xml]

Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed

Disconnected from the target VM, address: '127.0.0.1:65520', transport: 'socket'

Process finished with exit code 130

**Comment by liubao68** [comment]
你可以提供下重现demo， 或者描述下使用场景。 这个问题通常是配置不正确，导致了 bean 被加载了两次。

**Comment by xuleixie** [comment]
好的，感谢大佬，最后我们项目组要求不能整合spring boot，所以就没这么搭了...

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
