### ISSUE TITLE
自定义负载均衡策略，注册事件回调，收到服务变更后，通过ILoadBalancer对象的loadBalancer.getReachableServers()方法拿到的信息和实际状态不相符

### ISSUE THREAD

**Issue by csuyinwei** [apache/servicecomb-java-chassis#2008]
ILoadBalancer loadBalancer = springClientFactory.getLoadBalancer(serviceId);
SortedMap<Integer, Server> serverSortedMap = hashKey(loadBalancer.getReachableServers().stream().filter(Server::isAlive).collect(Collectors.toList()));
        for (Map.Entry<Integer, Server> entry : serverSortedMap.entrySet()) {
            Server v = entry.getValue();
            log.info("{}:{}",entry.getKey(),v.getHostPort());
        }

**Comment by csuyinwei** [comment]
1、滚动升级场景，容器化部署，服务实例IP变化，收到事件通知，查询到的还是原来的实例信息
2、服务实例1个场景先，服务从上线->下线状态改变，查询到的信息为1；下线->上线状态改变，查询到的信息为0

**Comment by liubao68** [comment]
你这个代码貌似是 spring cloud 代码， 不属于 java chassiss。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
