### ISSUE TITLE
responseEntity不支持image/jpeg

### ISSUE THREAD

**Issue by ZhuZiQing1** [apache/servicecomb-java-chassis#2016]
获取验证码图片接口，ResponseEntity contentType设置为image/jpeg，收到响应自动会转成json并且body为空

**Comment by liubao68** [comment]
servicecomb 实现的是 REST rpc， 编码都是 json。 使用图片，可以考虑上传下载： https://docs.servicecomb.io/java-chassis/zh_CN/general-development/upload-download/

**Comment by wujimin** [comment]
可以补充一下，如果要在浏览器中直接显示，而不是被浏览器处理为下载，需要将Content-Disposition设置为inline，而不是attachment  
当然这个信息，不是ServiceComb特有的

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.

**Comment by ZhuZiQing1** [comment]
你好，邮件已收到，我会尽快查看，谢谢！                                                      十方の彩
