### ISSUE TITLE
The  help document should prompt developers to be careful about implementing the "beforeSendResponse" method in "HttpServerFilter"

### ISSUE THREAD

**Issue by johnyannj** [apache/servicecomb-java-chassis#2022]
The  help document should prompt developers to be careful about implementing the "beforeSendResponse" method in "HttpServerFilter"

The “beforeSendResponse” may be invoked in the business thread or in the EventLoop thread, even if you use synchronous programming mode.

The help document should clearly point out these contents and remind developers not to make mistakes.

**Comment by liubao68** [comment]
Fixed in https://docs.servicecomb.io/java-chassis/zh_CN/general-development/http-filter/
