### ISSUE TITLE
request.getLocale()方法不支持

### ISSUE THREAD

**Issue by huang-xg** [apache/servicecomb-java-chassis#2029]
使用何种方法替代

**Comment by liubao68** [comment]
是否支持取决于运行环境。 如果运行环境是 j2EE (servlet， 比如 tomcat等）， 这个方法是支持的。 如果运行环境是轻量级 HTTP 环境 (比如 java chassis 默认的基于 vert.x 的 HTTP 环境） ， 这个方法是不支持的。 

参考[说明文档](https://docs.servicecomb.io/java-chassis/zh_CN/transports/rest-over-servlet/)

**Comment by wujimin** [comment]
我现在的项目是自行从header里取Accept-Language再计算的  
看来应该PR上来，实现getLocale

**Comment by VTracyHuang** [comment]
你解决了吗?

**Comment by wujimin** [comment]
我解决了，不过很快又废弃不用了  
因为我们项目的规范修改了，要求后端不做国际化，由前端做

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
