### ISSUE TITLE
vert.x 升级到3.9.4服务ServiceRegistry报错

### ISSUE THREAD

**Issue by Neverstop** [apache/servicecomb-java-chassis#2037]
ServiceRegistryClientImpl:710]|watcher handle microservice 9e40a74d9a6990f527b17ff0e57e9ea468676a3d response failed,

buffer是空的，没有打印出来，也不影响正常业务。 
请问这个watcher是和服务中心交互什么？

**Comment by liubao68** [comment]
是和服务中心的 websocket 连接，用于实例变更推送。 因为 pull 模式也是开启的，所以即使打印错误日志也不影响功能。 
需要看下service-center是否开启 websocket。客户端也可以增加配置项关闭。

**Comment by Neverstop** [comment]
vert.x回退到3.8版本就ok， 所以service-center是开启了 websocket的。
顺便请教下 客户端如何关闭 实例变更推送？

**Comment by Neverstop** [comment]
> 是和服务中心的 websocket 连接，用于实例变更推送。 因为 pull 模式也是开启的，所以即使打印错误日志也不影响功能。
> 需要看下service-center是否开启 websocket。客户端也可以增加配置项关闭。

vert.x回退到3.8版本就ok， 所以service-center是开启了 websocket的。
顺便请教下 客户端如何关闭 实例变更推送？

**Comment by liubao68** [comment]
参考[这里的配置](https://docs.servicecomb.io/java-chassis/zh_CN/registry/introduction/)。  目前还未验证 vert.x 3.9.x 版本， 有可能新版本有变更。 以前升级 vert.x 的时候， 也总是有些小变更影响功能的需要适配。

**Comment by Neverstop** [comment]
> 参考[这里的配置](https://docs.servicecomb.io/java-chassis/zh_CN/registry/introduction/)。 目前还未验证 vert.x 3.9.x 版本， 有可能新版本有变更。 以前升级 vert.x 的时候， 也总是有些小变更影响功能的需要适配。

好的 谢谢

**Comment by liubao68** [comment]
fixed in 2.1.3
