### ISSUE TITLE
使用tomcat启动war包，无法加载servicecomb

### ISSUE THREAD

**Issue by cherohey** [apache/servicecomb-java-chassis#2038]
使用spring boot能够启动项目。

**Comment by liubao68** [comment]
你没有提供任何信息， 不好回答。 可以先参考下这里的[例子](https://github.com/apache/servicecomb-samples/tree/master/java-chassis-deployment-samples) 和 [文档](https://docs.servicecomb.io/java-chassis/zh_CN/transports/rest-over-servlet/)

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
