### ISSUE TITLE
使用Nacos如何使用多个配置文件

### ISSUE THREAD

**Issue by cmkcmk181** [apache/servicecomb-java-chassis#2040]
在spring cloud中可以使用spring.cloud.nacos.config.shared-configs属性来配置多个文件，
在servicecomb中应该如何设置？

**Comment by liubao68** [comment]
目前的扩展只支持一个 dataId和groupId。 参考[开发指南](https://docs.servicecomb.io/java-chassis/zh_CN/config/general-config/)

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
