### ISSUE TITLE
@GET请求not allow complex type for query parameter

### ISSUE THREAD

**Issue by TCsteven** [apache/servicecomb-java-chassis#2044]
GET请求，入参的（@BeanParam A类）中有List属性，报错not allow complex type for query parameter

**Comment by liubao68** [comment]
可以贴一下具体的代码吗？

**Comment by liubao68** [comment]
fixed in https://github.com/apache/servicecomb-java-chassis/pull/1969/files and available in 2.1.1

**Comment by TCsteven** [comment]
使用3.1.5版本，这个问题解决了，谢谢解答

**Comment by TCsteven** [comment]
使用3.1.5版本，这个问题解决了
