### ISSUE TITLE
使用skywalking监控servicecomb的调用链，可以监控，但是没有输入和输出，现象正常么？

### ISSUE THREAD

**Issue by cherohey** [apache/servicecomb-java-chassis#2048]
springcloud能够正常显示输入输出。

**Comment by liubao68** [comment]
skywalking 我没使用过，不是很清楚它的工作原理。 servicecomb 的 RPC 处理过程和 spring cloud 是完全不一样的，估计skywalking 依赖于某些运行机制。 

采用搜索引擎找了些资料， 貌似 skywalking 针对 servicecomb 做个单独的扩展， 你可以查询下相关材料， 或者也可以去 skywolking 社区提问。

**Comment by wujimin** [comment]
印象里skywalking也是处理的字节码  
也许是对接点的类改变了  
最好使用servicecomb publish的事件来对接，会比较稳定

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
