### ISSUE TITLE
提一个优化需求：是否可以提供客户端异常处理的SPI机制？

### ISSUE THREAD

**Issue by zhoutianli518** [apache/servicecomb-java-chassis#2051]
目前服务提供方报异常后，不管报什么异常，到客户端后都变成了InvocationException运行期异常。是否可以增加客户端异常处理的SPI机制，由客户端实现SPI接口，捕获到异常后，客户端可以根据自己的需要做一些定制处理呢？

**Comment by liubao68** [comment]
按照 java-chasiss 的设计约束， 是不能将服务端的异常序列化返回给 client 的。 比较推荐的做法是服务端捕获异常，然后返回合理的错误码和错误消息。 详细参考[异常处理](https://docs.servicecomb.io/java-chassis/zh_CN/general-development/error-handling/)。

**Comment by zhoutianli518** [comment]
不是将服务端的异常序列化带回给client，我的意思是能否在客户端侧增加SPI，可以由客户端控制抛出的异常，这样，客户端可以定制抛出的异常。而不是只能由sdk固定抛出InvocationException。
sdk里的invoker使用的动态代理InvocationHandler，其invoke方法是可以抛出任何异常，是否可以放开一个口子，让业务定制抛出的异常实例呢？

**Comment by wujimin** [comment]
按原来的设计，服务要扩展，是改变InvocationException中的error data，而不是改变InvocationException，可以考虑一下这个能否满足

**Comment by zhoutianli518** [comment]
@wujimin 场景是这样的：
我们微服务框架从dubbo切到cse。我们使用dubbo好多年了。当前服务提供方通过自定义的异常将错误码和错误描述带给客户端。采用抛异常方式中断异常流程，保持主流程代码整洁。使用CSE后，在服务端，我们实现ExceptionToProducerResponseConverter扩展点，将服务端的异常信息通过error data带回给客户端。在客户端，因为没有扩展机制，拿到的都是InvocationException。如果客户端也能提供一个异常处理的SPI机制，我们实现这个SPI接口后，将InvocationException里的error data解析一下，换成业务自定义的异常抛出去，那么基本上能实现dubbo到cse的平滑切换，上层业务无感知。

**Comment by wujimin** [comment]
明白了  
基于现有版本，一个可能的快速规避方案如下  
你看一下是否ok：  
* 继承Invoker定制自己的逻辑  
```java
public class MyInvoker extend Invoker {
  public static <T> T createProxy(......) {
    ......
  }

  @Override
  public Object invoke(Object proxy, Method method, Object[] args) {
    try {
      super.invoke(proxy, method, args);
    } catch (Throwable e) {
      你们的转换逻辑

      这样处理，只搞定了同步调用，如果想异步也搞定，可以分别override syncInvoke和completableFutureInvoke  
      其中completableFutureInvoke不仅仅需要catch，还需要订阅future的结果做异常转换    
    }
  }
}
```
* 如何使用新invoker  
```java
@Configuration
public class ConsumerConfiguration {
  @Bean
  MyConsumerInterface myConsumerInterface() {
    return MyInvoker.createProxy(......);
  }
}
```
  
# 缺点  
syncInvoke和completableFutureInvoke是实现级的，不一定稳定，后续如果有变化，你们的代码需要同步跟着变一下

**Comment by wujimin** [comment]
更正式的方案，是使用`org.apache.servicecomb.core.exception.ExceptionConverter`  
但是：  
* producer流程已经提交，还未启用  
* consumer流程还没提交

**Comment by zhoutianli518** [comment]
客户端，使用如下方式调用服务端的接口
<cse:rpc-reference id="xxx" ..../>

客户端生成的动态代理，从源码PojoReferenceMeta类的实现来看，是写死使用Invoker.createProxy创建的，业务自定义的MyInvoker 没法生效吧。

  @Override
  public void afterPropertiesSet() {
    if (consumerIntf == null) {
      throw new ServiceCombException(
          String.format(
              "microserviceName=%s, schemaid=%s, \n"
                  + "do not support implicit interface anymore, \n"
                  + "because that caused problems:\n"
                  + "  1.the startup process relies on other microservices\n"
                  + "  2.cyclic dependent microservices can not be deployed\n"
                  + "suggest to use @RpcReference or "
                  + "<cse:rpc-reference id=\"...\" microservice-name=\"...\" schema-id=\"...\" interface=\"...\"></cse:rpc-reference>.",
              microserviceName,
              schemaId));
    }

    proxy = Invoker.createProxy(microserviceName, schemaId, consumerIntf);
  }

**Comment by wujimin** [comment]
![image](https://user-images.githubusercontent.com/16874843/99935226-31959700-2d9b-11eb-933c-ff6a5feaa92e.png)  
不使用xml方式，直接使用api，并通过@Bean发布为bean

**Comment by zhoutianli518** [comment]
明白你的意思了。通过@bean注解，业务直接构造要调用的接口的动态代理，而动态代理的实现就是业务自定义的MyInvoker（继承原Invoker ，覆写invoker方法）。 

如果不想用@bean注解，用xml配置bean，可以类似这么用

定义一个FactoryBean实现
public class CseReferenceBean implements FactoryBean<Object> {

    protected Class<?> intf;

    public void setIntf(Class<?> intf) {
      this.intf = intf;
    }

    @Override
    public Class<?> getObjectType() {
        return intf;
    }
    
    @Override
    public Object getObject() throws Exception {
         return MyInvoker.createProxy(......); //返回自定义的代理实现
    }
}

xml bean如此定义即可。

	<bean class="com.xxx.CseReferenceBean">
		<property name="intf" value="com.xxx.MyConsumerInterface"/>
	</bean>

**Comment by wujimin** [comment]
是的，:+1:

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
