### ISSUE TITLE
开启TLS认证后，消费端报错connection timed out

### ISSUE THREAD

**Issue by Eyekneemm** [apache/servicecomb-java-chassis#2053]
A开启TLS，rest监听的地址：rest://xx.xx.xx.xx:28443?sslEnabled=true，模式：rest on vertx；
B未开启TLS，rest监听地址：rest://xx.xx.xx.xx:28080?urlPrefix=xxxx，模式rest on servlet；

两端的ssl配置：
```
ssl.protocols=TLSv1.2
ssl.authPeer=false
ssl.ciphers=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
ssl.trustStore=xxx.keystore
ssl.trustStoreType=JKS
ssl.keyStore=xxxx.keystore
ssl.keyStoreType=JKS
ssl.sslCustomClass=com.demo.SslCustom

```
现象：A调用B正常，B调用A报错：connection timed out
当A注册时启用后TLS分两种情况：
1. 在IDEA中通过tomcat直接部署war包，互相调用成功
2. 将war包上传到linux 集成环境，B调用A报connection timed out
不启用TLS时，集成环境亦可用

**Comment by liubao68** [comment]
connection timed out一般是网络不可达， 和 TLS 关系不大。

**Comment by Eyekneemm** [comment]
> connection timed out一般是网络不可达， 和 TLS 关系不大。

更换端口成功了，不知道为什么；就28443端口不行，观察了环境也无占用。
好在问题解决了，非常感谢！
