### ISSUE TITLE
不能这么写吗？ 里面没有model,还是报错Caused by: org.apache.servicecomb.foundation.common.exceptions.ServiceCombException: [simple type, class java.util.function.Supplier] is interface. Must be a concrete type.

### ISSUE THREAD

**Issue by VTracyHuang** [apache/servicecomb-java-chassis#2055]
@ApiOperation(value = "下载导入模板")
    @GetMapping("/action/exportTempalte")
    public ResponseEntity<String> exportExcelTempalte(HttpServletResponse response){
        try{
            //Resource目录中的文件
            String filePath = "/excels/讲师新增模板.xlsx";
            ClassPathResource classPathResource = new ClassPathResource(filePath);
            Workbook workbook= WorkbookFactory.create(classPathResource.getInputStream());
            ExcelUtil.downLoadExcel("讲师新增模板.xlsx", response, workbook);
        }catch (Exception e){
            e.printStackTrace();
            logger.error("文件下载失败,msg{}",e.getMessage());
        }
        return ResponseEntity.ok("success");
    }

**Comment by liubao68** [comment]
不可以的。 参考[开发指南](https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/interface-constraints/)的说明， HttpServlepResponse 不能作为请求参数。 

[上传下载文件参考](https://docs.servicecomb.io/java-chassis/zh_CN/general-development/upload-download/)
[spring mvc 和 servicecomb 的差异](https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/springmvc/)
