### ISSUE TITLE
IllegalStateException: defined 4 body parameter

### ISSUE THREAD

**Issue by HoyerIsAlexander** [apache/servicecomb-java-chassis#2057]
GET接口请求类存在多层继承关系时，请求类使用@BeaParam注解，具体字段使用@QueryParam注解，父类中的字段没有使用@QueryParam注解，启动时会报这个错；CSE版本3.1.5，ServiceComb版本2.1.2，之前的CSE2.5.x版本中不存在这个问题，这种如何解决？

**Comment by liubao68** [comment]
2.1.2 是最新版本， 你是说最新版本没问题吗？ 你当前的版本是什么？ 是否可以考虑升级？

**Comment by HoyerIsAlexander** [comment]
2.1.2 版本报的这个问题，之前是1.3.0版本使用@BeanParam注解不存在这个问题

**Comment by liubao68** [comment]
你能提供一下接口原型定义吗？

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
