### ISSUE TITLE
上传文件的参数

### ISSUE THREAD

**Issue by VTracyHuang** [apache/servicecomb-java-chassis#2058]
@ApiOperation(value = "批量导入导师")
    @PostMapping(path = "/action/uploadLectures" , produces = MediaType.TEXT_PLAIN_VALUE,consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    public ResponseEntity<String> upload(@RequestPart(name = "file")MultipartFile file) {

        try {
            InputStream in = file.getInputStream();
            EasyExcel.read(in, LecturerModel.class,new ExcelListener()).sheet().doRead();
        } catch (IOException e) {
            e.printStackTrace();
            return ResponseEntity.ok("failed");
        }

        return ResponseEntity.ok("success");
    }

我用postman发请求
![image](https://user-images.githubusercontent.com/54627411/99148927-ac88ee80-26c5-11eb-855e-28406109e0d1.png)

报错
org.apache.servicecomb.swagger.invocation.exception.InvocationException: InvocationException: code=400;msg=CommonExceptionData [message=Parameter is not valid for operation [course-learning.lecturer-manage.upload]. Parameter is [file]. Processor is [formData].]

**Comment by VTracyHuang** [comment]
![image](https://user-images.githubusercontent.com/54627411/99148950-d3472500-26c5-11eb-9be6-11ff4095e1df.png)

**Comment by liubao68** [comment]
我自己测试了下，没有发现问题。 你用的哪个版本？能否提供一个重现的 DEMO ？


BTW: 使用 ResponseEntity ， 需要指定类型， 比如  ResponseEntity<String> 

我的接口定义：

```
  @PostMapping(path = "/upload", produces = MediaType.TEXT_PLAIN_VALUE)
  public String uploadFile(@RequestPart(name = "fileName") MultipartFile file) {
      return fileService.uploadFile(file);
  }
```

生成的 swagger :

```
  /upload:
    post:
      operationId: "uploadFile"
      consumes:
      - "multipart/form-data"
      produces:
      - "text/plain"
      parameters:
      - name: "fileName"
        in: "formData"
        required: true
        type: "file"
      responses:
        "200":
          description: "response of 200"
          schema:
            type: "string"
```

**Comment by VTracyHuang** [comment]
关于上传这个是需要在cse里面配文件上传路径吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/servicecomb-java-chassis"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月16日(星期一) 晚上6:53
收件人:&nbsp;"apache/servicecomb-java-chassis"<servicecomb-java-chassis@noreply.github.com&gt;;
抄送:&nbsp;"ICON"<861522731@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/servicecomb-java-chassis] 上传文件的参数 (#2058)





 
我自己测试了下，没有发现问题。 你用的哪个版本？能否提供一个重现的 DEMO ？
 
BTW: 使用 ResponseEntity ， 需要指定类型， 比如  ResponseEntity
 
我的接口定义：
   @PostMapping(path = "/upload", produces = MediaType.TEXT_PLAIN_VALUE)   public String uploadFile(@RequestPart(name = "fileName") MultipartFile file) {       return fileService.uploadFile(file);   }  
生成的 swagger :
   /upload:     post:       operationId: "uploadFile"       consumes:       - "multipart/form-data"       produces:       - "text/plain"       parameters:       - name: "fileName"         in: "formData"         required: true         type: "file"       responses:         "200":           description: "response of 200"           schema:             type: "string"

**Comment by VTracyHuang** [comment]
请求参数不能是List吗?


Caused by: java.lang.IllegalStateException: not allow complex type for query parameter, type=java.util.List.







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/servicecomb-java-chassis"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月16日(星期一) 晚上6:53
收件人:&nbsp;"apache/servicecomb-java-chassis"<servicecomb-java-chassis@noreply.github.com&gt;;
抄送:&nbsp;"ICON"<861522731@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/servicecomb-java-chassis] 上传文件的参数 (#2058)





 
我自己测试了下，没有发现问题。 你用的哪个版本？能否提供一个重现的 DEMO ？
 
BTW: 使用 ResponseEntity ， 需要指定类型， 比如  ResponseEntity
 
我的接口定义：
   @PostMapping(path = "/upload", produces = MediaType.TEXT_PLAIN_VALUE)   public String uploadFile(@RequestPart(name = "fileName") MultipartFile file) {       return fileService.uploadFile(file);   }  
生成的 swagger :
   /upload:     post:       operationId: "uploadFile"       consumes:       - "multipart/form-data"       produces:       - "text/plain"       parameters:       - name: "fileName"         in: "formData"         required: true         type: "file"       responses:         "200":           description: "response of 200"           schema:             type: "string"

**Comment by liubao68** [comment]
> 请求参数不能是List吗? Caused by: java.lang.IllegalStateException: not allow complex type for query parameter, type=java.util.List.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "apache/servicecomb-java-chassis" <notifications@github.com&gt;; 发送时间:&nbsp;2020年11月16日(星期一) 晚上6:53 收件人:&nbsp;"apache/servicecomb-java-chassis"<servicecomb-java-chassis@noreply.github.com&gt;; 抄送:&nbsp;"ICON"<861522731@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [apache/servicecomb-java-chassis] 上传文件的参数 (#2058) 我自己测试了下，没有发现问题。 你用的哪个版本？能否提供一个重现的 DEMO ？ BTW: 使用 ResponseEntity ， 需要指定类型， 比如 ResponseEntity 我的接口定义： @PostMapping(path = "/upload", produces = MediaType.TEXT_PLAIN_VALUE) public String uploadFile(@RequestPart(name = "fileName") MultipartFile file) { return fileService.uploadFile(file); } 生成的 swagger : /upload: post: operationId: "uploadFile" consumes: - "multipart/form-data" produces: - "text/plain" parameters: - name: "fileName" in: "formData" required: true type: "file" responses: "200": description: "response of 200" schema: type: "string" — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

要的, 必须配置 `servicecomb.uploads.directory` 参考： https://docs.servicecomb.io/java-chassis/zh_CN/general-development/file-upload/

**Comment by liubao68** [comment]
> 请求参数不能是List吗? Caused by: java.lang.IllegalStateException: not allow complex type for query parameter, type=java.util.List.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "apache/servicecomb-java-chassis" <notifications@github.com&gt;; 发送时间:&nbsp;2020年11月16日(星期一) 晚上6:53 收件人:&nbsp;"apache/servicecomb-java-chassis"<servicecomb-java-chassis@noreply.github.com&gt;; 抄送:&nbsp;"ICON"<861522731@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [apache/servicecomb-java-chassis] 上传文件的参数 (#2058) 我自己测试了下，没有发现问题。 你用的哪个版本？能否提供一个重现的 DEMO ？ BTW: 使用 ResponseEntity ， 需要指定类型， 比如 ResponseEntity 我的接口定义： @PostMapping(path = "/upload", produces = MediaType.TEXT_PLAIN_VALUE) public String uploadFile(@RequestPart(name = "fileName") MultipartFile file) { return fileService.uploadFile(file); } 生成的 swagger : /upload: post: operationId: "uploadFile" consumes: - "multipart/form-data" produces: - "text/plain" parameters: - name: "fileName" in: "formData" required: true type: "file" responses: "200": description: "response of 200" schema: type: "string" — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

使用 query 参数的时候， 如果一个 key 存在多个 value， 参考下面的方法：

```
  // query array
  @Path("queryArr")
  @GET
  public String queryArr(@QueryParam("queryArr") String[] queryArr) {
    return Arrays.toString(queryArr) + queryArr.length;
  }

  @Path("queryArrCSV")
  @GET
  public String queryArrCSV(@ApiParam(collectionFormat = "csv") @QueryParam("queryArr") String[] queryArr) {
    return Arrays.toString(queryArr) + queryArr.length;
  }

  @Path("queryArrSSV")
  @GET
  public String queryArrSSV(@ApiParam(collectionFormat = "ssv") @QueryParam("queryArr") String[] queryArr) {
    return Arrays.toString(queryArr) + queryArr.length;
  }

  @Path("queryArrTSV")
  @GET
  public String queryArrTSV(@ApiParam(collectionFormat = "tsv") @QueryParam("queryArr") String[] queryArr) {
    return Arrays.toString(queryArr) + queryArr.length;
  }

  @Path("queryArrPIPES")
  @GET
  public String queryArrPIPES(@ApiParam(collectionFormat = "pipes") @QueryParam("queryArr") String[] queryArr) {
    return Arrays.toString(queryArr) + queryArr.length;
  }

  @Path("queryArrMULTI")
  @GET
  public String queryArrMULTI(@ApiParam(collectionFormat = "multi") @QueryParam("queryArr") String[] queryArr) {
    return Arrays.toString(queryArr) + queryArr.length;
  }
```

**Comment by VTracyHuang** [comment]
还有就是
public class SyncUserLikeTagsRequest {

    private Long userId;

    private String userName;

    private Map<Integer,String&gt; userTagsList;
}
做请求参数的时候也会报错Map的key 期望是一个String  而不是Integer



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "bao liu"<notifications@github.com&gt;; 
发送时间: 2020年11月18日(星期三) 下午4:59
收件人: "apache/servicecomb-java-chassis"<servicecomb-java-chassis@noreply.github.com&gt;; 
抄送: "ICON"<861522731@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [apache/servicecomb-java-chassis] 上传文件的参数 (#2058)





  
请求参数不能是List吗? Caused by: java.lang.IllegalStateException: not allow complex type for query parameter, type=java.util.List.
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "apache/servicecomb-java-chassis" <notifications@github.com&gt;; 发送时间:&nbsp;2020年11月16日(星期一) 晚上6:53 收件人:&nbsp;"apache/servicecomb-java-chassis"<servicecomb-java-chassis@noreply.github.com&gt;; 抄送:&nbsp;"ICON"<861522731@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [apache/servicecomb-java-chassis] 上传文件的参数 (#2058) 我自己测试了下，没有发现问题。 你用的哪个版本？能否提供一个重现的 DEMO ？ BTW: 使用 ResponseEntity ， 需要指定类型， 比如 ResponseEntity 我的接口定义： @PostMapping(path = "/upload", produces = MediaType.TEXT_PLAIN_VALUE) public String uploadFile(@RequestPart(name = "fileName") MultipartFile file) { return fileService.uploadFile(file); } 生成的 swagger : /upload: post: operationId: "uploadFile" consumes: - "multipart/form-data" produces: - "text/plain" parameters: - name: "fileName" in: "formData" required: true type: "file" responses: "200": description: "response of 200" schema: type: "string" — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
使用 query 参数的时候， 如果一个 key 存在多个 value， 参考下面的方法：
   // query array   @Path("queryArr")   @GET   public String queryArr(@QueryParam("queryArr") String[] queryArr) {     return Arrays.toString(queryArr) + queryArr.length;   }   @Path("queryArrCSV")   @GET   public String queryArrCSV(@ApiParam(collectionFormat = "csv") @QueryParam("queryArr") String[] queryArr) {     return Arrays.toString(queryArr) + queryArr.length;   }   @Path("queryArrSSV")   @GET   public String queryArrSSV(@ApiParam(collectionFormat = "ssv") @QueryParam("queryArr") String[] queryArr) {     return Arrays.toString(queryArr) + queryArr.length;   }   @Path("queryArrTSV")   @GET   public String queryArrTSV(@ApiParam(collectionFormat = "tsv") @QueryParam("queryArr") String[] queryArr) {     return Arrays.toString(queryArr) + queryArr.length;   }   @Path("queryArrPIPES")   @GET   public String queryArrPIPES(@ApiParam(collectionFormat = "pipes") @QueryParam("queryArr") String[] queryArr) {     return Arrays.toString(queryArr) + queryArr.length;   }   @Path("queryArrMULTI")   @GET   public String queryArrMULTI(@ApiParam(collectionFormat = "multi") @QueryParam("queryArr") String[] queryArr) {     return Arrays.toString(queryArr) + queryArr.length;   }

**Comment by liubao68** [comment]
Map 必需 key-value 都是 string， 参考 [类型说明](https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/interface-constraints/)

**Comment by VTracyHuang** [comment]
还有就是下载文件的时候，如果出现错误信息，怎么把错误信息返给前端
public Resource exportExcelTempalte() throws IOException {
    logger.info("=========== 下载导入模板接口调用开始 ================" );

    try{
        // ClassPathResource类的构造方法接收路径名称，自动去classpath路径下找文件
        ClassPathResource classPathResource = new ClassPathResource("/office/讲师新增模板.xlsx");
        // 获得File对象，当然也可以获取输入流对象
        File file = classPathResource.getFile();
        final byte[] bytes = FileUtil.File2byte(file);
        return new ByteArrayResource(bytes) {
            @Override
            public String getFilename() {
                logger.info("=========== 下载导入模板接口调用结束 ================" );
                return "讲师新增模板.xlsx";
            }
        };
    }catch (Exception e){
        logger.error("文件下载失败,msg {}" + e.getMessage());
        throw new BaseException(Response.Status.BAD_REQUEST,"CAL8000","文件下载失败");
    }

}




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/servicecomb-java-chassis"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月16日(星期一) 晚上6:53
收件人:&nbsp;"apache/servicecomb-java-chassis"<servicecomb-java-chassis@noreply.github.com&gt;;
抄送:&nbsp;"ICON"<861522731@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/servicecomb-java-chassis] 上传文件的参数 (#2058)





 
我自己测试了下，没有发现问题。 你用的哪个版本？能否提供一个重现的 DEMO ？
 
BTW: 使用 ResponseEntity ， 需要指定类型， 比如  ResponseEntity
 
我的接口定义：
   @PostMapping(path = "/upload", produces = MediaType.TEXT_PLAIN_VALUE)   public String uploadFile(@RequestPart(name = "fileName") MultipartFile file) {       return fileService.uploadFile(file);   }  
生成的 swagger :
   /upload:     post:       operationId: "uploadFile"       consumes:       - "multipart/form-data"       produces:       - "text/plain"       parameters:       - name: "fileName"         in: "formData"         required: true         type: "file"       responses:         "200":           description: "response of 200"           schema:             type: "string"

**Comment by liubao68** [comment]
可以参考下 [错误处理](https://docs.servicecomb.io/java-chassis/zh_CN/general-development/error-handling/)的介绍。 
另外可以参考下 [相关issue](https://github.com/apache/servicecomb-java-chassis/issues/2051)

**Comment by VTracyHuang** [comment]
有点看不懂 我就是想实现如果下载成功就返回文件资源 如果下载失败了就返回错误信息 就是想让前端能收到错误的响应结果。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/servicecomb-java-chassis"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月24日(星期二) 上午9:41
收件人:&nbsp;"apache/servicecomb-java-chassis"<servicecomb-java-chassis@noreply.github.com&gt;;
抄送:&nbsp;"ICON"<861522731@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/servicecomb-java-chassis] 上传文件的参数 (#2058)





 
可以参考下 错误处理的介绍。
 另外可以参考下 相关issue

**Comment by liubao68** [comment]
这个问题里面包含了很多不相关问题， 一个 issue 里面只聚焦一个问题讨论。 这个问题先关闭了，新问题建议提交新的issue。
