### ISSUE TITLE
CSE升级到3.1.5版本，ServiceComb升级到2.1.2版本之后，通过edge调用其他服务，经常报No schema

### ISSUE THREAD

**Issue by HoyerIsAlexander** [apache/servicecomb-java-chassis#2065]
CSE升级到3.1.5版本，ServiceComb升级到2.1.2版本之后，通过edge调用其他服务，经常报No schema defined for xxx，我们自己实现了dispatcher，debug是生效的，而且schema也是存在的，也重启了edge和问题服务，这种大概是什么问题？之前使用2.5+1.3版本就没这个问题

**Comment by HoyerIsAlexander** [comment]
问题现象补充：我们有一个服务A  API较多，注册时间比较久，每次上线的时候A先升级，A升级完之后，我们通过控制台和日志也看到这个服务已经注册完，状态是ready，通过edge调用服务正常，然后开始升级edge（因为涉及到jar包版本升级），等edge刷完之后就报No schema defined for A的问题，看edge的启动日志，MicroServiceRule已经发现了A的三个实例，对比了版本和服务id等都是匹配的；然后我们重启了A服务，然后再重启edge，恢复正常，两次的日志打印都是一样的，有的时候还需要重启多次

**Comment by liubao68** [comment]
"然后开始升级edge（因为涉及到jar包版本升级），等edge刷完之后就报No schema defined for A的问题"  这个情况感觉和重启是一样的。 除非这个重启过程中服务A还没有注册成功，不过按照你的描述，不太可能是这个情况。 

从上面的描述，看不出哪个地方可能有问题。 可能得继续寻找下问题出现的条件。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
