### ISSUE TITLE
请问要怎样配置才能访问servicecomb+springboot项目下的静态文件如图片等

### ISSUE THREAD

**Issue by szcg1981** [apache/servicecomb-java-chassis#2067]
请问要怎样配置才能访问servicecomb+springboot项目下的静态文件如图片等，microservice.yaml和application.yml分别要怎样配置还是说要写代码？有没有实例链接？

**Comment by liubao68** [comment]
你可以参考下 [servicecomb-samples](https://github.com/apache/servicecomb-samples/tree/master/porter_springboot) 里面的 website 项目。 项目说明参考开发指南： https://docs.servicecomb.io/java-chassis/zh_CN/featured-topics/application-porter/

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
