### ISSUE TITLE
servicecomb.islation.timeoutinMilliseconds 超时设置 300000000，但是没有生效，返回的还是30000ms

### ISSUE THREAD

**Issue by huang-qw** [apache/servicecomb-java-chassis#2069]

**Comment by liubao68** [comment]
你说的配置项是 [隔离恢复](https://docs.servicecomb.io/java-chassis/zh_CN/references-handlers/bizkeeper/) 时间吗？

这个和超时设置没有关系。 


请求超时时间是 [servicecomb.request.timeout](https://docs.servicecomb.io/java-chassis/zh_CN/config-reference/rest-transport-client/)

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
