### ISSUE TITLE
碰到一个问题后端接口在一分钟没有返回的时候出现Error: socket hang up

### ISSUE THREAD

**Issue by luozuyi** [apache/servicecomb-java-chassis#2071]
不知道是不是和框架哪个设置有关 还是和代码相关
![image](https://user-images.githubusercontent.com/29859621/99927355-094c6f00-2d80-11eb-9cfe-b13fa0f08eed.png)

**Comment by liubao68** [comment]
通过这个信息看不出来是后端服务挂住了，还是网络故障，需要先检查下服务是否正常启动，以及是不是访问这个服务的所有接口都是类似的情况，服务监听的端口和协议是不是 REST 等。

**Comment by luozuyi** [comment]
> 通过这个信息看不出来是后端服务挂住了，还是网络故障，需要先检查下服务是否正常启动，以及是不是访问这个服务的所有接口都是类似的情况，服务监听的端口和协议是不是 REST 等。

这个接口是一个导出功能因为数据量大 后端一分钟没处理完 然后一分钟的出现了这问题 如果我把数据量调小点就能导出来来 这个是个导出excel功能 大神给给建议

**Comment by liubao68** [comment]
你能够提供一个简单的重现问题 DEMO 示例吗？ 我可以测试验证下。 
相关问题 [1](https://github.com/apache/servicecomb-java-chassis/issues/2072)
如何准备 DEMO 示例 [2](https://github.com/apache/servicecomb-java-chassis/wiki)

**Comment by luozuyi** [comment]
> 你能够提供一个简单的重现问题 DEMO 示例吗？ 我可以测试验证下。
> 相关问题 [1](https://github.com/apache/servicecomb-java-chassis/issues/2072)
> 如何准备 DEMO 示例 [2](https://github.com/apache/servicecomb-java-chassis/wiki)

package com.whwater.server.core.mapper;

import com.whwater.server.core.entity.ListRegistration;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultType;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.mapping.ResultSetType;
import org.apache.ibatis.session.ResultHandler;

import java.util.List;
import java.util.Map;

/**
 * <p>
 *  Mapper 接口
 * </p>
 *
 * @author luozuyi
 */
public interface ListRegistrationMapper extends BaseMapper<ListRegistration> {

    // 这是执行接口就是通过自定义的sql语句用流式处理一次取出1000条 获取的字段是不确定的所以用map封装
    @Select("${sql}")
    @Options(resultSetType = ResultSetType.FORWARD_ONLY, fetchSize = 1000)
    @ResultType(Map.class)
    void executeSqlStream(@Param("sql") String sql,ResultHandler<Map<String,Object>> handler);
}

/**
     * 自定义查询导出
     * @param customizeOrderQueryId 规则
     * @return
     */
    @GetMapping("export-query-execute-new")
    public Part exportQueryExecuteNew(Long customizeOrderQueryId){

        try {
            if(customizeOrderQueryId == null){
                throw new InvocationException(javax.ws.rs.core.Response.Status.BAD_REQUEST, new Result<>().fail("自定义查询id不能为空！"));
            }
            List<ColumnConfig> list = columnConfigService.list(new LambdaQueryWrapper<ColumnConfig>().eq(ColumnConfig::getCustomizeOrderQueryId, customizeOrderQueryId));
            List<ConditionConfig> conditionConfigs = conditionConfigService.list(new LambdaQueryWrapper<ConditionConfig>().eq(ConditionConfig::getCustomizeOrderQueryId, customizeOrderQueryId).orderByAsc(ConditionConfig::getId));
            if(list.isEmpty()){
                throw new InvocationException(javax.ws.rs.core.Response.Status.BAD_REQUEST, new Result<>().fail("未设置字段"));
            }
            List<String> workSheetColumns = new ArrayList<>();
            List<String> resultSheetColumns = new ArrayList<>();
            List<String> backNoticeColumns = new ArrayList<>();
            List<Dictionary> dictionnaryList = dictionaryService.list();
            //List<String> heads = Lists.newArrayList();
            LinkedHashMap<String,String> heads = new LinkedHashMap<>();
            StringBuffer sql = new StringBuffer();
            sql.append("select ");
            for (int i = 0; i < list.size(); i++) {
                ColumnConfig columnConfigItem = list.get(i);
                Long columnRegistrationId = columnConfigItem.getColumnRegistrationId();
                Long listRegistrationId = columnConfigItem.getListRegistrationId();
                ListRegistration listRegistration = listRegistrationService.getById(listRegistrationId);
                String tableName = listRegistration.getTableName();
                ColumnRegistration columnRegistration = columnRegistrationService.getById(columnRegistrationId);
                String columnName = columnRegistration.getColumnName();
                String columnCnname = columnRegistration.getColumnCnname();
                String key = tableName + "$" + columnName;
                //heads.add(columnCnname);
                heads.put(key,columnCnname);
                StringBuffer sb = new StringBuffer();
                sb.append(tableName).append(".").append(columnName).append(" as ").append(tableName).append("$").append(columnName);
                if(list.size() - 1 == i){
                    sb.append(" ");
                }else{
                    sb.append(",");
                }
                sql.append(sb.toString());
                if(sb.toString().startsWith("work_sheet_tab")){
                    workSheetColumns.add(sb.toString());
                }else if(sb.toString().startsWith("result_sheet_tab")){
                    resultSheetColumns.add(sb.toString());
                }else if(sb.toString().startsWith("back_notice_tab")){
                    backNoticeColumns.add(sb.toString());
                }
            }
            appendSql(resultSheetColumns, backNoticeColumns, sql);
            appendConditionNew(conditionConfigs, sql);
            sql.append(" order by work_sheet_tab.id desc");
            String sqlQuery = sql.toString();
            log.info(sqlQuery);
            // List<Map<String, Object>> records = listRegistrationService.executeSql(sqlQuery);
            **List<Map<String, Object>> recordsData = new ArrayList<>();
            listRegistrationMapper.executeSqlStream(sqlQuery, resultContext -> {
                Map<String, Object> objectMap = resultContext.getResultObject();
                log.info(resultContext.getResultCount()+"");
                log.info(objectMap.toString());
                parseQueryMap(dictionnaryList,objectMap);
                recordsData.add(objectMap);
            });**
            File listToExcelFile = ExcelUtils.listToExcelFile(recordsData, heads, "自定义导出");
            return new FilePart(null,listToExcelFile).setDeleteAfterFinished(true);
        } catch (Exception e) {
            log.error("导出错误",e);
            throw new InvocationException(javax.ws.rs.core.Response.Status.BAD_REQUEST, new Result<>().fail("导出错误"));
        }
    }
// 加粗的地方表示调用逻辑 获取每条数据去做相应的转换 例如判断字段是否需要转换为中文 是否从字典获取还是从别人接口获取
![mapper](https://user-images.githubusercontent.com/29859621/100181938-595d3a00-2f16-11eb-8e13-01e844099cd5.png)
![luoji](https://user-images.githubusercontent.com/29859621/100181949-624e0b80-2f16-11eb-9f0f-be8ae96499e5.png)
我的主要逻辑是每次获取1000条数据然后转换相应处理 然后放到要导入的集合 最后一起导出 当这个过程超过一分钟的时候就会超时 如果数据量小没有问题能导出

**Comment by liubao68** [comment]
这样写代码逻辑是不对的。 因为处理超过一分钟，postman 就超时了。 
正确的做法应该是返回流，然后你需要有一个后台任务持续的往流里面写数据。 你可以参考下 [DownloadSchema](https://github.com/apache/servicecomb-java-chassis/blob/master/integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/DownloadSchema.java) 里面的 slowInputStream 的例子。

**Comment by luozuyi** [comment]
> 这样写代码逻辑是不对的。 因为处理超过一分钟，postman 就超时了，客户端会主动关闭连接。
> 正确的做法应该是返回流，然后你需要有一个后台任务持续的往流里面写数据。 你可以参考下 [DownloadSchema](https://github.com/apache/servicecomb-java-chassis/blob/master/integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/DownloadSchema.java) 里面的 slowInputStream 的例子。 注意例子不要直接用于实际生成代码，比如生产代码要使用线程池和做好流控，否则可能导致创建大量线程导致内存泄露等问题。

大佬能给点提示吗 就是我那个list怎么放到你说的代码里面去 我这边最后是要在浏览器能导出excel功能 求助

**Comment by liubao68** [comment]
你要返回一个流， 后台开启一个任务（线程），从数据库读取数据，将数据写到流里面去。 相当于你读的过程就一直在写，这样浏览器不会超时。

**Comment by luozuyi** [comment]
> 你要返回一个流， 后台开启一个任务（线程），从数据库读取数据，将数据写到流里面去。 相当于你读的过程就一直在写，这样浏览器不会超时。 我给你发的例子里面就是使用 PipedStream 实现了这种处理。

![image](https://user-images.githubusercontent.com/29859621/100420093-c7ddfb80-30c0-11eb-8d5d-5580e173bd9c.png)
![image](https://user-images.githubusercontent.com/29859621/100420144-e04e1600-30c0-11eb-94b9-1b6aa2db4357.png)
例子里面还是一样在一分钟的时候socket hand up

**Comment by luozuyi** [comment]
@GetMapping("export-query-execute-csv")
    public void exportQueryExecuteCsv(Long customizeOrderQueryId){

        try {
            if(customizeOrderQueryId == null){
                throw new InvocationException(javax.ws.rs.core.Response.Status.BAD_REQUEST, new Result<>().fail("自定义查询id不能为空！"));
            }
            List<ColumnConfig> list = columnConfigService.list(new LambdaQueryWrapper<ColumnConfig>().eq(ColumnConfig::getCustomizeOrderQueryId, customizeOrderQueryId));
            List<ConditionConfig> conditionConfigs = conditionConfigService.list(new LambdaQueryWrapper<ConditionConfig>().eq(ConditionConfig::getCustomizeOrderQueryId, customizeOrderQueryId).orderByAsc(ConditionConfig::getId));
            if(list.isEmpty()){
                throw new InvocationException(javax.ws.rs.core.Response.Status.BAD_REQUEST, new Result<>().fail("未设置字段"));
            }
            List<String> workSheetColumns = new ArrayList<>();
            List<String> resultSheetColumns = new ArrayList<>();
            List<String> backNoticeColumns = new ArrayList<>();
            List<Dictionary> dictionnaryList = dictionaryService.list();
            List<String> heads = Lists.newArrayList();
            // LinkedHashMap<String,String> heads = new LinkedHashMap<>();
            heads.add("序号");
            StringBuffer sql = new StringBuffer();
            sql.append("select ");
            for (int i = 0; i < list.size(); i++) {
                ColumnConfig columnConfigItem = list.get(i);
                Long columnRegistrationId = columnConfigItem.getColumnRegistrationId();
                Long listRegistrationId = columnConfigItem.getListRegistrationId();
                ListRegistration listRegistration = listRegistrationService.getById(listRegistrationId);
                String tableName = listRegistration.getTableName();
                ColumnRegistration columnRegistration = columnRegistrationService.getById(columnRegistrationId);
                String columnName = columnRegistration.getColumnName();
                String columnCnname = columnRegistration.getColumnCnname();
                String key = tableName + "$" + columnName;
                heads.add(columnCnname);
                StringBuffer sb = new StringBuffer();
                sb.append(tableName).append(".").append(columnName).append(" as ").append(tableName).append("$").append(columnName);
                if(list.size() - 1 == i){
                    sb.append(" ");
                }else{
                    sb.append(",");
                }
                sql.append(sb.toString());
                if(sb.toString().startsWith("work_sheet_tab")){
                    workSheetColumns.add(sb.toString());
                }else if(sb.toString().startsWith("result_sheet_tab")){
                    resultSheetColumns.add(sb.toString());
                }else if(sb.toString().startsWith("back_notice_tab")){
                    backNoticeColumns.add(sb.toString());
                }
            }
            appendSql(resultSheetColumns, backNoticeColumns, sql);
            appendConditionNew(conditionConfigs, sql);
            sql.append(" order by work_sheet_tab.id desc");
            String sqlQuery = sql.toString();
            log.info(sqlQuery);
            long startMillis = System.currentTimeMillis();
            String[] dataArray = new String[heads.size()];
            String[] headsStr = heads.toArray(dataArray);
            String name = new String( "自定义查询".getBytes("utf-8"), "ISO8859-1" );
            name = name+".csv";
            ServletOutputStream outputStream = servletResponse.getOutputStream();
            servletResponse.setContentType("application/download");
            servletResponse.setContentType("application/csv;charset=utf-8");
            servletResponse.setHeader("Content-Disposition","attachment;filename="+name+"");
            CsvWriter writer = CsvUtil.getWriter(new OutputStreamWriter(outputStream, CharsetUtil.CHARSET_GBK));
            writer.write(headsStr);
            listRegistrationMapper.executeSqlStreamLinkMap(sqlQuery, resultContext -> {
                LinkedHashMap objectMap = resultContext.getResultObject();
                log.info(resultContext.getResultCount()+"");
                log.info(objectMap.toString());
                int row = resultContext.getResultCount();
                parseQueryMapWrite(dictionnaryList,objectMap,row,writer);

            });
            log.warn("执行数据库查询sql开始:"+startMillis);
            log.warn("执行数据库查询sql完毕:"+System.currentTimeMillis());
            writer.flush();
            writer.close();
        } catch (Exception e) {
            log.error("导出错误",e);
            throw new InvocationException(javax.ws.rs.core.Response.Status.BAD_REQUEST, new Result<>().fail("导出错误"));
        }
    }
这我的例子 本地idea启动不走网关一点问题都没  能下载不会断 一上到华为云的servicecomb走网关就断 
![image](https://user-images.githubusercontent.com/29859621/100708209-e0168900-33e6-11eb-9ff9-653fc501f6cd.png)
![image](https://user-images.githubusercontent.com/29859621/100708244-ec9ae180-33e6-11eb-89b7-00ceeba4cba9.png)
下面的下载也是慢慢下

**Comment by liubao68** [comment]
你这次贴的代码和上次不同，这次代码看起来像是 spring mvc 的 REST 服务， 不像是 java-chassis 的下载。 因为 java-chassis 不能够使用 ServletResponse 写数据的。 另外， 你说的 网关是指用 edge service 开发的应用网关吗？

**Comment by luozuyi** [comment]
> 你这次贴的代码和上次不同，这次代码看起来像是 spring mvc 的 REST 服务， 不像是 java-chassis 的下载。 因为 java-chassis 不能够使用 ServletResponse 写数据的。 另外， 你说的 网关是指用 edge service 开发的应用网关吗？

是的就是本地idea启动不走网关 都能下载 上到华为云的seviceComb的微服务后走的网关就网站已转移 例子不同是我尝试不同的方法 上面给出的例子也是 本地不走网关能下载 走到网关下载一分钟的时候就hand up

**Comment by liubao68** [comment]
你说的 网关是指用 edge service 开发的应用网关吗 （edge service 转发逻辑对于 java-chassis 和 spring cloud 工作机制存在非常大差异）？ 还是 APIG 或者其他产品?

**Comment by luozuyi** [comment]
> edge

edge网关

**Comment by liubao68** [comment]
估计是 edge service 等待响应超时了，可以结合日志看下。 如前面的讨论， 你的代码处理逻辑有点问题。 edge service 你是自定义的 Dispatcher 还是使用类 CommonHttpEdgeDispatcher?

**Comment by luozuyi** [comment]
APPLICATION_ID: CspOms
service_description:
  name: CspOmsGatewayService
  version: 0.0.83
  environment: testing
  properties:
    allowCrossApp: false
addressResolver:
  #servers: 8.8.8.8,114.114.114.114
  searchDomains: default.svc.cluster.local,svc.cluster.local,cluster.local
  ndots: 1
servicecomb:
  uploads:
    directory: ${user.dir}
  service:
    registry:
      address: https://10.200.16.137:30100
      instance:
        watch: false
#  monitor:
#    client:
#      serverUri: https://cse.cn-north-4.myhuaweicloud.com
  executors:
    default: servicecomb.executor.groupThreadPool
  rest:
    address: 0.0.0.0:8032
    client:
      http2:
        enabled: false
  handler:
    chain:
      Consumer:
        default: authHandler,loadbalance
          #service:
        #auth: loadbalance
  #When a local project is deployed as a container outside a cluster, you need to delete all monitor and credentials comments and configure the AK/SK.
  credentials:
    accessKey: ***
    secretKey: ***
    akskCustomCipher: default
    #project: cn-east-2
  http:
    dispatcher:
      edge:
        url:
          enabled: true
          mappings:
            CspOmsBusinessService:
              prefixSegmentCount: 1
              path: "/whwater-order/.*"
              microserviceName: CspOmsBusinessService
              versionRule: 0.0.0-2.0.0
            CspOmsCheckService:
              prefixSegmentCount: 1
              path: "/whwater-check/.*"
              microserviceName: CspOmsCheckService
              versionRule: 0.0.1-2.0.0
            CspOmsAuthService:
              prefixSegmentCount: 1
              path: "/whwater-oauth/.*"
              microserviceName: CspOmsAuthService
              versionRule: 0.0.1-2.0.0
            CspOmsAppService:
              prefixSegmentCount: 1
              path: "/whwater-app/.*"
              microserviceName: CspOmsAppService
              versionRule: 0.0.1-2.0.0
            CspOmsGisService:
              prefixSegmentCount: 1
              path: "/whwater-gis/.*"
              microserviceName: CspOmsGisService
              versionRule: 0.0.1-2.0.0
            CspOmsMessageService:
              prefixSegmentCount: 1
              path: "/whwater-socket/.*"
              microserviceName: CspOmsMessageService
              versionRule: 0.0.1-2.0.0
            CspCrmBusinessService:
              prefixSegmentCount: 1
              path: "/whwater-crm-business/.*"
              microserviceName: CspCrm:CspCrmBusinessService
              versionRule: 0.0.1-2.0.0
  isolation:
    timeoutInMilliseconds: 300000000
  request:
    timeout: 300000000
  cors:
    enabled: true
    origin: "*"
    allowedHeader: "*"
    allowCredentials: false
    allowedMethod: GET,POST,PUT,DELETE,OPTIONS
    maxAge: 3600
  datacenter:
    name: cn-north-4
    region: ${servicecomb.datacenter.name}
    availableZone: ${servicecomb.datacenter.name}

**Comment by luozuyi** [comment]
> 估计是 edge service 等待响应超时了，可以结合日志看下。 如前面的讨论， 你的代码处理逻辑有点问题。 edge service 你是自定义的 Dispatcher 还是使用类 CommonHttpEdgeDispatcher?

APPLICATION_ID: CspOms
service_description:
  name: CspOmsGatewayService
  version: 0.0.83
  environment: testing
  properties:
    allowCrossApp: false
addressResolver:
  #servers: 8.8.8.8,114.114.114.114
  searchDomains: default.svc.cluster.local,svc.cluster.local,cluster.local
  ndots: 1
servicecomb:
  uploads:
    directory: ${user.dir}
  service:
    registry:
      address: https://10.200.16.137:30100
      instance:
        watch: false
#  monitor:
#    client:
#      serverUri: https://cse.cn-north-4.myhuaweicloud.com
  executors:
    default: servicecomb.executor.groupThreadPool
  rest:
    address: 0.0.0.0:8032
    client:
      http2:
        enabled: false
  handler:
    chain:
      Consumer:
        default: authHandler,loadbalance
          #service:
        #auth: loadbalance
  #When a local project is deployed as a container outside a cluster, you need to delete all monitor and credentials comments and configure the AK/SK.
  credentials:
    accessKey: ***
    secretKey: ***
    akskCustomCipher: default
    #project: cn-east-2
  http:
    dispatcher:
      edge:
        url:
          enabled: true
          mappings:
            CspOmsBusinessService:
              prefixSegmentCount: 1
              path: "/whwater-order/.*"
              microserviceName: CspOmsBusinessService
              versionRule: 0.0.0-2.0.0
            CspOmsCheckService:
              prefixSegmentCount: 1
              path: "/whwater-check/.*"
              microserviceName: CspOmsCheckService
              versionRule: 0.0.1-2.0.0
            CspOmsAuthService:
              prefixSegmentCount: 1
              path: "/whwater-oauth/.*"
              microserviceName: CspOmsAuthService
              versionRule: 0.0.1-2.0.0
            CspOmsAppService:
              prefixSegmentCount: 1
              path: "/whwater-app/.*"
              microserviceName: CspOmsAppService
              versionRule: 0.0.1-2.0.0
            CspOmsGisService:
              prefixSegmentCount: 1
              path: "/whwater-gis/.*"
              microserviceName: CspOmsGisService
              versionRule: 0.0.1-2.0.0
            CspOmsMessageService:
              prefixSegmentCount: 1
              path: "/whwater-socket/.*"
              microserviceName: CspOmsMessageService
              versionRule: 0.0.1-2.0.0
            CspCrmBusinessService:
              prefixSegmentCount: 1
              path: "/whwater-crm-business/.*"
              microserviceName: CspCrm:CspCrmBusinessService
              versionRule: 0.0.1-2.0.0
  isolation:
    timeoutInMilliseconds: 300000000
  request:
    timeout: 300000000
  cors:
    enabled: true
    origin: "*"
    allowedHeader: "*"
    allowCredentials: false
    allowedMethod: GET,POST,PUT,DELETE,OPTIONS
    maxAge: 3600
  datacenter:
    name: cn-north-4
    region: ${servicecomb.datacenter.name}
    availableZone: ${servicecomb.datacenter.name}

**Comment by wujimin** [comment]
https://docs.servicecomb.io/java-chassis/zh_CN/config-reference/rest-transport-client/  

servicecomb.rest.client.connection.idleTimeoutInSeconds，默认是60秒

**Comment by luozuyi** [comment]
> https://docs.servicecomb.io/java-chassis/zh_CN/config-reference/rest-transport-client/
> 
> servicecomb.rest.client.connection.idleTimeoutInSeconds，默认是60秒

我待会去试试

**Comment by luozuyi** [comment]
> 60秒

![image](https://user-images.githubusercontent.com/29859621/100831285-6b078a00-34a0-11eb-9ae2-f3f3806667e1.png)


> https://docs.servicecomb.io/java-chassis/zh_CN/config-reference/rest-transport-client/
> 
> servicecomb.rest.client.connection.idleTimeoutInSeconds，默认是60秒

![image](https://user-images.githubusercontent.com/29859621/100831359-9c805580-34a0-11eb-880d-2ee05ca51da8.png)
m没有用

**Comment by luozuyi** [comment]
> 你这次贴的代码和上次不同，这次代码看起来像是 spring mvc 的 REST 服务， 不像是 java-chassis 的下载。 因为 java-chassis 不能够使用 ServletResponse 写数据的。 另外， 你说的 网关是指用 edge service 开发的应用网关吗？

我上面下载的用的 ServletResponse写数据就是本地起的servicecomb 是可以写的 是用的hutool的工具类写的csv本地不走网关都可以写 上到线上就此网站已转移

**Comment by luozuyi** [comment]
添加了一个压缩文件你们看看 一个不走网关可以下载 一个走网关不能下载

**Comment by luozuyi** [comment]
走网关会报一个错误 2020-12-02 14:36:22.291  WARN 7440 --- [ntloop-thread-6] o.a.s.t.r.c.h.DefaultHttpClientFilter    : method GET, path /list-registration/export-query-execute-csv/, statusCode 200, reasonPhrase , response content-type application/csv;charset=utf-8 is not supported
2020-12-02 14:36:22.291 ERROR 7440 --- [ntloop-thread-6] o.a.s.t.r.c.h.DefaultHttpClientFilter    : failed to decode response body, exception is [Invalid UTF-8 middle byte 0xc5
 at [Source: (org.apache.servicecomb.foundation.vertx.stream.BufferInputStream); line: 1, column: 5]]

**Comment by liubao68** [comment]
ServletResponse 走的不是 servicecomb的 运行流程， 是 Spring Boot 的， 你可以下载文件，但是不能走网关， 因为你的网关配置的是 UrlMappedEdgeDispatcher， 这个是不支持非 servicecomb 后台服务的。

**Comment by luozuyi** [comment]
> ServletResponse 走的不是 servicecomb的 运行流程， 是 Spring Boot 的， 你可以下载文件，但是不能走网关， 因为你的网关配置的是 UrlMappedEdgeDispatcher， 这个是不支持非 servicecomb 后台服务的。

怎么看走的是springboot 我启动了都注册到注册中心去了 为什么说是springboot的

**Comment by luozuyi** [comment]
> ServletResponse 走的不是 servicecomb的 运行流程， 是 Spring Boot 的， 你可以下载文件，但是不能走网关， 因为你的网关配置的是 UrlMappedEdgeDispatcher， 这个是不支持非 servicecomb 后台服务的。

我加上那个api的注解后可以用吗

**Comment by liubao68** [comment]
https://docs.servicecomb.io/java-chassis/zh_CN/using-java-chassis-in-spring-boot/introduction/  这有个原理介绍，可以了解下。 

spring boot 集成的时候， spring boot 会启动 web container， 也默认会启动自己的 SpringMVC 框架（本质是一个 servlet）。 java-chassis 也会加载自己（也是一个  servlet）。下载是谁提供的， 取决于请求进来的时候， 被哪个 servlet 处理。 你可以尝试在业务逻辑的入口打一个断点， 看调用栈， 就知道运行流程是 jaav-chassis, 还是 spring boot默认了。 

如果走 java-chassis， 上传下载的开发指南参考： https://docs.servicecomb.io/java-chassis/zh_CN/general-development/upload-download/

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
