### ISSUE TITLE
mvc的拦截器不生效的问题

### ISSUE THREAD

**Issue by laozhaoJava** [apache/servicecomb-java-chassis#2073]
使用常规的mvc的HandlerInterceptor或filter对http的请求起不到拦截的作用么，试了下两个都拦不住，那有提供对应的方式么

**Comment by liubao68** [comment]
可以通过[java-chassis运行时架构](https://docs.servicecomb.io/java-chassis/zh_CN/start/design/) 了解请求的处理过程。 对请求拦截， 可以考虑 [`Handler`](https://docs.servicecomb.io/java-chassis/zh_CN/references-handlers/intruduction/) ， 这个机制的处理过程对于 servlet/vert.x等底层运行时都是最通用的。 如果使用 REST, 还可以考虑 [`HttpServerFilter`](https://docs.servicecomb.io/java-chassis/zh_CN/general-development/http-filter/) 。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
