### ISSUE TITLE
文件上传传其他参数

### ISSUE THREAD

**Issue by VTracyHuang** [apache/servicecomb-java-chassis#2083]
@PostMapping(path = "/documentation/upload", produces = MediaType.TEXT_PLAIN_VALUE, consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    public Boolean uploadFile(@RequestBody UploadFileRequest request, @RequestPart("file") MultipartFile multipartFile){
        logger.info("请求参数"+request.toString());
        return false;
    }

请问上传文件的时候，除了文件参数 我可能还需要传递五六个参数 ，我就把他写成了个对象，这样需要怎么传呢?
文档里 @RequestAttribute可用，只能传一个简单类型。

**Comment by wujimin** [comment]
可以使用JAX-RS里的`@BeanParam`，springmvc模式下也可以用这个标注
