### ISSUE TITLE
ServiceComb如何支持soap类型的接口，或者怎么处理xml格式的消息呢？

### ISSUE THREAD

**Issue by yangyinqi** [apache/servicecomb-java-chassis#2085]
RT，现在有个场景是需要用微服务进行xml格式的消息交互，尝试了一下发现返回的数据类型仍然是application/json，但需要的是text/xml。

**Comment by yangyinqi** [comment]
找到了这个文档资料 [https://docs.servicecomb.io/java-chassis/zh_CN/general-development/produceprocess/](url)，可以实现返回扩展的格式。另外想问下有没有通用一些的支持方法，框架层面的注解或者配置之类的。

**Comment by liubao68** [comment]
servicecomb 没正式提供 xml 支持。 扩展机制试用的范围比较小。

**Comment by yangyinqi** [comment]
> servicecomb 没正式提供 xml 支持。 扩展机制适用的范围比较小。

好的，明白了，多谢。
