### ISSUE TITLE
rest on servlet场景下，请求报文大小受tomcat-maxHttpHeaderSize配置影响

### ISSUE THREAD

**Issue by Eyekneemm** [apache/servicecomb-java-chassis#2109]
rest on servlet场景下，请求报文大小受tomcat-maxHttpHeaderSize配置影响，
debug发现是cse在调用时把请求体都放到了url上，导致超出限制，请问是基于什么考虑呢？

**Comment by liubao68** [comment]
Http URL/HEADER/BODY 大小都有限制，这个是协议要求的内容。 "cse在调用时把请求体都放到了url上" 这个应该是你定义的接口存在错误， 比如可以指定 RequestBody， 但是没指定， 默认值是 RequestParam。 可以看下你的接口定义。

**Comment by Eyekneemm** [comment]
服务提供方代码问题，使用dto传参即可
