### ISSUE TITLE
 通过获取request对象获取请求路径报空指针

### ISSUE THREAD

**Issue by VTracyHuang** [apache/servicecomb-java-chassis#2121]
![image](https://user-images.githubusercontent.com/54627411/101718381-053c8300-3adc-11eb-891c-91f4c1978a55.png)
我在普通的springboot项目使用这种方式都可以取到 ，但是
![image](https://user-images.githubusercontent.com/54627411/101718442-27ce9c00-3adc-11eb-8587-3b4ab7dea8f8.png)
在serviceComb项目好像就不能这么取
请问可以怎么样获取请求路径呢

**Comment by liubao68** [comment]
spring boot 项目底层的 RPC 框架是 spring mvc， 而 java chassis 底层的 RPC 框架是完全不一样的， 它不是基于 JSP/Serlvet 协议的。 获取路径的最佳实践是在 Handler 中， 通过 Invocation 读取 `getOperationMeta().getMicroserviceQualifiedName()`。 这个是每一个接口的唯一标识。 在 java chassis中，无法使用 RequestControllerHolder， 这个是 sring mvc RPC 框架特有的。 

这里的[文章介绍](https://docs.servicecomb.io/java-chassis/zh_CN/using-java-chassis-in-spring-boot/using-java-chassis-in-spring-boot/) 可以帮助理解底层运行机制的差异。
