### ISSUE TITLE
可以自定义Timetamp的返回格式吗？

### ISSUE THREAD

**Issue by HoyerIsAlexander** [apache/servicecomb-java-chassis#2124]
从2.5.0升级到3.1之后发现Timetamp返回的格式变了，能指定自己这个格式吗？

**Comment by liubao68** [comment]
不建议在返回值里面使用 Timestamp， 这个类有很多内部状态。 自定义 REST 序列化的[说明参考 ](https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/interface-constraints/)。
