### ISSUE TITLE
generate swagger operation failed ，parameter name is not present

### ISSUE THREAD

**Issue by hypggg** [apache/servicecomb-java-chassis#2128]
Caused by: java.lang.IllegalStateException: parameter name is not present, method=XXXXX
solution:
  change pom.xml, add compiler argument: -parameters, for example:
    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-compiler-plugin</artifactId>
      <configuration>
        <compilerArgument>-parameters</compilerArgument>
      </configuration>
    </plugin>
	at org.apache.servicecomb.swagger.generator.SwaggerGeneratorUtils.collectParameterName(SwaggerGeneratorUtils.java:192) ~[swagger-generator-core-2.1.1.jar:2.1.1]
升级了cse 3.1.1,servicecomb 2.1.1，解决了一大堆的版本冲突问题，但最后启动还是报这个错，
https://github.com/apache/servicecomb-java-chassis/issues/1723， 参照这个issues的反馈的也没有解决。
求解

**Comment by liubao68** [comment]
可以参考[这个pom](https://github.com/apache/servicecomb-samples/blob/master/porter_springboot/pom.xml)， 配置 -paramters

记得重新import一下项目，或者rebuild一下项目，确保编译器，比如IDEA正常识别

```
  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.1</version>
          <configuration>
            <source>1.8</source>
            <target>1.8</target>
            <compilerArgument>-parameters</compilerArgument>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
```

**Comment by hypggg** [comment]
问题解决，我那个代码是在jar包里的，周六的时候没加到生成jar包的工程 里，感谢

**Comment by rainsun-sxy** [comment]
如果用gradle构建的话请问如何解决此类问题？
