### ISSUE TITLE
服务启动后，不会自动下载被调用服务实例接口锲约，只有接口第一次调用的时候才会去获取

### ISSUE THREAD

**Issue by xiaoyuer11** [apache/servicecomb-java-chassis#2129]
服务启动后，不会自动下载被调用服务实例接口锲约，只有接口第一次调用的时候才会去获取，获取锲约时间较长，有时超过2s。对于时延要求比较高的场景，将导致接口第一次调用永远是失败的。有没有什么方法解决这种问题？

**Comment by liubao68** [comment]
可以考虑使用[服务启动事件](https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/event-listener/)， 做一个预加载。比如调用一下对方的 Health 接口。

**Comment by xiaoyuer11** [comment]
已解决  ths
