### ISSUE TITLE
升级serviceComb到2.1.3后，部分RPC接口接收到的参数为null

### ISSUE THREAD

**Issue by hypggg** [apache/servicecomb-java-chassis#2132]
升级serviceComb到2.1.3后，部分RPC接口接收到的参数为null，这个怎么排查原因啊，接口定义也没看出区别

**Comment by wujimin** [comment]
猜测，你是参数命名不匹配  
如果是从1.x升级上来的，参数匹配从按顺序匹配，变成了按名字匹配

**Comment by hypggg** [comment]
改了下好了，确实是这个原因，我昨天其实往这方面试了下，但应该是没有重启consumer服务，导致也是不行
