### ISSUE TITLE
serviceComb、cse SDK 和 微服务引擎专享版的版本是怎样匹配的

### ISSUE THREAD

**Issue by hypggg** [apache/servicecomb-java-chassis#2134]
我在本地测试已经将servicecomb java-chassis-core升级到了 2.1.3，cse-solution-service-engine 升级到了 3.1.6，华为云的微服务引擎用的是1.0.28，我看最新版本是1.0.32了，请问 微服务引擎 是否要升级，这几个的版本关联关系在哪里可以看得到

**Comment by liubao68** [comment]
微服务引擎不需要升级， 大部分SDK版本都是支持的。 除非你需要使用微服务引擎的新特性，比如RBAC等。 

开发指南参考：
  https://support.huaweicloud.com/devg-servicestage/cse_03_0005.html
SDK版本支持情况： 
  https://support.huaweicloud.com/productdesc-servicestage/cse_productdesc_0008.html

**Comment by hypggg** [comment]
好的，谢 谢
