### ISSUE TITLE
上传文件

### ISSUE THREAD

**Issue by VTracyHuang** [apache/servicecomb-java-chassis#2135]
![image](https://user-images.githubusercontent.com/54627411/102191176-044c8c80-3ef4-11eb-8f35-80bd3daa16f8.png)
项目部署到linux环境下，有关文件的出现了这个错误，是什么原因呢
![image](https://user-images.githubusercontent.com/54627411/102191741-c7cd6080-3ef4-11eb-9403-e5b530c36f40.png)

**Comment by liubao68** [comment]
这个错误通常是配置项没生效， 看你的截图已经配置了。 可以尝试调试下代码看看什么情况。 返回这个错误的类在 `RestBodyHandler`

**Comment by VTracyHuang** [comment]
重启了网关好像就生效了



---原始邮件---
发件人: "bao liu"<notifications@github.com&gt;
发送时间: 2020年12月15日(周二) 晚上10:14
收件人: "apache/servicecomb-java-chassis"<servicecomb-java-chassis@noreply.github.com&gt;;
抄送: "VTracyHuang"<861522731@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [apache/servicecomb-java-chassis] 上传文件 (#2135)




 
这个错误通常是配置项没生效， 看你的截图已经配置了。 可以尝试调试下代码看看什么情况。 返回这个错误的类在 RestBodyHandler
