### ISSUE TITLE
升级serviceComb到2.1.3后，项目有时候会启动不起来，一直转圈圈

### ISSUE THREAD

**Issue by hypggg** [apache/servicecomb-java-chassis#2137]
升级serviceComb到2.1.3后，项目有时候会启动不起来，一直转圈圈，看日志也看不到错误 ，
访问就报490，需要 重启电脑才好使，这个会是什么原因呢

**Comment by liubao68** [comment]
你需要提供更多信息，或者提供重现的办法。

**Comment by hypggg** [comment]
原因不明，先关闭
