### ISSUE TITLE
边缘服务和业务服务交互

### ISSUE THREAD

**Issue by liuguangrong** [apache/servicecomb-java-chassis#2145]
利用边缘服务edge做网关与其他服务交互时。链接不通，异常信息是在RestClientInvocation.java的
clientRequest.exceptionHandler(e -> {
      invocation.getTraceIdLogger().error(LOGGER, "Failed to send request, local:{}, remote:{}.",
          getLocalAddress(), ipPort.getSocketAddress(), e);
      throwableHandler.handle(e);
    });
里面捕获了吗？有没有什么办法可以拿到这个异常信息

**Comment by liubao68** [comment]
重复： https://github.com/apache/servicecomb-java-chassis/issues/2150
