### ISSUE TITLE
ZoneAwareDiscoveryFilter里定义的变量GROUP_InstancesAZMatch 含义不对

### ISSUE THREAD

**Issue by johnyannj** [apache/servicecomb-java-chassis#2146]
GROUP_RegionAndAZMatch = "instancesRegionAndAZMatch"
是存储的Region和AZ都匹配的instance

GROUP_InstancesAZMatch = "instancesAZMatch"
应该是存的只有region匹配。 az不匹配的instance

变量名称含义和实际情况不符

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
