### ISSUE TITLE
通过RPC远程调用,服务的提供者获取到的String类型的参数有时候会为null

### ISSUE THREAD

**Issue by qwx996784** [apache/servicecomb-java-chassis#2147]
使用透明RPC方式远程调用时 服务的提供者接收到消费者传递过来的参数有时候会是null,大多数时候是正常的接收到传递过来的参数

**Comment by liubao68** [comment]
概率性出现的问题得先分析下错误情况差异的原因。 只是问题描述的话， 我们也无法分析。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
