### ISSUE TITLE
servicecomb的配置中心不能再不重启服务的情况下刷新配置

### ISSUE THREAD

**Issue by qwx996784** [apache/servicecomb-java-chassis#2149]
servicecomb的配置中心不能再不重启服务的情况下刷新配置

**Comment by liubao68** [comment]
需要检查下你的日志，看下配置是否正确下发。 正确下发的情况下，日志会打印更新的key值。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
