### ISSUE TITLE
edge边缘服务490异常信息抛出

### ISSUE THREAD

**Issue by liuguangrong** [apache/servicecomb-java-chassis#2150]
在利用edge做边缘服务与其他服务交互时，证书的校验出现异常。然而我发现在发生异常的时候，异常被handler捕获了，这个异常并没有被抛出，而抛出了490，请问在现有的代码中，是否存在钩子之类的方法可以拿到该异常？
RestClientInvocation.java#invoke(Invocation invocation, AsyncResponse asyncResp)
```
clientRequest.exceptionHandler(e -> {
      invocation.getTraceIdLogger().error(LOGGER, "Failed to send request, local:{}, remote:{}.",
          getLocalAddress(), ipPort.getSocketAddress(), e);
      throwableHandler.handle(e);
    });
```

**Comment by liubao68** [comment]
可以参考下 https://github.com/apache/servicecomb-java-chassis/issues/2158

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
