### ISSUE TITLE
接口日志在URI尾部拼接特殊字符，该特殊字符产生传递拼接问题

### ISSUE THREAD

**Issue by lengshanwudi** [apache/servicecomb-java-chassis#2151]
一个业务的请求流向为A-->B-->C

1、A服务调用B服务GET:v1/skill 接口，A服务在调用该接口前，调用如下方法在接口URI尾部拼接“skillName”字段，用于标识某类业务请求 ContextUtils.getInvocationContext().addContext(Constant.Trace.CONTEXT_APPEND_URL, skillName);
2、服务B处理完GET:v1/skill业务时，调用了C服务的GET:v1/user 接口。
问题：B、C服务的接口日志中均打印了GET:v1/user/skillName 接口，而不是GET:v1/user。这里接口日志是否应该传递拼接？

**Comment by liubao68** [comment]
ContextUtils.getInvocationContext().addContext 的内容会在调用链中传递，A设置的， 那么B、C取到的是一样的值。 如果不期望传递，那么应该调用 addLocalContext

**Comment by lengshanwudi** [comment]
多谢：）

**Comment by lengshanwudi** [comment]
![image](https://user-images.githubusercontent.com/10349459/104430021-2c95dc80-55c1-11eb-94fe-8b4c5ca49cdf.png)
使用addContext("appendUrl", skillName) ，原来在uri尾部可以在追加尾部skillName字符串，修改为addLocalContext("appendUrl", skillName) 无法追加，还有其他的参数需要修改吗？

**Comment by liubao68** [comment]
你说的功能似乎是业务自己定制的功能。 java-chassis并没有提供在URL末尾追加URL的功能。 如果方便，你也可以尝试使用java-chassis的samples验证下，并提供一个例子，供分析使用。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
