### ISSUE TITLE
CSE压测REST接口出现大量590错误码

### ISSUE THREAD

**Issue by huangdong-new** [apache/servicecomb-java-chassis#2160]
背景介绍：
    使用Jmeter工具压测REST接口性能，Jmeter工具设置了1600个线程并发，REST请求是通过SLB转发给后端的服务。后端服务通信协议是Vertx。
问题描述：
    启动压测时，后端服务返回大量的590错误，REST请求并未走到后端服务的业务处理逻辑中。几分钟后590错误还是会偶尔出现。
    搜索业务运行日志并未发现任何ERROR级别日志打印，但在接口日志中可以看到590的错误返回码。
    在网上搜索说请求数超过并发连接数会返回590的错误码，但是我在CSE开发指导文档中没有搜索到设置并发连接数的地方。

**Comment by liubao68** [comment]
590是服务端错误的意思， 一般都会打印错误日志，可以检查下日志是否有异常。 590错误和并发连接数没有必然联系，需要具体问题具体分析。 [异常处理](https://docs.servicecomb.io/java-chassis/zh_CN/general-development/error-handling/) 有介绍什么时候抛出 590错误。

**Comment by huangdong-new** [comment]
> 590是服务端错误的意思， 一般都会打印错误日志，可以检查下日志是否有异常。 590错误和并发连接数没有必然联系，需要具体问题具体分析。 [异常处理](https://docs.servicecomb.io/java-chassis/zh_CN/general-development/error-handling/) 有介绍什么时候抛出 590错误。

日志级别修改为DEBUG，通过traceId没有搜索到任何日志。在运行日志中搜索ERROR关键字也没有任何结果。这个问题压测时必现。

**Comment by liubao68** [comment]
没有打印日志就比较麻烦，需要想办法定位到出现问题的场景和位置，才好解答。

**Comment by huangdong-new** [comment]
感谢liubao大神的支撑，问题定位清楚了，是因为在处理链中使用了bizkeeper-provider，压测是超过了器默认的并发处理数导致。把该handler删除后，问题不在复现。
