### ISSUE TITLE
自动生成契约文件schemes值问题咨询

### ISSUE THREAD

**Issue by huangdong-new** [apache/servicecomb-java-chassis#2165]
schemes:
- "http"
- "https"
自动生成契约文件中，该schemes的值是受什么地方控制的？

**Comment by liubao68** [comment]
可以使用 `SwaggerDefinition`, 参考[文档](https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/swagger-annotation/)

**Comment by wujimin** [comment]
我记得是根据本进程监听是http还是https，自动决定的
