### ISSUE TITLE
流控算法优劣势咨询

### ISSUE THREAD

**Issue by huangdong-new** [apache/servicecomb-java-chassis#2166]
开发指导文档中CSE流控算法有三种，固定窗口算法、令牌桶算法、漏桶算法。
但文档中没有说明这几种算法的优劣势，能否帮忙答复下？建议文档中也补充下相关说明。

**Comment by liubao68** [comment]
这些算法应该很多公开材料可以查询，建议搜索下。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
