### ISSUE TITLE
GET接口：字符 + 号无法通过CseRestTemplate正常传输

### ISSUE THREAD

**Issue by singformyself** [apache/servicecomb-java-chassis#2169]
本人测试证实无法传输，查看了源码，发现**CseUriTemplateHandler继承了废弃的DefaultUriTemplateHandler**，spring官方文档推荐使用DefaultUriBuilderFactory。
手动更新掉handler：
        CseRestTemplate restTemplate = new CseRestTemplate();
        String url = xxxxx;
        DefaultUriBuilderFactory defaultUriBuilderFactory = new DefaultUriBuilderFactory();
        defaultUriBuilderFactory.setEncodingMode(DefaultUriBuilderFactory.EncodingMode.TEMPLATE_AND_VALUES);
        restTemplate.setUriTemplateHandler(defaultUriBuilderFactory);
        MyResponse rsp= restTemplate.getForObject(url, xxx.class, params);
测试结果：
 字符 + 号 可以正确传输到其他微服务

**Comment by singformyself** [comment]
补充：GET模式下无法正常传输，POST下应该没问题

**Comment by liubao68** [comment]
你的代码怎么写的？

**Comment by singformyself** [comment]
通过这个方式创建的restTemplate RestTemplate restTemplate = RestTemplateBuilder.create();
然后调用getForObject:
MyResponse rsp= restTemplate.getForObject(url, xxx.class, params); // 参数里有一个参数包含  字符 + 号，这里这里调用的时get接口

**Comment by singformyself** [comment]
内部代码，不允许外露，大概就是上面的流程

**Comment by singformyself** [comment]
CSE注册中心的接口调试那里是可以正常传输+号的，你们可以测试下

**Comment by liubao68** [comment]
我测试了下，并没有发现你描述的问题。 

```
    TestMgr.check("hi world1+world2 [world1+world2]",
        template.getForObject(prefix + "/controller/sayhi?name={name}",
            String.class,
            "world1+world2"));
```

需要看下你使用的版本， 你也可以尝试下新版本是否已经解决这个问题。

**Comment by singformyself** [comment]
不好意思，重新定位了下，是我们框架集成的spring-web版本过高，spring-web4.3.x是对+号进行url编码的，所以你测试的时候没发现问题。我们公司采用的是spring-web5.2.x，不再对+号进行编码，spring官方给的解释：The RFC 3986 states that the following characters are allowed in a query string (see the appendix A in the ABNF):

query         = *( pchar / "/" / "?" )
pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
unreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~"
pct-encoded   = "%" HEXDIG HEXDIG
sub-delims    = "!" / "$" / "&" / "'" / "(" / ")"
                 / "*" / "+" / "," / ";" / "="
This means that sub-delimiters are allowed in query strings and do not need to be percent encoded (that includes +, $).

Now I understand that some legal characters might still have a special meaning. We've applied some changes to be more consistent with the encoding of URLs (see SPR-16860), and I think you're ultimately after what was addressed in SPR-17039 (see the dedicated section in the reference documentation).

Thanks!
而cse的解码器只识别编码后的+号。前后编解码不一致，导致问题。
之前改代码用spring推荐的DefaultUriBuilderFactory 默认是对所有参数进行编码，所以可以调试成功。

**Comment by singformyself** [comment]
spring 官方解释中文：根据 RFC 3986 加号等符号的确实可以出现在参数中的，而且不需要编码，有问题的在于服务端的解析没有与时俱进
所以是否你们也与时俱进一下。

**Comment by liubao68** [comment]
目前 java-chassis 使用的 spring 版本是 `<spring.version>5.2.9.RELEASE</spring.version>`， 我也没发现你说的问题。

**Comment by singformyself** [comment]
主要是我们的resttemplate用的版本不同导致的，内部问题，不好意思
