### ISSUE TITLE
微服务调用报错490,请帮忙确认一下原因及如何解决

### ISSUE THREAD

**Issue by ljy19911228** [apache/servicecomb-java-chassis#2170]
CSE版本2.3.77.B002，java-chassis-dependencies版本1.2.0.B017r2
微服务调用时报错，不同服务有多种报错：
Invoke all server failed. Operation CONSUMER rest dsc-cim-service.swagger.innerQueryDevices, e=cause:InvocationException,message:InvocationException: code=490;msg=CommonExceptionData [message=Cse Internal Bad Request];cause:NoStackTraceTimeoutException,message:The timeout period of 30000ms has been exceeded while executing POST /dsc-cim-service/v1/innerQueryDevices for server 10.2.13.166:8081

Invoke server failed. Operation CONSUMER rest dsc-cim-service.swagger.deviceProfileQuery; server rest://10.2.13.77:8081?sslEnabled=true&protocol=http2; 0-0 msg cause:InvocationException,message:InvocationException: code=490;msg=CommonExceptionData [message=Cse Internal Bad Request];cause:VertxException,message:Connection was closed

Invoke server failed. Operation CONSUMER rest dsc-contacts-service.privateContacts.deletePrivateContacts; server rest://10.4.86.106:8082?sslEnabled=true&protocol=http2; 0-0 msg cause:InvocationException,message:InvocationException: code=490;msg=CommonExceptionData [message=Cse Internal Bad Request];cause:SSLException,message:SSLEngine closed already

请问这个是老版本的已知问题吗？是否有规避手段？升级能否解决？

**Comment by solitudeycq** [comment]
你这个看起来像是超时了

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
