### ISSUE TITLE
loadbalance strategy WeightedResponse recover too slow

### ISSUE THREAD

**Issue by angelfall-yy** [apache/servicecomb-java-chassis#2176]
Thereis one microservice m1, loadbalance used strategy WeightedResponse.
It has two endPointer p1 and p2
At first, p1's latency is 100ms, p2's latency is 100ms. The tps of p1 and p2 is same 100
Then,  p1's latency changed to 700ms, p2's latency is still 100ms. p1's tps is 40, and p2's tps is 160.
Last, p1's  latency recover to 100ms, p2's latency is still 100ms. p1's tps recover too slowly ,  one minute grow about 1 tps.
It can not recover as soon as the  latency recovered

**Comment by liubao68** [comment]
This is an known problems of  WeightedResponse ,because it uses and Ribbon Loadbalance Stats that will not clear. 
This beviour will not cause problem and sometimes works better than revocer fast. 
So need a discussion to check if should consider it is a problem.

**Comment by angelfall-yy** [comment]
I read the code, and find the main point is that WeightedResponse used mean latency of  Ribbon Loadbalance Stats.
`  private List<Double> doCalculateTotalWeights(List<ServiceCombServer> servers) {
    List<Double> stats = new ArrayList<>(servers.size() + 1);
    double totalWeights = 0;
    boolean needRandom = false;
    for (ServiceCombServer server : servers) {
      ServerStats serverStats = loadBalancer.getLoadBalancerStats().getSingleServerStat(server);
      double avgTime = serverStats.getResponseTimeAvg();
      if (!needRandom && avgTime > MIN_GAP) {
        needRandom = true;
      }
      totalWeights += avgTime;
      stats.add(avgTime);
    }
    stats.add(totalWeights);
    totalWeightsCache = totalWeights;
    if (needRandom) {
      return stats;
    } else {
      return new ArrayList<>();
    }
  }`

if we has one microservice m1, loadbalance used strategy WeightedResponse.It has two endPointer p1 and p2.
At first, p1's latency is 100ms, p2's latency is 100ms. They run for  one year. The mean latency of p1 is 100ms, p1 handles 50% requests. 
One day  p1's latency changed to 1000ms, p2's latency is still 100ms. The mean latency of p1 is (100*365+1000)/366=102ms

WeightedResponse  use mean latency of p1 to calc if p1 should select. But 100ms(run well for one year) and 102ms(one day error) is almost the same. So WeightedResponse' calculations is almost the same. p1 will still handle about 50% requests, when it's latency is 10 times than before.
It is right?

**Comment by liubao68** [comment]
Yes, you are right. The code need to be improved.

**Comment by liubao68** [comment]
Fixed in https://github.com/apache/servicecomb-java-chassis/pull/2192, and will be available in 2.1.5
