### ISSUE TITLE
cse注册中心是否支持项目中某些类中的对外接口不走cse注册，如何规避？

### ISSUE THREAD

**Issue by Carey-1996** [apache/servicecomb-java-chassis#2185]
项目中部分模块不直接走cse注册发布，而是通过手机端访问，这种场景如何处理？

**Comment by liubao68** [comment]
注册中心只是保留元数据，你提的是接口访问控制方面的问题。 可以参考下[案例](https://bbs.huaweicloud.com/blogs/116063)。

**Comment by guoHuanMessi** [comment]
我可能没有表述清楚， 基于cse的注册中心是按照服务的层面注册的，即服务内的接口都会被注册，也就需要按照cse的访问的参数要求等标准去修改这样cse才能初始化成功，而如果服务中部分接口不走cse,也会因此修改。目前只想到服务拆分，基于cse还有什么方式可以规避吗？

**Comment by liubao68** [comment]
如果不走 CSE 的处理流程，那么这些接口走什么样的处理流程了？ 

在J2EE集成模式下，比如tomcat， CSE 只是一个 servlet， 可以和其他的 servlet、spring boot MVC 接口并存。 参考： [案例(基于Spring Boot 2.0的IoT应用集成和使用servicecomb实践)](https://bbs.huaweicloud.com/blogs/100188)

**Comment by guoHuanMessi** [comment]
> 如果不走 CSE 的处理流程，那么这些接口走什么样的处理流程了？
> 
> 在J2EE集成模式下，比如tomcat， CSE 只是一个 servlet， 可以和其他的 servlet、spring boot MVC 接口并存。 参考： [案例(基于Spring Boot 2.0的IoT应用集成和使用servicecomb实践)](https://bbs.huaweicloud.com/blogs/100188)

感谢您的回答，我们服务中存在模块是开放给手机端直接调用，或者其他服务开放的openApi，这部分接口是不走CSE处理流程的

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
