### ISSUE TITLE
咨询一个ServiceComb接口分类的问题

### ISSUE THREAD

**Issue by zhufeizzz** [apache/servicecomb-java-chassis#2186]
**场景：**
我们团队和其它团队开发的微服务会部署在同一个CSE集群内，但是有些接口我们想进团队内部的微服务暴露，而对其它团队仅暴露少量Public接口。

**目前的思路：**
1、通过ApplicationID隔离，把Public接口抽取到独立微服务，允许allowCrossApp限制调用。但是这样局限性太强，无法在微服务内做区分。
2、在Swagger接口定义的Tag标记Public接口，服务端添加拦截器，获取Tag和来源微服务，并进行校验。

**问题：**
感觉目前的两种方式都不够优雅，请问还有没有别的选择对接口进行分组并校验？

**Comment by liubao68** [comment]
分组必须定义组。 感觉思路2已经是最简单了。
