### ISSUE TITLE
bean加载时读取配置有时候读不到

### ISSUE THREAD

**Issue by Yannis-01** [apache/servicecomb-java-chassis#2196]
代码中有bean加载时去读取cse配置中心的配置有读不到的情况.是否存在bean加载时还未连上线上配置中心的情况.连接配置中心和业务中spring bean加载的顺序是否有先后顺序

**Comment by Yang-gg** [comment]
@liubao68

**Comment by liubao68** [comment]
服务启动的时候，有可能连不上配置中心，这个时候， bean加载就可能无法获取配置中心数据，可以查看运行日志，确认是否存在这种情况。 在可以连上配置中心的场景， 一般能够获取到。 

配置中心在 `ConfigurationSpringInitializer`， 它实现了 `PropertySourcesPlaceholderConfigurer`， 通常会在业务bean之前加载， 这个是spring保证的。

**Comment by Yang-gg** [comment]
有没有考虑加一下限制,在存在配置线上配置中心的场景下,要确保先正常连接配置中心再进行业务bean的加载

**Comment by Yang-gg** [comment]
@liubao68

**Comment by liubao68** [comment]
不能无限制等待， 最多可以在无法访问配置中心的情况下，抛出异常， 不让应用启动。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
