### ISSUE TITLE
有木有那种filter是在invocationContext实例化只有生效的？

### ISSUE THREAD

**Issue by XiaoDongZhi** [apache/servicecomb-java-chassis#2197]
我们有一个模块的api，里面都有一些公共的参数，所以我想弄个拦截器，然后把这些参数都放到上下文里面，然后在每个api执行的时候，处理末端都传给第三方服务。

我们之前有httpserverfilter的实现，验证了下，这个httpserverfilter的调用是在设置上下文之前的，所以放不进去。

**Comment by liubao68** [comment]
可以看看自定义的 HttpServerFilter 和 平台的 `ServerRestArgsFilter` 的 `order`， 保证在之后执行就可以取到参数。 

接口API的实现里面也可以通过参数 InvocationContext 或者 ContextUtils 取到上下文。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
