### ISSUE TITLE
可否再细讲解一下这个RPC调用？

### ISSUE THREAD

**Issue by VTracyHuang** [apache/servicecomb-java-chassis#2198]
![image](https://user-images.githubusercontent.com/54627411/104572966-51f11c00-568f-11eb-8e3f-440f6e0c84c8.png)

**Comment by liubao68** [comment]
图片经常加载不出来，会影响问题处理。 建议不要截图。 参考说明： https://github.com/apache/servicecomb-java-chassis/wiki

**Comment by liubao68** [comment]
需要你先描述下具体疑问，或者建议。

**Comment by VTracyHuang** [comment]
https://www.bookstack.cn/read/ApacheServiceCombJavaChassis/54.md 这是官方文档的地址

关于Rpc这儿
   @RpcReference(schemaId = "hello", microserviceName = "helloApp:helloProvider")
  private Hello hello;

我就想问一下 这个Hello 是provider那边的controller类 然后consumer里需要把他声明成接口 补充方法 这样吗？ 还是要怎么写？

**Comment by VTracyHuang** [comment]
再来问一问 有没有serviceComb rpc调用的demo啊

**Comment by liubao68** [comment]
开发指南： https://docs.servicecomb.io/java-chassis/zh_CN/start/first-sample/

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
