### ISSUE TITLE
关于servicecomb中vertx性能的咨询

### ISSUE THREAD

**Issue by five111** [apache/servicecomb-java-chassis#2200]
servicecomb服务端大量使用了vertx，请问这种异步方式对比传统线程池方式的性能提升有多大。有没有具体一些的性能测试数据？

**Comment by wujimin** [comment]
https://www.itread01.com/hkcqcqhk.html   
可以参考一下这个  

![测试结果](https://img2.tuicool.com/7jaEvy3.png)

**Comment by five111** [comment]
我看了链接中的文章，其主要描述的是单consumer->单producer的场景，我认为这种场景主要测试的是两个服务之间调用的性能，
这种场景下servicecomb核心服务之如config-center service-center应该是不会产生交互的 。我更关注的是使用了vertx的config-center的性能如何

**Comment by liubao68** [comment]
over servlet 就是你们使用的容器的性能， 如果是 tomcat 的话，大约是 1/5。 这个是以前验证的经验值。 
业务选型的时候， 框架性能多数情况下不是一个主要考量因素， 因为业务性能一般都是主要瓶颈。 以后切换运行模式也是简单的，不需要改代码。

**Comment by five111** [comment]
> over servlet 就是你们使用的容器的性能， 如果是 tomcat 的话，大约是 1/5。 这个是以前验证的经验值，仅供参考，在不同的优化条件下差异比较大。
有个疑问， 这个1/5 tomcat是否开启了nio？还是希望能够提供一些官方的测试报告。我们目前很多项目都是通过servlet容器进行部署的，这个5倍的效率非常令人激动，如果有一些较为具体的测试报告，我们可以有很大的推力去推动大家进行一个servicecomb的应用
> 业务选型的时候， 框架性能多数情况下不是一个主要考量因素， 因为业务性能一般都是主要瓶颈，所以性能差异表现的并不明显。 以后切换运行模式也是简单的，不需要改代码。

**Comment by liubao68** [comment]
java-chassis不对外提供任何官方的性能测试报告。业务可以结合需要的业务场景和运行环境进行一个实际验证。
