### ISSUE TITLE
RuleExt自定义负载均衡策略，choose方法的servers引用经常发生变化？

### ISSUE THREAD

**Issue by yanshaohui** [apache/servicecomb-java-chassis#2203]
业务基于一致性hash自定义负载均衡策略，在public ServiceCombServer choose(List<ServiceCombServer> servers, Invocation invocation) 执行时，判断servers引用变化则认为服务发现变化，此时触发重建hash环。
但部分实例servers引用变化非常频繁触发hash环重建，部分实例却非常稳定。
经过比对，引用变化的实例servers中的endpoints列表（ip:port）字符串值并没有发生变化。

**Comment by liubao68** [comment]
你说的频繁是多久？通常只有存在实例变化的的时候，列表才会变化。 （即实例上下线）

**Comment by yanshaohui** [comment]
每秒钟都会有两三次的刷新，但完全相同配置的其他实例就非常稳定没有刷新。
可以确定的是，刷新前后，列表实际的producer list（ip:port）没有变化。

**Comment by liubao68** [comment]
ServiceCombServer 里面有 instance id， 可以看下这个是否变化。 不知道是不是某个负载均衡策略选择的列表不一样。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
