### ISSUE TITLE
RuleExt自定义负载均衡策略，choose方法的servers会漏掉一个微服务提供者。

### ISSUE THREAD

**Issue by sylar147** [apache/servicecomb-java-chassis#2208]
![image](https://user-images.githubusercontent.com/22445751/105275878-2b753880-5bdb-11eb-95e1-7f9115715f3c.png)

**Comment by liubao68** [comment]
你的问题描述不是很清晰，不是很容易理解什么问题。 日志里面显示的调用栈、线程信息似乎都不是java-chassis原来的样子。 

BTW，你可以提供下更加完整的信息，日志内容不要截图，参考说明：https://github.com/apache/servicecomb-java-chassis/wiki

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
