### ISSUE TITLE
Edge服务转发后HttpServletRequest中的body无法二次读取

### ISSUE THREAD

**Issue by rechief** [apache/servicecomb-java-chassis#2210]
Edge接收到三方请求后，转发请求信息给内部微服务，但是在微服务接收到的HttpServletRequest的bodyBuffer为null
已有特性：已针对HttpServerFilter增加了needCacheRequest()，做了码流缓存
`@Override
    public boolean needCacheRequest(OperationMeta operationMeta) {
        return true;
    }`

**Comment by liubao68** [comment]
needCacheRequest主要的目的是保证框架能够正常读取到body数据（在自定义HttpServerFilter并且已经读取body的情况下）。 流都是不能二次读取的。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
