### ISSUE TITLE
能否在请求报错时指定produceProcessor

### ISSUE THREAD

**Issue by Nick-The-Uncharted** [apache/servicecomb-java-chassis#2214]
场景：有一个场景时返回 application/vnd.ms-excel 给客户端，但是如果报错，我们希望能够使用json返回，否则我们就只能把错误写在xls里。。。。。请求的 accept是application/json,application/vnd.ms-excel

**Comment by liubao68** [comment]
文件下载的时候，可以指定 CONTENT_TYPE和内容。 不知道这个是否能够满足要求。 

```
  @GetMapping(path = "/download")
  @ApiResponses({
      @ApiResponse(code = 200, response = File.class, message = ""),
  })
  public ResponseEntity<InputStream> download() throws IOException {
    return ResponseEntity
        .ok()
        .header(HttpHeaders.CONTENT_TYPE, MediaType.TEXT_PLAIN_VALUE)
        .header(HttpHeaders.CONTENT_DISPOSITION, "attachment;filename=download.txt")
        .body(new ByteArrayInputStream("download".getBytes(StandardCharsets.UTF_8)));
  }
```

**Comment by Nick-The-Uncharted** [comment]
@liubao68 可以的~不过目前文件下载接口要是能有outputStream的callback就好了，workbook只有 org.apache.poi.ss.usermodel.Workbook#write(OutputStream stream)的方法，我得先把文件读作byte数组才能返回，内存占用偏大。

**Comment by liubao68** [comment]
这个只是合理使用Java的流机制的问题。 比如使用 `PipedInputStream` + `PipedOutputStream` 。
