### ISSUE TITLE
Handler的配置问题

### ISSUE THREAD

**Issue by Pangzhihong** [apache/servicecomb-java-chassis#2217]
microservice.yaml不就是对应一个微服务了吗，在这个配置文件配置Handler的service有什么意义，可不可以配置服务里面的schemaId之类的。

**Comment by liubao68** [comment]
https://docs.servicecomb.io/java-chassis/zh_CN/references-handlers/intruduction/  文档里面有描述一个使用场景。

**Comment by Pangzhihong** [comment]
文档里都是在Consumer上配置的，在Provider配置是不是没什么意义 ？

**Comment by liubao68** [comment]
是的。 没意义。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
