### ISSUE TITLE
版本更新后，方法标注废弃，业务如何设置响应的Status

### ISSUE THREAD

**Issue by SheldonJim** [apache/servicecomb-java-chassis#2218]
VertxServerResponseToHttpServletResponse.setStatus()方法被标注为Deprecated，方法只是简单的为类变量做赋值操作，
1.这个方法为何会被标注为Deprecated？
2.升级之后如何为VertxServerResponseToHttpServletResponse.HttpServerResponse 设置http状态？

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.

**Comment by SheldonJim** [comment]
该用户没有回应，可能用户忙，请稍候再试，或按Ctrl+Alt+Del返回。
