### ISSUE TITLE
compile master节点报错

### ISSUE THREAD

**Issue by bbinwang** [apache/servicecomb-java-chassis#2220]
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/apache/18/apache-18.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.apache.servicecomb:java-chassis:1.3.0: Could not transfer artifact org.apache:apache:pom:18 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/apache/apache/18/apache-18.pom and 'parent.relativePath' points at wrong local POM @ line 23, column 11
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   

工程中pom.xml包含：
  <parent>
    <groupId>org.apache</groupId>
    <artifactId>apache</artifactId>
    <version>18</version>
  </parent>

**Comment by liubao68** [comment]
你检查下网络，是否可以下载 https://repo.maven.apache.org/maven2/org/apache/apache/18/apache-18.pom

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
