### ISSUE TITLE
改造spring boot项目，websocket服务该怎么转换

### ISSUE THREAD

**Issue by keviswang** [apache/servicecomb-java-chassis#2222]

**Comment by liubao68** [comment]
这个不清楚你们的使用细节。 java-chassis 仍然支持使用 spring boot相关starter， 如果使用类spring boot的starter实现websocket，这个依然是可以使用的。 java-chassis自身没提供websocket支持。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
