### ISSUE TITLE
springboot+serviceComb热部署的问题

### ISSUE THREAD

**Issue by tiger-super** [apache/servicecomb-java-chassis#2223]
我用了spring-boot-devtools做热部署，但是每次改了代码后原本注册好的微服务就不见了这是怎么回事

**Comment by liubao68** [comment]
没使用过spring-boot-devtools， 不知道他的工作机制。 注册号的微服务不见了，是因为spring-boot-devtools热部署的时候，会执行shutdownhook,，导致实例注销了吗？
