### ISSUE TITLE
edgeService问题

### ISSUE THREAD

**Issue by tiger-super** [apache/servicecomb-java-chassis#2224]
一个项目本来就有一个edgeService(记为e1)，但这做的不符合我的需求，上面老板又不给改，我想可不可以在做一个edgeService(记为e2)，e1转给e2，e2在转发到真正的微服务，如果可以的话，e1与e2之间怎么实现，我试了一下demo的写法根本实现不了

**Comment by liubao68** [comment]
e1不修改的情况下是无法转到e2的。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
