### ISSUE TITLE
为什么不需要关注性能,是否可以改成单例实现?

### ISSUE THREAD

**Issue by Volcannozzz** [apache/servicecomb-java-chassis#2225]
https://github.com/apache/servicecomb-java-chassis/blob/c0162c16515e4e2ce0fe412a4fb49eae917d55e5/foundations/foundation-config/src/main/java/org/apache/servicecomb/config/inject/PlaceholderResolver.java#L32

**Comment by wujimin** [comment]
1. 这么复杂的定制resolve功能，只在启动流程中少量应用于operation的多级配置项  
2. 构造实例并不是这里的主要消耗，resolve才是  
  
所以是否单例并不关键  
因为也不是性能关键路径，所以也没对resolve做性能优化设计

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
