### ISSUE TITLE
想升级到最新的2.1.5版本，但service-registry模块好像没有对应的新版本，又必须引入旧版本（2.0.2），有冲突，这块怎么处理？

### ISSUE THREAD

**Issue by v35715009** [apache/servicecomb-java-chassis#2226]
依赖的组件：    
<dependency>
      <groupId>org.apache.servicecomb</groupId>
      <artifactId>service-registry</artifactId>
</dependency>

**Comment by liubao68** [comment]
使用：

```
    <dependency>
      <groupId>org.apache.servicecomb</groupId>
      <artifactId>registry-service-center</artifactId>
    </dependency>
```

详细参考[升级指导](https://docs.servicecomb.io/java-chassis/zh_CN/featured-topics/upgrading/2_0_1T2_1_0/)
