### ISSUE TITLE
咨询一个使用问题，如果想使用rest over vertx模式，是不是只能通过standalone方式部署

### ISSUE THREAD

**Issue by five111** [apache/servicecomb-java-chassis#2227]
![image](https://user-images.githubusercontent.com/19482564/106864413-cbb37d00-6704-11eb-8ffd-090a390fff0a.png)
2021-02-04 16:19:13.762  INFO 44140 --- [           main] o.a.s.core.transport.TransportManager    : choose org.apache.servicecomb.transport.rest.vertx.VertxRestTransport for rest.

我在springboot项目中通过在springboot的main函数启动的时候 能看到如上日志 ，感到费解 ，我理解这时候应该是通过over selvert方式去进行 rest通信的

**Comment by wujimin** [comment]
已经明确打印了是选择了VertxRestTransport了  
不是over servlet  
  
是否使用rest over vertx，与是否standalone之间没有耦合，但是一般都是这样用  
  
如果同时依赖了rest over vertx和servlet，那么决策规则：  
1. 如果配置的端口没有被占用，则使用rest over vertx  
2. 如果配置的端口已经被占用了，则认为自己是运行于servlet容器中，端口是被容器占用的，此时选择rest over servlet

**Comment by five111** [comment]
我是否可以这样理解 程序以何种通信模式去运行取决于我有没有使用servlet容器去运行我的程序，如果没有则都是rest over vertx模式 否则是rest over  servlet模式 ，另外这与springboot的内置tomcat又是何种关系

**Comment by wujimin** [comment]
不完全是  
使用servlet 容器 + 端口配置为servlet容器监听的端口，两者同时成立才行  
内置tomcat也是servlet容器场景，规则是一样的，都是上面的“决策规则”
