### ISSUE TITLE
AbstractEdgeDispatcher问题

### ISSUE THREAD

**Issue by tiger-super** [apache/servicecomb-java-chassis#2228]
AbstractEdgeDispatcher的实现类我想调dao层方法，用@Autowired发现是null，这个是怎么回事

**Comment by liubao68** [comment]
AbstractEdgeDispatcher 不是 spring bean ， 因此无法直接注入 spring bean。 可以使用 `BeanUtils` 获取 bean 的引用。

**Comment by tiger-super** [comment]
谢谢大佬，请问一下大佬有没有捕获异常的demo返回对应报文的demo

**Comment by tiger-super** [comment]
谢谢大佬，问一下大佬有没有捕获异常返回异常报文的demo

**Comment by liubao68** [comment]
Maybe you can look at implementations in java-chassis, like [CommonHttpEdgeDispatcher](https://github.com/apache/servicecomb-java-chassis/blob/master/edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/CommonHttpEdgeDispatcher.java) .
