### ISSUE TITLE
补丁版本2.4.x升级正式版本3.1.5详细指导

### ISSUE THREAD

**Issue by G-Jay-R** [apache/servicecomb-java-chassis#2235]
请问补丁版本2.4.x升级到3.1.5有什么详细一点的指导吗？

Java SDK | ServiceComb 基线版本 | 版本说明
2.4.x        | 1.3.0                              | 提供给具体产品的基于 1.3.0 修改的补丁版本，并且合入了2.0.x 的弱类型需求，建议升级到 3.1.5

**Comment by liubao68** [comment]
升级指导参考 : https://docs.servicecomb.io/java-chassis/zh_CN/featured-topics/upgrading/
