### ISSUE TITLE
490 超时未触发隔离，是我的配置有问题吗？帮看看呗

### ISSUE THREAD

**Issue by jlynet** [apache/servicecomb-java-chassis#2239]
`
servicecomb.loadbalance.retryEnabled: true
servicecomb.loadbalance.retryOnNext: 1
servicecomb.loadbalance.retryOnSame: 0
servicecomb.loadbalance.retryHandler: default

servicecomb.loadbalance.isolation.strategy.name: WeightedResponse
servicecomb.loadbalance.isolation.enabled: true
servicecomb.loadbalance.isolation.errorThresholdPercentage: 0
servicecomb.loadbalance.isolation.enableRequestThreshold: 1
servicecomb.loadbalance.isolation.singleTestTime: 1800000
servicecomb.loadbalance.isolation.continuousFailureThreshold: 1
`

**Comment by liubao68** [comment]
你用的哪个版本？ https://github.com/apache/servicecomb-java-chassis/releases/tag/2.1.3  有修复一个 bug。

**Comment by ai930** [comment]
1.2.1

**Comment by ai930** [comment]
实例重试机制是有用的。可是隔离在并发性丝毫不生效。

**Comment by ai930** [comment]
具体bug连接给我下，我去看看

**Comment by liubao68** [comment]
你的版本太老了。 bug链接在我前面给的tag里面有， 很容易找到。

**Comment by ai930** [comment]
我升级了后也是不行。还是无法触发隔离。依旧有请求被转发409节点
"framework": {
    "name": "servicecomb-java-chassis",
    "version": "ServiceComb:2.1.5"
  }

**Comment by liubao68** [comment]
因为你提供的信息太少， 可以尝试了解下`IsolationDiscoveryFilter`代码， 并结合场景调试下， 看看是否配置为生效， 或者错误检测方面有问题。

**Comment by ai930** [comment]
按照你的提示，我调试了下。要在服务生产者下的配置增加 `servicecomb.loadbalance.isolation.enabled: true` 才有效。不过第一次请求还是有十久次请求被分发到有问题的节点。后续再请求就不会分发过去了
服务消费端的配置是
```
servicecomb.loadbalance.retryEnabled: true
servicecomb.loadbalance.retryOnNext: 1
servicecomb.loadbalance.retryOnSame: 0
servicecomb.loadbalance.retryHandler: default

servicecomb.loadbalance.isolation.strategy.name: WeightedResponse
servicecomb.loadbalance.isolation.enabled: true
servicecomb.loadbalance.isolation.errorThresholdPercentage: 1 #serverStats.getFailedRate() < settings.errorThresholdPercentage
servicecomb.loadbalance.isolation.enableRequestThreshold: 1 #serverStats.getTotalRequests() < settings.enableRequestThreshold
servicecomb.loadbalance.isolation.singleTestTime: 1800000
servicecomb.loadbalance.isolation.continuousFailureThreshold: 1 #serverStats.getContinuousFailureCount() >= settings.continuousFailureThreshold
```

**Comment by ai930** [comment]
这个隔离好像并不能解决并发请求的情况。第一次还是会请求很多次有问题的节点

**Comment by ai930** [comment]
```
servicecomb.loadbalance.retryEnabled: true
servicecomb.loadbalance.retryOnNext: 1
servicecomb.loadbalance.retryOnSame: 0
servicecomb.loadbalance.retryHandler: default
```
服务异常调用重试，不会终断当前服务实例的吗？有什么配置启动流程拦截终断吗？

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
