### ISSUE TITLE
HttpServerFilter问题

### ISSUE THREAD

**Issue by tiger-super** [apache/servicecomb-java-chassis#2240]
大佬，我在HttpServerFilter定义了一个私有变量，是为了保存请求的报文数据，用于响应的报文的返回需要用到。
![image](https://user-images.githubusercontent.com/32871618/107628597-d8ebe100-6c9b-11eb-9d04-4125406a4119.png)
，但现在我有个疑问，这个是不是单例？也是就是在多线程下，这个是不是不安全的。

**Comment by liubao68** [comment]
HttpServerFilter是单实例的（JDK SPI机制），需要考虑多线程访问问题。

**Comment by wujimin** [comment]
放invocation.localcontext就可以了

**Comment by tiger-super** [comment]
> HttpServerFilter是单实例的（JDK SPI机制），需要考虑多线程访问问题。 你可以考虑在 Invocation 的 LocalContext 里面保存数据。

LocalContext和Context这两个有什么区别

**Comment by wujimin** [comment]
context在这一条调用链上，会向下一个进程传递  
localContext不会

**Comment by tiger-super** [comment]
> context在这一条调用链上，会向下一个进程传递
> localContext不会

非常感谢
