### ISSUE TITLE
java-chassis 2.0.0 以上 + spring boot 2.0 开发edgeservice

### ISSUE THREAD

**Issue by tiger-super** [apache/servicecomb-java-chassis#2246]
我用java-chassis 2.0.0 以上 + spring boot 2.0版本web模式开发了edgeService发起请求进入后自定义的dispatcher失效，但我改成java应用方式edgeService网关是成功zhuanf转发
![微信截图_20210222114219](https://user-images.githubusercontent.com/32871618/108654218-27527880-7503-11eb-8c8f-2c3ab5dc0b39.png)

**Comment by liubao68** [comment]
edge service只能运行于java模式， 即 reactive 模式。 不支持 servlet 模式。

**Comment by tiger-super** [comment]
> edge service只能运行于java模式， 即 reactive 模式。 不支持 servlet 模式。

好的感谢大佬解答

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
