### ISSUE TITLE
CSE 内容长度响应头Transfer-Encoding: chunked，能不能自定义改成content-length这种形式？

### ISSUE THREAD

**Issue by vaseniu** [apache/servicecomb-java-chassis#2247]
CSE 内容长度响应头Transfer-Encoding: chunked，能不能自定义改成content-length这种形式？

**Comment by liubao68** [comment]
是文件上传下载场景吗？

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
