### ISSUE TITLE
服务内部通过cse调用接口报空指针

### ISSUE THREAD

**Issue by xiali-cbc** [apache/servicecomb-java-chassis#2250]
通过cse调用接口报空指针异常  原因是这边启动的时候 没有加载到 TraceIdGenerator这个类 ，导致初始化调用链的时候报错

**Comment by liubao68** [comment]
记得以前碰到这个问题是因为有业务在servicecomb没初始化完成之前，就调用接口去访问其他服务。 可以按照这个思路排查下。 注意，第一次发起对其他服务的调用，需要在Invocatioin上下文里面（比如从REST接口进来的请求，这个请求的执行逻辑需要访问其他接口）。 或者在 [AFTER_REGISTRY](http://servicecomb.gitee.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/build-provider/event-listener/) 以后发起调用

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
