### ISSUE TITLE
改造CSE 后 RequestContextHolder依赖于Spring MVC REST来设置请求上下文，在整改后，获取到的attributes为空，从而导致抛出NPE异常

### ISSUE THREAD

**Issue by Carey-1996** [apache/servicecomb-java-chassis#2254]
public static HttpServletRequest getServletRequest() {
        ServletRequestAttributes requestAttributes = (ServletRequestAttributes)RequestContextHolder.currentRequestAttributes();
        return requestAttributes.getRequest();
    }

	public static RequestAttributes currentRequestAttributes() throws IllegalStateException {
		RequestAttributes attributes = getRequestAttributes();
		if (attributes == null) {
			if (jsfPresent) {
				attributes = FacesRequestAttributesFactory.getFacesRequestAttributes();
			}
			if (attributes == null) {
				throw new IllegalStateException("No thread-bound request found: " +
						"Are you referring to request attributes outside of an actual web request, " +
						"or processing a request outside of the originally receiving thread? " +
						"If you are actually operating within a web request and still receive this message, " +
						"your code is probably running outside of DispatcherServlet: " +
						"In this case, use RequestContextListener or RequestContextFilter to expose the current request.");
			}
		}
		return attributes;
	}

attributes  为空 ，因为cse定义了自己的上下文，对于这种依赖spring上下文如何处理。

**Comment by liubao68** [comment]
这类问题需要结合业务场景和目的进行分析和设计方案。 通常会用到Context参数， 参考：https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/catalog/

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
