### ISSUE TITLE
服务成功启动，但是注册成功的信息不打了

### ISSUE THREAD

**Issue by zhujiawen12345** [apache/servicecomb-java-chassis#2255]
之前启动成功debug日志都会打印watching microservice ****** successfully, the chosen service center address is ****，但是最近不知道为啥不打印了，debug代码发现已经调用了LOGGER.info但是日志中没有记录
LOGGER.info(
                "watching microservice {} successfully, "
                    + "the chosen service center address is {}:{}",
                selfMicroserviceId,
                ipPort.getHostOrIp(),
                ipPort.getPort());

log4j相关代码：

        <AsyncLogger name="org.apache.servicecomb.serviceregistry.client.http" level="INFO" additivity="false"
            includeLocation="true">
            <AppenderRef ref="NUWA_DEBUG" />
        </AsyncLogger>

        <RollingFile name="NUWA_DEBUG" fileName="${sys:LOG_HOME}/debug/nuwa_debug.log"
            filePattern="${sys:LOG_HOME}/debug/nuwa_debug-%d{yyyy-MM-dd}-%i.log.gz" immediateFlush="false"
            append="true">
            <PatternLayout
                pattern="%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level - [%file:%method:%line] - [%X{requestId}] - %msm%n" />
            <Policies>
                <SizeBasedTriggeringPolicy size="50MB" />
                <TimeBasedTriggeringPolicy />
            </Policies>
            <DefaultRolloverStrategy max="100">
                <DELETE basePath="${sys:LOG_HOME}/debug/" maxDepth="1">
                    <IfFileName glob="nuwa_debug-*.log.gz" />
                    <IfLastModified age="30d" />
                </DELETE>
            </DefaultRolloverStrategy>
        </RollingFile>

**Comment by liubao68** [comment]
这个日志是 `ServiceRegistryClientImpl` 打印的， 首先确认下是否开启 watch, [参考](https://docs.servicecomb.io/java-chassis/zh_CN/registry/service-center/)。 如果开启了，可以看下这个类的代码和调试下，是否连接成功打印日志。 如果打印了， 可能就是和日志配置有关系了。

**Comment by zhujiawen12345** [comment]
> 这个日志是 `ServiceRegistryClientImpl` 打印的， 首先确认下是否开启 watch, [参考](https://docs.servicecomb.io/java-chassis/zh_CN/registry/service-center/)。 如果开启了，可以看下这个类的代码和调试下，是否连接成功打印日志。 如果打印了， 可能就是和日志配置有关系了。

看了下yaml确认开启了watch，之前也debug过确认调用了打印日志的操作，后面自己把log4j的immediateFlush="false"改成了immediateFlush="true", 注册成功的日志也能正常打印了； 比较好奇的是之前一直都是正常打印的，log4j的配置也没改过，就是突然不打印了，而且同一个服务只有一台机器没有打印，其他机器都是正常打印的。不知道为啥会这样。
