### ISSUE TITLE
有工具能批量导入服务中心所有接口URL和定义吗？

### ISSUE THREAD

**Issue by zhufeizzz** [apache/servicecomb-java-chassis#2256]
为了方便做接口检视，想批量导出所有接口，现在必须要一个一个服务点进去手工下载，很麻烦。

有这种工具吗？还是只能自己写代码收集？

**Comment by liubao68** [comment]
界面好像没这个功能。 可以看下服务中心的文档，[有 REST  API可以使用](https://github.com/apache/servicecomb-service-center/blob/master/docs/openapi/v4.yaml) 。

**Comment by zhufeizzz** [comment]
好 只能自己写代码处理了
