### ISSUE TITLE
日志不输出

### ISSUE THREAD

**Issue by tiger-super** [apache/servicecomb-java-chassis#2257]
我升级到java-chassis 2.0.0 以上 + spring boot 2.0后，access.log、request.log、cse.log不管怎么发交易都为空的，请问一下整合springboot后这些配置是否有变化
![image](https://user-images.githubusercontent.com/32871618/109448060-1a440500-7a80-11eb-8df5-7f190c9daf36.png)
![image](https://user-images.githubusercontent.com/32871618/109448079-20d27c80-7a80-11eb-8f16-920f49d0d085.png)
![image](https://user-images.githubusercontent.com/32871618/109448097-262fc700-7a80-11eb-8167-9f3e292460d8.png)

**Comment by liubao68** [comment]
估计是logger系统变化了。 spring boot默认携带的是 logback 作为日志系统。 你发的配置文件是 log4j 的。

**Comment by tiger-super** [comment]
log4j试了一天冲突太多搞不出来，logback是可以的，还有org.apache.servicecomb.transport.rest.vertx.accesslog.parser.VertxRestAccessLogItemMeta变成了org.apache.servicecomb.common.accessLog.core.parser.VertxRestAccessLogItemMeta，这个也坑死我了，还以为自己哪里没有配对

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
