### ISSUE TITLE
serviceComb如何查看当前线程数

### ISSUE THREAD

**Issue by kzhuangfeilong** [apache/servicecomb-java-chassis#2263]
serviceComb并发上不去，cpu和内存使用率很低，想看下高并发下查看当前活跃线程数是否跟配置的一样，应该怎么看

**Comment by liubao68** [comment]
定位性能问题最佳实践是打开metrics日志, 参考：https://docs.servicecomb.io/java-chassis/zh_CN/general-development/metrics/

这个日志启用对性能影响很小，建议默认启用。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
