### ISSUE TITLE
触发隔离或者重试等事件，有优化自定义事件监听吗？达到监控告警目的

### ISSUE THREAD

**Issue by jlynet** [apache/servicecomb-java-chassis#2271]

**Comment by liubao68** [comment]
看看这里： https://docs.servicecomb.io/java-chassis/zh_CN/general-development/AlarmEvent/

**Comment by ai930** [comment]
我使用了这些功能，发现有个问题，你们的控制的纬度只在服务应用纬度，不能控制点具体服务应用里面的某个服务或者服务方法。。。

**Comment by liubao68** [comment]
不是很理解这个说明。建议可以描述下具体使用场景和解决的问题，可能会有更好的建议。

**Comment by ai930** [comment]
```
String p = getStringProperty("60000",
        PROP_ROOT + microservice + "." + FILTER_ISOLATION + FILTER_SINGLE_TEST,
        PROP_ROOT + FILTER_ISOLATION + FILTER_SINGLE_TEST);
```
获取隔离的相关配置纬度只能配置到MicroserviceName。如果一个应用内有一个服务异常，整个应用都会呗隔离。上次公司在使用的时候就出现应用实例被隔离完，导致注册中心无服务使用。。。。这个在新版本上有对这个纬度进行细化吗？

**Comment by liubao68** [comment]
这里有关于[基于Hystrix治理](http://servicecomb.gitee.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/references-handlers/bizkeeper/)的说明。 

这个实际产品用的比较少，确实不怎么好用。 建议使用实例隔离即可，参考： http://servicecomb.gitee.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/references-handlers/loadbalance/

**Comment by ai930** [comment]
实例隔离! 可以隔离到`@RpcSchema(schemaId = "xxxService")`吗？

**Comment by liubao68** [comment]
实例隔离是按照进程的，不能只隔离某个schema。 如果一个schema经常出问题， 可以考虑线程池隔离。 参考[线程池](http://servicecomb.gitee.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/build-provider/thread-pool/)

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
