### ISSUE TITLE
如何获取微服务名

### ISSUE THREAD

**Issue by tiger-super** [apache/servicecomb-java-chassis#2272]
有没有类可以在业务代码里面直接获得微服务名、微服务版本等微服务信息

**Comment by Hoysun** [comment]
![image](https://user-images.githubusercontent.com/33214952/109900072-ba449d00-7cd1-11eb-961a-82c5d9fe28c6.png)
https://docs.servicecomb.io/java-chassis/zh_CN/registry/introduction/

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
