### ISSUE TITLE
CSE是否有全局配置，可以在接口序列化时控制接口返回null的显示，将为null的字段不返回给客户端？

### ISSUE THREAD

**Issue by lengshanwudi** [apache/servicecomb-java-chassis#2276]
![image](https://user-images.githubusercontent.com/10349459/109944434-301c2900-7d11-11eb-9a9e-d55d9a7ca9c1.png)

如上图，期望不返回directives和cp 两个字段

**Comment by yhs0092** [comment]
可以通过定制Jackson ObjectMapper的行为来实现。Java-Chassis也是通过ObjectMapper来做参数序列化和反序列化的。

Java-Chassis实际使用的是`org.apache.servicecomb.common.rest.codec.RestObjectMapper`，ObjectMapper的子类，保存在`org.apache.servicecomb.common.rest.codec.RestObjectMapperFactory`工厂中。

**Comment by kissLife** [comment]
RestObjectMapperFactory.getRestObjectMapper().setSerializationInclusion(JsonInclude.Include.NON_NULL);

**Comment by lengshanwudi** [comment]
Thanks A Million!!! 👍 👍 👍

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
