### ISSUE TITLE
能否详细描述http over vertx推荐的standalone模式，之前没有接触过，网上搜索的内容大都和单机部署有关，感觉和这边的使用场景对不上，望不吝赐教

### ISSUE THREAD

**Issue by five111** [apache/servicecomb-java-chassis#2280]

**Comment by liubao68** [comment]
你说的是和spring boot集成的场景吗？ spring boot默认场景是使用embedded tomcat作为HTTP服务器；standalone模式指的是不使用 embedded tomcat作为HTTP服务器，而是使用servicecomb提供的vert.x HTTP服务器。 

可以参考说明：
https://docs.servicecomb.io/java-chassis/zh_CN/using-java-chassis-in-spring-boot/introduction/
https://docs.servicecomb.io/java-chassis/zh_CN/transports/introduction/
