### ISSUE TITLE
关于第三方调用

### ISSUE THREAD

**Issue by tiger-super** [apache/servicecomb-java-chassis#2286]
我在provider定义了一个第三方服务接口，报了一个java.lang.IllegalStateException: Can not execute sync logic in event loop,而且根据日志，server也是unknown
![image](https://user-images.githubusercontent.com/32871618/110306098-67077d00-8038-11eb-832b-2040974c694c.png)
![image](https://user-images.githubusercontent.com/32871618/110306142-7090e500-8038-11eb-8549-0c56192d1af9.png)
![image](https://user-images.githubusercontent.com/32871618/110306348-b2219000-8038-11eb-8e69-4cdda918d760.png)
![image](https://user-images.githubusercontent.com/32871618/110306379-b77eda80-8038-11eb-9e78-4a1a7d56a6d9.png)
但我在consumer定义了同样的第三方接口，却不会用上述错误，server也是我配置的ip
![image](https://user-images.githubusercontent.com/32871618/110306504-e09f6b00-8038-11eb-9b40-fdc5b756f4b2.png)
根据上面错误的意思，是只能从consumer发起，provider不可以吗

**Comment by tiger-super** [comment]
补充一下，上面图中490是因为我本地网络对那个ip的网络是不通的，我部署在服务器consumer是不会490是成功的

**Comment by liubao68** [comment]
你的项目是不是引入了 edge-core 这个 jar 包？

**Comment by tiger-super** [comment]
> 你的项目是不是约会了edge-core这个jar包？

我用的是springboot，2.1.5版本，目前我试了服务中心注册和本地注册两种方式，只有servlert模式才成功，standalone就是上图那个失败，这个只支持servlet模式？

**Comment by tiger-super** [comment]
> 你的项目是不是引入了 edge-core 这个 jar 包？ 如果引用了，删除这个包的引用即可。

真如大佬所说，因为网关需要 edge-core 这个包，我consumer和provider的pom都是网关哪里copy过来导致，谢谢大佬

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
