### ISSUE TITLE
拦截请求

### ISSUE THREAD

**Issue by Pangzhihong** [apache/servicecomb-java-chassis#2289]
为啥官方文档对拦截请求推荐的是处理链，而不是过滤链呢

**Comment by liubao68** [comment]
[参考文档](https://docs.servicecomb.io/java-chassis/zh_CN/general-development/http-filter/)

**Comment by Pangzhihong** [comment]
就是没看懂才过来请教下啊，可以简单的解释下吗？

**Comment by Pangzhihong** [comment]
> [参考文档](https://docs.servicecomb.io/java-chassis/zh_CN/general-development/http-filter/)

可以简单的解释下吗？

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
