### ISSUE TITLE
可以通过自定义Filter的方式对请求过来的参数进行校验吗？

### ISSUE THREAD

**Issue by Pangzhihong** [apache/servicecomb-java-chassis#2290]
就是说取出httpServletRequestEx的body或者请求头里面的参数，然后进行校验，如果校验不通过，直接拦截下来，不知道这种方式用得对不对，还是说有其他更好的方式？ 大佬可以给点意见吗？ 谢谢！

**Comment by liubao68** [comment]
可以参考下 [参数校验](https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/parameter-validator/) 是否满足业务要求

**Comment by Pangzhihong** [comment]
> 可以参考下 [参数校验](https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/parameter-validator/) 是否满足业务要求

这种不太满足业务要求，比如说一些SQL注入的校验等等，我看文档说不建议Filter对body进行操作，但可以对body进行校验吗？

**Comment by liubao68** [comment]
"不建议Filter对body进行操作" 一般指的是流不允许读取两次。如果业务自己处理流，可能破坏框架层面的处理流程。 

取决于你的业务场景， 可以选择使用 [`Handler` 或者 `HttpServerFilter`](https://docs.servicecomb.io/java-chassis/zh_CN/general-development/http-filter/)。 针对流可能多次读取的问题， `HttpServerFilter` 提供了`needCacheRequest` 设置， 开发的时候注意即可。

**Comment by Pangzhihong** [comment]
String body = httpServletRequestEx.getBodyBuffer().toString(); 
不能读取两次流？  这算是读取流吗，比如我想在Filter里面获取body参数的话

**Comment by liubao68** [comment]
getBodyBuffer的结果就是缓存的结果。如果是servlet模式（参考transport的说明：https://docs.servicecomb.io/java-chassis/zh_CN/transports/introduction/）， 必须有地方调用了getInputStream，并且needCacheRequest 为true 的时候， 才能够取到值。 如果是 vert.x 模式， vert.x是支持重复读取的。 这个地方可以取到值。

**Comment by wujimin** [comment]
"SQL注入的校验"，感觉正是应该使用validator方案，不应该去处理body呀

**Comment by Pangzhihong** [comment]
> getBodyBuffer的结果就是缓存的结果。如果是servlet模式（参考transport的说明：[https://docs.servicecomb.io/java-chassis/zh_CN/transports/introduction/），](https://docs.servicecomb.io/java-chassis/zh_CN/transports/introduction/%EF%BC%89%EF%BC%8C) 必须有地方调用了getInputStream，并且needCacheRequest 为true 的时候， 才能够取到值。 如果是 vert.x 模式， vert.x是支持重复读取的。 这个地方可以取到值。

嗯，现在这个项目是用vertx的，还有一个问题啊，就是通过httpServletRequestEx.getBodyBuffer获取参数和通过invocation.getSwaggerArgument(参数名) 

> "SQL注入的校验"，感觉正是应该使用validator方案，不应该去处理body呀

怎么理解？  validator方案支持SQL注入吗？

**Comment by Pangzhihong** [comment]
> "SQL注入的校验"，感觉正是应该使用validator方案，不应该去处理body呀

怎么理解？ validator方案支持SQL注入吗？

**Comment by wujimin** [comment]
validator是在controller入参上打校验annotation  
你要手工读取body，最终不是还是对应到各个入参的检查？

**Comment by Pangzhihong** [comment]
> annotation

是打注解啊，但有可以校验SQL注入的注解吗，我看了下只有最大值最小值等等这些简单的校验吧

**Comment by Pangzhihong** [comment]
> validator是在controller入参上打校验annotation
> 你要手工读取body，最终不是还是对应到各个入参的检查？

是打注解啊，但有可以校验SQL注入的注解吗，我看了下只有最大值最小值等等这些简单的校验吧

**Comment by wujimin** [comment]
validator注解是支持正则表达式的，也可以自定义检查逻辑，google一下，有很多例子

**Comment by Pangzhihong** [comment]
> validator注解是支持正则表达式的，也可以自定义检查逻辑，google一下，有很多例子

还有这种用法？ 我先去网上搜搜，谢了哈

**Comment by wujimin** [comment]
是的  
字段间联合校验，也是要自定义annotation

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
