### ISSUE TITLE
关于使用CompletableFuture 替代 AsyncRestTemplate 有几个疑问

### ISSUE THREAD

**Issue by five111** [apache/servicecomb-java-chassis#2291]
1、如果继续使用AsyncRestTemplate的话，会有哪些风险
2、官方给的示例是将一个AsyncRestTemplate发rest请求，改造成立通过CompletableFuture 使用rpc的方式进行通信，如果想使用CompletableFuture 发rest请求(jdk 8)，有没有demo可供参考？

**Comment by liubao68** [comment]
没有什么风险，只是spring将AsyncRestTemplate标记为deprecated， 使用的时候，会有编译警告，一般不建议使用deprecated的类。 

参考使用[异步调用](https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/reactive/)。

**Comment by wujimin** [comment]
`改造成立通过CompletableFuture 使用rpc的方式进行通信，如果想使用CompletableFuture 发rest请求(jdk 8)`  
接口方式调用，与是否发rest请求，是没有耦合的
