### ISSUE TITLE
edge service网关怎么定制可以支持状态码302重定向到请求头携带的Location

### ISSUE THREAD

**Issue by qwx996784** [apache/servicecomb-java-chassis#2292]
目前单独访问微服务可以响应302状态码重定向跳转到Location所在地址,但是从网关发请求的时候,日志显示不支持的类型

**Comment by liubao68** [comment]
你的微服务是怎么返回302状态码的？能否看下微服务的接口原型定义？

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
