### ISSUE TITLE
spring-cloud-huawei-common-1.5.1-Hoxton.jar使用自定义的AK/SK过程中，对AK的sha256加密使用的是加密的sk，未使用解密的sk

### ISSUE THREAD

**Issue by Alice523** [apache/servicecomb-java-chassis#2294]
com.huaweicloud.common.transport.ServiceCombAkSkProperties类中getSecretKey方法中，对AK的sha256加密未使用解密后的sk，具体如下：

  public String getSecretKey() {
    String decodedSecretKey = new String(findCipher().decrypt(this.secretKey.toCharArray()));

    if (ShaAKSKCipher.CIPHER_NAME.equalsIgnoreCase(this.akskCustomCipher)) {
      return decodedSecretKey;
    }

    return SecretUtil.sha256Encode(this.secretKey, this.accessKey);
  }

**Comment by liubao68** [comment]
not related to this project
