### ISSUE TITLE
带长度的tcp报文

### ISSUE THREAD

**Issue by tiger-super** [apache/servicecomb-java-chassis#2296]
我有个需求是连接第三方系统，通过tcp协议，通信之间通过这种带长度的xml报文
![image](https://user-images.githubusercontent.com/32871618/110913041-9aefe480-834f-11eb-9e6b-439db149b7ce.png)
那么通过本地注册highway协议是否可行的通，如果可行，那么接口该如何定义，目前我的接口如下定义，目前连接是通的，但第三方无法解析报文，接口定义是否有问题
![image](https://user-images.githubusercontent.com/32871618/110913857-9972ec00-8350-11eb-9235-830e2cf5b1d3.png)
![fb89cd1591570ad2217422308e805b4](https://user-images.githubusercontent.com/32871618/110913997-c6270380-8350-11eb-8b0c-6e591f2af409.png)

**Comment by tiger-super** [comment]
跟第三方要了系统报错信息发现报文头不是长度而是一个CSE.TCP的字符串
![image](https://user-images.githubusercontent.com/32871618/110914605-8c0a3180-8351-11eb-8b04-22cb16e96f88.png)

**Comment by tiger-super** [comment]
今天抓包抓出来的是这样的
![6dede670063cadbce24c65d7828054e](https://user-images.githubusercontent.com/32871618/111024191-42384e80-8418-11eb-8c2c-1e1470aeb7d2.png)
红色框框处是哪里来的

**Comment by wujimin** [comment]
highway是私有协议  
三方协议需要模仿highway定制自己的transport

**Comment by tiger-super** [comment]
> highway是私有协议
> 三方协议需要模仿highway定制自己的transport

因为我这里是旧系统改造，第三方是不会去改他们系统，所以目前serviceComb有什么解决方式，目前我想到是用直接用Vertx

**Comment by tiger-super** [comment]
> highway是私有协议
> 三方协议需要模仿highway定制自己的transport

因为我这里是旧系统改造，第三方是不会去改他们系统，所以目前serviceComb有什么解决方式，目前我想到是用直接用Vertx，不通过本地注册方式

**Comment by wujimin** [comment]
肯定是不改造旧系统  
我的意思是定制一个自己的transport，与现有三方协议对接

**Comment by tiger-super** [comment]
> 肯定是不改造旧系统
> 我的意思是定制一个自己的transport，与现有三方协议对接

这个transport如何定制，有没有demo可以参考

**Comment by wujimin** [comment]
github上好像没有，我们内部项目里倒是有这样用的，😢  
简单地说就是自己从头实现一个transport

**Comment by tiger-super** [comment]
> github上好像没有，我们内部项目里倒是有这样用的，😢
> 简单地说就是自己从头实现一个transport

第三方答应帮忙开个http端口出来，现在又遇到契约问题
接口如下，通过本地注册方式
![image](https://user-images.githubusercontent.com/32871618/111143013-499a5c00-85c0-11eb-82fb-3109d49d57ba.png)
![image](https://user-images.githubusercontent.com/32871618/111143234-836b6280-85c0-11eb-9c0e-2dac642a9afb.png)
但是都没有生效
![image](https://user-images.githubusercontent.com/32871618/111143062-55861e00-85c0-11eb-8de7-4c831a7eb2c5.png)
![image](https://user-images.githubusercontent.com/32871618/111143082-5b7bff00-85c0-11eb-9247-652461064d38.png)

**Comment by wujimin** [comment]
https://github.com/apache/servicecomb-java-chassis/blob/master/service-registry/registry-lightweight/src/main/java/org/apache/servicecomb/registry/lightweight/VirtualDiscoverySvc.java  

1. 调用三方服务，可以使用这个功能  
    NAME/shcema-id/client interface根据需要自行定义  
2. 配置三方服务的地址
   假设三方服务NAME定义成了svc，那么配置：
```
svc:
  urls:
    - https://ip1:port1
    - https://www.abc.com:port2
    ......
```
    client interface的method的endpoint参数，根据需要决定是否定义  
    如果定义了，则可以每次调用时指定地址调用
    指定地址调用时，如果不为null，则框架会忽略svc.urls的地址配置
3. 从数据看，三方服务返回的是xml数据，servicecomb是否内置了xml序列化/反序列化，我不太清楚，请 @liubao68 解答一下  

4. 三方服务实际返回的是xml数据，但是http header中content-type却是text/html，这应该是他们的bug

**Comment by wujimin** [comment]
根据我以前了解到的信息，扩展支持xml应答数据比较简单  
但是支持自动序列化、发送xml数据，在原有代码下，好像不太好搞，因为没想到还会有人使用xml做传输

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
