### ISSUE TITLE
如何解决CSE在反序列化中含有%号导致RPC调用失败。

### ISSUE THREAD

**Issue by small-small-bai** [apache/servicecomb-java-chassis#2298]
cse在做反序列化时使用了jackson的三方件。只要带%符号，生成的jsonParser会在读inputStream时读不到jsonToken，报错信息：
com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (org.apache.servicecomb.foundation.vertx.stream.BufferInputStream); line: 1, column: 0]

**Comment by liubao68** [comment]
你可以写一个例子，包含服务端的定义以及请求报文吗？

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
