### ISSUE TITLE
用postman或者其他方式发送请求，怎么判断是使用哪个transport的

### ISSUE THREAD

**Issue by Pangzhihong** [apache/servicecomb-java-chassis#2308]

**Comment by liubao68** [comment]
postman使用的HTTP，只能访问服务的REST通道。

**Comment by Pangzhihong** [comment]
> postman使用的HTTP，只能访问服务的REST通道。

InvokerUtils.syncInvoke(microserviceName, schemaId, operationName, args);  如果采用这种方式呢 ？

**Comment by liubao68** [comment]
默认是根据服务端的地址， 轮询的。

业务可以显示的指定使用哪个， 参考： https://docs.servicecomb.io/java-chassis/zh_CN/build-consumer/common-configuration/

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
