### ISSUE TITLE
servicecomb即使使用vertx也会引入jakarta.servlet-api，导致log4j判断其为webApp而不加shutdownHook

### ISSUE THREAD

**Issue by Nick-The-Uncharted** [apache/servicecomb-java-chassis#2328]
org.apache.logging.log4j.core.impl.Log4jContextFactory#SHUTDOWN_HOOK_ENABLED

规避方法：在log4j2.component.properties里配置 log4j2.is.webapp=false

**Comment by liubao68** [comment]
java-chassis依赖这个包，即使使用vertx运行的场景。 主要会用到它的API，做一些运行时上的统一处理。

**Comment by Nick-The-Uncharted** [comment]
@liubao68 那看来只能采用规避方法了

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
