### ISSUE TITLE
接口声明是否支持/*这种通配的匹配方式

### ISSUE THREAD

**Issue by 13212199211** [apache/servicecomb-java-chassis#2329]
接口声明是否支持/*这种通配的匹配方式，例如springmvc中的@RequestMapping("/**")来通配所有请求 ，从serviceComb的源码中看貌似是不支持，那如果想做uri通配需要如何操作

**Comment by liubao68** [comment]
可以使用 `/{path: .+}`， 参考： https://howtodoinjava.com/resteasy/jaxrs-path-uri-matching/

**Comment by 13212199211** [comment]
好的多谢，经实践，使用/{path: .+}可以实现通配

**Comment by yejiahao** [comment]
感谢
