### ISSUE TITLE
通过edge转发请求后

### ISSUE THREAD

**Issue by thenumb** [apache/servicecomb-java-chassis#2330]
返回，https://github.com/apache/servicecomb-java-chassis/issues/1624 和这位老哥一样，应该怎么解决，跪求大佬帮忙解答

**Comment by thenumb** [comment]
有人知道吗？

**Comment by thenumb** [comment]
返回这个，response content-type application/json; charset=utf-8 is not supported ，我在edge看到了正确的返回body，但是对应的javatype却是string，导致解析失败，我在后端服务需要怎样处理下

**Comment by thenumb** [comment]
才能让他有正确的type

**Comment by liubao68** [comment]
这个要看下服务端的接口定义，在什么情况下返回的类型是string， 是否和接口定义一致。 

不过从描述还不能清晰的理解你的问题， 可以考虑描述下服务端是如何定义接口的，这个问题发生的过程。

**Comment by thenumb** [comment]
后端服务使用war形式部署的，用的spring  xml配置的类，初步怀疑是服务端少了某个配置类，导致的，我并不知道从controller层返回后还需要哪些类来处理resp，所以不知道应该注入哪个类来处理。我的后端服务就一个简单的controller，如图片。

![Screenshot_20210330_112408_com huawei notepad_edit_4891423401336](https://user-images.githubusercontent.com/49965251/112929362-db6ea100-914a-11eb-989f-14a2b79e376c.jpg)



我用jar包形式部署，用springboot，开启自动装配并没有遇到上述的问题，可以正确返回，有正确的javaType.
@liubao68

**Comment by thenumb** [comment]
我现在需要用war包，xml配置进行部署，希望可以帮忙解答一下。 @liubao68 谢谢大佬

**Comment by thenumb** [comment]
我好像看到我的服务启动加载的时候ResponseMeta，没有将我的返回体ErrorcodeDemo类型加载进去，这个要怎么处理下

**Comment by liubao68** [comment]
[这里](https://github.com/apache/servicecomb-samples/tree/master/java-chassis-deployment-samples)有war包部署到tomcat的例子。 

[文档](https://docs.servicecomb.io/java-chassis/zh_CN/transports/rest-over-servlet/)

不过从你的描述还是看不出什么原因。 你可以看下启动的时候，日志里面是否正确打印这个REST服务的swagger， 也可以通过注册中心查看swagger是否正确。

**Comment by thenumb** [comment]
解决
