### ISSUE TITLE
Consumer端配置的熔断在什么时候会生效

### ISSUE THREAD

**Issue by jimmyk290** [apache/servicecomb-java-chassis#2337]
做了个简单的provider和consumer两个服务，consumer端配置了consumer相关的熔断配置，但是实验下来只有当consumer不配loadbalance时才能触发consumer配置的熔断事件。但是不配loadbalance请求就不能发送到provider端，日志提示cause:IllegalStateException,message:Endpoint is empty. Forget to configure "loadbalance" in consumer handler chain?。consumer的loadbalance是必要配置？consumer配置的circuitbreak事件在何种情况下才会触发？

**Comment by liubao68** [comment]
consumer调用provider， loadbalance是必须的。 

除非熔断和异常类型有关系， 要看你是如何构造异常场景的。

**Comment by jimmyk290** [comment]
我的疑问在于，当我只有一个provider的时候，且这个仅有的provider熔断时consumer继续请求会算到能触发熔断的异常次数里吗

**Comment by liubao68** [comment]
"仅有的provider熔断时consumer继续请求" 这个会导致consumer的连接异常吗？如果是网络异常，会作为错误计数。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
