### ISSUE TITLE
vertx 和 servlet的性能差异

### ISSUE THREAD

**Issue by Pangzhihong** [apache/servicecomb-java-chassis#2338]
java-chassis用vertx和servlet 在性能上有哪些差异，是不是servlet依赖容器，而容器消耗的资源比较重 ？

**Comment by liubao68** [comment]
主要是HTTP协议实现的问题， vert.x做了很多优化， 包括支持异步编程等。

**Comment by Pangzhihong** [comment]
> 主要是HTTP协议实现的问题， vert.x做了很多优化， 包括支持异步编程等。

资源消耗是不是也是一个问题，因为servlet要开启一个容器，容器消耗是不是比vertx直接启动webserver要大

**Comment by liubao68** [comment]
资源消耗对TPS影响不是那么大，会有少量的影响。 主要是IO、线程调度等方面，对高性能场景影响比较大。不过这些方面的差异，大部分业务场景感知不到，多数场景servlet也是一个很好的选择。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
