### ISSUE TITLE
war-external-tomcat

### ISSUE THREAD

**Issue by Pangzhihong** [apache/servicecomb-java-chassis#2341]
用github 上面的war-external-tomcat 示例， 为啥服务一直注册不上注册中心的？

**Comment by Pangzhihong** [comment]
通过http://127.0.0.1:8080/hello也访问不了

**Comment by liubao68** [comment]
你可以看下启动日志，是否有加载java-chassis，以及是否有错误和异常

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
