### ISSUE TITLE
接口级超时设置不生效,永远使用全局的3.3s

### ISSUE THREAD

**Issue by yifanCandy** [apache/servicecomb-java-chassis#2344]
客户端配置:
request:
    timeout: 3300
    dialogmanager_new_arch:
      speakerDialogManagerService:
        doDialog:
          timeout: 5300

服务端swag
![image](https://user-images.githubusercontent.com/16936089/113656739-06497f80-968c-11eb-89e9-a4d8fcc003a5.png)

**Comment by liubao68** [comment]
可以调试下看下超时设置是否生效，比如配置项是否生效。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
