### ISSUE TITLE
如何改变请求体内容

### ISSUE THREAD

**Issue by thenumb** [apache/servicecomb-java-chassis#2345]
我在网关的filter改变了requestEx的bodybuffer内容值，传递到后端服务，为什么值却没有改变？

**Comment by thenumb** [comment]
可以改变值的类型吗？

**Comment by liubao68** [comment]
一般不建议修改流。 具体问题分析需要贴一下使用代码看看。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
