### ISSUE TITLE
切换LoadBalancerClientFilter到ReactiveLoadBalancerClientFilter后，默认的RoundRobinLoadBalancer实现无法找到后端实例信息

### ISSUE THREAD

**Issue by csuyinwei** [apache/servicecomb-java-chassis#2346]
spring-boot-starter-servicecomb：1.3.0
spring-cloud-starter-huawei-router：1.3.8-Greenwich
spring-cloud-starter-gateway：2.2.4.RELEASE

使用默认的Ribbon负载均衡实现，正常转发请求，发现LoadBalancerClientFilter官方已经废弃，切换到ReactiveLoadBalancerClientFilter实现，默认轮询策略是实现，报错：No servers available for service:XXX

官方提供的配置开关：
![image](https://user-images.githubusercontent.com/14899491/113798482-d7173900-9785-11eb-9c7b-7def867b6b93.png)

Ribbon在spring-cloud-gateway中已经被废弃
![image](https://user-images.githubusercontent.com/14899491/113798266-70921b00-9785-11eb-97a6-ea734a8d3798.png)

默认RoundRobinLoadBalancer实现类，获取存活实例为空
![image](https://user-images.githubusercontent.com/14899491/113798407-b51db680-9785-11eb-871c-93b5869c5901.png)

**Comment by liubao68** [comment]
spring cloud huawei 和 servicecomb 是两个完全独立的项目。 为什么项目中需要同时使用 spring-boot-starter-servicecomb 和 spring-cloud-starter-huawei-router? 

servicecomb的后续版本不再提供spring cloud相关服务发现的适配， 全部由spring cloud huawei 提供。

**Comment by csuyinwei** [comment]
不好意思，刚才看了，spring-boot-starter-servicecomb只是一个声明，实际没有引用，已经删除

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.

**Comment by csuyinwei** [comment]
您好，邮件我已收到！人生在世，快乐和痛苦本就分不清，但求它货真价实
