### ISSUE TITLE
bizkeeper模块功能咨询

### ISSUE THREAD

**Issue by xiangyanggong** [apache/servicecomb-java-chassis#2347]
场景：provider 配置了 bizkeeper
1. bizkeeper使用了hystrix实现隔离、熔断等功能
2. 隔离机制使用的是“信号量”，默认为10；
3. 隔离/熔断的粒度**是接口级别，而非服务级别**。也就是说，服务M中包含接口1和接口2，接口1的信号量为10，接口2的信号量也为10，对于接口1和接口2的熔断统计数据(失败率)也是各计算各的，两者不耦合。 即接口1被隔离/熔断后，接口2依然可以提供服务；
4. 隔离引起的失败(590)会被纳入对该接口的熔断数据(失败率)统计

我想确认的是第3、4点是否理解正确？据我现在对hystrix的了解程度，这些依赖于GroupKey和CommandKey，而bizkeeper中的这些key的生成规则为 [type].[serviceName].[endpoint].[operationId]，所以我理解是接口级别，不知道对不对？

**Comment by liubao68** [comment]
是的。 说明文档参考： https://docs.servicecomb.io/java-chassis/zh_CN/references-handlers/bizkeeper/

里面也有使用这个模块的一些注意事项和建议。 除非是很具体的业务场景需要， 根据其他产品的经验，其实不太建议默认启用这些功能。

**Comment by xiangyanggong** [comment]
> 是的。 说明文档参考： https://docs.servicecomb.io/java-chassis/zh_CN/references-handlers/bizkeeper/
> 
> 里面也有使用这个模块的一些注意事项和建议。 除非是很具体的业务场景需要， 根据其他产品的经验，其实不太建议默认启用这些功能。

ok，这个确认了就好，我们现在也在评估去除bizkeeper，使用loadbalance模块中的“隔离”机制
