### ISSUE TITLE
Allow to control the timing to register to the service center

### ISSUE THREAD

**Issue by Shoothzj** [apache/servicecomb-java-chassis#2348]
How could I register to the service center after the `heavy resources` are ready?

**Comment by liubao68** [comment]
可以考虑在注册前按照业务实际逻辑进行等待，参考事件说明： https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/event-listener/

**Comment by Shoothzj** [comment]
> 可以考虑在注册前按照业务实际逻辑进行等待，参考事件说明： https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/event-listener/

这个在Spring的main线程，想阻塞的事情也在main线程的场景，这个是不是就很困难了，

**Comment by liubao68** [comment]
如果是同一个线程， 那么需要处理的只是加载顺序问题。
