### ISSUE TITLE
微服务配置文件microservice.yaml文件中配置项参数值中存在逗号时，解析成数组。

### ISSUE THREAD

**Issue by develpoerX** [apache/servicecomb-java-chassis#2349]
问题描述：
   微服务配置文件microservice.yaml文件中配置项参数值中存在逗号时，解析成数组。eg:在配置文件中写：
hello:
    sayHelloPrefix: "Hello, ft"
使用DynamicPropertyFactory.getInstance().getStringproperty（“hello.sayHelloPrefix”, ""）时，获取到的结果为Hello,ft，中间空格被删除。通过定位发现，配置文件参数值，在传递过程中，会经过com.netflix.config包中的ConcurrentMapConfiguration.java文件中的addPropertyImpl（String key, Object value）解析时，默认将value中的逗号解析成数组的形式。

**Comment by kaister3** [comment]
可以用instanceof来判断是string还是list。参考#2288

**Comment by wujimin** [comment]
getProperty时，placeholder无法发挥作用  
可以尝试一下直接使用spirng的enviorment读取

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
