### ISSUE TITLE
@RequestBody is Not working.

### ISSUE THREAD

**Issue by DongJigong** [apache/servicecomb-java-chassis#2356]
version 2.2.1  
springmvc model,  parameter @RequestBody check error
![image](https://user-images.githubusercontent.com/8855265/115515032-4bd69100-a2b7-11eb-9011-8b6e855223a6.png)
![image](https://user-images.githubusercontent.com/8855265/115515051-509b4500-a2b7-11eb-8490-4eeeaf76b099.png)

**Comment by wujimin** [comment]
```
solution:
    change pom.xml......
```

**Comment by DongJigong** [comment]
ok. sorry about that. Yes, after I did it. It sees running fine.
