### ISSUE TITLE
配置项的默认值与源码中不匹配

### ISSUE THREAD

**Issue by xiangyanggong** [apache/servicecomb-java-chassis#2360]
Java-Chassis版本：2.2.2
问题：开发指南中有的配置的默认值与源码中的不一致，如：

【开发指南中关于“应用性能监控”的配置如下】：
配置项 | 默认值 | 含义
servicecomb.metrics.publisher.defaultLog.enabled | **false** | ...
servicecomb.metrics.publisher.defaultLog.endpoints.client.detail.enabled | **false** | ...

【源码中】
在servicecomb-java-chassis-2.2.2\solutions\solution-basic\src\main\resources\microservice.yaml中的配置如下：
servicecomb:
    metrics:
    window_time: 60000
    invocation:
      latencyDistribution: 0,1,10,100,1000
    Consumer.invocation.slow:
      enabled: true
      msTime: 1000
    Provider.invocation.slow:
      enabled: true
      msTime: 1000
    publisher.defaultLog:
      enabled: **true**
      endpoints.client.detail.enabled: **true**

希望：文档与代码保持一致

**Comment by liubao68** [comment]
文档是按照默认值写的，这个没问题。 其实需要理解的是 solution-basic， 这个是为了简化用户配置，做的一个一键式依赖，需要注意 solution-basic 会跟着版本变化而变化，请留意release notes的说明。 solution-basic 的核心内容是 pom.xml， 指定了一些常用的依赖； microsrvice.yaml， 配置一下常用的配置项。

**Comment by xiangyanggong** [comment]
原来是这样，明白了，谢谢！
