### ISSUE TITLE
升级mybatis版本从2.0.1到2.0.6，MapperScannerConfigurer.java会导致serviceComb中的ConfigurationSpringInitializer的setEnvironment提早被触发，部分配置没能加载到

### ISSUE THREAD

**Issue by tianlige** [apache/servicecomb-java-chassis#2365]
java-chassis的版本是2.1.3，mybatis2.0.6中MapperScannerConfigurer.java会导致serviceComb中的ConfigurationSpringInitializer的setEnvironment提早被触发，部分配置没能加载到

**Comment by tianlige** [comment]
![image](https://user-images.githubusercontent.com/83752608/117260884-1b2f5380-ae82-11eb-8869-f11b3463a1c8.png)

**Comment by kaister3** [comment]
mybatis2.0.1 还是 myabtis-spring2.0.1？

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
