### ISSUE TITLE
servicecomb rest 返回的时间少了8小时

### ISSUE THREAD

**Issue by cpbeast** [apache/servicecomb-java-chassis#2369]
servicecomb rest 返回的时间少了8小时，jackson 要怎么配置，springboot的配置方法不生效

**Comment by liubao68** [comment]
代码是怎么写的？ 按照道理不会出现这个情况。

**Comment by liubao68** [comment]
能否贴一下服务端接口定义和客户端调用方式？

**Comment by cpbeast** [comment]
![image](https://user-images.githubusercontent.com/41602866/117449964-2f06b280-af73-11eb-9e04-249be9871dad.png)
![image](https://user-images.githubusercontent.com/41602866/117450019-4645a000-af73-11eb-9da4-6cd9877c6a2e.png)
少了八小时

**Comment by wujimin** [comment]
`+00:00`，UTC时间

**Comment by liubao68** [comment]
嗯。 这个是没问题的。 显示的时候， 用自己的时区就可以了。 传输格式是协议标准的。

**Comment by cpbeast** [comment]
> `+00:00`，UTC时间

这个能后台处理吗，因为前端要自己去判断哪个字段是日期格式

**Comment by cpbeast** [comment]
> 嗯。 这个是没问题的。 显示的时候， 用自己的时区就可以了。 传输格式是协议标准的。

这个能后台处理吗，因为前端要自己去判断哪个字段是日期格式

**Comment by wujimin** [comment]
为何需要判定，这是标准格式呀，js直接处理
```
var d = '2021-05-07T12:30:58.835+00:00'
new Date(d)
```
输出：Fri May 07 2021 20:30:58 GMT+0800 (China Standard Time)

**Comment by cpbeast** [comment]
> 为何需要判定，这是标准格式呀，js直接处理
> 
> ```
> var d = '2021-05-07T12:30:58.835+00:00'
> new Date(d)
> ```
> 
> 输出：Fri May 07 2021 20:30:58 GMT+0800 (China Standard Time)

因为我们做的是智能报表的，前端可视化拖拽，选择一个数据模型，然后选择对应的图标，各种图，饼图，折线图，柱形图等等，拖拽字段到x，y轴之类的，其实就是拼sql，后台返回的是，不确定哪个字段是date，前端不太好转换吧，我想类似Springboot那种，配置Jackson那样，但是servicecomb 好像没有

**Comment by liubao68** [comment]
有点看不明白你的问题在哪儿，看起来只是在如何使用上与早期的差异。 返回的时间内容只要是无损的， 那么就是可以被处理的。servicecomb的日志传输编解码是OpenAPI定义的标准格式，是不允许扩展修改的，这样的好处是所有人定义一样的API，看到的结果都是一样的。 当然会存在使用上的差异。
