### ISSUE TITLE
CSE 双AZ 接口兼容问题

### ISSUE THREAD

**Issue by xiaoxiao556655** [apache/servicecomb-java-chassis#2371]
A部署版本1.1.3500, B部署版本 1.1.4100， 新老版本都有一个相同的schame 接口，区别是 1.1.3500 接口新增一个非空的属性。

查看cse日志，A  edge服务加载1.1.3500 schame接口， 客户端发起请求，并携带了新增的字段，A edge 转发该请求给后端服务，发现并没有携带这个新增的字段.

**Comment by liubao68** [comment]
是不是使用的1.x版本？ 这个版本新增字段是不兼容修改。 不允许出现低版本比高版本多字段的场景。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
