### ISSUE TITLE
servicecomb在SC故障恢复后有可能不刷新实例缓存

### ISSUE THREAD

**Issue by johnyannj** [apache/servicecomb-java-chassis#2382]
1、servicecomb在heartbeat失败的时候，进入safe模式。

2、在safe模式下，
		
假设SC恢复了，从SC发现节点不为0，CSE内存会一直累加实例，不删除。
导致从内存缓存的实例可能比SC里实际的多，但是也会记录从SC返回的revision

3、此后heartbeat成功，safe模式退出。

4、但是后面如果SC里的实例节点不变化了，revision就不变，内存缓存就会一直得不到刷新。

**Comment by kaister3** [comment]
未能复现此问题，能否提供复现方法？

**Comment by johnyannj** [comment]
@kaister3 
屏蔽掉consumer和注册中心
取消屏蔽consumer和注册中心，同时快速下线一个provider节点

会发现这个provider节点一直在consumer的缓存里

**Comment by liubao68** [comment]
修复方案参考：https://github.com/apache/servicecomb-java-chassis/pull/2412。 方案性变化，在2.3.0修复， 老版本不提供修复。
