### ISSUE TITLE
当前不支持跨应用限流

### ISSUE THREAD

**Issue by fanjiwang1992** [apache/servicecomb-java-chassis#2385]

**Comment by liubao68** [comment]
可以的， 参考： http://servicecomb.gitee.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/references-handlers/ratelimit/

服务名称使用 APP:SERVICE 即可。 


也可以尝试新的治理策略：http://servicecomb.gitee.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/references-handlers/governance/

**Comment by fanjiang-2021** [comment]
好的
