### ISSUE TITLE
How limit sendqueue size?

### ISSUE THREAD

**Issue by jr981008** [apache/servicecomb-java-chassis#2388]
how limit sendqueue size
org.apache.servicecomb.common.rest.filter.inner.ServerRestArgsFilter#beforeSendResponseAsync 
![image](https://user-images.githubusercontent.com/20749545/118804236-023d8e00-b8d7-11eb-978b-0878165a5539.png)

in my case，per request have more than 100M data to send，always OOM，

**Comment by wujimin** [comment]
100MB？  
better to use download feature

**Comment by liubao68** [comment]
If you are using REST, response is encoded to JSON, this will take a lot of memory. As per suggested by wujimin, using file download if possible.

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
