### ISSUE TITLE
通过contract first开发方式，契约没有注册到注册中心

### ISSUE THREAD

**Issue by wangshuncai** [apache/servicecomb-java-chassis#2392]
问题描述： 参照文档使用contract first的开发方式，通过手动编写契约，讲契约放置要求的位置，启动微服务应用（使用本地注册中心），可以在注册中心看到注册上来的微服务，到时在schema页面，没有看到手动编写的契约，只能看到通过annotation注解生成的契约。

参考链接：https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/define-contract/

实际截图：
![contract1](https://user-images.githubusercontent.com/7950092/118913248-a79a4580-b95b-11eb-9f1d-27cde162c1fb.png)
![contract2](https://user-images.githubusercontent.com/7950092/118913249-a8cb7280-b95b-11eb-9b60-2431814419dd.png)
![contract3](https://user-images.githubusercontent.com/7950092/118913251-a9fc9f80-b95b-11eb-81a5-7d266eb8631b.png)
![contract4](https://user-images.githubusercontent.com/7950092/118913253-aa953600-b95b-11eb-8d78-bcdc655b7fdf.png)

**Comment by liubao68** [comment]
你可以尝试调试下： ProducerProviderManager registerSchema 方法。 比如是不是目录名称拼写错误了导致读取不到。

**Comment by kaister3** [comment]
把yaml文件名改成全限定类名试试。调试方法同上。
