### ISSUE TITLE
是否存在机制或者接口在微服务启动之后,能够进行服务发现

### ISSUE THREAD

**Issue by fanjiwang1992** [apache/servicecomb-java-chassis#2397]
背景: 目前再做管理面的可靠性研究,想最大程度的降低注册中心挂掉的影响
目的: 想通过配置的方式,设置微服务直接的调用关系,在微服务往注册中心注册之后,读取他们的调用关系,进行服务发现

**Comment by liubao68** [comment]
搭配本地注册中心一起用就可以了。 [参考](http://servicecomb.gitee.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/registry/introduction/)

**Comment by fanjiang-2021** [comment]
> 搭配本地注册中心一起用就可以了。 [参考](http://servicecomb.gitee.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/registry/introduction/)

**Comment by fanjiang-2021** [comment]
> 搭配本地注册中心一起用就可以了。 [参考](http://servicecomb.gitee.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/registry/introduction/)

(刚刚不小心操作失误关闭了)我看了一下 单配本地注册中心的话,实例的endpoint是写死的,由于我们的服务是部署在k8s中,它的endpoint是浮动的

**Comment by fanjiang-2021** [comment]
不同的注册发现机制，可能注册的信息和发现的信息不包括上述信息的全集，可以通过组合不同的注册发现机制，提供完整的信息。 比如，可以通过 mDNS 的方式发现网络地址(endpoints)信息， 可以通过配置文件的方式，发现契约信息。

mDNS的方式有最佳实践集成demo吗?
