### ISSUE TITLE
实例变更的可靠性测试问题

### ISSUE THREAD

**Issue by fanjiang-2021** [apache/servicecomb-java-chassis#2398]
背景:
在k8s环境中,将注册中心以及提供端A和提供端B重启,
由于endpoint是由k8s随机分配的浮动IP,提供端A老的IP被另外一个提供端B占用,
此时消费端C内存中缓存了提供端A的老的IP,以及新的IP,老的IP没有通知下线,
导致消费端C调提供端A,会出现概率性调用失败
-------------------------------------------------------

**Comment by liubao68** [comment]
按照目前的服务发现机制，这种情况是预期会发生的情况，是设计可接纳的。

**Comment by liubao68** [comment]
注册中心和提供端同时重启属于一个特殊的情况。 [PR](https://github.com/apache/servicecomb-java-chassis/pull/2406) 可以帮助缓解这个场景下的问题。

**Comment by liubao68** [comment]
这个问题是safemode机制处理导致的问题， [PR](https://github.com/apache/servicecomb-java-chassis/pull/2412) 优化了实例查询的机制。
