### ISSUE TITLE
根据特定条件，指定访问某一实例

### ISSUE THREAD

**Issue by SenixCoder** [apache/servicecomb-java-chassis#2399]
一个服务端存在多个实例，客户端想要根据某些条件访问指定实例（例如上一次接口调用的），该怎么去做呢？

我看文档中写到
``` 
Endpoint 描述当前请求需要发往的实例地址。 这个 context 参数只能够在 consumer 端的 PRC 接口使用。当 微服务存在多个实例的时候，可以使用这种方式指定将请求发往哪个实例。
```
这个SchemaDiscoveryService接口该怎么使用呢？

这个接口和AbstractEndpointDiscoveryFilter该使用哪一个呢？

**Comment by fanjiang-2021** [comment]
可以实现这个接口看看 org.apache.servicecomb.loadbalance.ServerListFilterExt  类似灰度

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
