### ISSUE TITLE
sc 任务超时

### ISSUE THREAD

**Issue by fanjiwang1992** [apache/servicecomb-java-chassis#2401]
sc task taken more than 203934ms to execute | org.apache.servicecomb.serviceregistry.task.ServiceCenterTaskMonitor.endCycle(ServiceCenterTaskMonitor.java:51)  
这种情况有人遇到吗

**Comment by liubao68** [comment]
看起来有点不可思议。 是偶然发生的，还是一段时间内一直报告这个错误？ 如果一直报错，可以试试jstack抓取堆栈看看， 系统在哪个地方繁忙。 
也可以先观察下系统负载，当CPU过高或者内存不足的情况下（垃圾回收），也可能导致类似的现象。

**Comment by fanjiang-2021** [comment]
这个是偶然发生的,业务上传大量文件,目前环境已经重启 后续我继续跟踪看看
