### ISSUE TITLE
ServiceComb 服务与服务之间是怎么做认证的？

### ISSUE THREAD

**Issue by Pangzhihong** [apache/servicecomb-java-chassis#2405]
ServiceComb 服务与服务之间是怎么做认证的？ 我看在服务里面直接调用其他服务，其中有没有一些认证过程啊，比如证书认证？

**Comment by liubao68** [comment]
默认没提供认证机制。 你可以配置[证书认证（TLS）](http://servicecomb.gitee.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/security/tls/)、[公钥认证](http://servicecomb.gitee.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/security/shi-yong-rsa-ren-zheng/)等， 以及添加自己的认证。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
