### ISSUE TITLE
CSE2.0】创建配置点击更新，配置停用再启用，配置变更不生效

### ISSUE THREAD

**Issue by develpoerX** [apache/servicecomb-java-chassis#2410]
实例启动注册后，当前配置生效，点击更新，停用配置，此时配置变更生效；3、再点击更新，修改状态为启用，SDK没有收到推送变更的通知，配置也没生效

**Comment by develpoerX** [comment]
经过定位，这是因为当配置只有一条时，后续启动和关闭导致MD5值没有被刷新，进一步造成配置没有被刷新。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
