### ISSUE TITLE
微服务之间调用逻辑 当http返回状态码为异常码时 代码直接进入了异常

### ISSUE THREAD

**Issue by five111** [apache/servicecomb-java-chassis#2411]
![image](https://user-images.githubusercontent.com/19482564/121671779-91f2e880-cae1-11eb-91d3-df64eefd3498.png)
这个接口返回的状态吗是500 或者403 我希望通过http状态码去处理一部分逻辑
但是代码直接进入了这个

![image](https://user-images.githubusercontent.com/19482564/121671952-c5ce0e00-cae1-11eb-9a1f-37810483be01.png)

**Comment by liubao68** [comment]
可以参考下[异常处理](http://servicecomb.gitee.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/general-development/error-handling.html) 的描述
