### ISSUE TITLE
配置线程池，是用executors，还是executor？开发指南多处说明不一致

### ISSUE THREAD

**Issue by xiaoyuer11** [apache/servicecomb-java-chassis#2424]
![image](https://user-images.githubusercontent.com/39411325/122695230-6787f480-d272-11eb-8b72-65ddc8bfeb5d.png)
![image](https://user-images.githubusercontent.com/39411325/122695268-7c648800-d272-11eb-9674-680e92c12a75.png)

**Comment by liubao68** [comment]
你截图的内容都是真实情况， 是不同的配置项。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
