### ISSUE TITLE
传递中文乱码

### ISSUE THREAD

**Issue by chenchanglong1997** [apache/servicecomb-java-chassis#2427]
实现httpClintFilter,   向里面传中文value,解析乱码 
客户端：public void beforeSendRequest(Invocation invocation, HttpServletRequestEx requestEx) {
        // 发送前设置上下文，传输到服务端
        TransferContextHelper.injectCommonContext(invocation,
            (TransferContextHelper.Setter<Invocation>) (request, key, value) -> invocation.addContext(key, value));

服务端    public Response afterReceiveRequest(Invocation invocation, HttpServletRequestEx requestEx) {
        ContextManager.clearAll();
        TransferContextHelper.extractCommonContext(invocation, InvocationContext::getContext);

**Comment by liubao68** [comment]
Http协议里面明确了header只支持一种编码，不能使用中文。 如果需要使用中文，需要业务自行编码后，在设置到header， 使用端自行解码。
