### ISSUE TITLE
有2个provider，当某个provider出现网络时延时，2个provider的吞吐量都下降了，是什么机制导致的吗？

### ISSUE THREAD

**Issue by kissLife** [apache/servicecomb-java-chassis#2429]
有2个provider，然后在某1个provider上模拟网络时延（另1个provider保持正常），当consumer调用时，发现2个provider的吞吐量都下来了，从之前的280TPS降到了60TPS

**Comment by liubao68** [comment]
受consuemr共享线程池的影响，一个请求慢了， 其他快的请求也会等待线程池被释放。

**Comment by wujimin** [comment]
```
jmeter -> consumer -> provider 1/2
```
如果是这个流程  
consumer首先是一个provider，默认使用一个共享线程池处理所有请求  
收到请求后，再   **同步**   调用后面的provider，此时会阻塞当前线程等待provider应答，这个“当前线程”，就是共享线程池里的线程  
所以，某个provider慢，会影响整体速度  

所有的同步调用，都会面临这种问题，要彻底解决，业务需要从同步改为异步方式调用后面的provider

**Comment by kissLife** [comment]
@liubao68  @wujimin

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
