### ISSUE TITLE
CRL没有验证颁发者

### ISSUE THREAD

**Issue by xinadfga** [apache/servicecomb-java-chassis#2432]
请问一下：软件是不是没有校验传入crl文件的颁发者？只是通过revoked函数来校验证书序列号，但是序列号有可能是不唯一的。（序列号只在同个CA下唯一，不同CA下可能是不唯一的）
![image](https://user-images.githubusercontent.com/86401349/123219932-02e1c980-d500-11eb-997f-42a10014f8de.png)
这样是不是有可能导致错误吊销的情况。合理的做法是不是：先找到owner的颁发者A，再判断当前crl是否为A颁发的，如果是才调用revoked函数执行吊销检查。求作者解惑。

**Comment by liubao68** [comment]
你的理解有碰到实际情况吗，或者有参考文献吗？ JDK 提供了函数， 估计应该会考虑到这个问题。 但你说的情况是否存在， 并没查询到相关资料。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
