### ISSUE TITLE
【偶现大概率】微服务启动后在服务中心有实例，但是契约为空，需要将版本号+1重启服务才能恢复

### ISSUE THREAD

**Issue by mikkocheng** [apache/servicecomb-java-chassis#2434]
微服务启动后在服务中心有实例，但是契约为空，需要将版本号+1重启服务才能恢复，是偶现问题，但是是大概率
![image](https://user-images.githubusercontent.com/15166997/123503975-eae98180-d688-11eb-884b-882d7ccf2751.png)

**Comment by liubao68** [comment]
能描述下重现步骤和条件吗？或者提供一个简单DEMO示例。

**Comment by mikkocheng** [comment]
> 能描述下重现步骤和条件吗？或者提供一个简单DEMO示例。

这是个偶现问题，目前还不知道怎么样让他必现。等遇到了我们找你会议一起看下吧。另外请问下之前有这种类似案例吗，契约为空一般都是什么原因，我们也好自己排查下

**Comment by diwenzheng** [comment]
> > 能描述下重现步骤和条件吗？或者提供一个简单DEMO示例。
> 
> 这是个偶现问题，目前还不知道怎么样让他必现。等遇到了我们找你会议一起看下吧。另外请问下之前有这种类似案例吗，契约为空一般都是什么原因，我们也好自己排查下

我之前遇到过,频繁重新更新服务 会导致这个问题,一直没当回事,考虑
1.etcd缓存没及时更新
2.服务测配置与注册中心交互心跳线程出现超时会异常.

**Comment by liubao68** [comment]
是否用了service-center提供的SCA功能？ 即服务会在不同的注册中心注册。 记得早些时候，使用SCA的服务出现过类似问题，当多个region的服务通过SCA并发注册的时候，会出现这个问题。 解决方案是需要避免在SCA场景下， 不同region的微服务版本相同。

**Comment by diwenzheng** [comment]
是的,目前我们也是这么解决的

liubao68 ***@***.***> 于2021年7月5日周一 上午10:02写道：

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
