### ISSUE TITLE
RestConstroller  producer and consumer APPLICATION_VALUE_XML dataType not accept.

### ISSUE THREAD

**Issue by DongJigong** [apache/servicecomb-java-chassis#2435]
Is there any way to deal with the Xml type rest data?

**Comment by liubao68** [comment]
java chassis now only support mapping object with json, do not support xml yet.

**Comment by DongJigong** [comment]
> java chassis now only support mapping object with json, do not support xml yet.

I have resolve this problem in some other way. It would be nicer to support xml restful data. Could be this add in future feature

**Comment by chenchanglong1997** [comment]
> > java chassis now only support mapping object with json, do not support xml yet.
> 
> I have resolve this problem in some other way. It would be nicer to support xml restful data. Could be this add in future feature

可否告知如何解决的？

**Comment by DongJigong** [comment]
@chenchanglong1997 @RequestBody  receive String  xml data then parse to java bean. return with xml String data.
![image](https://user-images.githubusercontent.com/8855265/124684416-ae781a00-df01-11eb-9bb8-01dd21f866a8.png)
![image](https://user-images.githubusercontent.com/8855265/124684448-c51e7100-df01-11eb-856e-6f64bda88572.png)

**Comment by liubao68** [comment]
看历史合入记录，有提供xml简单扩展支持： https://github.com/apache/servicecomb-java-chassis/commit/ec3ec37e9fa18d1b2ec310f9d749b617d0938d4e#diff-f1bc9aab98b85867c7c9ccd4d96c3471d18291db7445075b24b37c8afadd6f77

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
