### ISSUE TITLE
ServiceComb如何配置Controller的mapping忽略大小写

### ISSUE THREAD

**Issue by haijianfengying** [apache/servicecomb-java-chassis#2437]
使用@EnableWebMvc @Configuration 注解无法注入WebMvcConfigurationSupport。通过这个类的配置忽略大小写失败。
有没有ServiceComb的修改方法？
代码Controller中：
@PostMapping(value = "/deviceInfo" //接口声明
其中I是大写，客户端如果使用 xxx/deviceinfo 请求，则ServiceComb报如下日志。想忽略url的大小写ServiceComb有没有配置的方法？
错误日志：
17:39:30.035 [vert.x-eventloop-thread-15] ERROR org.apache.servicecomb.common.rest.locator.OperationLocator - locate path failed, status:Not Found, http method:POST, path:/iothome/app/v1/deviceinfo/, microserviceName:iot-command-adapter-service

**Comment by liubao68** [comment]
servicecomb和Spring MVC是两个完全不同的RPC框架， 只是在REST标签支持上有共同的地方。 参考[文档](https://servicecomb.apache.org/references/java-chassis/zh_CN/build-provider/springmvc.html)和[文档](https://servicecomb.apache.org/references/java-chassis/zh_CN/using-java-chassis-in-spring-boot/diff-spring-mvc.html)

**Comment by haijianfengying** [comment]
> servicecomb和Spring MVC是两个完全不同的RPC框架， 只是在REST标签支持上有共同的地方。 参考[文档](https://servicecomb.apache.org/references/java-chassis/zh_CN/build-provider/springmvc.html)和[文档](https://servicecomb.apache.org/references/java-chassis/zh_CN/using-java-chassis-in-spring-boot/diff-spring-mvc.html)

使用ServiceComb如何忽略Mapping大小写呢？

**Comment by liubao68** [comment]
URL是大小写敏感的，java-chassis不支持忽略大小写的配置。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
