### ISSUE TITLE
如何打开servicecomb.codec.printErrorMessage=true配置项

### ISSUE THREAD

**Issue by haijianfengying** [apache/servicecomb-java-chassis#2438]
参数校验异常后日志中出现“Add servicecomb.codec.printErrorMessage=true to print the details.”
这个配置项在哪个配置文件中配置能够生效呢

**Comment by DongJigong** [comment]
Of course. this config will work. Y can try to find out.

**Comment by liubao68** [comment]
可以了解下[通用配置说明](http://servicecomb.gitee.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/config/general-config.html)  ， 一般就是 `microservice.yaml`

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
