### ISSUE TITLE
On branch 1.3.x, QpsControllerManager throws NPE when the qps limit config property is changed to null

### ISSUE THREAD

**Issue by yhs0092** [apache/servicecomb-java-chassis#2442]
Problem scene:
I'm using Java-Chassis 1.3.2. A NullPointerException is thrown from https://github.com/apache/servicecomb-java-chassis/blob/cef9dedbd7a84a9845458c5c372c01021e821750/handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/QpsControllerManager.java#L207
, when a microservice instance can get qps limit configuration from a config center dynamically, and I only set one qps limit property on any of service/schema/operation level and then remove it

**This seems a known problem.** Because there seems a patch pull request for the master branch. In this pull request, the method `updateObjMap` on branch master will check whether the `qpsStrategy` returned by `searchQpsController` is null and handle it accordingly.

Here seems the corresponding pull request: https://github.com/apache/servicecomb-java-chassis/pull/2287

**Comment by liubao68** [comment]
fixed
