### ISSUE TITLE
Java-Chassis在跨应用调用的场景下, consumer传递给provider的微服务名没有遵循跨应用调用的格式

### ISSUE THREAD

**Issue by yhs0092** [apache/servicecomb-java-chassis#2443]
consumer会在`InvocationContext`中设置`x-cse-src-microservice`来标识自己的微服务名. 但是这个设置机制没有区分同应用调用和跨应用调用, 导致跨应用调用场景下, `x-cse-src-microservice`键的值仍然是只有微服务名称的, **而不是**`<APPLICATION_ID>:<微服务名>`的格式.
这会导致用户配置provider端限流等涉及provider感知consumer微服务名的场景, 用户体验不一致. 即跨应用调用场景下, 有些配置下需要给微服务名加上APPLICATION_ID前缀, 有些配置又不能加.

**Comment by yhs0092** [comment]
考虑到兼容性问题, 可能没那么好找到妥善的解决办法? 这个问题还有没有可能修复呢?

**Comment by liubao68** [comment]
有什么特殊场景，必须包含application吗？ 
如果场景非常重要，可以考虑头信息里面加上application信息。 主要要评估增加额外信息的必要性。 好像很少场景必须使用这个头。

**Comment by fanjiang-2021** [comment]
这个问题 我们也遇到过 我们的处理方式 是在core/src/main/java/org/apache/servicecomb/core/invocation/InvocationFactory.java
做了处理,具体处理方案是这样的:
<html>
<body>


String microserviceName = RegistrationManager.INSTANCE.getMicroservice().getServiceName();
--
  |   | 46 | +    String microserviceAppID = RegistrationManager.INSTANCE.getAppId();
  |   | 47 | +    if (null != microserviceAppID && !(microserviceAppID.equals(invocation.getAppId()))){
  |   | 48 | +      microserviceName = microserviceAppID + ":" + microserviceName;
  |   | 49 | +    }
46 | invocation.addContext(Const.SRC_MICROSERVICE, microserviceName); | 50 | invocation.addContext(Const.SRC_MICROSERVICE, microserviceName);
47 | return invocation; | 51 | return invocation;


</body>
</html>

**Comment by yhs0092** [comment]
@liubao68  是有业务同事反馈他们做流控的时候, 跨应用调用场景下provider这边限制跨应用consumer的流量, 他们以为要配置的对端微服务名称是`consumer_APP_ID:consumer_microservice_name` 这样的, 结果由于InvocationContext里面携带的consumer微服务名只有`consumer_microservice_name`这段, 导致配置不生效. 这个主要是用户体验不太好, 跟资料里面一直宣称的跨应用调用需要在微服务名配置上加上`APP_ID:`前缀的说法不匹配.

@fanjiang-2021  比较理想的处理方式确实是这样的

**Comment by liubao68** [comment]
在Context里面增加两个头： APPID+INSTANCEID， 大家觉得怎么样？

**Comment by yhs0092** [comment]
加一个INSTANCEID挺好的, 这样可以表示很多信息, 对端的APPID, microserviceName, version 等等, 这样APPID是不是也没必要加了呀?

**Comment by liubao68** [comment]
fixed in https://github.com/apache/servicecomb-java-chassis/pull/2526 , try 2.5.1
