### ISSUE TITLE
handler能否获取response对象，希望拿到responseBody

### ISSUE THREAD

**Issue by yfliuas** [apache/servicecomb-java-chassis#2444]
handler能否获取response对象，希望拿到responseBody

**Comment by liubao68** [comment]
Handler的Invocation包含了已经解析的Response。 

```
  invocation.next(response -> ...)
```

**Comment by wisper-shadow** [comment]
> Handler的Invocation包含了已经解析的Response。
> 
> ```
>   invocation.next(response -> ...)
> ```

在next中使用lambda函数确实可以去到JsonObject响应，但是处理后，asyncResp不再向后传递，后续Filter不执行，且接口不返回结果，拿到responseBody的最佳实践应该是什么呢？

**Comment by liubao68** [comment]
你说的Filter也是Handler吧？ 他的执行流程参考 http://servicecomb.gitee.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/start/design.html

![](http://servicecomb.gitee.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/start/runtime-model.png)

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
