### ISSUE TITLE
edge route to provider Get request paramters lost

### ISSUE THREAD

**Issue by DongJigong** [apache/servicecomb-java-chassis#2448]
`
package com.kejue.edge.config;

import io.vertx.core.http.Cookie;
import io.vertx.ext.web.Router;
import io.vertx.ext.web.RoutingContext;
import org.apache.servicecomb.edge.core.AbstractEdgeDispatcher;
import org.apache.servicecomb.edge.core.EdgeInvocation;

import java.util.Map;

public class ApiDispatcher extends AbstractEdgeDispatcher {
  @Override
  public int getOrder() {
    return 10002;
  }

  @Override
  public void init(Router router) {
    String regex = "/api/([^\\/]+)/(.*)";
    router.routeWithRegex(regex).handler(createBodyHandler());
    router.routeWithRegex(regex).failureHandler(this::onFailure).handler(this::onRequest);
  }

  protected void onRequest(RoutingContext context) {
    Map<String, String> pathParams = context.pathParams();
    String microserviceName = pathParams.get("param0");
    String path = "/" + pathParams.get("param1");

    System.out.println(context.request().params().get("out_trade_no")+"=====");
    EdgeInvocation invoker = new EdgeInvocation() {
      // Authentication. Notice: adding context must after setContext or will override by network
      protected void setContext() throws Exception {
        super.setContext();
        // get session id from header and cookie for debug reasons
        String sessionId = context.request().getHeader("session-id");
        if (sessionId != null) {
          this.invocation.addContext("session-id", sessionId);
        } else {
          Cookie sessionCookie = context.cookieMap().get("session-id");
          if (sessionCookie != null) {
            this.invocation.addContext("session-id", sessionCookie.getValue());
          }
        }
      }
    };
    System.out.println(context.getBodyAsString("UTF-8"));
    context.request().headers().addAll(context.request().params());
    invoker.init(microserviceName, context, path, httpServerFilters);
    invoker.edgeInvoke();
  }
}
`
![image](https://user-images.githubusercontent.com/8855265/124216257-67b4a980-db28-11eb-9152-1416c6293f44.png)
![image](https://user-images.githubusercontent.com/8855265/124216318-93379400-db28-11eb-9eb6-5e20bb350c3f.png)

**Comment by DongJigong** [comment]
provider service using servlet mode.

**Comment by liubao68** [comment]
The code looks fine and can not fiure out where the problem is. Maybe you can write a simple short demo first and check if it works. 

And you can check service center and look at the swagger generated by this method, if it is correct and contains the expected parameter.

**Comment by DongJigong** [comment]
I have change this using @QueryBean and annotation field @QueryParam ,then It works fine.
