### ISSUE TITLE
偶现The request is rejected. Cannot process the request due to STATUS = DOWN的问题根源是什么

### ISSUE THREAD

**Issue by fanjiang-2021** [apache/servicecomb-java-chassis#2452]
业务容器化部署的时候,偶现The request is rejected. Cannot process the request due to STATUS = DOWN,观察内存,无任何异常

**Comment by fanjiang-2021** [comment]
[HbaseStoreTask-Hadoop_C1-Consumer-60]2021-07-06 06:22:00,831[WARN ]  | The request is rejected. Cannot process the request due to STATUS = DOWN | org.apache.servicecomb.core.SCBEngine.ensureStatusUp(SCBEngine.java:314)
[HbaseStoreTask-Hadoop_C1-Consumer-60]2021-07-06 06:22:00,831[ERROR]  | send update msg fail, exception=Exception:org.apache.servicecomb.swagger.invocation.exception.InvocationException[N]InvocationException: code=503;msg=CommonExceptionData [message=The request is rejected. Cannot process the request due to STATUS = DOWN][N]         at org.apache.servicecomb.core.SCBEngine.ensureStatusUp(SCBEngine.java:315)[N]          at org.apache.servicecomb.core.SCBEngine.getReferenc*****#*#*****Engine.java:326)[N]            at org.apache.servicecomb.provider.springmvc.referenc*****#*#*****st.findReferenc*****#*#*****pRequest.java:181)[N]             at org.apache.servicecomb.provider.springmvc.referenc*****#*#*****st.createRequestMeta(CseClientHttpRequest.java:163)[N]                at org.apache.servicecomb.provider.springmvc.referenc*****#*#*****st.execute(CseClientHttpRequest.java:144)[N]          at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:739)[N]              at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:674)[N]                at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:418)[N]          at org.apache.servicecomb.provider.springmvc.referenc*****#*#*****r.postForObject(RestTemplateWrapper.java:113)[N]              at com.huawei.ryoma.ude.service.core.component.UdeAgentTaskService.sendResultMsg(UdeAgentTaskService.java:130)[N]               at com.huawei.seq.common.task.rmiservice.TaskAgentMgr.sendUpdataMsg(TaskAgentMgr.java:178)[N]           at com.huawei.seq.common.task.Agent.updateTaskStatus(Agent.java:456)[N]         at com.huawei.seq.common.task.Agent.dynamicAgentRunner(Agent.java:271)[N]               at com.huawei.seq.common.task.Agent.run(Agent.java:245)[N]              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[N]           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)[N]           at java.lang.Thread.run(Thread.java:748)[N] | com.huawei.seq.common.task.rmiservice.TaskAgentMgr.sendUpdataMsg(TaskAgentMgr.java:181)
[HbaseStoreTask-Hadoop_C1-Consumer-60]2021-07-06 06:22:00,836[WARN ]  | The request is rejected. Cannot process the request due to STATUS = DOWN | org.apache.servicecomb.core.SCBEngine.ensureStatusUp(SCBEngine.java:314)

**Comment by liubao68** [comment]
需要保证在服务正常启动以后调用其他服务，参考[服务事件](http://servicecomb.gitee.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/build-provider/event-listener.html) 。 如果服务没启动完毕，就调用其他服务，就会出现这个错误。

**Comment by fanjiang-2021** [comment]
我当时看了业务的代码 他们的确是保证服务正常启动以后才调用其他服务,所以 这个很奇怪,而且他们前一秒还是可以调通的 后面就失败了

**Comment by fanjiang-2021** [comment]
所以想确认一下 这个的原理,什么样的情况会触发down的状态

**Comment by liubao68** [comment]
默认就是down状态， 注册成功才是up状态。 个人感觉不是其他地方触发的。 你需要看下奇怪现象是不是不同的线程，另外， 调用其他服务是不是在AFTER_REGISTRY事件以后。

**Comment by fanjiang-2021** [comment]
问题现在清楚了 是业务自己实现了一个监听器 将服务给destroy了  从而导致状态变成down,但是服务进程还存在

**Comment by fanjiang-2021** [comment]
针对这个问题 提个意见不知道合不合理:
