### ISSUE TITLE
servicecomb使用原生java filter，如何支持ThreadLocal

### ISSUE THREAD

**Issue by JasonBeiJing** [apache/servicecomb-java-chassis#2453]
基于cse RestServlet发布的api，默认cse注册的RestServlet是开启异步支持的，如果我们添加javax.servlet.Filter并通过@WebFilter(filterName = "xxxx", urlPatterns = "/api/*", asyncSupported = true)启用filter，其中asyncSupported = true是必须的（因为RestServlet的异步是开启的）。我们一般会在filter做一些拦截处理然后设置一些线程变量进ThreadLocal，这个时候发现ThreadLocal是不起作用的，因为asyncSupported = true，导致filter中和后续api的执行线程不是同一个线程，请问cse这块有没有什么解决方案？

**Comment by liubao68** [comment]
要结合业务场景分析下解决方案。单纯从技术角度来讲，使用异步的情况下， 不要使用 ThreadLocal， 或者业务能够完整控制各个地方的线程切换，并在线程切换的时候，清理本线程的ThreadLocal并合理设置下一个线程的ThreadLocal。 

多数的拦截截止，可以使用java-chassis提供的 `Handler` 或者 `HttpServerFilter` 等， 使用 InvocationContext， java-chassis会处理InvocationContext 的传递。 参考：http://servicecomb.gitee.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/build-provider/context-param.html

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
