### ISSUE TITLE
部署RestServerVerticle时不能充分利用所有EventLoop线程

### ISSUE THREAD

**Issue by jushuang-lyy** [apache/servicecomb-java-chassis#2454]
1）应用启动，部署RestServerVerticle阶段，框架默认设置了WorkerPoolName、WorkerPoolSize。
![image](https://user-images.githubusercontent.com/62862072/124596207-95854f80-de94-11eb-888d-46ad4b404da7.png)
2）部署Verticle实例的逻辑中，会根据WorkerPoolName是否为空来决定是否创建WorkerExecutor。创建WorkerExecutor时，会从vertx对象获取ContextImpl，并把WorkerExecutor加入到ContextImpl的CloseHooks中。
3）部署Verticle实例的逻辑中，会再次从vertx对象获取ContextImpl，用来执行Verticle实例的init和start逻辑，将Verticle实例和ContextImpl（EventLoop线程）绑定。
![11](https://user-images.githubusercontent.com/62862072/124597806-7be50780-de96-11eb-9722-f532592caff5.png)
4）以上逻辑都在main主线程执行，而在主线程中，每次从vertx对象获取ContextImpl，实际上是遍历一个EventLoopGroup成员。
![image](https://user-images.githubusercontent.com/62862072/124597960-b058c380-de96-11eb-8294-46438750524c.png)

也就是说，每部署一个RestServerVerticle实例，EventLoopGroup成员被遍历两个，RestServerVerticle实例与EventLoop实例的绑定关系大概是：RestServerVerticle-0绑定EventLoop-1、RestServerVerticle-2绑定EventLoop-3、RestServerVerticle-3绑定EventLoop-5……。
框架未开放EventLoopGroupSize配置，默认值是cpucore*2，一定是偶数，因此无论将RestServerVerticle实例数设置为多少，所有RestServerVerticle实例都只能绑定到一半的EventLoop线程，无法充分利用所有EventLoop线程，无法充分利用所有cpucore。

**Comment by wujimin** [comment]
如果是这样的，确实与期望的不符，需要确认一下  
@liubao68 看一下？

**Comment by liubao68** [comment]
`每部署一个RestServerVerticle实例，EventLoopGroup成员被遍历两个，RestServerVerticle实例与EventLoop实例的绑定关系大概是：RestServerVerticle-0绑定EventLoop-1、RestServerVerticle-2绑定EventLoop-3、RestServerVerticle-3绑定EventLoop-5`

意思是vert.x绑定eventloop线程的逻辑有问题？ 还是说这个逻辑是正确的，必须保证使用基数的eventloop线程数？

**Comment by wujimin** [comment]
我一直以为是连续的  
如果当前eventloop已经分配到了1(第一个为0)，共有4个eventloop，此时需要创建4个verticle，期望是2/3/0/1

**Comment by jussssss** [comment]
看起来是vert.x的逻辑有问题，在一次部署Verticle逻辑里，WorkerExecutor被两次添加到不同的Context的CloseHook里。
https://stackoverflow.com/questions/63466734/how-does-vertx-create-eventloop-thread
找到一个相同的问题，但没有结论。准备给vert.x提个issue。

我觉得chassis框架目前可以做的是开放WorkerPool配置，把是否需要WorkerPool及WorkerPoolSize交给业务控制。

**Comment by jussssss** [comment]
vertx issue https://github.com/eclipse-vertx/vert.x/issues/4006

**Comment by liubao68** [comment]
我们正在计划升级vert.x 4. 但是在等待netty的版本，vert.x依赖了netty 4.1.6x版本， 目前netty的6x版本有些功能性问题，还不敢集成。

**Comment by liubao68** [comment]
alreay updated to vert.x 4
