### ISSUE TITLE
cse如何实现xml入参与javaBean的转换（或重写BodyProcessorCreator）

### ISSUE THREAD

**Issue by rhy18636090373** [apache/servicecomb-java-chassis#2456]
contentType不为APPLICATION_JSON走这儿，这么能实现转化xml为javaBean(请求入参为xml的反序列化为javaBean而不是String)

源代码如下：
      if (!contentType.isEmpty() && !contentType.startsWith(MediaType.APPLICATION_JSON)) {
        // TODO: we should consider body encoding
        return IOUtils.toString(inputStream, StandardCharsets.UTF_8);
      }

**Comment by liubao68** [comment]
java chassis设计上没支持xml， 需要评估下是否提供xml支持。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
