### ISSUE TITLE
对请求设置了超时时间为200ms，从实际调用耗时来看用了1s200ms+，超时设置未生效

### ISSUE THREAD

**Issue by Zhanhaoxin** [apache/servicecomb-java-chassis#2462]
超时设置如下：
    AppGalleryJointContentService:AppGalleryJForumContentService:
      usage-topic:
        batchGetTopicProfiles:
          timeout: 1000
      usage-composite:
        queryRecommendHotspots:
          timeout: 200

实际调用的方法为queryRecommendHotspots，耗时1s200ms

**Comment by liubao68** [comment]
可以[收集下metrics日志](https://servicecomb.apache.org/references/java-chassis/zh_CN/featured-topics/performance.html)，看看耗时环节。

**Comment by Zhanhaoxin** [comment]
> 可以[收集下metrics日志](https://servicecomb.apache.org/references/java-chassis/zh_CN/featured-topics/performance.html)，看看耗时环节。

超时调用的业务日志里面都有打印这样一行日志：
> Perf-stats has been removed, please removed it from handler chain and use metrics instead. See servicecomb.metrics.publisher.defaultLog.enabled.

对应CSE的配置如下：
```  handler:
    chain:
      Provider:
        default: perf-stats,bizkeeper-provider
      Consumer:
        default: loadbalance,bizkeeper-consumer
```

请问这个有什么影响吗？

**Comment by liubao68** [comment]
没影响。只是提示perf-stats可以删除，没用了。

**Comment by Zhanhaoxin** [comment]
从metrics.log来看，调用没有超时，但是从进行RPC调用前后的两行业务日志打印的时间戳来看是超时了。metrics日志如下：

> 2021-07-12 09:15:21,329 [spectator-poller-0] INFO  org.apache.servicecomb.metrics.core.publish.DefaultLogPublisher - 
os:
  cpu:
    all usage: 7.51%    all idle: 92.49%    process: 110.52%
  net:
    send(Bps)    recv(Bps)    send(pps)    recv(pps)    interface
    110          110          1            1            lo
    4.468M       3.287M       5.785K       7.039K       eth1
vertx:
  instances:
    name       eventLoopContext-created
    registry   0
    transport  0
    monitor-center 0
    config-center 0
  transport:
    client.endpoints:
      remote                connectCount disconnectCount queue         connections send(Bps) receive(Bps)
      (summary)             84           79              0             15          18.316K   10.619K
threadPool:
  coreSize maxThreads poolSize currentBusy rejected queueSize taskCount taskFinished name
  25       100        6        1           0        0         0.0       0.0          cse.executor.groupThreadPool-group1
  25       100        9        2           0        0         0.0       0.0          cse.executor.groupThreadPool-group0
consumer:
 simple:
  status      tps      latency            operation
  rest.200    0.0      4.035/4.035        AppGalleryAppDistService:AppGalleryCommentInfoService.AppCommentsStats.getCommentStats
              0.6      1054.947/1337.538  AppGalleryAppDistService:AppGalleryApkOptimizeService.GreenAppInfo.batchGetGreenAppInfoFlag
              0.0      28.093/28.093      AppGalleryAppDistService:AppGalleryAppMaterialService.app-material-services.getRelatedContent
              0.0      32.699/32.699      AOP:AppGalleryActivitySystemService.usageAdFlash.getAdFlashs
              0.1      258.664/381.657    AppGalleryAppPromotionService:AppGalleryPromotionExecuteService.apppromote-service.getRelrcmdListPromoteApp
              0.0      26.010/28.642      AppGalleryAppPromotionService:AppGalleryPromotionExecuteService.apppromote-service.getCommonListPromoteApp
              0.0      30.654/30.654      AppGalleryAppDistService:AppGalleryInstallListService.getinstalllist-api.getInstallList
              0.0      9.072/9.072        AppGalleryJointContentService:AppGalleryJForumContentService.usage-composite.queryRecommendHotspots
              0.0      17.330/17.330      AppGalleryAppDistService:AppGalleryDeviceInfoService.hcr.queryHcrIdByDeviceId
              0.0      27.290/27.290      DPS:AppGalleryDigitalProductService.usagePromotion.queryProductInfoByApp
              0.0      12.829/12.829      AppGalleryAppDistService:AppGalleryGlobalConfigService.GlobalConfigForClientAPI.getPopupConfig
              0.0      10.666/10.666      AppGalleryAppDistService:AppGalleryDeviceInfoService.deviceinfo.queryDeviceInfo
              0.0      31.972/55.568      AppGalleryAppDistService:AppGalleryCustomizeListService.substance-api.getSubstanceDataSource
              0.0      17.704/17.704      AppGalleryAppDistService:AppGalleryApkOptimizeService.AppHarmonyServiceAPI.getAppHarmonyInfos
              0.8      717.912/1337.538   (summary)
  rest.490    1.3      1504.104/1605.840  AppGalleryAppDistService:AppGalleryApkOptimizeService.GreenAppInfo.batchGetGreenAppInfoFlag
              1.3      1504.104/1605.840  (summary)
 details:
    rest.200:
      AppGalleryAppDistService:AppGalleryCommentInfoService.AppCommentsStats.getCommentStats:
        prepare     : 0.008/0.008        handlersReq : 0.514/0.514        cFiltersReq: 0.225/0.225        sendReq     : 1.108/1.108
        getConnect  : 0.959/0.959        writeBuf    : 0.150/0.150        waitResp   : 1.862/1.862        wakeConsumer: 0.040/0.040
        cFiltersResp: 0.208/0.208        handlersResp: 0.069/0.069
      AppGalleryAppDistService:AppGalleryApkOptimizeService.GreenAppInfo.batchGetGreenAppInfoFlag:
        prepare     : 0.013/0.065        handlersReq : 0.463/0.649        cFiltersReq: 0.293/0.890        sendReq     : 4.459/6.713
        getConnect  : 4.312/6.577        writeBuf    : 0.147/0.183        waitResp   : 1049.325/1331.592  wakeConsumer: 0.037/0.045
        cFiltersResp: 0.267/0.392        handlersResp: 0.089/0.112
      AppGalleryAppDistService:AppGalleryAppMaterialService.app-material-services.getRelatedContent:
        prepare     : 0.007/0.007        handlersReq : 5.076/5.076        cFiltersReq: 0.182/0.182        sendReq     : 18.302/18.302
        getConnect  : 18.153/18.153      writeBuf    : 0.148/0.148        waitResp   : 4.274/4.274        wakeConsumer: 0.036/0.036
        cFiltersResp: 0.126/0.126        handlersResp: 0.092/0.092
      AOP:AppGalleryActivitySystemService.usageAdFlash.getAdFlashs:
        prepare     : 0.005/0.005        handlersReq : 0.331/0.331        cFiltersReq: 0.171/0.171        sendReq     : 0.985/0.985
        getConnect  : 0.876/0.876        writeBuf    : 0.109/0.109        waitResp   : 30.868/30.868      wakeConsumer: 0.032/0.032
        cFiltersResp: 0.212/0.212        handlersResp: 0.094/0.094
      AppGalleryAppPromotionService:AppGalleryPromotionExecuteService.apppromote-service.getRelrcmdListPromoteApp:
        prepare     : 0.008/0.009        handlersReq : 1.569/3.909        cFiltersReq: 1.099/2.518        sendReq     : 1.768/4.751
        getConnect  : 1.616/4.598        writeBuf    : 0.151/0.155        waitResp   : 253.164/380.296    wakeConsumer: 0.047/0.054
        cFiltersResp: 0.924/2.268        handlersResp: 0.085/0.090
      AppGalleryAppPromotionService:AppGalleryPromotionExecuteService.apppromote-service.getCommonListPromoteApp:
        prepare     : 0.008/0.008        handlersReq : 1.704/3.031        cFiltersReq: 0.516/0.762        sendReq     : 0.283/0.324
        getConnect  : 0.153/0.186        writeBuf    : 0.131/0.138        waitResp   : 23.158/24.172      wakeConsumer: 0.033/0.035
        cFiltersResp: 0.223/0.229        handlersResp: 0.084/0.088
      AppGalleryAppDistService:AppGalleryInstallListService.getinstalllist-api.getInstallList:
        prepare     : 0.005/0.005        handlersReq : 6.351/6.351        cFiltersReq: 0.634/0.634        sendReq     : 5.655/5.655
        getConnect  : 5.527/5.527        writeBuf    : 0.128/0.128        waitResp   : 15.757/15.757      wakeConsumer: 0.035/0.035
        cFiltersResp: 2.124/2.124        handlersResp: 0.091/0.091
      AppGalleryJointContentService:AppGalleryJForumContentService.usage-composite.queryRecommendHotspots:
        prepare     : 0.007/0.007        handlersReq : 4.317/4.317        cFiltersReq: 0.219/0.219        sendReq     : 1.541/1.541
        getConnect  : 1.433/1.433        writeBuf    : 0.108/0.108        waitResp   : 2.129/2.129        wakeConsumer: 0.033/0.033
        cFiltersResp: 0.748/0.748        handlersResp: 0.076/0.076
      AppGalleryAppDistService:AppGalleryDeviceInfoService.hcr.queryHcrIdByDeviceId:
        prepare     : 0.008/0.008        handlersReq : 3.495/3.495        cFiltersReq: 0.583/0.583        sendReq     : 4.517/4.517
        getConnect  : 4.391/4.391        writeBuf    : 0.126/0.126        waitResp   : 8.395/8.395        wakeConsumer: 0.037/0.037
        cFiltersResp: 0.172/0.172        handlersResp: 0.122/0.122
      DPS:AppGalleryDigitalProductService.usagePromotion.queryProductInfoByApp:
        prepare     : 0.058/0.058        handlersReq : 11.501/11.501      cFiltersReq: 0.410/0.410        sendReq     : 3.307/3.307
        getConnect  : 3.193/3.193        writeBuf    : 0.113/0.113        waitResp   : 10.721/10.721      wakeConsumer: 0.034/0.034
        cFiltersResp: 1.173/1.173        handlersResp: 0.087/0.087
      AppGalleryAppDistService:AppGalleryGlobalConfigService.GlobalConfigForClientAPI.getPopupConfig:
        prepare     : 0.008/0.008        handlersReq : 3.878/3.878        cFiltersReq: 0.415/0.415        sendReq     : 1.029/1.029
        getConnect  : 0.906/0.906        writeBuf    : 0.122/0.122        waitResp   : 6.548/6.548        wakeConsumer: 0.037/0.037
        cFiltersResp: 0.830/0.830        handlersResp: 0.084/0.085
      AppGalleryAppDistService:AppGalleryDeviceInfoService.deviceinfo.queryDeviceInfo:
        prepare     : 0.005/0.005        handlersReq : 0.364/0.364        cFiltersReq: 0.315/0.315        sendReq     : 0.274/0.274
        getConnect  : 0.140/0.140        writeBuf    : 0.135/0.135        waitResp   : 9.388/9.388        wakeConsumer: 0.033/0.033
        cFiltersResp: 0.204/0.204        handlersResp: 0.083/0.083
      AppGalleryAppDistService:AppGalleryCustomizeListService.substance-api.getSubstanceDataSource:
        prepare     : 0.007/0.008        handlersReq : 1.640/2.929        cFiltersReq: 0.352/0.459        sendReq     : 1.532/2.012
        getConnect  : 1.421/1.905        writeBuf    : 0.111/0.115        waitResp   : 26.656/51.429      wakeConsumer: 0.048/0.050
        cFiltersResp: 1.657/1.916        handlersResp: 0.079/0.079
      AppGalleryAppDistService:AppGalleryApkOptimizeService.AppHarmonyServiceAPI.getAppHarmonyInfos:
        prepare     : 0.008/0.008        handlersReq : 2.847/2.847        cFiltersReq: 1.386/1.386        sendReq     : 5.876/5.876
        getConnect  : 5.783/5.783        writeBuf    : 0.093/0.093        waitResp   : 6.422/6.422        wakeConsumer: 0.035/0.035
        cFiltersResp: 1.057/1.057        handlersResp: 0.072/0.072
    rest.490:
      AppGalleryAppDistService:AppGalleryApkOptimizeService.GreenAppInfo.batchGetGreenAppInfoFlag:
        prepare     : 0.013/0.069        handlersReq : 0.451/0.669        cFiltersReq: 0.263/0.635        sendReq     : 3.544/59.845
        getConnect  : 3.400/59.682       writeBuf    : 0.144/0.257        waitResp   : 1499.501/1598.123  wakeConsumer: 0.000/0.001
        cFiltersResp: 0.000/0.001        handlersResp: 0.331/0.397
producer:
 simple:
  status      tps      latency            operation
  rest.200    0.0      16.906/16.906      store.DevWords.getDevWords
              0.0      11002.593/11002.593 store.DynamicLayoutAPI.getTabDetail
              0.0      47.652/47.652      store.ClientSplashAPI.getSplashList
              0.1      3689.050/11002.593 (summary)
 details:
    rest.200:
      store.DevWords.getDevWords:
        prepare: 0.049/0.049        queue       : 0.408/0.408        filtersReq : 1.166/1.166        handlersReq: 2.748/2.748
        execute: 11.439/11.439      handlersResp: 0.043/0.043        filtersResp: 0.738/0.738        sendResp   : 0.261/0.261
      store.DynamicLayoutAPI.getTabDetail:
        prepare: 0.063/0.063        queue       : 0.355/0.355        filtersReq : 2.707/2.707        handlersReq: 2.987/2.987
        execute: 10973.019/10973.019 handlersResp: 0.033/0.033        filtersResp: 19.376/19.376      sendResp   : 4.039/4.039
      store.ClientSplashAPI.getSplashList:
        prepare: 0.046/0.046        queue       : 0.387/0.387        filtersReq : 1.070/1.070        handlersReq: 0.187/0.187
        execute: 45.182/45.182      handlersResp: 0.022/0.022        filtersResp: 0.539/0.539        sendResp   : 0.207/0.207

**Comment by liubao68** [comment]
```
  rest.490    1.3      1504.104/1605.840  AppGalleryAppDistService:AppGalleryApkOptimizeService.GreenAppInfo.batchGetGreenAppInfoFlag
              1.3      1504.104/1605.840  (summary)
```

这部分显示是超时的。 这里一个 [介绍](http://servicecomb.gitee.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/references-handlers/fail-retry.html) 能够帮助你理解metrics的含义。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
