### ISSUE TITLE
Handler能否针对schema进行配置

### ISSUE THREAD

**Issue by wisper-shadow** [apache/servicecomb-java-chassis#2470]
在搭建微服务的过程中，发现自定义的健康检查schema也会被处理链拦截，在打印操作日志时因为解析不出必要参数导致健康检查失败

**Comment by liubao68** [comment]
Handler不支持schema进行配置， 参考： http://servicecomb.gitee.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/references-handlers/intruduction.html

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
