### ISSUE TITLE
springboot无法启动，空指针，无法加载CseApplicationListener这个bean

### ISSUE THREAD

**Issue by holdyou01** [apache/servicecomb-java-chassis#2472]
![image](https://user-images.githubusercontent.com/72956826/125789316-e3ae2f4f-5057-4a7b-b87d-0fc5b6a05fcb.png)
无法启动，这个依赖是有的，为什么说空指针呢？
springboot start fail. exception:org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.apache.servicecomb.springboot2.starter.ServiceCombSpringConfiguration': Unsatisfied dependency expressed through method 'setCseApplicationListener' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.apache.servicecomb.core.CseApplicationListener#0' defined in URL [jar:file:/E:/temprepository/caches/modules-2/files-2.1/org.apache.servicecomb/java-chassis-core/2.1.5/ddf9bbcd218ae9e8d4780ff68598d443935e3f2d/java-chassis-core-2.1.5.jar!/META-INF/spring/cse.bean.xml]: Initialization of bean failed; nested exception is java.lang.NullPointerException

**Comment by liubao68** [comment]
可以参考 [例子](https://github.com/apache/servicecomb-samples/tree/master/porter_springboot) 提供一个复现的例子以进行分析。 你提供的信息缺少帮助分析的内容。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
