### ISSUE TITLE
文件上传大小限制配置uploads.maxSize是否可以支持按照接口区分

### ISSUE THREAD

**Issue by x00384074** [apache/servicecomb-java-chassis#2480]
文件上传大小限制配置uploads.maxSize是否可以支持按照接口区分
如何区分接口配置？
![image](https://user-images.githubusercontent.com/71321625/126946312-2794c982-59ed-49e8-96ab-833a30ac6866.png)

**Comment by liubao68** [comment]
现在不支持

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
