### ISSUE TITLE
@RequestPath @PostMapping里的值建议支持变量解析，如 @RequestMapping("${foo.bar}")

### ISSUE THREAD

**Issue by Nick-The-Uncharted** [apache/servicecomb-java-chassis#2481]
目前看 org.apache.servicecomb.swagger.generator.springmvc.processor.annotation.AbstractHttpMethodMappingAnnotationProcessor#processPath的代码似乎不支持

动机: 一套代码部署到两个namespace里，各自有自己数据库等 只有路径前缀不同

**Comment by liubao68** [comment]
需要先分析下swagger生成等逻辑

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
