### ISSUE TITLE
微服务运行过程中会创建udp协议，有全零监听安全问题

### ISSUE THREAD

**Issue by polyLi** [apache/servicecomb-java-chassis#2483]
服务是容器服务，以java命令启动springboot的jar
服务启动后，java进程关联端口是tcp的端口，服务运行一段时间后，即被调用一段时间后，会创建多个udp的全零监听端口，端口是随机创建的，无固定端口
想了解下怎么去关闭udp的端口，udp的端口是怎么创建的。

**Comment by liubao68** [comment]
以前好像处理过类似的咨询，但是最后发现端口都不是java chassis开放的。 所以需要你提供更多信息。比如提供一个简单的demo，能够复现， 或者分析现有问题找到具体模块。

**Comment by wujimin** [comment]
netty的异步dns client会开udp端口  
好像改同步的就不会，但是风险是可能阻塞网络线程

**Comment by hufaguang** [comment]
> netty的异步dns client会开udp端口 好像改同步的就不会，但是风险是可能阻塞网络线程

-----netty的异步dns client会开udp端口，这个能详细的说明下吗

**Comment by liubao68** [comment]
see https://github.com/apache/servicecomb-java-chassis/issues/3790
