### ISSUE TITLE
请教关于连接数配置

### ISSUE THREAD

**Issue by five111** [apache/servicecomb-java-chassis#2484]
文档连接http://servicecomb.gitee.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/transports/rest-over-vertx.html 
原文:
“站在server的角度，在极限情况下： * 一个client最多向一个server建立40条连接。(8 * 5 = 40)
 n个client最多会向一个server建立40 * n条连接”
疑问：
实际上我在客户端是可以配置servicecomb.rest.client.verticle-count为8 servicecomb.rest.client.connection.maxPoolSize为10
这样当client和server端的实例数都为1时 client和server的连接是多少？
另外提一句 这两个配置似乎在 rest-over-servlet下也能起作用

**Comment by wujimin** [comment]
1. 如果全部在普通线程发起调用，则使用的是client verticle里的连接池，此时按你说的场景，极限连接数为`8 * 10`  
2. 如果除此之外，这个“客户端”进程，还作为服务端接受别人的请求，并且使用的是reactive模式  
    因为业务逻辑直接在网络线程中执行，也就是server verticle中执行  
    此时，如果需要向外发送请求，并不会再切到client verticle去（可能涉及线程切换），而是直接在当前verticle创建连接池  
    所以，如果server verticle count为4， 对于极限情况，还会增加`4 * 10`的连接

**Comment by five111** [comment]
感谢回答！同时还有一些疑问
> 2. 如果除此之外，这个“客户端”进程，还作为服务端接受别人的请求，并且使用的是reactive模式
>    因为业务逻辑直接在网络线程中执行，也就是server verticle中执行
>    此时，如果需要向外发送请求，并不会再切到client verticle去（可能涉及线程切换），而是直接在当前verticle创建连接池
>    所以，如果server verticle count为4， 对于极限情况，还会增加`4 * 10`的连接
大部分场景下 服务即是client 又会是server 
一  如果都在verticle创建连接池的话 是不是client verticle里的连接池并不会被利用到？
二  关于使用reactive模式，在servicecomb中什么样的行为可以定义为使用了reactive模式，通信模式使用rest-over-vertx？
三  在我服务既是client又是server的情况下，我想要通过增加连接来提升性能的话 是不是server verticle count为配置为8（最大为8），servicecomb.rest.client.connection.maxPoolSize配置尽量配大一些即可?

**Comment by wujimin** [comment]
大部分业务还是同步的，此时都是使用client verticle里的池   
本质上，是看发起调用点是在普通线程，还是网络线程  

简单的判断，可以观察controller方法：
1. int add(int x, int y)  
    这种情况，框架会自动调度到普通线程池执行，称之为同步方法  
    add方法内部向外发起调用，使用client verticle里的池  
2. CompletableFuture<Integer> add(int x, int y)  
    这种情况，框架会直接在网络线程中调用，称之为reactive方法  
   add方法内部向外发起调用，使用server verticle里的池  
   当然，如果开发人员在add方法内部手工切线程到了普通线程执行逻辑，在那里发起向外的调用，又会使用client verticle的池  

所以，最终还是要按上面的“本质”来判断

**Comment by wujimin** [comment]
verticle count要看准备给这个进程多少cpu资源  
如果增加连接数不是问题，可以调用client verticle/server verticle/maxPoolSize来达到最佳效果  
但是，如果连接数达到几万级别了，最好考虑使用http2，规划会简单得多，可靠性也更强

**Comment by five111** [comment]
我们的服务目前成了性能瓶颈，针对服务我们规划了3个cpu核心，verticle count数量应该是6，能提高的数量应该有限了，而我们目前cpu使用率缺只有20%左右，远远没有充分利用我们的资源，所以考虑在增加连接数来提高cpu使用率达到增强性能的目的

**Comment by wujimin** [comment]
打开metrics日志，观察连接池以及其他环节消耗时间，可以快速定界性能问题

**Comment by five111** [comment]
问题解决了 但是解决过程中metric日志提供的帮助其实很少 尤其是连接被快速关闭的场景
