### ISSUE TITLE
Connection was closed 本地调度任务 非接口触发

### ISSUE THREAD

**Issue by five111** [apache/servicecomb-java-chassis#2487]
我本地有个定时任务线程 会去发接口访问别的服务 偶现（几小时一次）Failed to send request, Connection was closed 报错
目前怀疑两个点 
1、服务端的连接不够 （servlet模式 目前已经在调优测试了）
2、怀疑超时（想知道这种调度任务的超时时间是怎么计算的？）

**Comment by liubao68** [comment]
可以参考 http://servicecomb.gitee.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/featured-topics/performance.html  先收集下信息， 结合信息分析下。
