### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by helloworldhelloworld** [apache/servicecomb-java-chassis#2488]
client 端是8c的机器，thread-count配置的16，connection maxPoolSize 100
service端是4c的机器 ，thread-count配置的16

当前压测时候，有三个接口  一个同步A的60tps  超时100ms，两个异步接口分别是B 120tps 超时1s，C 60tps 超时100ms

现在同步调用的A接口，要求时延是100ms，100ms超时。当前在并发跑的时候，发现会出现超时。
超时的时候，现象是client端的请求已经触发超时返回了。比如在2021-07-30 01:20:28.435  ，但是service端rest接口入口处日志是
2021-07-30 01:20:28.822  ，晚了接近400ms. service端的入口直接是拿到请求就丢到线程池里执行任务，不会阻塞

请问这个时延是在哪里

**Comment by liubao68** [comment]
建议参考 http://servicecomb.gitee.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/featured-topics/performance.html  先获取下相关信息。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
