### ISSUE TITLE
升级后读取不到CSE配置

### ISSUE THREAD

**Issue by myw1234** [apache/servicecomb-java-chassis#2492]
servicecomb升级2.1.5后，读取cse配置失败
![image](https://user-images.githubusercontent.com/49012437/128285418-a3d259d4-f83a-4314-be02-e21f372059be.png)

**Comment by liubao68** [comment]
问题缺少必要信息

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
