### ISSUE TITLE
pojo类的属性定义@notblank ，controller 层使用@Validated注解

### ISSUE THREAD

**Issue by chenchanglong1997** [apache/servicecomb-java-chassis#2503]
pojo类的属性定义@notblank 
controller 层使用@Validated注解
生成的契约，此属性为非必填项，没有生效。

**Comment by chenchanglong1997** [comment]
controller 层方法参数使用@Valid注解也不生效

**Comment by liubao68** [comment]
“不生效” 的含义是什么？能给一个具体例子吗？

**Comment by chenchanglong1997** [comment]
> “不生效” 的含义是什么？能给一个具体例子吗？

public class Student {
    @NotBlank
    String name;
    @NotNull
    int age;

**Comment by chenchanglong1997** [comment]
> “不生效” 的含义是什么？能给一个具体例子吗？

public class Student {
    @NotBlank
    String name;
    @NotNull
    int age;

**Comment by chenchanglong1997** [comment]
> “不生效” 的含义是什么？能给一个具体例子吗？

public class Student {
    @NotBlank
    String name;
    @NotNull
    int age;
}
    @RequestMapping(path = "/testNotBlank", method = RequestMethod.POST)
    public void testNotBlank(@Validated @RequestBody Student student) {
    }       使用@notnull是可以的，生成的swagger是必填属性，而notblank不行，并不是非必填属性

**Comment by liubao68** [comment]
这块的内容属于 swagger api的实现范围。 应该大部分validation annotation都是支持的。 但是需要考虑swagger语义和validation annotation的语义的对应关系。 我没详细测试过， 可能 NotBlank 是不受支持的标签。 

也可以检查下目前的swagger版本。 参考： https://stackoverflow.com/questions/37145656/configure-swagger-javax-validation-constraints-on-dtos

**Comment by chenchanglong1997** [comment]
> 这块的内容属于 swagger api的实现范围。 应该大部分validation annotation都是支持的。 但是需要考虑swagger语义和validation annotation的语义的对应关系。 我没详细测试过， 可能 NotBlank 是不受支持的标签。
> 
> 也可以检查下目前的swagger版本。 参考： https://stackoverflow.com/questions/37145656/configure-swagger-javax-validation-constraints-on-dtos
