### ISSUE TITLE
建议注册到注册中心的实例信息里包含业务进程启动时间

### ISSUE THREAD

**Issue by johnyannj** [apache/servicecomb-java-chassis#2507]
用户扩展自己的负载均衡算法，对于刚启动的进程，会采用慢慢预热的的方式分发请求到新节点。

当前consumer端只能获取到一个“注册”时间，如果provider和注册中心之间网络闪断，心跳失败，再注册后会被误认为是新启动的进程。

建议注册到注册中心的实例信息里包含业务进程启动时间

**Comment by develpoerX** [comment]
建议提供一个注册信息扩展点，类似headers的map格式，支持用户自定义的注册到服务中心一些业务定制化参数。对于用户定制化参数进行数量进行限制，防止参数过多影响SC性能。

**Comment by liubao68** [comment]
@develpoerX 目前是有扩展的。 业务可以通过实现 `EnvAdapter` 即可。 详细查看 `EnvAdapterManager` 代码。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
