### ISSUE TITLE
消费端是否对提供端的版本数量有限制

### ISSUE THREAD

**Issue by fanjiang-2021** [apache/servicecomb-java-chassis#2510]
背景:
目前业务侧,提供端一直升级,注册中心会保留N个版本,当消费端服务发现的时候,会从注册中心 获取提供端的版本契约信息保存到内存中,想确认一下,sdk 针对提供端多个版本共存的情况,是否存在相关约束,防止占用过多内存

**Comment by liubao68** [comment]
java chassis只会获取有实例的版本，不会存在你的情况。 

service center最新版本提供了自动清理历史无实例版本的功能， 可以考虑升级 service center。
