### ISSUE TITLE
DefaultHttpClientFilter的优先级为Integer.MAX_VALUE，导致Consumer在处理完Response后无法进行后续的自定义Filter处理

### ISSUE THREAD

**Issue by LnManch** [apache/servicecomb-java-chassis#2521]
Provider对Request和Response的处理优先级都是处于中间态，Consumer对Request的处理优先级也是处于中间态，这样可以方便业务通过设置Filter的优先级来达到预处理和后处理的目的。
DefaultHttpClientFilter是否也可以调整相应的处理优先级，方便业务自定义Filter来实现后处理的目的。

**Comment by liubao68** [comment]
能简单描述下业务场景吗？或许可能有其他方案。

**Comment by liubao68** [comment]
fixed.
