### ISSUE TITLE
Client调用Server的问题咨询

### ISSUE THREAD

**Issue by qubo11** [apache/servicecomb-java-chassis#2535]
写了一个小例子，就是简单的Client调用Server的demo：
![image](https://user-images.githubusercontent.com/4074496/131431604-5caae9a0-3826-4805-8928-997691e0dd16.png)
接收请求使用了EventLoop线程：
![image](https://user-images.githubusercontent.com/4074496/131432564-5cd4b696-cfec-4f70-8c00-1ec654b8821a.png)

在Controller中，执行业务代码，使用的是业务线程：
![image](https://user-images.githubusercontent.com/4074496/131431763-6e261b2a-65e8-4e16-8416-f8e22156431c.png)

当Client调用Server的接口的时候，在RestClientInvocation#invoke方法中，发送请求的时候，会使用EventLoop线程：
![1](https://user-images.githubusercontent.com/4074496/131432349-7ef8b0e4-6624-4885-aa00-7de3a521d270.png)

我看源码有一行注释“从业务线程转移到网络线程中去发送”，疑问：
1.Client接收请求和Client发送Server请求是同一个EventLoop线程吧？
2.如果是同一个EventLoop线程，那如果我Client调用Server有阻塞，也会影响Client本身的接收请求的吞吐量吧？

**Comment by liubao68** [comment]
如果你使用的HTTP协议， 请求和应答都是一个连接。 完成请求应答后， 这个连接才会被其他请求复用。 
event-loop不能阻塞。

**Comment by qubo11** [comment]
我看Client接收到的请求是EventLoop线程8，Client调用Server的EventLoop线程是12。

我的意思是，如果Client调用Server的时候，如果网络或者什么原因，导致时延大，那应该也会影响Client本身接收的请求吧？

**Comment by fanjiang-2021** [comment]
#2484

**Comment by qubo11** [comment]
上述说的client verticle指定是：ClientVerticle类？server verticle指的是：RestServerVerticle类？

我看他们都是用的同一个vertx实例。没太看出来Client和Server的连接池有什么区别哈，我看都是transport-vert.x-eventloop-thread-x线程。

**Comment by liubao68** [comment]
连接池和线程池是两个不同的概念。 transport-vert.x-eventloop-thread是线程池。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
