### ISSUE TITLE
关于java-chassis 1.3.0 升级到2.5.0

### ISSUE THREAD

**Issue by diwenzheng** [apache/servicecomb-java-chassis#2546]
有没有相应的指导手册,最好有案例代码.

**Comment by diwenzheng** [comment]
找到了 如果没错的话,应该是在 servicecomb-samples里面 只不过分支写着master 让我以为 是 1.3.x左右的版本,还有就是我看案例中对于microservice.yaml 每个服务写的东西 比较少. 有没有把所有的service-comb的功能都应用的yaml,最好能有注释 告诉我这些功能大致的应用处.

**Comment by liubao68** [comment]
开发指南里面有[升级指导](https://servicecomb.apache.org/references/java-chassis/zh_CN/featured-topics/upgrading.html)
