### ISSUE TITLE
kie 在框架中如何应用？

### ISSUE THREAD

**Issue by diwenzheng** [apache/servicecomb-java-chassis#2548]

**Comment by diwenzheng** [comment]
@liubao68

**Comment by diwenzheng** [comment]
找到了 在 servicecomb-java-chassis/dynamic-config/config-kie 在 sample 里面有.

**Comment by liubao68** [comment]
参考： https://servicecomb.apache.org/references/java-chassis/zh_CN/config/general-config.html

**Comment by diwenzheng** [comment]
> 参考： https://servicecomb.apache.org/references/java-chassis/zh_CN/config/general-config.html ， 例子也可以参考： https://github.com/apache/servicecomb-java-chassis/tree/master/demo/demo-cse-v2

考虑合并下到sample吧.不然学习案例,来回切换.

**Comment by diwenzheng** [comment]
还有一个问题 kie 存在session问题吗? 如果我采用轻量的swarm的方式部署 kie的话,kie实例有三个,会有问题吗?也就是和K8s部署差不多,对面一个node-ip,连过来那样

**Comment by liubao68** [comment]
这个问题你可以在kie创建一个issue。
