### ISSUE TITLE
Provider在response序列化时抛出JsonMappingException，ServerRestArgsFilter自动将该异常封装成590的内部错误，但是Consumer却显示HTTP响应正常，返回结果为NULL

### ISSUE THREAD

**Issue by LnManch** [apache/servicecomb-java-chassis#2550]
Provider在response序列化时抛出JsonMappingException，ServerRestArgsFilter自动将该异常封装成590的内部错误。
![servicecomb](https://user-images.githubusercontent.com/32447408/132181010-7ed8e66b-c62d-4b45-8652-7b23ca75e586.PNG)
但是在返回响应时，却没有将该异常信息封装，导致consumer接收到的是一个内容为空的成功response，从而引发空指针异常
![servicecomb](https://user-images.githubusercontent.com/32447408/132181557-41249f8d-5e83-47c3-b1e6-1decad44b23f.PNG)

**Comment by liubao68** [comment]
看你提供的信息，使用场景涉及比较复杂的封装。 你能提供一个PR针对这个特殊的场景修复下吗？

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
