### ISSUE TITLE
关于新版本2.5.0的问题

### ISSUE THREAD

**Issue by diwenzheng** [apache/servicecomb-java-chassis#2553]
1.resttemplate 我看到好像你们做了 可配置的重试的情况,应该如何应用?
2.关于三方接口的地方,如何使用注册中心访问.
3.能否提供一套2.5.0版本的yaml,包含所有功能.
4.关于服务内部事件注册回调的案例,如服务启动完成,服务熔断,服务下线等事件接口。

**Comment by liubao68** [comment]
这些问题太泛了， 尽可能提具体问题。 

下面一些材料可参考： [开发指南](https://servicecomb.apache.org/references/java-chassis/zh_CN/) 、 [学习和应用实践](https://blog.csdn.net/looook/article/details/116271333)

**Comment by diwenzheng** [comment]
主要官方文档没有明确2.5.0的yaml 应该如何配置啊,我们之前用的1.3.0 现在看一些配置的方式都改了,这让我很头痛,所以我需要一份关于2.5.0的文档,目前官方的是混在一起的,能否专门出一份

**Comment by liubao68** [comment]
你能列一下具体问题吗？ 1.3.0的配置应该2.5.0都是能够识别的。

**Comment by diwenzheng** [comment]
> 你能列一下具体问题吗？ 1.3.0的配置应该2.5.0都是能够识别的。

是有改变部分的,稍后我来提供全套yaml的配置方式,另外一个提一个idea,关于三方的接口,我建议是否能做成支撑动态变化的,因三方接口的不可控性,地址变化或者什么的,如果应用三方接口的方式在注册中心,就会有些问题.

**Comment by diwenzheng** [comment]
@liubao68 我升级到2.5.0的java-classis,随后放上去还是发现1.3.0的问题,所以我想问下,https://xie.infoq.cn/article/c402d62a1cd95457a9a0f0621 这里面的异步注册 应该怎么用？

**Comment by liubao68** [comment]
1. INFOQ的文档说的是注册中心实现逻辑。和使用 java-chassis 没有关系的。 对于开发者不可见。 
2. 你说的第三方注册是指什么？ 这里的功能吗？ https://servicecomb.apache.org/references/java-chassis/zh_CN/build-consumer/3rd-party-service-invoke.html

**Comment by diwenzheng** [comment]
> 1. INFOQ的文档说的是注册中心实现逻辑。和使用 java-chassis 没有关系的。 对于开发者不可见。
> 2. 你说的第三方注册是指什么？ 这里的功能吗？ https://servicecomb.apache.org/references/java-chassis/zh_CN/build-consumer/3rd-party-service-invoke.html
是的,这个功能,当我接口的url,或者地址变更,现在支持不重启服务的情况下无缝切换吗

**Comment by diwenzheng** [comment]
> 2. 你说的第三方注册是指什么？ 这里的功能吗？ https://servicecomb.apache.org/references/java-chassis/zh_CN/build-consumer/3rd-party-service-invoke.html

是的,这个功能,当我接口的url,或者地址变更,现在支持不重启服务的情况下无缝切换吗

**Comment by diwenzheng** [comment]
> 1. INFOQ的文档说的是注册中心实现逻辑。和使用 java-chassis 没有关系的。 对于开发者不可见。

那现在2.5.0是采用长连接的心跳吗,按照我的理解如果配置多个注册中心ip,这三个ip会缓存住,随后不停的和注册中心发送心跳,当第一个ip心跳不可用,切换到第二个吗?

**Comment by liubao68** [comment]
1. 不支持无缝切换，可以将配置项写成place holder, 改变后需要重启
2. 微服务和注册中心之间的心跳是短连接， 轮询给各个实例发送心跳（包括失败的情况）。

**Comment by diwenzheng** [comment]
> 1. 不支持无缝切换，可以将配置项写成place holder, 改变后需要重启
> 2. 微服务和注册中心之间的心跳是短连接， 轮询给各个实例发送心跳（包括失败的情况）。

这个无缝切换,有考虑新版本做吗,还有一个就是highway的使用方式,应该如何使用.

**Comment by liubao68** [comment]
highway的使用你可以先看下我前面给的[学习材料](https://blog.csdn.net/looook/article/details/116271333) 

这个issue的讨论不够聚焦了。 针对单点问题你可以创建一个新的 issue。 这个问题关闭了。
