### ISSUE TITLE
对于灰度发布的一个猜想

### ISSUE THREAD

**Issue by huanghezhen** [apache/servicecomb-java-chassis#2559]
我看如果使用service center来实现灰度发布的时候,需要做配置,每次升级需要指定新实例的版本 比较麻烦
所以我想可以不可以结合k8s的自己的健康机制来实现,
比如 我将每个服务发布到注册中心的地址都是deployment的ip地址(这个我还没验证过,不同的服务是否可以注册相同的地址)
然后 k8s 自己本身配置了健康检测,这样service center就不需要及时的知道哪个下线 从而避免空档期的error

**Comment by liubao68** [comment]
你的思路解决的是滚动升级不断服的问题，重要的是合理管理优雅下线等。 灰度发布是更加复杂的路由管理。
