### ISSUE TITLE
2.5.0 上传文件报错 

### ISSUE THREAD

**Issue by diwenzheng** [apache/servicecomb-java-chassis#2560]
![image](https://user-images.githubusercontent.com/60613511/132616341-9b98aeb6-b08b-4bca-b6a4-1a52669e3e6e.png)

**Comment by diwenzheng** [comment]
@liubao68

**Comment by diwenzheng** [comment]
用的是servlet那种     
<dependency>
            <groupId>org.apache.servicecomb</groupId>
            <artifactId>java-chassis-spring-boot-starter-servlet</artifactId>
            <version>${servicecomb.version}</version>
        </dependency>

**Comment by diwenzheng** [comment]
原因是因为官方升级了springboot 版本到2.3.4,如需导入文件按照下列做法做.建议放到文档中
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true

**Comment by liubao68** [comment]
谢谢分享这个案例。 加上配置项就可以实现下载了吗？ spring boot默认只限制大文件， 小文件下载不受影响？

**Comment by diwenzheng** [comment]
> 谢谢分享这个案例。 加上配置项就可以实现下载了吗？ spring boot默认只限制大文件， 小文件下载不受影响？

不是下载,是上传文件

**Comment by diwenzheng** [comment]
> > 谢谢分享这个案例。 加上配置项就可以实现下载了吗？ spring boot默认只限制大文件， 小文件下载不受影响？
> 
> 不是下载,是上传文件

具体原因在这里.https://www.cnblogs.com/siroinfo/p/13045008.html
