### ISSUE TITLE
2.5.0 注册中心CSE调用返回失败

### ISSUE THREAD

**Issue by diwenzheng** [apache/servicecomb-java-chassis#2561]
statusCode 200, reasonPhrase OK, response content-type application/json; charset=utf-8 is not supported

这是日志的东西,1.3.0不会返回这个,

**Comment by diwenzheng** [comment]
还有一个就是cse get的问题 java.lang.IllegalStateException: Could not create URI object: Illegal character in query at index 135: cse://Alarm/rest/ir/v1/alarm?pageNum=1&pageSize=20&alarmName=&alarmId=&id=&alarmLevel=&alarmType=&alarmStatus=&param=&orderBy=create_at DESC&startTime=0&endTime=0&species=current

**Comment by diwenzheng** [comment]
@liubao68

**Comment by liubao68** [comment]
你能描述下如何使用才能够出现上述问题现象吗？

**Comment by diwenzheng** [comment]
> 你能描述下如何使用才能够出现上述问题现象吗？

第一个问题是 正常cse调用 post,使用exchange发送,打印的日志为这样,直接调用下属服务返回的正常,
第二个问题,如果没猜错,=的后面不让有空格.

**Comment by diwenzheng** [comment]
第二个问题我已经解决了,原因还是在于官方升级了springboot版本,所以对于get参数有校验了,发现如果是非法字符抛异常.

**Comment by diwenzheng** [comment]
第一个应该是你们升级之后的问题了,之前接收方是一个HttpRequest对象,1.3.0的时候必须使用byte接收,否则报错.2.5.0看样子是强类型关系有点,我要byte他是json,所以返回上述.
