### ISSUE TITLE
 2.5.0 关于将第三方url注册到自己的注册中心这块的疑问

### ISSUE THREAD

**Issue by diwenzheng** [apache/servicecomb-java-chassis#2563]
首先集成三方url配置的yaml或者自己使用bean来注册,官方文档只是说明针对三方的接口实现服务治理的过程,过于服务治理这块能详细告诉我下做了哪些,怎么做的吗,想学习下经验.

**Comment by diwenzheng** [comment]
@liubao68

**Comment by liubao68** [comment]
java-chassis提供的第三方调用不是把第三方信息注册到注册中心。 而是在本地构造一个虚拟的微服务，包括其服务信息和实例信息。 这样就可以像请求其他注册到注册中心的java-chassis服务一样访问了。

**Comment by diwenzheng** [comment]
> java-chassis提供的第三方调用不是把第三方信息注册到注册中心。 而是在本地构造一个虚拟的微服务，包括其服务信息和实例信息。 这样就可以像请求其他注册到注册中心的java-chassis服务一样访问了。

一般情况下第三方只会提供一个虚拟ip又或者负载均衡的vip,那么他如何针对这块做服务治理,还有比如我的实例如20个,每一个都需要在本地构建一个虚拟微服务,那么当20个实例中的其中一个发现Ip不通,这时候会熔断吗又或者访问过多会限流吗?当其中一个实例发现问题,所有实例共享这个信息,还是自己管自己呢?

**Comment by diwenzheng** [comment]
@liubao68  这块的问题 麻烦帮我解答下.我要考虑我们自己的三方服务应用有没有必要改造这块.

**Comment by diwenzheng** [comment]
其实我主要关心的是,上面我们说的其实是在本地构造一个虚拟微服务,多实例的时候,其实一个实例限流或者熔断,其余实例是自动感知到随后熔断还是每个是独立的.

**Comment by liubao68** [comment]
如果是实例隔离， 那么错误统计是基于实例的。 如果是“服务接口”隔离”（参考bizkeeper模块基于hystrix的实现，或者基于流量的治理部分）， 那么隔离是针对所有实例的。 

也就是效果取决于实际采用的治理策略。
