### ISSUE TITLE
2.5.0 服务注册失败自动下线

### ISSUE THREAD

**Issue by diwenzheng** [apache/servicecomb-java-chassis#2565]
当我更改了yaml文件的样式,更新服务的时候,和注册中心交互的时候  自动下线??

**Comment by diwenzheng** [comment]
这时候必须手动删除 注册中心原有的版本,随后可以注册成功,这什么情况?

**Comment by diwenzheng** [comment]
@liubao68

**Comment by liubao68** [comment]
能否提供下具体的错误信息？ 是[这里](https://servicecomb.apache.org/references/java-chassis/zh_CN/question-and-answer/interface-compatibility.html) 说明的问题吗？

**Comment by diwenzheng** [comment]
啊 忘记这个了,因为 1.3.0 是 
service_description:
  name: xxx-service
  version: 0.0.1
  environment: development

2.5.0 为 
servicecomb:
  uploads:
    directory: /tmp/upload
  service:
    environment: development
    name: es-management
    version: 1.1.0

**Comment by diwenzheng** [comment]
我的天,我给我们管理服务加了这个环境参数,我没更新其他服务的参数,然后我去测试ETCD的问题,一直以为我的ETCD有问题导致注册中心有问题,原来是因为加了这个环境参数,导致注册中心查询没找到
