### ISSUE TITLE
2.5.0 设置的json体返回有问题

### ISSUE THREAD

**Issue by diwenzheng** [apache/servicecomb-java-chassis#2569]
![image](https://user-images.githubusercontent.com/60613511/132841171-4cc562c6-9b70-44b3-b856-ba0fa900f5db.png)

如果没加这个属性,返回的这个对象会自动少一个s

加了注解报错.
Caused by: java.lang.IllegalStateException: Conflicting/ambiguous property name definitions (implicit name 'controlItems'): found multiple explicit names: [controlItems, controlItem], but also implicit accessor: [method com.xxx.license.vo.License#setControlItems(java.util.List)][visible=true,ignore=false,explicitName=false]

**Comment by liubao68** [comment]
能直接贴一下代码吗？ 截图经常无法显示。 另外“如果没加这个属性” 这个指什么？

**Comment by diwenzheng** [comment]
指的是jsonProperty. 

    @GetMapping("/")
    @CommonResponseResult
    @ResponseBody
    public ResponseResult queryLicenseInfo()
    {
        return succ(licenseService.queryLicenseInfo());
    }



public License queryLicenseInfo() {

        LicInfo licInfo = infoMapper.queryByLicense();

        if (licInfo == null) {
            return License.builder().build();
        }

        List<ControlItem> controlItems = controlItemMapper.queryByControlItemsById(licInfo.getId());

        return License.builder().licInfo(licInfo).controlItems(controlItems)
                .build();
    }
代码很简单,普通查询

**Comment by diwenzheng** [comment]
主要返回的json结构 把数据篡改了.应该是controltems,但是放回controlitem

**Comment by diwenzheng** [comment]
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Data
public class License {
    @JsonProperty("licInfo")
    private LicInfo licInfo;
    private List<ControlItem> controlItems;


    public LicInfo getLicInfo() {
        return licInfo;
    }

    public void setLicInfo(LicInfo licInfo) {
        this.licInfo = licInfo;
    }

    @XmlElementWrapper(name="controlItems")
    @XmlElement(name = "controlItem")
    public List<ControlItem> getControlItems() {
        return controlItems;
    }

    public void setControlItems(List<ControlItem> controlItems) {
        this.controlItems = controlItems;
    }

    @Override
    public String toString() {
        return "License{" +
                "licInfo=" + licInfo +
                ", controlItems=" + controlItems +
                '}';
    }
}
大致知道原因所在了,是因为xmlElement这个注解的问题

**Comment by diwenzheng** [comment]
这也是升级版本的原因,暂时还没找到怎么解决

**Comment by diwenzheng** [comment]
主要想办法忽略 jackson对于 @xmlElement的命名规则  这个能帮忙看看吗,我也在找解决问题

**Comment by diwenzheng** [comment]
我看到有办法忽略这个注解,1.3.0中对于这个注解还不敏感,2.5.0对于这个很敏感了,有没有相关接口方便我自己修改你们底层的mapper,这就让我很困扰.

我用注解的目的只是为了生成这样格式的xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<license>
    <licInfo>

    </licInfo>
    <controlItems>
        <controlItem>

        </controlItem>
        <controlItem>

        </controlItem>
        <controlItem>

        </controlItem>
    </controlItems>
</license>

**Comment by liubao68** [comment]
java chassis没有解析这个注解。 怀疑是 swagger 会解析，可以看下最终生成的 swagger 的内容。

**Comment by diwenzheng** [comment]
<definitions:
  RxxxponseRxxxult:
    type: "object"
    propertixxx:
      data:
        type: "object"
      code:
        type: "string"
      mxxxsage:
        type: "string"
    x-java-class: "xxx.xxx.foundation.rxxxponse.common.data.RxxxponseRxxxult"
  LicInfo:
    type: "object"
    propertixxx:
      lsn:
        type: "string"
      product:
        type: "string"
      version:
        type: "string"
      issuer:
        type: "string"
      creator:
        type: "string"
      createTime:
        type: "string"
        format: "date-time"
      customer:
        type: "string"
      country:
        type: "string"
      expirationTime:
        type: "string"
        format: "date-time"
      licenseType:
        type: "string"
        dxxxcription: "- PERMANENT_LICENSE: \n- YEAR_LICENSE: \n- TRY_OUT_BUSINxxxS_LICENSE:\
          \ \n- BUSINxxxS_LICENSE: \n"
        enum:
        - "0"
        - "1"
        - "2"
        - "3"
        x-java-class: "xxx.license.enums.LicenseType"
      licenseApplyYear:
        type: "string"
      electronicSerialNumber:
        type: "string"
      contractNumber:
        type: "string"
      sign:
        type: "string"
    x-java-class: "xxx.license.pojo.LicInfo"
  license:
    type: "object"
    propertixxx:
      licInfo:
        $ref: "#/definitions/LicInfo"
      controlItem:
        type: "array"
        xml:
          name: "controlItems"
          wrapped: true
        items:
          xml:
            name: "controlItem"
          $ref: "#/definitions/ControlItem"
    xml:
      name: "license"
    x-java-class: "XXXX.vo.License"
]

看起来确实是 这个问题 那么该如何修改

**Comment by diwenzheng** [comment]
![image](https://user-images.githubusercontent.com/60613511/132936526-0cdb579c-7a8b-48ed-8855-3a888af6f253.png)

**Comment by liubao68** [comment]
可以分析下xml标签的用途， java chassis不使用这个标签， 如果可以的话，删除即可。

**Comment by diwenzheng** [comment]
> 可以分析下xml标签的用途， java chassis不使用这个标签， 如果可以的话，删除即可。

这是我要用的- -

**Comment by diwenzheng** [comment]
我现在的做法 就是换了一个实体类,把之前实体类的数据覆盖过来.就没问题了.但我还是希望能真正解决这个问题的本质.原因我已经说了,是因为@xmlElement的标签,让swagger这里的返回的json,认为这个标签的内容是我希望转换的,所以当我使用@jsonProerty这个注解,他就会报错二义性.这本身就是个bug,应该有优先级的.

**Comment by diwenzheng** [comment]
我们工程里这块的类有些地方还是应用这个注解的,改起来很麻烦,而且还是复制一份代码这种工作.建议还是帮忙看看如何兼容这种问题,感谢.

**Comment by diwenzheng** [comment]
https://github.com/swagger-api/swagger-ui/issues/2907 这个问题 不知道有没有被修复,看起来官方只是把它放到3.0去做,还是18年的问题.但是看分支他们有一个2.0,官方是否可以尝试使用2.0看看问题是否还存在,如果还有,框架总不能因为swagger有局限性把,是否可以干掉swagger解析这块.或者自己修复这块的问题呢

**Comment by diwenzheng** [comment]
或者如果不影响框架整体,尝试使用1.3.0的swagger版本可以吗.1.3.0没有这个问题。

**Comment by liubao68** [comment]
1. java-chassis 2.x 无法升级到到 swagger 2.x， 因为2.x支持的open api是不同版本， 不兼容。 这个规划是在 java-chassis 3.x 进行升级。 
2. java-chassis无法降低swagger版本， 一般来讲，只能生版本，无法降版本。 因为老版本的安全等问题无法追溯。 

1.3.0使用的是1.5.22版本， 你可以通过[maven dependency manage ](https://servicecomb.apache.org/cn/docs/maven_dependency_management/) 使用这个版本临时规避， 尽管不建议这么做。

**Comment by diwenzheng** [comment]
> 1. java-chassis 2.x 无法升级到到 swagger 2.x， 因为2.x支持的open api是不同版本， 不兼容。 这个规划是在 java-chassis 3.x 进行升级。
> 2. java-chassis无法降低swagger版本， 一般来讲，只能升版本，无法降版本。 因为老版本的安全等问题无法追溯。
> 
> 1.3.0使用的是1.5.22版本， 你可以通过[maven dependency manage ](https://servicecomb.apache.org/cn/docs/maven_dependency_management/) 使用这个版本临时规避， 尽管不建议这么做。
> 
> 另外， 我发现你提供的代码可能有点问题：
> 
> ```
> private List controlItems;
>  @XmlElementWrapper(name="controlItems")
> @XmlElement(name = "controlItem")
> public List<ControlItem> getControlItems() {
>     return controlItems;
> }
> 
> public void setControlItems(List<ControlItem> controlItems) {
>     this.controlItems = controlItems;
> }
> ```
> 
> java-chassis使用泛型，必须制定具体类型。
> 
> ```
> private List<ControlItem> controlItems;  // 必须制定具体类型
> 
>  @XmlElementWrapper(name="controlItems")
> @XmlElement(name = "controlItem")
> public List<ControlItem> getControlItems() {
>     return controlItems;
> }
> 
> public void setControlItems(List<ControlItem> controlItems) {
>     this.controlItems = controlItems;
> }
> ```

能方便举个例子吗,我尝试去看了https://www.bookstack.cn/read/java-chassis-1.x/1a25b5dc81f6fec0.md.不知道你说的具体类型是什么.

关于swagger的问题,我决定还是使用新po去规避把. 我有在jackson那边也有提问他们对于这个问题也是想着规避,这看起来已经是约束了.你们可以在文档中标注下这个约束.
