### ISSUE TITLE
servicecomb是否支持指定Ip和port调用Provider

### ISSUE THREAD

**Issue by faryang-sh** [apache/servicecomb-java-chassis#2570]
dubbo中支持指定Ip Port调用Provider，servicecomb中是否有相应的api来支持这一特性。
dubbo这一特性文档地址：https://dubbo.apache.org/zh/docs/v2.7/user/examples/invoke-with-specified-ip/

**Comment by liubao68** [comment]
可以的， 参考： [使用 Context 参数](https://servicecomb.apache.org/references/java-chassis/zh_CN/build-provider/context-param.html)

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
