### ISSUE TITLE
2.x版本中watch超时配置失效

### ISSUE THREAD

**Issue by waibozie** [apache/servicecomb-java-chassis#2571]
Describe the bug
2.x版本中watch超时配置失效， 即`servicecomb.service.registry.client.timeout.watch`配置失效

原因是通过SPI（RegistryHttpClientOptionsSPI）重构了HttpClientWithContext的获取方式。

 在RegistryWatchHttpClientOptionsSPI的实现中超时配置继承于RegistryHttpClientOptionsSPI的值，及当前实现下watch超时的实际配置来源于`servicecomb.service.registry.client.timeout.idle`

修改方法可以`RegistryWatchHttpClientOptionsSPI`中Override `getIdleTimeoutInSeconds`方法。

To Reproduce
必现

Expected behavior
`servicecomb.service.registry.client.timeout.watch`生效

Platform And Runtime (please complete the following information):
环境无差别，稳定复现

Additional context
无

**Comment by liubao68** [comment]
方便提交一个PR修改下吗？

**Comment by waibozie** [comment]
可以，晚些时候我会提交

**Comment by diwenzheng** [comment]
这里的watch 其实我一直没太搞懂 ,能方便说一下嘛.

**Comment by waibozie** [comment]
> 这里的watch 其实我一直没太搞懂 ,能方便说一下嘛.

可以把问题范围缩小、实例化吗？

**Comment by waibozie** [comment]
> 方便提交一个PR修改下吗？

我看最新分支上已经把`servicecomb.service.registry.client.timeout.watch`配置项删除了，确认一下这是有意为之还是误操作？

修改的提交记录：![cb-2317](https://github.com/apache/servicecomb-java-chassis/pull/2531/files)， contributor是@develpoerX

讨论确认一下。

**Comment by diwenzheng** [comment]
> > 这里的watch 其实我一直没太搞懂 ,能方便说一下嘛.
> 
> 可以把问题范围缩小、实例化吗？

大致就是pull和watch的区别,以及各个的作用,目前我了解pull就是和注册中心的心跳,而且偶尔我看到心跳交互有异常,你在应用的时候有看过心跳错误的日志吗,方便说下你们的部署模式吗,稍微广一点哈.

**Comment by waibozie** [comment]
> > > 这里的watch 其实我一直没太搞懂 ,能方便说一下嘛.
> > 
> > 
> > 可以把问题范围缩小、实例化吗？
> 
> 大致就是pull和watch的区别,以及各个的作用,目前我了解pull就是和注册中心的心跳,watch我没有用,yaml配置的是false,所以对watch的理解不是太到位,而且偶尔我看到心跳交互有异常,你在应用的时候有看过心跳错误的日志吗,方便说下你们的部署模式吗,稍微广一点哈.

我个人觉得你认为的pull是心跳理解有不太恰当， 服务和远端的注册中心的心跳是通过HeartbeatTask来维持的；

至于pull和watch需要说明一下调用模型： 服务在运行过程中会与其他服务产生调用关系，基于一个假设：服务consumer如果在
运行过程中调用过服务provider，则在后续运行过程中也会存在调用，为了下次调用能直接命中provider的有效实例，java-chassis在调用远端的注册中心实例发现接口时，会隐式的创建一下consumer到provider的依赖关系， 后续服务provider实例的任何变更会通过websocket推送的java-chassis，表现到的接口行为就是watch。

简单来说，就是服务调用产生依赖关系，依赖关系的provider服务变化后通知consumer，consumer就可以更新本地的实例缓存了。servicecomb社区的chassis（go-chassis、java-chassis）提供了更新本地实例缓存的机制：pull和watch， pull是轮询的逻辑，定期拉取实例，watch则是远端注册中心主动推送（java-chassis当前只是把这种推送当做是一个信号，会忽略推送中的信息，收到信号后主动去pull一次数据）。

总结一下，pull是客户端轮询行为， watch是注册中心主动推送变化的行为，两者都是解决本地缓存的刷新，加上watch后时效性会较好。

**Comment by diwenzheng** [comment]
> > > > 这里的watch 其实我一直没太搞懂 ,能方便说一下嘛.
> > > 
> > > 
> > > 可以把问题范围缩小、实例化吗？
> > 
> > 
> > 大致就是pull和watch的区别,以及各个的作用,目前我了解pull就是和注册中心的心跳,watch我没有用,yaml配置的是false,所以对watch的理解不是太到位,而且偶尔我看到心跳交互有异常,你在应用的时候有看过心跳错误的日志吗,方便说下你们的部署模式吗,稍微广一点哈.
> 
> 我个人觉得你认为的pull是心跳理解有不太恰当， 服务和远端的注册中心的心跳是通过HeartbeatTask来维持的；
> 
> 至于pull和watch需要说明一下调用模型： 服务在运行过程中会与其他服务产生调用关系，基于一个假设：服务consumer如果在
> 运行过程中调用过服务provider，则在后续运行过程中也会存在调用，为了下次调用能直接命中provider的有效实例，java-chassis在调用远端的注册中心实例发现接口时，会隐式的创建一下consumer到provider的依赖关系， 后续服务provider实例的任何变更会通过websocket推送的java-chassis，表现到的接口行为就是watch。
> 
> 简单来说，就是服务调用产生依赖关系，依赖关系的provider服务变化后通知consumer，consumer就可以更新本地的实例缓存了。servicecomb社区的chassis（go-chassis、java-chassis）提供了更新本地实例缓存的机制：pull和watch， pull是轮询的逻辑，定期拉取实例，watch则是远端注册中心主动推送（java-chassis当前只是把这种推送当做是一个信号，会忽略推送中的信息，收到信号后主动去pull一次数据）。
> 
> 总结一下，pull是客户端轮询行为， watch是注册中心主动推送变化的行为，两者都是解决本地缓存的刷新，加上watch后时效性会较好。

非常感谢你的分享.我说的比较片面,哈哈.之前我一直很困扰服务应用内部频发报心跳的问题.服务不停打印那些心跳超时的日志.看到你的issue才让我去仔细去看了pull,watch的问题.另外官方文档中说.watch事件走websocket，watch事件是观察服务中心实例信息有没有变更。我现在刚更改了使用watch模式,随后我在观察服务会不会在报心跳的问题.

**Comment by diwenzheng** [comment]
更改了watch之后.好像还是有这个问题,

servicecomb:
  service:
    environment: development
    application: XXX
    name: mock-server
    version: 1.1.0
    registry:
      address: ${REGISTRY_ADDRESS}
      client:
        timeout:
          idle: 60
      instance:
        healthCheck:
          interval: 60
          times: 6
        pull:
          interval: 60
        watch: true
        empty:
          pretection: true
      autodiscovery: true


2021-09-12 16:12:32.434 - [ERROR] - [registry-vert.x-eventloop-thread-1] - [o.a.s.s.client.http.RestClientUtil] - [RestClientUtil.java:145] - GET /v4/default/registry/instances?rev=5970674cffceb553d8e52ef4b944843af37c5743&appId=default&global=true&serviceName=SERVICECENTER&env=development&version=0.0.0.0%2B fail, endpoint is 10.0.1.223:30100, message: Connection was closed


2021-09-12 16:12:32.436 - [WARN] - [registry-vert.x-eventloop-thread-1] - [o.a.s.s.c.h.ServiceRegistryClientImpl] - [ServiceRegistryClientImpl.java:128] - invoke service [10.0.1.223:30100] failed, retry address [10.0.1.224:30100].
你的服务会有这些吗? 这让我困扰很久了.

**Comment by diwenzheng** [comment]
我之前想过是因为心跳设置的timeout时间不够,尝试加到15秒还是30秒我忘记了,但仍然有这个问题,

**Comment by waibozie** [comment]
> 更改了watch之后.好像还是有这个问题,
> 
> servicecomb:
> service:
> environment: development
> application: XXX
> name: mock-server
> version: 1.1.0
> registry:
> address: ${REGISTRY_ADDRESS}
> client:
> timeout:
> idle: 60
> instance:
> healthCheck:
> interval: 60
> times: 6
> pull:
> interval: 60
> watch: true
> empty:
> pretection: true
> autodiscovery: true
> 
> 2021-09-12 16:12:32.434 - [ERROR] - [registry-vert.x-eventloop-thread-1] - [o.a.s.s.client.http.RestClientUtil] - [RestClientUtil.java:145] - GET /v4/default/registry/instances?rev=5970674cffceb553d8e52ef4b944843af37c5743&appId=default&global=true&serviceName=SERVICECENTER&env=development&version=0.0.0.0%2B fail, endpoint is 10.0.1.223:30100, message: Connection was closed
> 
> 2021-09-12 16:12:32.436 - [WARN] - [registry-vert.x-eventloop-thread-1] - [o.a.s.s.c.h.ServiceRegistryClientImpl] - [ServiceRegistryClientImpl.java:128] - invoke service [10.0.1.223:30100] failed, retry address [10.0.1.224:30100].
> 你的服务会有这些吗? 这让我困扰很久了.

你的链接timeout和pull的周期一致了，或许是这导致的问题：pull的时候尝试复用到了一个马上超时的链接，导致了Connection was closed。

这只是从你配置中看到的可能的原因，进一步的debug确认应该可以证明这一点对不对。

**Comment by diwenzheng** [comment]
> > 更改了watch之后.好像还是有这个问题,
> > servicecomb:
> > service:
> > environment: development
> > application: XXX
> > name: mock-server
> > version: 1.1.0
> > registry:
> > address: ${REGISTRY_ADDRESS}
> > client:
> > timeout:
> > idle: 60
> > instance:
> > healthCheck:
> > interval: 60
> > times: 6
> > pull:
> > interval: 60
> > watch: true
> > empty:
> > pretection: true
> > autodiscovery: true
> > 2021-09-12 16:12:32.434 - [ERROR] - [registry-vert.x-eventloop-thread-1] - [o.a.s.s.client.http.RestClientUtil] - [RestClientUtil.java:145] - GET /v4/default/registry/instances?rev=5970674cffceb553d8e52ef4b944843af37c5743&appId=default&global=true&serviceName=SERVICECENTER&env=development&version=0.0.0.0%2B fail, endpoint is 10.0.1.223:30100, message: Connection was closed
> > 2021-09-12 16:12:32.436 - [WARN] - [registry-vert.x-eventloop-thread-1] - [o.a.s.s.c.h.ServiceRegistryClientImpl] - [ServiceRegistryClientImpl.java:128] - invoke service [10.0.1.223:30100] failed, retry address [10.0.1.224:30100].
> > 你的服务会有这些吗? 这让我困扰很久了.
> 
> 你的链接timeout和pull的周期一致了，或许是这导致的问题：pull的时候尝试复用到了一个马上超时的链接，导致了Connection was closed。
> 
> 这只是从你配置中看到的可能的原因，进一步的debug确认应该可以证明这一点对不对。

你的配置是啥样子的? 能参考下吗

**Comment by waibozie** [comment]
> > 方便提交一个PR修改下吗？
> 
> 我看最新分支上已经把`servicecomb.service.registry.client.timeout.watch`配置项删除了，确认一下这是有意为之还是误操作？
> 
> 修改的提交记录：[cb-2317](https://github.com/apache/servicecomb-java-chassis/pull/2531/files)， contributor是@develpoerX
> 
> 讨论确认一下。

讨论有点偏离主题了

@liubao68 我们回到主题，我把话题迁移回来。

**Comment by liubao68** [comment]
这个提交没问题， 只是删除了无用的方法。看起来这个配置项是没有用的，我理解应该不会存在这么一个配置项。 你在哪个应用场景（版本）需要使用或者依赖到这个配置项吗？从业务需要出发， 在看下最早加这个配置项是做什么的。

**Comment by develpoerX** [comment]
> > 方便提交一个PR修改下吗？
> 
> 我看最新分支上已经把`servicecomb.service.registry.client.timeout.watch`配置项删除了，确认一下这是有意为之还是误操作？
> 
> 修改的提交记录：[cb-2317](https://github.com/apache/servicecomb-java-chassis/pull/2531/files)， contributor是@develpoerX
> 
> 讨论确认一下。

你说的这个问题，是一个无效的方法，在删除之前，它在整个项目中没有任何地方被使用到，所以我就删除了它。我猜测之前应该是有操作吧这个配置项删除，或者有存在预设了一个配置项，但是还没有想好使用场景，因此没有用到这个配置。

**Comment by waibozie** [comment]
> > > 方便提交一个PR修改下吗？
> > 
> > 
> > 我看最新分支上已经把`servicecomb.service.registry.client.timeout.watch`配置项删除了，确认一下这是有意为之还是误操作？
> > 修改的提交记录：[cb-2317](https://github.com/apache/servicecomb-java-chassis/pull/2531/files)， contributor是@develpoerX
> > 讨论确认一下。
> 
> 你说的这个问题，是一个无效的方法，在删除之前，它在整个项目中没有任何地方被使用到，所以我就删除了它。我猜测之前应该是有操作吧这个配置项删除，或者有存在预设了一个配置项，但是还没有想好使用场景，因此没有用到这个配置。

从git提交记录看，这个配置是一个非常老的提交：[[JAV-442]add PULL support between SDK and service center](https://github.com/apache/servicecomb-java-chassis/commit/1626b64a1bbf262420096214577317fe7f784cd5)
```java
// WebSocketClientPool   tag 1.2.0
  @Override
  public HttpClientOptions createHttpClientOptions() {
    // ignore
    httpClientOptions.setIdleTimeout(ServiceRegistryConfig.INSTANCE.getIdleWatchTimeout());
    // ignore
}
```
我记得注册中心的websocket策略的30s一次，且不接受客户端的ping，只允许注册中心主动ping客户端， 在我的场景里我把这个值调整得比心跳的超时的链路超时长得多。

2.X的重构确实破坏了这个配置项，我个人觉得把它独立出来还是有必要的， 比较注册中心的ping/pong策略比较特别。

@liubao68 @develpoerX 你们觉得呢？

**Comment by liubao68** [comment]
谢谢你提供的信息。 可以把这个配置项加回来。 是在代码重构的时候，疏漏了。

**Comment by waibozie** [comment]
好的， 晚些时候我会提交PR加入`servicecomb.service.registry.client.timeout.watch`配置

**Comment by waibozie** [comment]
在完成这种修改的过程中， 我同时发现UT中的配置读取似乎存在问题，即[TestServiceRegistryConfig](https://github.com/apache/servicecomb-java-chassis/blob/master/service-registry/registry-service-center/src/test/java/org/apache/servicecomb/serviceregistry/config/TestServiceRegistryConfig.java)并不能读取测试resource下的microservice.yaml问题， 这可能是一个项目的的共有问题，可以开一个单独的issue跟踪处理这个问题。 

同时本项目的CI测试用例有构建吗？ 如果有的话，能告诉我一下具体的位置吗？ 我没找到，这样能避免后续的重构对既有功能的破坏。
