### ISSUE TITLE
可靠性问题

### ISSUE THREAD

**Issue by fanjiang-2021** [apache/servicecomb-java-chassis#2587]
https://github.com/apache/servicecomb-java-chassis/blob/b1948e193c7516a58dcc70f72adabb574171a0c4/foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/consumer/MicroserviceVersions.java#L252

pulledInstances 目前 包含 所有的instance,在极端场景下,比如说注册中心 跟服务端同时出故障,然后又恢复,服务端IP 发生变更,这个时候pulledInstances 会包含服务端新旧两个实例信息,这个时候 旧实例信息 实际已经不可用,当前操作 是将pulledInstances 所有的instance添加到instances,是否可以加一个判断 在处理,比如:
  MergedInstances mergedInstances = new MergedInstances();
    MicroserviceInstancePing ping = SPIServiceUtils.getPriorityHighestService(MicroserviceInstancePing.class);
    pulledInstances.stream().forEach(instance -> {
      if (ping.ping(instance)){
        mergedInstances.addInstance(instance);
      }
    });

**Comment by liubao68** [comment]
目前检查的是客户端缓存的实例，而从注册中心查询上来的实例是不做检查的，你列的只是一个极小概率的场景，而且即使发生，也会很快恢复。
