### ISSUE TITLE
restTemplate.postForObject()第一次调用超时

### ISSUE THREAD

**Issue by Riiiiicher** [apache/servicecomb-java-chassis#2595]
在第一次使用restTemplate.postForObject()这种方式请求cse类型的url时(例如：cse://XXXService:XXXMircoService/xxx)，会消耗很长时间来从注册中心加载目标微服务的所有版本和schema下的实体，导致第一次调用总是超时的现象。
以上情况怎么处理规避呢？

**Comment by liubao68** [comment]
你使用的那个版本？契约个数大概是多少？

**Comment by Riiiiicher** [comment]
> 你使用的那个版本？契约个数大概是多少？

servicecomb版本为1.3.2，契约数量除去安全检查和性能外有26个

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
