### ISSUE TITLE
InvocationContext传递的参数 服务端如何获取

### ISSUE THREAD

**Issue by five111** [apache/servicecomb-java-chassis#2596]
客户端代码如下
`
            CseHttpEntity<?> entity = new CseHttpEntity<>(null);

            InvocationContext invocationContext = new InvocationContext();

            invocationContext.addContext("aaa", "bbb");

            entity.setContext(invocationContext);

            UUID uuid = UUID.randomUUID();

            System.out.println(formatter.format(new Date())+uuid);

            ResponseEntity<String> responseEntity =
                    restTemplate.getForEntity(url + uuid, String.class, entity)
`
我想将aaa传递至服务端
服务端对应接口如下
`
    @GetMapping("/hello/{name}")
    public String sayHello(@PathVariable("name") @Length String name, InvocationContext invocationContext) throws InterruptedException {
        System.out.println(invocationContext.getContext().get("aaa"));
        System.out.println(formatter.format(new Date())+ " " +name);
        return name+", hello";
    }
`
这里无法获取到上下文的值
请问这个值该如何正确传递和获取
https://servicecomb.apache.org/references/java-chassis/zh_CN/build-provider/context-param.html
文档这里描述的不是很清晰，我服务端的写法是照着文档写的，建议文档能安招从客户端-》服务端的过程来描述

**Comment by fanjiwang1992** [comment]
客户端设置方式:
第一种:  通过ContextUtils直接获取invocationContext
     InvocationContext invocationContext = ContextUtils.getInvocationContext();
     invocationContext.addContext("csefjw", "ddddd");
第二种: 直接new InvocationContext() 放进CseHttpEntity中
 InvocationContext invocationContext = new InvocationContext();
 CseHttpEntity<?> entity = new CseHttpEntity<>(null)
entity.setContext(invocationContext);

服务端获取方式:
第一种: 通过ContextUtils直接获取invocationContext
InvocationContext invocationContext = ContextUtils.getInvocationContext()
invocationContext .getContext()或者指定具体的key 
第二种: 在接口参数中添加 InvocationContext invocationContext
![image](https://user-images.githubusercontent.com/84115877/134656073-0f1e172b-f3bc-4a9f-84f5-8a7c30491444.png)

**Comment by five111** [comment]
@fanjiwang1992  感谢回答 但似乎不太起作用 ，这样的做法似乎只在接口处使用有效，我的业务场景是在系统启动后，开启一个任务，任务中去发送请求给指定微服务，这种场景下 似乎无法传递

**Comment by fanjiwang1992** [comment]
InvocationContext invocationContext = new InvocationContext();

        invocationContext.addContext("aaa", "bbb");

        entity.setContext(invocationContext);

        UUID uuid = UUID.randomUUID();

        System.out.println(formatter.format(new Date())+uuid);

        ResponseEntity<String> responseEntity =
                restTemplate.getForEntity(url + uuid, String.class, entity)
--------------------------------------------------------------------------------------

用restTemplate的exchange方法 传递 CseHttpEntity

**Comment by five111** [comment]
感谢  @fanjiwang1992 的回答 问题清晰了 new的InvocationContext 需要正确传递下去，之前使用的调用方式不能正确将这个参数传递下去，导致后面new了一个新的invocation 接口中的InvocationContext 是从ContextUtils中获取的，直接赋值即可
