### ISSUE TITLE
提个优化建议，serviceComb 的sdk在打印异常时，能否把异常堆栈打印出来，便于问题定位

### ISSUE THREAD

**Issue by zhoutianli518** [apache/servicecomb-java-chassis#2605]
java-Chassis sdk在打印异常时，能否将堆栈打出来，便于问题的定位。比如：
org.apache.servicecomb.core.handler.impl.ProducerOperationHandler的如下代码，当出现异常后，打印的日志里，没有将异常堆栈打印出来，只是打印了异常的message，导致出现运行期异常时，很难定位问题。

  public Response doInvoke(Invocation invocation, SwaggerProducerOperation producerOperation) {
    Response response;
    try {
      invocation.onBusinessMethodStart();

      Object[] args = invocation.toProducerArguments();
      for (ProducerInvokeExtension producerInvokeExtension : producerOperation.getProducerInvokeExtenstionList()) {
        producerInvokeExtension.beforeMethodInvoke(invocation, producerOperation, args);
      }

      Object result = producerOperation.getProducerMethod().invoke(producerOperation.getProducerInstance(), args);
      response = producerOperation.getResponseMapper().mapResponse(invocation.getStatus(), result);

      invocation.onBusinessMethodFinish();
      invocation.onBusinessFinish();
    } catch (Throwable e) {
      if (shouldPrintErrorLog(e)) {
        invocation.getTraceIdLogger().error(LOGGER, "unexpected error operation={}, message={}",
            invocation.getInvocationQualifiedName(),
            org.apache.servicecomb.foundation.common.utils.ExceptionUtils.getExceptionMessageWithoutTrace(e));
      }
      invocation.onBusinessMethodFinish();
      invocation.onBusinessFinish();
      response = processException(invocation, e);
    }
    return response;
  }

**Comment by fanjiwang1992** [comment]
可以基于SPI 机制,通过 ExceptionToProducerResponseConverter 拦截异常来扩展

**Comment by liubao68** [comment]
可以考虑增加一个配置项 `servicecomb.error.printSensitiveErrorMessage` 来统一控制对于安全（信息泄露）有争议的日志输出，默认为 false。

**Comment by liubao68** [comment]
fixed in https://github.com/apache/servicecomb-java-chassis/pull/2644/files
