### ISSUE TITLE
流控代码疑问

### ISSUE THREAD

**Issue by Nick-The-Uncharted** [apache/servicecomb-java-chassis#2611]
1.  https://github.com/apache/servicecomb-java-chassis/blob/c5a929e16dea239024da00715b9510cec5112282/handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/strategy/LeakyBucketStrategy.java#L45 此处是否应该为Math.min
2. https://github.com/apache/servicecomb-java-chassis/blob/c5a929e16dea239024da00715b9510cec5112282/handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/QpsControllerManager.java#L223 此处读取的key并非文档里的servicecomb.flowcontrol.**Provider**.qps.strategy

**Comment by Nick-The-Uncharted** [comment]
https://github.com/apache/servicecomb-java-chassis/blob/3286fa4e6235b14809b62e35becb1cbb49ca260d/governance/src/main/java/org/apache/servicecomb/governance/MatchersManager.java#L46

这里是不是应该检查取出的value为Boolean.TRUE

**Comment by lbc97** [comment]
> 

没看见文档中的QPS流控配置项说明里面有servicecomb.flowcontrol.Provider.qps.strategy这个配置
https://huaweicse.github.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/references-handlers/ratelimit.html

**Comment by liubao68** [comment]
For Matchers manager, it is designed for performance and you need to add rate liming in a invocation context and will not have the problem. 

But this performance improvement seems not neccessary, see https://issues.apache.org/jira/browse/SCB-2628. And will remove this.

**Comment by Nick-The-Uncharted** [comment]
> 2\. servicecomb.flowcontro

可能是我当时看错了。。时间有点久远
