### ISSUE TITLE
RegistryUtils.getServiceRegistry().findServiceInstance 首次正常 第二次内部空指针

### ISSUE THREAD

**Issue by diwenzheng** [apache/servicecomb-java-chassis#2612]
通过RegistryUtils.getServiceRegistry().findServiceInstance获取服务列表,首次正常,之后我看源码获取缓存的时候空指针.

RegistryUtils.findServiceInstance  正常

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
