### ISSUE TITLE
不同注册中心间服务调用

### ISSUE THREAD

**Issue by faryang-sh** [apache/servicecomb-java-chassis#2613]
场景：有2个注册中心，分布式是注册中心1和注册中心2，A、B、C服务是注册到1中，D、E、F服务是注册到2中。
问题：对于跨注册中心的服务间调用，应该怎么做？例如，现在A服务想访问到D、E、F中接口，应该怎么做？

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
