### ISSUE TITLE
关于接口响应 httpStatus的问题

### ISSUE THREAD

**Issue by diwenzheng** [apache/servicecomb-java-chassis#2621]
除了 使用 throw new InvocationException 这样抛异常的方式,正常使用不可以吗？ @liubao68

**Comment by pigbayspy** [comment]
这玩意不支持 `@ResponseStatus` 注解的，很无语

**Comment by pigbayspy** [comment]
我自己试了可以用这种方法返回异常
```java
    @GetMapping("/hello")
    public ResponseEntity<?> hello() {
        InvocationException exception = new InvocationException(Response.Status.BAD_REQUEST, "hello");
        ResponseEntity<InvocationException> response = new ResponseEntity<>(exception, HttpStatus.BAD_REQUEST);
        return response;
    }
```

**Comment by diwenzheng** [comment]
> 我自己试了可以用这种方法返回异常
> 
> ```java
>     @GetMapping("/hello")
>     public ResponseEntity<?> hello() {
>         InvocationException exception = new InvocationException(Response.Status.BAD_REQUEST, "hello");
>         ResponseEntity<InvocationException> response = new ResponseEntity<>(exception, HttpStatus.BAD_REQUEST);
>         return response;
>     }
> ```

这种可以吗?响应体如果是自己的po还可以传入异常类吗？ 我们已经发现了处理方式,第一个 使用Response这个替代 ResponseEntity,该对象内部是存在createFail方式的 那么第二个就是 使用自定义处理链 来处理自己想要返回的异常情况。

本质原因是因为内部还是过于依赖Swagger的东西,其实与springboot还是有很大的区别,即使用过程中给开发人员带来很多不便。@liubao68

**Comment by liubao68** [comment]
servicecomb和spring boot是有差异的， 主要体现在spring boot早期是基于 `servlet` 的 REST 实现， 所以包含了很多 `servlet` 特性。 servicecomb 主打的并不是 `servlet` ， 而是基于 `Open API` 的 RPC 框架， 所以会有差异。 

处理错误码可以参考 :  https://servicecomb.apache.org/references/java-chassis/zh_CN/general-development/error-handling.html

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
