### ISSUE TITLE
多个handler协同处理

### ISSUE THREAD

**Issue by yfliuas** [apache/servicecomb-java-chassis#2630]
项目中包含多个handler+HttpServerFilter，大致：
A-handler --> B-handler --> C-handler --> D-httpServerFilter --> 业务代码 --> D-httpServerFilter
我们需要在A-handler失败之后，直接返回形如 413 xxxerror的错误码。

在handler中直接调用如下代码，预期B-handler之后的handler应该不会执行：
`
asyncResponse.consumerFail(new InvocationException(413, "forbidden", "request error"));
`
调用如下代码，预期走下一个handler：
`
invocation.next(asyncResponse);
`

发现在A-handler调用consumerFail之后，依然走了B-handler的逻辑，请问从Servicecomb预期应该怎么样

**Comment by yfliuas** [comment]
确认是servicecomb 2.1.5版本bug

**Comment by liubao68** [comment]
你能提供下修复链接吗？貌似没修复过类似问题。 另外， 你有试过哪个版本修复过这个问题吗？

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
