### ISSUE TITLE
高版本spring(5.3.7以及以上)UriComponentsBuilder的URI_PATTERN发生变化，没办法识别CSE的URI(cse://appid:servicename/...))

### ISSUE THREAD

**Issue by fanjiwang1992** [apache/servicecomb-java-chassis#2631]

**Comment by fanjiwang1992** [comment]
![image](https://user-images.githubusercontent.com/84115877/140675013-7bf745c7-b28a-4cad-a0e6-43edb7e15269.png)

**Comment by fanjiwang1992** [comment]
UriComponentsBuilder handles invalid port numbers correctly 

https://github.com/spring-projects/spring-framework/pull/26905

**Comment by liubao68** [comment]
这个使用方式是 servicecomb 早期设计不当导致的。 服务名 `APP:SERIVCE` 中的 `:` 会破坏 url 语义。 有如下建议：

1. 使用 `APP.SERIVCE`  替换  `APP:SERIVCE` 
2. 解析服务名的代码做判断，如果使用了  `APP:SERIVCE` ， 提示错误； 服务名和应用名如果包含 `.`， 也检查一下提示错误，建议用户使用 `-` 替换。 以避免 url 中 `.` 带来的歧义。

**Comment by develpoerX** [comment]
建议保留并兼容老的策略。添加一个开关进行对老的写法进行校验。默认开关是打开的，只有老用户不愿意修改时，可以关闭校验开关，进行规避。

**Comment by liubao68** [comment]
修改方案：
1. 如果业务代码使用了 APP:SERIVCE ， 打印一行警告日志， 并将 APP:SERIVCE 转换为 APP.SERIVCE 进行调用。
2. 后续正确的用法使用 APP:SERIVCE 。

**Comment by liubao68** [comment]
如果 使用 APP.SERIVCE 替换 APP:SERIVCE 会涉及很多兼容性问题， 包括：

1. 注册中心microservice的alias机制需要修改
2. `@RpcReference`的名字需要修改
3. RestTemplate的 `cse://app:ms` 需要修改

特别1和2,3的修改有矛盾的地方。 这个版本暂时不做这个变更。 仍然保留老的习惯， 支持  `cse://app:ms`
