### ISSUE TITLE
上传文件接口edge调用微服务，是否可以支持接收MultipartFile+Object

### ISSUE THREAD

**Issue by x00384074** [apache/servicecomb-java-chassis#2634]
问题场景：上传文件接口包含多个参数，而且参数还会不断变化，调用流程：edge->微服务，能否支持接收json并自动反序列化成Object对象
如果有方案，如何配置？

**Comment by liubao68** [comment]
HTTP只能有一个body。 body的编码要么是Form（文件），要么是json。 不能出现body放文件和json并存的情况。 

你可以使用header、query等参数。

**Comment by x00384074** [comment]
ok 多谢
