### ISSUE TITLE
resttemplate cse调用是不支持proxy代理访问还是我不会用，找了半点没找见。

### ISSUE THREAD

**Issue by NingGelin** [apache/servicecomb-java-chassis#2636]
本地调试服务，访问k8s集群服务，很需要该功能。

**Comment by NingGelin** [comment]
sock协议

**Comment by liubao68** [comment]
目前不支持proxy访问。

**Comment by fanjiwang1992** [comment]
你外挂一个支持NIO的sock5协议

**Comment by fanjiwang1992** [comment]
可以参考一下这个 https://github.com/fanjiwang1992/nio-socks-proxy 目前已经验证可以的

**Comment by fanjiwang1992** [comment]
看看这个 https://github.com/fanjiwang1992/nio-socks-proxy 有没有帮助

**Comment by NingGelin** [comment]
> 看看这个 https://github.com/fanjiwang1992/nio-socks-proxy 有没有帮助

这个可以代理访问到k8s，我就是用的这个。   resttemplate调用的时候，如果使用http访问 + 这个代理是可以本地访问k8s服务的。但是使用cse模式就走不了代理。

**Comment by fanjiwang1992** [comment]
CSE 模式也是可以的呀 有业务这么用过 你可以把堆栈日志发一下吗

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
