### ISSUE TITLE
ServiceComb支持请求或者响应直接使用byte数组吗

### ISSUE THREAD

**Issue by lynnllh** [apache/servicecomb-java-chassis#2640]
用rest接口，请求体和响应体里面是可以直接塞byte数组的，但是这样的话，在byte数组上面还会再封装一层http。业务想请求体和响应体直接使用byte数组，这种支持吗

**Comment by liubao68** [comment]
"在byte数组上面还会再封装一层http"是什么意思？ 不是很理解。 

“业务想请求体和响应体直接使用byte数组” 指的是不用 HTTP 协议， 直接使用 TCP 协议？

**Comment by lynnllh** [comment]
对，想直接使用TCP协议

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
