### ISSUE TITLE
使用serviceComb提供的方法转发用spring-cloud-huawei开发的微服务post接口有问题，服务provide无法接收到body里面的内容

### ISSUE THREAD

**Issue by haozhi-ly** [apache/servicecomb-java-chassis#2646]
使用serviceComb提供的方法转发用spring-cloud-huawei开发的微服务post接口有问题，服务provide一直报缺少Required request body is missing。转发get请求时正常的，看serviceComb的文档说对springmvc的大部分注解都是支持的，例如@requestBody,@requestParam等，但实际调用发现post请求在使用上述2个注解的情况下一直接收不到参数。serviceComb是不是对spring-cloud-huawei的服务不支持啊？麻烦能解答下

serviceComb的调用方式如下
` 
EdgeInvocation edgeInvocation = new EdgeInvocation();
edgeInvocation.init(microserviceName, context, path, httpServerFilters);
edgeInvocation.edgeInvoke();
`
serviceComb的版本
<groupId>org.apache.servicecomb</groupId>
    <artifactId>java-chassis-dependencies-parent</artifactId>
    <version>2.5.3</version>
spring-cloud-huawei版本
<dependency>
        <groupId>com.huaweicloud</groupId>
        <artifactId>spring-cloud-huawei-bom</artifactId>
        <version>1.7.0-2020.0.x</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

**Comment by liubao68** [comment]
这个属于理解错误。 Spring Cloud Huawei主要是接入servicecomb提供的注册中心、配置中心， RPC框架还是Spring Cloud。 开发指南里面描述的是ServiceComb Java Chassis开发框架， ServiceComb Java Chassis在RPC、治理等功能设计上是完全不同于Spring Cloud的。 

edge service是给 ServiceComb Java Chassis 设计的， 默认情况下不能在 Spring Cloud工作， 对于非 ServiceComb Java Chassis服务， 可以考虑使用 [CommonHttpEdgeDispatcher](https://servicecomb.apache.org/references/java-chassis/zh_CN/edge/by-servicecomb-sdk.html)

**Comment by haozhi-ly** [comment]
ok
