### ISSUE TITLE
请问现在现网支持，一个cse注册中心兼容http和https的接入吗？

### ISSUE THREAD

**Issue by jessefjxm** [apache/servicecomb-java-chassis#2648]
我们服务计划将现网一个微服务接入CSE注册中心的方式改为HTTPS，但该注册中心其他微服务依然沿用HTTP接入。不知道这样是否可行呢？
![image](https://user-images.githubusercontent.com/1498592/144342282-b3dc81e0-30e4-49b0-9542-f48566b37db6.png)

**Comment by fanjiwang1992** [comment]
这个是注册中心服务端的能力 可以去这里咨询https://github.com/apache/servicecomb-service-center

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
