### ISSUE TITLE
微服务第一次调用耗时过久，希望框架提供预热加载机制，优化微服务第一次调用性能优化

### ISSUE THREAD

**Issue by develpoerX** [apache/servicecomb-java-chassis#2652]

**Comment by develpoerX** [comment]
两种策略，
1.提供给用户可以配置对应参数比如（微服务名，环境，版本，接口名，等信息），框架对这些配置的微服务实例进行预热加载。
2.框架做到自动化对全量微服务调用进行预热加载。通过开关控制，默认开关关闭

**Comment by liubao68** [comment]
预加载不是一个好的措施，主要表现为：1. 配置哪些预加载比较麻烦， 很难提前规划；2. 预加载实际上假设了一些启动顺序，否则预加载很容易出现错误。 

目前看针对这个问题比较好的优化手段是第一次调用的时候， 不全量加载微服务所有的契约，只加载当前访问的契约。

**Comment by liubao68** [comment]
还有个可行的方法：将契约信息放到客户端本地，不用从注册中心取契约。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
