### ISSUE TITLE
两个不同版本的微服务拥有相同接口A（指接口名称和接口映射一致），但接口实现方式不一样，并一个拥有B接口，一个没有B接口的调用情况

### ISSUE THREAD

**Issue by lbc97** [apache/servicecomb-java-chassis#2658]

**Comment by lbc97** [comment]
验证结果：
当consumer访问接口A时是轮询访问，即这一次访问调用provider1的A接口，下一次就会访问provider2的A接口，而B接口可以正常访问，与正常访问无异。
验证过程：
先启动两个provider项目（provider1,provider2），再启动consumer,然后多次调用A,B两个接口

**Comment by liubao68** [comment]
你的疑问和问题是什么？ 上面描述的现象是符合预期的。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
