### ISSUE TITLE
文件上传临时目录属主不对时，cse会抛出java.nio.file.AccessDeniedException异常，但此异常没有办法捕获，导致异常信息直接被抛到客户端，泄漏服务器路径信息

### ISSUE THREAD

**Issue by z00283015** [apache/servicecomb-java-chassis#2659]
问题现象：
业务上传功能的临时文件目录的属主不对，不是业务用户，而是root用户：
![image](https://user-images.githubusercontent.com/46476965/145182666-ce34cb7e-e1b2-45d8-97ba-50b9cb7ddbbe.png)
用户在web页面使用上传功能后，接口报错，查看接口响应，发现报错信息里暴露了服务器的路径信息：
![image](https://user-images.githubusercontent.com/46476965/145183134-f1338ea5-1354-4b9c-874c-80aac793c18c.png)
经过查找，发现会在cse_run.log里打印出这段异常信息：
![image](https://user-images.githubusercontent.com/46476965/145183314-e611f77b-fe52-4ef0-9bd1-2a3d10460384.png)
经过尝试，这个异常无法通过下面这个wiki里的几种方法，进行捕获：
https://servicecomb.apache.org/references/java-chassis/zh_CN/general-development/error-handling.html
后来，咨询了刘宝，得到结论是这个异常捕获不到：
![Snipaste_2021-12-08_17-30-55](https://user-images.githubusercontent.com/46476965/145184055-bc8cd3f0-da7b-4b91-a92a-1a0fc6135c35.PNG)
但由于这个问题会导致服务器路径泄漏，属于安全问题，因此建议做下优化，请帮忙处理下，谢谢：）

**Comment by liubao68** [comment]
fixed in 2.7.0
