### ISSUE TITLE
Java-Chassis 1.3 版本consumer端path参数编码存在问题, 不支持特殊字符`;.,`

### ISSUE THREAD

**Issue by yhs0092** [apache/servicecomb-java-chassis#2662]
复现用例见截图(直接在`org.apache.servicecomb.common.rest.definition.path.PathVarParamWriter`类里加main函数):
![image](https://user-images.githubusercontent.com/22049770/145749407-d4016002-a076-4b85-aa49-3b16b4f80aad.png)

Java-Chassis 1.3 版本没有正确对 `;` 和 `.` 以及 `,` 三种字符进行转义处理

**Comment by liubao68** [comment]
这个问题看起来属于理解错误。 `;`, `.`, `,` 是合法的 [URL-path-segment string](https://url.spec.whatwg.org/#syntax-url-path-segment) ， 是不需要转义的。 

理解错误的关键点在于  `;`, `.`, `,`  在 path-segment 中是有特殊含义的，  使用者不期望表现出这个特殊含义。 作为框架处理层， 是不知道使用者的意图， 是表现特殊含义还是不表现特殊含义？ 提这个问题显然是期望不表现特殊含义。 

考虑到上述歧义， 框架处理层只能二选一。 当使用者不期望表现出这个特殊含义时，需要自己预先转义，而不是框架转义。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
