### ISSUE TITLE
CSE在接收Content-Encoding为gzip的参数时，参数解析缺失了

### ISSUE THREAD

**Issue by MyLittlePlan** [apache/servicecomb-java-chassis#2663]
前端调用后端接口是将参数用gzip方式压缩，cse后端接口解析时无法解析出全部参数。

**Comment by liubao68** [comment]
能描述下问题发生的过程吗？ java-chassis服务之间的调用不会存在这个情况。

**Comment by MyLittlePlan** [comment]
前端传参数时，手动通过代码方式将参数进行gzip的方式进行压缩，java侧在解码入参时，一直提示解码失败

**Comment by MyLittlePlan** [comment]
前端是通过https来调用的，不是通过cse内部来调用的

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
