### ISSUE TITLE
Java-Chassis 1.x分支的下一个版本能否升级Vert.x 和 Netty 新版本?

### ISSUE THREAD

**Issue by yhs0092** [apache/servicecomb-java-chassis#2671]
Vert.x 3.9.11 新版本已发布, 集成 Netty 4.1.72.Final 版本, 修复了一些漏洞. 麻烦在下个 1.x 版本中升级一下 Vert.x 和 Netty 新版本, 多谢了

**Comment by liubao68** [comment]
Blocked by https://github.com/eclipse-vertx/vert.x/issues/4227, need more analyse.

**Comment by david6969xin** [comment]
[#2698](url)

**Comment by david6969xin** [comment]
[#2698 ](https://github.com/apache/servicecomb-java-chassis/pull/2698/files)
