### ISSUE TITLE
客户端接口ServerListFilterExt的参数ServiceCombServer中的MicroserviceInstanceStatus微服务状态是否准确实时？

### ISSUE THREAD

**Issue by SenixCoder** [apache/servicecomb-java-chassis#2678]
通过实现ServerListFilterExt#getFilteredListOfServers来做一个lb的功能，想确认下，入参中的List<ServiceCombServer> servers，实例的status是否准确实时？

想知道客户端获得的服务端实例信息是怎么获取到的？缓存机制是什么？

**Comment by liubao68** [comment]
简单的描述就是微服务通过pull（默认30s一次）或者push（注册中心有实例变更）方式获取实例更新。 详细内容可以看下 [service-center](https://github.com/apache/servicecomb-java-chassis/tree/master/service-registry/registry-service-center)的实现。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
