### ISSUE TITLE
SwaggerProducerOperation类打印的异常包含了用户个人数据，请隐去

### ISSUE THREAD

**Issue by Soonf** [apache/servicecomb-java-chassis#2679]
[SwaggerProducerOperation.java188]unexpected error operation=PRODUCER rest DataSyncService.PathRest.addMotionPathData, message=cause:InvocationTargetException,message:null;cause:JSONException,message:parseLong error, field : avgPace;cause:JSONException,message:syntax error, pos 49, line 1, column 50{"abnormalTrack":0,"avgHeartRate":105,"avgPace":abc,"avgStepRate":18,............

该类中的方法打印了JSON解析异常的具体内容，其中包含用户个人数据，安全不合规，请安排整改谢谢。

**Comment by liubao68** [comment]
能提供下版本信息吗？ 未找到你提供的代码行和日志。也可以看看新版本是否还有你报告的问题。

**Comment by yhs0092** [comment]
他们用的应该是 1.3.6 版本的Java-Chassis

**Comment by liubao68** [comment]
这个文件建议用户自己对解析json代码加上try-catch，不要把信息抛出来即可。 框架层处理会导致后续问题定位变得非常复杂，这个地方已经改了很多次了。

**Comment by liubao68** [comment]
这个问题不处理。 业务抛出类似异常的场景非常少，可由业务自行决定如何处理。
