### ISSUE TITLE
bug： metaspace oom

### ISSUE THREAD

**Issue by five111** [apache/servicecomb-java-chassis#2693]
##【SCB-2372】
## 触发场景
servicecomb 会在调用之初为服务创建配置类，大量调用未注册的服务,  由于服务未注册，每次调用都会去创建类，一定数量之后会导致metaspace oom

**Comment by liubao68** [comment]
可以稳定的重现这个问题吗？是否可以提供简单的重现代码片段和过程。

**Comment by five111** [comment]
可以稳定重现 复现手段
-------------------------------------------------------
jmeter+微服务A
微服务A发送请求给微服务B,且环境没有微服务B,然后用jmeter发送大量请求给微服务B 请求如下 无特殊之处 
```
@GetMapping("/asyncSayHello/{name}")
    public String asyncSayHello(@PathVariable("name") String name) {
        cseAsyncRestTemplate.getForEntity("cse://TOF-provider/provider/tomcat/hello/" + name, String.class);
        return null;
    }
```
通过visualVM观察metaspace如下图
![image](https://user-images.githubusercontent.com/19482564/149447336-a188338e-53fa-4117-b54e-13e31773d707.png)
虽然能看到gc回收 单如果我将metaspace大小设置较小 很容易oom

**Comment by five111** [comment]
建议是在ConfigObjectFactory类做一层缓存 每个微服务无论调用成功失败 都只加载1次

**Comment by liubao68** [comment]
你描述的应该是jmeter调用微服务A吧？ 写成了 “用jmeter发送大量请求给微服务B"。 
另外， 记得历史上有修复过这个问题。 你用的版本是什么？

**Comment by five111** [comment]
2.1.5版本

**Comment by liubao68** [comment]
应该是的。 2.6.0也能重现这个问题吗？

**Comment by liubao68** [comment]
@five111 Any updates?
