### ISSUE TITLE
如何不忽视起服务时端口占用问题

### ISSUE THREAD

**Issue by csy1030** [apache/servicecomb-java-chassis#2711]
CCE使用host模式部署，在伸缩时，旧的实例还没完全下线（端口仍然在占用），新的实例就已经重启，在起服务的时候监听18090失败

报错日志：
`o.a.s.t.rest.vertx.VertxRestTransport    : Can not start VertxRestTransport, the port:18090 may have been occupied.`

请问是否可配置为此处不能忽略此异常，*阻塞启动过程*，直到所需端口释放后，SCB再启动监听。

**Comment by yhs0092** [comment]
## 背景

Java-Chassis 框架(CSE框架)支持用Vert.x做服务器(所谓的**REST over Vert.x模式**); 也支持Tomcat做服务器, 自身作为servlet从Tomcat接请求(所谓的**REST over Servlet模式**).
当用Tomcat做服务器时, 端口由Tomcat监听, Java-Chassis自身不监听端口, 所以Java-Chassis允许在端口被占用的情况下启动.

## 解决方案

如果你希望框架在端口被占用时报错, 可以排除掉 ServiceComb Java-Chassis 的 `transport-rest-servlet` 依赖包, 这样框架就不会支持REST over Servlet模式了, 碰到端口占用会直接报错.

**Comment by csy1030** [comment]
> ## 背景
> Java-Chassis 框架(CSE框架)支持用Vert.x做服务器(所谓的**REST over Vert.x模式**); 也支持Tomcat做服务器, 自身作为servlet从Tomcat接请求(所谓的**REST over Servlet模式**). 当用Tomcat做服务器时, 端口由Tomcat监听, Java-Chassis自身不监听端口, 所以Java-Chassis允许在端口被占用的情况下启动.
> 
> ## 解决方案
> 如果你希望框架在端口被占用时报错, 可以排除掉 ServiceComb Java-Chassis 的 `transport-rest-servlet` 依赖包, 这样框架就不会支持REST over Servlet模式了, 碰到端口占用会直接报错.

可以了！感谢！
