### ISSUE TITLE
如何给予实例标志位的概念

### ISSUE THREAD

**Issue by diwenzheng** [apache/servicecomb-java-chassis#2712]
service-comb 2.5.0. 现在我们有这样的需求,A实例有一个,B实例有两个,A给B转发的时候,需要基于请求体带的内容,根据不同的内容转发到不同的实例上,同样的内容转发的同样的实例上。即需要B实例有标志位的概念. 现在框架支持这样做吗

**Comment by diwenzheng** [comment]
这就是多租户的支持 @liubao68

**Comment by fanjiwang1992** [comment]
可以给实例加个实例级熟悉,路由的时候根据实例属性做个判断

**Comment by diwenzheng** [comment]
> 可以给实例加个实例级属性,路由的时候根据实例属性做个判断

感谢你的回答,您说的这些我有些懵懂,能否举例一下呢,或者有相关实例.

**Comment by fanjiwang1992** [comment]
B的两个实例分别设置不同的实例属性,A服务通过实现org.apache.servicecomb.loadbalance.ServerListFilterExt接口,在路由转发的时候,根据请求体内容结合B的实例标记,路由到对应的B实例上

**Comment by diwenzheng** [comment]
> B的两个实例分别设置不同的实例属性,A服务通过实现org.apache.servicecomb.loadbalance.ServerListFilterExt接口,在路由转发的时候,根据请求体内容结合B的实例标记,路由到对应的B实例上

明确了,实例属性是yaml的哪个配置

**Comment by fanjiwang1992** [comment]
> > B的两个实例分别设置不同的实例属性,A服务通过实现org.apache.servicecomb.loadbalance.ServerListFilterExt接口,在路由转发的时候,根据请求体内容结合B的实例标记,路由到对应的B实例上
> 
> 明确了,实例属性是yaml的哪个配置

参考一下负载均衡的实例属性路由转发https://servicecomb.apache.org/references/java-chassis/zh_CN/references-handlers/loadbalance.html

**Comment by diwenzheng** [comment]
> > > B的两个实例分别设置不同的实例属性,A服务通过实现org.apache.servicecomb.loadbalance.ServerListFilterExt接口,在路由转发的时候,根据请求体内容结合B的实例标记,路由到对应的B实例上
> > 
> > 
> > 明确了,实例属性是yaml的哪个配置
> 
> 参考一下负载均衡的实例属性路由转发https://servicecomb.apache.org/references/java-chassis/zh_CN/references-handlers/loadbalance.html

好的,我那会寻找的时候,没有找到,感谢你的帮忙.
