### ISSUE TITLE
Is the 1.x still in maintaining mode?

### ISSUE THREAD

**Issue by wu-sheng** [apache/servicecomb-java-chassis#2714]
Hi ServiceComb Java Chassis team

I am from the Apache SkyWalking community. When we were doing a plugin review of guava plugin review, we noticed that we only have plugin working for servicecomb 0.x and 1.x. https://github.com/apache/skywalking-java/pull/107#issuecomment-1033506898
Also, the last 1.x release is in Sep last year. So, is this release branch still working for end user? a.k.a. are you still maintaining?

Another question is that, does anyone in your community support or verify whether this plugin works for 2.x release?

**Comment by wu-sheng** [comment]
A little more context, the previous 0.x and 1.x plugins were contributed from ServiceComb's team, we(SkyWalking) just host the codes and released them with our agents. 
The major concern is, is this plugin still being maintained and considered meaningful?

**Comment by liubao68** [comment]
Now servicecomb maintains two branches: 1.x and 2.x， which the lastest version is 1.3.6 and 2.6.0. 
1.x now only provide bug and security fixes, as I know only a small group of users are still use the version, most of servicecomb users use 2.x. 

I think for SkyWalking plugins, provide 2.x is quite enough for servicecomb users.

**Comment by wu-sheng** [comment]
Then I am removing the 0.x plugin now. If your community is going to contribute the plugin, it would be good.

**Comment by liubao68** [comment]
We make a plan for the new plugin and if need some help we'll contact you. Thanks.

**Comment by wu-sheng** [comment]
@liubao68 SkyWalking Java agent has received https://github.com/apache/skywalking-java/pull/127 to fix this.

I hope your team could take a part in reviewing.

**Comment by liubao68** [comment]
sure
