### ISSUE TITLE
是否可以提供对WebClient的支持？

### ISSUE THREAD

**Issue by david6969xin** [apache/servicecomb-java-chassis#2725]

**Comment by liubao68** [comment]
后续应该不提供支持。 早起适配 `RestTemplate`, `AsynRestTempate` 主要是为了降低代码迁移的成本，并不是好的开发习惯， 实际上也给很多开发者带来了很多混淆，将spring boot mvc和servicecomb混用，导致问题。 使用  servicecomb, `CompletableFutre` 的RPC是最推荐的方式。
