### ISSUE TITLE
Sevicecomb耗时时间疑问？

### ISSUE THREAD

**Issue by njhw12** [apache/servicecomb-java-chassis#2738]
vmall产品现网出现了一个奇怪的耗时日志
显示总耗时与明细对不上，帮忙看下还有其他可能的原因吗

2022-03-19 22:46:57.038|WARN |cgs_wap_cp|188|10.235.65.131|d75f81e890fe2a17233ffb4a14e27f5c|slow(1000 ms) invocation, CONSUMER rest vmall-pms.PmsInterface.querySbomIdCode:
  http method: POST
  url        : /RpcPmsInterfaceImpl/querySbomIdCode/
  server     : rest://10.228.161.240:30061
  status code: 408
  total      : 3000.803 ms
    prepare                : 0.0 ms
    handlers request       : 0.282 ms
    client filters request : 0.31 ms
    send request           : 0.78 ms
    get connection         : 0.24 ms
    write to buf           : 0.110 ms
    wait response          : 0.0 ms
    wake consumer          : 0.0 ms
    client filters response: 0.0 ms
    handlers response      : 0.0 ms|org.apache.servicecomb.metrics.core.publish.SlowInvocationLogger

**Comment by liubao68** [comment]
超时情况下  wait response 计算不准确
