### ISSUE TITLE
@RpcReference注解在某些场景会失效

### ISSUE THREAD

**Issue by sunshinexp1** [apache/servicecomb-java-chassis#2740]
针对这个@RpcReference失效的bean进行debug定位，发现初始化，执行到applyBeanPostProcessorsBeforeInitialization时，对应的RpcReferenceProcessor还没有被registerBeanPostProcessors注册上，能否提高一点RpcReferenceProcessor注册的优先级，比如实现PriorityOrdered接口，确保RpcReferenceProcessor更早一点注册，避免时序问题导致部分@RpcReference失效。

**Comment by liubao68** [comment]
能提供下具体的写法代码吗？

**Comment by sunshinexp1** [comment]
我提供一个Demo吧，三个类：
接口类：
`public interface DemoInterface {
    void test();
}
`
接口实现类：
`@Service
public class DemoInterfaceImpl implements DemoInterface {
    @RpcReference(microserviceName = "DemoService", schemaId = "demo-api")
    private IDemoService demoService;
    
    @Override
    public void test() {
        System.out.println("test");
    }
}`

DemoBean类实现FactoryBean，并且通过构造函数注入上述的DemoInterfaceImpl 
`@Service
public class DemoBean implements FactoryBean<String> {
    @Setter
    private DemoInterface demoInterface;
    
    @Autowired
    public DemoBean(DemoInterface demoInterface) {
        this.demoInterface = demoInterface;
    }
    
    @Override
    public String getObject() {
        return "demoBean";
    }

    @Override
    public Class<?> getObjectType() {
        return String.class;
    }

    @Override
    public boolean isSingleton() {
        return true;
    }
}`

最后出现的问题就是接口实现类DemoInterfaceImpl里的@RpcReference注解不生效

**Comment by sunshinexp1** [comment]
> 能提供下具体的写法代码吗？

Demo代码已经提供，可以看看是否有问题。

**Comment by liubao68** [comment]
感觉这个不是一个合理的使用场景。 FactoryBean 的加载时机比一般的普通 Bean 早， 你的例子中 DemoBean  依赖了 DemoInterface , 导致了 DemoInterfaceImpl 被提前加载， 而这个时候， Spring 的 BeanPostProcessor 都还未初始化。 

印象中 Spring 新版本对这种请都会打印警告的。

**Comment by nogeek-cn** [comment]
结论：就是在 `BeanPostProcessor` 处理之前，那么 `BeanPostProcessor`  处理器都要注册到容器中，这个是正确的。

参考：
> 比如：dubbo 的 `ReferenceAnnotationBeanPostProcessor` 处理器是在 `DubboInfraBeanRegisterPostProcessor` 继承了 `BeanDefinitionRegistryPostProcessor` 去注册的。

servicecomb  的 `@RpcReference` 的处理器 `RpcReferenceProcessor` 处理不了这种问题，而 `FactoryBean `  的延迟初始化也有它存在的意义。在一些 Spring 底层工具包 和 一些工程团队开发的底层包中经常使用。

所以 servicecomb 对 `RpcReferenceProcessor` 的注册时机，需要变得更早才行。

**Comment by liubao68** [comment]
这个是非常特殊的场景了， 如果必须使用， 可以试试 ` IDemoService demoService = Invoker.createProxy("DemoService", "demo-api", IDemoService.class)` 能否规避。

**Comment by liubao68** [comment]
这个问题还可以使用 setter injection 来规避， 只会在 constructor injection场景有问题。 

```
@Service
public class DemoBean implements FactoryBean<String> {
    @Autowired
    private DemoInterface demoInterface;
    

    public DemoBean() {

    }
    
    @Override
    public String getObject() {
        return "demoBean";
    }

    @Override
    public Class<?> getObjectType() {
        return String.class;
    }

    @Override
    public boolean isSingleton() {
        return true;
    }
}
```

**Comment by liubao68** [comment]
新版本将支持上述用法，但是仍然推荐使用提到的Lazy方案或者setter injection方案。 在 `FactoryBean`, `BeanPostProcessor`中使用construction injection会破坏Spring的标准流程，Spring会打印警告， 不是推荐的方案。

警告信息:

```
Bean '?' of type [?] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
```
