### ISSUE TITLE
Jackson-databind 2.12.1有高分漏洞

### ISSUE THREAD

**Issue by kinkwok117** [apache/servicecomb-java-chassis#2742]
https://github.com/advisories/GHSA-57j2-w4cx-62h2

**Comment by Shoothzj** [comment]
but jackson doesn't have aviable version yet

**Comment by liubao68** [comment]
Jackson do not have a version to fix this yet. https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.12

Only jackson-databind got a patch version. We will fix this later when jackson released a version. And users can upgrade jackson-databind only before servicecomb release a patch.

**Comment by liubao68** [comment]
I see spring boot upgraded to  2.13.2.20220328,  may be we can try this. 

see  https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.13
  and https://github.com/spring-projects/spring-boot/releases/tag/v2.6.6
