### ISSUE TITLE
关于指标发布格式的问题

### ISSUE THREAD

**Issue by sofkyle** [apache/servicecomb-java-chassis#2746]
ServiceComb的相关资料上有这样一段描述：
“经过权衡，我们最后决定发挥ServiceComb契约的优势，直接返回RegistryMetric实体对象”。

想了解下，这里所谓的ServiceComb契约的优势指的是哪方面呢？
现在一个直接的问题，这种格式Grafana无法直接解析，不利于我们监控面板的数据抽取。能否直接以Prometheus的格式返回呢。

**Comment by liubao68** [comment]
资料的原始链接在哪里？ 不是很了解背景。

**Comment by sofkyle** [comment]
> 资料的原始链接在哪里？ 不是很了解背景。

https://servicecomb.apache.org/assets/slides/20180111/ServiceComb_Metrics_Introduction.pdf 第13页

**Comment by liubao68** [comment]
`/metrics` 接口返回的是 Prometheus， 只是 content-type 是 json 的， 不是 text 的

**Comment by sofkyle** [comment]
搞定了，Prometheus另外持有了一个端口：9696，可以通过配置：servicecomb.metrics.prometheus.address来变更。

**Comment by liubao68** [comment]
参考：https://servicecomb.apache.org/references/java-chassis/zh_CN/general-development/metrics.html
