### ISSUE TITLE
 Why is the timeout set to double

### ISSUE THREAD

**Issue by five111** [apache/servicecomb-java-chassis#2764]
https://github.com/apache/servicecomb-java-chassis/blob/5370277e3d22cac11550bddba3aa01f42b830bbf/core/src/main/java/org/apache/servicecomb/core/provider/consumer/SyncResponseExecutor.java#L103

hello， i have found 2.7.0 set   timeout  to double，I don't think it's reasonable。
Why does my request timeout need to consider whether the downstream interface still calls others?
Under this logic, how long is the link set?
I think the original version is more reasonable

**Comment by five111** [comment]
@liubao68

**Comment by liubao68** [comment]
Do you find any specific problem with this change ? 

This timeout mentioned only controlls the longest time when some bugs or unchecked operations happened that may hang the client. It's not request timeout.

**Comment by five111** [comment]
Maybe I understand now why changed it this way

In historical versions, the request timeout was usually equal to the wait time here. Because of the time consuming to establish a connection etc, we never see a real request timeout, but a call timeout.
When we were locating the timeout problem, we always thought that request timeout should include the time before the service actually makes a request, such as establishing a connection, queuing requests, etc.

So the historical version has not used the request timeout correctly, so you made this change, right?

**Comment by liubao68** [comment]
Yes

**Comment by five111** [comment]
thanks
