### ISSUE TITLE
如何让接口返回的byte[] 不被序列化成String?

### ISSUE THREAD

**Issue by huxiaozheng** [apache/servicecomb-java-chassis#2785]
当前的contentType:  application/json。新增一个接口，期望返回体是byte[]  但最终结果却是String。是否有demo教程，如何针对不同的contentType做拓展？好像实现ProduceProcessor就行了？

**Comment by liubao68** [comment]
是的，但是定制的时候，如果存在a->b-c这样的场景， 估计还挺麻烦的。 
你的场景也是老代码兼容性场景吧？ 否则可以避免这样设计。

**Comment by liubao68** [comment]
java chassis看下是否能够后续提供 content-type:application-binary的支持， 不过得先做下设计和相关的支持场景

**Comment by huxiaozheng** [comment]
新增微服务，新增的接口。目前不考虑a->b->c这种场景。

**Comment by liubao68** [comment]
可以做成上传/下载不？  https://servicecomb.apache.org/references/java-chassis/zh_CN/general-development/upload-download.html

**Comment by huxiaozheng** [comment]
上传下载性能上我觉得应该会有过多的损耗。另外，这种类型application/octet-stream 不支持byte[] 返回吗

**Comment by liubao68** [comment]
java chassis目前没对 application/octet-stream 建模。 需要先建模，支持哪些场景， 然后再实现相关功能。

**Comment by huxiaozheng** [comment]
好的，谢谢
