### ISSUE TITLE
InvocationContext 的 mergeContext 方法没有做好深拷贝保护

### ISSUE THREAD

**Issue by yhs0092** [apache/servicecomb-java-chassis#2801]
当前的`mergeContext`方法是先判断输入的map和自有的map哪个entry更多, 将entry少的map合并到entry多的, 然后将entry多的map作为新的自有`context`属性. 因此如果输入的InvocationContext entry更多的话, 会发现`mergeContext`执行完后输入参数中带出来了被输入的Invocation的内部属性, 并且修改输入Invocation的context会影响被输入的Invocation的context.

**Comment by Shoothzj** [comment]
typo? `输入参数中带出来了被输入的Invocation的内部属性` => `输入参数中带出来了被输出的Invocation的内部属性`

we'd better provider the code piece link.

**Comment by yhs0092** [comment]
> typo? `输入参数中带出来了被输入的Invocation的内部属性` => `输入参数中带出来了被输出的Invocation的内部属性`
> 
> we'd better provider the code piece link.

我可能表述得不好, 这是问题展示demo, 以`org.apache.servicecomb.core.Invocation`做例子:
```java
  public static void main(String[] args) {
    final Invocation i0 = new Invocation();
    i0.addContext("i0-k0","abc");
    i0.addContext("i0-k1","abc");
    final Invocation i1 = new Invocation();
    i1.addContext("i1-k0","def");
    i1.addContext("i1-k1","def");
    i1.addContext("i1-k2","def");
    i1.addContext("i1-k3","def");

    i0.mergeContext(i1);
    // 预期 i1 是输入参数, 其本身并不会受影响, 但实际发现 mergeContext 执行后 i1 自身的 context 也变了
    System.out.println(i0.getContext());
    System.out.println(i1.getContext());
    // 预期merge应该是深拷贝, 防止外部修改 i0 的数据, 但实际上只需修改 i1 就会引起 i0 的 context 变化
    i1.addContext("extra","ext-value");
    System.out.println(i0.getContext());
  }
```

输出会是这个样子的:
```
{i1-k2=def, i0-k1=abc, i1-k3=def, i1-k0=def, i1-k1=def, i0-k0=abc}
{i1-k2=def, i0-k1=abc, i1-k3=def, i1-k0=def, i1-k1=def, i0-k0=abc}
{i1-k2=def, i0-k1=abc, i1-k3=def, i1-k0=def, i1-k1=def, i0-k0=abc, extra=ext-value}
```

**Comment by Shoothzj** [comment]
@yhs0092 Thanks, I got it. I saw there is another method named `addContext`. Is that the `addContext` has same problem too?

**Comment by liubao68** [comment]
I think this is a bug and need fix.

**Comment by liubao68** [comment]
I create a PR to fix this: https://github.com/apache/servicecomb-java-chassis/pull/2802
