### ISSUE TITLE
泛化调用没有办法获取Invocation不方便使用

### ISSUE THREAD

**Issue by 780664893** [apache/servicecomb-java-chassis#2811]
https://servicecomb.gitee.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/featured-topics/features/invoker.html
如文档中介绍，可以通过泛化调用避免POJO方式中的api依赖，但是实际用的时候发现没有手段获取到invocation，无法向其中设置上下文，导致上下文无法向下游传递，建议优化一下，预留一些扩展点

**Comment by liubao68** [comment]
可以在Handler中得到Invocation的引用， 能满足要求吗？ 你期望的使用方式是怎么样的？

**Comment by 780664893** [comment]
handler可以满足，感谢
