### ISSUE TITLE
RPC调用时body中有emoji等unicode时buffer转换会无法识别unicode

### ISSUE THREAD

**Issue by sleep4u** [apache/servicecomb-java-chassis#3198]
body中存在emoji表情（包括其他unicode编码）时
BodyProcessorCreator里的createBodyBuffer方法返回的buffer中，unicode编码会被认为正常字符处理

**Comment by sleep4u** [comment]
![image](https://user-images.githubusercontent.com/109343675/179661452-5141e7d0-17a4-42eb-9745-3cbf5d0bc7bb.png)

追到了这里UTF8JsonGenerator#_outputMultiByteChar
CSE现在这种encode decode流程会丢失unicode

**Comment by lbc97** [comment]
> 补充一个demo
> 
> ```java
>     @Test
>     public void test() throws Exception {
> 
>         TextMessage message = new TextMessage("📣");
>         System.out.println(Arrays.toString("📣".getBytes(StandardCharsets.UTF_8)));
>         System.out.println(Arrays.toString("\uD83D\uDCE3".getBytes(StandardCharsets.UTF_8)));
>         // 转义后每个字符作为String
>         System.out.println(Arrays.toString("\\uD83D\\uDCE3".getBytes(StandardCharsets.UTF_8)));
>         Buffer requestBody;
>         try (BufferOutputStream output = new BufferOutputStream()) {
>             RestObjectMapperFactory.getConsumerWriterMapper().writeValue(output, message);
>             requestBody = output.getBuffer();
>         }
>         System.out.println(Arrays.toString(requestBody.getBytes()));
>     }
> ```
> 
> 结果是 [-16, -97, -109, -93] [-16, -97, -109, -93] [92, 117, 68, 56, 51, 68, 92, 117, 68, 67, 69, 51] [123, 34, 116, 34, 58, 34, **92, 117, 68, 56, 51, 68, 92, 117, 68, 67, 69, 51**, 34, 125]
> 
> 可以看到buffer里的emoji变成了错误的内容，当成了非unicode来处理

你那个TextMessage是啥啊

**Comment by sleep4u** [comment]
> > 补充一个demo
> > ```java
> >     @Test
> >     public void test() throws Exception {
> > 
> >         TextMessage message = new TextMessage("📣");
> >         System.out.println(Arrays.toString("📣".getBytes(StandardCharsets.UTF_8)));
> >         System.out.println(Arrays.toString("\uD83D\uDCE3".getBytes(StandardCharsets.UTF_8)));
> >         // 转义后每个字符作为String
> >         System.out.println(Arrays.toString("\\uD83D\\uDCE3".getBytes(StandardCharsets.UTF_8)));
> >         Buffer requestBody;
> >         try (BufferOutputStream output = new BufferOutputStream()) {
> >             RestObjectMapperFactory.getConsumerWriterMapper().writeValue(output, message);
> >             requestBody = output.getBuffer();
> >         }
> >         System.out.println(Arrays.toString(requestBody.getBytes()));
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 结果是 [-16, -97, -109, -93] [-16, -97, -109, -93] [92, 117, 68, 56, 51, 68, 92, 117, 68, 67, 69, 51] [123, 34, 116, 34, 58, 34, **92, 117, 68, 56, 51, 68, 92, 117, 68, 67, 69, 51**, 34, 125]
> > 可以看到buffer里的emoji变成了错误的内容，当成了非unicode来处理
> 
> 你那个TextMessage是啥啊

就是个model
@Data
@NoArgsConstructor
public class TextMessage {

    private String t;

    public TextMessage(String text) {
        t = text;
    }
}

**Comment by sleep4u** [comment]
这个问题已经明确。
jackson对部分unicode的处理和String对unicode的处理不一样，不能说哪种不对
CSE之间有配套的编解码。
