### ISSUE TITLE
Java-Chassis的限流模块在动态配置场景下存在问题

### ISSUE THREAD

**Issue by yhs0092** [apache/servicecomb-java-chassis#3203]
Java-Chassis的限流模块在动态配置场景下存在问题

## 问题触发场景

假设存在两个Java-Chassis框架开发的微服务 A 和 B, B微服务有一个契约接口, 其`qualifiedName`=`B.schema.oper`. 如果业务在B启动后, 先在配置中心为 B 微服务添加一条对`ANY.schema.oper`接口的限流规则, 再触发 A 调用 B 的 `oper` 接口, 则 B 的 `org.apache.servicecomb.qps.QpsControllerManager#configQpsControllerMap` 属性中缓存的 `A.schema.oper` 的`QpsStrategy`对象实际是 `ANY.schema.oper` 配置项的.
而当用户再从配置中心删除`ANY.schema.oper`接口的限流规则时, 动态配置刷新的回调将触发`org.apache.servicecomb.qps.QpsControllerManager#updateObjMap`方法刷新缓存的各个接口的`QpsStrategy`对象, 由于入参的`configKey`=`ANY.schema.oper`, 无法匹配上`configQpsControllerMap`中缓存的 `A.schema.oper` key, 因此实际上 `A.schema.oper` 指向的 `QpsStrategy` 对象无法刷新, 还是 `ANY.schema.oper` 配置项的, 此时配置值为 `null` , 导致 `org.apache.servicecomb.qps.strategy.FixedWindowStrategy#isLimitNewRequest` 的 `this.getQpsLimit() == null` 校验为 `true`, 抛出`IllegalStateException("should not happen")`异常, 微服务 A 调 B 的 `schema.oper` 接口无法调通.

这个问题的直接原因是 `org.apache.servicecomb.qps.QpsControllerManager#updateObjMap` 方法没有考虑到微服务层级为 `ANY` 的场景, 可能导致 `QpsControllerManager#updateObjMap` 中的缓存漏刷新.

## 问题版本

Java-Chassis 1.3.7

------

麻烦看看这个什么时候能修复呢?

**Comment by liubao68** [comment]
fixed in https://github.com/apache/servicecomb-java-chassis/pull/3349
