### ISSUE TITLE
 [simple type, class java.time.chrono.Chronology] is interface. Must be a concrete type.

### ISSUE THREAD

**Issue by RayTigerZ** [apache/servicecomb-java-chassis#3204]
in springmvc, controller method uses LocalDateTime as parameter
but throw exception:
org.apache.servicecomb.foundation.common.exceptions.ServiceCombException: [simple type, class java.time.chrono.Chronology] is interface. Must be a concrete type.

**Comment by liubao68** [comment]
see https://servicecomb.apache.org/references/java-chassis/zh_CN/featured-topics/features/date-time.html  , what's your version?

**Comment by RayTigerZ** [comment]
I see the content of link，but can not understand
the version is 

the code of controller method is 2.1.5

 public XXXX<?> xxxxxxxxx(
            @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime startTime,
            @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime endTime)
