### ISSUE TITLE
请问为什么`servicecomb.error.printSensitiveErrorMessage`==`true`的时候不使用用`invocation.getTraceIdLogger().error`打印日志呢？这样打出的异常堆栈没有`trace id`,根据`trace id` 查询错误日志的时候会漏掉这个信息呢

### ISSUE THREAD

**Issue by lizeze** [apache/servicecomb-java-chassis#3219]
请问为什么`servicecomb.error.printSensitiveErrorMessage`=`true`的时候不使用用`invocation.getTraceIdLogger().error`打印日志呢？这样打出的异常堆栈没有`trace id`,根据`trace id` 查询错误日志的时候会漏掉这个信息呢

_Originally posted by @lizeze in https://github.com/apache/servicecomb-java-chassis/pull/2644#discussion_r929438785_

**Comment by Shoothzj** [comment]
@lizeze Thanks for reporting this. I think it's a bug, and I create #3220 to fix this
cc @liubao68

**Comment by lizeze** [comment]
速度真快，我刚Fork完准备提交PR呢！
