### ISSUE TITLE
升级2.6.0，发现metaspace oom

### ISSUE THREAD

**Issue by fanjiwang1992** [apache/servicecomb-java-chassis#3225]
Loaded org.apache.servicecomb.foundation.common.utils.LambdaMetafactoryUtils$$Lambda$6847/1927231073 from org.apache.servicecomb.foundation.common.utils.LambdaMetafactoryUtils]
[Loaded org.apache.servicecomb.foundation.common.utils.LambdaMetafactoryUtils$$Lambda$6848/1448812228 from org.apache.servicecomb.foundation.common.utils.LambdaMetafactoryUtils]
[Loaded org.apache.servicecomb.foundation.common.utils.LambdaMetafactoryUtils$$Lambda$6849/1850306981 from org.apache.servicecomb.foundation.common.utils.LambdaMetafactoryUtils]
通过Eclipse Memery Analyzer分析：
![image](https://user-images.githubusercontent.com/84115877/180996292-677f7e43-2d5a-4224-a1e6-9f467e30470e.png)

**Comment by liubao68** [comment]
问题怎么发生的？ 参考 https://servicecomb.apache.org/references/java-chassis/zh_CN/config/read-config.html#java-chassis  ， 是频繁调用了 createObject 来创建配置吗？

**Comment by fanjiwang1992** [comment]
> 问题怎么发生的？ 参考 https://servicecomb.apache.org/references/java-chassis/zh_CN/config/read-config.html#java-chassis ， 是频繁调用了 createObject 来创建配置吗？

[bug： metaspace oom](https://github.com/apache/servicecomb-java-chassis/issues/2693)
跟这个类似，但是这个之前是大量调用未注册的服务出现的，当前是业务跑常稳的时候就会出现

**Comment by liubao68** [comment]
"业务跑常稳的时候就会出现" 这个估计还是得看下原因，感觉PR修改不是针对问题发生场景来的，只是做一个保护。

**Comment by fanjiwang1992** [comment]
好的

**Comment by fanjiwang1992** [comment]
> "业务跑常稳的时候就会出现" 这个估计还是得看下原因，感觉PR修改不是针对问题发生场景来的，只是做一个保护。

好的，目前修改完成 常稳运行之后，对比了一下加载的class数量，之前是3万多，之后一直稳定在30左右
