### ISSUE TITLE
HTTP请求Query参数携带“；”被截断

### ISSUE THREAD

**Issue by sword123458** [apache/servicecomb-java-chassis#3227]
https://stackoverflow.com/questions/3481664/semicolon-as-url-query-separator
The W3C Recommendation from 1999 is obsolete. The current status, according to the 2014 W3C Recommendation, is that semicolon is now illegal as a parameter separator:
规范上说"；"不作为 分割符，请帮忙看看这个地方 CSE是否能将分割符做成可配置；这样既能支持老产品兼容，也能满足新规范要求

**Comment by liubao68** [comment]
查询了你提供的信息，感觉你的理解有误， 你给的内容是 form 规范，相关信息在你给的链接里面有详细澄清。 关于 `query param`的分割符协议规范没有定义标准，而且[推荐使用 `;` 替代 `&`](https://www.w3.org/TR/html401/appendix/notes.html#h-B.2.2) 。 考虑到 `&` 被广泛使用， 所以同时支持 `;` 和 `&` 作为 `query param` 是必要的。

**Comment by liubao68** [comment]
对于你的场景，建议做好转义，而不是改变协议。 不一定考虑所谓的`兼容`。

**Comment by liubao68** [comment]
补充说明：tomcat容器，分隔符只支持`&`； 对于vert.x容器，分隔符支持`&`和`;`。 为了尽可能减少错误， 业务代码在拼接URL的时候，需要做好转义。 HTTP只规范了如何转义，并没有规范分割服务使用什么，这个是容器实现有关的。
