### ISSUE TITLE
BUG zero-config failed to register(401) with handler-publickey-auth on

### ISSUE THREAD

**Issue by trydofor** [apache/servicecomb-java-chassis#3266]
chassis version `2.7.7`

ERROR message `UNAUTHORIZED` in log 
```log
2022-08-05 17:09:58.686 ERROR 67961 --- [ntloop-thread-1] 
lightweight.StoreService  : register instance failed, 
serviceId=/servicecomb-demo/winx-api/0.0.1, 
instanceId=0f695ba4-bfa0-4423-a42f-4da7e9698c20, 
endpoints=[rest://192.168.3.14:8095?urlPrefix=%2Fservcomber], 
message=InvocationException: code=401;
msg={message=UNAUTHORIZED}
```

handler chain config with `auth-*`
```properties
servicecomb.handler.chain.Consumer.default=loadbalance, auth-consumer
servicecomb.handler.chain.Provider.default=auth-provider
```

dependencies
```xml
<dependency>
    <groupId>org.apache.servicecomb</groupId>
    <artifactId>registry-zero-config</artifactId>
</dependency>
<dependency>
    <groupId>org.apache.servicecomb</groupId>
    <artifactId>handler-publickey-auth</artifactId>
</dependency>
```

**Comment by liubao68** [comment]
would you mind create a fix for this ? we now have not enough committers to maintain this zero-config module.

**Comment by trydofor** [comment]
this cause by `ProviderAuthHanlder` that handles register invocation(without Const.AUTH_TOKEN) as `UNAUTHORIZED`

BTW: ProviderAuthHanlder is typo, `Hanlder` → `Handler`
```java
@Override
public void handle(Invocation invocation, AsyncResponse asyncResp) throws Exception {

  String token = invocation.getContext(Const.AUTH_TOKEN);
  if (null != token && authenticationTokenManager.valid(token)) {
    invocation.next(asyncResp);
  } else {
    asyncResp.producerFail(new InvocationException(new HttpStatus(401, "UNAUTHORIZED"), "UNAUTHORIZED"));
  }
}
```

**Comment by trydofor** [comment]
> 

not family with 

> would you mind create a fix for this ? we now have not enough committers to maintain this zero-config module.

newbie to servicecomb, not easy to PR code.
i guess the following way can fix this.

* ProviderAuthHanlder 's white list support invocation. eg SchemaId=scb-discovery
* zero-config register without ProviderAuthHanlder

**Comment by liubao68** [comment]
I think we can not use ProviderAuthHanlder for zero config. Because it needs to register public key to a registry and zero config has no centralized data repository.

**Comment by trydofor** [comment]
> I think we can not use ProviderAuthHanlder for zero config. Because it needs to register public key to a registry and zero config has no centralized data repository.

yes. the `onBootEvent` can not register public key to zero-config.
so in my case, if using zero-config then must implement one of

* multicast public-key and keep in jvm (multicast+caffeine)
* have some centralized/distributed repo (hazelcast/redis)

**Comment by trydofor** [comment]
close this issue.
for simply extends `ProviderAuthHanlder`, and put `scb-discovery` to `skipSchemaId`(is `Set<String>`)

```java
@Override
public void handle(Invocation invocation, AsyncResponse asyncResp) throws Exception {
    if (skipSchemaId.contains(invocation.getSchemaId())) {
        invocation.next(asyncResp);
    }
    else {
        super.handle(invocation, asyncResp);
    }
}
```

reimplement `registry-zero-config` is too heavy, should use `servicecomb-service-center`
