### ISSUE TITLE
[建议] @RpcReference 支持setter注入

### ISSUE THREAD

**Issue by trydofor** [apache/servicecomb-java-chassis#3286]
声明中仅支持`FIELD`，希望增加`METHOD`，最好和`@Autowired`一样，支持更多。
如同时支持 `CONSTRUCTOR`, `METHOD`, `PARAMETER`, `FIELD`

```java
@Target({FIELD, ANNOTATION_TYPE})
public @interface RpcReference {
  String microserviceName();

  String schemaId() default "";
}
```

理由如下：

* 在实践中，推荐以setter注入取代field注入。
* 同时IDEA提示 Private field 'xxx' is never assigned 
* 已有关联issue [[SCB-2297]](https://github.com/apache/servicecomb-java-chassis/pull/2473/)，估计影响不大

```java
@RpcReference(microserviceName = "winx-api", schemaId = "winx-hello")
private HelloContract winxHelloContract;
```

**Comment by liubao68** [comment]
setter injection added : https://github.com/apache/servicecomb-java-chassis/pull/3358/files
