### ISSUE TITLE
是否可以考虑支持@ApiOperation的extensions属性？

### ISSUE THREAD

**Issue by SpireCat** [apache/servicecomb-java-chassis#3295]
实际场景是这样：服务端想在方法层级标注一些接口的特殊描述信息，并且不想使用tags的能力（tags是个String数组，并不能描述值本身的特性），希望能够通过Swagger的extensions能力来支持（不知道为啥SwaggerDefinition支持了但ApiOperation不支持...）。
看了下ApiOperationProcessor的写法，发现并不支持也无法扩展。

**Comment by liubao68** [comment]
你可以描述下输入和预期结果吗？ 

我查看了 ApiOperationProcessor 有如下代码：

```
  @Override
  public void process(SwaggerGenerator swaggerGenerator,
      OperationGenerator operationGenerator, ApiOperation apiOperationAnnotation) {
...
    operation.setOperationId(apiOperationAnnotation.nickname());
    operation.getVendorExtensions().putAll(BaseReaderUtils.parseExtensions(apiOperationAnnotation.extensions()));
...
```

**Comment by SpireCat** [comment]
> 做了一些测试之后，我发现这只是我自己的问题，ServiceComb是支持extensions的，只是在文档中没有生命出来。


> 你可以描述下输入和预期结果吗？
> 
> 我查看了 ApiOperationProcessor 有如下代码：
> 
> ```
>   @Override
>   public void process(SwaggerGenerator swaggerGenerator,
>       OperationGenerator operationGenerator, ApiOperation apiOperationAnnotation) {
> ...
>     operation.setOperationId(apiOperationAnnotation.nickname());
>     operation.getVendorExtensions().putAll(BaseReaderUtils.parseExtensions(apiOperationAnnotation.extensions()));
> ...
> ```
