### ISSUE TITLE
关于jakarta.validation-api升级支持

### ISSUE THREAD

**Issue by CN-Dian** [apache/servicecomb-java-chassis#3320]
详见 https://beanvalidation.org/3.0/
jakarta.validation-api 3.0+ 版本对包路径名称做了改动，该软件的2.0的最后一个版本发布时间是2019年，已经超期；在代码中升级jakarta.validation-api 至3.0+版本后servicecomb无法启动

**Comment by Shoothzj** [comment]
I don't think we will update it quickly. Overdue is not the reason to update. Specially, jakarta 3.0+ will not works with springboot 2.X.

**Comment by trydofor** [comment]
>Spring Boot 3 based applications will require a minimum of JDK 17 at runtime, as well as a minimum of Tomcat 10 / Jetty 11 (for Jakarta EE 9 compatibility). Even more importantly, there might be some changes required in your application source code: e.g. the javax to jakarta namespace change in Jakarta EE 9 wherever you’re touching the Servlet API, JPA, Bean Validation, etc.

https://spring.io/blog/2021/09/02/a-java-17-and-jakarta-ee-9-baseline-for-spring-framework-6
