### ISSUE TITLE
Java-Chassis 默认的同步业务线程池命名不清晰, 能否优化?

### ISSUE THREAD

**Issue by yhs0092** [apache/servicecomb-java-chassis#3350]
目前的名字类似于 `pool-1-thread-1` 这样, 实际是由 `java.util.concurrent.Executors.DefaultThreadFactory` 命名的, 可能与其他框架或者最终使用者创建的线程池搞混.
能否给 Java-Chassis 的同步业务线程池取一个更有辨识度的名字呢?

**Comment by liubao68** [comment]
Good idea

**Comment by liubao68** [comment]
Java chassis thread pool name defaults to `group0-1-thread-1`, seems your issue is not correct

**Comment by yhs0092** [comment]
For Java-Chassis 1.x, the thread name is `pool-0-thread-1` style. It's generated by `java.util.concurrent.Executors.DefaultThreadFactory`.

For Java-Chassis 2.x, it's `group0-1-thread-1` indeed as you said.
