### ISSUE TITLE
是否能支持在一个springboot应用启动两个CSE引擎或注册两个微服务路由

### ISSUE THREAD

**Issue by koshox** [apache/servicecomb-java-chassis#3390]
我们现在有两个微服务 svc-a，svc-b，因为一些性能开销的原因，想把两个微服务做合并。但有大量团队存量代码依赖这两微服务的CSE服务URL。
所以想问有没有可能合并为一个微服务svc-ab，在其中启动两个CSE引擎，注册svc-a，svc-b的路由，对原先这两个微服务的CSE访问，都请求到新的svc-ab服务上。
或者只启动一个CSE引擎，能够注册两个微服务的路由信息到注册中心。亦或有什么更好的方式能实现这种效果。

**Comment by yanghao605** [comment]
是不是可以对同一个微服务同时注册两个微服务名称，或者说在微服务初始化成功之后，再在代码里面手动的去注册另一个微服务名称

**Comment by fanjiwang1992** [comment]
> > 是不是可以对同一个微服务同时注册两个微服务名称，或者说在微服务初始化成功之后，再在代码里面手动的去注册另一个微服务名称
> 
> 嗯这个思路一样的，主要是实现问题，以及不清楚这么做会不会有其他影响。
> 
> 1. producer的处理逻辑是否依赖当前microserviceName
> 2. servicecomb大量使用了静态方法和单例，是否有比较好的方式手动重新注册一个实例

=============================
目前我们有业务这么处理
1、这个应该不依赖
2、两步骤
第一步： 基于启动事件，服务注册过程中，再注册另外一个微服务的静态属性信息（主要是微服务）

**Comment by koshox** [comment]
> > 是不是可以对同一个微服务同时注册两个微服务名称，或者说在微服务初始化成功之后，再在代码里面手动的去注册另一个微服务名称
> 
> 嗯这个思路一样的，主要是实现问题，以及不清楚这么做会不会有其他影响。
> 
> 1. producer的处理逻辑是否依赖当前microserviceName
> 2. servicecomb大量使用了静态方法和单例，是否有比较好的方式手动重新注册一个实例

尝试了一下手动构造microservice注册，可以运行
