### ISSUE TITLE
IsolationDiscoveryFilter配置项不兼容，且不支持微服务级别的开关

### ISSUE THREAD

**Issue by doom15** [apache/servicecomb-java-chassis#3404]
https://github.com/apache/servicecomb-java-chassis/blob/ed12685d645d2d59e4ff638204ee1498354bdd46/handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/filterext/IsolationDiscoveryFilter.java#L75-L80

新的isolation开关配置项为servicecomb.loadbalance.filter.isolation.enabled
与老的开关不兼容：servicecomb.loadbalance.isolation.enabled
且新开关不支持微服务级别（老版本支持的）。

https://github.com/apache/servicecomb-java-chassis/blob/ed12685d645d2d59e4ff638204ee1498354bdd46/handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/filterext/IsolationDiscoveryFilter.java#L99-L110
隔离的配置项风格（servicecomb.loadbalance开头，无filter）也与新开关的配置不统一

@liubao68 @zhaozw 请看下是否要兼容一下配置项，补充微服务级别的开关。

**Comment by liubao68** [comment]
我看了下代码和文档， 修改前的配置项也是一样的：

```
  @Override
  public boolean enabled() {
    return DynamicPropertyFactory.getInstance()
        .getBooleanProperty("servicecomb.loadbalance.filter.isolation.enabled", true).get();
  }
```

文档貌似不对， 你是看的文档，还是确认老代码配置项被修改了？

**Comment by doom15** [comment]
是1.3.7升级到1.3.8版本的[IsolationDiscoveryFilter.java](https://github.com/apache/servicecomb-java-chassis/commit/61e2db26f9a29f5b4e55ff7604f8771ac7f09728#diff-e6ac82e6fe140a22ad99f21f3c6d8baa24da0ffb156f95be6cb3b1bd28072f3a)，在1.3.7版本是用：
```
    if (!Configuration.INSTANCE.isIsolationFilterOpen(invocation.getMicroserviceName())) {
      return parent;
    }
```
对应的代码如下：
```
  public boolean isIsolationFilterOpen(String microservice) {
    String p = getStringProperty("true",
        PROP_ROOT + microservice + "." + FILTER_ISOLATION + FILTER_OPEN,
        PROP_ROOT + FILTER_ISOLATION + FILTER_OPEN);
    return Boolean.parseBoolean(p);
  }
```

1.3.8之后就改为了filter的enable方法了，原来的配置项失效了，且不支持微服务
```
  @Override
  public boolean enabled() {
    return DynamicPropertyFactory.getInstance()
        .getBooleanProperty("servicecomb.loadbalance.filter.isolation.enabled", true).get();
  }
```

**Comment by liubao68** [comment]
看起来是代码改漏了， 把额外的控制逻辑弄丢了。 `servicecomb.loadbalance.filter.isolation.enabled` 这个配置项也是一直存在的， 控制的是Filter是否启用， 这个逻辑是实现逻辑里面判断， 控制对服务是否启用。

**Comment by liubao68** [comment]
fixed in https://github.com/apache/servicecomb-java-chassis/pull/3412
