### ISSUE TITLE
除了给提供者添加打包-parameters参数，2.0.0以上版本的消费者是否有其他方式可以正常RPC调用提供者服务？

### ISSUE THREAD

**Issue by EickMing** [apache/servicecomb-java-chassis#3405]
目前需要开发一个包含多个提供者组件的消费者，由于提供者项目开发较早，使用的servicecomb的版本是商用版的1.0.0.B003.H98,当时这多个项目的打包配置中并无<compilerArgument>-parameters</compilerArgument>配置，目前使用2.6.0版本开发消费者，在rpc调用时会在 swagger-generator-core.jar的 org.apache.servicecomb.swagger.generator.SwaggerGeneratorUtils的collectParameterName的245行抛出IllegalStateException,想问一下有没有简单的配置，可以避免这种需要读取被调用者接口方法实际参数名的情况，像使用以前的1.0.0.B003.H98的版本一样？

**Comment by liubao68** [comment]
能提供下详细异常信息和用法说明吗？ 按照你的描述, 2.6.0 的消费者， 应该是使用了 -parameters配置,  与提供者没有关系。 是消费者依赖了提供者给的 jar 包吗？

**Comment by EickMing** [comment]
> 能提供下详细异常信息和用法说明吗？ 按照你的描述, 2.6.0 的消费者， 应该是使用了 -parameters配置, 与提供者没有关系。 是消费者依赖了提供者给的 jar 包吗？

是的，消费者依赖了提供者的jar包，使用的是rpc方式开发的消费者，在接口上加@RpcReferrence注解，接口实现写在提供者里，消费者引入包含该接口的提供者jar包。如果依赖的提供者jar包是使用-parameters参数打出来的，就没问题。

**Comment by EickMing** [comment]
。

**Comment by liubao68** [comment]
如果这种场景确实会有问题，暂时没想到可行的处理办法

**Comment by EickMing** [comment]
> 如果这种场景确实会有问题，暂时没想到比较好的处理办法，这种情况老版本生成的契约里面的参数可能都是类似 `arg0`, `arg1` 这样的，可读性也是比较差的。 两个要通信的前提，是 类 - 契约 能够对应起来。
> 
> 推荐的方法是新版本调用老版本，直接在新版本创建一个接口，这个接口根据老版本生成的契约来定义，调用哪个接口只需要声明哪个。

推荐的方法可以使用，感谢帮助
