### ISSUE TITLE
Failed to create SSL connection; cause: SslHandshakeTimeoutException

### ISSUE THREAD

**Issue by yanghao605** [apache/servicecomb-java-chassis#3408]
微服务调用过程中因为握手超时导致请求失败，java-chassis是否可以针对该异常做一次重试操作

**Comment by fanjiwang1992** [comment]
可以将SSLHandshakeException以及SslHandshakeTimeoutException加入默认重试白名单
这几种场景 请求都是没有发到提供端

**Comment by liubao68** [comment]
超时异常重试可能导致更加严重的超时。 有个比较好的策略， 可以试试在客户端加一个隔离仓， 参考 https://servicecomb.apache.org/references/java-chassis/zh_CN/references-handlers/governance.html

**Comment by fanjiwang1992** [comment]
https://github.com/apache/servicecomb-java-chassis/pull/3453
