### ISSUE TITLE
ServiceCenterRegistration注册成功时，有可能不推送MicroserviceRegistrationEvent

### ISSUE THREAD

**Issue by provenceee** [apache/servicecomb-java-chassis#3457]
2.8.2版本，在RegisterMicroserviceTask中，如果schema ids不相等时，会尝试重新注册schema，此时服务已经注册成功，但没有推送MicroserviceRegistrationEvent。核心代码如下：
```java
if (serviceCenterConfiguration.isCanOverwriteSwagger()) {
  LOGGER.warn("Service has already registered, but schema ids not equal, try to register it again");
  startTask(new RegisterSchemaTask(0));
  return;
}
```
应该需要在startTask(new RegisterSchemaTask(0));之前执行eventBus.post(new MicroserviceRegistrationEvent(true));把？

**Comment by provenceee** [comment]
> Yes. See #3465.
> 
> But why you use this event ? Maybe you need use MicroserviceInstanceRegisteredEvent

The previous reference is dubbo-servicecomb, which initializes ServiceCenterDiscovery when receiving MicroserviceRegistrationEvent, but now it is temporarily changed to initialize ServiceCenterDiscovery when receiving MicroserviceInstanceRegisteredEvent to avoid the problem

**Comment by liubao68** [comment]
MicroserviceInstanceRegisteredEvent is the correct one.
