### ISSUE TITLE
serviceComb support wildcard path parameters?

### ISSUE THREAD

**Issue by minshiwu** [apache/servicecomb-java-chassis#3531]
I have an API which allows any arbitrary path to be passed in, for example all of these:
/api/tags
/api/tags/foo
/api/tags/foo/bar/baz

are valid paths.  I exepect to define url like:
/api/tags/*
/api/tags/{path}:    

sometimes it’s useful to have a path parameter which takes the full remainder of the HTTP path including slashes;

I found some other[ restful framework](https://connexion.readthedocs.io/en/latest/cookbook.html#wildcard-path-parameters) support. serviceComb whether support or not ?

**Comment by liubao68** [comment]
可以看看 https://github.com/apache/servicecomb-java-chassis/issues/2329
