### ISSUE TITLE
请问 配置中心动态的配置哪些能够让servicecomb动态生效

### ISSUE THREAD

**Issue by five111** [apache/servicecomb-java-chassis#3533]
浅浅看了下代码 是不是只有netfix相关的负载均衡配置能够动态生效？

**Comment by five111** [comment]
@liubao68

**Comment by lbc97** [comment]
除了微服务本身信息不能生效以外 任何自定义配置都可以生效

**Comment by five111** [comment]
> 除了微服务本身信息不能生效以外 任何自定义配置都可以生效

我的意思是自动加载 比如限流策略 我从配置中心下发一个限流策略 根据观察 服务受到消息后应用了这个应用策略
但是比如 注册中心的地址 ，这也是一个servicecomb的配置 我从配置中心下发了 我的服务并没有去新的注册中心注册

**Comment by liubao68** [comment]
java chassis的大部分配置都可以动态生效。 除了少量的基础信息，比如注册中心、配置中心的连接信息等。 对于特定的配置项，可以看下阅读下代码, 使用 https://servicecomb.apache.org/references/java-chassis/zh_CN/config/read-config.html  这里的配置读取方式都可以动态生效。  另外， 很多配置项不动态生效是可以从具体功能推测的，比如更新证书、更新密码、更新网络监听端口、线程池大小等操作。
