### ISSUE TITLE
MicroserviceVersionsMeta getMicroserviceConfig 造成OOM,作为已知问题，请问下一直不解决的原因？

### ISSUE THREAD

**Issue by huxiaozheng** [apache/servicecomb-java-chassis#3570]
最近业务发现调用其他微服务，对方微服务加载契约中某个接口失败的话，就会导致出现OOM,经检查发现 是 MicroserviceVersionsMeta getMicroserviceConfig 已知问题。因为对整个框架设计和原理不太了解，所以请教下 作为已知问题 为什么servicecomb不解决？出于什么考虑？

**Comment by zhfeng** [comment]
If you find the potential issues, I think we are very welcome with the contribution PR. Anyway, this is an open source project and you can fix any time, any where and any thing by yourself.

**Comment by lbc97** [comment]
Is there a link to the known problem you said?

**Comment by liubao68** [comment]
你使用的是哪个版本？能否详细描述下问题？

**Comment by huxiaozheng** [comment]
MicroserviceVersionsMeta.java 源码里有注释： edge scene, if attacker request to forward request to not exist microservice, will cause OOM  这个可以理解为已知问题吧？
