### ISSUE TITLE
配置中有空数据导致微服务启动失败，是否可以捕获该异常

### ISSUE THREAD

**Issue by yanghao605** [apache/servicecomb-java-chassis#3572]
微服务创建ConfigurationSpringInitializer对象时，由于空指针导致对象创建失败，目前来看应该是配置项中有空指针，但是无法判断到底是什么配置项，能不能捕获该异常，并显示导致空指针的配置项

**Comment by liubao68** [comment]
能提供下重现问题的步骤吗？

**Comment by lbc97** [comment]
框架的版本号也提供一下吧

**Comment by yanghao605** [comment]
2.6.0版本，暂时没有复现的方法

**Comment by fanjiwang1992** [comment]
这个问题，非常偶现，遇到的时候，重启服务没法无法解决，只能整个环境卸载重装，怀疑跟容器注入的env有关系，根据错误日志发现，多数据源配置在duplicateCseConfigToServicecomb处理的时候，会有一个方法对入参严格要求是Notnull，否则会拋空指针，目前我们的处理方法是将duplicateCseConfigToServicecomb处理逻辑try catch处理了

**Comment by liubao68** [comment]
能提供下错误堆栈吗？

**Comment by yanghao605** [comment]
![image](https://user-images.githubusercontent.com/73453250/212020560-42ae1e77-7bd6-445d-80da-0ef3fac52284.png)

**Comment by lbc97** [comment]
The microservice fails to be started due to empty data in the configuration. Can the exception be captured?

**Comment by liubao68** [comment]
fixed in 2.8.5
