### ISSUE TITLE
PrometheusPublisher.java: Integrated with Spring Boot

### ISSUE THREAD

**Issue by sofkyle** [apache/servicecomb-java-chassis#3589]
1. Line 97, the type fixed into Type.UNKNOWN, but prometheus supports gauge, counter, timer and so on, which isn't a standardized output in prometheus sampling, and may cause unpredictable errors in some dashboard system(for example, Digital View in Huawei).
2. Not support HTTPS protocol in some data sensitive scenary.
3. Out of mainstream technology. Spring Boot integrates Micrometer and Prometheus Client, which provide more standardized Prometheus sampling output and support more types of metrics.

Hope to refactor this part.

**Comment by liubao68** [comment]
we may support this in 3.0.0.

**Comment by liubao68** [comment]
3.0.0 changed metrics to micrometer.
