### ISSUE TITLE
Load balancer does not have available server for client.

### ISSUE THREAD

**Issue by sofkyle** [apache/servicecomb-java-chassis#3617]
It's just like #1671. 
A specific troubleshooting method is not included.

**Comment by sofkyle** [comment]
Our configuration center has an entry: servicecomb.loadbalance.xxxService.transactionControl.options.tags.status=ready.
The InstancePropertyDiscoveryFilter(Line.64) will check this config.
When the properties "tags.status=ready" write into MicroserviceInstance?

**Comment by liubao68** [comment]
java chassis will not update microservice instance status to ready, please check your application flow design and how to use the status of ready.

**Comment by sofkyle** [comment]
> java chassis will not update microservice instance status to ready, please check your application flow design and how to use the status of ready.

It is a configuration added by our service code. The problem is solved.
