### ISSUE TITLE
多Discovery扩展模块合并存在问题

### ISSUE THREAD

**Issue by yhs0092** [apache/servicecomb-java-chassis#3638]
## 版本
Java-Chassis 2.8.2

## 问题根因分析

`org.apache.servicecomb.registry.api.registry.MicroserviceInstances#mergeMicroserviceInstances` 合并实例列表的逻辑存在问题.

`DiscoveryManager#findServiceInstances(java.lang.String, java.lang.String, java.lang.String, java.lang.String)` 方法遍历 `Discovery` 扩展, 获取各扩展返回的实例列表, 然后调用`MicroserviceInstances#mergeMicroserviceInstances`方法合并实例列表.
```java
// DiscoveryManager#findServiceInstances(java.lang.String, java.lang.String, java.lang.String, java.lang.String) 方法
  public MicroserviceInstances findServiceInstances(String appId, String serviceName,
      String versionRule, String revision) {
    MicroserviceInstances result = new MicroserviceInstances();
    // default values not suitable for aggregate, reset.
    result.setNeedRefresh(false);
    result.setMicroserviceNotExist(true);
    discoveryList
        .forEach(discovery -> {
          MicroserviceInstances instances = discovery.findServiceInstances(appId, serviceName, versionRule, revision);
          result.mergeMicroserviceInstances(instances);  // <------ 这里对遍历查询的各实例列表做合并
        });

    return result;
  }
```

合并后的实例列表, 其 `revision` 是通过字符串比大小, 以最大值为实际生效的`revision`, 对应逻辑在 `MicroserviceInstances#mergeRevision` 方法中:
```java
  private void mergeRevision(String revision) {
    if (revision == null) {
      return;
    }
    if (this.revision == null || this.revision.compareTo(revision) < 0) {
      this.revision = revision;
    }
  }
```
**这里有两个问题,**
- 不同Discovery 扩展的 revision 是各自计数的, 不具有可比性;
- 用string类型的 revisionId 做比较, 比较方法是 compareTo , 结果可能不符合预期, 例如 `"3".compareTo("23")` 的输出结果就是 `1`.

**Comment by liubao68** [comment]
或许更好的实现方式是"服务发现"只从一个注册中心发现。 默认情况，可以考虑如果一个注册中心发现的实例为空，那么就从另外的注册中心发现实例。

**Comment by liubao68** [comment]
see https://github.com/apache/servicecomb-java-chassis/pull/3651
