### ISSUE TITLE
我们A微服务同步RPC调用B微服务，会偶现query参数丢失的现象，

### ISSUE THREAD

**Issue by liusseu** [apache/servicecomb-java-chassis#3654]
排查了B微服务提供的契约一直都是有参数的，也没变过。但是C微服务有个schemaId 和 operationId一样的接口，没有参数。是否有可能在rpc调用时将B微服务和C微服务的契约弄混，导致参数没有组装

**Comment by lbc97** [comment]
B微服务和C服务是两个完全不同的微服务还是说B,C两个微服务微服务名字相同只是版本号不同

**Comment by liusseu** [comment]
> 

两个完全不同的微服务

**Comment by lbc97** [comment]
这个偶现频率是咋样100次能有几次呢。

**Comment by liusseu** [comment]
> 这个偶现频率是咋样100次能有几次呢。

是这样如果一但出现就是必现，一般现网跑一周后会出现，测试环境没有复现

**Comment by liusseu** [comment]
> 这个偶现频率是咋样100次能有几次呢。

还有就是A微服务对B和C都有调用，并且都是RPC调用，并且用了一个interface
![image](https://user-images.githubusercontent.com/12468810/220834008-ce7da19d-02f8-4512-8447-fbaaba44d918.png)
![image](https://user-images.githubusercontent.com/12468810/220834035-3f85db59-8142-4d5f-8e7f-5f7d9a5efdf4.png)

**Comment by lbc97** [comment]
这个A服务发起调用是如何发起的呢 能给看一下A调用的实现吗

**Comment by liusseu** [comment]
> 这个A服务发起调用是如何发起的呢 能给看一下A调用的实现吗

![image](https://user-images.githubusercontent.com/12468810/220834187-0ab89c6a-64a2-4485-8baa-138c2d8d08e7.png)

**Comment by lbc97** [comment]
那个你们用的框架版本号是多少。

**Comment by liusseu** [comment]
> 那个你们用的框架版本号是多少。

1.3.8

**Comment by liusseu** [comment]
问题清楚了，是我们的consumerIntf写了两个getHose，一个有参数一个无参数，在和契约匹配时又只看方法名。是使用不规范导致的
![image](https://user-images.githubusercontent.com/12468810/220851181-ca4c46a1-b678-4a47-a7eb-cfa968b746e9.png)

**Comment by lbc97** [comment]
清楚了就把issue关了吧
