### ISSUE TITLE
CSE调用方式，返回结果类型为ParameterizedTypeReference时， 会导致OOM

### ISSUE THREAD

**Issue by lcyzhyx-520** [apache/servicecomb-java-chassis#3697]
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
	at org.springframework.util.StreamUtils.copy(StreamUtils.java:167)
	at org.springframework.util.FileCopyUtils.copy(FileCopyUtils.java:112)
	at org.springframework.util.FileCopyUtils.copyToByteArray(FileCopyUtils.java:152)
	at org.springframework.web.client.HttpMessageConverterExtractor.getResponseBody(HttpMessageConverterExtractor.java:148)
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:126)
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:996)
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:979)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:739)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:693)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:620)
	at org.apache.servicecomb.provider.springmvc.reference.RestTemplateWrapper.exchange(RestTemplateWrapper.java:184)

![image](https://user-images.githubusercontent.com/63617742/223908518-320981ea-ce9e-41a2-ac3a-62188acfc514.png)

**Comment by lcyzhyx-520** [comment]
> 


例如： 

返回结果为 Result<String>时，会报错OOM 。 不支持泛型。 

![image](https://user-images.githubusercontent.com/63617742/224007272-a7ec5047-ea5f-41f0-a06d-ca8736708081.png)

![image](https://user-images.githubusercontent.com/63617742/224007371-d60630d1-9448-42c6-a232-157090738398.png)

![image](https://user-images.githubusercontent.com/63617742/224007414-05d0f7c5-6d83-40a4-80dc-4570d45775dc.png)

**Comment by lbc97** [comment]
OOM不是内存溢出吗 跟泛型有什么关系呢

**Comment by lcyzhyx-520** [comment]
> OOM不是内存溢出吗 跟泛型有什么关系呢

messageConverter解析带有泛型的返回结果时，有bug，会导致OOM

**Comment by lbc97** [comment]
> > OOM不是内存溢出吗 跟泛型有什么关系呢
> 
> messageConverter解析带有泛型的返回结果时，有bug，会导致OOM

具体是什么bug呢 有分析吗

**Comment by lcyzhyx-520** [comment]
> > > OOM不是内存溢出吗 跟泛型有什么关系呢
> > 
> > 
> > messageConverter解析带有泛型的返回结果时，有bug，会导致OOM
> 
> 具体是什么bug呢 有分析吗

有的， CseHttpMessageConverter 不支持泛型。 但是CseRestTemplate不支持拓展converter

**Comment by lbc97** [comment]
你使用的框架版本是啥 你demo里面的@RpcClient注解是我们框架里面的吗。

**Comment by lbc97** [comment]
还有那个Result<String> 都是你们自定义的还是其他第三方依赖都详细说明一下

**Comment by lcyzhyx-520** [comment]
> 你使用的框架版本是啥 你demo里面的@RpcClient注解是我们框架里面的吗。

这个是我们自己实现的注解。 内部还是通过调用CseRestTemplate来访问的

**Comment by lcyzhyx-520** [comment]
> 还有那个Result 都是你们自定义的还是其他第三方依赖都详细说明一下

我们自定义的返回体。 

@Getter
@Setter
@ToString
@NoArgsConstructor
public class Result<T> {
    private static final long serialVersionUID = 1L;

    private int code;

    private boolean success;

    private T data;

    private String msg;

    private String errorCode;
}

**Comment by liubao68** [comment]
这个应该是非常基础的功能来的。 有没有写一个简单的DEMO验证下？ 还是由于其他因素导致的？比如消息太大之类的。

**Comment by lbc97** [comment]
> 这个应该是非常基础的功能来的。 有没有写一个简单的DEMO验证下？ 还是由于其他因素导致的？比如消息太大之类的。

其实这个我简单复现了一下没发现问题

cosumer 端demo:
public interface ProviderService {
  List<String> list();
}
========
RestSchema(schemaId = "ConsumerController")
@RequestMapping(path = "/")
public class ConsumerController {
  @RpcReference(schemaId = "ProviderController", microserviceName = "provider")
  private ProviderService providerService;

  @GetMapping("/list")
  public List<String> list(){
    return providerService.list();
  }
 }


provider端demo:
@RestSchema(schemaId = "ProviderController")
@RequestMapping(path = "/")
public class ProviderController {
  @GetMapping("/list")
  public List<String> list() {
    List<String> list =  new ArrayList<>();
    list.add("1");
    list.add("2");
    return list;
  }
}

**Comment by lcyzhyx-520** [comment]
> > 这个应该是非常基础的功能来的。 有没有写一个简单的DEMO验证下？ 还是由于其他因素导致的？比如消息太大之类的。
> 
> 其实这个我简单复现了一下没发现问题
> 
> cosumer 端demo: public interface ProviderService { List list(); }
> 
> ======== RestSchema(schemaId = "ConsumerController") @RequestMapping(path = "/") public class ConsumerController { @RpcReference(schemaId = "ProviderController", microserviceName = "provider") private ProviderService providerService;
> 
> @GetMapping("/list") public List list(){ return providerService.list(); } }
> 
> ======== provider端demo: @RestSchema(schemaId = "ProviderController") @RequestMapping(path = "/") public class ProviderController { @GetMapping("/list") public List list() { List list = new ArrayList<>(); list.add("1"); list.add("2"); return list; } }



问题解决了。  

        final ParameterizedTypeReference<?> typeReference = ParameterizedTypeReference.forType(
            method.getGenericReturnType());
        responseEntity = template.exchange(requestUrl, httpMethod, entity, typeReference, params.getPathVariables());

我们之前的调用方式有问题， 代码如上所示。  这里处理ParameterizedTypeReference有问题。 
修改为 responseEntity = template.exchange(requestUrl, httpMethod, entity, method.getReturnType(),
                params.getPathVariables());
就正常了

**Comment by lbc97** [comment]
> > > 这个应该是非常基础的功能来的。 有没有写一个简单的DEMO验证下？ 还是由于其他因素导致的？比如消息太大之类的。
> > 
> > 
> > 其实这个我简单复现了一下没发现问题
> > cosumer 端demo: public interface ProviderService { List list(); }
> > ======== RestSchema(schemaId = "ConsumerController") @RequestMapping(path = "/") public class ConsumerController { @RpcReference(schemaId = "ProviderController", microserviceName = "provider") private ProviderService providerService;
> > @GetMapping("/list") public List list(){ return providerService.list(); } }
> > ======== provider端demo: @RestSchema(schemaId = "ProviderController") @RequestMapping(path = "/") public class ProviderController { @GetMapping("/list") public List list() { List list = new ArrayList<>(); list.add("1"); list.add("2"); return list; } }
> 
> 问题解决了。
> 
> ```
>     final ParameterizedTypeReference<?> typeReference = ParameterizedTypeReference.forType(
>         method.getGenericReturnType());
>     responseEntity = template.exchange(requestUrl, httpMethod, entity, typeReference, params.getPathVariables());
> ```
> 
> 我们之前的调用方式有问题， 代码如上所示。 这里处理ParameterizedTypeReference有问题。 修改为 responseEntity = template.exchange(requestUrl, httpMethod, entity, method.getReturnType(), params.getPathVariables()); 就正常了

这是你们自己写的rpc调用逻辑是吧 跟你们那个自定义注解一起配套使用的是吗

**Comment by lcyzhyx-520** [comment]
> > > > 这个应该是非常基础的功能来的。 有没有写一个简单的DEMO验证下？ 还是由于其他因素导致的？比如消息太大之类的。
> > > 
> > > 
> > > 其实这个我简单复现了一下没发现问题
> > > cosumer 端demo: public interface ProviderService { List list(); }
> > > ======== RestSchema(schemaId = "ConsumerController") @RequestMapping(path = "/") public class ConsumerController { @RpcReference(schemaId = "ProviderController", microserviceName = "provider") private ProviderService providerService;
> > > @GetMapping("/list") public List list(){ return providerService.list(); } }
> > > ======== provider端demo: @RestSchema(schemaId = "ProviderController") @RequestMapping(path = "/") public class ProviderController { @GetMapping("/list") public List list() { List list = new ArrayList<>(); list.add("1"); list.add("2"); return list; } }
> > 
> > 
> > 问题解决了。
> > ```
> >     final ParameterizedTypeReference<?> typeReference = ParameterizedTypeReference.forType(
> >         method.getGenericReturnType());
> >     responseEntity = template.exchange(requestUrl, httpMethod, entity, typeReference, params.getPathVariables());
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我们之前的调用方式有问题， 代码如上所示。 这里处理ParameterizedTypeReference有问题。 修改为 responseEntity = template.exchange(requestUrl, httpMethod, entity, method.getReturnType(), params.getPathVariables()); 就正常了
> 
> 这是你们自己写的rpc调用逻辑是吧 跟你们那个自定义注解一起配套使用的是吗

是的。 自己实现的rpc调用逻辑。 配合 自定义的@RPCClient注解使用。

**Comment by lcyzhyx-520** [comment]
> > > > 这个应该是非常基础的功能来的。 有没有写一个简单的DEMO验证下？ 还是由于其他因素导致的？比如消息太大之类的。
> > > 
> > > 
> > > 其实这个我简单复现了一下没发现问题
> > > cosumer 端demo: public interface ProviderService { List list(); }
> > > ======== RestSchema(schemaId = "ConsumerController") @RequestMapping(path = "/") public class ConsumerController { @RpcReference(schemaId = "ProviderController", microserviceName = "provider") private ProviderService providerService;
> > > @GetMapping("/list") public List list(){ return providerService.list(); } }
> > > ======== provider端demo: @RestSchema(schemaId = "ProviderController") @RequestMapping(path = "/") public class ProviderController { @GetMapping("/list") public List list() { List list = new ArrayList<>(); list.add("1"); list.add("2"); return list; } }
> > 
> > 
> > 问题解决了。
> > ```
> >     final ParameterizedTypeReference<?> typeReference = ParameterizedTypeReference.forType(
> >         method.getGenericReturnType());
> >     responseEntity = template.exchange(requestUrl, httpMethod, entity, typeReference, params.getPathVariables());
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我们之前的调用方式有问题， 代码如上所示。 这里处理ParameterizedTypeReference有问题。 修改为 responseEntity = template.exchange(requestUrl, httpMethod, entity, method.getReturnType(), params.getPathVariables()); 就正常了
> 
> 这是你们自己写的rpc调用逻辑是吧 跟你们那个自定义注解一起配套使用的是吗

是的。 自己实现的rpc调用逻辑。 配合 自定义的@RPCClient注解使用。

**Comment by lbc97** [comment]
现在问题解决了 看看是否可以关闭这个issue
