### ISSUE TITLE
CSE作为消费者走透明RPC的方式调度三方Spring服务,无法调度Spring后缀为/的接口

### ISSUE THREAD

**Issue by JedrekWang** [apache/servicecomb-java-chassis#3698]
### 问题背景: 
cse服务作为消费者走透明RPC(没有服务中心)的方式调度三方Spring服务,无法调度Spring后缀为/的接口
### 问题分析:
通过代码分析, 对于Spring框架来说, @PostMapping(path = "/getDemoList/") 无法接收 /getDemoList的请求
当cse服务走透明RPC方式(参考:https://servicecomb.apache.org/references/java-chassis/zh_CN/build-consumer/3rd-party-service-invoke.html), 提供的RPC schema无论@RequestMapping有没有trailing slash,调到Spring侧都没有带trailing slash
代码走读发现,cse都会走**org.apache.servicecomb.common.rest.definition.path.URLPathBuilder#initPathWriterList** 方法将请求的path进行处理,去除了后缀/,导致这种场景无法调通, 建议兼容这种场景,至少可以提供一个开关可以不去除用户配置的path信息
### 复现版本
Spring版本: spring-boot-starter-parent 2.5.7
cse版本: 2.8.2
### 复现demo
cse侧:
```java
@RestSchema(schemaId = "ProviderController")
@RequestMapping(path = "/hello-service/")
public class App {
  public static void main(String[] args) {
    BeanUtils.init();  // 加载Spring bean定义文件，开始微服务启动流程
  }

  @PostMapping("getList/{name}")
  public List<String> getList(@PathVariable String name) {
    DemoProviderIntf client = BeanUtils.getContext().getBean(DemoProviderIntf.class);
    DemoInfo demoInfo = new DemoInfo();
    demoInfo.setName(name);
    return client.getDemoList(demoInfo);
  }
```
```java
@RequestMapping(path = "/demo")
public interface DemoProviderIntf {
    @RequestMapping(path = "/getDemoList/", method = RequestMethod.POST)
    List<String> getDemoList(@RequestBody DemoInfo req);
}
```
```java
@Configuration("demo")
public class ThirdSvc extends ThirdServiceWithInvokerRegister {

    public ThirdSvc() {
        super("demo");
        addSchema("schema-1", DemoProviderIntf.class);
    }
}
```
```java
public class DemoInfo {

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    private String name;
}
```
Spring侧
```
@RequestMapping("/demo")
@RestController
@SpringBootApplication
public class SpringCustomerApplication {

	public static void main(String[] args) {
		SpringApplication.run(SpringCustomerApplication.class, args);
	}

	@PostMapping(path = "/getDemoList/")
	public List<String> getDemoList(@RequestBody DemoInfo req) {
		return Arrays.asList(req.getName(), "xxx", "yyy");

	}

}
```

**Comment by lbc97** [comment]
https://servicecomb.apache.org/references/java-chassis/zh_CN/registry/local-registry.html 可以看下这篇文档是否对你有所帮助

**Comment by JedrekWang** [comment]
现在问题是org.apache.servicecomb.common.rest.definition.path.URLPathBuilder#initPathWriterList这个类永远会把后缀/去掉和新版本Spring 后缀/严格匹配 不兼容,你发的这个没法解决问题

**Comment by lbc97** [comment]
你这个demo 你发起请求的请求路径是啥样啊

**Comment by JedrekWang** [comment]
> 你这个demo 你发起请求的请求路径是啥样啊

就是走DemoProviderIntf.getDemoList的注解: /demo/getDemoList/

**Comment by lbc97** [comment]
> > 你这个demo 你发起请求的请求路径是啥样啊
> 
> 就是走DemoProviderIntf.getDemoList的注解: /demo/getDemoList/

就直接浏览器输入http://xxx.x.x.x:xxx/demo/getDemoList/这么调用是吧

**Comment by JedrekWang** [comment]
> > > 你这个demo 你发起请求的请求路径是啥样啊
> > 
> > 
> > 就是走DemoProviderIntf.getDemoList的注解: /demo/getDemoList/
> 
> 就直接浏览器输入[http://xxx.x.x.x:xxx/demo/getDemoList/这么调用是吧](http://xxx.x.x.x:xxx/demo/getDemoList/%E8%BF%99%E4%B9%88%E8%B0%83%E7%94%A8%E6%98%AF%E5%90%A7)

浏览器访问cse侧：http://127.0.0.1:9092/hello-service/getList/jedrek

cse侧内部调度spring：/demo/getDemoList/

spring侧接收到请求：/demo/getDemoList
与spring配置的@PostMapping(path = "/getDemoList/")对不上，报错path not found

**Comment by chengyouling** [comment]
虽然/demo/getDemoList/能正常调用，但是官方用法还是推荐/demo/getDemoList；

**Comment by yhs0092** [comment]
CSE忽略请求path末尾的斜杠, 统一处理, 这个是不是以前 Java-Chassis 为了兼容 SpringMVC 框架的路径匹配行为而做的妥协呢? 现在Spring本身已经把这个问题修了, Java-Chassis即使要考虑兼容老版本, 也可以考虑把客户端改过来吧?

Java-Chassis有没有可能改成consumer端发送请求严格按照契约处理, provider端生成的契约严格按照注解值, 而provider端做路径匹配的行为不变呢? 如果做到这种效果, 应该能保障 Java-Chassis 自己的前向兼容性, 同时也能保障Java-Chassis和Spring体系互相调通. ServiceComb社区自身应该也有这种发展诉求的吧, 能否考虑一下.

**Comment by lbc97** [comment]
@liubao68  宝哥看看这个啊

**Comment by liubao68** [comment]
这个问题比较复杂。首先需要考虑 URL 的末尾加上 `/` 还是不加上 `/` ， 这个业界并没有标准的说法（详细信息可以检索网络 ` http path with or without last slash` ）。 通常会有一些常见的做法:

* 加上 `/` 和不加上 `/` 表示不同的 URL。 如果使用 Spring MVC， 最新版本是表示不同的URL。 
* 加上 `/` 和不加上 `/` 表示相同的 URL。 如果使用 Java Chassis，表示相同的URL， 无论是采用 Spring MVC还是JAX RS开发风格。 

在提供REST接口的场景下， 表示相同的 URL 对于使用者是比较简单的，也可以减少歧义。 

本问题需要验证从客户端的视角， 是否在用户指定的原始 URL 中显示加上 `/`。

**Comment by liubao68** [comment]
[3.0.0 做下修改](https://github.com/apache/servicecomb-java-chassis/pull/4002) ， client不自动去掉 / 。 服务端仍然支持两种形式。 2.x.x版本不做修改，维持现状。
