### ISSUE TITLE
java-chassis:2.8.6使用nacos作为配置中心，未覆写本地servicecomb启动配置

### ISSUE THREAD

**Issue by huilaokedejuzi** [apache/servicecomb-java-chassis#3708]
问题描述：
引用config-nacos，使用nacos作为配置中心，已读到指定配置，初始化controller时，可注入nacos的配置，但无法覆写本地的以下同名启动配置：
![image](https://user-images.githubusercontent.com/81682823/225565917-b8c4d905-7f4a-43a0-a653-f7e3e8c508f0.png)

是否2.8.6版本不支持覆写servicecomb启动配置?

补充：使用java chassis 1.0.0 使用com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-config可覆写本地全部同名配置

*****************使用包版本如下：
![image](https://user-images.githubusercontent.com/81682823/225566376-88ce5a6a-a66c-479c-ad68-832baceefe2b.png)

**Comment by lbc97** [comment]
这个微服务本身信息无法在配置中心配置 https://servicecomb.apache.org/references/java-chassis/zh_CN/build-provider/definition/service-definition.html
