### ISSUE TITLE
遗留系统（非CSE）调用基于CSE发布的Rpc接口问题咨询

### ISSUE THREAD

**Issue by minshiwu** [apache/servicecomb-java-chassis#3713]
我有一个微服务A是基于ServiceComb的，且发布了一些rpc接口。现在有一个遗留系统B（非Servicecomb也不想整改成Servicecomb模式）。B现在想调用A发布的rpc接口，请问当前Servicecomb是否支持这种场景？

**Comment by lbc97** [comment]
https://servicecomb.apache.org/references/java-chassis/zh_CN/registry/local-registry.html

**Comment by minshiwu** [comment]
我发现在没有配置highway协议时候。通过`@RcpScheme`发布的rpc接口，底层实现是通过rpc over rest的方式，也就是将rpc接口转成post接口生成swagger契约来注册和调用的。
