### ISSUE TITLE
注册中心实例watch下，未合并短时间内的实例列表查询和更新请求，对注册中心可能存在较大的压力

### ISSUE THREAD

**Issue by smalljunHw** [apache/servicecomb-java-chassis#3724]
ServiceComb 1.3.8
注册中心实例watch模式下，微服务的每一个实例状态出现变化，就会导致CSE重新从注册中心查询实例列表。设被调用方微服务有m个实例，则n个被调用方的微服务同时发生变化，就会触发 m * n次实例查询，对注册中心冲击会较大。若能合并短时间内的查询请求，这样查询次数可以由 m * n 变为m * 1次。
建议实现：watch事件通知后，delay一段时间（如200ms，可通过配置设置），在此期间若有其他查询（来自watch或周期查询）请求，则合并为1次。

**Comment by chengyouling** [comment]
1、以固定窗口200ms内合并查询，即固定的每个请求的200ms内合并查询，这个感觉做不到你的效果？
2、滑动的累加请求呢，即每合并一次查询后以后一次请求时间作为时间计算起点，如果请求间隔时间刚好都在200ms以内，能达到你说的效果，但是取最大延迟n * 200ms，会不会有点高呢？

**Comment by smalljunHw** [comment]
1、为啥不可以呢？可以限制200ms内最多只有1次调用，而不限制，则等于被watch通知的事件数；
2、时延最多有200ms，而不是n*200ms；200ms内的watch事件都会合并为同一个查询请求，而不是会往后排队。
3、为啥不推荐用watch呢？目前我们使用比较多，可以解决及时通知实例变化的问题。不过合并一段时间内的多个watch事件进行，我认为是可以做的优化。尽管会增加一段时延，但可以通过配置项配置，且相对于周期查询任务导致的时延，是可以忽略的。

**Comment by liubao68** [comment]
事件处理合并新版本应该是已经具备的功能。

**Comment by liubao68** [comment]
一个微服务实例只有一个线程访问注册中心，如果这个线程正在查询实例，那么后续事件则被忽略， 参考RefreshableServiceRegistryCache。 这个策略整体应该不会给注册中心带来很大的压力。注册中心的设计规格必须至少支持 M *N 的并发查询要求。

**Comment by liubao68** [comment]
2.8.x使用单线程池处理事件，并且设置了有界队列，丢弃大量的排队事件。 已经能够满足要求。
