### ISSUE TITLE
java 17、spring 6.x配套计划

### ISSUE THREAD

**Issue by songfeiyue** [apache/servicecomb-java-chassis#3751]
请问java17和spring 6.x的配套版本的版本计划

**Comment by lbc97** [comment]
最新的master分支 是java17 目前是有spring boot 3.0的计划。

**Comment by songfeiyue** [comment]
请问适配SpringBoot3.0版本，具体计划是什么，什么时候可提供版本

**Comment by lbc97** [comment]
目前还在开发中 具体版本什么时候能提供还定不下来。

**Comment by SheepPP** [comment]
spring已明确11月后不再更新java8的版本，请尽快发布支持java17和spring 6.x的版本。我看master分支已经升级了部分了。

**Comment by liubao68** [comment]
Working in progress.  Status can be check in https://servicecomb.apache.org/references/java-chassis/zh_CN/featured-topics/upgrading/2_8_0T3_0_0.html

**Comment by shoothzj** [comment]
I think you can try with 3.x now.
