### ISSUE TITLE
如何将线程池中线程在RPC调用其他微服务时的Zipkin跟踪链路统一到主线程跟踪链路中

### ISSUE THREAD

**Issue by EickMing** [apache/servicecomb-java-chassis#3762]
在子线程中RPC调用其他微服务时，在ZipkinTracingHandler的handler方法中会调用ZipKinTracingDelegate.createSpan(Invocation)方法生成一个跟踪链路，在发起RPC调用之前在Invocation设置X-B3-TraceId和X-B3SpanId的值会被这个方法重写，请问可以通过什么配置修改或invocation参数设定来避免该情况，保证子线程RPC调用的traceId和主线程的保持一致

**Comment by lbc97** [comment]
这个 ZipKinTracerHandler是谁写的，能否咨询一下写这个类的人可不可以不要重写框架原生的东西。

**Comment by EickMing** [comment]
> 这个 ZipKinTracerHandler是框架原生的吗，你们框架版本是多少。

是原生的，
<dependency>   
    <groupId>org.apache.servicecomb</groupId>
    <artifactId>handler-tracing-zipkin</artifactId>
  <version>1.0.0-m1<version>
</dependency>

**Comment by lbc97** [comment]
https://github.com/apache/servicecomb-java-chassis/find/1.0.0-m1 你是不是搞错了没找到名字一模一样的 找到三个类似的

**Comment by EickMing** [comment]
https://gitee.com/nanjing0919/person_picture/raw/sit/image/202304271500907.png

**Comment by lbc97** [comment]
在发起RPC调用之前在Invocation设置X-B3-TraceId和X-B3SpanId的值会被这个方法重写。

这个值你们是自己赋值了 还是框架自己赋的值 被createSpan重写了。

**Comment by lbc97** [comment]
X-B3SpanId 框架好像没这个值

**Comment by EickMing** [comment]
> X-B3SpanId 框架好像没这个值

不好意思，是X-B3-SpanId

**Comment by lbc97** [comment]
> > X-B3SpanId 框架好像没这个值
> 
> 不好意思，是X-B3-SpanId

这个值也没有啊

**Comment by EickMing** [comment]
> 在发起RPC调用之前在Invocation设置X-B3-TraceId和X-B3SpanId的值会被这个方法重写。
> 
> 这个值你们是自己赋值了 还是框架自己赋的值 被createSpan重写了。

在子线程里RPC调用前不作任何操作，就会被createSpan重写，现在是尝试在RPC调用前在invocation添加X-B3-TraceId和X-B3-SpanId，但是还是会被重写。

**Comment by EickMing** [comment]
这个是子线程RPC调用前的invocation
![936d08e0fa2d66f12842c479da74736a](https://user-images.githubusercontent.com/20539987/234792820-ba1a046b-a232-4596-97ae-e78429283404.png)
这个createSpan重写后的
![9ad4a0bf9469ca43286471694f2a50b1](https://user-images.githubusercontent.com/20539987/234793025-a363775d-8a41-4138-b4e5-d7436493c6e1.png)

**Comment by EickMing** [comment]
主线程RPC调用前
![d50eb09130d86662a57e2683f38cf060](https://user-images.githubusercontent.com/20539987/234793277-4a677fdf-dc42-46e3-8af8-b735abb1b441.png)
createSpan重写后
![a1f477ccaabfc87abed6e5c3496b2f79](https://user-images.githubusercontent.com/20539987/234793349-a73e8775-a588-4b2f-851c-9589333a5e67.png)

**Comment by lbc97** [comment]
不是我是问X-B3-SpanId 那个值是怎么来的框架并没有找到X-B3-SpanId这个值啊

**Comment by lbc97** [comment]
我看唯一框架有修改traceId的地方就是这里 你断点点在这里看看这里是啥时候被走的吧   https://github.com/apache/servicecomb-java-chassis/blob/1.0.0-m1/common/common-rest/src/main/java/org/apache/servicecomb/common/rest/filter/tracing/TracingFilter.java

**Comment by EickMing** [comment]
> ```
> 我看唯一框架有修改traceId的地方就是这里 你断点点在这里看看这里是啥时候被走的吧   https://github.com/apache/servicecomb-java-chassis/blob/1.0.0-m1/common/common-rest/src/main/java/org/apache/servicecomb/common/rest/filter/tracing/TracingFilter.java
> ```

这个过滤器存在于common-rest的包里，在目前使用的CSE商业版中已经找不到了。
在开始RPC调用时，会经过ZipkinTracingHandler，ZipkinTracingHandler里的handler方法调用ZipkinTracingDelegate的createSpan(invocation)方法，这个方法的实现是ZipkinConsumerDelegate的createSapn()；
下图是调用的链路：
![image](https://user-images.githubusercontent.com/20539987/234803641-c9877c47-d012-43cc-bf4c-f4a4ad1b3693.png)
在这里调用了brave包中的HttpClientHandler的方法，一下三张图是方法调用路径
![image](https://user-images.githubusercontent.com/20539987/234803671-64079764-44f9-4373-ad11-0177954446ea.png)
![image](https://user-images.githubusercontent.com/20539987/234803692-1565f5e0-b3ce-4515-a900-6ff99b059e35.png)
![image](https://user-images.githubusercontent.com/20539987/234803725-6693cd6d-c03c-4f81-b79e-69fd07b332e7.png)
第三张图中的方法的nextSpan生成了Span对象，以下2张图是进入方法内部的逻辑
![image](https://user-images.githubusercontent.com/20539987/234804686-7ee71942-37dc-4a09-80fc-5fd918a13f35.png)
![image](https://user-images.githubusercontent.com/20539987/234804713-aa480ccf-ca11-4c8f-b3a4-ced545ae94a3.png)
生成Span以后，回到HttpClientHandler的handlerSend方法，
![image](https://user-images.githubusercontent.com/20539987/234805490-49e0a411-3ea6-460b-a338-64e44866f2c6.png)
![image](https://user-images.githubusercontent.com/20539987/234805784-56ccb1bb-7cf7-49ee-915b-5a5cc8119727.png)
在B3Propagation的inject方法中将X-B3-SpanId存入invocation

**Comment by EickMing** [comment]
> 你可以看一下那个B3Propagation 具体是哪个地方的 并不是我们框架自带的 那应该就是zikpin把我们原生的traceId也给改了

它生成新的traceId的原因是下图的方法中，子线程无法从CurrentTraceContext获取父级TraceContext
![image](https://user-images.githubusercontent.com/20539987/234808500-0bca4507-7ac1-490a-b91d-b82eaeea1ffc.png)
而这个对象的生成是ZipkinTracingHandler里ZipkinConsumerDelegate的属性，目前不知道该怎么改造ZipkinConsumerDelegate，使得子线程里的ZipkinConsumerDelegate里的TraceContext能够像主线程那样存在

**Comment by EickMing** [comment]
在发起RPC调用前，都会经过多个handler，在主线程里调用和在子线程里调用，生成的ZipkinTracingHandler对象的属性值不一样，导致调用Zipkin框架的方法时，子线程的调用当成了一次新的调用链

**Comment by EickMing** [comment]
> 你可以看一下那个B3Propagation 具体是哪个地方的 并不是我们框架自带的 那应该就是zikpin把我们原生的traceId也给改了

解决了，在子线程里获取HttpTracing对象，new TraceContext对象后设入CurrentTraceContext中
![image](https://user-images.githubusercontent.com/20539987/235051655-c3dc3477-0455-45b3-ab3c-672cd56ffd88.png)
