### ISSUE TITLE
Java-Chassis 的 HTTP/2 keepalive 配置没有生效

### ISSUE THREAD

**Issue by yhs0092** [apache/servicecomb-java-chassis#3774]
## 版本

Java-Chassis 2.8.2

## 问题描述

Vert.x 4.x 版本的客户端配置对象区分了 HTTP/1.1 和 HTTP/2 连接池的 keepalive 超时时间配置:

![image](https://user-images.githubusercontent.com/22049770/236617963-7c5bec7a-a5da-49d9-b4ab-271eb48ac64e.png)

分析代码发现Java-Chassis 2.x 版本设置 Vert.x 客户端配置的地方是  `org.apache.servicecomb.foundation.vertx.client.http.HttpClientOptionsSPI#createHttpClientOptions`, 这里只调用了`HttpClientOptions`的`setKeepAliveTimeout`方法, 而 HTTP/2 连接池使用的 keepalive 超时时间一直是默认值.

**Comment by liubao68** [comment]
Fixed in https://github.com/apache/servicecomb-java-chassis/pull/3773
