### ISSUE TITLE
请问进行微服务接口调用时是用的是UDP还是TCP？用的什么端口？

### ISSUE THREAD

**Issue by AndyChen1992** [apache/servicecomb-java-chassis#3786]

**Comment by liubao68** [comment]
可以参考下 https://servicecomb.apache.org/references/java-chassis/zh_CN/transports/rest-over-servlet.html

**Comment by AndyChen1992** [comment]
好像没看到关于rpc调用时用的udp还是tcp的说明，现在在排查端口，对于出现的一些udp端口怀疑是rpc调用的，但找不到地方能确认
