### ISSUE TITLE
限流能力的疑问点

### ISSUE THREAD

**Issue by fanjiwang1992** [apache/servicecomb-java-chassis#3788]
背景：
当前SDK提供了多层级的限流能力配置，支持microservice/schema/operation三个级别的配置，后者的优先级高于前者

问题描述：
假设我配置了两条限流策略：
策略一： 针对schema-A配置了限流值50
策略二： 针对schema-A下的某个operation-A设置了限流值60

针对某个operation-A并发55，由于operation-A属于schema-A，理论上策略一应该生效，发生限流现象，
但是由于当前的优先级关系，满足策略二，小于限流值60，不生效

所有想了解一下，当前的实现背景是啥，是否是一个缺陷

**Comment by liubao68** [comment]
预期结果是不是更加灵活点？
