### ISSUE TITLE
开启TLS通信后，是如何进行证书校验的？

### ISSUE THREAD

**Issue by yanghao605** [apache/servicecomb-java-chassis#3798]
我只在foundation-ssl模块下的TrustManagerExt中看到有对证书校验的部分，但是我实际debug看了一下服务的调用过程，并没有走到那个逻辑里面

**Comment by liubao68** [comment]
是使用 vert.x transport 吗？ SSL验证是在vert.x 做的，只是设置了证书。

**Comment by yanghao605** [comment]
是说TrustManagerExt只是设置证书吗？

**Comment by yanghao605** [comment]
我理解REST通信底层也是用的vertx进行通信的吧，就是说所有的证书验证都是vertx做了的？
