### ISSUE TITLE
从配置中心无法下发配置到environment属性不为空的服务

### ISSUE THREAD

**Issue by yanghao605** [apache/servicecomb-java-chassis#3828]
https://github.com/apache/servicecomb-java-chassis/blob/d4824c74a3bab89d631a09bd28ec61ae9f812c81/clients/config-center-client/src/main/java/org/apache/servicecomb/config/center/client/ConfigCenterClient.java#L93

**Comment by yanghao605** [comment]
我是在2.6.0版本上发现的这个问题，master上应该也是有的。
当一个微服务的environment属性不为空后，它在配置中心定义的key为environment:serviceName@appID#version，
但是SDK中生成的key没有包含environment从而导致，虽然SDK从配置中心读取到了environment不为空的配置，但是却无法进行解析。2.1.5版本是可以获取到相应的配置的

**Comment by yanghao605** [comment]
简单给一个微服务的定义：
```APPLICATION_ID: xyxyh11
service_description:
  name: ok_dasfjdo
  version: 515.863.4.167
  environment: production
  properties:
    allowCrossApp: true

**Comment by lbc97** [comment]
这个微服务定义的配置很老了啊，新的配置有这个问题吗

**Comment by lbc97** [comment]
> 我是在2.6.0版本上发现的这个问题，master上应该也是有的。 当一个微服务的environment属性不为空后，它在配置中心定义的key为environment:serviceName@appID#version， 但是SDK中生成的key没有包含environment从而导致，虽然SDK从配置中心读取到了environment不为空的配置，但是却无法进行解析。2.1.5版本是可以获取到相应的配置的

这句话要咋理解 没很看懂 啥叫SDK生成的key key 不是在配置中心页面用户自定义下发的吗
