### ISSUE TITLE
微服务启动后，接口请求报status = starting

### ISSUE THREAD

**Issue by huxiaozheng** [apache/servicecomb-java-chassis#3847]
最近现网遇到几个问题，想请教下
1、微服务启动后，接口请求一直报503 status = starting. 请问什么场景下会出现这种情况？（cse日志已经没了，所以想咨询下大概可能的原因）
2、微服务能一直处于这样的状态吗？没有什么保护机制去重启？
3、我们健康检查显示微服务是正常的。健康检查也是通过请求接口来判断微服务状态，请问存在这种可能吗？

**Comment by yanghao605** [comment]
这种情况一般来说是微服务没有成功注册，自身状态没有转换为UP，导致在发起请求的时候因为自身状态不为UP请求失败

**Comment by huxiaozheng** [comment]
这个我了解 ，我主要想了解是问题2和3，请问还知道可能是什么原因？

**Comment by liubao68** [comment]
具体要看你们的健康检查的实现机制。 或许合适的健康检查机制就能解答你的疑问。
