### ISSUE TITLE
Java-Chassis是否可以使用SpringBoot中提供的SseEmitter能力？

### ISSUE THREAD

**Issue by yanghao605** [apache/servicecomb-java-chassis#3851]
服务端可以通过SpringBoot的SseEmitter推送消息到客户端，Servicecomb-Java-Chassis有支持这个能力吗？我这边看好像没办法使用

**Comment by liubao68** [comment]
java chassis目前主要还是提供RPC， SseEmitter 不支持。 不过你依然可以考虑 Spring Boot Servlet模式集成 java chassis， 对外暴露Spring MVC给前端使用。内部访问其他服务走java chassis的RPC。

**Comment by yanghao605** [comment]
那是否可以基于ProduceProcessor做扩展实现这个能力

**Comment by liubao68** [comment]
3.2.0版本开始支持服务器事件推送(SSE）, 参考： https://huaweicse.github.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/featured-topics/secrets/sse.html
