### ISSUE TITLE
升级Java-Chassis 2.x版本后, ServerRestArgsFilter校验必填参数报错所返回的信息中没有具体的接口和参数名, 不利于问题定位

### ISSUE THREAD

**Issue by yhs0092** [apache/servicecomb-java-chassis#3865]
## 问题原因

Java-Chassis 在 2.x 分支修改了`RestCodec`的逻辑, 1.x分支统一捕获所有Exception类型异常, 并在转换错误响应时添加接口、参数、参数处理器信息. 而2.x分支区分捕获`InvocationException`异常和其他的`Exception`异常, 其中`InvocationException`直接抛出, 只有其他的`Exception`异常才会附加错误接口信息. 而参数必填项检查刚好是在`ParamProcessor`内部做的, 报错抛出的是`InvocationException`, 因此绕过了附加接口信息的逻辑.

差异点在`org.apache.servicecomb.common.rest.codec.RestCodec#restToArgs`方法中.

**Comment by chengyouling** [comment]
我们检查下，然后充填下必要的信息。

**Comment by yhs0092** [comment]
> 我们检查下，然后充填下必要的信息。

好的, 感谢~
