### ISSUE TITLE
2.6.0 -> 2.8.0之后HttpClientFilter中的beforeSendRequest方法改为了异步，这个的目的是什么？

### ISSUE THREAD

**Issue by yanghao605** [apache/servicecomb-java-chassis#3880]
https://github.com/apache/servicecomb-java-chassis/blob/9ba323621cd066d6d02444bbd319ee27792e3d1a/common/common-rest/src/main/java/org/apache/servicecomb/common/rest/filter/HttpClientFilter.java#L37

2.8.0中的接口改成了异步方法，并提供了一个异步方法的执行器，这么修改是为了什么？
@liubao68

**Comment by liubao68** [comment]
vert.x新版本修改了一些执行逻辑，这个逻辑必须在event-loop执行，因此不能在使用同步。显示的将方法声明为异步。 

相关问题参考： https://github.com/apache/servicecomb-java-chassis/issues/3164

**Comment by yanghao605** [comment]
这么修改并没有解决之前的ThreadLocal无法获取的问题，我按照[#3164](https://github.com/apache/servicecomb-java-chassis/issues/3164)的测试方法进行验证，发现在HttpCLientFilter中仍然无法获取ThreadLocal中的数据
@liubao68

**Comment by liubao68** [comment]
这个修改不能解决ThreadLocal的问题，而是显示的标注不能使用ThreadLocal.
