### ISSUE TITLE
Servicecomb-Java-Chassis中是否能够兼容fastjson注解

### ISSUE THREAD

**Issue by yanghao605** [apache/servicecomb-java-chassis#3887]
当前看Servicecomb-Java-Chassis中使用的是开源软件Jackson，是否能够进行扩展兼容fastjson的相关注解

**Comment by liubao68** [comment]
目前依赖jackson，不能支持fastjson。 fastjson在java chassis依赖的技术选型体系里面（包括swagger等）不是很兼容，没有能和这些生态保持很好的融合，无法采用fastjson。
