### ISSUE TITLE
超时时间配置问题

### ISSUE THREAD

**Issue by hypggg** [apache/servicecomb-java-chassis#3897]
servicecomb.request.timeout 和 servicecomb.isolation.Provider.timeoutInMilliseconds 配置超过30 秒，就不生效，是不是有
最大30秒的限制？有没有办法放开？

**Comment by liubao68** [comment]
see the pined : https://github.com/apache/servicecomb-java-chassis/issues/2603

**Comment by hypggg** [comment]
单配置servicecomb.request.timeout 这个不行，会受 servicecomb.rest.client.connection.idleTimeoutInSeconds 默认30秒超时的影响  ,这种解决方案会对性能造成些影响 ，只适合临时解决问题。
