### ISSUE TITLE
servicecomb-java-chassis 依赖的三方jar存在CVE安全漏洞，有升级修复计划吗

### ISSUE THREAD

**Issue by zijian-zhao** [apache/servicecomb-java-chassis#3899]
您好，我司采用了servicecomb作为微服务框架，但向客户交付时做安全扫描无法通过，下图中红框中为存在cve安全漏洞的依赖包，经排查maven依赖树，发现都是servicecomb引入的三方依赖，由于涉及依赖较多，且vertx-web核心组件也需要升级，请问官方是否有计划？
![image](https://github.com/apache/servicecomb-java-chassis/assets/56858130/25a523ff-9dd5-43f6-8cf2-227d33f2481b)

**Comment by yanghao605** [comment]
你使用的是哪个版本的？
可以升级一下Servicecomb-Java-Chassis版本或者是自行升级开源三方件

**Comment by zijian-zhao** [comment]
我尝试升级到最新2.7.0了，但上述问题仍存在

**Comment by liubao68** [comment]
java chassis最新版本是2.8.9， 一直在持续升级三方件， 可以试试升级这个版本。 每个版本的三方件都可以在 https://github.com/apache/servicecomb-java-chassis/blob/master/dependencies/default/pom.xml 查询， 另外， 你可以自行升级部分三方件。 对于无法升级的三方件依赖（必须java chassis升级）也可以提issue， 写清楚具体三方件版本， 和使用的java chassis版本。
