### ISSUE TITLE
ServiceComb2.8.7版本，导致新老版本并存的时候，请求一直不发往新版本节点。

### ISSUE THREAD

**Issue by qubo11** [apache/servicecomb-java-chassis#3914]
升级ServiceComb 2.7.6到ServiceComb 2.8.9版本，滚动升级的时候，发现所有新节点的内部接口完全无流量，外部接口都是正常运行。在家里环境复现，当服务端升级过程中，出现2.7.6和2.8.9并行的时候，客户端只能调用服务端2.7.6老节点。经定位，2.8.7版本出现该问题。

**Comment by liubao68** [comment]
这个问题由https://github.com/apache/servicecomb-java-chassis/pull/3770 修改导致, 这个修改的目的是保持更老版本的兼容（中间版本修改错误）。 


规避措施：
1. 禁用zoneaware负载均衡： servicecomb.loadbalance.filter.zoneaware.enabled: false
或者2. 显示的配置数据中心信息：
   servicecomb:
  datacenter:
    name: mydatacenter
    region: my-Region
    availableZone: my-Zone

可以在老版本先增加配置信息，后面再新版本继承后再升级。
