### ISSUE TITLE
CseRestTemplate不能使用ClientHttpRequestInterceptor，存在强转异常

### ISSUE THREAD

**Issue by study-renjie** [apache/servicecomb-java-chassis#3931]
在使用CSERestTemplate进行请求，并且通过JAVASPI使用拦截器ClientHttpRequestInterceptor对请求进行拦截时，存在强转异常，CSE不兼容Spring的原生拦截功能。

报错如下：
`Failed to execute http request. Exception: {}
java.lang.ClassCastException: org.springframework.http.client.InterceptingClientHttpRequest cannot be cast to org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest
	at org.springframework.web.client.CseHttpMessageConverter.write(CseHttpMessageConverter.java:77) ~[provider-springmvc-1.3.0.B012.jar:5.3.27]`

问题代码
org.springframework:spring-web:5.3.27
778-782行
```
ClientHttpRequest request = createRequest(url, method);
if (requestCallback != null) {
requestCallback.doWithRequest(request);
}
response = request.execute();
```

在CSERestTemplate重写了doWithRequest，里面存在强转逻辑

```public void doWithRequest(ClientHttpRequest request) throws IOException {
    orgCallback.doWithRequest(request);

    if (!CseHttpEntity.class.isInstance(requestBody)) {
      return;
    }

    CseClientHttpRequest req = (CseClientHttpRequest) request;
    CseHttpEntity<?> entity = (CseHttpEntity<?>) requestBody;
    req.setContext(entity.getContext());
  }
```

**Comment by mainsunshine01** [comment]
898

**Comment by mainsunshine01** [comment]
> 898

90

**Comment by mainsunshine01** [comment]
> > 898
> 
> 90

898uygshafsqgvahbjnkmagshabjn是为更好的给我回车都不是·

**Comment by liubao68** [comment]
java chassis提供了RestTemplate调用微服务，但是实现并不是基于SpringMVC的，不能使用ClientHttpRequestInterceptor。 对于请求的拦截和处理，需要使用 Handler 或者 HttpClientFilter。

**Comment by liubao68** [comment]
see https://github.com/apache/servicecomb-java-chassis/issues/3931
