### ISSUE TITLE
ServiceComb-java-chassis中的调用链中的path为什么要使用operationID？

### ISSUE THREAD

**Issue by yanghao605** [apache/servicecomb-java-chassis#3966]
java-chassis提供了handler-tracing-zipkin，以供业务使用进行调用链追踪。
但是在获取path的方法上与原生brave的存在如下区别：
java-chassis
![image](https://github.com/apache/servicecomb-java-chassis/assets/73453250/76d64a94-a464-4972-9a2a-258a526ccb5d)
brave中则是直接返回的uri
遇到一个问题就是：
从其它架构过来的请求到CSE的逻辑中会输出operationID，但是另外的则输出uri，两者不一致
为什么要使用operationID，是否可以换成uri

**Comment by liubao68** [comment]
java chassis是基于 schema id + operation id标识唯一接口的， 是RPC的表达。 尽管 URI + Method也能表达唯一性，但是前面的更容易理解和进行代码查找。 其他框架（一般指sprnig mvc）是RESTful的，设计理念不太一样。

**Comment by liubao68** [comment]
如果业务需要，可以加个配置项控制。 你方便提个PR实现这个功能吗？

**Comment by yanghao605** [comment]
好的

**Comment by yanghao605** [comment]
配置项这么定义可以吗? servicecomb.trace.workWithThirdParty @liubao68
