### ISSUE TITLE
消费端是否可以无契约加载调用服务端接口？

### ISSUE THREAD

**Issue by yanghao605** [apache/servicecomb-java-chassis#3981]
当前SDK的逻辑是：消费端调用服务端时，首先需要加载服务端的契约，然后再基于契约进行相关的微服务调用
这里遇到一个问题就是：当一个服务作为网关使用或者需要调用大量的服务端时，就可能会导致服务加载了过多的服务契约，从而导致服务中占用的内存较大。
是否可以将基于契约的调用逻辑改为可选的？

**Comment by liubao68** [comment]
目前不可以。这个问题比较复杂，在3.0.0会考虑相关的优化，还没有比较好的方案。

**Comment by liubao68** [comment]
目前3.0.0的想法有几个：1. 把所有契约合并为一个，减少查询次数。 2. 可以将契约放到本地，减少注册中心查询。 另外你说的内存问题， 这个是不可避免的，在java chassis设计里面，内存和契约大小个数是成正比的。 如果不想保留这个特性， 只能考虑选择其他不依赖于契约的网关， 比如spring cloud gateway等。
