### ISSUE TITLE
当前框架能否支持流式查询、流失响应？

### ISSUE THREAD

**Issue by SpireCat** [apache/servicecomb-java-chassis#3994]
请问现在servicecomb具备流式响应的能力吗？项目上A服务需要调用B服务查询大批量数据，希望基于流式查询提升效率。

**Comment by liubao68** [comment]
server event push不太适合RPC框架建模，是HTTP协议的特性。 你可以考虑使用独立的微服务专门处理这种情况（即通过架构韧性解决一些特殊的问题），也是一个非常好的架构选择。

**Comment by liubao68** [comment]
3.2.0版本开始支持服务器事件推送(SSE）, 参考： https://huaweicse.github.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/featured-topics/secrets/sse.html
