### ISSUE TITLE
请问这里抛出的错误如何定位：o.a.s.c.h.impl.ProducerOperationHandler  : 50 unexpected error operation=PRODUCER rest cbsadapter.cbsAdapterHessianService.queryPackageUsage, message=cause:InvocationTargetException,message:null;cause:NumberFormatException,message:null

### ISSUE THREAD

**Issue by edgar1170** [apache/servicecomb-java-chassis#4136]
![image](https://github.com/apache/servicecomb-java-chassis/assets/117433297/da7603fa-49ab-4661-bb46-1691a2ea95a5)
![image](https://github.com/apache/servicecomb-java-chassis/assets/117433297/5a4c2726-bf2d-46e8-9261-4d496db625cc)
问题一：请问这里的错误如何定位，这是服务端的业务代码的错误吗，还是说在返回消费者的过程中发生的错误？
问题二：是否可以通过对整个服务端的方法增加try catch来解决？

**Comment by edgar1170** [comment]
从日志上看不到具体报错的代码位置，偶现，本地无法模拟

**Comment by liubao68** [comment]
可以看下 ProducerOperationHandler 的 132 行等代码， 你的截图 50 应该不是行号， 也可以通过你们的 logger 配置确认下。

**Comment by edgar1170** [comment]
> 可以看下 ProducerOperationHandler 的 132 行等代码， 你的截图 50 应该不是行号， 也可以通过你们的 logger 配置确认下。

好的，根据arthas定位132行的代码找到了，非常感谢
