### ISSUE TITLE
配置文件里配了注册中心的地址为servicecenter所部属的k8s service的地址，但是日志报错连的还是127.0.0.1

### ISSUE THREAD

**Issue by maglna1** [apache/servicecomb-java-chassis#4183]
![image](https://github.com/apache/servicecomb-java-chassis/assets/54428342/4dfc4242-f504-4174-b2fd-f3cd631f1956)
![image](https://github.com/apache/servicecomb-java-chassis/assets/54428342/3712bbaf-46be-40ef-b830-d01c5d4a2e6b)

**Comment by liubao68** [comment]
Maybe you need to check java chassis 2 documents.
