### ISSUE TITLE
线程调度何时入队问题

### ISSUE THREAD

**Issue by timwind** [apache/servicecomb-java-chassis#4195]
默认线程池GroupExecutor中描述：
2.if all core threads are busy, then create new thread
3.if thread count reach the max limitation, then queue the request.

但在LinkedBlockingQueueEx类offer函数中，
// no need to create more thread, just queue the task
    if (owner.getNotFinished() <= owner.getPoolSize()) {
      return super.offer(runnable);
    }

如果所有的core线程都是未完成，恰好两者相等时，也入队，而不是新创建线程吗？
按照GroupExecutor的描述，应该是达到max时，才入队。

所以，这里是不是应当修改为：owner.getNotFinished() < owner.getPoolSize()？

**Comment by timwind** [comment]
是不是因为这里的getNotFinshed已经包含本次任务了

**Comment by liubao68** [comment]
看起来有点道理。 你是检视代码发现的问题，还是测试发现了什么具体问题吗？有什么功能影响？

**Comment by timwind** [comment]
> 看起来有点道理。 你是检视代码发现的问题，还是测试发现了什么具体问题吗？有什么功能影响？

生产遇到了性能问题，像是某个队列卡住了。 但是确信没有达到最大线程数。看了源码，本怀疑是入队有问题导致。
后来打开metric，看到的确没有线程数的队列积压，应该不是这里的问题。
threadPool:
  coreSize maxThreads poolSize currentBusy rejected queueSize taskCount taskFinished name
  25       400        42       18          NaN      0         3.1       3.0          cse.executor.groupThreadPool-group1
  25       400        120      90          NaN      0         8.3       8.0          cse.executor.groupThreadPool-group0

左边是正常状态，右边是出问题前后的状态。
是client的队列积压了，这个积压的原因是连接数达到上限30了吗？
为什么这个时间段连接数会增长这么多？
![image](https://github.com/apache/servicecomb-java-chassis/assets/32792621/2ecad951-e757-4c2f-b2e9-282217cc68fc)

client配置如下：
![image](https://github.com/apache/servicecomb-java-chassis/assets/32792621/150ae0f4-f234-4a0f-bf7d-daad25742e85)

**Comment by liubao68** [comment]
估计是这个时间点突发的用户并发请求吧。

**Comment by timwind** [comment]
> 估计是这个时间点突发的用户并发请求吧。

入口TPS并没有增加，不过服务内部处理时，有多线程调用其他服务。
请问：如果服务端返回慢，这种纯reactive模式会一直占用连接数不释放吗？
CompletableFuture<Response<XXX>> queryXXX(@Valid @RequestBody XXX req);

**Comment by liubao68** [comment]
HTTP在响应没收到的时候，都不会是否。和reactive/非reactive没关系。

**Comment by timwind** [comment]
像这种服务端偶发耗时长，导致积压的问题，能修改哪个参数解决吗？
旧请求一直积压着处理，有可能会导致新来的正常请求都无法及时响应。后端服务压力也无法及时释放。
业务上允许超时过长的请求抛弃掉，不影响新请求就行。
rest.client.maxWaitQueueSize设置为0？

**Comment by timwind** [comment]
> HTTP在响应没收到的时候，都不会释放。和reactive/非reactive没关系。

像这种服务端偶发耗时长，导致积压的问题，能修改哪个参数解决吗？
旧请求一直积压着处理，有可能会导致新来的正常请求都无法及时响应。后端服务压力也无法及时释放。
业务上允许超时过长的请求抛弃掉，不影响新请求就行。
rest.client.maxWaitQueueSize设置为0？

**Comment by liubao68** [comment]
一般而言，只能丢弃新请求， 而无法终止已经处理的请求。  可以提前丢弃可能过载的请求，防止积压，而不是终止已经处理的请求。 快速失败的一些常见措施参考： [过载状态下的快速失败](https://huaweicse.github.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/featured-topics/secrets/fail-fast.html)
