### ISSUE TITLE
java-chassis3.0.0使用nacos做配置中心如何动态刷新配置

### ISSUE THREAD

**Issue by prank-xcw** [apache/servicecomb-java-chassis#4198]
`java-chassis 3.0.0`
`nacos-server 2.2.3`
配置中心重新发布配置后，程序代码中未更新配置

**Comment by liubao68** [comment]
你是如何使用的？

**Comment by prank-xcw** [comment]
步骤如下：
1.代码中使用@Value注入的配置，启动应用到nacos中心后
2.在nacos的配置中心更新配置重新发布后，代码中并没有更新到最新配置。

**Comment by chengyouling** [comment]
@value结合refreshScope是spring-cloud的机制，按照basic的测试接口/exampleConfig是可以实现的

**Comment by liubao68** [comment]
可以看下这篇介绍： https://servicecomb.apache.org/references/java-chassis/zh_CN/featured-topics/secrets/applied-config.html
