### ISSUE TITLE
基于chassis 3.x 创建的服务端接口，在消费端无法基于其生成的契约进行参数转换调用

### ISSUE THREAD

**Issue by yanghao605** [apache/servicecomb-java-chassis#4207]
接口定义如下：
![image](https://github.com/apache/servicecomb-java-chassis/assets/73453250/d987d1f1-4499-4fd5-be9e-b3d444114a88)
消费端报错：
{
    "message": "Parameter is not valid for operation [consumer.uploadSpringmvcSchema.uploadMultiformMix]. Parameter is [fileList]. Processor is [formData]. Message is [File input parameter of strList could be jakarta.servlet.http.Part / java.io.InputStream / org.springframework.core.io.Resource / byte[] or java.io.File, but got java.lang.String.]."
}

**Comment by liubao68** [comment]
`List<MultipartFile>` 和 `List<String>` 用于文件上传没有良好的 HTTP 语义， 建议结合业务分析下具体场景。  

设计合适的API可以参考 [HTTP参数映射参考](https://huaweicse.github.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/build-provider/http-mapping.html) 。

**Comment by liubao68** [comment]
see https://github.com/apache/servicecomb-java-chassis/pull/4235
