### ISSUE TITLE
空指针异常是否需要处理

### ISSUE THREAD

**Issue by yanghao605** [apache/servicecomb-java-chassis#4236]
2.8.4版本，在获取client时，如果client不存在会返回null，这会导致后续逻辑执行时，抛出一个空指针异常。这种情况是否需要处理？
![image](https://github.com/apache/servicecomb-java-chassis/assets/73453250/e7e3c70c-5d09-44d1-a76e-deecda9fb411)
![image](https://github.com/apache/servicecomb-java-chassis/assets/73453250/9c0b0100-ccba-470a-97d5-181c891f565b)

**Comment by liubao68** [comment]
关键是要看下这个场景发生的条件。 如果可以避免，则需要处理，如果不能避免， 那么可能也没有处理手段。

**Comment by yanghao605** [comment]
这个场景是不可避免的，当client创建失败时，服务需要重启才能修复由此产生的空指针不处理好像也没什么事
