### ISSUE TITLE
服务报错： code=590;msg=CommonExceptionData [message=not support file upload.  并出现线程阻塞

### ISSUE THREAD

**Issue by qwerty759** [apache/servicecomb-java-chassis#4241]
项目未使用 上传功能 ，出现  code=590;msg=CommonExceptionData [message=not support file upload
![image_2024-03-01_14-20-37](https://github.com/apache/servicecomb-java-chassis/assets/155422161/2c7f6c12-f4aa-407e-8b75-ae90227e778d)
并且之后出现线程阻塞
![image_2024-03-01_14-22-02](https://github.com/apache/servicecomb-java-chassis/assets/155422161/20564b6e-74e4-4bdd-8f94-3069c4c3de1b)
![image_2024-03-01_14-25-18](https://github.com/apache/servicecomb-java-chassis/assets/155422161/329310eb-4033-4fe4-af0a-37b0772d2cf0)
这个是什么原因导致的呢？

**Comment by liubao68** [comment]
上面的信息很难推测你的使用场景。

**Comment by qwerty759** [comment]
> 建议你先检查一下文件上传的配置项
项目中 没有用到文件上传的配置项
APPLICATION_ID: 
service_description:
  name: 
  version: 
  environment: 
servicecomb:
  service:
    registry:
      address: 
  rest:
    address: 
  executors:
    default:

**Comment by qwerty759** [comment]
> 上面的信息很难推测你的使用场景。
![屏幕截图 2024-03-18 111536](https://github.com/apache/servicecomb-java-chassis/assets/155422161/14e53c6a-5e60-4bc7-932b-c8ec1c1c5712)

项目经常会 出现  这种异常，造成 cpu 过高，每次重启之后就好了，但是过段实际就又出现了
