### ISSUE TITLE
Springboot引入ServiceComb之后，出现类型转换的问题

### ISSUE THREAD

**Issue by Welkin1027** [apache/servicecomb-java-chassis#4263]
我在一个SpringBoot项目中引入了ServiceComb，但是出现了类型转换的问题。相关代码如下：

```
Caused by: java.lang.IllegalStateException: failed to fill parameter, parameterName=uploadFile.
	at org.apache.servicecomb.swagger.generator.core.AbstractOperationGenerator.scanMethodParameter(AbstractOperationGenerator.java:329)
	at org.apache.servicecomb.swagger.generator.core.AbstractOperationGenerator.scanMethodParameters(AbstractOperationGenerator.java:196)
	at org.apache.servicecomb.swagger.generator.core.AbstractOperationGenerator.generate(AbstractOperationGenerator.java:152)
	at org.apache.servicecomb.swagger.generator.core.AbstractSwaggerGenerator.scanMethods(AbstractSwaggerGenerator.java:297)
	... 16 common frames omitted
Caused by: java.lang.ClassCastException: class io.swagger.models.parameters.BodyParameter cannot be cast to class io.swagger.models.parameters.FormParameter (io.swagger.models.parameters.BodyParameter and io.swagger.models.parameters.FormParameter are in unnamed module of loader 'app')
	at org.apache.servicecomb.swagger.generator.core.processor.parameter.PartProcessor.fillParameter(PartProcessor.java:34)
	at org.apache.servicecomb.swagger.generator.core.AbstractOperationGenerator.fillParameter(AbstractOperationGenerator.java:378)
	at org.apache.servicecomb.swagger.generator.core.AbstractOperationGenerator.scanMethodParameter(AbstractOperationGenerator.java:322)
	... 19 common frames omitted

@ApiOperation("更新静态检查结果")
    @PostMapping("update")
    public WebResult<Void> update(
        @RequestBody(required = false) MultipartFile uploadFile) {
        return WebResult.success();
    }

pom中的主要依赖是
<dependency>
            <groupId>org.apache.servicecomb</groupId>
            <artifactId>registry-service-center</artifactId>
            <version>2.6.0</version>
</dependency>

<dependency>
            <groupId>org.apache.servicecomb</groupId>
            <artifactId>java-chassis-spring-boot-starter-servlet</artifactId>
            <version>2.6.0</version>
</dependency>

在使用@EnableServiceComb注解之前，相关代码都是正常运行的，但是使用ServiceComb之后，org.apache.servicecomb.swagger下的包对这些注解进行了新的验证操作。我现在没弄懂这里为什么会有ClassCastException，如何能够避免servicecomb对这块的检验呢？

**Comment by Welkin1027** [comment]
> 我在一个SpringBoot项目中引入了ServiceComb，但是出现了类型转换的问题。相关代码如下：
> 
> Caused by: java.lang.IllegalStateException: failed to fill parameter, parameterName=uploadFile. at org.apache.servicecomb.swagger.generator.core.AbstractOperationGenerator.scanMethodParameter(AbstractOperationGenerator.java:329) at org.apache.servicecomb.swagger.generator.core.AbstractOperationGenerator.scanMethodParameters(AbstractOperationGenerator.java:196) at org.apache.servicecomb.swagger.generator.core.AbstractOperationGenerator.generate(AbstractOperationGenerator.java:152) at org.apache.servicecomb.swagger.generator.core.AbstractSwaggerGenerator.scanMethods(AbstractSwaggerGenerator.java:297) ... 16 common frames omitted Caused by: java.lang.ClassCastException: class io.swagger.models.parameters.BodyParameter cannot be cast to class io.swagger.models.parameters.FormParameter (io.swagger.models.parameters.BodyParameter and io.swagger.models.parameters.FormParameter are in unnamed module of loader 'app') at org.apache.servicecomb.swagger.generator.core.processor.parameter.PartProcessor.fillParameter(PartProcessor.java:34) at org.apache.servicecomb.swagger.generator.core.AbstractOperationGenerator.fillParameter(AbstractOperationGenerator.java:378) at org.apache.servicecomb.swagger.generator.core.AbstractOperationGenerator.scanMethodParameter(AbstractOperationGenerator.java:322) ... 19 common frames omitted
> 
> @ApiOperation("更新静态检查结果") @PostMapping("update") public WebResult update( @requestbody(required = false) MultipartFile uploadFile) { return WebResult.success(); }
> 
> pom中的主要依赖是 org.apache.servicecomb registry-service-center 2.6.0
> 
> org.apache.servicecomb java-chassis-spring-boot-starter-servlet 2.6.0
> 在使用@EnableServiceComb注解之前，相关代码都是正常运行的，但是使用ServiceComb之后，org.apache.servicecomb.swagger下的包对这些注解进行了新的验证操作。我现在没弄懂这里为什么会有ClassCastException，如何能够避免servicecomb对这块的检验呢？

**Comment by Welkin1027** [comment]
去掉@RequestBody注解之后，该接口验证通过，但这没有意义，有没有什么办法不让Servicecomb的注解影响到原本的工程？

**Comment by Welkin1027** [comment]
org.apache.servicecomb.swagger这个包导致的错误还很多，都是引入servicecomb之后，程序在springboot的基础上对一些注解进行了再次的检验。有些检验结果虽然能改，但也会导致不太方便，能不能直接屏蔽掉这个swagger包，或者让它不要影响原始工程

**Comment by Welkin1027** [comment]
> 去掉@requestbody注解之后，该接口验证通过，但这没有意义，有没有什么办法不让Servicecomb的注解影响到原本的工程？

这个问题已经解决了，File类文件需要使用@RequestPart。不过还有别的问题，比如参数不可以是HttpServletResponse。
Caused by: java.lang.IllegalStateException: all input/output of ServiceComb operation are models, not allow to use HttpServletResponse.
org.apache.servicecomb.swagger.generator.core.AbstractOperationGenerator.validateParameter(AbstractOperationGenerator.java:313)

**Comment by liubao68** [comment]
java chassis不是spring mvc， 你们是spring mvc项目改造为java chassis吗？这个可能涉及很多问题，需要看下你们使用java chassis的背景和目标。架构改造通常是个复杂的过程， 需要建立在充分理解两个框架的基础上。

**Comment by Welkin1027** [comment]
> [Spring MVC用户和Java Chassis的差异及开发指引](https://github.com/apache/servicecomb-java-chassis/issues/2766) 看看这个呢?

感谢回复，不过相关文档我都看过，针对我提到的具体问题，这里解释了不能用HttpServletResponse。
我现在还有个疑问。我的项目中，两个不同的类中有相同的子类，具体是PackageOwnershipViewDto$AllDataCompareResult与PackageFileViewDto$AllDataCompareResult，在servicecomb中，这两个子类被判定为duplicate，然后报错了。我查看了源码，在org.apache.servicecomb.swagger.SwaggerUtils.modelOfClassNotDuplicate方法中，这两个类的比较结果是不相同，方法返回的是false，但方法名却表示它们是duplicate的，导致程序错误。这里是否是方法写得有问题？明明是notEqual的，应该是不重复的吧？

代码版本是org.apache.servicecomb:swagger-generator-core-2.8.9.jar

**Comment by Welkin1027** [comment]
> java chassis不是spring mvc， 你们是spring mvc项目改造为java chassis吗？这个可能涉及很多问题，需要看下你们使用java chassis的背景和目标。架构改造通常是个复杂的过程， 需要建立在充分理解两个框架的基础上。
> 
> 可以看下 [java chassis介绍与spring cloud等比较](https://www.zhihu.com/question/67498050/answer/3412461410)

感谢回复，springboot与servicecomb的差异比我想的大，相关升级改造正在进行中。

**Comment by liubao68** [comment]
> > [Spring MVC用户和Java Chassis的差异及开发指引](https://github.com/apache/servicecomb-java-chassis/issues/2766) 看看这个呢?
> 
> 感谢回复，不过相关文档我都看过，针对我提到的具体问题，这里解释了不能用HttpServletResponse。 我现在还有个疑问。我的项目中，两个不同的类中有相同的子类，具体是PackageOwnershipViewDto$AllDataCompareResult与PackageFileViewDto$AllDataCompareResult，在servicecomb中，这两个子类被判定为duplicate，然后报错了。我查看了源码，在org.apache.servicecomb.swagger.SwaggerUtils.modelOfClassNotDuplicate方法中，这两个类的比较结果是不相同，方法返回的是false，但方法名却表示它们是duplicate的，导致程序错误。这里是否是方法写得有问题？明明是notEqual的，应该是不重复的吧？
> 
> 代码版本是org.apache.servicecomb:swagger-generator-core-2.8.9.jar，具体方法如下：
> 
> ```
> private static boolean modelOfClassNotDuplicate(Model tempModel, Model model) {
>     String tempModelClass = (String) tempModel.getVendorExtensions().get(SwaggerConst.EXT_JAVA_CLASS);
>     String modelClass = (String) model.getVendorExtensions().get(SwaggerConst.EXT_JAVA_CLASS);
>     return tempModelClass.equals(modelClass);
>   }
> ```
> 
> 逻辑上来说，两个class equal的时候才是重复的吧

代码逻辑是没问题的, equal的时候才是不重复。 这个逻辑就是检测你说的：  "PackageOwnershipViewDto$AllDataCompareResult与PackageFileViewDto$AllDataCompareResult"  类名不一样， model一样的情景。

这种场景你必须使用 `@ApiModel` 声明不同的名字，否则是不允许的。

**Comment by Welkin1027** [comment]
> > > [Spring MVC用户和Java Chassis的差异及开发指引](https://github.com/apache/servicecomb-java-chassis/issues/2766) 看看这个呢?
> > 
> > 
> > 感谢回复，不过相关文档我都看过，针对我提到的具体问题，这里解释了不能用HttpServletResponse。 我现在还有个疑问。我的项目中，两个不同的类中有相同的子类，具体是PackageOwnershipViewDto$AllDataCompareResult与PackageFileViewDto$AllDataCompareResult，在servicecomb中，这两个子类被判定为duplicate，然后报错了。我查看了源码，在org.apache.servicecomb.swagger.SwaggerUtils.modelOfClassNotDuplicate方法中，这两个类的比较结果是不相同，方法返回的是false，但方法名却表示它们是duplicate的，导致程序错误。这里是否是方法写得有问题？明明是notEqual的，应该是不重复的吧？
> > 代码版本是org.apache.servicecomb:swagger-generator-core-2.8.9.jar，具体方法如下：
> > ```
> > private static boolean modelOfClassNotDuplicate(Model tempModel, Model model) {
> >     String tempModelClass = (String) tempModel.getVendorExtensions().get(SwaggerConst.EXT_JAVA_CLASS);
> >     String modelClass = (String) model.getVendorExtensions().get(SwaggerConst.EXT_JAVA_CLASS);
> >     return tempModelClass.equals(modelClass);
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 逻辑上来说，两个class equal的时候才是重复的吧
> 
> 代码逻辑是没问题的, equal的时候才是不重复。 这个逻辑就是检测你说的： "PackageOwnershipViewDto$AllDataCompareResult与PackageFileViewDto$AllDataCompareResult" 类名不一样， model一样的情景。
> 
> 这种场景你必须使用 `@ApiModel` 声明不同的名字，否则是不允许的。

已按照建议修改，问题已解决，谢谢！
