### ISSUE TITLE
org.apache.servicecomb.foundation.common.utils.BeanUtils多提供一个initWithoutDefaultResource方法

### ISSUE THREAD

**Issue by qiuchao123** [apache/servicecomb-java-chassis#4269]
原因：当前我们业务初始化会使用org.apache.servicecomb.foundation.common.utils.BeanUtils加载classpath*:META-INF/spring/*.xml，包含DEFAULT_BEAN_RESOURCE：classpath*:META-INF/spring/*.bean.xml，导致cse.bean生成了两个SCBApplicationListene bean实例，启动抛了Registry has already bean initialized and not allowed to initialize twice.异常。
![image](https://github.com/apache/servicecomb-java-chassis/assets/42757982/5c74ba28-a38b-4e73-8181-b4ea1293533c)

期望：能加一个initWithoutDefaultResource方法，不加载DEFAULT_BEAN_RESOURCE
![image](https://github.com/apache/servicecomb-java-chassis/assets/42757982/235472c6-1ba8-4079-bd80-e167764ae81e)

**Comment by liubao68** [comment]
Fixed in https://github.com/apache/servicecomb-java-chassis/pull/4274
