### ISSUE TITLE
框架上报版本号后，在业务代码中如何获取

### ISSUE THREAD

**Issue by ghosts321** [apache/servicecomb-java-chassis#4305]
分别实现org.apache.servicecomb.registry.api.Versions接口和org.apache.servicecomb.registry.api.PropertyExtended接口
项目启动后将properties和version都注入到了微服务的元数据中，业务代码中该如何获取properties和version

**Comment by liubao68** [comment]
可以看看 MicroserviceInstance。 不同的版/注册中心实现获取实例信息的API会有差异。
