### ISSUE TITLE
microservice.yaml配置动态加载生效能力 失效

### ISSUE THREAD

**Issue by ForeverDone** [apache/servicecomb-java-chassis#4330]
背景：
业务在使用CSE时，为实现microservice.yaml配置动态加载生效能力，自行覆盖CSE原有的PollingScheduler。
例如：在microservice.yaml中配置的流控配置，修改后无需重启，即可生效。

现象：
当前业务升级nuwa3.1, foundation-config从 1.3.11 升级到 2.8.14版本。业务运行过程中会报空指针。 业务调用
(MicroserviceConfigLoader) configurations.getProperty("cse-microservice-config-loader");
获取到的loader 为空

原因：发现foundation-config从 1.3.11 升级到 2.8.14版本后，删掉了设置 “cse-microservice-config-loader”的代码
ConfigUtil.setMicroserviceConfigLoader(config, loader);

Q:请问为什么要删掉这个呢，升级后，为了保持原有功能，推荐怎么做

**Comment by liubao68** [comment]
`MicroserviceConfigLoader loader = new MicroserviceConfigLoader()` , 内部变量，业务可以自己声明。
