### ISSUE TITLE
InvocationContext map 不安全

### ISSUE THREAD

**Issue by dfdfqwqw** [apache/servicecomb-java-chassis#4410]
![image](https://github.com/apache/servicecomb-java-chassis/assets/51687046/21a13824-ad71-47ee-999d-2de0d363d0b6)

问题：localContext目前存在并发操作，hashmap并发操作时可能导致值丢失，框架中多处使用invocation.getHandlerContext().get()，当取出来为null时就会导致空指针

建议：
修改localContext为ConcurrentHashMap

**Comment by liubao68** [comment]
能具体描述下业务场景吗，看看是不是一定需要并发访问？对应一个invocation，理论上不应该存在并发的情况。 如果不是必须，建议考虑下其他的实现方案，避免并发。

**Comment by dfdfqwqw** [comment]
> 能具体描述下业务场景吗，看看是不是一定需要并发访问？对应一个invocation，理论上不应该存在并发的情况。 如果不是必须，建议考虑下其他的实现方案，避免并发。
> 
> 另外， `框架中多处使用invocation.getHandlerContext().get()，当取出来为null时就会导致空指针` 是指问题不是业务场景导致的吗？能否提供一个重现问题的例子。

当前 有使用 探针或者调用链产品时，针对servicecomb埋点时会使用上下文进行并发的修改，例如当前使用华为云的APM探针就会有这个问题
另外定位问题时，日志中打印 invocation.getHandlerContext().tostring  有概率会报ConcurrentModificationException 错误，说明是存在并发操作的

**Comment by dfdfqwqw** [comment]
> > 能具体描述下业务场景吗，看看是不是一定需要并发访问？对应一个invocation，理论上不应该存在并发的情况。 如果不是必须，建议考虑下其他的实现方案，避免并发。
> > 另外， `框架中多处使用invocation.getHandlerContext().get()，当取出来为null时就会导致空指针` 是指问题不是业务场景导致的吗？能否提供一个重现问题的例子。
> 
> 当前 有使用 探针或者调用链产品时，针对servicecomb埋点时会使用上下文进行并发的修改，例如当前使用华为云的APM探针就会有这个问题 另外定位问题时，日志中打印 invocation.getHandlerContext().tostring 有概率会报ConcurrentModificationException 错误，说明是存在并发操作的

另外这个上下文获取是public的，就没法避免外部的多种使用场景，建议加强框架可靠性

**Comment by liubao68** [comment]
> > > 能具体描述下业务场景吗，看看是不是一定需要并发访问？对应一个invocation，理论上不应该存在并发的情况。 如果不是必须，建议考虑下其他的实现方案，避免并发。
> > > 另外， `框架中多处使用invocation.getHandlerContext().get()，当取出来为null时就会导致空指针` 是指问题不是业务场景导致的吗？能否提供一个重现问题的例子。
> > 
> > 
> > 当前 有使用 探针或者调用链产品时，针对servicecomb埋点时会使用上下文进行并发的修改，例如当前使用华为云的APM探针就会有这个问题 另外定位问题时，日志中打印 invocation.getHandlerContext().tostring 有概率会报ConcurrentModificationException 错误，说明是存在并发操作的
> 
> 另外这个上下文获取是public的，就没法避免外部的多种使用场景，建议加强框架可靠性

能展示下代码片段吗？有可能是对应产品的代码有问题。

**Comment by dfdfqwqw** [comment]
> 从

是的，有可能是产品并发使用了，这个我们使用方也不太清楚
代码片段的话， 我们只是在put上下文之后打印了一下上下文的内容日志，这个会导致ConcurrentModificationException 
![image](https://github.com/apache/servicecomb-java-chassis/assets/51687046/af69d332-a283-47ad-974a-74ce7bf04d7a)

**Comment by liubao68** [comment]
需要看看产品的代码，不是这段。 这段应该是你基于java chassis修改后的调试代码吧？这个地方不会引起并发修改的。 一个后台线程修改请求上下文，可能破坏处理流程的。

**Comment by dfdfqwqw** [comment]
> 需要看看产品的代码，不是这段。 这段应该是你基于java chassis修改后的调试代码吧？这个地方不会引起并发修改的。 一个后台线程修改请求上下文，可能破坏处理流程的。

但是这个日志打印代码  可以抛出 ConcurrentModificationException 是否说明本身也可能存在并发修改呢

**Comment by liubao68** [comment]
> > 需要看看产品的代码，不是这段。 这段应该是你基于java chassis修改后的调试代码吧？这个地方不会引起并发修改的。 一个后台线程修改请求上下文，可能破坏处理流程的。
> 
> 但是这个日志打印代码 可以抛出 ConcurrentModificationException 是否说明本身也可能存在并发修改呢

需要找到另外的修改的线程。你贴的代码是请求执行流程。
