### ISSUE TITLE
protobuf-java 升级适配问题

### ISSUE THREAD

**Issue by yanghao605** [apache/servicecomb-java-chassis#4416]
当前用的protobuf-java还是3.23.4版本，升级到3.25.0之后，highway的client会因为protobuf无法解析导致无法调用。该如何处理？
![image](https://github.com/user-attachments/assets/3c77e5d1-a4fb-4caf-b35c-c407b2c48008)

**Comment by shoothzj** [comment]
which servicecomb version you are using? did the library upgrade to 3.25.0 or you update it alone?

**Comment by yanghao605** [comment]
> which servicecomb version you are using? did the library upgrade to 3.25.0 or you update it alone?
version：2.8.4
only upgrade protobuf-java to 3.25.0

**Comment by shoothzj** [comment]
@yanghao605 I think you should also update servicecomb version in case of jar version conflict. Feel free to reopen this issue if you still have other question.
