### ISSUE TITLE
InvokerUtils.syncInvoke兼容问题

### ISSUE THREAD

**Issue by 2759996860** [apache/servicecomb-java-chassis#4422]
servicecomb1.x升级到2.x之后，InvokerUtils.syncInvoke的swaggerArguments由object[]变成了Map<String, Object> swaggerArguments，我们有业务实现了类似网关的功能，大量的接口调用都无法感知到参数名，servicecomb2.x有办法不传参数名，通过参数顺序进行微服务调用吗？

**Comment by liubao68** [comment]
能给下示例代码吗？ `schemaId`, `operationId`怎么得来的？貌似通过InvokerUtils没法实现类似网关的功能。

**Comment by 2759996860** [comment]
我们的service, schemaId, operationId, swaggerArguments都是保存在了数据库中，根据不同业务从表里拿到这些参数，然后直接使用InvokerUtils.syncInvoke进行调用，参数在表里存的是object[]类型，要修改成Map<String, Object>需要做大整改。

**Comment by liubao68** [comment]
这种场景比较麻烦，没法提供通用的兼容性方案。 可以看看 InvokerUtils `createInvocation` 方法， 可以通过 `OperationMeta` 获取到参数列表，然后将数组参数映射为Map参数，再调用。 这个前提是 `OperationMeta` 获取到参数列表是和实际的参数列表顺序是一致的（1.3.x其实也有这样的假设，但这个假设可能是不可靠的，这也是2.x做这个变化的原因）。
