### ISSUE TITLE
Java-Chassis的getBodyBuffer方法的行为变化

### ISSUE THREAD

**Issue by yhs0092** [apache/servicecomb-java-chassis#4426]
## 现象

如果在 `HttpServerFilter` 的 `afterReceiveRequest` 方法中调用 `requestEx.getBodyBuffer()` 方法, 在 Java-Chassis 1.3 分支, `getBodyBuffer()`方法一定会返回一个对象, 即使是对于 GET 请求这种没有 body 的请求, 也能拿到一个空的 bodybuffer. 但在 Java-Chassis 2.8 分支, 如果请求本身没有body, 则 `getBodyBuffer()` 方法返回值变为 `null`.

涉及此场景的用户就会发现, 升级之后他们多了一些 NullPointerException 错误, 而这在使用 Java-Chassis 1.3 分支的时候并不存在.

## 代码分析

我们简要分析了一下 Java-Chassis 的相关源码, 发现变化点可能是  `org.apache.servicecomb.transport.rest.vertx.RestBodyHandler` 引入的.
在 Java-Chassis 1.3 分支, `RestBodyHandler`无论如何都会向 `HttpServerRequest` 中引入一个 `BHandler` 实例, 而这个 `BHandler` 始终会向`RoutingContext`中添加一个非null的 bodybuffer 对象.

但在 Java-Chassis 2.8 分支, `RestBodyHandler`会先判断请求是否有body, 如果没有, 则根本不会添加 `BHandler` 实例.

这种空指针异常通常会让用户比较迷惑, 因为从业务视角看来, 他们在升级 Java-Chassis 的过程中, 通常不会修改 `getBodyBuffer()` 上下文的代码,但是升级之后就是会突然多出一些空指针异常.

请问 Java-Chassis 能否在这里做一下兼容? P.S. 要修的话, 还有`getInputStream` 等获取body内容的方法, 也有类似的现象, 请一起处理一下.

**Comment by liubao68** [comment]
建议业务针对这种情况下改下代码，做好保护。 从上面的分析，这个变化是三方件升级(vert.x引起的），而且对于GET请求， 确实没有body，业务在这种情况下获取和使用body，逻辑上就是应该保护的。 

具体能否兼容还需要分析下可能的风险。
