### ISSUE TITLE
RpcReferenceProcessor在涉及FactoryBean构造方法注入的场景中可能失效

### ISSUE THREAD

**Issue by yhs0092** [apache/servicecomb-java-chassis#4433]
## 问题场景

1. 声明一个Spring Bean(假设为`TestBean`), 在其中添加一个带`@RpcReference`注解的RPC动态代理属性;
2. 声明一个FactoryBean(假设为`TestFactoryBean`), 通过构造方法注入的形式引用第一步声明的`TestBean`;

此时会造成第一步声明的 Spring Bean 初始化的时间点早于 Java-Chassis 的 `RpcReferenceProcessor` 生效的时间点, 造成第一步声明的TestBean的 RpcReference 属性未被 Java-Chassis 的`RpcReferenceProcessor`扫描处理, 结果为null.

## 根因分析

Java-Chassis 有一个类 `org.apache.servicecomb.config.inject.InjectBeanPostProcessor` , 在新版本改为了使用构造方法注入的形式引用 `PriorityPropertyManager`, 同时`InjectBeanPostProcessor`这个类是`BeanPostProcessor`类型的, 会在Spring启动的早期就初始化.

因此Spring会在一个比较早的时间点就实例化`InjectBeanPostProcessor`, 进而触发Spring提前扫描所有的 Spring bean 定义, 搜索其中为`PriorityPropertyManager`类型的 Bean 以便做注入.
如果在这个过程中, 有部分Bean是以 `FactoryBean` 的形式声明的, 则这些 `FactoryBean` 也会被提前创建出来, 因为Spring要调用`FactoryBean`的`getObjectType`方法, 以便过滤目标类型的 Spring Bean. **假如业务有`FactoryBean`以构造方法的形式引用了其他的业务bean, 则这些业务bean也会连带着被提前初始化. 而这些业务bean中如果存在`@RpcReference`注解声明的RPC动态代理, 则会由于`RpcReferenceProcessor`还没有注册到Spring而错过处理`@RpcReference`注解的流程, 最终导致这些业务的bean中的 RPC 动态代理属性为 null.**

根本原因在于`InjectBeanPostProcessor`和`RpcReferenceProcessor`同为`BeanPostProcessor`, 没有区分优先级, 因此Spring会在同一个批次初始化它们两个, Spring会在这一批BeanPostProcessor都初始化完成后, 再统一注册到Spring中生效.

关键位置的截图如下:

> `InjectBeanPostProcessor`触发Spring扫描`PriorityPropertyManager`类型的Bean

![image](https://github.com/user-attachments/assets/7abc49c9-74ae-480c-a32b-069357c2b1a3)

Spring初始化`BeanPostProcessor`的代码在`org.springframework.context.support.PostProcessorRegistrationDelegate#registerBeanPostProcessors(org.springframework.beans.factory.config.ConfigurableListableBeanFactory, org.springframework.context.support.AbstractApplicationContext)`方法中.

## 解决思路

Spring会按照`PriorityOrdered`->`Ordered`->无order 三个批次初始化`BeanPostProcessor`, 如果给 `org.apache.servicecomb.provider.pojo.reference.RpcReferenceProcessor` 添加 `Ordered` 或 `PriorityOrdered` 接口, 使其提前注册到Spring中, 则可以在`InjectBeanPostProcessor`触发 `FactoryBean` 初始化时生效.

**Comment by liubao68** [comment]
see https://github.com/apache/servicecomb-java-chassis/issues/2740
