### ISSUE TITLE
添加nacos-api依赖

### ISSUE THREAD

**Issue by karsonto** [apache/servicecomb-java-chassis#4465]
学习源码时发现使用nacos作为注册中心，idea找不到nacos-api类，需要在pom.xml补充依赖

**Comment by liubao68** [comment]
你能提供下错误信息和使用场景吗？ 项目是有CICD的， 有nacos的自动化测试， 而且大家使用IDEA都未碰到这个问题。

**Comment by karsonto** [comment]
我看了nacos client 对api 的依赖是optional为true

**Comment by liubao68** [comment]
> 我看了nacos client 对api 的依赖是optional为true

你能提供下你的java chassis版本和nacos client版本吗？ 我记得早期开发的时候，碰到过你的情况。 用 `mvn dependency:tree -Pnacos` 导出依赖关系， 我也没看到 nacos-api的依赖，但是项目编译、运行都是没问题的。

**Comment by karsonto** [comment]
情况时这样的，我下载项目源码学习时候，发现项目里面没有引入nacos api 的依赖，导致idea警告编译错误，所以我提了这个issue
<img width="1411" alt="image" src="https://github.com/user-attachments/assets/99212294-35cf-411f-a4ff-6863f44a0577">

**Comment by liubao68** [comment]
这些类都在nacos-client*jar里面。 我本地都能编译。 
你的PR提交后跑了下CI，反而自动化测试都通不过了： https://github.com/apache/servicecomb-java-chassis/pull/4466

**Comment by karsonto** [comment]
嗯，找到原因了，是我本地仓库nacos版本问题，2.4.0后改动了本地仓库导致api引入依赖问题，谢谢了
