### ISSUE TITLE
how to bump jakarta.servlet:jakarta.servlet-api from 6.0.0 to 6.1.0

### ISSUE THREAD

**Issue by caimo** [apache/servicecomb-java-chassis#4467]
Jakarta的HttpServletResponse在6.1.0加了5个接口（sendRedirect/setTrialer，
现在ServiceComb的两个类，VertxServerResponseToHttpServletResponse,VertxClientResponseToHttpServletResponse继承了这个接口，没有实现这些接口。所以报错。

继承关系：
VertxServerResponseToHttpServletResponse 
extends AbstractHttpServletResponse 
  extends BodyBufferSupportImpl implements HttpServletResponseEx
                                                                             extends HttpServletResponse

修改方案：
VertxServerResponseToHttpServletResponse （是否新增5个接口）
extends AbstractHttpServletResponse （需要新增5个接口默认实现，同其他接口一致，默认抛异常）
  extends BodyBufferSupportImpl implements HttpServletResponseEx
                                                                             extends HttpServletResponse 6.1.0已新增5个接口

**方案1：**
只修改：AbstractHttpServletResponse，修改内容为实现5个接口，同其他接口一致，默认抛异常

**方案2：**
同时修改：
VertxClientResponseToHttpServletResponse（需要新增5个接口实现）
VertxServerResponseToHttpServletResponse（需要新增5个接口实现）
AbstractHttpServletResponse（需要新增5个接口默认实现，同其他接口一致，默认抛异常）

**Comment by liubao68** [comment]
java chassis会定期升级三方件。 如果还未升级，可以描述下你需要从哪个版本升级到哪个版本，已经升级原因（比如安全漏洞等）。

**Comment by caimo** [comment]
升级原因
1、dependentbot自动升级失败了，需要手动升级。
2、springboot下个版本也是6.1.0，需要配套

已沟通跟随大版本升级，采用方案1，按需提供接口方式进行升级，升级跟踪使用jira：
https://issues.apache.org/jira/projects/SCB/issues/SCB-2890?filter=allissues
