### ISSUE TITLE
JavaChassis 2.8.X 版本中rxnetty的版本显示控制为了0.5.1，但是从rxnetty的社区中看，0.5.1是误“发布”版本，后续是否需要更新rxnetty版本？

### ISSUE THREAD

**Issue by lennonchan** [apache/servicecomb-java-chassis#4479]
JavaChassis中 显式控制了rxnettty的版本为0.5.1 https://github.com/apache/servicecomb-java-chassis/blob/2.8.19/dependencies/default/pom.xml#L90
rxnetty的社区中说明 0.5.1为误发布版本，https://github.com/ReactiveX/RxNetty/issues/439。 
JavaChassis中的rxnettty的版本是否需要升级为其他版本？

**Comment by liubao68** [comment]
2.x升级为0.5.3.    3.x已经不依赖Hystrix相关组件（社区已经停止更新），不存在这个组件依赖。
