### ISSUE TITLE
RegistryUtils.getServiceRegistryClient()方法被弃用

### ISSUE THREAD

**Issue by Lishuoyy** [apache/servicecomb-java-chassis#4565]
RegistryUtils.getServiceRegistryClient()方法已经被弃用了，现在应如何调用这个方法？

**Comment by chengyouling** [comment]
RegistryUtils.getResultFromFirstValidServiceRegistry(ServiceRegistry::getServiceRegistryClient);这样获取应该是可以的
用原来的方法是有什么异常吗？方法还是可以正常调用的

**Comment by Lishuoyy** [comment]
> RegistryUtils.getResultFromFirstValidServiceRegistry(ServiceRegistry::getServiceRegistryClient);这样获取应该是可以的 用原来的方法是有什么异常吗？方法还是可以正常调用的

感谢回复！
https://servicecomb.apache.org/references/java-chassis/2.x/zh_CN/featured-topics/upgrading/2_0_1T2_1_0.html
上述升级指导书中，**服务注册发现 API 的变化章节**建议不使用RegistryUtils接口，想知道不通过RegistryUtils 接口如何获取ServiceRegistryClient。

**Comment by liubao68** [comment]
需要看下你的业务场景，使用 ServiceRegistryClient 做什么。

**Comment by Lishuoyy** [comment]
> 需要看下你的业务场景，使用 ServiceRegistryClient 做什么。

更新微服务实例状态，当前是这么使用的。
```
RegistryUtils.getServiceRegistryClient()
    .updateMicroserviceInstanceStatus(RegistryUtils.getMicroserviceInstance().getServiceId(),
        RegistryUtils.getMicroserviceInstance().getInstanceId(), MicroserviceInstanceStatus.UP);
```
对应的是改为下面这样吗？
`RegistrationManager.INSTANCE.updateMicroserviceInstanceStatus(MicroserviceInstanceStatus.UP);`
