### ISSUE TITLE
servicecomb3对http请求头Content-Type的值，改为大小写敏感

### ISSUE THREAD

**Issue by cuixiushuai** [apache/servicecomb-java-chassis#4638]
1、从servicecomb2升级到servicecomb3升级后，对type敏感

**Comment by cuixiushuai** [comment]
1、从servicecomb2升级到servicecomb3升级后，对Content-Type的值大小写敏感
2、servicecomb2，客户端对Content-Type的值，传“Application/json”，不报错，正常处理
3、升级到servicecomb3之后，客户端对Content-Type的值，传“Application/json”，报错，类似：“not support content-type Application/json”

**Comment by liubao68** [comment]
具体还不清楚什么地方的变更引起的，建议可以先调整为application/json ， 几乎没见过这样写的 `Application/json`

**Comment by cuixiushuai** [comment]
> 具体还不清楚什么地方的变更引起的，建议可以先调整为application/json ， 几乎没见过这样写的 `Application/json`

1、是servicecomb的这次变更引起的
https://github.com/apache/servicecomb-java-chassis/commit/3d4c0b071ca676e20d8c4f65bb664fcb65081fc0#diff-7435bd2eafee6d1642b2f9aef8405dcaa64886c18291f754dd951e9e689062bbR33
2、由于客户端是第三方系统，第三方系统声称这是符合规范的，没同意修改
3、请确认下，是否确实是框架的逻辑有问题

**Comment by SweetWuXiaoMei** [comment]
根据[RFC 7231](https://datatracker.ietf.org/doc/html/rfc7231#section-3.1.1.1)标准，严格来说，HTTP 头字段中的内容类型（如 Content-Type）是 大小写不敏感 的，但是推荐使用全部小写，为了支持标准，servicecomb予以修改，支持RFC标准。
