### ISSUE TITLE
使用Nacos注册中心发现实例时存在问题

### ISSUE THREAD

**Issue by myhaiting** [apache/servicecomb-java-chassis#4643]
### 代码实现：
https://github.com/apache/servicecomb-java-chassis/blob/27552d28ac0d16eb73b9c0023833aa753fd09173/service-registry/registry-nacos/src/main/java/org/apache/servicecomb/registry/nacos/NacosDiscovery.java#L75-L100

### 问题描述
1、当发现demo-service服务时，如果demo-service服务还未注册，subscribe回调不会执行，返回空的List
2、然后demo-service启动，subscribe执行回调，由于
```java
if (result.getAndSet(false)) {
        // ignore the first event.
        return;
}
```
实例并不能正常通知，调用服务会报错：no instances

需要依赖的服务提前注册，或者依赖服务再重启一次才能正常发现实例

**Comment by liubao68** [comment]
不知道你方便分析和提交PR修复下吗？

**Comment by myhaiting** [comment]
> 不知道你方便分析和提交PR修复下吗？
可以，这个问题我来修复
