### ISSUE TITLE
ServiceComb的调用链默认是对接zipkin的，如何对接jaeger？

### ISSUE THREAD

**Issue by ryphnyuan** [apache/servicecomb-java-chassis#722]
在代码中使用restTemplate.getForEntity等方法调用其他的springmvc服务，springboot对接jaeger使用springboot自配置，可以正常的提交调用链信息，log信息，但是集成了ServiceComb后，调用链信息会被分割成多条，而且log信息，错误信息等无法输出。

**Comment by WillemJiang** [comment]
请问能提供jeager的版本信息吗？ 还有集成ServiceComb，使用是java chassis提供的restTemplate吗？

**Comment by ryphnyuan** [comment]
<dependency>
        <groupId>io.opentracing.contrib</groupId>
        <artifactId>opentracing-spring-web-autoconfigure</artifactId>
        <version>0.2.1</version>
    </dependency>
    <dependency>
	    <groupId>io.jaegertracing</groupId>
	    <artifactId>jaeger-core</artifactId>
	    <version>0.27.0</version>
    </dependency>

@Bean
    public RestTemplate restTemplate()
    {
        // Do any additional configuration here
        return RestTemplateBuilder.create();
    }

  jaeger版本为0.27.0，restTemplate是调用org.apache.servicecomb.provider.springmvc.reference.RestTemplateBuilder.create()方法生成的

**Comment by WillemJiang** [comment]
jaeger 是构建在zipkin基础之上的，ServiceComb已经支持zipkin 2.x. 
这里我们需要知道ServiceComb Java chassis的版本。还有就是你是如何使用servicecomb java chassis的？
http://servicecomb.incubator.apache.org/docs/howto-upgrade-topzipkin2/

**Comment by ryphnyuan** [comment]
CSE版本是2.3.12，使用方式参照的https://huawei-servicecomb.gitbooks.io/developerguide/content/using-cse-in-spring-boot/web-application.html，

**Comment by ryphnyuan** [comment]
CSE版本是2.3.12。
使用方式参照的是https://huawei-servicecomb.gitbooks.io/developerguide/content/using-cse-in-spring-boot/web-application.html。
通过在应用中注入一个io.opentracing.Tracer bean的方式，使用opentracing-spring-web-autoconfigure的能力，配置jaeger相关，并没有其他的额外配置。
@Bean
    public io.opentracing.Tracer jaegerTracer()
    {
        SenderConfiguration sender = new SenderConfiguration().withAgentHost(
                System.getProperty("jaegeragent.ip", "100.114.160.214")).withAgentPort(
                        Integer.getInteger("jaegeragent.port", 6831));
        SamplerConfiguration sampler = new SamplerConfiguration().withType(ProbabilisticSampler.TYPE).withParam(1);
        return new Configuration("configservice").withSampler(sampler).withReporter(
                new Configuration.ReporterConfiguration().withSender(sender)).getTracer();
    }
调用方式
@Autowired
    private RestTemplate restTemplate;

    @RequestMapping(path = "/test", method = RequestMethod.GET)
    public ResponseEntity<QueryTenantRsp> queryTenant()
    {
        QueryTenantRsp resp = restTemplate.getForObject(
                "cse://configservice/v1/tenants?tenant_id=111&page_size=10", QueryTenantRsp.class);
        return new ResponseEntity<QueryTenantRsp>(resp, HttpStatus.CREATED);
    }

jaegerui上看到的是调用/test一条，然后/v1/tenants一条。

是否当前ServiceComb并不支持集成jaeger，而仅支持zipkin呢？

**Comment by WillemJiang** [comment]
这是restTemplate 没有把当前的Transaction id传递过来， 需要做相关的打通的工作。
你可以参考一下 这里的代码， 让RestTemplate能知道传递过来的 Transaction ID https://github.com/apache/incubator-servicecomb-saga/tree/master/omega/omega-transport/omega-transport-resttemplate/src/main/java/org/apache/servicecomb/saga/omega/transport/resttemplate

**Comment by ryphnyuan** [comment]
还有一个问题，使用restTemplate调用服务的时候，如果是用的http://xxx的URL，是可以走到类似TransactionClientHttpRequestInterceptor这样的Interceptor的(jaeger的是TracingRestTemplateInterceptor)，但是如果使用的是cse://xxx这样的URL，则完全走不到上面的Interceptor

**Comment by ryphnyuan** [comment]
重新调测了一下，在启用了ServiceComb并去掉了spring原来的DispatcherServlet后，请求处理关键流程大致如下：
@SpringBootApplication(exclude= {DispatcherServletAutoConfiguration.class, DataSourceAutoConfiguration.class})
@EnableServiceComb

1、进入io.opentracing.Tracer，生成初始的span并将生成的span存入ThreadLocal。
2、进入到org.apache.servicecomb.transport.rest.servlet.RestServlet，调用具体的服务，并通过org.apache.servicecomb.common.rest.AbstractRestInvocation.scheduleInvocation()丢入线程池执行具体的业务处理。
3、通过RestTemplate，调用其他的服务。
这个时候，虽然也进入到了io.opentracing.contrib.spring.web.client.TracingRestTemplateInterceptor的相关方法中，但是之前保存在ThreadLocal中的初始span获取不到了，因为已经不是同一个线程了，导致后续的span是分离的，无法形成一个完成的调用链。

同时如果不使用ServiceComb，让请求走原来的org.springframework.web.servlet.DispatcherServlet，则不会出现这个问题，因为整个过程都是在一个线程中运行的，通过ThreadLocal能很好的处理这个初始span。

**Comment by WillemJiang** [comment]
需要想个办法处理跨线程span信息传递的问题的， 用ThreadLocal不能解决这个问题，估计得用显示的API get,set 相关的span信息了。

**Comment by ryphnyuan** [comment]
ThreadLocal是opentracing-spring-web-autoconfigure的默认实现。
考虑实现一个ScopeManager接口，但是这个接口也没办法进行span信息的传递的。
用显式的get/set处理相关的span信息，那是不是要侵入到servicecomb代码里面呢？
毕竟跨线程这一步是在servicecomb内部封装的也。
有没有可能退一步，提供个开关，关闭AbstractRestInvocation.scheduleInvocation()这里面的异步操作呢？
或者有什么建议吗？我肯定是希望越简单越好的~~

**Comment by WillemJiang** [comment]
我觉得这个问题可放到dev@servicecomb.apache.org 里面来讨论，如果使用同步调用接口带来的问题会带来性能下降的问题。

**Comment by ryphnyuan** [comment]
当前是通过在tracingfilter之后添加一个filter，把当前的span放到HttpRequest的attribute里面，经过RestServlet后，再做一个实现了HttpServerFilter的接口，把请求里面的span重新激活，目前看形成了一条调用链。
不过相比未开启servicecomb的时候，还是缺少由io.opentracing.contrib.spring.web.interceptor.TracingHandlerInterceptor这个类添加上去的一些信息。因为这些在原来的DispatcherServlet调用的一些Handler在RestServlet中并不会调用
![image](https://user-images.githubusercontent.com/37541919/42307207-485fc802-8064-11e8-8ce7-f886953e2a33.png)

**Comment by WillemJiang** [comment]
感觉是不是可以把 
io.opentracing.contrib.spring.web.interceptor.TracingHandlerInterceptor
https://github.com/opentracing-contrib/java-spring-web/blob/master/opentracing-spring-web/src/main/java/io/opentracing/contrib/spring/web/interceptor/TracingHandlerInterceptor.java#L78
有关异步调用的处理放到ServiceComb的 TracingHandler中来 处理异步线程线程切换所带来的问题。

**Comment by wujimin** [comment]
serviceComb内部，不同的开发模式（透明RPC/JaxRS/springmvc)，不同的传输（highway/vertx-rest/servlet-rest)，同步或reactive都是统一模型处理的  
  
如果使用threadLocal，则会导致reactive或线程池场景时，数据丢失  
处理调用链时，数据应该保存在invocation.context中，这里面的数据，在远程调用时会自动携带，并且不会随着线程调度（切换或异步）而丢失  

当前的trace机制，应该就是按这个思路做的，但是估计场景没做全，导致servlet流程没生效

**Comment by ryphnyuan** [comment]
@wujimin 如果RestServlet能够像DispatcherServlet的doDispath方法中获取HandlerExecutionChain然后调用prehandle\handle\posthandle进入到io.opentracing.contrib.spring.web.interceptor.TracingHandlerInterceptor的话，是否有机会完成调用信息的处理呢？
https://github.com/spring-projects/spring-framework/blob/6887802526dbef2857c4c0106153c0650ec5e4aa/spring-webmvc/src/main/java/org/springframework/web/servlet/DispatcherServlet.java#L1054

**Comment by wujimin** [comment]
fixed by https://issues.apache.org/jira/browse/SCB-859

if still have problems, please raised another issue, thanks.
