### ISSUE TITLE
为什么代码这样写?导致不支持多namespace

### ISSUE THREAD

**Issue by kkrgwbj** [apache/servicecomb-java-chassis#834]
![image](https://user-images.githubusercontent.com/6836934/43074704-c2830572-8eb0-11e8-8da2-5aa5c53abd4c.png)

**Comment by kkrgwbj** [comment]
![image](https://user-images.githubusercontent.com/6836934/43074793-1575c210-8eb1-11e8-8eb5-5f69d159b1bd.png)
这里改成遍历,就支持多个namesapce了.apollo官方是支持多namespace的.

**Comment by wujimin** [comment]
this source code of: org.apache.commons.configuration.AbstractConfiguration#resolveContainerStore
archaius based on this

ServiceComb can not modify them.

**Comment by kkrgwbj** [comment]
apollo官方提供有多namespaces的配置,请问如何在servicecomb中使用?
很多时候我们会抽取一些基础的配置,作为一个单独的namespace来使用.例如:
datasource.property  
mq.property
...
但是servicecomb中无法引入多namespace

**Comment by wujimin** [comment]
i'm sorry for not familiar of multiple namespaces.
and google it just now, it seems for development/product environment and so on, right?

if that's true, maybe can IMPL in org.apache.servicecomb.config.archaius.sources.ApolloConfigurationSourceImpl:
- set namespace to development/product and so on
- based on ServiceComb environment(development/product/...... ), only accept the expect namespace data, and drop others

i'm not sure if it's what your wanted, sorry.

**Comment by kkrgwbj** [comment]
你没有理解我的意思.假如我现在有2个项目.这两个项目  都需要连接数据库.那么我就需要在这两个项目的配置文件中 分别加入 数据库连接的配置信息  很麻烦.
但是如果我可以将数据连接的配置 提取出一个 共有的namespace,如datasource.property 那么我只需要在两个项目中引入这个namespace就行.不需要在每个项目的property里面都分别复制一份了.
这里仅仅是举例了 2个  实际中很可能 数十个..

**Comment by wujimin** [comment]
also should be extend in org.apache.servicecomb.config.archaius.sources.ApolloConfigurationSourceImpl

currently we only process one namespace:
private final String namespace = APOLLO_CONFIG.getNamespace();

change that to multiple namesapces, or get namespaces from remote, and then process them.

Are you interested in implementing this feature? :)

**Comment by kkrgwbj** [comment]
我也是借助你们的项目才知道这个配置中心，之前用的是spring cloud config，有空的话我试试。感觉项目更新的不是很频繁。。不过，非常喜欢你们这种简洁和调用方式，我们现在用的sc相当繁琐，特别是最不爽的就那个feign远程调用。
