### ISSUE TITLE
关于apollo配置中心不支持@ConfigurationProperties

### ISSUE THREAD

**Issue by kkrgwbj** [apache/servicecomb-java-chassis#840]
集成了apollo配置中心后,启动发现无法识别@ConfigurationProperties 导致一些插件初始化报错

**Comment by WillemJiang** [comment]
Could you create a [JIRA](https://issues.apache.org/jira/projects/SCB) with the stack trace information here?

**Comment by kkrgwbj** [comment]
yes

**Comment by kkrgwbj** [comment]
我这边打开那个网址相当慢..根本打不开.

**Comment by kkrgwbj** [comment]
我在这里给你截图吧.
我把mybatis的配置放到apollo里面了.但是启动的时候,sb加载mybatis的配置读取到为空.但是我直接放到项目的配置文件里面就可以.
![image](https://user-images.githubusercontent.com/6836934/43314696-47fc8904-91c6-11e8-83aa-37747df75ea5.png)
![image](https://user-images.githubusercontent.com/6836934/43314708-50581f64-91c6-11e8-8e1d-f504aec344eb.png)

**Comment by kkrgwbj** [comment]
@WillemJiang 我已经提交了.https://issues.apache.org/jira/browse/SCB-781

**Comment by liubao68** [comment]
I submit a PR for this: https://github.com/apache/servicecomb-java-chassis/pull/1069
