### ISSUE TITLE
关于servicecomb 的一些建议

### ISSUE THREAD

**Issue by kkrgwbj** [apache/servicecomb-java-chassis#848]
servicecomb其他方面都挺好.就配置中心不能理解,既然选择了apollo为什么还要在搞个模块在项目里面呢.而且目前的实现还有问题.
apollo本身对spring的兼容性非常好,而且社区也很活跃,为什么不让用户自己选择集成apollo.

实际上,当我引入了apollo官方自己的client去掉了servicecomb-config的依赖后,一切问题都解决了.
包括:
     不支持多namespace
     和sb的一些注解不兼容,导致 初始化无法读取配置信息

**Comment by liubao68** [comment]
你可以列一下ServiceComb集成的具体问题吗？我们分析和优化一下。ServiceComb集成的主要目的是适配Archaius API，因为ServiceComb动态配置都是通过Archaius API来读取的。

当然业务直接使用apollo的client也是可以的，这块只是解决问题的方式不同，并没有矛盾的地方。

**Comment by kkrgwbj** [comment]
1 核心依赖版本低
2不兼容sb2.0,我尝试过升级，启动报错。因为sb2.0的spring是5.x而servicecomb底层依赖spring4.x，5.x有个类删除了，启动报错。
3如果不用servicecomb config单纯用apollo client会不会存在一些问题？

**Comment by liubao68** [comment]
Close old issues, please feel free to open a new one. 

最新 spring boot支持：https://docs.servicecomb.io/java-chassis/zh_CN/using-java-chassis-in-spring-boot/using-java-chassis-in-spring-boot/
配置支持：https://docs.servicecomb.io/java-chassis/zh_CN/config/inject-config/
