### ISSUE TITLE
servicecomb的动态配置模块不支持将microservice.yaml文件中微服务相关配置转移到apollo配置中心进行配置

### ISSUE THREAD

**Issue by chaomeijun** [apache/servicecomb-java-chassis#860]
如题，servicecomb的动态配置模块不支持将microservice.yaml文件中微服务相关配置转移到apollo配置中心进行动态配置，建议支持，当前springcloud中微服务相关配置就可以转移到apollo配置中心进行动态配置

**Comment by zhengyangyong** [comment]
Hi, @chaomeijun ,most configuration in microservice.yaml support dynamic config, but some are not such as endpoint etc...

**Comment by liubao68** [comment]
servicecomb configuration is different configuration principle of spirng cloud. please feel free if you have some questions about how to manage configuration well. I will close this issue. 
configuration docs: https://docs.servicecomb.io/java-chassis/zh_CN/config/general-config.html
