### ISSUE TITLE
Suggestion : multiple rest service endpoint.

### ISSUE THREAD

**Issue by hjianhao** [apache/servicecomb-java-chassis#938]
I think servicecomb need to provide multiple service endpoint for different port.

for example,  I need provide a service for dealing with the requests from internet. In the same time, I also need to provide a service for dealing with the requests from other micro-services in intranet.

For security, authentication and other reason, we had to listen different port to provide two or more services.

We now implement micro-service for internal micro-services, and implement   service for internal using raw vert.x API. we implement a home-made transport.  in the init function, we using vertx instance created by servicecomb to do our own initializations.

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
