### ISSUE TITLE
Suggestion : support calling other rest services.

### ISSUE THREAD

**Issue by hjianhao** [apache/servicecomb-java-chassis#939]
In our project, we need not only calling the micro-service, but also calling othe rest service (Baidu, Google, QQ Music, etc).

Now we had to call these service using vert.x API (reactive mode) or other blocking API ourselves. 

but using these raw API, we can not enjoy the chain handler plugin and can to trace the call using the unified tracing mechanism. 

So I wondering if servicecomb can provide the similar API to call other rest services just like call internal micro-services.

**Comment by liubao68** [comment]
Please check https://docs.servicecomb.io/java-chassis/zh_CN/build-consumer/3rd-party-service-invoke.html  if it can help.

**Comment by liubao68** [comment]
Clear long time not updated issue. Please feel free to submit a new one if problem happended again.
