### ISSUE TITLE
Suggestion : provide executeBlocking mechanism

### ISSUE THREAD

**Issue by hjianhao** [apache/servicecomb-java-chassis#940]
In our project, we using reactive mode to gain high performance in high concurrency scenarios.  But sometimes we had using a few legacy Blocking API. 

So we need to using executor's executeBlocking to running these blocking code. but with this raw vert.x API, blocking code lost the InvocationContext. we need to using ugly wrapper to passing InvocationContext, traceId, etc , just like following : 

public class TraceUtils <T> {
	public static <T> Handler<T> traceable (Handler<T> fromHandler) {
		String traceId = MDC.get(MDC.TRACE_ID_KEY);
		return T -> {
			MDC.put (MDC.TRACE_ID_KEY, traceId);
			fromHandler.handle(T);
		};
	}
}  

If servicecomb provide similar executingBlocking API, and passing the InvocationContext. it would be helpful. we can using InvocationContext the pass the context variable like traceId.

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
