### ISSUE TITLE
Suggestion: provide mechanism to deal with chunked mode and multipart request

### ISSUE THREAD

**Issue by hjianhao** [apache/servicecomb-java-chassis#941]
Now service comb only provide rest api for deal with the whole http request body.

But in some scenarios, save whole body in memory is not an effective way. 

Servicecomb only support using multipart request to upload files but can not process other scenarios.

I hope servicecomb can provide call-back mechanism to deal with chunked message and multipart requests.

for example, see the Amazon Alexa AVS API.

https://developer.amazon.com/zh/docs/alexa-voice-service/structure-http2-request.html

**Comment by hjianhao** [comment]
Additional info, we hope servicecomb can also support chunked response and http/2 frames. In some scenarios, we can't construct a whole response before we send back. For example  : http/2 half-closed down channel stream as link above about alexa AVS API.

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
