### ISSUE TITLE
Suggestion: Ringpop like loadbalance

### ISSUE THREAD

**Issue by hjianhao** [apache/servicecomb-java-chassis#942]
For most scenarios, round-robin load-balance is good enough.

But in our project, sometimes round-robin is not the best choice.

1. every instance of micro-service maintains a data zone by keys. especially using in-memory cache. Using round-robin, every instance may maintains all data.

2. every micro-service may have many instances. Using round-robin, may case m * n connection network.

These scenarios can reference to Uber's Ringpop micro-service model.  

1. Instances of a micro-service construct a consistence hash ring 
2. Each instance maintains a piece of data by specified key.
3. Random select three instance deal with the request from client, so no m * n connections.

**Comment by sirisak1985** [comment]
propasal

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
