### ISSUE TITLE
Suggestion : API for kotlin coroutines

### ISSUE THREAD

**Issue by hjianhao** [apache/servicecomb-java-chassis#943]
Some new project using kotlin as a better Java. kotlin coroutines make none-blocking programing easier.

Vert.x provide coroutines API : https://vertx.io/docs/vertx-lang-kotlin-coroutines/kotlin/

kotlin also provide kotlinx-coroutines-reactive and  kotlinx-coroutines-reactor to integrate with Spring Reactor.

I think Kotlin have great potential in server programming, so you guys may think about provide kotlin coroutine integration in your roadmap. :)

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
