### ISSUE TITLE
serviceComb往serviceCenter注册https服务

### ISSUE THREAD

**Issue by Jwx411845** [apache/servicecomb-java-chassis#955]
按照官方文档配置了SSL配置项
#########SSL options
ssl.protocols: TLSv1.2
ssl.authPeer: true
ssl.checkCN.host: true

#########certificates config
ssl.trustStore: trust.jks
ssl.trustStoreType: JKS
ssl.trustStoreValue: Changeme_123
ssl.keyStore: server.p12
ssl.keyStoreType: PKCS12
ssl.keyStoreValue: Changeme_123
ssl.crl: revoke.crl
ssl.sslCustomClass: org.apache.servicecomb.demo.DemoSSLCustom

使用了我们自己的证书文件，但是在往serviceCenter注册服务的时候报错了，报错提示为:No CRL Data

想请问下各位大神，有人知道这个配置具体的使用方法以及要求吗？

ps:证书信息使用的是我们正在使用的证书，DemoSSLCustom也已经使用了自己实现的类。

**Comment by liubao68** [comment]
Can you show the full error log or give more detail error information?

**Comment by liubao68** [comment]
Clear long time not updated issue. Please feel free to submit a new one if problem happended again.
