### ISSUE TITLE
以后能否不要命名那么长的java文件，好吗？超过git的允许长度了。

### ISSUE THREAD

**Issue by luzheng4qm** [apache/servicecomb-java-chassis#978]
error: lstat("integration-tests/springmvc-tests/springmvc-tests-simplified-mapping-with-springboot/src/test/java/org/apache/servicecomb/demo/springmvc/tests/SpringMvcSpringSimplifiedMappingAnnotationIntegrationTest.java"): Filename too long
fatal: Unable to process path integration-tests/springmvc-tests/springmvc-tests-simplified-mapping-with-springboot/src/test/java/org/apache/servicecomb/demo/springmvc/tests/SpringMvcSpringSimplifiedMappingAnnotationIntegrationTest.java

**Comment by liubao68** [comment]
Can yo provide some steps to produce this error? We are using git too, but not see this error.

**Comment by yhs0092** [comment]
@luzheng4qm   我以前也碰到过这个问题，配上下面这行配置后就好了
```shell
git config --system core.longpaths true
```

**Comment by liubao68** [comment]
Clear long time not updated issue. Please feel free to submit a new one if problem happended again.
