### ISSUE TITLE
RestSchema和RpcSchema里面加个字段描述schema

### ISSUE THREAD

**Issue by msnetc** [apache/servicecomb-java-chassis#979]
现在的RestSchema和RpcSchema只有schemaId, 不能描述清楚这个schema的内容。
我们需要维护一个文档来描述schema包含的功能。
能否在RestSchema和RpcSchema中增加字段，如schemaName, schemaNote等，描述它的内容。

**Comment by wujimin** [comment]
seems you are looking for "title" and "description" of swagger.info?

```
swagger: "2.0"
info:
  description: "description of info for SwaggerAnnotation"
  version: "0.1"
  title: "title of SwaggerAnnotation"
  termsOfService: "termsOfService"
```

**Comment by wujimin** [comment]
any update?

**Comment by liubao68** [comment]
Clear long time not updated issue. Please feel free to submit a new one if problem happended again.
