### ISSUE TITLE
请问现在支持所有的config都放到配置中心了吗？

### ISSUE THREAD

**Issue by kkrgwbj** [apache/servicecomb-java-chassis#982]
以前研究过一段时间了。但是不支持所有配置都可以放到配置中心。请问现在好了吗？

**Comment by liubao68** [comment]
你可以帮忙列举一下具体的配置项吗。 并不是所有配置项都需要动态配置，也不是所有配置项都能动态配置。 讨论具体场景的时候，才具有意义。

**Comment by wpcchengxuyuan** [comment]
在zuul中支持动态filter，在这段时间的了解下，service comb中的handle链是类似其他网关的filter用来做复杂点的业务逻辑拓展。但是好像没办法动态添加handle，除非先在pom文件中添加相应的依赖，在配置中心配置后才会生效。

**Comment by liubao68** [comment]
Handler chain not support change in runtime. 

Clear long time not updated issue. Please feel free to submit a new one if problem happended again.
