### ISSUE TITLE
microservice.yml中如何使用maven变量呢

### ISSUE THREAD

**Issue by SoyMeng** [apache/servicecomb-java-chassis#989]
看有些demo可以使用${spring.application.name}，但是我这边不行？
想要使用pom中的project name与version来管理微服务名称与版本

**Comment by liubao68** [comment]
这个是运行时的变量。通过[配置机制](https://docs.servicecomb.io/java-chassis/zh_CN/general-development/config.html)可以指定值。 理解你的问题是编译时修改值，这个可能需要使用相关的maven插件或者脚本来完成。

**Comment by jeho0815** [comment]
@SoyMeng 你大概搞错了阶段。pom是构建的时候用的，microservice.yaml是运行时用的。除非你构建的时候动态改下microservice.yaml文件里面的内容。你可以尝试使用启动脚本设置环境变量或者-D参数来控制这些变量
