### ISSUE TITLE
Does ServerListFilterExt support to sort by order

### ISSUE THREAD

**Issue by fallblank** [apache/servicecomb-java-chassis#992]
Does ServerListFilterExt support to sort by order？
I found  `getOrder()`  definition in ServerListFilterExt, but it seem never used.
if it support, what behavior it perform？ the smaller  first ?

**Comment by liubao68** [comment]
This smallest first. You can check LoadBalancer for more details on how to load ServerListFilterExt

**Comment by liubao68** [comment]
Clear long time not updated issue. Please feel free to submit a new one if problem happended again.
