### ISSUE TITLE
DynamicSchemaLoader机制废弃的原因？

### ISSUE THREAD

**Issue by fallblank** [apache/servicecomb-java-chassis#998]
出于什么考虑需要把动态schema加载机制废弃掉呢？
在跨语言的微服务调用场景中，比如C/C++，Python等语言实现（实现满足OpenAPI契约）的微服务，通过DynamicSchemaLoader机制，java端直接实现跨语言调用呀。

**Comment by liubao68** [comment]
这个接口的设计初衷不是为你说的场景服务的。而是早期版本功能特性的缺失需要使用这个接口（不支持从服务中心下载接口）。 解决跨语言调用目前也提供了机制，可以参考：https://docs.servicecomb.io/java-chassis/zh_CN/build-consumer/3rd-party-service-invoke.html

**Comment by liubao68** [comment]
Clear long time not updated issue. Please feel free to submit a new one if problem happended again.
